### ISSUE TITLE
[IMPROVE] Integrate stocksera API into stocks/insider/finviz_model.py

### ISSUE THREAD

**Issue by guanquann** [OpenBB-finance/OpenBBTerminal#1300]
I have been scraping Finviz regularly and saving the insider trading records in my own database. The stocksera API gives you access to the historical insider trading data. Both of them will return a panda dataframe.

```
import stocksera

stock = stocksera.Stock()

# Get last n records of insider trading from Finviz
insider_trading_df = stock.insider_trading(limit=2000)

# Get analysis of last 1 month insider trading summary from Finviz
latest_insider_trading_summary_df = stock.latest_insider_trading_summary()
```

Not sure how useful will it be, but here is the documentation to the api I have currently. https://github.com/guanquann/Stocksera-API

**Comment by DidierRLopes** [comment]
Hi @guanquann ,

Thanks for reaching out! Impressive work with Stocksera btw!

Our team will have a peek at how we can use this data on the terminal, thank you 😄 

@jmaslek @JerBouma @deeleeramone

**Comment by deeleeramone** [comment]
Would love to have the historical borrow costs ported in!
