### ISSUE TITLE
[Bug] Stocks/Candle: Compact Date Needs To Display Year When Period > 1 year. Other Inconsistent Details

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1493]
Compact Date Needs To Display Year When Period > 1 year. Displaying the time under these circumstances does not provide any value or function to the user and also wastes valuable screen space.

<img width="1299" alt="Screen Shot 2022-03-15 at 4 02 38 PM" src="https://user-images.githubusercontent.com/85772166/158486362-100482de-54c1-4551-9e20-9cf6e9c54bae.png">

When compared to the chart produced by /stocks/ca/historical - the size of the chart is different, and the date is formatted in a different way.

<img width="1150" alt="Screen Shot 2022-03-15 at 4 13 15 PM" src="https://user-images.githubusercontent.com/85772166/158487320-28318871-5adf-461e-b3e9-7d2c95467b0a.png">

With /stocks/ca/volume - The scale is labeled with [M] for millions. With candle, this same scale is labeled with scientific notation. [K], [M], [B] is preferred. 

<img width="1150" alt="Screen Shot 2022-03-15 at 4 15 53 PM" src="https://user-images.githubusercontent.com/85772166/158487565-3e84a192-6d8b-4ad2-a8f6-cd56b04ac008.png">

**Comment by minhhoang1023** [comment]
@deeleeramone Tested this and the datetime format was already fixed. I created the PR to address the magnitude ticker label & remove scientific notations #1565

**Comment by minhhoang1023** [comment]
For the plot scale, both charts are set to auto-scale at the moment. @piiq would you say it's because of mpf - as we are using the package to plot the first one and not the second one
