### ISSUE TITLE
[Bug] Reports: Some images are failing to render. econ_data report does not render any.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1516]
Images are not rendering in some reports: econ_data fails to render any image. 

<img width="487" alt="Screen Shot 2022-03-18 at 8 54 54 AM" src="https://user-images.githubusercontent.com/85772166/159037753-ffbd3dfc-1dfd-4941-a98c-e6d6c842171f.png">

**Comment by jmaslek** [comment]
<img width="1303" alt="Screen Shot 2022-03-19 at 1 07 38 PM" src="https://user-images.githubusercontent.com/18151143/159131087-b52a13eb-5a34-41ac-a95b-7b62c799d20d.png">

I am getting all the images?

**Comment by deeleeramone** [comment]
It seems to work when opened as a Jupyter Notebook, but when it is launched from the terminal via /jupyter/reports/ it does not render. Perhaps this is because it is not launching via Voila?

**Comment by piiq** [comment]
Just tested report generation on the latest main an it seems to work. The only thing that caught my eye is that the similar_analysis report notebook generates errors in a few cells and produces tables like this
<img width="869" alt="image" src="https://user-images.githubusercontent.com/11668535/161956430-48b8c552-9953-4942-bb24-03b60d474b70.png">
