### ISSUE TITLE
[IMPROVEMENT] Add jupyter support fro packaged apps

### ISSUE THREAD

**Issue by andrewkenreich** [OpenBB-finance/OpenBBTerminal#1521]
It started with a number of bugs:

# 1. textwrap3 pyinstaller support

**Describe the bug**
When running .exe textwrap3 is also required...this is brought in by ansiwrap. 

**To Reproduce**
Run .exe file from windows or Mac and try to run Jupyter reports- requires textwrap3 

https://github.com/jrnl-org/jrnl/issues/1191
https://github.com/jonathaneunice/ansiwrap/blob/master/ansiwrap/core.py

The repo for ansiwrap hasn't been updated in a long time and it looks like we only used it before Rich was implemented. I don't think it's actually required now. I did a quick search and it looks like its only used in the logging to strip color from one line in paper mill

Line where it is used is listed below in ansiwrap/core.py - and they bring in this textwrap3 then.

```
# import a copy of textwrap3 which we will viciously monkey-patch
# to use our version of len, not the built-in
import os
a_textwrap = imp.load_module('a_textwrap', *imp.find_module('textwrap3")
```

I think worst case we could just delete this import...it's only required for python <3.6

# 2. Launching jupyter lab and voila in subprocess

At the moment the lab and voila are launched using subprocess what doesn't work in packaged apps.

**Comment by Chavithra** [comment]
Adding it on the list of improvements for next major version.
