### ISSUE TITLE
[Bug] /economy/plot - Treasury does not plot on -y1 overlaying with fred mortgage rate data. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1573]
The example I was attempting to make was a chart of 30-year Treasuries and Mortgage Rates on 1 axis, and the price of oil, or sp500 etc, on the second axis.  Is stored data from the treasury command expressed as a %?

![Screen Shot 2022-03-28 at 2 56 33 PM](https://user-images.githubusercontent.com/85772166/160493933-9cb22e28-b0db-49e0-bcb3-53ddb7dc487f.png)

![Screen Shot 2022-03-28 at 3 00 34 PM](https://user-images.githubusercontent.com/85772166/160494449-aaf8924d-69dd-490b-9f11-5be0a2b1ad9f.png)

![Screen Shot 2022-03-28 at 3 01 24 PM](https://user-images.githubusercontent.com/85772166/160494552-c33bb9d7-19ba-450b-a088-81d6bdc65cbd.png)

**Comment by deeleeramone** [comment]
```
                                   Options available to plot                                    
┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Command  ┃ Options                                                                           ┃
┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ fred     │ MORTGAGE30US, MORTGAGE15US                                                        │
├──────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ treasury │ Nominal_3-month, Nominal_2-year, Nominal_5-year, Nominal_10-year, Nominal_30-year │
├──────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ index    │ sp500                                                                             │
└──────────┴───────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by LBolte29** [comment]
@deeleeramone
Could you put the exact sequence of commands necessary to reproduce this?

**Comment by deeleeramone** [comment]
This issue has now been resolved, but was not linked to the PR that resolved it.

![image](https://user-images.githubusercontent.com/85772166/161699272-301bfe16-5ec1-4f59-a470-1f4746a47896.png)
