### ISSUE TITLE
[Bug] crypto/ov/cgproducts - Error: Incorrect path.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1576]
crypto/ov/cgproducts
```
Error: {'error': 'Incorrect path. Please check https://www.coingecko.com/api/'}

Error: 'list' object has no attribute 'empty'
```

The same error occurs for: crypto/ov/cgplatforms

**Comment by hunttom** [comment]
It looks like the `cgplatforms` and `cgproducts` is no longer supported and should be removed from the tool.

https://www.coingecko.com/en/api/documentation?

**Comment by jose-donato** [comment]
> It looks like the `cgplatforms` and `cgproducts` is no longer supported and should be removed from the tool.
> 
> https://www.coingecko.com/en/api/documentation?

Yes you are right. thanks for pointing this out. @minhhoang1023 do you know any alternative? 
I know [defirate](https://defirate.com/api/) but i don't think they have a public api yet

**Comment by minhhoang1023** [comment]
> It looks like the `cgplatforms` and `cgproducts` is no longer supported and should be removed from the tool.

Closest one I know is CMC category endpoints (https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyCategories) but it does not have L1 category. 

We can disable this for now, and add it back once come across another source. Wdyt?

**Comment by jose-donato** [comment]
[https://loanscan.io/](https://loanscan.io/)

Loanscan provides great info for this! Will replace with that :)
