### ISSUE TITLE
[Bug] crypto/headlines lacks legends & y-axis label

### ISSUE THREAD

**Issue by minhhoang1023** [OpenBB-finance/OpenBBTerminal#1577]
**Describe the bug**
Legends on the plot & y-axis label are missing. It's not clear the unit of the labels neither.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/40023817/160546814-f6305ce7-f024-4918-815f-f241932c9203.png">

The same goes for raw data:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/40023817/160547016-afef36bb-7e59-4e99-9b07-3a8154e2f11e.png">

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by piiq** [comment]
resolved by #1903
