### ISSUE TITLE
[Bug] stocks/disc/divcal freezes the terminal

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBBTerminal#1583]
**Describe the bug**
`stocks/disc/divcal -l 2` freezes the terminal

**To Reproduce**
`stocks/disc/divcal -l 2`

**Desktop (please complete the following information):**

- OS: macOS 12
- Python version: 3.8

**Comment by Chavithra** [comment]
Looks like it doesn't freeze on :
- OS : Windows
- Python version : 3.8

**Comment by minhhoang1023** [comment]
Tested on my side and it worked fine.

OS : MacOs
Python version : 3.9

**Comment by Chavithra** [comment]
Do you still have the issue ?

**Comment by piiq** [comment]
not anymore, but I need to check in a packaged app. I'll close the issue if it works in the package

**Comment by piiq** [comment]
Yep. The issue is still there. The request freezes. I've added a timeout to bypass it, but will debug a bit further
<img width="761" alt="image" src="https://user-images.githubusercontent.com/11668535/161927409-d199fbd2-6030-4706-b953-e0aeb27bc808.png">

**Comment by piiq** [comment]
There are some settings on nasdaq's side that make this thing appear for users who might have some non-conventional network configuration. 
The url works from the browser because the browser supplies nasdaqs cookie. It doesn't work with curl, but depending on the network configuration the response can be a timeout or a 200 with a 403 text message. It works from pythons requests depending on both network configuration and the supplied user agent.

To fix the integration tests I will add a timeout to the request and a todo in the code to investigate this command later on
