### ISSUE TITLE
About to Mac OS version.

### ISSUE THREAD

**Issue by anarchy89** [OpenBB-finance/OpenBBTerminal#1605]
Hi, is the Mac OS installer meant for Intel macs or m1 macs? 

Do you have plans to support both?

**Comment by Chavithra** [comment]
Yes the installer should work on both `intel` and `m1` macs.

**Comment by DidierRLopes** [comment]
Closing this :)

**Comment by anarchy89** [comment]
What about natively? Does it use Rosetta or isit native apple silicon?
