### ISSUE TITLE
[FR] Proposal: add charm.sh to make it a real terminal

### ISSUE THREAD

**Issue by chris-aeviator** [OpenBB-finance/OpenBBTerminal#1612]
This is just a sidenote and not to be taken too seriously as a feature request. I wanted to make you aware of https://charm.sh/ , a rich TUI framework(s) including backend servers. Their tools allow to have outside users connect and authenticate passwordless with SSH, from a hosting perspective this would be one of the lowest possible barriers, since even a low-bandwith user with a 5$ raspberry pi and a cheap display could use it on a 2G connection.

![grafik](https://user-images.githubusercontent.com/11522213/161378790-16124a8b-d191-4ea6-a48b-6264752d48ed.png)

**Comment by DidierRLopes** [comment]
I have a call with @toby this week to discuss this! 

Also like what @willmcgugan is doing with [Textualize](https://github.com/Textualize/textual).

Regarding the RaspberryPy, @Zedris was actually able to put our terminal running on his RaspberryPi. The #1 ever person to do that!

**Comment by Zedris** [comment]
if we can get something to render the graphs(roughly) within the terminal and not require x11 the pi could run just headless and guiless fully which would be awesome!

**Comment by CoconutMacaroon** [comment]
I've been working on a web UI for this, so check that out as well. However, I've been stuck on getting graphs working as my upstream libraries don't support it. See  #1251 and https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/openbb_terminal_web

**Comment by chris-aeviator** [comment]
> if we can get something to render the graphs(roughly) within the terminal and not require x11 the pi could run just headless and guiless fully which would be awesome!

There are some graph libs out there - here’s a nice high freq graph (though not a lib)

https://github.com/dashersw/brain-monitor
