### ISSUE TITLE
[Bug] Cannot load Coinbase portfolio

### ISSUE THREAD

**Issue by marcelonyc** [OpenBB-finance/OpenBBTerminal#1624]
**Describe the bug**
When trying to load a Coinbase portfolio an error occurs. The error indicates an authentication issue, but it is not. The error happens when attempting to get a price on an invalid pair (USD-USD or XRP-USD) The response array contains all the currencies in a portfolio. The code tries to get a price for <CRYPTO>-<CURRENCY>

**: CoinbaseApiException: Invalid Authentication: {"message":"NotFound"}**

**Error: 'list' object has no attribute 'empty'**

**To Reproduce**
NOTE: This requires that you set up your Coinbase Pro API key and secret
At the terminal:
portfolio
bro
cb
account

**Desktop (please complete the following information):**

- OS: Windows wsl2
- Python version 3.8

**Additional context**
Error occurs on coinbase_model.py:79 When to_get == "USD-USD"
`make_coinbase_request(f"/products/{to_get}/stats", auth=auth)`

To validate this, I tested with the following changes and I was able to load my portfolio
1. coinbase_model.py:75
`    for index, row in df.iterrows():
`
2. Add after coinbase_model.py:76
`
            if to_get in { "USD-USD", "XRP-USD" }:
                df.drop(index,inplace=True)
                continue
`

The drop is needed otherwise this line fails coinbase_model.py:85
`        df["current_price"] = current_prices
`

**Comment by minhhoang1023** [comment]
@marcelonyc Nice catch! Do you want to create a PR for this and we'll review and get it merged? :D

**Comment by marcelonyc** [comment]
@minhhoang1023 I will work on a fix a create a PR later today.
