### ISSUE TITLE
[Bug] /stocks/options/ $ oi Error: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1626]
```
/stocks/options/load ^RUT --source yf//exp 1/oi
```

```
2022 Apr 03, 19:09 (🦋) /stocks/options/ $ oi
Error: 'NoneType' object is not subscriptable
```

I edited this issues to keep relevant bug. The other will be solved when https://github.com/OpenBB-finance/OpenBBTerminal/pull/1613 is merged.

**Comment by deeleeramone** [comment]
Entering a wrong command can also lead to printing the logging error message. Can we silence this?

**Comment by DidierRLopes** [comment]
> Entering a wrong command can also lead to printing the logging error message. Can we silence this?

I had the same issue. This is because your top folder is using still "GamestonkTerminal" and logging was expecting OpenBBTerminal.

This has already been fixed. Pull the latest changes and let me know if it works

**Comment by deeleeramone** [comment]
That makes no difference. The error message is because of Tradier returning no results, and it also occurs when you enter a command wrong.

**Comment by DidierRLopes** [comment]
> That makes no difference. The error message is because of Tradier returning no results, and it also occurs when you enter a command wrong.
> […](#)

Rename GamestonkTerminal to OpenBBTerminal and let me know if it didn't work.

There's an issue with Tradier, but the big log of data is not due to that, it's due to the name of the folder

**Comment by deeleeramone** [comment]
That did work! I suppose this can be closed now! 

Was I under the correct assumption that the “fix”, deployed for people not renaming the folder to OpenBB, would mean not having to rename the folder?

**Comment by Chavithra** [comment]
@deeleeramone the current main should handle any folder name now.
