### ISSUE TITLE
[FR] Add Matrix integration

### ISSUE THREAD

**Issue by sbstn87** [OpenBB-finance/OpenBBTerminal#1629]
**What's the problem of not having this feature?**
No open and decentralized communication protocol.

**Describe the solution you would like**
Add chat integration for the Matrix protocol.

**Describe alternatives you've considered**
Already present Slack, etc. integrations.

**Additional information**
See:
https://matrix.org/
https://element.io/

**Comment by bolshoytoster** [comment]
@sbstn87 do you mean adding a chat feature/submenu?

If so, I'd be happy to try adding this.

**Comment by sbstn87** [comment]
Yes, like the Bloomberg chat, but using matrix protocol. There is a Python based matrix client, so it could be perhaps somehow integrated:
https://matrix.org/docs/projects/client/weechat-matrix

It is TUI client, so it fits the Terminal.

**Comment by the-praxs** [comment]
Commenting here to remind myself that this is what I am working on (early pre-alpha stage).
