### ISSUE TITLE
[FR] New and improved prediction techniques (DARTS)

### ISSUE THREAD

**Issue by marvision-ai** [OpenBB-finance/OpenBBTerminal#1631]
I was playing around with: https://github.com/unit8co/darts

They provide a very simple interface to use the latest models with super simple install.

Features to potentially include to the terminal: 
- Testing predictions using past/future covariates
- Training a large NBEATs model on all times series to provide out of the box prediction 
    - Multivariable prediction - could help predict price based on more than just ticker price
- Probabilistic forecasting 

Just some thoughts :smile:

**Comment by DidierRLopes** [comment]
Using an open-source library to help on our ML/AI side, would definitely be very helpful. At least for our full-blown prediction menu. @hrzn thoughts? 

unit8 [🤝](https://emojipedia.org/handshake/) OpenBB?

**Comment by hrzn** [comment]
Hey, what you guys are building looks very nice. I'd be happy to understand if/how Darts could help.

**Comment by DidierRLopes** [comment]
Yes,

So our focus is in making investment research effective, powerful and accessible. For that, an important part is to connect users to data, so we act as a bridge between data sources and users. We have both raw data data (e.g. tweets) or processed data (e.g. estimated sentiment from those tweets).

We want our users to be able to extract their own insights from the terminal, including using ML/AI on the data available. Thus we have a "prediction menu" where users can predict any time-series price (from stocks, crypto or even economic), see:
<img width="916" alt="Screenshot 2022-04-04 at 17 47 04" src="https://user-images.githubusercontent.com/25267873/161592441-cfb310a6-d6e8-404e-beb2-11555c19f40a.png">

However, this was something that was done last year, and the team has not had time to further delve on this, and is still very primitive as it only uses historical data. But I want these models to be using different time-series as inputs, and this is something I believe Dart supports.

Also, we are recruiting a ML Engineer to work on this area, so supporting Dart could be a path forward. 

Let me know if you want to schedule a call to discuss this. 

PS: [We just raised $8.5M](https://venturebeat.com/2022/03/30/openbb-wants-to-be-an-open-source-challenger-to-bloomberg-terminal/), so the project won't go anywhere :)

**Comment by hrzn** [comment]
OK I see, at first sight it looks like Darts might indeed be able to help. A couple of things it provides (for ML-based models) are:
* Ability to train on multiple time series, which don't need to have the same time axis.
* Each of the individual time series may be multi-dimensional.
* In addition, it is possible to specify "covariates" known either only into the past (past_covariates) or also into the future (future_covariates).
* Some of the models (and all deep learning models) can provide different kinds of probabilistic forecasts.

I try to give an overview of some of these features in the 2nd half of the video here: https://youtu.be/g6OXDnXEtFA?t=894

We can schedule a call sometime in the coming days to discuss more. You can contact me at: <my_firstname> <at> unit8.co.

**Comment by DidierRLopes** [comment]
Hi @marvision-ai !

Yes, we actually will later this week start reviewing applications, so if you can send your CV across that would be great. [Here's the job posting](https://jobs.lever.co/openbb/050e5d79-a883-46b0-a497-0ea1fb655f67). 

On your CV please write that you have experience with other open-source libraries (darts, hugging face, ...), that is great!

Thanks @hrzn for this summary. Yup, as @marvision-ai brought up. Relying on your models would make a lot of sense from our end. 

FYI @jmaslek

**Comment by DidierRLopes** [comment]
#1851 👀 

Closing this because this is in the roadmap
