### ISSUE TITLE
[Bug] Hugo Site has white space at the bottom

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#1636]
**Describe the bug**
The hugo site has whitespace at the bottom.

**To Reproduce**
Go to the url: https://openbb-finance.github.io/OpenBBTerminal/terminal/

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://files.slack.com/files-pri/T02KN1WM94J-F03A034ND42/screen_shot_2022-04-04_at_11.55.07_am.png)

**Desktop (please complete the following information):**
16" Mac Book Pro

**Additional context**
Running Chrome

**Comment by bolshoytoster** [comment]
@colin99d interestingly, it only appears sometimes (for me at least). I can reliably recreate it by clicking on one of the links on the left then going back (left arrow in browser).

I tried to check the difference between a normal version and the one with the space at the bottom and it looks to be just whitespace:
```diff
$ diff 1.html 2.html
1a2,10
>             
>         
> 
>         
>         
>     
> 
>         
>     
```

**Comment by alexferrari88** [comment]
@colin99d  the screenshot provided requires login to view. Can you please post it on something open (e.g. imgur) ?

Also, I cannot see any excessive whitespace at the bottom, could it be that the problem is now solved? Can you please double check? Thank you!

**Comment by jose-donato** [comment]
> @colin99d the screenshot provided requires login to view. Can you please post it on something open (e.g. imgur) ?
> 
> Also, I cannot see any excessive whitespace at the bottom, could it be that the problem is now solved? Can you please double check? Thank you!

Hey, i remember debugging this a while ago and iirc it happens when the device display is bigger than a small laptop and when the device system has light mode defined on system settings
