### ISSUE TITLE
pandas-market-calendars required but not in requirements.txt

### ISSUE THREAD

**Issue by hurricane-dorian** [OpenBB-finance/OpenBBTerminal#1638]
pandas-market-calendars is required to run terminal.py
It is in requirements-full.txt but not in requirements.txt

I just used pip install -r requirements.txt in Linux instead of using anaconda

**Comment by piiq** [comment]
Hey @hurricane-dorian 

Have you tried using `poetry` for dependency management? We've adopted poetry for this project and everyone seems to like it.

In the project root in your venv (or other python environment) you can do:

```bash
pip install poetry
poetry install
```
and poetry will install all the requirements from the .lock file.

The requirements.txt that are in the repo might be lagging behind poetry.lock a bit

**Comment by piiq** [comment]
> In poetry.lock "pandas-market-calendars" is marked as a dev package but it is required to run

That's a good catch! Thanks a lot. This issue will be closed once the PR is merged
