### ISSUE TITLE
[Bug] Reddit API Keys: Only 4/5 Inputs Are Sent To .env

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1645]
[Bug] Reddit API Keys: Only 4/5 Inputs Are Sent To .env

![image](https://user-images.githubusercontent.com/85772166/161874127-4f0f3ce4-6832-411c-b6af-c5685713b590.png)

This results in the wrong fields being populated by input. For example,
```
OPENBB_API_REDDIT_PASSWORD='Danglewood69420'
```
This is my username. To remedy this, I edited the .env file to add this line: 

```
OPENBB_API_REDDIT_USERNAME='Danglewood69420'
```
Then re-arranged the incorrectly populated fields.

The result was a Key that passes tests and is correctly recalled when restarting the terminal.

**Comment by deeleeramone** [comment]
the following message is printed when using the command: /stocks/ba/wsb

```
/Users/danglewood/GitHub/GST1/miniconda3/envs/gst/lib/python3.8/site-packages/psaw/PushshiftAPI.py:244: UserWarning: Not all PushShift shards are active. Query results may be incomplete
  warnings.warn(shards_down_message)
```

This does not prevent the terminal from returning results.

**Comment by salvadorgarcia23** [comment]
Attempted the procedure above with little success. 

OS: Windows 10 
Application: OpenBB Terminal 
Installation Method: https://github.com/OpenBB-finance/OpenBBTerminal/releases/tag/v1.0.0 downloaded Windows setup.exe 
Problem: Cannot connect Reddit API 
Error: defined, test failed 

As mentioned by deeleeramone, when attempting to enter variables using terminal command: /keys/reddit -i [Client ID] -s [Client Secret] -u [Username] -p [Password] -a [User Agent], the .env file is erroneously entering in the information in the improper fields. 

As an example: 
OPENBB_API_REDDIT_CLIENT_ID is being defined by whatever variable is entered in for:  -p

Below is a list of the rest of the variables (Some are correct) 
OPENBB_API_REDDIT_CLIENT_SECRET is being defined by whatever variable is entered in for -s
OPENBB_API_REDDIT_PASSWORD is being defined by whatever variable is entered in for -u
OPENBB_API_REDDIT_USER_AGENT is being defined by whatever variable is entered in for -a 
-i is completely missing from the equation. (It is not found in the .env when entered as a variable within terminal) 

Additionally, when viewing the .env, it seems like there are lines that are out of order / missing.

**Comment by Chavithra** [comment]
@deeleeramone @salvadorgarcia23 Thanks for your feedback !
