### ISSUE TITLE
[Bug] Discord bot crawled image is croped

### ISSUE THREAD

**Issue by jadru** [OpenBB-finance/OpenBBTerminal#1648]
**Describe the bug**
Discord bot crawled images is croped to the small size.

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
in discord
![image](https://user-images.githubusercontent.com/21021930/161930553-3fec5e21-6500-40a8-a64d-c9b790a3553e.png)
"/dd pt tsla"

**Screenshots**
![image](https://user-images.githubusercontent.com/21021930/161930996-bb9faeee-63d6-4d8e-b7f0-baab69b4916c.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Python version: is not about PY.

**Additional context**
Add any other information that you think could be useful for us.

**Comment by tehcoderer** [comment]
Thank you @jadru! Fixed it that night 😂
