### ISSUE TITLE
[Bug] upcoming earnings release dates

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#1689]
After watching [this video](https://www.youtube.com/watch?v=hioOaYMctxo&ab_channel=ObjectiveTrade) I noticed that the upcoming earnings shows the earnings happening on the date EVEN if the market is already closed. 

I think the upcoming earnings release date should have the earnings on the day ONLY if the market is not yet open, otherwise it should have for the next trading day.

**Comment by jmaslek** [comment]
Earnings can happen after market close.

**Comment by LBolte29** [comment]
mhmmm, so I checked now and this makes sense (despite duplicated)

![image](https://user-images.githubusercontent.com/97528701/163572341-925c75a1-66c8-4112-8c12-f244c1ec508b.png)

![image](https://user-images.githubusercontent.com/97528701/163572282-ffbe4692-1fd3-4d59-bf04-8ced5236f132.png)

**Comment by jmaslek** [comment]
Is it possible to grab the other columns?
