### ISSUE TITLE
[Bug] Mutual funds search fail

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#1690]
<img width="1610" alt="Screenshot 2022-04-11 at 11 07 38" src="https://user-images.githubusercontent.com/25267873/162716313-b4d69f60-fde7-4018-bedd-633ac23da64b.png">

This is from [this video](https://www.youtube.com/watch?v=hioOaYMctxo&ab_channel=ObjectiveTrade) minute 13.

**Comment by jmaslek** [comment]
invesco:
<img width="965" alt="Screen Shot 2022-04-11 at 10 51 10 AM" src="https://user-images.githubusercontent.com/18151143/162766513-07444804-a746-4b10-8711-4b488603485a.png">

fidelity:
<img width="1157" alt="Screen Shot 2022-04-11 at 10 50 15 AM" src="https://user-images.githubusercontent.com/18151143/162766583-865493fb-5eac-4c41-8764-c3f9045afa72.png">

**Comment by LBolte29** [comment]
I get the same result as James! Will close this

**Comment by jmaslek** [comment]
Any chance this is related to being used on installer?
