### ISSUE TITLE
UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.

### ISSUE THREAD

**Issue by chrisco23** [OpenBB-finance/OpenBBTerminal#1692]
I'm wanting to run the docker install.  Everything looks good so far except I cannot get any display windows, plots etc.

Any time I try to plot ("pt") I get no window.

Maybe I'm misunderstanding something in the way docker should handle the DISPLAY.

I'm on Arch Linux, running i3 WM.  I've googled the error msg and tried everything I found and everything I can think of, but I'm still stuck with no display showing and the message "UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure."

Any suggestions?
TIA.

**Comment by piiq** [comment]
Hi Chris 👋

The idea is to use X11 to forward the window from the container to the host machine. i3 should support this stuff out of the box, but nobody on the team actually uses i3 to test it out.

The way the `DISPLAY` address can be obtained is briefly covered here https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/DOCKER_ADVANCED.md , have you seen it?

**Comment by chrisco23** [comment]
Yes I was working with that section.  When I run that IP with ifconfig command, I get an IP of "172.20.0.1 172.18.0.1 172.17.0.1 192.168.4.38"  (4 ips).  These correspond to "br-980f6a71cb25", "br-ccc839453fa3", "docker0" and "wlan0".  Which should DISPLAY be set to?  As it the value of $IP that arises should surely not be telling DISPLAY to be all 4...

**Comment by piiq** [comment]
I would go for the `192.168.4.38:0` but I can't rationalize my choice 😂

Can you test different ones by passing them as environment variable on container launch?

**Comment by chrisco23** [comment]
Yes I've now tried all 4, but I still get the "/home/python/openbb_terminal/menu.py:16: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure."

btw, I'm trying like this: 

`$ docker run -it --rm --env-file=.env -e DISPLAY=$IP:0 ghcr.io/openbb-finance/openbbterminal-poetry:latest`

...because if I try it as it's documented, I get

```
$ docker run -it --rm --env-file=.env -e DISPLAY=$IP:0 ghcr.io/OpenBBTerminal/gst-poetry:latest
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
```

Am I doing that wrong?  The former at least runs the terminal, only problem seems to be having the docker display the plot etc. windows to my display.

**Comment by chrisco23** [comment]
To clarify, when I am running that first command, I am first doing

export IP=192.168.4.38 # or any other of the 4 IPs

**Comment by chrisco23** [comment]
I don't know if this is a part of my solution or not, but I found that the first snippet of the first answer here:  https://stackoverflow.com/questions/3285193/how-to-change-backends-in-matplotlib-python

It made me add parentheses to the print statements, and I added "Agg" to the list, but I got this:

```
$ python test.py
testing Agg
testing TKAgg
testing GTKAgg
testing Qt4Agg
testing WXAgg
Using: QtAgg
Traceback (most recent call last):
  File "/home/mylinuxuser/test.py", line 13, in <module>
    Using: GTKAgg
NameError: name 'GTKAgg' is not defined
```
Even if I can use this GTKAgg (or add TkAgg as I've seen suggested elsewhere), I'm not clear how to change the import matplotlib when I'm pulling down the docker image.  I've used docker some but not quite in this way.

**Comment by piiq** [comment]
I see the same behaviour on an ubuntu machine locally. I don't think that it's related to the matplotlib backend, but rather the x11 connectivity. I'll need to look further into it to figure out what's going on. Sorry, no quick fix for now 🤷‍♂️

**Comment by piiq** [comment]
It does work on a mac with XQuartz

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/11668535/163455950-c077147c-88bb-450b-bff6-9a3db215c7c7.png">

I run `docker run -it --rm -e DISPLAY=host.docker.internal:0 ghcr.io/openbb-finance/openbbterminal-poetry`

**Comment by chrisco23** [comment]
Hmm.  Might it be possible to use something like that little snippet above that tests for available backends first and then uses whatever is available?

I've been through every first-page google-result on the error and tried all the things suggested.  Many times the suggestions are geared more towards Ubuntu than Arch, so for example it will be recommended to "pip apt-get install python3-tk" (Ubuntu) but I have installed tk for Arch.  And anyway I think it would hit the same problem.

Farther down on this page:  https://stackoverflow.com/questions/56656777/userwarning-matplotlib-is-currently-using-agg-which-is-a-non-gui-backend-so  It's suggested to just comment out "matplotlib.use('Agg')"...

I'm just not sure how to test.  How can I modify the code that is being pulled down on the fly?

**Comment by piiq** [comment]
To explicitly specify a backend you can set the `OPENBB_BACKEND` environment variable to the value that you would otherwise want to pass into `matplotlib.use`. It will be handled in `config_plot.py`
<img width="733" alt="image" src="https://user-images.githubusercontent.com/11668535/163480809-a83cea40-f417-44aa-91df-4d881a0ea75f.png">


Regarding installation of packages that are potentially missing - there is some tkinter library being pulled by the container chain
https://github.com/OpenBB-finance/OpenBBTerminal/blob/a12e0946da4d85baa6590eb2a06cd440b42734a5/docker/openbbterminal-python.dockerfile#L24
So at first I would probably try to add some Qt for Python related library into the container and change the backend to `Qt5Agg`. I would first test `pyside2` and if it fails fall back to `pyqt5`

**Comment by chrisco23** [comment]
Thanks.

My really stupid question though is about docker.  I've used docker but
I've never run it in quite this way where it is referring to the openBB via
URL.  I don't actually know how to get at the openBB code when running this
way.(?)

**Comment by dreamerc** [comment]
Hi,

I also have the same problem at Ubuntu 21.10 Desktop, but fix it with the script.

run.sh :
```bash
docker pull ghcr.io/openbb-finance/openbbterminal-poetry:latest
xhost +local:
docker run -it --rm --name openbb --env-file=./setenv -e DISPLAY=$DISPLAY -v/tmp/.X11-unix:/tmp/.X11-unix ghcr.io/openbb-finance/openbbterminal-poetry:latest
xhost -local:
```

setenv :
```
OPENBB_BACKEND=Qt5Agg
```

Hope it can help you.

**Comment by chrisco23** [comment]
Thanks dreamerc!  This absolutely seems to work for me.

For whatever reason I didn't even need to change setenv but maybe that had to do with something else I was doing, installing tk, something like that.

**Comment by vezeli** [comment]
Had the same problem on Ubuntu 18.04. @dreamerc solution solved the issue. Thanks so much!

**Comment by DidierRLopes** [comment]
> Hi,
> 
> I also have the same problem at Ubuntu 21.10 Desktop, but fix it with the script.
> 
> run.sh :
> 
> ```shell
> docker pull ghcr.io/openbb-finance/openbbterminal-poetry:latest
> xhost +local:
> docker run -it --rm --name openbb --env-file=./setenv -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ghcr.io/openbb-finance/openbbterminal-poetry:latest
> xhost -local:
> ```
> 
> setenv :
> 
> ```
> OPENBB_BACKEND=Qt5Agg
> ```
> 
> Hope it can help you.

@piiq should we add this solution to our README? Installation guidelines? For Ubuntu users?

**Comment by piiq** [comment]
I don't fully understand what was the issue here and what resolved.
From the comments it seems that explicitly specifying the Qt5Agg backend helps linux users who for some reason don't have Tk on their systems. Am i right?

**Comment by dreamerc** [comment]
This script takes X-Window Client (in the Guest Docker) to the Host Desktop.
In DOCKER_ADVANCED.md , I tested , but not work.
Then I found the easy way.
Using UNIX domain socket (,IPC Socket) to /tmp/.X11-unix , not Network Socket.
Recently the Docker changed the security protection, and early version in 2020 might work with the old solution.

**Comment by piiq** [comment]
thanks for pointing it out @dreamerc 
are you open to creating a PR that updates the DOCKER_ADVANCED.md?
