### ISSUE TITLE
[IMPROVE] asynchronous http request

### ISSUE THREAD

**Issue by PzaThief** [OpenBB-finance/OpenBBTerminal#1694]
**What's the feature that should be improved?**
In case of alternative.oss.github_model.get_stars_history function, function calls requests n-times. so there are huge waiting time for waiting response by page size.

**Describe how you would like the feature improved**
It needs to be change to non-blocking async requests. then we can gather all pages at once in 1 page wating time + overhead.
The more pages. the more faster

**Possibly describe the ideal way to improve this**
find loop requests and change to use aiohttp or asyncio run_in_executor(in case of keeping backward compatibility)

**Comment by alexferrari88** [comment]
are you already working on this @jose-donato ?

**Comment by jose-donato** [comment]
Hey @alexferrari88 
No, not yet 😄

**Comment by alexferrari88** [comment]
@jose-donato please reach out if you need any help!

**Comment by jose-donato** [comment]
> @jose-donato please reach out if you need any help!

if you want to take over go ahead 🙌

**Comment by alexferrari88** [comment]
I was wrongly assuming that the project was already using asyncio! Unfortunately I don't have the capacity at the moment to embark in such a big task!

**Comment by alexferrari88** [comment]
on the other hand, we could also make async only github_view...

**Comment by alexferrari88** [comment]
example:

oss_controller.py
`python
    def call_sh(self, other_args: List[str]):
        """Process sh command"""
        parser = argparse.ArgumentParser(
            add_help=False,
            formatter_class=argparse.ArgumentDefaultsHelpFormatter,
            prog="sh",
            description="Display a repo star history [Source: https://api.github.com]",
        )
        parser.add_argument(
            "-r",
            "--repo",
            type=str,
            required="-h" not in other_args,
            dest="repo",
            help="Repository to search for star history. Format: org/repo, e.g., openbb-finance/openbbterminal",
        )
        if other_args and "-" not in other_args[0][0]:
            other_args.insert(0, "-r")
        ns_parser = parse_known_args_and_warn(
            parser,
            other_args,
            export_allowed=EXPORT_BOTH_RAW_DATA_AND_FIGURES,
            raw=True,
        )
        if ns_parser:
            if len(self.queue) == 0:
                log_and_raise(
                    argparse.ArgumentTypeError(
                        f"{ns_parser.repo} is not a valid repo. Valid repo: org/repo"
                    )
                )
            repo = ns_parser.repo + "/" + self.queue[0]
            if valid_repo(repo):
                asyncio.run(
                    github_view.display_star_history(repo=repo, export=ns_parser.export)
                )
                self.queue = self.queue[1:]`

and then make the various functions in github_view as async and then github_model.py:
`python
async def get_github_data(url: str, **kwargs):
    """Get repository stats

    Parameters
    ----------
    url: str
        github api endpoint
    params: dict
        params to pass to api endpoint
    Returns
    -------
    dict with data
    """
    async with aiohttp.ClientSession() as session:
        async with session.get(
            url,
            headers={
                "Authorization": f"token {cfg.API_GITHUB_KEY}",
                "User-Agent": get_user_agent(),
                "Accept": "application/vnd.github.v3.star+json",
            },
            **kwargs,
        ) as res:
            if res.status == 200:
                return res.json()
            if res.status in (401, 403):
                console.print(
                    "[red]Rate limit reached, please provide a GitHub API key.[/red]"
                )
            elif res.status == 404:
                console.print("[red]Repo not found.[/red]")
            else:
                console.print(f"[red]Error occurred {res.json()}[/red]")
            return None`

**Comment by jose-donato** [comment]
> example:
> 
> oss_controller.py
> 
> ```python
>     def call_sh(self, other_args: List[str]):
>         """Process sh command"""
>         parser = argparse.ArgumentParser(
>             add_help=False,
>             formatter_class=argparse.ArgumentDefaultsHelpFormatter,
>             prog="sh",
>             description="Display a repo star history [Source: https://api.github.com]",
>         )
>         parser.add_argument(
>             "-r",
>             "--repo",
>             type=str,
>             required="-h" not in other_args,
>             dest="repo",
>             help="Repository to search for star history. Format: org/repo, e.g., openbb-finance/openbbterminal",
>         )
>         if other_args and "-" not in other_args[0][0]:
>             other_args.insert(0, "-r")
>         ns_parser = parse_known_args_and_warn(
>             parser,
>             other_args,
>             export_allowed=EXPORT_BOTH_RAW_DATA_AND_FIGURES,
>             raw=True,
>         )
>         if ns_parser:
>             if len(self.queue) == 0:
>                 log_and_raise(
>                     argparse.ArgumentTypeError(
>                         f"{ns_parser.repo} is not a valid repo. Valid repo: org/repo"
>                     )
>                 )
>             repo = ns_parser.repo + "/" + self.queue[0]
>             if valid_repo(repo):
>                 asyncio.run(
>                     github_view.display_star_history(repo=repo, export=ns_parser.export)
>                 )
>                 self.queue = self.queue[1:]
> ```
> 
> and then make the various functions in github_view as async and then in github_model.py:
> 
> ```python
> async def get_github_data(url: str, **kwargs):
>     async with aiohttp.ClientSession() as session:
>         async with session.get(
>             url,
>             headers={
>                 "Authorization": f"token {cfg.API_GITHUB_KEY}",
>                 "User-Agent": get_user_agent(),
>                 "Accept": "application/vnd.github.v3.star+json",
>             },
>             **kwargs,
>         ) as res:
>             if res.status == 200:
>                 return res.json()
>             if res.status in (401, 403):
>                 console.print(
>                     "[red]Rate limit reached, please provide a GitHub API key.[/red]"
>                 )
>             elif res.status == 404:
>                 console.print("[red]Repo not found.[/red]")
>             else:
>                 console.print(f"[red]Error occurred {res.json()}[/red]")
>             return None
> ```

that looks nice! did you try it?

**Comment by alexferrari88** [comment]
@jose-donato sorry for the delay, I had problems with my laptop. I picked it up again now and I'm having some progress already. Will keep you posted!

**Comment by alexferrari88** [comment]
@jose-donato  I have added pytest-asyncio manually to requests.txt therefore now the tests are running. Only problem is that I think VCR is making them fail. On my laptop (where I have re-created the cassette for alternative/oss) all tests are passing fine...

**Comment by DidierRLopes** [comment]
Am going to close this issue since we haven't found a solution that doesn't block terminal execution. 😞

See #1776
