### ISSUE TITLE
[Bug] Plots are not prioritizing global styles. Wild inconsistencies between sizes and styles.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1698]
With plot autoscaling = true. If you adjust "settings" to make a pleasing chart window for your machine, other charts are negatively impacted. All charts need to print at the same scale and window size that is set by the user. 

Here is the difference between "candle" and "cpis", at exactly the same setting, this is the proportional difference, and I'm not resizing windows here.

![Screen Shot 2022-04-13 at 11 38 28 PM](https://user-images.githubusercontent.com/85772166/163328200-65c15542-2a1c-4ef4-82e1-19c1a89e10bd.png)

Without plot autoscaling it is even worse.

**Comment by deeleeramone** [comment]
With an appropriately sized/scaled candle plot, without Plot Autoscaling, stocks/ta/view, outputs this:

![Screen Shot 2022-04-14 at 10 07 53 AM](https://user-images.githubusercontent.com/85772166/163441077-a1ae06d0-e094-4b2e-8a52-42778c43571b.png)


With autoscaling: stocks/ta/view (with Candle showing to compare)

![Screen Shot 2022-04-14 at 10 15 05 AM](https://user-images.githubusercontent.com/85772166/163441320-8b5af903-b0f2-454c-aecf-2a6b5298ee76.png)

**Comment by deeleeramone** [comment]
Here's another example of the difference in chart sizes: index vs candle


Without autoscaling:
![Screen Shot 2022-04-14 at 5 29 18 PM](https://user-images.githubusercontent.com/85772166/163497145-2356a2a3-76be-42ae-8b0c-7a8e31f54f4e.png)


With autoscaling
![Screen Shot 2022-04-14 at 5 31 01 PM](https://user-images.githubusercontent.com/85772166/163497423-d2e9da06-8989-4b5f-a1ff-1535298f7f69.png)

**Comment by piiq** [comment]
@deeleeramone can you provide a sample command sequence or a code snippet to reproduce this issue?

**Comment by piiq** [comment]
I can't replicate it whatever i try

**Comment by deeleeramone** [comment]
Just pull up charts from different features, and you'll see how they are different sizes. I would also like an option to render all images in the same window because this will be a much better visual presentation for screen captures. I need the window to be in the same place on the screen and stay at a designated size.

load a ticker
candle
/economy/index sp500
yield
/stocks/options/pcr
vsurf

**Comment by DidierRLopes** [comment]
You are right, `vsurf` didn't have same format. Now from the examples provided this will be fixed in #1853
<img width="1463" alt="Screenshot 2022-05-21 at 22 25 38" src="https://user-images.githubusercontent.com/25267873/169669497-9275ff2e-2393-4bae-be5c-1f3bfc0e6b4f.png">
