### ISSUE TITLE
[IMPROVE] Build functionality to enable multiple API keys per broker 

### ISSUE THREAD

**Issue by marcelonyc** [OpenBB-finance/OpenBBTerminal#1699]
**What's the feature that should be improved?**
This request is related to Coinbase PRO's API key options. Each portfolio has its own API key. Right now you can only provide one Coinbase API key to OpenBBTerminal.  I do not know if this applies to any other brokers.

**Describe how you would like the feature improved**
Key management would need to allow more than one API key per broker (Or, at least Coinbase)

**Possibly describe the ideal way to improve this**
As far as I know, this applies only to Coinbase PRO. Allowing multiple keys per broker would impact the key validation and broker functions. It will also require that the broker functions be modified to handle multiple portfolios. Before making changes to the broker functions, key management needs to allow multiple keys. To allow time to build the functionality into the broker functions, key management should return the default config with a single API key plus an additional object with multiple portfolios' keys.

In my application, I keep my portfolio keys in a JSON file. Maybe, for now, we can use an environment variable that has the JSON as a string (ugly :) ) 

{ "Portfolio_Name" : 
       {"KEY":"KEY","SEC":"SEC","PHRASE":"PHRASE"},
}

**Additional information**
As an alternative, I can build the portfolio key management into the bro/cb functions. I am waiting for feedback before I start any development on this feature.

**Comment by DidierRLopes** [comment]
Sorry for the delay on this.

What about allowing API_COINBASE_KEY and others to be defined as:
`API_COINBASE_KEY=KEY1,KEY2,KEY3`

And then we can just check that the number of `,` are the same when there is at least one.

Then on the `coinbase` broker we could just have a command to select portfolio when there's more than 1.

Thoughts? Is this something you would still be up to work on? 

Sorry for delay once again.

**Comment by marcelonyc** [comment]
@DidierRLopes Coinbase recently announced that they are discontinuing Pro and consolidating the services with the main Coinbase framework. They now have an Advanced version similar to Pro.

At this point I would not invest time on developing for Coinbase Pro. And I have not had a chance to review API options for Coinbase Advanced. 

Unless this particular issue is helpful for other broker integration, I suggest we close it.

**Comment by DidierRLopes** [comment]
Makes sense and agreed @marcelonyc.

Thank you. 🙏🏽
