### ISSUE TITLE
[Bug] /crypto/dd/load error handling when coin not found

### ISSUE THREAD

**Issue by minhhoang1023** [OpenBB-finance/OpenBBTerminal#1701]
**Describe the bug**

<img width="481" alt="image" src="https://user-images.githubusercontent.com/40023817/163397032-a6d089aa-1185-4ab8-8bec-1aa1d23d6c6b.png">

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by colin99d** [comment]
<img width="377" alt="Screen Shot 2022-04-16 at 9 22 50 PM" src="https://user-images.githubusercontent.com/72827203/163696297-1571e745-b85e-477d-bce6-9dbe0efb480b.png">

Works fine for me!

**Comment by DidierRLopes** [comment]
<img width="400" alt="Screenshot 2022-04-18 at 10 21 59" src="https://user-images.githubusercontent.com/25267873/163787471-9a0574bb-53cc-4011-9146-e958d5a7b4a4.png">

I get the same as @minhhoang1023
