### ISSUE TITLE
[Bug] Incorrect Github link in the Installation Instructins

### ISSUE THREAD

**Issue by mathadoor** [OpenBB-finance/OpenBBTerminal#1702]
**Describe the bug**
The installation instructions on the website under "Through Anaconda" tab contains incorrect link

**Screenshots**
![image](https://user-images.githubusercontent.com/63516302/163418027-cff39b00-5441-4ca8-b8d1-069854aa956b.png)

**Suggested Resolution**
As per Readme.md under the main page, the link should be one of the following instead: https://github.com/OpenBB-finance/OpenBBTerminal.git or git@github.com:OpenBB-finance/OpenBBTerminal.git

**Comment by jose-donato** [comment]
Thanks for reporting this and present a possible solution 🙌

**Comment by jose-donato** [comment]
Should be fixed, you may need to clear the cache
