### ISSUE TITLE
[Bug] Could not build wheels for `bt`.

### ISSUE THREAD

**Issue by FedericoGarza** [OpenBB-finance/OpenBBTerminal#1706]
**Describe the bug**
I'm following the instructions [here](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/README.md#installing-the-terminal). The step `poetry install` (`pip install -r requirements.txt`) raises the error `Failed building wheel for bt`.

**To Reproduce**

1. `conda env create -n gst --file build/conda/conda-3-8-env.yaml`
2. `conda activate gst`
3. `poetry install`

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/10517170/163627650-47ac8cf0-cf61-47f5-83dc-02855134a96a.png">

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04.2 LTS
- Python version 3.8.

**Comment by KingMichaelPark** [comment]
https://linuxize.com/post/how-to-install-gcc-on-ubuntu-20-04/

You need to install GCC compiler on your system

**Comment by deeleeramone** [comment]
The message there is showing grpcio not installing because Python:>=3.6. Is the ~/.bashrc pointing to the correct path?

export PYTHONPATH='local path/miniconda3/envs/gst/lib/python3.8/'

Updating the git and pip packages can help, and you can also install Python 3.8.13.
```
conda update git 
conda update pip
conda install -c conda-forge python==3.8.13
```

**Comment by ShivaSmith** [comment]
I also had this issue on Windows 11, when running:

conda env create -n qstack10 --file https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/conda/conda-3-10-env.yaml

I eventually experienced:

 Building wheel for bt (pyproject.toml) ... error                                                                            
 error: subprocess-exited-with-error                                                                                         
                                                                                                                             
 × Building wheel for bt (pyproject.toml) did not run successfully.                                                          
 │ exit code: 1                                                                                                              
 ╰─> [13 lines of output]                                                                                                    
     running bdist_wheel                                                                                                     
     running build                                                                                                           
     running build_py                                                                                                        
     creating build                                                                                                          
     creating build\lib.win-amd64-cpython-310                                                                                
     creating build\lib.win-amd64-cpython-310\bt                                                                             
     copying bt\algos.py -> build\lib.win-amd64-cpython-310\bt                                                               
     copying bt\backtest.py -> build\lib.win-amd64-cpython-310\bt                                                            
     copying bt\core.py -> build\lib.win-amd64-cpython-310\bt                                                                
     copying bt\__init__.py -> build\lib.win-amd64-cpython-310\bt                                                            
     running build_ext                                                                                                       
     building 'bt.core' extension                                                                                            
     error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.m
crosoft.com/visual-cpp-build-tools/                                                                                          
     [end of output]                                                                                                         
                                                                                                                             
 note: This error originates from a subprocess, and is likely not a problem with pip.                                        
 ERROR: Failed building wheel for bt                                                                                         

==============================
But I did eventually have success with:

conda env create -n qstack --file https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/conda/conda-3-9-env.yaml

But Python 3.10 would be better...  :)
