### ISSUE TITLE
Fraud Explanations[IMPROVE]

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#1727]
**What's the feature that should be improved?**
The fraud command is confusing.

**Describe how you would like the feature improved**
Explain what the figures mean.

**Possibly describe the ideal way to improve this**
Added some explanations.

**Additional information**
Add any other information o
<img width="478" alt="Screen Shot 2022-04-20 at 9 54 35 PM" src="https://user-images.githubusercontent.com/72827203/164356057-3fa4b75c-3d67-497f-a78a-eccdae2a66ab.png">
r screenshots about the feature improvement.

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk
