### ISSUE TITLE
IEX API: Error: 'str' object has no attribute 'strftime'[Bug]

### ISSUE THREAD

**Issue by ginmaster** [OpenBB-finance/OpenBBTerminal#1729]
**Describe the bug**
If a stock is loaded via IEX API, e.g. via

`load --source iex -t amzn`

or

`load --source iex -t amzn --iexrange 6m`

Nearly every terminal command, except `candle` that follows lead to the following error:

Error: 'str' object has no attribute 'strftime'

To get the terminal being usable one has to log out of the current session.

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

`stocks`
`load --source iex -t amzn`
`h`

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS 12.3.1 on MBP 2021 (M1 Max)
- Python 3.8.13

**Additional context**
Add any other information that you think could be useful for us.

**Comment by DidierRLopes** [comment]
Has been solved!
