### ISSUE TITLE
[Bug] Incorrect log for reddit keys.

### ISSUE THREAD

**Issue by penfold1972** [OpenBB-finance/OpenBBTerminal#1733]
**Describe the bug**

Referring to file [keys_controller.py](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/keys_controller.py)

Line 358 logs test passed while line 359 displays keys failed. The log message needs the word passed changed to failed.

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by lepla** [comment]
Can this simple issue be assigned to me?

**Comment by DidierRLopes** [comment]
Done @lepla ! Thank you!

**Comment by piiq** [comment]
Fixed by #1735
