### ISSUE TITLE
[Bug] /crypto/onchain/ $ prices return no data

### ISSUE THREAD

**Issue by minhhoang1023** [OpenBB-finance/OpenBBTerminal#1741]
- our API return no data found
<img width="834" alt="image" src="https://user-images.githubusercontent.com/40023817/165117784-6db4650a-1740-4613-b3af-4b7d463292c6.png">

- however, CoinGecko API does return data
<img width="481" alt="image" src="https://user-images.githubusercontent.com/40023817/165117856-bd398720-01b4-4dd4-8a5d-c139ebcd594e.png">

**Comment by alexferrari88** [comment]
I confirm the bug. It's due to very small number being represented as 0. Will work out a fix

**Comment by minhhoang1023** [comment]
@alexferrari88 Very nice one! Thanks for fixing it 🚀
