### ISSUE TITLE
Charting: Y-Axis Scale Label is underneath chart titles in: portfolio/sr & portfolio/dd

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1751]
Y-Axis Scale Label is underneath chart titles in: portfolio/sr & portfolio/dd. The label is also in scientific notation when it should be represented by %.

![Screen Shot 2022-04-30 at 1 25 20 PM](https://user-images.githubusercontent.com/85772166/166121533-7f72db2c-b15e-4159-bc03-5777137b55fd.png)

![Screen Shot 2022-04-30 at 1 27 57 PM](https://user-images.githubusercontent.com/85772166/166121575-4cb9dd98-cf80-4eb0-a6d1-5c4deb38525c.png)

**Comment by DidierRLopes** [comment]
I believe this has been fixed already in one of the portfolio refactoring PRs.

<img width="1433" alt="Screenshot 2022-07-03 at 14 19 47" src="https://user-images.githubusercontent.com/25267873/177041595-e88f81ee-8396-41d2-8de2-1725d05f948e.png">

<img width="1423" alt="Screenshot 2022-07-03 at 14 20 04" src="https://user-images.githubusercontent.com/25267873/177041603-1fb273d2-640e-40cf-a0c4-daa5968bb348.png">
