### ISSUE TITLE
[IMPROVE] Add export function to portfolio menu features.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1754]
Currently there is no export capabilities for the Portfolio Menu features. It would be very helpful for batch processing to have this functionality.

**Comment by alexferrari88** [comment]
hi, I would like to help you by developing this feature. Can you please provide some examples?
Also, in which format would be most convenient to have data in?

**Comment by alexferrari88** [comment]
btw, what about the current save function doesn't satisfy you?

**Comment by deeleeramone** [comment]
Thanks for jumping in! :)

If you look at other commands, many of them will have a flag for —export. The problem with the save function is that it does not work for OpenBB routines, the export flag needs to be present. 

It’s nice to be able to export both raw data and the image, but understandable if it is not practical. Where there is a chart, the output should be the user choice of png, jpg, pdf, svg. Where there is a table, the export should be a choice of CSV, XLSX, or JSON. 


(🦋) /stocks/ta/ $ adx -h
usage: adx [-l N_LENGTH] [-s N_SCALAR] [-d N_DRIFT] [-h] [--export EXPORT]

The ADX is a Welles Wilder style moving average of the Directional Movement Index (DX). The values range from 0 to 100, but rarely get above 60. To interpret the ADX, consider a high number to be a strong trend, and a low number, a weak trend.

optional arguments:
  -l N_LENGTH, --length N_LENGTH
                        length (default: 14)
  -s N_SCALAR, --scalar N_SCALAR
                        scalar (default: 100)
  -d N_DRIFT, --drift N_DRIFT
                        drift (default: 1)
  -h, --help            show this help message (default: False)
  --export EXPORT       Export raw data into csv, json, xlsx and figure into png, jpg, pdf, svg (default: )

**Comment by alexferrari88** [comment]
it makes sense, I will take a look at it ;)
