### ISSUE TITLE
[Bug] Portfolio - Efficient Frontier has lost the Asset Labels 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1765]
![Screen Shot 2022-05-05 at 1 26 28 AM](https://user-images.githubusercontent.com/85772166/166887274-3c721a26-0252-4c0f-a248-cd70fa931012.png)

what it used to look like:

![](https://res.cloudinary.com/practicaldev/image/fetch/s--RUWwZ4cL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/nnj8qarpxo80yrn360hn.png)

**Comment by alexferrari88** [comment]
@deeleeramone  how could I replicate that?

**Comment by deeleeramone** [comment]
This is the portfolio file used for the unlabeled chart:


[BuyList.csv](https://github.com/OpenBB-finance/OpenBBTerminal/files/8636261/BuyList.csv)

![Screen Shot 2022-05-05 at 2 54 00 PM](https://user-images.githubusercontent.com/85772166/167031860-f6ea36d9-687e-433a-b482-605ab554c431.png)

To print it, load the portfolio and then:
```
po
ef
```

The labels disappeared once before, after a global change, and @jmaslek patched it up.

**Comment by JerBouma** [comment]
Not so sure if you would want these labels in the first place. You are rarely optimizing a portfolio with just a few tickers as it makes little sense especially with the current method. Maximizing for sharpe for example just gives you a very concentrated portfolio which is exactly what you do not want. If I would input 50-100+ tickers, you would completely clutter the graph. 

I therefore think it is good the way it is, it gives a sense of direction where your portfolio lies on the efficient frontier but, being so dependent on set parameters and the mean-variance method used being rather sub-optimal, does not have tremendous value in the first place.

**Comment by colin99d** [comment]
What if we only showed labels if there was below a certain amount of tickers? @JerBouma

**Comment by deeleeramone** [comment]
I don't necessarily agree with this because without any labels you have no idea which assets are attributable to the overall calculations. How would one be able to adjust for weights? This is also where an interactive chart using mouse-activated labels becomes very useful.

**Comment by JerBouma** [comment]
These models are too mathematical to just capture in a graph. What we are showing in `ef` is an interesting and fun depiction of a portfolio but nothing to take too seriously.

We have advanced options through different methods that also depict weights, risk contributions and whatnot. This should be used in combination with the parameters file, which should be checked extensively before even using this menu.

I am fine with showing the top 10 contributors or so, due to the default settings creating a very concentrated portfolio that is fine anyways. Other than that we shouldn't spend much more time in `ef`.

**Comment by deeleeramone** [comment]
Labeling the best and worst would be helpful, and allow the picture to tell a better story. You are right that 100 labels would be unmanageable but at the same time, viewers, other than the terminal operator, should be able to understand what a chart is depicting.

**Comment by colin99d** [comment]
What if we just made it an argument to toggle on/off. That way if people want it they can use it but if they do not they can turn it off.

**Comment by JerBouma** [comment]
Honestly everything is good to me, it's not an important command anyways. Just make sure it doesn't clutter the plot if I have a lot of tickers. The toggle sounds good.

**Comment by piiq** [comment]
i like this command and i use it on small portfolios (under 10 tickers) and i like the labels. having labels as an argument is fine with me

**Comment by colin99d** [comment]
I have the fix for this like 80% complete just need to get ahead on other work and then I will get it done.

**Comment by piiq** [comment]
🚀

**Comment by JerBouma** [comment]
@piiq Just to inform you that the calculations done with EF, especially the default settings lead to very concentrated portfolios (e.g. "invest 80% in Apple") which is by definition suboptimal.

I'd advise very much against using this for you investment asset allocation. Instead, look into Hierarchical Risk Parity or HERC (and even then, you need to understand it 100% to gain any meaningful benefit out of it).

Just don't want you to take any unnecessary risk!
