### ISSUE TITLE
[Bug] Portfolio/graphs does not attribute any allocations for recently acquired positions.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1766]
![Screen Shot 2022-05-05 at 1 40 06 AM](https://user-images.githubusercontent.com/85772166/166889898-c12fb511-8980-4f04-b5e4-8a0c9ecb639a.png)

The movement of one component over the holding period:
![Screen Shot 2022-05-05 at 1 51 37 AM](https://user-images.githubusercontent.com/85772166/166891015-8362f97e-fb12-43ae-92a8-730a27fc6a10.png)

A portfolio older than one year:
![Screen Shot 2022-05-05 at 1 46 25 AM](https://user-images.githubusercontent.com/85772166/166890196-04a63461-804f-456d-b44f-5d75e6686396.png)

Where colours repeat, there is no way to know which asset is which.

**Comment by piiq** [comment]
Hey @deeleeramone this is actually not a bug. The color palette that has only 12 colors so if you use more tickers in the chart the colors will be repeated for multiple tickers.
Using more colors would make the palette less contrast which would lead to similar colors to be used on charts where you have 2 or 3 lines and that would be even less usable

**Comment by deeleeramone** [comment]
How do you propose one identifies the security in a static chart? Most portfolios will hold more than 12 names.

**Comment by piiq** [comment]
how does excel handle this?
i see the same behaviour in google sheets
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/11668535/167661157-97c47d7b-0975-4408-8414-53e826074f23.png">

**Comment by DidierRLopes** [comment]
> Those are all different colours, so I’m not sure what you’re getting at here?
> […](#)

It repeats the bulk after 6 with a slight different transparency. We have a 12 color pallet. So in this plot we would actually be even better than this.

My 2 cents is that if you need more than 12 colors, you are probably not making sense out of any of the data... since there's too much noise.

**Comment by DidierRLopes** [comment]
Correct, but that's a different problem :)

**Comment by deeleeramone** [comment]
You're right. So back to the original issue raised, was that dealt with or was the issue closed because we were talking about colours?

**Comment by piiq** [comment]
This was closed because we're talking about colors
