### ISSUE TITLE
Feature: Investipedia paper trading API

### ISSUE THREAD

**Issue by ElTitoDG** [OpenBB-finance/OpenBBTerminal#1771]
I learned how to trade stocks using the Investopedia website, it taught me a lot. That's why I think it's a nice feature, to be able to see the results of your research using the platform's tools. 

For this I found an api that does just that: https://github.com/kirkthaker/investopedia-trading-api

**Comment by hjoaquim** [comment]
Hello @ElTitoDG, looked into it but apparently that API is out of date. Tried to find an alternative but so far without any luck.

**Comment by ElTitoDG** [comment]
I know it is outdated, but I think the idea is good, I will try to update it and implement it.
