### ISSUE TITLE
[IMPROVE] Improve error message when openbb.stocks.pred. is used

### ISSUE THREAD

**Issue by sautplat** [OpenBB-finance/OpenBBTerminal#1778]
**What's the feature that should be improved?**
pred_api does not get imported when tensorflow is not installed.
As a result, when openbb.stocks.pred.  is used, it's hard to know why the API is not working as expected.

**Describe how you would like the feature improved**
Ideally, we should know that openbb.stocks.pred was not fully imported due to tensorflow dependency

**Comment by piiq** [comment]
What would be the proper way of handling this?

At the moment the import of the pred api is wrapped into a try-except.
<img width="453" alt="image" src="https://user-images.githubusercontent.com/11668535/169779760-0feca92f-ff3a-4c44-af05-cf15158de30a.png">


We can add a message printout when the exception is raised, but that would lead to this message being there all the time even if the user had no intention to use the prediction menu. 
We can handle this verbosity using some sort of env variable flag, but that would not add to UX simplicity.

@sautplat @DidierRLopes please advice

**Comment by DidierRLopes** [comment]
> What would be the proper way of handling this?
> 
> At the moment the import of the pred api is wrapped into a try-except. <img alt="image" width="453" src="https://user-images.githubusercontent.com/11668535/169779760-0feca92f-ff3a-4c44-af05-cf15158de30a.png">
> 
> We can add a message printout when the exception is raised, but that would lead to this message being there all the time even if the user had no intention to use the prediction menu. We can handle this verbosity using some sort of env variable flag, but that would not add to UX simplicity.
> 
> @sautplat @DidierRLopes please advice

not sure how to best handle this honestly
