### ISSUE TITLE
I Keep Getting "Error: No module named 'riskfolio'"

### ISSUE THREAD

**Issue by djdiddles2000** [OpenBB-finance/OpenBBTerminal#1783]
Whenever I Select Certain Options, OpenBB Tells Me, "Error: No module named 'riskfolio'", Despite Having The Module Installed. 

I Tried Implementing It Myself But I Can't Seem To Get It To Work...

Thank you!

[Screenshot](https://ibb.co/NpGXGfX)

**Comment by jmaslek** [comment]
Hey!  I can answer this if you are running locally, not through the installer package.

If `poetry install` doesn't add this for some reason, you can manually add it by doing `pip install riskfolio-lib`

You can test if its installed by running `pip list|grep Riskfolio`, which should give the below:

```
(openbb) james@Jamess-MBP OpenBBTerminal % pip list|grep Riskfolio
Riskfolio-Lib                 3.1.1
```

**Comment by djdiddles2000** [comment]
> Hey! I can answer this if you are running locally, not through the installer package.
> 
> If `poetry install` doesn't add this for some reason, you can manually add it by doing `pip install riskfolio-lib`
> 
> You can test if its installed by running `pip list|grep Riskfolio`, which should give the below:
> 
> ```
> (openbb) james@Jamess-MBP OpenBBTerminal % pip list|grep Riskfolio
> Riskfolio-Lib                 3.1.1
> ```

I believe the issue here maybe the fact that I'm using a Unix Shell on Windows. When I type grep Riskfolio, it states, "grep is not recognized as an internal or external command,
operable program or batch file."

**Comment by djdiddles2000** [comment]
A quick update, this seems to be an issue with the installer. It doesn't have the modules, after installation on windows. I understand it's still in beta, and not complete. Hopefully this gets fixed soon!

**Comment by jmaslek** [comment]
Thanks for this!  Gonna pin this to @andrewkenreich

**Comment by deeleeramone** [comment]
Just got another report of this error

**Comment by andrewkenreich** [comment]
Building a fix for this now. Will make this v1.2.1 on windows, since it was v1.2.0 :)

**Comment by andrewkenreich** [comment]
This should be fixed now in the new .exe I just uploaded. It's in the same v1.2.1 release but windows is now on that version as well.
