### ISSUE TITLE
[Bug] stocks/ta/VWAP: VWAP artificially limits the user to the most recent trading session.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1789]
VWAP artificially limits the user to the most recent trading session despite intraday data being loaded. 

![Screen Shot 2022-05-09 at 9 00 12 PM](https://user-images.githubusercontent.com/85772166/167540122-917a1a77-b68f-4f5c-bc51-15985b610bd6.png)
![Screen Shot 2022-05-09 at 9 14 48 PM](https://user-images.githubusercontent.com/85772166/167541424-1004529b-4db2-4bf1-b5a0-851f6ecd6d08.png)

**Comment by piiq** [comment]
resolved by #1790
