### ISSUE TITLE
[Bug] Tests : Cryptocurrency > Due Diligence > Glassnode

### ISSUE THREAD

**Issue by Chavithra** [OpenBB-finance/OpenBBTerminal#1791]
**Describe the bug**
The following test seems to display the chart as soon as `subplot` is called.
- File : `tests\openbb_terminal\cryptocurrency\due_diligence\test_glassnode_view.py`
- Function : `test_display_btc_rainbow`

**Comment by piiq** [comment]
resolved by #1903
