### ISSUE TITLE
[Bug] /crypto/ta/kc - The command 'kc' doesn't exist on the /crypto/ta/ menu

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1793]
[Bug] /crypto/ta/kc - The command 'kc' doesn't exist on the /crypto/ta/ menu

![image](https://user-images.githubusercontent.com/85772166/167750883-05e6e4b7-d52d-453b-a7fa-4de293af8888.png)

**Comment by alexferrari88** [comment]
I think I have found the problem, I will try to fix it
