### ISSUE TITLE
[Bug] /stocks/options/hedge/plot: Chart has no legend identifying the two lines.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1817]
Chart has no legend identifying the two lines.

![Screen Shot 2022-05-14 at 12 52 31 PM](https://user-images.githubusercontent.com/85772166/168446515-f58b5ea4-5450-456e-a5b7-1285e8687ea3.png)

**Comment by deeleeramone** [comment]
/stocks/options/hedge/plot:
![Screen Shot 2022-05-20 at 11 56 47 AM](https://user-images.githubusercontent.com/85772166/169594240-d2dbb2ef-f579-48e5-8791-33877a1dcb9c.png)

**Comment by colin99d** [comment]
I think the bigger issue with this new implementation is that the underlying asset is now a derivative. @JerBouma do you know what this is?

**Comment by JerBouma** [comment]
@colin99d So the current implementation is based on https://towardsdatascience.com/algorithmic-portfolio-hedging-9e069aafff5a. Essentially, you hedge an option position giving two options and the underlying. Or another explaining it well: https://www.investopedia.com/terms/d/deltagamma-hedging.asp

In essence, if you want to vega-gamma-delta hedge you are essentially hedging an _option_ position which is what is currently happening. So, the `payoff` menu doesn't exist anymore, this is now built into the `hedge` menu. 

I believe the payoff diagram is still correct, it still represents two options and the underlying asset. However, it does not take into account the option you have chosen at `pick`. So labelling + adding the option from `pick` should be enough.
