### ISSUE TITLE
[Bug] Closed Bug Not Resolved: #1645 - The Windows & Mac installer v1.3.0 exhibit the same problem.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1825]
Another issue has been opened: [1831] https://github.com/OpenBB-finance/OpenBBTerminal/issues/1831

[#1645](https://github.com/OpenBB-finance/OpenBBTerminal/issues/1645)

The issue still persists with v1.3.0 of installer, both Mac and Windows. 

In the installer, the test fails; in the GitHub Repo version, it passes.

**Comment by DidierRLopes** [comment]
What is the issue? 

praw being outdated is a warning, and doesn't influence Reddit API.

**Comment by DidierRLopes** [comment]
I think this should be fixed now.
