### ISSUE TITLE
[IMPROVE] Add Hugo doc link in each command's help

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#1847]
**What's the feature that should be improved?**
For every command, add in the Hugo documentation which we explain the command in more detail with actual examples. This improves traffic to these docs and also gives the opportunity for the user to see the related guides that are currently being created.

**Possibly describe the ideal way to improve this**
I already created a version that works, it just needs to be nicer + work for *all* commands.

Note @piiq comments: *On the controller level you have the path of the controller in self.path, the command name you can get from the came of the call_ function that is being executed at the moment.* (the command name can also be obtained from parser.prog). His suggestion is better than the below implementation where the `command_path` would be the `__file__` of the command you want to link to.
 
Within **parse_known_args_and_warn** of _helper_funcs.py_. 
```
  if ns_parser.help:
      subsequent_paths = os.path.dirname(command_path).split("openbb_terminal")[-1].split("/")

      documentation_location = "https://openbb-finance.github.io/OpenBBTerminal/terminal/"
      for path in subsequent_paths:
          if path:
              documentation_location += f"{path}/"
      documentation_location += parser.prog

      txt_help = parser.format_help()
      console.print(f"[help]{txt_help}[/help]")
      console.print(f"For more information, see: {documentation_location}")

      return None
```

Which returns:
```
usage: quote [-h]

Get current exchange rate quote

optional arguments:
  -h, --help  show this help message (default: False)

For more information, see: https://openbb-finance.github.io/OpenBBTerminal/terminal/forex/quote
```

**Note that some hugo docs need to be refactored, for example crypto vs. cryptocurrency, to make this work.**

**Additional information**
Add any other information or screenshots about the feature improvement.

**Comment by JerBouma** [comment]
**An addition:**
Also do this for the menus being able to call `options -h` which returns the (still to be created) link to the "Introduction to Options" page.

**Comment by DidierRLopes** [comment]
<img width="797" alt="Screenshot 2022-06-13 at 16 42 26" src="https://user-images.githubusercontent.com/25267873/173314834-8820ea08-5d03-41ae-8bba-9b5559ab4135.png">

This will be done as part of #1928
