### ISSUE TITLE
[Improve]Stocks/options/vsurf: Zooming makes the plots bigger than the canvas

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1848]
/stocks/options/vsurf: zooming in makes the plots do this.
![Screen Shot 2022-05-20 at 9 34 57 AM](https://user-images.githubusercontent.com/85772166/169573247-ebee8fc0-ab50-4678-b2a2-c4ba60efe924.png)

**Comment by jmaslek** [comment]
unfortunately with MPL 3d, this is a feature not a bug

**Comment by deeleeramone** [comment]
This is new behaviour though. It didn't do this before.

**Comment by deeleeramone** [comment]
It would be great if the data here was selectable, like the other features, and defaulted to the chosen source.

**Comment by DidierRLopes** [comment]
We can't do anything here since this is the library we are currently using. Will close this ticket.

**Comment by deeleeramone** [comment]
How about we use Plotly here?

**Comment by deeleeramone** [comment]
This function should be re-mapped to use Plotly because Matplotlib will likely *never* close this issue - related to the longest open issue they have on GitHub. We don't want to wait ten years for this not to be fixed.

![Screen Shot 2022-09-29 at 8 50 23 PM](https://user-images.githubusercontent.com/85772166/193186321-1bd3f936-9c29-4489-a51e-4bc475544aaf.png)

**Comment by colin99d** [comment]
We have looked at plotly several times but unfortunately it is not a simple transfer. We either needs a backend to run it (PyQt is the most common, but its license is incompatible with ours). Or we need to show in a browser (which Didier and James are against). I saw we leave the issue open, but move it to an enhancement.

**Comment by deeleeramone** [comment]
We already have two functions that do this. `Candle` and `heatmap`. Then there are dashboards. Working software > broken software.

**Comment by deeleeramone** [comment]
I disagree with this label. It's not an enhancement, it's literally a bug in the charting library. The function does not work with this bug.

**Comment by DidierRLopes** [comment]
This is a bug on `matplotlib` side not on ours. For us adding `plotly` is an enhancement.

**Comment by the-praxs** [comment]
What if we use Bokeh? It's an excellent alternative to Plotly and does provide all the features we need.

**Comment by deeleeramone** [comment]
The charting library has been completely redone for Plotly using a custom backend. Closing the issue.
