### ISSUE TITLE
[IMPROVE]Options/Pricing - As is, this feature is not really usable because it requires an impossible amount of known values be manually entered by the user.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1849]
- Is the purpose that this feature attempts to serve accomplished already through `hedge` and `binom`?

```
stocks/options/pricing
```
This feature requires an impossible amount of manual data entry before any values will be calculated.

- Chance must = 1, where chance is the y-value in a binomial probabilities outcome distribution bell curve.

- Chance is also a % represented by 1.00 = 100%, and rounding occurs after only two decimal places.

- Price is all of the strike prices for the expiration date

- All values that require user input are already known values by the program.

- This table really ought to be self-populated, based on a choice of the options pricing model and variables for RFR, volatility, and style of option.  

The graph in this screenshot of from `binom --plot`. The expiration dates are different, it is only for illustrative purpose.
![Screen Shot 2022-05-20 at 4 29 08 PM](https://user-images.githubusercontent.com/85772166/169624592-314968f4-6d0c-4250-86f9-a08aa8a90a12.png)

**Comment by DidierRLopes** [comment]
@colin99d can you have a look at this please?

**Comment by colin99d** [comment]
I am bit confused on the line `all of the values that require entry are already known by the program`. The whole point of this command is  that a user has a list of different price they think an equity might end at, and the porbability of each price. Then we tell them how they can profit if their assumptions are true. 

I agree this has limited availability for some users, but so do a lot of our commands. The main point is someone who just created a binomial tree can now see what they should do based on their results.

**Comment by deeleeramone** [comment]
If we can eliminate the requirement to input all values to equal 100%, so a user could enter only one value, for example a 25% chance of $400 SPY price EOW, and that would determine the peak of the probabilities distribution bell curve. Adding three or more values would allow the user to modify, or allow for, the skew value.

**Comment by jmaslek** [comment]
this went bye bye 👋
