### ISSUE TITLE
[Bug] Options/grhist: feature is broken. All responses return a blank chart, and the error message: Data from API is not valid.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1857]
![Screen Shot 2022-05-22 at 2 45 13 PM](https://user-images.githubusercontent.com/85772166/169717307-859f32fe-cd93-4c8f-9a78-48c50ff76603.png)

**Comment by jmaslek** [comment]
Pinging the syncretism author :)

**Comment by piiq** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/11668535/172205263-102c8e4d-45f9-4ff3-bf9e-52bdc0ff789b.png">
this seems to work

**Comment by deeleeramone** [comment]
Looks like the problem fixed itself! Strong work everyone!
