### ISSUE TITLE
[Bug] Stocks/ba/reddit API - reddit_sent: command hangs the terminal with --full_search argument. popular: Not all PushShift shards are active

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1861]
The Terminal hangs when using: `reddit_sent -f`

![Screen Shot 2022-05-23 at 10 59 52 AM](https://user-images.githubusercontent.com/85772166/169879591-b04bb053-c01e-4376-9460-109397b5036e.png)

It never advances, even after leaving it for a long while.

![Screen Shot 2022-05-23 at 10 47 42 AM](https://user-images.githubusercontent.com/85772166/169877950-a47aa1b3-0afe-4fa8-8da1-c76df7a92025.png)

The chart displayed here is not very clear about what we are looking at. 

![Screen Shot 2022-05-23 at 10 54 16 AM](https://user-images.githubusercontent.com/85772166/169878745-0e7dc4e1-baed-48e3-ad44-810c0c443df7.png)

The terminal is also hanging with the command, popular
```
(🦋) /stocks/ba/ $ popular
Search for latest tickers for 50 'Superstonk' posts
/Users/danglewood/GitHub/GST1/miniforge3/envs/tester/lib/python3.8/site-packages/psaw/PushshiftAPI.py:252: UserWarning: Not all PushShift shards are active. Query results may be incomplete
  warnings.warn(shards_down_message)

**Comment by simmonsj330** [comment]
@deeleeramone I tried the commands shown and they seem to work appropriately. The commands that result in an '403 HTTP Response' revolve around the particular subreddits that the user wants to query. More specifically r/wsb. This subreddit is private and as such not subject to API calls. However, r/wallstreetbets works, if thats the subreddit you actually wanted to try. Additionally, the when providing a list of subreddits, the list must be comma separated and* there should be no spaces. Perhaps this could be more clear in the help dialogue and more appropriate labels could be added to the graphs.

<img width="1213" alt="Screen Shot 2022-06-19 at 2 18 44 PM" src="https://user-images.githubusercontent.com/53658028/174498397-c3f3e017-ef8f-4334-a3ad-fa04e280b348.png">
<img width="1269" alt="Screen Shot 2022-06-19 at 2 57 33 PM" src="https://user-images.githubusercontent.com/53658028/174498409-602a0475-29bc-40e4-8b97-5f26d26afcbf.png">
<img width="1288" alt="Screen Shot 2022-06-19 at 3 05 05 PM" src="https://user-images.githubusercontent.com/53658028/174498511-8bb5f4a7-c0e0-4865-8e10-e53c6a8011bc.png">
