### ISSUE TITLE
[IMPROVE] Add fmp, plotting and ratios to the fa menu

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#1866]
I'd like to see the following improved:
- Adding in the source fmp ([FinancialModellingPrep](https://github.com/JerBouma/FundamentalAnalysis)) that is currently an unnecessary sub-menu (can be an option where alpha vantage is the default)
- The ability to plot data from things like income  and balance over time
- The ability to show ratios over time (and plot them)

This makes the menu compact and allows you to see metrics that matter. It means a lot more if you look at revenue growth than the individual items of the financial statements.

**Comment by northern-64bit** [comment]
This issue can be closed @JerBouma
