### ISSUE TITLE
[IMPROVE] Add ratios and more reliable fundamentals to the sia menu

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#1867]
I'd like to see the following improved:
- Add in ratios, the financial statements we currently show do not allow for proper comparison (as I learned from a buy-side analyst, he only looks at the ratios since that allows comparisons)
- Add in the fmp ([Financial Modelling Prep](https://github.com/JerBouma/FundamentalAnalysis), or any other) as source for a more reliable way to collect data. Note that it only shows annual data of max 5 years but currently we use a source that breaks if you use it a couple of times.

Showing ratios (e.g. revenue growth) allows for a much better comparison than using the individual items. It also allows you to understand relationships between the items.

**Comment by joshuabuildsthings** [comment]
I'd like to add a +1 to this, plus suggest adding these:

- [DCF](https://site.financialmodelingprep.com/developer/docs#Company-Discounted-cash-flow-value)
- [Financial Scores; Especially Altman-Z & Piotroski F-Score.](https://site.financialmodelingprep.com/developer/docs#Stock-Financial-scores)

Having the DCF model in Excel is a really amazing feature, but is less useful for value screening. The Altman-Z & Piotroski scores also have some solid data backing them up as being reliable metrics.

**Comment by colin99d** [comment]
Closing because for now we killed the SIA menu.
