### ISSUE TITLE
[Bug] Can't enter QA menu with intraday data loaded, but you can load intraday data inside the QA menu.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1879]
There seems to be no real reason why a user can't use the features with intraday data, so this artificial barrier should be removed, and the date label here, `Ticker: Intraday 15min GME (from 2019-05-23)`, should change according to the new starting date when using `load` inside the menu. 

```
(🦋) /stocks/ $ qa
Load daily data to use this menu! 
```
![Screen Shot 2022-05-27 at 12 11 37 PM](https://user-images.githubusercontent.com/85772166/170775561-6832ace6-20a6-426f-b07a-2cfd492e8041.png)
![Screen Shot 2022-05-27 at 12 12 15 PM](https://user-images.githubusercontent.com/85772166/170775643-dda9f7e4-31ce-4c3a-9fa7-bde604687b68.png)
![Screen Shot 2022-05-27 at 12 14 34 PM](https://user-images.githubusercontent.com/85772166/170775943-1651ef66-5ab5-41a0-b8ad-dffd03a2860a.png)
![Screen Shot 2022-05-27 at 12 16 22 PM](https://user-images.githubusercontent.com/85772166/170776525-c37cf37d-1e85-4327-b0f0-a9eba0c90fe6.png)

**Comment by jmaslek** [comment]
closed by #1880
