### ISSUE TITLE
[Bug] Generating a report fails due to not having a `pred` attribute in the `stocks_api` module

### ISSUE THREAD

**Issue by stkerr** [OpenBB-finance/OpenBBTerminal#1898]
**Describe the bug**

I tried to generate a report with the commands:
```
reports
1 TSLA
```

The report ran for a while and then failed mid-way through to due the error:

`AttributeError: module 'openbb_terminal.stocks.stocks_api' has no attribute 'pred'`

It appears to be failing on this [line](https://github.com/OpenBB-finance/OpenBBTerminal/blob/6aa487b590d3be178531ce83ab501a8b286525ea/openbb_terminal/reports/equity.ipynb?short_path=7b29bec#L535).

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

Open the terminal.
Go to the reports menu.
Use the text `1 TSLA` (or another ticker) to generate a report.
Notice the error message.

**Screenshots**

Screenshot below.

![image](https://user-images.githubusercontent.com/69191/171931875-0c77b831-d2b8-45fc-95c6-7006b77d71ba.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Python version 3.8.13

**Additional context**
Add any other information that you think could be useful for us.

**Comment by jmaslek** [comment]
Do you have the prediction feature flag enabled?  You can check with `featflags` on the main menu.  (see below).

The prediction packageson also needstop be installed (if using poetry: `poetry install -E prediction` )

<img width="691" alt="Screen Shot 2022-06-03 at 4 08 01 PM" src="https://user-images.githubusercontent.com/18151143/171943470-732bdc96-348a-474c-8255-6b9744b7b1ce.png">

**Comment by stkerr** [comment]
@jmaslek thanks for pointing me at that. I did have the feature flag enabled and could have sworn I'd already installed the prediction package with poetry. I re-ran poetry though and after doing so the bug went away, so I must have missed it before 🤷 

We can close now. I'll try to put a PR together to catch the error and print a string to suggest folks enable the flag & install the package, rather than a stack trace.
