### ISSUE TITLE
[Bug] stocks/dps/FTD - Start/End flags are broken: 404 error & Error: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1904]
![Screen Shot 2022-06-05 at 1 28 54 PM](https://user-images.githubusercontent.com/85772166/172069400-c64c316a-0c43-4a91-9461-816da795562f.png)

using `n -500` works, but specifying date windows does not. 

![Screen Shot 2022-06-05 at 1 33 51 PM](https://user-images.githubusercontent.com/85772166/172069462-db979640-3dcb-4964-b203-2ece0302a868.png)

**Comment by simmonsj330** [comment]
This bug results from a wrong link resulting in an HTTP 404 error. When looking on the SEC website at the .zip links (https://www.sec.gov/data/foiadocsfailsdatahtm) occasionally a .zip path will not be structured in the same way that a majority of the other paths are. 
Where the standard path is:
`...data/fails-to-deliver/cnsfails...`
There are some that are structured as: 
`...data/frequently-requested-foia-document-fails-to-deliver/cnsfails...` 
or 
`node/add/data_distribution/cnsfails...`
etc

The location of non-standard paths is fairly random. I suggest refactoring and utilizing the above link to scrape a list of the paths as to not run into this error.

**Comment by simmonsj330** [comment]
Per Darren, we could potentially switch to FINRA API however this is only came online recently, so there has been no development on implementing this API as a source. As a result we will simply patch this bug and look into utilizing the API for 'fails to deliver' functionality.
