### ISSUE TITLE
[Bug] Wrong error message

### ISSUE THREAD

**Issue by Chavithra** [OpenBB-finance/OpenBBTerminal#1910]
**Describe the bug**

Wrong error message displayed :
```bash
Error: ERR#0043: no results were found for the introduced symbol.

Error: not enough values to unpack (expected 2, got 0)

Error: not enough values to unpack (expected 4, got 0)
```

**Comment by DidierRLopes** [comment]
@Chavithra what command was this?

**Comment by Chavithra** [comment]
Command : ```/funds/load arkg````

**Comment by simmonsj330** [comment]
@Chavithra ARKG is an ETF not a mutual fund. We utilize a module named investpy and when looking at the module's code it seems like the error you are receiving is the correct response.
