### ISSUE TITLE
[IMPROVE] How do you get information about indian stocks

### ISSUE THREAD

**Issue by jan53n** [OpenBB-finance/OpenBBTerminal#1934]

**Comment by DidierRLopes** [comment]
Hey @jan53n,

If you do `search -c India` you can see a couple of examples of stocks located in India:
<img width="1367" alt="Screenshot 2022-06-13 at 15 23 25" src="https://user-images.githubusercontent.com/25267873/173300983-5eab3fae-6089-4b53-9b70-74385ec13f27.png">

If you do `search -e India` you can see a couple of examples of stocks that are in an Indian exchange:
<img width="1013" alt="Screenshot 2022-06-13 at 15 26 28" src="https://user-images.githubusercontent.com/25267873/173301478-3474a274-982b-43cb-bc0b-89bf6fd41cbf.png">

Typically you will see that they need a `.NS` suffix, and you can access them with:
<img width="1615" alt="Screenshot 2022-06-13 at 15 33 13" src="https://user-images.githubusercontent.com/25267873/173302575-933320f1-38a5-4640-ae04-2a4888f83935.png">

Closing this, but let me know if you need further help
