### ISSUE TITLE
[Bug] Cannot access /stocks/dd menu

### ISSUE THREAD

**Issue by 8000937** [OpenBB-finance/OpenBBTerminal#1935]
**Describe the bug**
When trying to access the dd menu, I get the error "Error: No module named 'fundamentalanalysis'". Fresh install.

**To Reproduce**
Go to the stocks menu, load a ticker, and then type dd. 

**Desktop:**
- OS: Windows 10
- Python 3.8.8

From logs:

openbb_terminal.stocks.stocks_controller.StocksController|call_dd|0|Exception: No module named 'fundamentalanalysis' - Traceback (most recent call last): - File cut\file\path\decorators.py, line 62, in wrapper - value = func(*args, **kwargs) - File cut\file\path\stocks_controller.py, line 549, in call_dd - from openbb_terminal.stocks.due_diligence import dd_controller - File cut\file\path\pyimod03_importers.py, line 495, in exec_module - File cut\file\path\dd_controller.py, line 23, in <module> - from openbb_terminal.stocks.due_diligence import ( - File cut\file\path\pyimod03_importers.py, line 495, in exec_module - File cut\file\path\fmp_view.py, line 9, in <module> - from openbb_terminal.stocks.due_diligence import fmp_model - File cut\file\path\pyimod03_importers.py, line 495, in exec_module - File cut\file\path\fmp_model.py, line 6, in <module> - import fundamentalanalysis as fa - ModuleNotFoundError: No module named cut\file\path\

**Comment by 8000937** [comment]
From logs; 

openbb_terminal.stocks.stocks_controller.StocksController|call_dd|0|Exception: No module named 'fundamentalanalysis' - Traceback (most recent call last): - File cut\file\path\decorators.py, line 62, in wrapper - value = func(*args, **kwargs) - File cut\file\path\stocks_controller.py, line 549, in call_dd - from openbb_terminal.stocks.due_diligence import dd_controller - File cut\file\path\pyimod03_importers.py, line 495, in exec_module - File cut\file\path\dd_controller.py, line 23, in <module> - from openbb_terminal.stocks.due_diligence import ( - File cut\file\path\pyimod03_importers.py, line 495, in exec_module - File cut\file\path\fmp_view.py, line 9, in <module> - from openbb_terminal.stocks.due_diligence import fmp_model - File cut\file\path\pyimod03_importers.py, line 495, in exec_module - File cut\file\path\fmp_model.py, line 6, in <module> - import fundamentalanalysis as fa - ModuleNotFoundError: No module named cut\file\path\

**Comment by DidierRLopes** [comment]
Hey @8000937,

I don't think you have the latest version. This issue has been fixed a couple of weeks ago.

You can either `git pull` or use the installer from here: https://www.openbb.co/products/terminal.

Please re-open this issue if this didn't fix it!
