### ISSUE TITLE
[Bug] /crypto/defi/govp not working

### ISSUE THREAD

**Issue by minhhoang1023** [OpenBB-finance/OpenBBTerminal#1936]
Is this API deprecated? If so, could we remove this command?

![image](https://user-images.githubusercontent.com/40023817/173341243-e1e12a22-2c8c-4a05-b227-56b0996d4e7d.png)

**Comment by montezdesousa** [comment]
I think the API still works for other information, but governance is not working

**Comment by minhhoang1023** [comment]
@montezdesousa If that's no longer working, I'd suggest syncing with @jose-donato to see if there's any other source we can replace with. Otherwise, time to say goodbye to `govp`

**Comment by montezdesousa** [comment]
Given current situation with luna his suggestion is to just wait a few weeks to see if they start updating it again, and if not we remove it
