### ISSUE TITLE
[Bug] crypto/defi/sratio: Remove scientific notation in Chart title

### ISSUE THREAD

**Issue by minhhoang1023** [OpenBB-finance/OpenBBTerminal#1937]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/40023817/173341864-cd9b9db9-c6dd-4527-a4cd-983d250d1092.png">

**Comment by montezdesousa** [comment]
Actual staking ratio provided by this source just went from ~0% to 36745921080547700% on may/24.

This makes sense? Ratio was around 40% before the crash and I could understand it going to zero after they print so much new tokens, but the spike is a mystery to me.

![image](https://user-images.githubusercontent.com/79287829/174129476-992971be-7a4e-46e2-9434-73d1633db7f3.png)´

![image](https://user-images.githubusercontent.com/79287829/174131914-6d1500ef-c6d0-4812-b40c-39059a6461d5.png)

**Comment by minhhoang1023** [comment]
@montezdesousa Yeah that does not make any sense. The staking ratio cannot exceed 100%. Was checking other sites and the staking ratio, which should be around 1%. https://www.stakingrewards.com/earn/terra/

We can deprecate this command. As Luna is basically dead now 😢
