### ISSUE TITLE
[Bug] Stocks/search - Filtering by Exchange is broken when the choice is USA

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1938]
`stocks/search Walmart -e USA`

For Exchange = USA, search returns no results. Other countries work. 

<img width="691" alt="Screen Shot 2022-06-13 at 6 54 28 AM" src="https://user-images.githubusercontent.com/85772166/173369498-90b9d7b2-14e2-46e7-96fc-128155670690.png">

![image](https://user-images.githubusercontent.com/85772166/173369617-33cbb42a-4831-45c3-af2c-eaef719645bf.png)

<img width="798" alt="Screen Shot 2022-06-13 at 6 56 14 AM" src="https://user-images.githubusercontent.com/85772166/173369820-e71fbc1c-c8bb-48f5-936c-fa62c55cb569.png">

**Comment by DidierRLopes** [comment]
Has been fixed in #1939 by @stkerr 🙌
