### ISSUE TITLE
[Bug] /crypto/ $ headlines showing warning

### ISSUE THREAD

**Issue by minhhoang1023** [OpenBB-finance/OpenBBTerminal#1955]
Copied from a user report bug on our Support Form.

I used the exe installer on windows

2022 Jun 14, 09:10 (🦋) /crypto/ $ headlines
openbb_terminal\helper_classes.py:373: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
2022 Jun 14, 09:10 (🦋) /crypto/ $ openbb_terminal\menu.py:15: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  pyplot.pause(0.1)

**Comment by Joe-TheBro** [comment]
Can confirm any GUI based actions from the terminal seem to error in similar ways to the headlines menu, just got this one in crypto/ov/ after poking for a bit
```
2022 Jun 18, 02:45 (🦋) /crypto/ov/ $ hm
openbb_terminal\cryptocurrency\discovery\pycoingecko_model.py:128: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame(data), ignore_index=True)
openbb_terminal\helper_classes.py:373: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()

2022 Jun 18, 02:45 (🦋) /crypto/ov/ $ openbb_terminal\menu.py:15: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  pyplot.pause(0.1)
```
Also, side note, if you continuing using console afterwards, like if you were to go to ```2022 Jun 18, 02:47 (🦋) /stocks/ $ search twitter``` it will give a warning (seen below) when normally it wouldn't using a terminal that hadn't experienced the previous bug.
```
2022 Jun 18, 02:47 (🦋) /stocks/ $ openbb_terminal\menu.py:15: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  pyplot.pause(0.1)
````

**Comment by jmaslek** [comment]
As of 1.6 this was no longer present.  Closing.  Reopen if I am a liar
