### ISSUE TITLE
[FR] Add Setuptools.py installation

### ISSUE THREAD

**Issue by bulvara** [OpenBB-finance/OpenBBTerminal#1962]
I prefer the setuptools.py way for distro packaging. But since some time neither

```
dephell deps convert --from pyproject.toml --to setup.py
python -m pyproject2setuppy build
python setup.py install --root="$pkgdir/" --skip-build --optimize=1
```
nor
```
python -m build --wheel --no-isolation
python -m installer --destdir="$pkgdir" dist/*.whl
```
work due to

`ImportError: cannot import name 'ConfigMetadataHandler' from 'setuptools.config' (/usr/lib/python3.10/site-packages/setuptools/config/__init__.py)`

**Comment by piiq** [comment]
Hey @bulvara
At this moment we support python 3.8 and python 3.9. Can you try one of those?

p.s. pypi and pip fully support installation from a pyproject.toml file
