### ISSUE TITLE
[IMPROVE]Messari API Key

### ISSUE THREAD

**Issue by ginmaster** [OpenBB-finance/OpenBBTerminal#1963]
**What's the feature that should be improved?**
A description of what's the feature you want improved, and a bit of context (why is that).
Messari API Key has to be correct in openbb_terminal/keys_controller.py 

**Describe how you would like the feature improved**
A description of what the current feature is vs what it would be after your suggestion.
in line #68: there is a typo one 's' is missing which leads to problems with the messari API key

**Possibly describe the ideal way to improve this**
If you have thought about how you would do it, add it here.
Correct the typoi

**Additional information**
Add any other information or screenshots about the feature improvement.

**Comment by DidierRLopes** [comment]
Thanks for pointing this out. Sorry for the delay, #2036 fixes this!
