### ISSUE TITLE
[Bug] crypto/disc/cgtrending: Help dialogue says to use --limit argument, but argument does not exist.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1967]
crypto/disc/cgtrending: Help dialogue says to use --limit argument, but argument does not exist.

<img width="613" alt="Screen Shot 2022-06-20 at 11 25 30 AM" src="https://user-images.githubusercontent.com/85772166/174660043-9a5b4d4a-bdd3-4d75-a726-857230c7944b.png">

**Comment by DidierRLopes** [comment]
The issue is on documentation, cgtrending doesn't allow a limit. I will reflect that on documentation
