### ISSUE TITLE
[IMPROVE] Add dialogue to keys menu

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#1969]
**What's the feature that should be improved?**
Users described that it was not very apparent how to add a new api key when in the keys menu.

**Describe how you would like the feature improved**
Add dialogue at the top of the keys menu to assist users in adding a key.

**Possibly describe the ideal way to improve this**
Ideally add a single sentence suggesting that the user type in <API> -h due to the fact that certain APIs need different key info.

<img width="914" alt="Screen Shot 2022-06-20 at 6 16 02 PM" src="https://user-images.githubusercontent.com/53658028/174687857-4969975e-4812-4da3-8a85-f2820dc4d6b6.png">

**Comment by DidierRLopes** [comment]
This has been done AFAIK, so closing it!
