### ISSUE TITLE
[FR] Linux: Flatpak version

### ISSUE THREAD

**Issue by rogue-agent** [OpenBB-finance/OpenBBTerminal#1991]
**What's the problem of not having this feature?**
I recently switched to Linux only, as it saves money and time, I have not found any OpenBB version for Linux.

**Describe the solution you would like**
As there are multiple Linux and BSD platforms with different repositories and versions of packages; easiest would be to create a Flatpak version of OpenBB.

**Describe alternatives you've considered**
Appimage or .deb files are less inclusive of overall coverage of the Linux market. Alternatives (kind of) to OpenBB are: Markets by Bitstower which only lists stocks and buyables. Merkato by Flávio Vasconcellos Corrêa seems to be the older version of Markets. Portfolio Performance by Andreas Buchen might just be the closest to a rival.

**Additional information**
Some might disagree but keeping a clean look Adwaita and GTK4 would make it easy to have an universally clean look. Compatible with system themes.

**Comment by ebdavison** [comment]
I would like to see this as well if at all possible.  I struggled for many hours to get the install done on my Linux workstation and in the end I was able to get it to work ... finally!

**Comment by spaskob** [comment]
> I would like to see this as well if at all possible. I struggled for many hours to get the install done on my Linux workstation and in the end I was able to get it to work ... finally!

Do you mind posting what worked for you?

**Comment by deepakiim** [comment]
Looking forward for ubuntu snap version of openbb

**Comment by rogue-agent** [comment]
> 
I can just recommend reading this. Snap is just a waste of time. Let the community do it. Flatpak is where it's at.
https://www.reddit.com/r/linux/comments/j3ajnf/whats_wrong_with_snaps_why_so_many_people_hate_it/

**Comment by wiki-me** [comment]
I don't see a flatpak release [here](https://docs.openbb.co/terminal/quickstart/installation), so i assume this was closed in order so that [this](https://github.com/OpenBB-finance/OpenBBTerminal/issues/3651) issue will be it's replacement?

**Comment by 097115** [comment]
> We have an AppImage in the works, but yet still early

@piiq, Any progress on the AppImage release, may be?

**Comment by wiki-me** [comment]
> We actually did invest time into making an appimage for Linux. While exploring this approach we faced some challenges due to our dependency tree. This made it difficult to create a bundle that would provide a good user experience across different distributions. It works on Ubuntu, it doesn’t work on Arch. It works on Fedora it doesn’t work on CentOS etc.

Maybe you didn't use an old enough version of Ubuntu when making the package?


>It’s still early to say for sure, but from my current perspective the “double-click install” experience on Linux is not going to be neither an appimage not a flatpack, but more likely a self-extracting script.

tbh i don't really like that, running  a script that does god knows what and potentially adding closed source components to my system, i think if you would do a survey you would find that a lot of linux users like me also don't like it. It would be better to just ship binary and have people do stuff like adding an icon on their desktop (something like [cataclysm dda](https://cataclysmdda.org/releases/) ).

another option is [nix](https://github.com/NixOS/nix) (which is a cross distribution package manager and the [third most popular repository](https://repology.org/) in term of number of maintainers), It's UX is currently buggy but that is being worked on and i think it has a bright future.

**Comment by jiiiijiij** [comment]
+1 hope for an appimage

**Comment by rogue-agent** [comment]
What is the current state of the situation as I have not had the time to investigate further into this matter.
