### ISSUE TITLE
[Bug] Crypto/load & candle - Chart is backwards, X-axis travels the wrong direction over time. Incorrect performance metrics are displayed, with price being wrong.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1993]
![Screen Shot 2022-06-26 at 12 44 13 PM](https://user-images.githubusercontent.com/85772166/175831299-34768be2-a03d-4b03-a11e-0e9247a7875a.png)

<img width="807" alt="Screen Shot 2022-06-26 at 12 46 28 PM" src="https://user-images.githubusercontent.com/85772166/175831310-b6c030e9-baf3-480c-b968-e7fa626c4e35.png">

Loading from the Stocks menu shows the correct price.

<img width="688" alt="Screen Shot 2022-06-26 at 12 48 41 PM" src="https://user-images.githubusercontent.com/85772166/175831394-ed473e40-4280-429f-9b96-baa6c395dc70.png">

**Comment by DidierRLopes** [comment]
Has been fixed by @soggyomelette, closing this!
