### ISSUE TITLE
[Bug] Crypto/DeFi/Lending - command is broken. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1994]
```
crypto/defi/lending

Error: 4 columns passed, passed data had 12 columns

Error: 'list' object has no attribute 'loc'
```
Flag for Current or Last 30 Days Average has a label that is inverse to function. `lending --current` to show the 30-day average is not ideal for an intuitive workflow. It is by default showing current so the flag should be labeled, something like `--average or -a`, to request the 30-day average. 

<img width="656" alt="Screen Shot 2022-06-26 at 12 59 08 PM" src="https://user-images.githubusercontent.com/85772166/175831777-903b8d47-ac2b-4939-8729-4393509d7814.png">

The description is missing a letter `ending --> lending`

<img width="743" alt="Screen Shot 2022-06-26 at 1 04 18 PM" src="https://user-images.githubusercontent.com/85772166/175831935-19c3edc9-aff3-490e-aa88-e1bedb07829e.png">

Not a bug, but a suggestion: the three commands of `funding, borrow, lending` could be consolidated as a single command `rates`, with optionality and arguments for the subcategories of funding, borrowing, and lending.

**Comment by hjoaquim** [comment]
@jose-donato do we still have this command?

**Comment by hjoaquim** [comment]
We've removed the functions based on defirate scraping here: https://github.com/OpenBB-finance/OpenBBTerminal/commit/b90025555b61f35430390314a92c754db865ddb1

@Chavithra @deeleeramone do we want to keep this one open?
