### ISSUE TITLE
[Bug] Stocks/BT/whatif - does not account for stock splits, which makes the answers wrong.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#1995]
```
(🦋) /stocks/bt/ $ whatif -d 2010-06-29 -n 100
If you had acquired 100 shares of TSLA on 2010-06-29 with a cost of 476.60.
These would be worth 73712.00. Which represents an increase of 15366.22%. 
```
In reality, you would have 5X the number of shares, and a significantly higher value.

<img width="278" alt="Screen Shot 2022-06-26 at 2 14 03 PM" src="https://user-images.githubusercontent.com/85772166/175834049-278c5889-65ee-4b11-bb76-a29e8a11fc08.png">

**Comment by deeleeramone** [comment]
If you bought 100 shares at IPO for $10, you would have 500 shares today, worth $710 each.

**Comment by soggyomelette** [comment]
Yes but the stock price takes that into account by showing the equivalent price if you bought 500 shares (i.e. $2) 
For TSLA, the price at IPO was $17 but the split-adjusted share price shows $3.40 so buying either 100 for $17 or 500 for $3.40, the value remains the same

**Comment by deeleeramone** [comment]
Problem solved then. :)

**Comment by soggyomelette** [comment]
Cheers!
