### ISSUE TITLE
[Bug] Cannot get `news` to use sources that I have provided

### ISSUE THREAD

**Issue by lazarillo** [OpenBB-finance/OpenBBTerminal#2005]
**Describe the bug**
I am not sure this is a bug.  It could be user error.

I have signed up for a few of the APIs as explained in the instructions and in the menu.  They passed as can be seen below.

<img width="1777" alt="Screen Shot 2022-06-28 at 15 52 31" src="https://user-images.githubusercontent.com/636798/176196183-5e9281e2-40a2-44a1-ba37-3d825b64d11e.png">

But when I then try to get news on any company, it fails.  Below is an example with Google... I figured I would use a "mega" company to test.

<img width="1767" alt="Screen Shot 2022-06-28 at 15 52 12" src="https://user-images.githubusercontent.com/636798/176196351-20303310-64a7-4a74-bebd-131922f6cd92.png">

I am able to get other things besides news, though:

<img width="424" alt="Screen Shot 2022-06-28 at 15 55 12" src="https://user-images.githubusercontent.com/636798/176196790-c3af1024-b3f0-4452-8fcb-951586e57c90.png">

**To Reproduce**
Add a few API keys, then try to get any news about them.

**Screenshots**
I embedded the screen shots above.

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]

MacOS Monterey 12.4

- Python version [e.g. 3.6.8]

I actually have several flavors of Python, but the default looks like it's 3.9.13.

```sh
❯ python --version
Python 3.9.13
```

**Additional context**
Add any other information that you think could be useful for us.

**Comment by wandesky** [comment]
Can you confirm if you have set the `news` API key under keys menu?

**Comment by lazarillo** [comment]
OK, that was the problem.  It wasn't clear to me that _**only**_ the `news` API provided "news".   Sorry for the dumb question.
