### ISSUE TITLE
[Bug] Error while setting binance API Key 

### ISSUE THREAD

**Issue by wandesky** [OpenBB-finance/OpenBBTerminal#2006]
**Describe the bug**
The application fails to add the Binance API key

**To Reproduce**
- downloaded the latest (28th June 2022) copy of the Windows installer from [openBB](https://openbb.co/products/terminal#get-started) downloads page
- Installed the application using default settings
- access the keys page
- try to set binance key by using command `binance myprivateAPIkey`

**Screenshots**
![image](https://user-images.githubusercontent.com/19204205/176201614-c624ac9d-1586-41ef-9bc4-ad11d4a33950.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Python version 3.9.6
![image](https://user-images.githubusercontent.com/19204205/176202100-bf82d8f2-a0af-48b8-8bfa-03697bdb363e.png)

**Additional context**
Other API keys setup commands appear to be working other than Binance

***Error Message(s)***
str expected not nonetype openbb
the following args couldn't be interpreted

**Comment by wandesky** [comment]
Running the command
`binance -k myAPIkey -s myAPIsecret`
appeared to successfully set the API key and secret. The challenge I'm facing now is that the key is not getting tested (defined, not tested). Not sure if there is a way  I can trigger the test from the CLI.
![image](https://user-images.githubusercontent.com/19204205/176213556-8b903b8e-c032-44b5-bbf3-a79e28a9c5d3.png)

**Comment by DidierRLopes** [comment]
This has been fixed by @soggyomelette ! Closing issue 😄
