### ISSUE TITLE
[IMPROVE] Improve plotting functionality and add delete option to Economy menu

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#2014]
**What's the feature that should be improved?**
Features from the `Economy` menu, specifically `macro`, `fred`, `index`, `treasury` and `plot`.

**Describe how you would like the feature improved**
From the discussion of this PR #1996  we should include the following:
- Add delete option to remove databases that you stored with `macro`, `fred`, `index` or `treasury`.
- Allow for more y-axises to be plotted in one graph with `plot` (max is now 2)
- **Advanced:** make it possible to `plot` data without needing to use `macro`, `fred`, `index` or `treasury`.

**Possibly describe the ideal way to improve this**

**Basic ones:**
Simply add in a feature or command that deletes databases and allow for more y-axes. Do note that it shouldn't be too big of a clusterfuck.

**For the advanced one:**
What I am looking for is the ability to plot data without needing to plot it first with the other functions, e.g. macro, fred, index. Right now, I first need to use those commands (and get two separate plots) before I can combine a graph with `macro` and `fred` data. That is kinda annoying.

Ideally, you want to plot both without needing to run the commands separately first. E.g. I say `plot --y1 United_States_CPI --y2 sp500` and it figures out the data comes from macro and index.

**Comment by deeleeramone** [comment]
It is really cumbersome to have to type a long name for a plot, especially when the autocomplete does not kick in after the first variable is used. It would be much more efficient to have an indexed table of the stored datasets where they can be called upon as single digit/letter variables, i.e., ` plot --y1 1,2 --y2 5,8`. 

1 Index SP600
2 Index SP400
3 Index Move
4 Fred FF
5 Fred SOFR
6 Treasury 2y_daily
7 Macro PPI_[2 letter country code]
8 Etc.
9 Etc.

Ideally, these datasets would continue to be stored even after exiting the Terminal and re-launching. Many of these series are weekly/monthly, having to find/load/store several seriesID every launch is a hindrance to productivity.
