### ISSUE TITLE
[Bug] /stocks/disc/divcal - Errors created because sort-by filter names are not the column headers.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2046]
```
(🦋) /stocks/disc/ $ divcal -s Indicated Annual Dividend -d 2022-07-06 -l 20
Error: 'Indicated Annual Dividend'
```
```
(🦋) /stocks/disc/ $ divcal -s Announcement Date -d 2022-07-06 -l 20
Error: 'Announcement Date'
```

No sorting applied:
<img width="866" alt="Screen Shot 2022-07-04 at 6 17 04 PM" src="https://user-images.githubusercontent.com/85772166/177231183-82472781-e556-4c8f-b1e9-3be2464c5ace.png">

Columns that are sortable according to autocomplete: 
<img width="649" alt="Screen Shot 2022-07-04 at 6 16 00 PM" src="https://user-images.githubusercontent.com/85772166/177231129-005acd3c-ae42-4c5b-93d8-70ec01e518ff.png">

**Comment by jmaslek** [comment]
oops.
