### ISSUE TITLE
[Bug] Error: No module named: "fundamentalanalysis"

### ISSUE THREAD

**Issue by benninkcorien** [OpenBB-finance/OpenBBTerminal#2047]
**Describe the bug**
/stocks/ $ fa
Error:  No module named: "fundamentalanalysis"

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

$ stocks
$ load CVX
$ fa

**Screenshots**
[Screenshot on Imgur of error](https://imgur.com/k0s7Iso)

API keys are set
[Screenshot on Imgur of API keys](https://imgur.com/aXyGZyU)

**Desktop (please complete the following information):**

- OS: Win11
- Python version 3.10.2

**Comment by deeleeramone** [comment]
This issue is related to: https://github.com/OpenBB-finance/OpenBBTerminal/issues/2049

Specific to the Windows `.exe` installer.

**Comment by andrewkenreich** [comment]
Yes you did months ago but for some reason my env for conda never updated the naming. It's updated now for the next release.

**Comment by JerBouma** [comment]
Great, @benninkcorien, please keep an eye out for the next release of the OpenBB Terminal and this will be fixed.
