### ISSUE TITLE
[Bug] Entering /stocks/sia causes colors to go away

### ISSUE THREAD

**Issue by dharmatech** [OpenBB-finance/OpenBBTerminal#2049]
**Description**
Entering the `/stocks/sia` menu causes the terminal menu colors to go away.

**Video**
I recorded the following video to demonstrate the issue (high res version should be available in a few hours):

https://youtu.be/QaXpZLzFptU

**Screenshots**

Normal menu with colors:

![image](https://user-images.githubusercontent.com/20816/177427577-3e75da47-4f49-418e-8a3c-ea631cdb49d4.png)

Menu after entering `/stocks/sia`. Note that the menu is now black and white:

![image](https://user-images.githubusercontent.com/20816/177427637-00d6c772-581f-4e98-9733-3e8a50d5f2f6.png)

**Desktop**

- OS: Windows 10
- Python version 3.8.13

**Comment by deeleeramone** [comment]
Can you try updating to version 1.5? There are a couple of known bugs with the Windows installer.

Screenshot here is from MacOS v1.5

![Screen Shot 2022-07-07 at 1 45 01 AM](https://user-images.githubusercontent.com/85772166/177731704-8bd9fa60-b910-4124-b292-e43b916babed.png)

**Comment by deeleeramone** [comment]
https://github.com/OpenBB-finance/OpenBBTerminal/releases/tag/v1.5.0

**Comment by dharmatech** [comment]
> Can you try updating to version 1.5? There are a couple of known bugs with the Windows installer.
> 
> Screenshot here is from MacOS v1.5
> 
> ![Screen Shot 2022-07-07 at 1 45 01 AM](https://user-images.githubusercontent.com/85772166/177731704-8bd9fa60-b910-4124-b292-e43b916babed.png)

I didn't use the Windows installer. I'm running from the latest on github.

**Comment by dharmatech** [comment]
> Your screenshot shows that you are on version 1.4.0, so your local copy and/or GitHub fork has not been updated.

I did a `git pull` and it brought in a bunch of changes. Partial output shown:

![image](https://user-images.githubusercontent.com/20816/177832095-2f32605b-b8fd-4a29-9ddd-0b483295bc65.png)

I then ran:

    pip install -r .\requirements.txt

However, when I run the terminal, it's still showing v1.4.0m:

![image](https://user-images.githubusercontent.com/20816/177832511-f35fdc42-5916-4860-9a40-94fef548ffa6.png)

Here's my git remote settings:

![image](https://user-images.githubusercontent.com/20816/177832638-ebeb9822-6756-4f0f-bb04-0340acc7d3f6.png)

Any suggestions?

**Comment by jmaslek** [comment]
Hey! You need to run `poetry install` after doing a git pull to 'finish' the update

**Comment by dharmatech** [comment]
> This also happens to people who are below a version of Linux Ubuntu. It can be helpful sometimes to update git and pip.
> 
> ```
> conda update git
> conda update pip
> ```

Ran both of these and it's still showing v1.4.0m.

**Comment by jmaslek** [comment]
This likely happens because of this in the feature flags

```
try:
    version = pkg_resources.get_distribution("OpenBBTerminal").version
except Exception:
    version = "1.4.0m"
```

I am not sure what the exception is.  If you wanted to change that to
```
except Exception as e:
   version="1.4.0m"
   print(e)
```
We could see what the error is (@piiq may know what's going on better than I).  AFAIK, requirements.txt doesn't install "OpenBBTerminal", but poetry does.

Anyways.  After all those installs, does the color go away in SIA menu?

**Comment by dharmatech** [comment]
> Anyways. After all those installs, does the color go away in SIA menu?

Yes, the menu still goes to black and white.

**Comment by piiq** [comment]
> However, after this completed, the terminal is still showing v1.4.0.m.

There is a problem on windows that in some cases poetry doesn't actually install the version. This is very Windows specific and we saw it a few times when non-conda python was used.

Just to confirm @dharmatech are you using python from conda?

**Comment by dharmatech** [comment]
Hey everyone,

I went ahead and setup a new clone of the repository and went through the latest installation steps as described here:

https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/README.md

And everything went smoothly this time! This is on Windows 10, not in WSL!

The first time I'd gone through the install, I recall there being issues with `poetry install`. Now it worked fine.

I'm in the `/stocks/sia` menu and the colors are still there:

![image](https://user-images.githubusercontent.com/20816/180594915-9c22eaa6-9cde-47a8-9346-dfe75fe786f0.png)

Thanks for everyone's patience and help. Feel free to close out this issue.
