### ISSUE TITLE
[Bug] The load doesn't work on a submenu due to where default sources is located

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2052]
<img width="571" alt="Screenshot 2022-07-06 at 15 36 37" src="https://user-images.githubusercontent.com/25267873/177578765-937cb335-8890-4e5e-bd6b-4b7cb71087bc.png">

**Comment by deeleeramone** [comment]
This also impacts other commands. 
```
(🦋) /stocks/dps/ $ psi
(🦋) /stocks/dps/ $
```
The terminal outputs nothing unless the `--source` flag is actively engaged.
