### ISSUE TITLE
[Bug] fundamentalanalysis model

### ISSUE THREAD

**Issue by interactivebroke** [OpenBB-finance/OpenBBTerminal#2078]
I added api keys to the terminal but it still shows Error: No module named 'fundamentalanalysis'

**To Reproduce**
stocks/ load ticker
fa 
Error: No module named 'fundamentalanalysis'

![terminal](https://user-images.githubusercontent.com/109185686/178623584-309aa447-cb2b-4ba3-ab4a-581aff90625d.png)

windows
I installed it through installer.
Thank you

**Comment by andrewkenreich** [comment]
Yes it is. Will be good next release

**Comment by andrewkenreich** [comment]
Yes it is, will be good next release

**Comment by Chavithra** [comment]
Will test that and close it if it's fixed.
