### ISSUE TITLE
[IMPROVE] Report output SEC filings Link is not a hyperlink

### ISSUE THREAD

**Issue by ghbcode** [OpenBB-finance/OpenBBTerminal#2081]
**What's the feature that should be improved?**
The report feature generates a PDF (from notebook) that includes an SEC filing section (in the Fundamental Analysis tab). The text is correct though it is not a hyperlink. It would be nice to be able to click on the link instead of copying the URL and opening after a paste into a browser window. 

**Describe how you would like the feature improved**
Create a hyperlink. Perhaps there is a simpler way though you could do this (I think):
df_sec_filings['Link'] = df_sec_filings['Link'].apply(lambda x: "<a href='{0}'>{0}</a>".format(x))

**Possibly describe the ideal way to improve this**
again there may be an easier way to get the notebook and the pdf to show a hyperlink.

**Additional information**
Both the notebook and pdf show the text not hyperlink. Though df_sec_filings.Link does parse correctly into a hyperlink.
![openbb_report_sec_filing](https://user-images.githubusercontent.com/25670636/178696071-11ea86e9-36d4-4940-a344-fcb9788e17e6.PNG)

**Comment by atericparker** [comment]
Given the SEC / edgar has a competent API, why pull from marketwatch in the first place. Could provide some code to do that if needed.

**Comment by DidierRLopes** [comment]
> Given the SEC / edgar has a competent API, why pull from marketwatch in the first place. Could provide some code to do that if needed.

Very much agreed @ghbcode! I can work on this.

That report was a draft that I worked on to show what the terminal was capable of, if you want you can let me know what you are interested to see and I can build a template for you :)

Yes please @atericparker ! If you could contribute with that, it would be very much appreciated 🙏🏽
