### ISSUE TITLE
[Bug] Crypto/Onchain Address doesn't work for users with ETH and no token values.

### ISSUE THREAD

**Issue by jfarid27** [OpenBB-finance/OpenBBTerminal#2094]
**Describe the bug**
Explorer address doesn't work when user has no token history.

**To Reproduce**
1. Take an address user with ETH and no tokens.
2. Navigate to crypto/onchain.
3. Load the address user.
4. Search for balances. Errors will appear.

**Screenshots**

<img width="711" alt="Screen Shot 2022-07-15 at 8 24 54 PM" src="https://user-images.githubusercontent.com/1673206/179327057-10cf4208-4536-4cff-8ab4-97e4491659e2.png">

Error appears because of the logic of the line below. It will attempt to convert a dictionary key that returns None if you have no token values.

https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/cryptocurrency/onchain/ethplorer_model.py#L235

**Desktop (please complete the following information):**

- OS: Mac
- Python version 3.8.13

**Additional context**
Send a message for test address if you need it.

**Comment by xrc-20** [comment]
https://binance.zendesk.com/hc/requests/suggestion_click?data=BAh7CToTc3VnZ2VzdGlvbnNfaWRJIikyMDFhYjUwMi02Yzc0LTQyZmMtODVlYi1hODFlNjU4ZmM2M2IGOgZFRjoPYXJ0aWNsZV9pZGwrCADfw8YaADoIdXJsSSJZaHR0cHM6Ly9iaW5hbmNlLnplbmRlc2suY29tL2hjL2VuLXVzL2FydGljbGVzLzExNTAwMzg3NTA3Mj9pbnB1dF9zdHJpbmc9cGVyc29uZWwrdnJyBjsGVDoLbG9jYWxlSSIKZW4tdXMGOwZU--10199e2fbb6d1c9134d80f71a8d5eb9b426ccc3a
