### ISSUE TITLE
[IMPROVE] (cryptocurrency/news) Add clickable hyperlinks to dataframe print outputs

### ISSUE THREAD

**Issue by jfarid27** [OpenBB-finance/OpenBBTerminal#2098]
**What's the feature that should be improved?**
News hyperlinks in crypto dd should be clickable.

**Describe how you would like the feature improved**
Currently hyperlinks in crypto are not clickable. Ideally, they should be clickable and open a new browser window.

**Possibly describe the ideal way to improve this**
Links that are shown through `pandas` dataframes that format table values automatically, and also truncate them. I'm not sure how to get the dataframe print to show a clickable hyperlink, but maybe a wrapper formatter where devs can specify a link column, and transform it to something clickable would suffice. 

This has to be possible since I see clickable terminal links.

**Additional information**

### Related Issues
#2081 

### Screenshot
<img width="1368" alt="Screen Shot 2022-07-16 at 11 37 30 PM" src="https://user-images.githubusercontent.com/1673206/179382790-e01c77fb-7939-4bbd-b145-562e6e5eb63c.png">

**Comment by DidierRLopes** [comment]
I believe this has to do with the terminal app you are currently using to run the terminal.

On my machine, as you can see bellow I can follow those links:
<img width="1412" alt="Screenshot 2022-07-18 at 09 48 34" src="https://user-images.githubusercontent.com/25267873/179476134-1fc514b8-9c62-4173-8d8f-858f2c36564d.png">

I'm using the `bash` integrated in `VSCode`.


I've looked into this and from what I understood, this is always down to the terminal being able to interpret these links. @piiq can you confirm this?

**Comment by piiq** [comment]
There is another problem that print output truncates the link to what fits onto the screen and if the link is long - it will not be a valid link. Maybe that can be addressed?

**Comment by DidierRLopes** [comment]
It still works @piiq 

<img width="781" alt="Screenshot 2022-07-18 at 13 50 51" src="https://user-images.githubusercontent.com/25267873/179515057-58949e09-a7a4-4fde-9718-ee680f846f1f.png">
