### ISSUE TITLE
[FR] (Crypto) Add Perpetuals Funding Rate Data

### ISSUE THREAD

**Issue by jfarid27** [OpenBB-finance/OpenBBTerminal#2099]
# What's the problem of not having this feature?

I'm interested in seeing Perpetuals Options Funding Rates on the OpenBB platform. Usually, I like to use this as a bullish or bearish signal since traders showing willingness to pay this funding rate gives a good Longs vs. Shorts metric. Typically I take a look at the overview on [this page to see in general if rates are more negative, or more positive.](https://www.coinglass.com/FundingRate) 

Coinglass provides aggregate data for the top coins across the major perpetuals markets: Binance, FTX, Bybit, and Okex.

# Describe the solution you would like

Perpetuals funding rate data can be shown from [CoinGlass here](https://coinglass.github.io/API-Reference/#funding-rates-chart). On first glance this would require two updates.

## Update `keys` to accept Coinglass API Keys

- When a user is in the `keys` menu, they should be able to add a `coinglass` API key.

## Add a `perps` menu option in crypto after a Symbol is loaded

- When a user has loaded a crypto symbol that matches the options provided by Coinglass, they should be able to see `perps` funding rates via the API.

## Add a `perps` menu option in `crypto/ov`, showing a general table of all available symbols.

<img width="1322" alt="Screen Shot 2022-07-17 at 8 59 45 AM" src="https://user-images.githubusercontent.com/1673206/179399514-1b5546ab-ea7a-44dd-bd4b-25c1b9a095c7.png">

- When a user is in the `ov` menu, they should be able to see a table of funding rates from all available symbols.
- If a user gives a flag, it should be possible to generate a color coded popup table to users can get a sort of visual representation of how the market is generally pricing crypto perpetuals.

# Describe alternatives you've considered

## Binance API

The Binance API has this data as well [here](https://binance-docs.github.io/apidocs/futures/en/#get-funding-rate-history), but it looks like Coinglass aggregates this data across multiple sources. The tradeoff of using only Binance is that while Binance may have more symbols as well since they're the largest market provider of perpetual options, Coinglass shows aggregate data of major tokens across multiple exchange operators.

# Additional information

An introduction to Perpetual Options can be found [here](https://www.paradigm.xyz/2021/03/the-cartoon-guide-to-perps) that explains their features.

**Comment by jose-donato** [comment]
<img width="978" alt="image" src="https://user-images.githubusercontent.com/43375532/180657076-3c17d2a2-1da0-40df-b194-8a578b3ca7f8.png">

Added to dd menu for individual coins since we already had a feature from coinglass there it was really easy to add funding rate also

will work later on adding to `ov` menu a table as you suggested
