### ISSUE TITLE
[IMPROVE] Options/Chains - This feature can't be used by most people because Tradier no longer offers developer access, and requires a brokerage account. There is no alternate source for data.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2115]
There is a problem with the Options menu, I would consider it pretty important because it will affect any new user. While Tradier offered free developer access to their data, it was a great source; however, those days are over and now every user will require a brokerage account in order to get an API token for options data. For people such as myself, from Canada, you are not allowed to have an account there. The core features within this menu rely heavily on Tradier, and thus, are blocked for the majority of users.

<img width="1139" alt="Screen Shot 2022-07-19 at 1 29 31 PM" src="https://user-images.githubusercontent.com/85772166/179842496-12972190-34e0-414c-840f-9c633e397e3d.png">

Tradier: https://developer.tradier.com

![Screen Shot 2022-07-19 at 1 50 23 PM](https://user-images.githubusercontent.com/85772166/179845935-14624bce-1025-4448-8a39-7e92cd033dd6.png)

Problem: new users will not be able to functionally use this, and other functions because there is no alternative source. 

Solution: As a public service, the OCC publishes 15 minute delayed quotes for all listed US options. This is a clean source of data, and is published for public dissemination purposes, by the industry. 

https://www.optionseducation.org/toolsoptionquotes/options-quotes

Adding this as a source will restore functionality to all features in the Options menu with a single source. 

There is also the opportunity to incorporate Polygon endpoints for Options, as well as yFinance. This would give users more choices, and would allow the features to use data from any source.

**Comment by deeleeramone** [comment]
As a very quick fix, yFinance should be made a source for `chains`. How quick is that for a band-aid, @jmaslek?

**Comment by jmaslek** [comment]
> As a very quick fix, yFinance should be made a source for `chains`. How quick is that for a band-aid, @jmaslek?

It shouldn't be too hard, we just need to merge in the `greeks` command

**Comment by jmaslek** [comment]
i fixed dis
