### ISSUE TITLE
[Bug] Options/exp - `exp` shows dates, but selecting causes error: Expiration `2022-07-27` cannot be found. Available expirations are: []

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2117]
Unable to select expiration date for ticker that is valid, with listed expiration dates, when source = tradier. 

To reproduce, use the ticker VIX.

load VIX - from Tradier
load ^VIX --source yf  - from yFinance

```
(🦋) /stocks/options/ $ load SPX

Error: Expiration `2022-07-27` cannot be found. Available expiration are: []

(🦋) /stocks/options/ $ exp

  Available expiry dates   
┏━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Identifier ┃ Date       ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 0          │ 2022-07-21 │
├────────────┼────────────┤
│ 1          │ 2022-07-22 │
├────────────┼────────────┤
│ 2          │ 2022-07-25 │
├────────────┼────────────┤
│ 3          │ 2022-07-26 │
├────────────┼────────────┤
│ 4          │ 2022-07-27 │
├────────────┼────────────┤
```

<img width="567" alt="Screen Shot 2022-07-20 at 11 41 22 PM" src="https://user-images.githubusercontent.com/85772166/180146677-4c5522b9-d0be-47c5-9497-acefb8fa0eb9.png">

<img width="985" alt="Screen Shot 2022-07-20 at 11 43 21 PM" src="https://user-images.githubusercontent.com/85772166/180147080-deb918cf-23cf-49d0-ba4d-fdda416bdb9f.png">

![Screen Shot 2022-07-20 at 11 42 42 PM](https://user-images.githubusercontent.com/85772166/180146925-28af5125-98a9-4e26-b14a-7053959f341f.png)

**Comment by colin99d** [comment]
I am not able to recreate this issue. If I try to use VIX it works fine, and SPX returns no expiration dates. This might not be accurate, but we cannot control the data that yfinance sends. Is this still an issue for you?

**Comment by deeleeramone** [comment]
Still an issue, seems to be only Tradier now. 

--source tradier - can't set any expiration date
<img width="617" alt="Screen Shot 2022-07-29 at 2 17 30 PM" src="https://user-images.githubusercontent.com/85772166/181844197-8125d871-2ee3-440f-90ea-e61ad6796258.png">

--source yfinance - working
<img width="509" alt="Screen Shot 2022-07-29 at 2 18 20 PM" src="https://user-images.githubusercontent.com/85772166/181844288-8da44340-ef93-46a6-8209-4d7eaf65d62a.png">
