### ISSUE TITLE
[Bug] Stocks - Screener - overview can't be sorted by P/E

### ISSUE THREAD

**Issue by ffilipus** [OpenBB-finance/OpenBBTerminal#2119]
**Describe the bug**
Overview with sort by P/E can't be performed, when on the stocks screener page (/stocks/scr/), after a selection of preset i.e. cheap_dividend.

OpenBB windows version - OpenBB Terminal v1.5.0 installer.

**To Reproduce**
1. Go to `/stocks/scr`, enter `stocks` and `scr` from root menu.
2. Select a preset, i.e. `set cheap_dividend`
3. Get overview sorted by P/E, `overview -s P/E`

**Screenshots**
![Overview](https://user-images.githubusercontent.com/6762631/180200316-ea641fa1-190d-4df3-b9b7-cff4b0e214dd.png)

**Desktop (please complete the following information):**

- OS: Windows 10, x64
- Tested with 1) default launcher from Start Menu and 2) from Terminal (https://github.com/microsoft/terminal) with same results.

**Comment by DidierRLopes** [comment]
This is a known issue because of the way users can create a pipeline of commands. E.g. you can type something like this: `stocks/disc/ugs` and it should give you data directly. Or one step further and build an `file.openbb` that has automated commands.

#2064 should fix this once merged! 🙏🏽

**Comment by piiq** [comment]
fixed by #2064
