### ISSUE TITLE
[Bug] Login Issues with Degiro Broker integration

### ISSUE THREAD

**Issue by perezpaya** [OpenBB-finance/OpenBBTerminal#2120]
### Issue

When attempting to use the Degiro integration while having provided succesfully my user name, password and otp secret, login fails with this output and no other actions are allowed.

```bash
2022 Jul 21, 13:16 (🦋) /portfolio/bro/degiro/ $ login
Error: 'NoneType' object is not callable

You are now logged in !

2022 Jul 21, 13:16 (🦋) /portfolio/bro/degiro/ $ topnews
Error: 'NoneType' object is not callable

Error: 'list' object has no attribute 'DESCRIPTOR'
```

### To reproduce
```bash
export OPENBB_DG_USERNAME={} OPENBB_DG_PASSWORD={} OPENBB_DG_TOTP_SECRET={}
/Applications/OpenBB\ Terminal/OpenBB\ Terminal
portfolio/bro/degiro
login
```
- OS: macOS Monterrey
- Python version 3.6.8

### Additional
I've tried using directly the `degiro_connector` library (the one your integration is using) and it was possible to login providing the same credentials. IMO we can discard that my account has a specific issue that makes the library fail.

![image](https://user-images.githubusercontent.com/1226151/180202501-84cdedc6-fe2f-4503-8768-3f60b276538c.png)

**Comment by perezpaya** [comment]
Any updates on this? Anything I can do for helping?

**Comment by montezdesousa** [comment]
Hi @perezpaya, apparently you were not logged in.

There were some issues solved by this PR https://github.com/OpenBB-finance/OpenBBTerminal/pull/2234. We also updated login instructions here https://openbb-finance.github.io/OpenBBTerminal/terminal/portfolio/bro/degiro/.

Can you check if you still have problems?
