### ISSUE TITLE
[Bug] v1.6 [all] - Economy: Cannot enter prediction or QA menus with stored datasets. Error: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2130]
<img width="1220" alt="Screen Shot 2022-07-21 at 8 13 46 PM" src="https://user-images.githubusercontent.com/85772166/180354969-b4ea2619-5438-4005-9c89-873090242f3e.png">

```
(🦋) /economy/ $ qa
Error: single positional indexer is out-of-bounds
```

**Comment by DidierRLopes** [comment]
This was broken recently with changes on economy menu (@JerBouma @montezdesousa next time try to remember to check pred/qa as well since they depend on the ticker)

Should get fixed on: https://github.com/OpenBB-finance/OpenBBTerminal/pull/2150

**Comment by cheeeeee** [comment]
I may be doing something wrong, but I have the most recent openBB release and this bug appears to still be occurring. Pred menu functions fine in the forex menu but doesn't in economy.
