### ISSUE TITLE
[FR] Is there any way to get this working on Replit? Could get folks setup in a few clicks.

### ISSUE THREAD

**Issue by sorenrood** [OpenBB-finance/OpenBBTerminal#2132]
I think a one-click setup option would be super useful for folks who want to try this out without having to set everything up locally.

**Comment by sorenrood** [comment]
Here's an example of what it could look like: https://replit.com/@GLiQue/ASCII-ART-GENERATOR?v=1

(random terminal app I found)

**Comment by jmaslek** [comment]
Closing as stale, but the Platform CLI release should be usable on replit.  We have tutorials on https://replit.com/@openbb
