### ISSUE TITLE
docker pull denied error

### ISSUE THREAD

**Issue by dumabg** [OpenBB-finance/OpenBBTerminal#2133]
`docker pull` gives a denied error:

```
docker pull ghcr.io/gamestonkterminal/gst-poetry:latest
Error response from daemon: Head "https://ghcr.io/v2/gamestonkterminal/gst-poetry/manifests/latest": denied

```

**Comment by franalbani** [comment]
Try `docker pull ghcr.io/openbb-finance/openbbterminal-poetry:latest`. I believe the website is outdated.

Source: https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/README.md#docker-installation

**Comment by DidierRLopes** [comment]
Yes, we need to update our Docker solution. Thanks!

@aia is this something you have some minutes to help with? 😄

**Comment by colin99d** [comment]
This is updated.
