### ISSUE TITLE
Licensing correct?

### ISSUE THREAD

**Issue by S-c-o-t-t-i-e** [OpenBB-finance/OpenBBTerminal#2134]
Hey guys, just saw your work, very nice job! I was just wondering about your licensing which enables any usage (including commercial - interesting for me), but your data (at least partly) is from yahoo finance (which does not allow commercial use).

Would be great to hear from you! Thanks

Ferdi

**Comment by DidierRLopes** [comment]
Hey @S-c-o-t-t-i-e,

As an MIT license, you can use OpenBB Terminal for anything commercial in terms of the source code: leverage our architecture / structure, use our paper mill notebook integration, our pipeline of commands, NLP models, yada yada

**However**, the data that is available through our platform **does not belong to us.** Thus, for you to be able to use it in a commercial setting, you would need to speak with the data providers of interest directly (e.g. Yahoo Finance).

At the end of the day we are a gateway to data providers, but do not have neither license rights neither redistribution rights to the data. This is also why each user needs to run the terminal on their machine, and OpenBB is not allowed to store or process any data through our servers.

**Comment by S-c-o-t-t-i-e** [comment]
Thank you for that quick explanation. Any chance you have an overview of your vendors somewhere?

All the best

**Comment by DidierRLopes** [comment]
> Thank you for that quick explanation. Any chance you have an overview of your vendors somewhere?
> 
> All the best

No problem! You can find most of the ones we are leveraging here: https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/config_terminal.py

Hope that's helpful!
