### ISSUE TITLE
Error in starting the terminal.py code.

### ISSUE THREAD

**Issue by Samar-080301** [OpenBB-finance/OpenBBTerminal#2139]
**Describe the bug**
Error in running the terminal.py script after following the instructions provided on the website. I followed the commands given on the website and tried installing it on ubuntu using anaconda. But when I ran the `python3 terminal.py` it returned an error as
```
Traceback (most recent call last):
  File "/home/samar/OpenBBTerminal/terminal.py", line 20, in <module>
    from openbb_terminal.core.log.generation.path_tracking_file_handler import (
  File "/home/samar/OpenBBTerminal/openbb_terminal/core/log/generation/path_tracking_file_handler.py", line 11, in <module>
    from openbb_terminal.core.log.collection.log_sender import LogSender
  File "/home/samar/OpenBBTerminal/openbb_terminal/core/log/collection/log_sender.py", line 10, in <module>
    from openbb_terminal.feature_flags import LOG_COLLECTION
  File "/home/samar/OpenBBTerminal/openbb_terminal/feature_flags.py", line 21, in <module>
    i18n.load_path.append(i18n_dict_location)
AttributeError: module 'i18n' has no attribute 'load_path'
```

**To Reproduce**
Steps(from the start) and commands given on [this website using anaconda method](https://openbb.co/products/terminal#get-started)

**Desktop (please complete the following information):**

- OS: [Ubuntu VERSION="20.04.4 LTS (Focal Fossa)"]
- Python version [3.9.12]

**Comment by kr3kls** [comment]
Duplicate issue. Ubuntu 20.04.4 is not currently compatible with this project. Please see the issue below for update instructions.

https://github.com/OpenBB-finance/OpenBBTerminal/issues/2125#issuecomment-1192110776

**Comment by sautplat** [comment]
Getting the same issue on mac os X

`from openbb_terminal import api as openbb`

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 from openbb_terminal import api as openbb

File ~/OpenBBTerminal/openbb_terminal/api.py:4, in <module>
      1 """OpenBB Terminal API."""
      2 # flake8: noqa
      3 # pylint: disable=unused-import
----> 4 from .stocks import stocks_api as stocks
      5 from .alternative import alt_api as alt
      6 from .cryptocurrency import crypto_api as crypto

File ~/OpenBBTerminal/openbb_terminal/stocks/stocks_api.py:6, in <module>
      1 """Stocks context API."""
      2 # flake8: noqa
      3 # pylint: disable=unused-import
      4 
      5 # Context root level functions
----> 6 from openbb_terminal.common.newsapi_view import display_news
      7 from openbb_terminal.common.newsapi_model import get_news
      8 from .stocks_helper import load, process_candle, search, quote

File ~/OpenBBTerminal/openbb_terminal/common/newsapi_view.py:8, in <module>
      4 import logging
      6 import pandas as pd
----> 8 from openbb_terminal.decorators import check_api_key
      9 from openbb_terminal.common import newsapi_model
     10 from openbb_terminal.decorators import log_start_end

File ~/OpenBBTerminal/openbb_terminal/decorators.py:8, in <module>
      5 import os
      6 import pandas as pd
----> 8 from openbb_terminal import feature_flags as obbff
      9 from openbb_terminal.rich_config import console
     11 logger = logging.getLogger(__name__)

File ~/OpenBBTerminal/openbb_terminal/feature_flags.py:21, in <module>
     14 # pylint: disable=no-member
     16 i18n_dict_location = (
     17     os.path.join(os.path.dirname(os.path.abspath(__file__)), "i18n")
     18     if os.path.exists(os.path.join(os.path.dirname(os.path.abspath(__file__)), "i18n"))
     19     else os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "i18n")
     20 )
---> 21 i18n.load_path.append(i18n_dict_location)
     22 i18n.set("locale", "en")
     23 i18n.set("filename_format", "{locale}.{format}")

AttributeError: module 'i18n' has no attribute 'load_path'`

**Comment by sautplat** [comment]
I ran into the same issue, it's related to the package not installed.

`pip install python-i18n
`
