### ISSUE TITLE
[Bug]Funds/info - Command is dead.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2140]
```
(🦋) /funds/ $ info
Error: Document is empty

Error: 'list' object has no attribute 'reset_index'
```
![image](https://user-images.githubusercontent.com/85772166/180517423-79095be2-6a46-41e6-ab36-8c07b5ca67b3.png)

Temporary workaround is to load the symbol from the `stocks` menu, and use the Fundamental Analysis functions to retrieve this data.

**Comment by laaksonel** [comment]
I could not reproduce with the current version (tip of the main branch)

![image](https://user-images.githubusercontent.com/5064947/180607538-582a1469-d7fb-4a38-aed7-e466eaeffa9e.png)

**Comment by DidierRLopes** [comment]
Thanks @laaksonel for testing this. I had the same experience as you:
 
<img width="675" alt="Screenshot 2022-07-23 at 18 38 12" src="https://user-images.githubusercontent.com/25267873/180616550-e2dd7cfe-2115-4bbd-a372-0fcd4ff2de6b.png">

Will close the ticket based on that.

**Comment by deeleeramone** [comment]
I'm still receiving the same error, even after updating from main.
<img width="1242" alt="Screen Shot 2022-07-23 at 1 45 17 PM" src="https://user-images.githubusercontent.com/85772166/180622354-c145dced-e605-4f6c-a576-00b92fd7f2ba.png">

**Comment by deeleeramone** [comment]
updating to include these notes:

- also occurs for me with the M1 installer package
- does not occur on another computer using the Intel version of the installer.

**Comment by deeleeramone** [comment]
Updating to report that another user has experienced the same issue as me who has both M1 and Intel machines. The Intel version works fine, but the M1 does not. The problem is likely in the dependency chain.
