### ISSUE TITLE
[Bug]Forex/candle - triggers a user warning and pyplot.pause(0.1)

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2142]
The source does not appear to make a difference. Every time `candle` is run from the Forex menu, this happens:

```
(🦋) /forex/ $ /Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/menu.py:15: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  pyplot.pause(0.1)
```

<img width="1327" alt="Screen Shot 2022-07-22 at 1 16 33 PM" src="https://user-images.githubusercontent.com/85772166/180521590-ecda8348-0462-4646-8d82-4765661c026e.png">

**Comment by DidierRLopes** [comment]
<img width="1391" alt="Screenshot 2022-07-23 at 18 29 14" src="https://user-images.githubusercontent.com/25267873/180616247-e24cd924-57a2-4f44-98e4-b31e66b48cd0.png">

I cannot recreate this

**Comment by deeleeramone** [comment]
Perhaps this is another "Mac M1"-specific item.

<img width="1317" alt="Screen Shot 2022-07-24 at 2 53 19 PM" src="https://user-images.githubusercontent.com/85772166/180667296-a9c1a200-63bc-4fe0-bac5-f83ecdbb5f12.png">

**Comment by deeleeramone** [comment]
I didn't figure out what setting was causing this, but I resolved it by deleting the contents of the user styles folder.
