### ISSUE TITLE
[Bug] flair - 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by dharmatech** [OpenBB-finance/OpenBBTerminal#2146]
When I try to run the following `flair 😀`, under '/settings', the result is the error shown below:

![image](https://user-images.githubusercontent.com/20816/180595213-3065f03c-eba3-4aa6-a6c6-fddcf340e0cb.png)

Consider having a more graceful error message when this issue occurs.

**Desktop (please complete the following information):**

- OS: Windows 10
- Python version 3.9.13

**Comment by DidierRLopes** [comment]
<img width="1298" alt="Screenshot 2022-07-23 at 18 19 40" src="https://user-images.githubusercontent.com/25267873/180615883-3356d633-4231-439f-b608-199a6a9c20a4.png">

Sorry, I implemented that and it was working on my machine. Am assuming that the reviewer also was using the same OS, where emojis were supported. Unfortunately, I cannot recreate this.

@piiq @tehcoderer @piiq this one is up for grabs, who's taking it?
