### ISSUE TITLE
[FR] Add TD Ameritrade to Broker List

### ISSUE THREAD

**Issue by raviolispy** [OpenBB-finance/OpenBBTerminal#2149]
**What's the problem of not having this feature?**
I'd like to be able to import a TD Ameritrade portfolio automatically like Ally Invest. 

**Describe the solution you would like**
A description of what you think would be the best solution for this. From user inputs, to an output.

**Describe alternatives you've considered**
If there are other alternatives (worth considering) to your solution, list them here. 

**Additional information**
https://github.com/areed1192/td-ameritrade-api

**Comment by aleksanderleyfman** [comment]
They have a get account/get accounts API call that should be able to support this:
https://developer.tdameritrade.com/account-access/apis

**Comment by JerBouma** [comment]
It is on our roadmap to provide these integrations (including many other brokers) so they can be directly imported inside the `portfolio` menu for now. We are also happy to provide guidance if you wish to design this yourself.

**Comment by aleksanderleyfman** [comment]
Is there a template to follow?

**Comment by JerBouma** [comment]
If you are looking to contribute via a Pull Request, you can do so by following these steps:

1. Fork the Project
2. Create your Feature Branch (git checkout -b feature/AmazingFeature)
3. Install the pre-commit hooks by running: pre-commit install. Any time you commit a change, linters will be run automatically. On changes, you will have to re-commit.
4. Commit your Changes (git commit -m 'Add some AmazingFeature')
5. Push to your Branch (git push origin feature/AmazingFeature)
6. Open a Pull Request

Keeping note of our guidelines: https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md

**Comment by JerBouma** [comment]
In my opinion, it will require too many steps for the average user to get to work and we can not expect them to install some third party software (selenium) next to OpenBB. My suggestion would be that we allow support for loading in a CSV or Excel file containing the person's transactions that the user downloads directly from the TD Ameritrade website.

We are also in talks with Snaptrade (https://snaptrade.com/) which could be a neat integration at some point.

**Comment by JerBouma** [comment]
I think for now it is fine we provide support for the CSV even if it is limited. At a later stage we can extend this when there are more users interested. Would be awesome if you could work on that! :)

**Comment by jmaslek** [comment]
Feel free to ping me if you have any questions.  I have my TD stuff setup so can check out.

**Comment by fivetwentysix** [comment]
Can we also setup OpenBB to get ticker information such as intraday candles and such?
