### ISSUE TITLE
/stocks/ins/act - Function fails when --source Polygon. Error: Timestamp('2022-04-01 00:00:00')

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2164]
A chart is made, but it does not draw the insider trading activity. 

```
(🦋) /stocks/ins/ $ load aapl --source polygon

(🦋) /stocks/ins/ $ act
Error: Timestamp('2022-04-01 00:00:00')
```
Source is Polygon:
<img width="1344" alt="Screen Shot 2022-07-24 at 4 39 14 PM" src="https://user-images.githubusercontent.com/85772166/180670584-b6a2db1a-d85c-46d5-a86d-f0bc077cad79.png">

Source is yFinance:
![image](https://user-images.githubusercontent.com/85772166/180670719-3f30a051-d00f-4e33-a9e9-0fe82d84ecbc.png)

**Comment by colin99d** [comment]
Fixed
