### ISSUE TITLE
[IMPROVE] Add in Andreas Clenow Volatility Adjusted Momentum

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#2170]
**What's the feature that should be improved?**
Andreas Clenow Volatility Adjusted Momentum column / indicator for stocks. See for more information here: https://www.quant-investing.com/blog/this-easy-to-use-adjusted-slope-momentum-strategy-performed-7-times-better-than-the-market.

As this is momentum, this could be part of the `ta` menu.

**Describe how you would like the feature improved**
Takes sum of 90 day least squares of Log Prices,  then annualises to give a slope value (in decimals for expected yearly return assuming momentum continues). Filters out any stocks that have gapped up/down by 15% to leave true momo stocks.

**Additional information**
This comes from feedback from the [Request a Feature form](https://openbb.co/request-a-feature).

**Comment by jmaslek** [comment]
can I do this one :D

**Comment by JerBouma** [comment]
@jmaslek Go ahead and have fun, never heard of this indicator.

**Comment by jmaslek** [comment]
> @jmaslek Go ahead and have fun, never heard of this indicator.

Me neither :P

**Comment by aksingh11** [comment]
I have been trying to replicate the clenow indicator metric on excel following the method in the original method by the andreas clenow in his book stocks on the move . here is the methodology . ranking by the above method we get a different factor ( Annualised Slope*R squared) than the one calculated by openbb/stocks/ta/clenow. In fact the fitness coefficient seems to be missing from Andreas Clenow's method. 
I am sure there is a reasonable explanation to this and its just that i dont know it.

**Comment by aksingh11** [comment]
[book extract ](https://media.discordapp.net/attachments/831166136800116786/1028871324891877438/Screenshot_2022-10-10_at_08.53.03.png)
