### ISSUE TITLE
While using stocks getting error 

### ISSUE THREAD

**Issue by chinni505** [OpenBB-finance/OpenBBTerminal#2175]
While trying to access stocks getting below error.

Error: 'setuptools_scm.parse_scm'

2022 Jul 25, 10:41 (🦋) / $ stocks
Error: 'setuptools_scm.parse_scm'

**Comment by colin99d** [comment]
Hello, is this from the installer or did you install manually using conda?

**Comment by deeleeramone** [comment]
Users have reported being able to work around this issue by installing WSL:

https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/README.md#installing-wsl-only-for-windows-users
