### ISSUE TITLE
$settings/ - issues Entering setting with no values

### ISSUE THREAD

**Issue by HoughtonSam** [OpenBB-finance/OpenBBTerminal#2177]
This issue was found on OpenBB Terminal v1.6.0 relating to the settings page with the fact that you can enter the value for the functions as nothing ('None') (this accounts for all of the settings on that page) 

Example: 
2022 Jul 25, 14:51 (🦋) /settings/ $ dpi
output in the .env file OPENBB_PLOT_DPI='None' 

Then if the terminal window is then closed without that setting being amended back to default. 
the next time the terminal is opened it outputs this error.
![Screenshot (100)](https://user-images.githubusercontent.com/109986376/180852700-b8a7cf19-df58-41c3-b5c3-91ec06c88255.png)

The Fix for this was going into the .env file and just below the API keys (if any are set) the new set settings should be there, its just a case of removing the troublesome ones (any with the value set to 'None' saving the file. then upon re-opening OpenBB the program will work again. 

Suggested fix would be to stop the Settings page from allowing you to set a Setting with no value.

**Comment by jmaslek** [comment]
Nice catch.  For height/width and DPI, I made the value a required field.

**Comment by jmaslek** [comment]
#2197
