### ISSUE TITLE
[Bug] /stocks/fa/key: --export does not function.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2181]
Reported by a support request, and recreated by me:

```
/stocks/load goog/fa/key --export xlsx
```

![Screen Shot 2022-07-25 at 9 33 40 PM](https://user-images.githubusercontent.com/85772166/180924138-1b13fb1a-66c4-4a31-ae73-122753d5713d.png)

**Comment by jmaslek** [comment]
boop #2184
