### ISSUE TITLE
An error occured while executing a docker command for installing the OpenBB image.

### ISSUE THREAD

**Issue by Samar-080301** [OpenBB-finance/OpenBBTerminal#2183]
**Describe the bug**
I copied this command `docker pull ghcr.io/gamestonkterminal/gst-poetry:latest ` from the [tutorial](https://openbb.co/products/terminal#get-started). But after executing the command in my bash shell, I got an error as.
```
Error response from daemon: Head "https://ghcr.io/v2/gamestonkterminal/gst-poetry/manifests/latest": denied
```

**Desktop :**

- OS: [Ubuntu VERSION="20.04.4 LTS (Focal Fossa)"]
- Python version [3.9.12]
- Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1

**Comment by aaronsgithub** [comment]
I came across the same issue.

The link in the tutorial seems to be out of date.

This page has a link to a different docker image which works:
https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/README.md#docker-installation

**Comment by colin99d** [comment]
Great find guys! I got this over to our web development guy and he is updating!
