### ISSUE TITLE
/fa Error: No module named 'fundamentalanalysis'

### ISSUE THREAD

**Issue by RylandCapital** [OpenBB-finance/OpenBBTerminal#2185]
**Describe the bug**
Error: No module named 'fundamentalanalysis'

1. why is /fa (and all the others to be honest) greyed out and give me the above options. why cant I use /fa /ta etc. 

thanks!

**To Reproduce**
/stocks/fa

**Screenshots**
![image](https://user-images.githubusercontent.com/16804873/181098360-87412f69-b729-43f8-bb0b-2c3770b1dd38.png)

**Desktop (please complete the following information):**

- windows 10
- installer latest

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
Hello, this was an error that has been patched in version 1.6.0. Are you certain you have this version installed? Please check that you are not using v1.5.0.

https://github.com/OpenBB-finance/OpenBBTerminal/releases/tag/v1.6.0

**Comment by colin99d** [comment]
Hello, the other options will be usable once you load a ticker. Try `load gme` and then press `h` to see the menu again.

**Comment by colin99d** [comment]
Are you still having any issues with the terminal, or did updating resolve the issues?

**Comment by RylandCapital** [comment]
it worked great! i had the most updated version but I just needed to load the ticker and boom.

thank you for your help!

**Comment by colin99d** [comment]
Good to hear!! Let me know if you have any other issues.
