### ISSUE TITLE
[Bug] stocks/dps/shorted - No data found

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2187]
```
(🦋) /stocks/dps/ $ shorted
No data found.
```

<img width="1056" alt="Screen Shot 2022-07-26 at 5 07 32 PM" src="https://user-images.githubusercontent.com/85772166/181133033-8c248d8e-35a9-4157-b59e-0e4ab82a5739.png">

**Comment by jmaslek** [comment]
Hmmm.  Peeking at this two days later and looking at the request gives the following response:

```
 'Will be right back...  Thank you for your patience.  Our engineers are working quickly to resolve the issue.'
```

**Comment by deeleeramone** [comment]
I guess they took the table away because I did see that message in a rich table the other day, and then it went away.

**Comment by jmaslek** [comment]
I found fix :nft-james:

**Comment by jmaslek** [comment]
#2197 (note the request needed a user-agent)
