### ISSUE TITLE
[Bug] Economy/macro - nan values give error.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2193]
There are many countries where World Bank, Fred, BIS, or other, sources have gaps in reports or are not current. The `macro` function currently displays an error message in the place of a more polite message indicating that there is not any reported data. 

![image](https://user-images.githubusercontent.com/85772166/181433712-0492e1bb-a6f1-4f94-b5b1-beeb0b630f9c.png)

Error is only when there are `nan` values present:

![image](https://user-images.githubusercontent.com/85772166/181434490-3523397e-4427-4eab-95c8-7f84c9e17f99.png)

```
(🦋) /economy/ $ macro -p GDEBT -c Italy
```

![](https://cdn.discordapp.com/attachments/831166136800116786/1002093762731851826/Screen_Shot_2022-07-27_at_11.00.41_PM.png)

**Comment by jmaslek** [comment]
#2197
