### ISSUE TITLE
Feature $stocks/load gme/dd/rating doesn't seem to be working 

### ISSUE THREAD

**Issue by HoughtonSam** [OpenBB-finance/OpenBBTerminal#2195]
On version 1.6 of the program i don't seem to be able to get the ratings [Source: FMP] function to work. I have tested all of the other functions on this page $stocks/dd and all are working. Potentially this could just be an issue with the data source coming from FMP themselves. 

![DD-rating](https://user-images.githubusercontent.com/109986376/181502914-a06eb079-1ffc-439a-be00-aef166ad9bcd.jpg)

i've also enquired about other functions that use FMP as a data source to do some further testing on if it is an issue with their steam.

**Comment by deeleeramone** [comment]
I am not able to recreate. Did you register with FMP and enter your API key in the `keys` menu? 

If this is the case, at the very least, there should be an error message indicating that no API key was found. 

![Screen Shot 2022-07-28 at 8 43 29 AM](https://user-images.githubusercontent.com/85772166/181580688-7e0bc985-36ab-4227-8eff-1fbad62d88bd.png)

**Comment by HoughtonSam** [comment]
Sadly yeah i am. I've definitely got the correct key too. I've tried this on other tickers too incase it was a lack of data issue. but same thing unfortunately 

![KEYS](https://user-images.githubusercontent.com/109986376/181582263-4641b723-04e5-4524-b90d-6498475701e9.jpg)
![GME](https://user-images.githubusercontent.com/109986376/181582276-eb2a7605-8ace-46bf-800a-583d58e947cb.jpg)
![TSLA](https://user-images.githubusercontent.com/109986376/181582277-b3eeb9db-c5cf-4b31-9f21-ada907f13025.jpg)

**Comment by deeleeramone** [comment]
This doesn't appear to be the problem with OP, but there is a related bug here where there is no message indicating an API key is required for this function.
