### ISSUE TITLE
[Bug] crypto/headlines goes wild

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#2199]
<img width="811" alt="Screen Shot 2022-07-28 at 8 35 03 PM" src="https://user-images.githubusercontent.com/18151143/181659334-d33d647a-e83a-4582-9306-52d3340bb5d2.png">

**Comment by jmaslek** [comment]
feel like this is because I messed with settings, but I have PLOT_DPI = 300 and plot autoscaling on

**Comment by colin99d** [comment]
Are you still having this issue? Command works fine for me.

**Comment by soggyomelette** [comment]
Yeah not able to recreate this one
