### ISSUE TITLE
[IMPROVE] Portfolio should figure out whether ticker is stock or ETF automatically

### ISSUE THREAD

**Issue by raviolispy** [OpenBB-finance/OpenBBTerminal#2217]
**What's the feature that should be improved?**
The portfolio loading feature.

**Describe how you would like the feature improved**
Currently the portfolio loading tool will fail on ETFs labeled as stocks. The portfolio loading tool should be able to intelligently discern whether a ticker (perhaps ambiguously labeled as "equity") is a single stock or an ETF rather than the user having to specify.

**Possibly describe the ideal way to improve this**
yfinance has an quoteType field which is "EQUITY" for a single stock and "ETF" for an ETF. 
![image](https://user-images.githubusercontent.com/62662248/182042518-9fe3ea37-27fa-49a4-a69d-ccce011709a0.png)

**Additional information**
I think the portfolio loading documentation is also slightly out of date - the examples in the repo work but the tool doesn't work exactly as described on the docs (w.r.t optional columns specifically).

**Comment by JerBouma** [comment]
The only downside with this method is that it is going to be very time-consuming. E.g. let's say my portfolio consists of 100 instruments. Collecting the info of all 100 will be very slow. Nonetheless a good enhancement when the labelling isn't applied by the user.
