### ISSUE TITLE
[Bug] Reports/1 throws error when downloaded data has problems or if no data is available for that symbol

### ISSUE THREAD

**Issue by ngoel17** [OpenBB-finance/OpenBBTerminal#2219]
**Describe the bug**
When certain API's return empty or when they return values but the values are not as expected (nan instead of a number for example), the reports module throws an error. This is very common for small/mid-cap companies because of less activity. 

**To Reproduce**
reports/1 cbz

**Screenshots**
Error: 
---------------------------------------------------------------------------
Exception encountered at "In [13]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/opt/anaconda3/envs/obb/lib/python3.9/site-packages/pandas/core/indexes/base.py:3621, in Index.get_loc(self, key, method, tolerance)
   3620 try:
-> 3621     return self._engine.get_loc(casted_key)
   3622 except KeyError as err:

File ~/opt/anaconda3/envs/obb/lib/python3.9/site-packages/pandas/_libs/index.pyx:136, in pandas._libs.index.IndexEngine.get_loc()

File ~/opt/anaconda3/envs/obb/lib/python3.9/site-packages/pandas/_libs/index.pyx:163, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:5198, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:5206, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'target_to'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Input In [13], in <cell line: 2>()
      2 if not df_analyst.empty:
      3     if "target" in df_analyst.columns:
----> 4         df_analyst["target_to"] = df_analyst["target_to"].combine_first(df_analyst["target"])
      5     df_analyst = df_analyst[["category", "analyst", "rating", "target_to"]].rename(
      6         columns={
      7             "category": "Category",
   (...)
     11         }
     12     )
     13 df_analyst

File ~/opt/anaconda3/envs/obb/lib/python3.9/site-packages/pandas/core/frame.py:3505, in DataFrame.__getitem__(self, key)
   3503 if self.columns.nlevels > 1:
   3504     return self._getitem_multilevel(key)
-> 3505 indexer = self.columns.get_loc(key)
   3506 if is_integer(indexer):
   3507     indexer = 

File ~/opt/anaconda3/envs/obb/lib/python3.9/site-packages/pandas/core/indexes/base.py:3623, in Index.get_loc(self, key, method, tolerance)
   3621     return self._engine.get_loc(casted_key)
   3622 except KeyError as err:
-> 3623     raise KeyError(key) from err
   3624 except TypeError:
   3625     # If we have a listlike key, _check_indexing_error will raise
   3626     #  InvalidIndexError. Otherwise we fall through and re-raise
   3627     #  the TypeError.
   3628     self._check_indexing_error(key)

KeyError: 'target_to'

**Desktop (please complete the following information):**

- OS: Mac Sierra
- Python version [e.g. 3.6.8]: 3.9.13

**Additional context**
Add any other information that you think could be useful for us.
   I think I am referring to more than one bug. If you would ask me to test on a branch, I will be happy to test with some of the symbols I have been testing with and point out all the other ones as they are fixed.

**Comment by ngoel17** [comment]
A more graceful behavior would be to either put a NAN in the missing value of output or Color that report red and flag it with data problems and move on instead of abandoning the entire report.

**Comment by ngoel17** [comment]
Another example
 /reports/ $ 1 RCL
Executing:  39%|██████████████████████████████████████████▏                                                                 | 16/41 [00:31<00:48,  1.95s/cell]
Error: 
---------------------------------------------------------------------------
Exception encountered at "In [13]":
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/opt/anaconda3/envs/obb/lib/python3.9/site-packages/pandas/core/indexes/base.py:3621, in Index.get_loc(self, key, method, tolerance)
   3620 try:
-> 3621     return self._engine.get_loc(casted_key)
   3622 except KeyError as err:

File ~/opt/anaconda3/envs/obb/lib/python3.9/site-packages/pandas/_libs/index.pyx:136, in pandas._libs.index.IndexEngine.get_loc()

File ~/opt/anaconda3/envs/obb/lib/python3.9/site-packages/pandas/_libs/index.pyx:163, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:5198, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:5206, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'target_to'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Input In [13], in <cell line: 2>()
      2 if not df_analyst.empty:
      3     if "target" in df_analyst.columns:
----> 4         df_analyst["target_to"] = df_analyst["target_to"].combine_first(df_analyst["target"])
      5     df_analyst = df_analyst[["category", "analyst", "rating", "target_to"]].rename(
      6         columns={
      7             "category": "Category",
   (...)
     11         }
     12     )
     13 df_analyst

File ~/opt/anaconda3/envs/obb/lib/python3.9/site-packages/pandas/core/frame.py:3505, in DataFrame.__getitem__(self, key)
   3503 if self.columns.nlevels > 1:
   3504     return self._getitem_multilevel(key)
-> 3505 indexer = self.columns.get_loc(key)
   3506 if is_integer(indexer):
   3507     indexer = 

File ~/opt/anaconda3/envs/obb/lib/python3.9/site-packages/pandas/core/indexes/base.py:3623, in Index.get_loc(self, key, method, tolerance)
   3621     return self._engine.get_loc(casted_key)
   3622 except KeyError as err:
-> 3623     raise KeyError(key) from err
   3624 except TypeError:
   3625     # If we have a listlike key, _check_indexing_error will raise
   3626     #  InvalidIndexError. Otherwise we fall through and re-raise
   3627     #  the TypeError.
   3628     self._check_indexing_error(key)

KeyError: 'target_to'

**Comment by colin99d** [comment]
Thanks for this bug!! Allowed me to add some good error handling throughout the codebase.
