### ISSUE TITLE
Bug] Crypto/OV/HM - limit of 50 returns Error: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2220]
When the limit touches 50, this error message displays.

```
 /crypto/ov/ $ hm stablecoins -l 50
Error: cannot convert float NaN to integer
```

When a `category` is selected, the % of market cap should then be calculated as relative to the % of the chosen category, and not the entire market cap of all cryptos. This is why everything is crowded into one tiny corner while the biggest pieces are fractions of one percent. 

![Screen Shot 2022-07-31 at 8 04 59 PM](https://user-images.githubusercontent.com/85772166/182064202-39205617-4179-4b2f-b17a-3e4d15e9a19f.png)

![Screen Shot 2022-07-31 at 8 06 41 PM](https://user-images.githubusercontent.com/85772166/182064352-9ee4ac57-4fdb-41c3-9e7d-a7a4814fab76.png)

**Comment by deeleeramone** [comment]
The help dialogue indicates this is ranked by market cap, but this is clearly not the % of BTC's market cap. There is nowhere to indicate what this value is, why it's there, and what it has to do with the % of total market cap.  

![Screen Shot 2022-07-31 at 8 14 47 PM](https://user-images.githubusercontent.com/85772166/182065118-74771253-2d38-4f22-abdd-1778bf75c6a7.png)

**Comment by soggyomelette** [comment]
@deeleeramone the % here represents the daily percentage change in the currency - I've updated the help for the hm command to say the same, hopefully that helps?

**Comment by deeleeramone** [comment]
@soggyomelette One would eventually make that logical leap as a conclusion, but knowing the % change from today does little to help situations such as the screenshot above, the Top 20 Stable Coins. Ranking stable coins by a market cap value relative to the entire market makes all stable coins = 0% by the time you introduce rounding. This is why the large majority of coins are right on top of each other and is unreadable.

**Comment by soggyomelette** [comment]
> @soggyomelette One would eventually make that logical leap as a conclusion, but knowing the % change from today does little to help situations such as the screenshot above, the Top 20/40 Stable Coins. Ranking stable coins by a market cap value relative to the entire market makes all stable coins = 0% by the time you introduce rounding. This is why the large majority of coins are right on top of each other and is unreadable.

It's just that looking at other heatmaps online (like this one https://www.tradingview.com/heatmap/stock/?color=change&dataset=SPX500&group=sector&size=market_cap_basic) I saw they used the percentage in the center to denote the same thing so I thought I would leave it unchanged. 

Also, looking at the code, it does in fact rank them relative to the category you choose but the market cap of some of the later stable coins is so minute that they get dwarfed by the much larger stable coins (https://www.coingecko.com/en/categories/stablecoins? for example check the market of $65B of USDT with even the 20th coin   with $108M - it's almost a 1000x less

**Comment by deeleeramone** [comment]
I suppose the issue is in the clarity of the purpose for the function, and communicating that to the user. The text is also insanely small. Is there a way to auto-scale the size of the text?

![Screen Shot 2022-08-07 at 4 08 08 PM](https://user-images.githubusercontent.com/85772166/183314599-66c41d89-2b03-43a8-8f23-123aaefada67.png)

**Comment by soggyomelette** [comment]
Regarding the clarity, that's why I updated the help to reflect the fact that the percentage denoted is the daily percentage change, is there something else that can be changed to make it clearer to the user?

Also, I had a go at scaling text sizes and here's what it looks like:
![image](https://user-images.githubusercontent.com/85685255/183616656-0a3a6a1a-d98f-4fea-885b-55a588272e11.png)

I think it's definitely better since there's no more crowding in the corners

**Comment by deeleeramone** [comment]
Nicely done!
