### ISSUE TITLE
[IMPROVE] Date format for display is inconsistent, and not what the user enters to define the window of observation.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2222]
The way to select start and end periods for time-series is, YYYY-MM-DD.

The way that dates are displayed in tables is not consistent with this and creates confusion when they are presented in a different way.

For example, we have DD-MM-YYYY:
```
2022 Aug 01, 01:58 /economy/ $ ecocal -c china -i all -s 2022-07-31 -e 2022-08-05 -l 500 --export xlsx --raw

                                             Economic Calendar (GMT -4:00)                                             
┏━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┓
┃ date       ┃ time  ┃ zone  ┃ currency ┃ importance ┃ event                           ┃ actual ┃ forecast ┃ previous ┃
┡━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━┩
│ 02/08/2022 │ 21:45 │ china │ CNY      │ medium     │ Caixin Services PMI  (Jul)      │        │          │ 54.5     │
├────────────┼───────┼───────┼──────────┼────────────┼─────────────────────────────────┼────────┼──────────┼──────────┤
│ 31/07/2022 │ 21:45 │ china │ CNY      │ high       │ Caixin Manufacturing PMI  (Jul) │ 50.4   │ 51.5     │ 51.7     │
└────────────┴───────┴───────┴──────────┴────────────┴─────────────────────────────────┴────────┴──────────┴──────────┘
```
The here we have YYYY-MM-DD + Time:

<img width="1343" alt="Screen Shot 2022-07-31 at 11 10 31 PM" src="https://user-images.githubusercontent.com/85772166/182083298-ddb19c5b-a9e6-451a-b0c5-f1d83c616af5.png">

Then there is month as an abbreviation: 

![Screen Shot 2022-07-31 at 11 14 45 PM](https://user-images.githubusercontent.com/85772166/182083918-39705af3-eb7f-40eb-88d2-dff25957355e.png)

This chart displays YYYY-MM-DD:

![Screen Shot 2022-07-31 at 11 16 03 PM](https://user-images.githubusercontent.com/85772166/182084120-6419e0aa-8e47-4001-aba8-5c951b6b5b0c.png)

```
2022 Aug 01, 02:18 /funds/ $ load vfiax
2022 Aug 01, 02:19 /funds/ $ plot
```

Here we are YYYY-MM:

![Screen Shot 2022-07-31 at 11 19 30 PM](https://user-images.githubusercontent.com/85772166/182084536-0ac6e9b1-533c-4a90-bd41-7e43a6c8818d.png)

These are just a few examples, of which there are many more. Perhaps we can keep a thread going that identifies all the spots.

**Comment by deeleeramone** [comment]
The advantage of YYYY_MM_DD is that it sorts properly. Other configurations lead to problems with sort-by-date functions.

**Comment by deeleeramone** [comment]
Intraday shows time, but it is not helpful. Showing intraday that references market open/close and pre/post market times would be more helpful to the user. 

![Screen Shot 2022-08-01 at 1 05 20 AM](https://user-images.githubusercontent.com/85772166/182102470-9aeb5025-b00c-42b6-9623-cf32f3873539.png)

**Comment by DidierRLopes** [comment]
The API restructure should be handling all of these. So bring this up with @minhhoang1023 if you find any issues, but the API 2.0 will have this fixed.
