### ISSUE TITLE
[Bug]  tcgetpgrp failed: Not a tty

### ISSUE THREAD

**Issue by tinix84** [OpenBB-finance/OpenBBTerminal#2232]
**Describe the bug**
After producing report, 
error display:  tcgetpgrp failed: Not a tty

**To Reproduce**
reports
equity AAPL

**Screenshots**
![image](https://user-images.githubusercontent.com/16301528/182305822-923ba771-50cc-4b42-8e47-3c2129e42dc3.png)

**Desktop (please complete the following information):**

- OS: WSL ubuntu
- Python version 3.9

**Additional context**
Add any other information that you think could be useful for us.

**Comment by colin99d** [comment]
Looks like this is a WSL specific issue: https://stackoverflow.com/questions/50882266/using-jupyter-with-windows-subsystem-for-linux. Can someone using WSL take a look at this?

**Comment by Chavithra** [comment]
Closing this issue since it's pending for a while.

Feel free to open another ticket or reach us on Discord.
