### ISSUE TITLE
No module named 'openbb_terminal'

### ISSUE THREAD

**Issue by wajihwajeh** [OpenBB-finance/OpenBBTerminal#2237]
In your site(https://openbb-finance.github.io/OpenBBTerminal/api/) it says to type "from openbb_terminal import api as openbb" in python script but that brings an error " No module named 'openbb_terminal'"

**Comment by JerBouma** [comment]
It's important you open your Notebook from the OpenBB Terminal folder. E.g. as follows:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/46355364/182611377-6eca03c3-bec4-4411-928e-7ef5e2c258e0.png">
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/46355364/182611448-03516402-2c4d-43cf-b6d5-e2e96b952096.png">
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/46355364/182611581-5c58c6f6-70cc-4a19-89b0-2c5ad91a28c4.png">

**Comment by JerBouma** [comment]
> Did that, had a bunch of modules that I had to install, roughly 40, now I am stuck on binance.client module showing an error "No module named 'binance.client'; 'binance' is not a package" even though I installed all packages it required

Did you follow the instructions as stated here? https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/README.md#anaconda--python

**Comment by colin99d** [comment]
It looks like this is an issue installing the terminal in a conda environment. If you cannot figure it out feel free to reach out on Discord: Charlestons#0746.

**Comment by gsegatti** [comment]
In case someone else has a similar issue. running `pip install -r requirements.txt` outside of the conda environment did it for me, like Colin mentioned above.
