### ISSUE TITLE
VWap [Bug]

### ISSUE THREAD

**Issue by jmmartinnu2** [OpenBB-finance/OpenBBTerminal#2242]
**Describe the bug**
Not correctly calculating the functionality of this volume-weighted [average](url)
![unknown](https://user-images.githubusercontent.com/93231115/182596187-8bfb9760-7436-4c65-b264-02f10f3dac16.png)

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by jmaslek** [comment]
Hey!  VWAP is calculated on a daily basis (see below).  So if you have the daily chart, all you will see is the close price.

![image](https://user-images.githubusercontent.com/18151143/182597867-10572e7f-4cc8-4e65-a20e-e652b7daa7ae.jpeg)
