### ISSUE TITLE
[FR] Add an `esg` menu displaying information and news for a loaded `stock`.

### ISSUE THREAD

**Issue by jfarid27** [OpenBB-finance/OpenBBTerminal#2245]
# **What's the problem of not having this feature?**

I'm interested in having a menu for ESG related news and metrics for a given loaded company. I'm not sure of a news source in particular but I'd like to start a search for some data feeds on this and try to implement it. An overview of the companies ESG metrics, scores, and news would be interesting and adding a new menu seems appropriate.

At the very least, a `metrics` option should be available that exposes yfinance's `sustainability` data if available.

# **Describe the solution you would like**
`stocks/esg` should load an esg menu for the loaded ticker, only after loading. There could be something like `metrics` and `news` in this menu.

## Metrics

<img width="311" alt="Screen Shot 2022-08-03 at 3 32 36 PM" src="https://user-images.githubusercontent.com/1673206/182693930-2721a1b8-0288-47e8-ad8f-dbdd1127fd9b.png">

[yfinance has a "sustainability" option mentioned in the documentation.](https://pypi.org/project/yfinance/). Above is an example of the option with `META`. Possibly wrapping this in a pandas dataframe would be nice so this can also be nice to work with in jupyter contexts.

## News

I'm open to suggestions but I'm not sure of a good solution to this. It doesn't seem like there's a focused ESG aggregator but maybe opening the conversation to others to suggest something would be nice. Ideally this feed could show climate and other ESG related news. Maybe a google search with '+esg' would be interesting, or even parsing reddit?

# **Describe alternatives you've considered**
None.

# **Additional information**
None

**Comment by jmaslek** [comment]
Hey!  We actually do have the yahoo finance sustainability in `stocks/fa/sust`.  Maybe thats not the most obvious place for it,,,

@JerBouma has been keen on ESG for quite a while so feel free to shoot him ideas.

**Comment by jfarid27** [comment]
@jmaslek maybe this is a docs issue then? I see now the `sust` but actually, now that I'm looking at this menu, a lot of the menu items are labeled with the terminal code. Maybe an improvement would be also adding a second more human readable explanation on the side.

Currently looks like this.

<img width="239" alt="Screen Shot 2022-08-03 at 3 46 45 PM" src="https://user-images.githubusercontent.com/1673206/182696202-e64ebd5e-5b4b-49bb-9a82-5d71e06cbedb.png">

Could look like this?
<img width="239" alt="Screen Shot 2022-08-03 at 3 48 57 PM" src="https://user-images.githubusercontent.com/1673206/182696479-1ad61bad-0a77-4d39-aa47-8de894144a12.png">

**Comment by JerBouma** [comment]
The suggestions is great @jfarid27 but it unfortunately blows up the menu size significantly. Some commands are abbreviations for rather long terminology. E.g. `lpsb` means Latest Penny Stock Buys.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/46355364/182849294-b0d83473-8187-4436-97c1-6984eb503233.png">

Furthermore, you have the ability to search for these terms. E.g. when I search for `sustainability`:

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/46355364/182849444-4cdc374c-a089-4dc4-9559-322b4374d3f9.png">

Or just Google:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/46355364/182849517-d6b5693d-26e9-43fc-a913-ecbde07ef115.png">

**Comment by JerBouma** [comment]
About the menu itself, this is indeed something that we need to build at some point. ESG data is, however, often paid and thus we need to look at our options in this regard (if you have suggestions for APIs with free tiers that would be great). In my opinion, it shouldn't even reside under `stocks` but be a completely separate menu because you might also want to understand geographically how certain countries or states are affected by climate change, changing employee conditions and government actions

**Comment by DidierRLopes** [comment]
For a start we could rename `sust` command to `esg` 😄 

Agree with the `ESG` menu, or even being on the "alternative".

Closing this for now
