### ISSUE TITLE
What it shows are not pennystocks /stocks/disc/ $ hotpenny

### ISSUE THREAD

**Issue by jmmartinnu2** [OpenBB-finance/OpenBBTerminal#2252]
**Describe the bug**
this menu when launching the pennystocks command should show shares of less than 1 dollar! that's the pennystocks.. right now it throws other information when that command is called
![penny-stocks](https://user-images.githubusercontent.com/93231115/183034463-edc389e4-a2d1-47a5-9990-c44dc1f78c4f.png)

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by DidierRLopes** [comment]
The source we are using is from here: https://www.pennystockflow.com

Do you have any API suggestion?

**Comment by colin99d** [comment]
Maybe we just rename the command to hotstocks? I think if they were super low volume you could maybe still argue it but these "hot" ones have plenty of volume. Any thoughts @JerBouma. This would probably be a 30 second fix.

**Comment by JerBouma** [comment]
@colin99d @DidierRLopes 

I have no idea what I am looking at when I visit https://www.pennystockflow.com/. Why is this the list of "hot stocks"? I'd rather scrape something like this: https://finance.yahoo.com/u/yahoo-finance/watchlists/most-active-penny-stocks/

I know it's not ideal to scrape but what we are currently showing to me is completely random.

**Comment by colin99d** [comment]
I am just gonna add both of these as sources. I will still leave pennystockflow, but a disclaimer will print when someone uses it.
