### ISSUE TITLE
[IMPROVE] Add in Investor’s Business Daily Relative Price Strength (RS)

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#2254]
**What's the feature that should be improved?**
This feature can be obtained from an already public repository found here: https://github.com/skyte/relative-strength. It is the _Yearly performance of stock (most recent quarter is weighted double) divided by yearly performance of reference index (SPY by default)._

**Describe how you would like the feature improved**
Simply be able to load in the following two files (that are generated daily):

- Stocks: https://github.com/skyte/rs-log/blob/main/output/rs_stocks.csv
- Industries: https://github.com/skyte/rs-log/blob/main/output/rs_industries.csv

Do note the disclaimer: _Unfortunately the close prices loaded from the price history API are not always split adjusted. So if a stock had a split recently there is a chance the relative strength value will be wrong._

**Additional information**
IBD Style Relative Strength Percentile Ranking of Stocks (i.e. 0-100 Score): https://education.investors.com/financialdictionary.aspx?mode=1&term=Relative+Price+Strength+(RS)+Rating+or+Relative+Strength&termid=1

**Comment by soggyomelette** [comment]
@JerBouma I can add this as is but atm, it only returns the top 30 percentile of stocks so it'll run into an error most of the time. I was thinking of forking the repo, changing the config file, and hosting the modified outputs directly from my page. Is this something you would recommend or is there another alternative?

**Comment by JerBouma** [comment]
Hi @soggyomelette, feel free to do so!
