### ISSUE TITLE
[IMPROVE] Stocks/Disc - Improve `hotpenny` function by updating source to: https://www.allpennystocks.com/hotpennystocks/nsd.aspx

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2258]
The current source for this function in the Discovery menu is, https://pennystockflow.com. There are no filters or the capability to refine the returned results. Updating the source to use: https://www.allpennystocks.com/hotpennystocks/nsd.aspx would improve functionality and broaden the coverage of penny stocks. Filters at the source offer price bands, market venues, and sortable columns. 

![Screen Shot 2022-08-05 at 11 32 41 AM](https://user-images.githubusercontent.com/85772166/183139823-05c05983-ba15-4ffb-8112-ed1d6a67e9d2.png)

**Comment by DidierRLopes** [comment]
We only want to incorporate APIs going forward. Closing this ticket based on that

**Comment by deeleeramone** [comment]
Copy that. I will advise people to use the stock screener instead of this function.
