### ISSUE TITLE
[Bug] Options - VOI function is not returning the correct values. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2259]
The `voi` function in the options menu is not returning correct values. These screenshots were taken while the market was open. It is most easily noticed at the $22.50 strike.

![Screen Shot 2022-08-05 at 12 56 34 PM](https://user-images.githubusercontent.com/85772166/183152573-ff73cab2-535e-4ad9-ad62-db39cd2eeb1d.png)
![Screen Shot 2022-08-05 at 12 57 53 PM](https://user-images.githubusercontent.com/85772166/183152631-50907119-5320-4728-a352-e12d69107335.png)

![image](https://user-images.githubusercontent.com/85772166/183154735-86124052-0287-42b5-a8c5-141d9fec3516.png)

As a sidenote, this chart would be much easier to read if the strike price was the X-axes. This would prevent crowded labels for very dense chains. The `vol` and `oi` charts are very easy to read, and I would much rather see the volume + open interest chart  presented in the same way - a double y-axes.

**Comment by colin99d** [comment]
I am going to attack this now.

**Comment by mubbud** [comment]
Any luck in setting up the correct representation of Volume and OI bars combined using "voi" in options...?

**Comment by jmaslek** [comment]
Looks like #2613 should have closed this
