### ISSUE TITLE
stocks/disc not entirely working

### ISSUE THREAD

**Issue by jnyilas** [OpenBB-finance/OpenBBTerminal#2272]
**Describe the bug**
I am having problems with:
gainers, losers, ugs, gtech, active, ulc, asc.

All of these seem to be pulling from yahoo (no API key required).
lsof is showing connections to:
https://69.147.65.252/
https://69.147.65.251/

**To Reproduce**
/stocks/disc/gainers
.. etc ...

**Screenshots**
022 Aug 08, 12:13 (🦋) /stocks/disc/ $ gainers

                                                    Gainers                                                     
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ 0                                                                                                            ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Will be right back...  Thank you for your patience.  Our engineers are working quickly to resolve the issue. │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Desktop (please complete the following information):**

- OS: Linux
- Python version 3.9

**Additional context**
This is a fresh install of obb using anaconda.

I have not changed any of the default API sources.
The error is coming from the yahoo finance end. This can be verified by using your browser to fetch the above URL.

My question is, is there a better yahoo URL to use for OBB out of the box? finance.yahoo.com is working and I can see the top gainers report there.

Still learning and exploring, but this is really a wonderful tool. Thank you for making this available to everyone!!!

**Comment by colin99d** [comment]
Good find!
