### ISSUE TITLE
[Bug] Stocks/Insider/stats: when exporting `stats` function, fields are populated with `[red]value[/red]`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2274]
When exporting `stats` function, fields are populated with `[red]value[/red]`. The user must remove all of these from the entire file before it can be used.

<img width="955" alt="Screen Shot 2022-08-08 at 11 26 50 AM" src="https://user-images.githubusercontent.com/85772166/183487619-7856622f-bc6e-4874-9710-af6ca0320a0c.png">
<img width="948" alt="Screen Shot 2022-08-08 at 11 29 01 AM" src="https://user-images.githubusercontent.com/85772166/183488033-e33fe876-9052-493a-89a8-2602b3782191.png">

**Comment by colin99d** [comment]
Lol. this should be a quick fix.
