### ISSUE TITLE
Income command should also specify the type of currency.

### ISSUE THREAD

**Issue by ArcD7** [OpenBB-finance/OpenBBTerminal#2285]
**What's the feature that should be improved?**
The income command in the stocks menu returns a table without specifying the currency in which values are being returned.

**Describe how you would like the feature improved**
Small statement showing the currency, like the one in Yahoo Finance

**Possibly describe the ideal way to improve this**
The API you are querying is probably return the type of currency or something based on the location of the compnay.

**Additional information**
![Income statement](https://user-images.githubusercontent.com/46811622/183905503-08b28bd9-2cf1-4591-82cd-8f940b48428a.jpg)

**Comment by jmaslek** [comment]
I did this. In #2498 

Albeit--this will only impact yahoo source
