### ISSUE TITLE
[Bug] Load missing today

### ISSUE THREAD

**Issue by WyattLiu** [OpenBB-finance/OpenBBTerminal#2293]
**Describe the bug**
Load QQQ will not include today's price. 

**To Reproduce**
Load any stock from yh

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Python version [3.8.13]

**Additional context**
Highly suggest "quote" today's price so we can do some real-time analysis. Otherwise, analysis has to be done at midnight

**Comment by deeleeramone** [comment]
Hello, you can use the function `quote`. There is also an interval selection for the load function that allows intraday. Use the `-h` flag to display all the optional arguments for a command. 

This post might help you get what you need: https://www.reddit.com/r/openBB/comments/w2d8w7/daily_command_for_monday_july_18_2022_candle/

**Comment by WyattLiu** [comment]
The intra-day is not a free option. with yh, load grabs everything excluding today and I want today's value to be the value we see in the quote command. Under the hood, the list/array should use the yh csv + a fresh yh quote.

Why: this way we can use pred command. Do you agree?

**Comment by deeleeramone** [comment]
Yes, it is free. Use, `--source yf`

**Comment by WyattLiu** [comment]
I know yf is free, the thing is that yh does not give intra day. Even if it gives, pred does not work with that as you stated.

that is what I am trying to convey here. We need pred to work today's price, preferred a fresh quote.

say prices are [102 104 108] + (110) where 110 is a fresh quote or closing price of today. then we can use pred. It requires code change to load with some helper functions from the quote command.

I have no issue using load or pred or quote.

I don't recall if the "no today" issue existed from gamestonk era.

**Comment by deeleeramone** [comment]
Here is the entire trading day, pre/post, in 5-minute candles.

```
/stocks/ $ load spy -i 5 -s 2022-08-10 -p
```


![Screen Shot 2022-08-10 at 10 02 15 PM](https://user-images.githubusercontent.com/85772166/184067632-69c31b80-e47c-497b-a169-b91e80d1c0fb.png)

**Comment by WyattLiu** [comment]
Thank you, but I am loading daily value simply load QQQ so I can call pred

**Comment by deeleeramone** [comment]
Loading a daily price would mean EOD price, which is not reported during market hours.

**Comment by WyattLiu** [comment]
Sure, but the behavior is that it does not give a price even after the market hour, it only gives when the system time is the next day.

**Comment by deeleeramone** [comment]
If you are attempting to `load` a stock where the price is before EOD, you must use the intraday flag, `-i`.

**Comment by deeleeramone** [comment]
![Screen Shot 2022-08-10 at 10 12 49 PM](https://user-images.githubusercontent.com/85772166/184068392-6730b320-a94c-49d6-a7d6-977a10a07c7b.png)

**Comment by WyattLiu** [comment]
sure, I know, for us to see, it is ok. but just a bit off when using pred

**Comment by deeleeramone** [comment]
I encourage you to attend this event, which will preview the upcoming Forecast menu, which will replace the Prediction menu: https://discord.gg/hx4JS73P?event=1006682810590969876

**Comment by WyattLiu** [comment]
thank you, we will see.
