### ISSUE TITLE
[IMPROVE] get_macro_data function improvement.

### ISSUE THREAD

**Issue by eidnanrohod1** [OpenBB-finance/OpenBBTerminal#2299]
Hey guys! This is my first interaction in the open source world, so please excuse me if I'm not clear. I noticed that the function “get_macro_data” that performs the connection between OpenBB and EconDB to import the data via API works with the parameters listed in the PARAMETERS dictionary and the country codes listed in the COUNTRY_CODES dictionary (OpenBBTerminal-maino\openbb_terminal\economy\ ecodb_model.py).
With this, it is possible to use the API only for the parameters already listed. However, there are several other tickers available in EconDB that would be possible to access, if the restriction imposed by “PARAMETERS” was flexible or incremented.
Given such an obstacle, I would like to suggest two ways to overcome this. The first involves the creation of a new function, similar to “get_macro_data”, but that allows the search for generic tickers, without the need for country inputs.
The second way just involves adding a new argument inside the “get_macro_data” function to allow the search for tickers not listed inside PARAMETERS and which have no equivalents in COUNTRY_CODES.
Which solution makes the most sense to you?
As the second solution seemed easier to me, I have already performed it. I'll make available the new code of the function that allows this generic search right below and feel free to use it, if it makes sense.
Example of a generic ticker in the API that is not accessible today:

import pandas as pd
df = pd.read_csv(
'https://www.econdb.com/api/series/BCB_SELIC.422.D.BR/?format=csv',
index_col='Date', parse_dates=['Date'])

**SECOND-WAY POSSIBLE SOLUTION**: [opendb get_macro_data function improvement](https://github.com/eidnanrohod1/OpenBBTerminal.git)

`
def get_macro_data(
    parameter: str,
    country: str,
    start_date=pd.to_datetime("1900-01-01"),
    end_date=datetime.today().date(),
    convert_currency=False,
    free_parameter:str,
) -> Tuple[Any, Union[str, Any]]:
    """Query the EconDB database to find specific macro data about a company [Source: EconDB]
    Parameters
    ----------
    parameter: str
        The type of data you wish to acquire
    country : str
       the selected country
    start_date : str
        The starting date, format "YEAR-MONTH-DAY", i.e. 2010-12-31.
    end_date : str
        The end date, format "YEAR-MONTH-DAY", i.e. 2020-06-05.
    convert_currency : str
        In what currency you wish to convert all values.
    free_parameter: str
        This is the generic ticker we will use to use the API 
    Returns
    ----------
    pd.Series
        A series with the requested macro data of the chosen country
    units
        The units of the macro data, e.g. 'Bbl/day" for oil.
    """
    country = country.replace(" ", "_")
    country = country[0].upper() + country[1:]
    parameter = parameter.upper()
    
    if free_parameter="":
        if country not in COUNTRY_CODES:
            console.print(f"No data available for the country {country}.")
            return pd.Series(dtype=float), ""
        if parameter not in PARAMETERS:
            console.print(f"The parameter {parameter} is not an option for {country}.")
            return pd.Series(dtype=float), ""
        country_code = COUNTRY_CODES[country]
        country_currency = COUNTRY_CURRENCIES[country]
    else:
        parameter = free_parameter.upper()
        country_code=""
    '''
    I included an "IF" inside the original block. Now, in case "free_parameter" is equal to a null value,
    we continue with the original get_macro_data function.
    Otherwise, "parameter" receives "free_parameter" and "country_code" receives a null value.
    The rest of the function follows as the original.
    '''

    try:
        r = requests.get(
            f"https://www.econdb.com/series/context/?tickers={parameter}{country_code}"
        )
        res_json = r.json()
        if res_json:
            data = res_json[0]
            scale = data["td"]["scale"]
            units = data["td"]["units"]

            df = pd.DataFrame(data["dataarray"])
            df = (
                df.set_index(pd.to_datetime(df["date"]))[f"{parameter}{country_code}"]
                * SCALES[scale]
            )
            df = df.sort_index().dropna()

        if not res_json or df.empty:
            console.print(
                f"No data available for {parameter} ({PARAMETERS[parameter]['name']}) "
                f"of country {country.replace('_', ' ')}"
            )
            return pd.Series(dtype=float), ""

        if start_date or end_date:
            df = df.loc[start_date:end_date]

        if (
            convert_currency
            and country_currency != convert_currency
            and units in COUNTRY_CURRENCIES.values()
        ):
            if units in COUNTRY_CURRENCIES.values():
                units = convert_currency

            currency_data = yf.download(
                f"{country_currency}{convert_currency}=X",
                start=df.index[0],
                end=df.index[-1],
                progress=False,
            )["Adj Close"]

            merged_df = pd.merge_asof(
                df, currency_data, left_index=True, right_index=True
            )
            df = merged_df[f"{parameter}{country_code}"] * merged_df["Adj Close"]

            if pd.isna(df).any():
                df_old_oldest, df_old_newest = df.index[0].date(), df.index[-1].date()
                df = df.dropna()
                df_new_oldest, df_new_newest = df.index[0].date(), df.index[-1].date()
                console.print(
                    f"Due to missing exchange values, some data was dropped from {parameter} of {country}. "
                    f"Consider using the native currency if you want to prevent this. \n"
                    f"OLD: {df_old_oldest} - {df_old_newest}\n"
                    f"NEW: {df_new_oldest} - {df_new_newest}"
                )

    except HTTPError:
        return console.print(
            f"There is no data available for the combination {parameter} and {country}."
        )

    return df, units
`

**Comment by montezdesousa** [comment]
Hi @eidnanrohod1 , sorry for the delay! I read through your idea and agree with the problem statement :ok_hand: 

If I understood it correctly, my suggestion would be to solve it like `fred` command works rn. Currently `fred` chooses its prompt parameters with no need to stored them a priori. This is how I'd see it working:

* Query the database and save the search results in the controller.
![image](https://user-images.githubusercontent.com/79287829/194407194-19fcd61e-20e6-4379-b310-993b9a8b17f4.png)

* Prompt the search results when `--parameters` flag is passed.
![image](https://user-images.githubusercontent.com/79287829/194407490-0cdd265c-aefa-4cee-8911-f3af41f0dc8a.png)

* But this does not restrict the search space, only the `--parameters` prompt space. (Note that `CPIAUCSL` is not related to `GDP` query and works fine if I use it regardless of the previous query)
![image](https://user-images.githubusercontent.com/79287829/194407958-24d83062-6a52-4755-aecd-b44ffae8cb9d.png)

I think this would be good for the user as well, because it would work just like `fred`. Let me know your thoughts and if this addresses your point.
