### ISSUE TITLE
Stocks/BA/JCDR - Jim Cramer Daily Recommendation website is out of date

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2307]
<img width="694" alt="Screen Shot 2022-08-11 at 8 11 33 PM" src="https://user-images.githubusercontent.com/85772166/184278146-f30bf212-6b89-4a52-831c-b64313a62ac8.png">

**Comment by jmmartinnu2** [comment]
I think that we must also collect the date column. In this case the most recent date, if you look at the filter on the web you can filter by the most recent date. In this case on August 4. Well, I think that adding date and more recent date then we have it
![fecha-reciente](https://user-images.githubusercontent.com/93231115/184317073-86a6378d-692e-4bc9-90f6-4bf27019d570.png)

**Comment by jmmartinnu2** [comment]
that date would be the most recent (June 15). In the filter you can select from to show those of the past week... but it doesn't show anything, empty results!
![recent](https://user-images.githubusercontent.com/93231115/184321437-24f577ba-8b40-467c-a4db-a8380c13ecab.png)

**Comment by jmaslek** [comment]
Yup this is the last time that source was updated. ( https://www.thestreet.com/jim-cramer ).

Not able to quickly find an up to date replacement so this may need to be re-evaluated

**Comment by colin99d** [comment]
Im going to switch this from a bug to improve. Looks like the terminal is functioning correctly

**Comment by jmaslek** [comment]
Im gonna reopen this as a request for an up to date source
