### ISSUE TITLE
Etf Gainers show symbol[FR]

### ISSUE THREAD

**Issue by jmmartinnu2** [OpenBB-finance/OpenBBTerminal#2308]
**What's the problem of not having this feature?**
When I am working with etfs and I make a list of the top winners... it shows it to me but an important field is missing, such as the Symbol or ticker. Since if, for example, I like an ETF from that list, I want to continue working directly and I copy the symbol or ticker and I already have it... Right now to do this you have to go to the Yahoo finance website and manually copy the symbol
![gainers](https://user-images.githubusercontent.com/93231115/184372182-1bd219a0-0461-4d56-9e36-e77357e1d50c.png)

**Describe the solution you would like**
A description of what you think would be the best solution for this. From user inputs, to an output.

**Describe alternatives you've considered**
If there are other alternatives (worth considering) to your solution, list them here. 

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by jmaslek** [comment]
Hey thanks for this.  Unfortunately this is all the information available from the table:
<img width="488" alt="Screen Shot 2022-08-12 at 10 17 34 AM" src="https://user-images.githubusercontent.com/18151143/184373765-fdd52f5a-1f97-49e5-9281-17db6dcb9aeb.png">

**Comment by jmmartinnu2** [comment]
![Uploading etf.png…]()
It cannot be taken from this page. I have checked the tickers and they are the same as yahoo finance. Or take everything from here! it's good enough
