### ISSUE TITLE
[Bug] ETF/SCR/Screen - Can't use screener. Error: name 'Price' is not defined  Error: 'list' object has no attribute 'sort_values'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2310]
![Screen Shot 2022-08-12 at 10 54 43 AM](https://user-images.githubusercontent.com/85772166/184415872-2364b0b3-bdad-4ff2-848f-898230cd1aa3.png)

```
2022 Aug 12, 13:52 /etf/scr/ $ screen
Error: name 'Price' is not defined

Error: 'list' object has no attribute 'sort_values'
```

Attempting to use the ETF screener by modifying the etf_config.ini file is a guessing game. There is nothing that documents what the valid values are for the configuration file. All valid parameters should be included as comments in the ETF screener so the user knows what is possible and how to format them in the preset file.

**Comment by Chavithra** [comment]
@soggyomelette will look at this one.

**Comment by tonoSM86** [comment]
Hi I raised the question. 
What I did was try to get a list of ETFs with more than 5 Million in Assets. 
However, I noticed that the list stopped on the letter "T". So many ETFs that I know with more than 5 million in assets such as YOLO or ZROZ did not appeared. 
I ran the following code:
/etf/scr/ $ screen -l 3000 -s Assets -a --export csv

**Comment by jmaslek** [comment]
I think my etf screener database is broken.

Stock analysis changed their website so that the scraping now times out and I cannot do all in a single github action.

https://github.com/jmaslek/etf_scraper

**Comment by tonoSM86** [comment]
Hi James,

I apologise for the ignorance. But does that mean it does not have a solution?

Regards.

**Comment by jmaslek** [comment]
It means I need a cleaner solution.  Scraping all of the etfs on that site takes almost (over) 24 hours so I either need a new source of all etfs (danglewood yes I know the ishares and ssga links) or some kind of proxy thing to scrape it more than allowed.

**Comment by deeleeramone** [comment]
maybe? https://www.trackinsight.com/en/etf-providers

**Comment by DidierRLopes** [comment]
@jmaslek any update on this?

**Comment by jmaslek** [comment]
screener is dead
