### ISSUE TITLE
[IMPROVE] crypto/load using id

### ISSUE THREAD

**Issue by minhhoang1023** [OpenBB-finance/OpenBBTerminal#2313]
![image](https://user-images.githubusercontent.com/40023817/184510580-e16caf02-36f4-4120-9578-4b74dcd80296.png)

When there are multiple tokens with the same symbol, users don't have a way to distinguish them. We should provide a way to load using `id`

**Comment by ccostel** [comment]
Also I would suggest taking into account the network/chain that the coin is being looked at. 

I'm early to the project so I might be out of context. But certain stats could be chain specific (e.g. dex liquidity pools).
