### ISSUE TITLE
[Bug] Stocks/BA/Popular - Error: 'NoneType' object has no attribute 'name'  Error: 'list' object has no attribute 'empty'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2314]
This command collects data, but then fails to produce the table.

```
(🦋) /stocks/ba/ $ popular
popular
Search for latest tickers for 50 'Superstonk' posts
/Users/danglewood/GitHub/GST1/miniforge3/envs/obb/lib/python3.10/site-packages/psaw/PushshiftAPI.py:244: UserWarning: Not all PushShift shards are active. Query results may be incomplete
  warnings.warn(shards_down_message)
  278 potential tickers found.
Search for latest tickers for 50 'pennystocks' posts
  89 potential tickers found.
Search for latest tickers for 50 'RobinHoodPennyStocks' posts
  31 potential tickers found.
Search for latest tickers for 50 'Daytrading' posts
  92 potential tickers found.
Search for latest tickers for 50 'StockMarket' posts
  179 potential tickers found.
Search for latest tickers for 50 'stocks' posts
  173 potential tickers found.
Search for latest tickers for 50 'investing' posts
Error: 'NoneType' object has no attribute 'name'

Error: 'list' object has no attribute 'empty'
```

**Comment by montezdesousa** [comment]
Hi @deeleeramone, I can't reproduce the error on my end, but will try to avoid it when submission output is None. Will also silence that warning.

**Comment by barpig** [comment]
![Screenshot 2022-08-22 200342](https://user-images.githubusercontent.com/66177147/186040460-219bf0c2-e460-404c-8e4c-15851ab79200.png)

Still not working for me.

**Comment by montezdesousa** [comment]
> ![Screenshot 2022-08-22 200342](https://user-images.githubusercontent.com/66177147/186040460-219bf0c2-e460-404c-8e4c-15851ab79200.png)
> 
> Still not working for me.

Thanks, will check it again!

**Comment by montezdesousa** [comment]
> ![Screenshot 2022-08-24 110751](https://user-images.githubusercontent.com/66177147/186454544-1a7cd250-9fe6-4ae8-a7ed-efe90c95f8b1.png)
> 
> I made no changes to last time I ran it,
> 
> but it appears to somewhat work now.

Yes, I think the issue was when the subreddit returned no posts. So, maybe it only occurs sometimes. Hope the fix avoids future  crash now. Tks for taking the time to test, mine looks like this now:

![image](https://user-images.githubusercontent.com/79287829/186487683-10dfc000-ba38-4df4-871e-67d366fee9f5.png)
