### ISSUE TITLE
[Bug] Windows 10 Pro with EXE Installer v.1.7: This app can't run on your PC

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2316]
User reported error; version v1.6 is able to run. 

![image](https://user-images.githubusercontent.com/85772166/184553324-c395be9e-2791-43c9-8594-a322b06c1935.png)

![image](https://user-images.githubusercontent.com/85772166/184553319-2137d72e-aaa5-43d1-b1d6-207cd358382e.png)

**Comment by Chavithra** [comment]
Closing this issue since `v1.6` is an old version.
