### ISSUE TITLE
[Bug] Stocks/DPS/PSI --source quandl returns nothing but adding --raw flag returns the table.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2317]
<img width="583" alt="Screen Shot 2022-08-14 at 1 18 47 PM" src="https://user-images.githubusercontent.com/85772166/184553493-491838d8-72c6-4cec-81ef-f761af752961.png">

no output when `--raw = false & --source = quandl`

```
2022 Aug 14, 16:17 /stocks/dps/ $ psi --source quandl
2022 Aug 14, 16:18 /stocks/dps/ $
```
Ticker used was AMC. When `--source = stockgrid`, the chart prints

**Comment by Chavithra** [comment]
@soggyomelette working on this one

**Comment by soggyomelette** [comment]
This has been fixed in the recent api refactor
