### ISSUE TITLE
[Bug]Portfolio/PO/Maxsharpe - Error: time-weighted interpolation only works on Series or DataFrames with a DatetimeIndex  Error: returns must be a DataFrame  Error: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2319]
```
2022 Aug 14, 18:28 /portfolio/po/ $ maxsharpe
Optimization can take time. Please be patient...

5 Failed downloads:
- FB: No data found, symbol may be delisted
- CERN: No data found, symbol may be delisted
- BF.B: No data found for this date range, symbol may be delisted
- BLL: No data found, symbol may be delisted
- BRK.B: No data found, symbol may be delisted
Error: time-weighted interpolation only works on Series or DataFrames with a DatetimeIndex

Error: returns must be a DataFrame

Error: not enough values to unpack (expected 2, got 0)
```
To recreate: `/portfolio/po/load -f SP_500_Portfolio.xlsx/maxsharpe`

The provided file, SP_500_Portfolio.xlsx uses an incompatible symbol formats for B-shares. `BRK.B` is the symbol when `--source polygon`, but when `--source yf` the symbol must be `BRK-B`

Ideally, there would be an automated way to retrieve all current symbols for the S&P 500 constituents and weightings without having to update and maintain this file manually, with it also being non-source-dependent for retrieving historical/meta data. 

A potential source for updated daily constituents data: https://www.kaggle.com/datasets/andrewmvd/sp-500-stocks

**Comment by Chavithra** [comment]
Hi @soggyomelette can you take a look at this one ?
Thanks
