### ISSUE TITLE
[IMPROVE] Add in a Point-and-Figure (P&F) chart as an option for any asset class 

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#2321]
**What's the feature that should be improved?**
As requested from a user via the [Request a Feature format](https://openbb.co/request-a-feature), it could be beneficial to graphically show charts with a Point-and-Figure chart, see here: https://www.investopedia.com/terms/p/pointandfigurechart.asp

> A point-and-figure chart plots price movements for stocks, bonds, commodities, or [futures](https://www.investopedia.com/terms/f/futures.asp) without taking into consideration the passage of time.
>
> Contrary to some other types of charts, like [candlesticks](https://www.investopedia.com/trading/candlestick-charting-what-is-it/), which mark the degree of an asset's movement over set time periods, P&F charts utilize columns consisting of stacked X's or O's, each of which represents a set amount of price movement. The X's illustrate rising prices, while O's represent a falling price.
>
> Technical analysts still utilize concepts such as [support and resistance](https://www.investopedia.com/trading/support-and-resistance-basics/), as well as other patterns, when viewing P&F charts. Some argue that support and resistance levels, as well as [breakouts](https://www.investopedia.com/terms/b/breakout.asp), are more clearly defined on a P&F chart since it filters out tiny price movements and is less susceptible to [false breakouts](https://www.investopedia.com/terms/f/failedbreak.asp).

**Describe how you would like the feature improved**
Integrate this feature in all charting tools that also provide the option to show a candle chart. E.g. in Crypto and Stocks.

**Possibly describe the ideal way to improve this**
It is fine that you need to type `candle --pf` to get the Point-and-Figure instead of a separate command (or name change).

**Comment by jmaslek** [comment]
Note that this is a pretty easy add on through mplfinance (can also do renko when this is being worked on): 

```
mpf.plot(year,type='pnf')
```

**Comment by the-praxs** [comment]
So do we have this feature yet?

**Comment by jmaslek** [comment]
negative
