### ISSUE TITLE
[Bug] Portfolio Upload returns "Loading price data: Error: 'Ticker"

### ISSUE THREAD

**Issue by albioninnovate** [OpenBB-finance/OpenBBTerminal#2322]
**Describe the bug**
When up loading a portfolio file an error is returned. The portfolio file has only the required columns and was produced using Libre Calc  

**To Reproduce**

 /portfolio/ $ load -f test_me.csv

**Screenshots**

This upload in a csv file " test_me.csv":
![image](https://user-images.githubusercontent.com/5296724/184726926-bdeb440a-e515-4b08-b759-fa80976c591a.png)

Returns this error:
![image](https://user-images.githubusercontent.com/5296724/184726830-b5fc0054-6831-49fa-94b8-cdf0686eb367.png)

**Desktop (please complete the following information):**

- OS: Linux Mint 20.1 
- Python version 3.8

**Comment by pbullian** [comment]
had the same issue, had to change **Name** to **Ticker** and add all the optional columns (as described by the documentation) to make it work.

columns
Currency	Ticker	Date	Quantity	Price	Type	Side	Sector	Industry	Country	Fees	Premium	Investment

**Comment by montezdesousa** [comment]
Hi @albioninnovate, we'll try to improve this on a future iteration of the menu, but currently the way to make it work is like @pbullian pointed. 

My suggestion would be to edit one the examples provided under portfolio/holdings, like "Public_Equity_Orderbook_No_Categorization.xlsx" screenshot below.

![image](https://user-images.githubusercontent.com/79287829/186395543-a0544171-b78d-462a-b256-f279b6f03cd9.png)
