### ISSUE TITLE
[FR] Add ISM data series 

### ISSUE THREAD

**Issue by mfuentesbo** [OpenBB-finance/OpenBBTerminal#2323]
Could you please add the ISM data series from Nasdaq Data Link (formerly quandl) to the economy section of the terminal? https://data.nasdaq.com/data/ISM/MAN_PMI-pmi-composite-index

I believe it's an important economic series to analyze the economic cycle.

**Comment by jmaslek** [comment]
Happy to have someone look into this, but it looks like this source has stopped updating?  Monthly updates, last one in april.


<img width="270" alt="Screen Shot 2022-08-16 at 3 52 20 PM" src="https://user-images.githubusercontent.com/18151143/184972691-38304bcb-956e-479d-b465-3b3b3f25359b.png">
