### ISSUE TITLE
[FR]  Addition of Tiingo API support.

### ISSUE THREAD

**Issue by xel-arjona** [OpenBB-finance/OpenBBTerminal#2324]
**What's the problem of not having this feature?**
[Tiingo](https://www.tiingo.com/) is another datafeed proxy provider with a *free tier* to get limited to access for 83,480 Global securities, 37,929 US & Chinese stocks and 45,551 listed ETFs.

[For 10/month, they offer JSON fundamentals and more historical data and daily data quotas...](https://api.tiingo.com/about/pricing)

**Describe the solution you would like**
Implement a model for OpenBBTerminal in order to access their REST API.

**Describe alternatives you've considered**
A good alternative for Tiingo could be [Financial Modeling Prep](https://site.financialmodelingprep.com/), they have a free limited tier and a 10/m plan with all doors open for their service.

**Comment by jmaslek** [comment]
Integrated into platform v4
