### ISSUE TITLE
[Bug]lastcontracts and toplobbying commands not working

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2331]
**To Reproduce**
api.stocks.gov.lastcontracts(s)
api.stocks.gov.toplobbying(s)

**Screenshots**
<img width="1272" alt="Screen Shot 2022-08-16 at 3 17 26 PM" src="https://user-images.githubusercontent.com/72827203/184963628-56a4abb1-dffe-492c-af9f-a7e224494b67.png">

**Comment by deeleeramone** [comment]
I don't see an argument for ticker on this function. What is (s)?

![Screen Shot 2022-08-16 at 3 02 52 PM](https://user-images.githubusercontent.com/85772166/184993123-0e8f0dcc-269c-4fcb-a6b9-7a653dcf68ca.png)

**Comment by montezdesousa** [comment]
@deeleeramone right, this just displays the rich table for all tickers found. Should we close the issue @colin99d ?

**Comment by colin99d** [comment]
Looks good to me!
