### ISSUE TITLE
[Bug] Stocks/News --source newsapi - Error: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2332]
Ticker loaded here is BBBY

```
/stocks/ $ news --source newsapi
Error: 'str' object does not support item assignment
```

<img width="1028" alt="Screen Shot 2022-08-16 at 2 10 54 PM" src="https://user-images.githubusercontent.com/85772166/184985873-41a978c6-9f70-4a65-a70f-e6bc7e3e5fdc.png">

**Comment by sandsmichael** [comment]
I'm unable to replicate this error. command appears to be working fine. 
![image](https://user-images.githubusercontent.com/19890404/186063790-4e0955d0-0b93-4ba4-abda-3f605860761b.png)

**Comment by deeleeramone** [comment]
Are you on a PC? This issue is likely related to: #2334
