### ISSUE TITLE
[IMPROVE] Add "growth rate" flag on `economy/macro` from EconDB

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2335]
See https://twitter.com/TheBloggins/status/1559748102722134016

This should be possible from the economy menu:
![image](https://user-images.githubusercontent.com/25267873/185071533-22cc92e9-fbf9-45ae-a7e7-e1e9ca179032.png)

**Comment by JerBouma** [comment]
This should be as easy as calculating the procentual differences between the RGDP values we receive from EconDB. See the data source: https://www.econdb.com/series/RGDPUS/. This should be applicable to all data series we obtain from EconDB (and even FRED). Make this a common function that can be applied on many different data series. Do note that the above plot requires two y-axis.
