### ISSUE TITLE
[IMPROVE] Calculate intrinsic and book value of a stock and allow for comparison of the numbers

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#2336]
**What's the feature that should be improved?**
As requested from a user via the [Request a Feature format](https://openbb.co/request-a-feature), it could be helpful to be able to display the intrinsic value of a stock and compare that to the book value. See the note the requestor provided:

> You can use this feature to identify how cheap is a stock ore price is too high in compare to the intrinsic value, when you calculate this with a triple A corporate bond you can see a very relation between actual price and value of the stock. Warren Buffet use this formula for a long period of time and i use this formula in excel with a compare of the price to book value. attached a website for more informations and the correct formula with margin of safety [here](https://www.valueresearchonline.com/stories/27759/the-ben-graham-way/#:~:text=Intrinsic%20value%20%3D%20%5BEPS%20%C3%97%20(,2g)%20%C3%97%204.4%5D%2FY&text=Graham%20thought%20that%20as%20the,intrinsic%20value%20of%20a%20stock.).

**Describe how you would like the feature improved**
Be able to calculate the intrinsic value as well as the comparison between the book value.

**Possibly describe the ideal way to improve this**
This could reside within the `stocks/fa` menu as a separate command. Do note we have multiple data sources that probably can provide the correct result. Therefore, support with multiple sources is desired.

**Comment by devfinwiz** [comment]
Maybe I can help with this feature request. 
I'll do it initially for tickets residing in some specific stock exchanges. 
Maybe later somebody can help me expand its reach for several stock exchanges. The logic would obviously stay almost the same. 
Doing this would be okay?
