### ISSUE TITLE
[Bug] polygon income statement off

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#2343]
```
stocks/load aapl/fa
income --source polygon -l 3
```

1) Columns are `value` not the date 
2) limit not being followed

<img width="1181" alt="Screen Shot 2022-08-17 at 6 12 06 PM" src="https://user-images.githubusercontent.com/18151143/185252676-f9269596-fa5a-489f-b347-0db16afa4391.png">

**Comment by deeleeramone** [comment]
This problem is also happening for all sources in some way or another: #2370
