### ISSUE TITLE
[Bug] Paths set from the Settings menu creates a weird mess.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2345]
Default path is not the default:
![image](https://user-images.githubusercontent.com/85772166/185280708-79fd0be7-559b-4b74-8d4b-94d70c52649e.png)

![image](https://user-images.githubusercontent.com/85772166/185280746-781b605b-b16c-4ba1-83f2-80eaff313301.png)
![image](https://user-images.githubusercontent.com/85772166/185280754-2e75ccbb-d45c-4ea7-b70f-42bcb5bff732.png)

Setting path without quotes, "/path":
![image](https://user-images.githubusercontent.com/85772166/185280850-ff4cb69f-e6cb-4cef-a487-f686947461ab.png)

Setting path, to the actual exports folder that already exists because I have exported files there already:
![image](https://user-images.githubusercontent.com/85772166/185280945-e867b3a3-012d-41c3-876a-4ef458fdfa9b.png)

![image](https://user-images.githubusercontent.com/85772166/185280968-0efbfde4-36f4-49c9-9746-757b7b456587.png)

**Comment by nickvin** [comment]
Have you tried the following command?
export --folder ~/Desktop/OPENBB-exports

**Comment by deeleeramone** [comment]
That should be what is there by default, but instead is blank.

**Comment by DidierRLopes** [comment]
This is because of the fact that we fixed the forward slash issue "/" a couple of days ago. Should be fixed now
