### ISSUE TITLE
Bad CPU type in executable on M1

### ISSUE THREAD

**Issue by dbugg** [OpenBB-finance/OpenBBTerminal#2365]
I've downloaded and installed M1.OpenBB.Terminal.dmg on MacBook Pro M1.

When I start the terminal I get this error: 

`The boot up process might take a while. Please be patient...

/Applications/OpenBB Terminal/OpenBB Terminal: line 22: /Applications/OpenBB Terminal/.OpenBB/OpenBBTerminal: Bad CPU type in executable

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]`

**Comment by deeleeramone** [comment]
Hello! Just a quick question, does your system terminal launch using "Rosetta"?

![Screen Shot 2022-08-19 at 8 17 47 AM](https://user-images.githubusercontent.com/85772166/185651489-2e394990-819d-44fe-8eeb-b9a30292e847.png)

**Comment by dbugg** [comment]
Hello! No, I don't have Rosetta. That's why I've downloaded the M1 image. :)

**Comment by DidierRLopes** [comment]
@deeleeramone do you have more information on this?

**Comment by deeleeramone** [comment]
Install Rosetta, open using Rosetta.
