### ISSUE TITLE
[Bug] Stocks/FA - Cash/Balance/Income functions are seemingly broken

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2370]
yFinance is returning nothing.

<img width="822" alt="Screen Shot 2022-08-19 at 9 17 43 AM" src="https://user-images.githubusercontent.com/85772166/185662661-841eed63-66aa-4a6b-afcf-ec420d5fe3ad.png">

![Screen Shot 2022-08-19 at 9 18 19 AM](https://user-images.githubusercontent.com/85772166/185662808-5c63d763-ebd4-473d-a565-dd298153ec5e.png)

No data is returned from `--source av`:
```
2022 Aug 19, 12:17 /stocks/fa/ $ income --source av
No data found from Alpha Vantage
```
`--source polygon` prints yearly statements with the date showing as "value"

<img width="1320" alt="Screen Shot 2022-08-19 at 9 20 00 AM" src="https://user-images.githubusercontent.com/85772166/185663087-9dfe9fa5-a260-42b9-9aa8-3d0ad6993d34.png">

Requesting 12 quarterly statements from `--source polygon` returns only one quarter from 2009.

<img width="682" alt="Screen Shot 2022-08-19 at 9 22 09 AM" src="https://user-images.githubusercontent.com/85772166/185663487-f21832c0-e7d5-44d4-9e23-ad1116274b42.png">

**Comment by colin99d** [comment]
Hey Darren I will attack this last issue. The value header one I solved already, and the yfinance one will not be easily solvable (I could use Selenium, but that opens up a whole can of worms we dont want to deal with).

**Comment by deeleeramone** [comment]
@colin99d what would have happened? Quarterly statements from yFinance were working a few weeks ago.
