### ISSUE TITLE
[Bug] Portfolio/EF - adding start/end dates, or period flag, generates Error: shapes (1002, 13) and (14, 20032) not aligned

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2372]
When deploying the start/end dates, errors and empty charts can be returned. 

`ef`
![Screen Shot 2022-08-19 at 9 46 22 AM](https://user-images.githubusercontent.com/85772166/185667694-44e0de29-89f2-4315-b1f1-8bac84e5ade4.png)

`ef -s 2018-08-19 -e 2022-08-18`
<img width="1202" alt="Screen Shot 2022-08-19 at 9 48 29 AM" src="https://user-images.githubusercontent.com/85772166/185668083-9bafb7be-aec8-4b0c-8002-3093286424d1.png">

`ef -s 2019-08-19 -e 2022-08-18'
<img width="1210" alt="Screen Shot 2022-08-19 at 9 49 35 AM" src="https://user-images.githubusercontent.com/85772166/185668335-858a0966-adc4-4f0f-9d00-d67bc706d028.png">

```
2022 Aug 19, 12:49 /portfolio/po/ $ ef -p max
Error: shapes (6939, 3) and (14, 133) not aligned
```
<img width="1275" alt="Screen Shot 2022-08-19 at 9 50 19 AM" src="https://user-images.githubusercontent.com/85772166/185668457-410ff1db-d0e6-4c67-8a82-4357c3076cf2.png">

**Comment by DidierRLopes** [comment]
![Screenshot 2022-08-27 at 19 10 15](https://user-images.githubusercontent.com/25267873/187042796-66ed2227-697d-4c91-869c-b1cb77b06ec7.png)

I've tried several portfolios, they all worked. When reporting a bug you need to say everything about it otherwise it's hard to recreate.

**Comment by deeleeramone** [comment]
Did you try with `ef -p max`?
```
load -f Public_Equity_Orderbook.xlsx
po
ef -p max

Error: shapes (10515, 2) and (10, 129) not aligned
```
<img width="1207" alt="Screen Shot 2022-08-27 at 1 04 15 PM" src="https://user-images.githubusercontent.com/85772166/187046302-4b461b35-d194-4b85-bea4-0a1022a6e73a.png">

**Comment by soggyomelette** [comment]
I was having a look at this a couple days ago, should be fixed now!
