### ISSUE TITLE
[Bug] Short version of source flag ('-s') cannot be interpreted

### ISSUE THREAD

**Issue by boyestrous** [OpenBB-finance/OpenBBTerminal#2378]
**Describe the bug**
In stocks/options, when trying to load a ticker from the non-default source, you cannot use the `-s` flag to load finance

`--source` works [as described in the documentation](https://openbb-finance.github.io/OpenBBTerminal/terminal/stocks/options/), but `-s` does not work

You will see the error: `The following args couldn't be interpreted: ['-s', 'yf']`

**To Reproduce**
1. Open the OpenBB terminal
2. navigate to stocks/options
3. type `load -s yf -t TSLA` (any ticker will work)
4. experience failure
5. type `load --source yf -t TSLA` 
6. Winning!

**Screenshots**
This is the text from  [the documentation](https://openbb-finance.github.io/OpenBBTerminal/terminal/stocks/options/) for the options module.
![image](https://user-images.githubusercontent.com/13008046/185755158-747bdf35-48b1-41ad-9fb6-aae0d3295811.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Python version 3.8.5

**Additional context**
_Apologies for the initial empty issue description. No clue what happened..._

**Comment by boyestrous** [comment]
I think I can handle the fix for this one. 

In the function: `parse_known_args_and_warn` (parent_classes.py, line 436), the source flag doesn't include a short version for `-s`, but other flags do (`-h`, `-l`, etc.)

**Comment by DidierRLopes** [comment]
I believe that this is because `-s` is reserved to `--start` due to its usage across the platform.

**Comment by boyestrous** [comment]
That makes sense. Should we just update the documentation then? 

FWIW the help text in the app itself doesn't list `-s` as an option.
```
2022 Aug 20, 11:56 (🦋) /stocks/options/ $ load -h
usage: load [-t TICKER] [-h] [--source {tradier,yf}]

Load a ticker into option menu

optional arguments:
  -t TICKER, --ticker TICKER
                        Stock ticker (default: None)
  -h, --help            show this help message (default: False)
  --source {tradier,yf}
                        Data source to select from (default: tradier)

For more information and examples, use 'about load' to access the related guide.
```

**Comment by DidierRLopes** [comment]
Yes, we definitely should! Do you want to tackle this one? 😄

**Comment by boyestrous** [comment]
Happy to take this one

**Comment by DidierRLopes** [comment]
Thank you! 🙏
