### ISSUE TITLE
[Bug] ETF/Compare - Command is Broken. Error: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2381]
etf/compare - command is broken.

```
(🦋) /etf/ $ compare -e QQQ
compare -e QQQ
Error: list indices must be integers or slices, not str

Error: list index out of range

(🦋) /etf/ $ compare -e QQQ SPY
compare -e QQQ SPY
Error: list indices must be integers or slices, not str

Error: list index out of range

(🦋) /etf/ $ compare -e QQQ, SPY
compare -e QQQ, SPY
Error: list indices must be integers or slices, not str

Error: list index out of range

(🦋) /etf/ $ compare -e QQQ,SPY
compare -e QQQ,SPY
Error: list indices must be integers or slices, not str

Error: list index out of range
```

![Screen Shot 2022-08-21 at 3 17 59 PM](https://user-images.githubusercontent.com/85772166/185813116-77d7abfa-3061-44b8-93c8-d509311fc3b4.png)

**Comment by sandsmichael** [comment]
I have resolved this. The issue appears to be due to an errror parsing the json file requested in by get_all_names_symbols(). The fix was simple.

`    etfs = pd.DataFrame(json.loads(script.string)[1]["data"])
`

**Comment by colin99d** [comment]
We figured it out within two minutes of each other (:.
https://github.com/OpenBB-finance/OpenBBTerminal/pull/2394
