### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by tinix84** [OpenBB-finance/OpenBBTerminal#2398]
**Describe the bug**
error running routine fa_demo.openbb
The command 'fmp' doesn't exist on the /stocks/fa/ menu.
The command 'income --source polygon' doesn't exist on the /stocks/ menu.
The command 'income -q -l 8 --source polygon' doesn't exist on the /stocks/ menu.
The command 'balance --source polygon' doesn't exist on the /stocks/ menu.
The command 'balance -q -l 8 --source polygon' doesn't exist on the /stocks/ menu.
The command 'cash' doesn't exist on the /stocks/ menu.
The command 'cash -q -l 8' doesn't exist on the /stocks/ menu.
The command 'data' doesn't exist on the /stocks/ menu.
The command 'dupont' doesn't exist on the /stocks/ menu.
The command 'divs -p' doesn't exist on the /stocks/ menu.
The command 'splits' doesn't exist on the /stocks/disc/ menu.
The command 'mktcap -s 1962-01-01' doesn't exist on the /stocks/disc/ menu.
The command 'dcf' doesn't exist on the /stocks/disc/ menu.

**To Reproduce**
exe fa_demo.openbb

**Screenshots**
[20220823_fademo_bug.txt](https://github.com/OpenBB-finance/OpenBBTerminal/files/9399564/20220823_fademo_bug.txt)

**Desktop (please complete the following information):**

- OS: wsl
- Python version3.9

**Additional context**
Add any other information that you think could be useful for us.

**Comment by tinix84** [comment]
I shoud expect that the script return the same message of normal console like: 
Thank you for using Alpha Vantage! This is a premium endpoint. You may subscribe to any of the premium plans at https://www.alphavantage.co/premium/ to instantly unlock all premium endpoints
Invalid response from AlphaVantage

instead where there is problem return
usage: stocks {search,load,quote,candle,news,resources,codes,ta,ba,qa,pred,disc,dps,scr,sia,ins,gov,res,fa,bt,dd,ca,options,th,cls,home,about,h,?,help,q,quit,..,exit,r,reset,support}
stocks: error: argument cmd: invalid choice: 'dupont' (choose from 'search', 'load', 'quote', 'candle', 'news', 'resources', 'codes', 'ta', 'ba', 'qa', 'pred', 'disc', 'dps', 'scr', 'sia', 'ins', 'gov', 'res', 'fa', 'bt', 'dd', 'ca', 'options', 'th', 'cls', 'home', 'about', 'h', '?', 'help', 'q', 'quit', '..', 'exit', 'r', 'reset', 'support')

The command 'dupont' doesn't exist on the /stocks/ menu.

**Comment by JerBouma** [comment]
@deeleeramone Could you adjust this script? Because we integrated the `fmp` menu into `fa` it returns errors.

**Comment by deeleeramone** [comment]
Changes have been made in PR: #2414
