### ISSUE TITLE
[Bug] routine fa_demo not update with the new fa menu

### ISSUE THREAD

**Issue by tinix84** [OpenBB-finance/OpenBBTerminal#2399]
**Describe the bug**
the fmp menu not exist anymore and the fa_demo is not working

**To Reproduce**
exe fa_demo.openbb

**Screenshots**

**Desktop (please complete the following information):**

- OS: wsl
- Python version 3.9

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
This is addressed in #2414
