### ISSUE TITLE
[FR] Add Coinglass Crypto Liquidation data to crypto for loaded coin.

### ISSUE THREAD

**Issue by jfarid27** [OpenBB-finance/OpenBBTerminal#2400]
![bybt_chart](https://user-images.githubusercontent.com/1673206/186166039-9ea71023-226b-4cb9-862d-224cafd0a003.jpeg)

**What's the problem of not having this feature?**
I'm interested in adding liquidation data to the stack fo available information on the terminal. Data is currently available on Coinglass, so it doesn't require much updating.

**Describe the solution you would like**
I would like to see an appropriate liquidation chart to compare previous days to current days. Add liquidations data to crypto dd.

**Describe alternatives you've considered**
I haven't seen other liquidation data aggregators at the moment. If anyone has alternatives, please list here.

**Additional information**
[Liquidation Data view on Coinglass](https://www.coinglass.com/LiquidationData)

**Comment by jose-donato** [comment]
Closed #2402
