### ISSUE TITLE
[Bug] Forex Quote API blocked via premium account

### ISSUE THREAD

**Issue by jfarid27** [OpenBB-finance/OpenBBTerminal#2403]
**Describe the bug**
AlphaVantage seems to have converted the API used for quotes into a premium feature. Since this is a pretty simple ask, it may be better to use a different API that's free so users can access quote information.

**To Reproduce**
`forex/load GBPUSD/quote`

**Screenshots**
<img width="988" alt="Screen Shot 2022-08-23 at 1 14 07 PM" src="https://user-images.githubusercontent.com/1673206/186222792-c22062f4-1c32-4f81-b78d-074dc7e84fb0.png">

**Desktop (please complete the following information):**

- OS: Mac Big Sur 11.6
- Python version 3.8.13

**Additional context**

It might be possible to convert quote to a Yahoo Finance ticker using their currency quote tickers in their API. Remapping each forex pair to their format of `GBPUSD=X` could be an option. [See here for a reference page.](https://finance.yahoo.com/quote/GBPUSD=X?p=GBPUSD=X&.tsrc=fin-srch)

**Comment by deeleeramone** [comment]
I feel like data source for `quote` needs to be determined by the `load --source` function..

**Comment by jmaslek** [comment]
Dang they did a bamboozle.

Ill look into another source for quotes and am open to api ideas (yahoo could be used)

**Comment by DidierRLopes** [comment]
> Dang they did a bamboozle.
> 
> Ill look into another source for quotes and am open to api ideas (yahoo could be used)

Done 😋
