### ISSUE TITLE
[Bug] FRED function is broken - Cannot get series output. Error: 5755341024

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2406]
Cannot get output for any series ID.

![image](https://user-images.githubusercontent.com/85772166/186275701-dcc92bb9-9685-4838-b11a-044be9d8c78d.png)

**Comment by sandsmichael** [comment]
Looking into this...The series is being retrieved successfully but the plot is not rendering in `display_fred_series()`

**Comment by deeleeramone** [comment]
I think you may be on to something here.

```
(🦋) /economy/ $ fred MORTGAGE5US
Error: 'MORTGAGE5US'
```

<img width="806" alt="Screen Shot 2022-08-23 at 7 18 31 PM" src="https://user-images.githubusercontent.com/85772166/186303092-ec752564-1b26-43e7-a6f4-0e7149cf768b.png">

**Comment by deeleeramone** [comment]
Plotting the stored datasets does produce the error as well.

<img width="512" alt="Screen Shot 2022-08-23 at 7 21 01 PM" src="https://user-images.githubusercontent.com/85772166/186303331-def69284-8a36-4f2e-a151-2a242dee6c2a.png">

**Comment by deeleeramone** [comment]
Entering the `/qa` menu with these datasets allows both to be picked and plotted with the `line` function. 

![Screen Shot 2022-08-23 at 7 22 35 PM](https://user-images.githubusercontent.com/85772166/186303526-314e23a1-5daf-4c42-a7e9-fbcb4fe3d6c9.png)

**Comment by sandsmichael** [comment]
I think the issue is with the detail dict on line 128. Taking a look.

![image](https://user-images.githubusercontent.com/19890404/186304754-a0f27a68-d1b0-4cf9-a7eb-7af02b82df6a.png)

**Comment by jmaslek** [comment]
Was an issue in defining a dictionaty
