### ISSUE TITLE
Create a menu for macro and fred 

### ISSUE THREAD

**Issue by Lorenzo025** [OpenBB-finance/OpenBBTerminal#2410]
**What's the problem of not having this feature?**
With Macro, the indicators appear on a drop down in abbreviation. It would be more convenient to see all the indicators full names and what they represent. With FRED, I currently cannot see any functions to pull from fred data. 

**Describe the solution you would like**
A full menu like you see in TA or DD, with each callable dataset and a short description.

**Comment by DidierRLopes** [comment]
Fred has an insane amount of data. You have something better currently, you have a `query` parameter.

E.g if you are interested in a dataset about unemployment you can look for the dataseries ID utilizing: `fred -q unemployment`.

<img width="1100" alt="Screenshot 2022-08-25 at 00 31 37" src="https://user-images.githubusercontent.com/25267873/186541307-6cf84bde-059e-44e4-b3ba-1d0098016644.png">
