### ISSUE TITLE
[Bug] /Stocks/FA/income -p basic_eps: Scale Values [and title] are incorrect. EPS is not $5.67 million per share, there is no scale multiplier.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2417]
![Screen Shot 2022-08-25 at 9 31 00 AM](https://user-images.githubusercontent.com/85772166/186720191-dbb820f9-5de0-46be-bb00-2d2668be4797.png)

Title should read: Annual Basic EPS for AAPL

A few other items:

- Scientific notation is not necessary and it also makes charts harder to read.
- Titles for charts should always have proper capitalization.
- Charts for individual line items may be better presented as a bar chart instead of a line.

**Comment by jmaslek** [comment]
you dont like 10^-6 Millions ?  :D

**Comment by deeleeramone** [comment]
I think we'd have to adjust the total market cap of the company to a bazillion. because it would be very undervalued. :P

**Comment by DidierRLopes** [comment]
PR incoming @deeleeramone 

![Screenshot 2022-08-27 at 16 32 35](https://user-images.githubusercontent.com/25267873/187036992-cb58317e-28d5-4199-8c6e-7301e5457a78.png)
