### ISSUE TITLE
/economy/valuation does not work on Mac M1

### ISSUE THREAD

**Issue by ethene** [OpenBB-finance/OpenBBTerminal#2422]
When selecting /economy/valuation an error pops up with no result:

Error: 'ascii' codec can't encode character '\u2026' in position 1128: ordinal not in range(128)
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

**To Reproduce**
go to /economy/valuation

- OS: macOS Monterey
Default MacOS installer

**Comment by deeleeramone** [comment]
I am not able to recreate this issue with the M1 macOS installer package.

![Screen Shot 2022-08-25 at 9 55 55 PM](https://user-images.githubusercontent.com/85772166/186825116-7d75b764-7744-4ee8-9bf8-ee8d6b2719f0.png)

Check your default profile for the Mac OS Terminal, and under the Advanced tab, select UTC-8

![Screen Shot 2022-08-25 at 9 57 03 PM](https://user-images.githubusercontent.com/85772166/186825253-c4737844-be02-4617-a9fc-ec8c5104b817.png)

**Comment by ethene** [comment]
Problem seems to disappear after checking 'Set locale environment variables on startup'

**Comment by DidierRLopes** [comment]
Thanks for reporting. Will close this since you have solved it on your own!
