### ISSUE TITLE
[Bug] Options/load [exp] --source nasdaq: exp 0 is a date in the past & other errors.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2423]
`2022 Aug 25, 21:42 Danglewood /stocks/options/ $ load AAPL --source nasdaq`

```
Error: "['c_colour', 'p_colour', 'drillDownURL', 'expirygroup'] not found in axis"

Error: 'list' object has no attribute 'columns'
```
![Screen Shot 2022-08-25 at 9 44 06 PM](https://user-images.githubusercontent.com/85772166/186824031-c83bb98f-382e-4e14-8784-03290afc2203.png)

This one is weird:
```
2022 Aug 25, 21:43 Danglewood /stocks/options/ $ load spy --source nasdaq
Error: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```
Had to exit the menu and re-enter it to clear the memory:

![Screen Shot 2022-08-25 at 9 49 48 PM](https://user-images.githubusercontent.com/85772166/186824393-843e1853-c77c-43fb-af79-9d54fcfb7a5f.png)

![Screen Shot 2022-08-25 at 9 51 27 PM](https://user-images.githubusercontent.com/85772166/186824653-51a5dcf7-97e9-4af8-a7ba-d0d938ff30bc.png)

**Comment by jmaslek** [comment]
sooooo it seems that the way this is implemented, you have to specify that the source for `exp` must be nasdaq if you load in nasdaq (even though the expitrations should be the same (which actually looks like nasdaq returns expirations from the previous week).

Reasoning is how different the yahoo vs nasdaq handles option chains .  

@colin99d and I have talked that this menu needs a big refactoring, which will come, but the current (not-ideal) implementation is to either specify your default source in the sources menu, or just specify --source nasdaq each time.

**Comment by DidierRLopes** [comment]
I don't get the same issue as you @deeleeramone. See below

![Screenshot 2022-08-27 at 16 20 50](https://user-images.githubusercontent.com/25267873/187036545-9d22900f-2a4c-40ba-b84b-e00176d68e58.png)

**Comment by deeleeramone** [comment]
yes you do, the first three expiration dates are in the past!
