### ISSUE TITLE
[Bug] Crypto/load - No interval named `1day` required to use QA functions.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2431]
To recreate, load a coin from the crypto menu and attempt to enter the QA menu.
<img width="1338" alt="Screen Shot 2022-08-26 at 9 28 13 PM" src="https://user-images.githubusercontent.com/85772166/187014376-ac598629-dbba-49ca-81a5-7b16a5d337d7.png">

**Comment by jfarid27** [comment]
I can also confirm this is happening for the `/pred` menu too.

![Peek 2022-08-28 07-41](https://user-images.githubusercontent.com/1673206/187073598-bf816d4e-17f6-4224-b7f1-7e6aeceb63f2.gif)
.

**Comment by DidierRLopes** [comment]
@jfarid27 the fix I added should actually work for both :) I will reflect the title to show that! Thanks!
