### ISSUE TITLE
[FR] Add Stocks heatmap to stocks/disc

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2443]
<img width="538" alt="Screenshot 2022-08-28 at 01 27 52" src="https://user-images.githubusercontent.com/25267873/187052639-2ae2726e-027e-4c99-8692-df9605e28fa8.png">

**Comment by jmaslek** [comment]
Im on this one.  Already sketched up an SP500 one :P

<img width="1457" alt="Screen Shot 2022-08-28 at 9 30 27 PM" src="https://user-images.githubusercontent.com/18151143/187105477-8d570cac-46dd-4c1f-82e2-c778631f150f.png">

**Comment by jmaslek** [comment]
<img width="1792" alt="Screen Shot 2022-08-28 at 9 49 55 PM" src="https://user-images.githubusercontent.com/18151143/187107374-298be9bc-bc3a-40d0-8bb2-3ad982f760de.png">
