### ISSUE TITLE
[Bug] Portfolio fails when trade happened "today"

### ISSUE THREAD

**Issue by jfarid27** [OpenBB-finance/OpenBBTerminal#2450]
**Describe the bug**
The portfolio engine fails if a trade has occurred on the current day. This is a very odd time dependent bug that requires historical data fetching not to return the daily date.

**To Reproduce**
1. I'm not sure how to get Yahoo not to fetch the current day date, besides try this around 8am EST.
2. Pick today in the format %Y-%m-%d and add it to your csv portfolio, or portfolio_trades.csv.
3. Navigate to `portfolio` and `load` the file. It should fail with an index out of bounds error.

**Screenshots**
TBD

**Desktop (please complete the following information):**

- OS: Big Sur
- Python version 3.8.13

**Additional context**
None

**Comment by deeleeramone** [comment]
If trade = today, then there would be no daily data available until after market close.
