### ISSUE TITLE
[Bug] openbbterminal-poetry-full:1.7.0 images not available in ghcr.io

### ISSUE THREAD

**Issue by metlos** [OpenBB-finance/OpenBBTerminal#2452]
**Describe the bug**
The last version of the terminal available as a docker image is 1.6.0.

**To Reproduce**
Visit https://github.com/openbb-finance/OpenBBTerminal/pkgs/container/openbbterminal-poetry-full and see that the latest version is 1.6.0.

**Comment by teracapital** [comment]
and there are some breaking changes that need to be updated

**Comment by teracapital** [comment]
for example api.etf.models.stockanalysis.get_all_names_symbols() stoped working at 1.6.0

**Comment by DidierRLopes** [comment]
Hey @metlos and @teracapital ,

We are working hard on our OpenBB Terminal 2.0 (coming very soon).

Our goal is to have our API widely available through `pip install openbb` and an updated docker version.

Thanks for flagging this

**Comment by teracapital** [comment]
Thanks @DidierRLopes. Looking forward to 2.0!!! 

if anyone got this error from api.etf.models.stockanalysis.get_all_names_symbols(), you can still use api.economy.models.investingcom.investpy.etfs.etfs_as_df()['symbols'] diferent sources, but almost the same result!

**Comment by DidierRLopes** [comment]
@montezdesousa can you make sure we have this particular API call working? Thanks!

**Comment by montezdesousa** [comment]
> Thanks @DidierRLopes. Looking forward to 2.0!!!
> 
> if anyone got this error from api.etf.models.stockanalysis.get_all_names_symbols(), you can still use api.economy.models.investingcom.investpy.etfs.etfs_as_df()['symbols'] diferent sources, but almost the same result!

This second source seems to have more data available actually. Anyways I'll fix the first here https://github.com/OpenBB-finance/OpenBBTerminal/pull/2467 and make it available on the new api as well. Thanks!!
