### ISSUE TITLE
[IMPROVE] Forex/Candle - Add export, raw, sort, descending, trend, limit arguments.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2455]
The Candle function in the Forex menu, and others, is missing the same functionality that the Stocks menu is equipped to handle. There should be no differences between the various `candle` commands throughout the terminal. 

<img width="1374" alt="Screen Shot 2022-08-29 at 11 21 52 AM" src="https://user-images.githubusercontent.com/85772166/187271410-0422c212-ea20-414d-a0fc-1236aeda04ee.png">

<img width="1006" alt="Screen Shot 2022-08-29 at 11 26 41 AM" src="https://user-images.githubusercontent.com/85772166/187272038-0e00ce4d-a9da-4d6e-bb17-6afac32b7fc5.png">

**Comment by jmaslek** [comment]
the duplicate one was closed so this must be good ¯\_(ツ)_/¯
