### ISSUE TITLE
[Bug] Forex/TA/EMA - function is dead when source = Polygon. Error: 'date'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2456]
To recreate:

`/forex/load EURUSD --source polygon/ta/ema`

<img width="1375" alt="Screen Shot 2022-08-29 at 11 31 46 AM" src="https://user-images.githubusercontent.com/85772166/187272909-2362db6e-5d34-4db7-9d8b-6f8c59f792ba.png">

Not a problem when the source = yFinance. 

<img width="1390" alt="Screen Shot 2022-08-29 at 11 33 15 AM" src="https://user-images.githubusercontent.com/85772166/187273177-ecde2290-6c97-49f4-b640-500b396fbb60.png">

Also works when source = av. However, the name that is displayed for the source is incorrect and should be, AlphaVantage. 
```
Source: AlphaAdvantage 
```
<img width="1412" alt="Screen Shot 2022-08-29 at 11 35 02 AM" src="https://user-images.githubusercontent.com/85772166/187273439-43f35224-8538-4cd5-bda9-07963b716327.png">

**Comment by jmaslek** [comment]
Can you confirm this still is happening?

<img width="1395" alt="Screen Shot 2022-09-06 at 8 43 07 PM" src="https://user-images.githubusercontent.com/18151143/188764248-b84b670d-6b6a-4e3f-8c6b-a30fff5bd12b.png">

**Comment by jmaslek** [comment]
@deeleeramone bump

**Comment by colin99d** [comment]
I am going to close for now. This works for me as well.
