### ISSUE TITLE
[Bug] Forex/TA - ADX, AROON, RSI, Fisher, CG & CCI are broken.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2457]
This error is the same for any source used to load the currency pair.

```
Error: display_cci() got an unexpected keyword argument 'length'
```
<img width="1379" alt="Screen Shot 2022-08-29 at 11 40 28 AM" src="https://user-images.githubusercontent.com/85772166/187274286-1f7d0294-4ea4-45d9-a5e9-5020ef7353bc.png">

<img width="677" alt="Screen Shot 2022-08-29 at 11 43 28 AM" src="https://user-images.githubusercontent.com/85772166/187274730-87b4979f-efef-4aed-8e79-9b55e325ecd0.png">

**Comment by jmaslek** [comment]
Can you confirm if any of these issues are there after those PR's?

**Comment by deeleeramone** [comment]
I cannot confirm because this is what I get after the latest pull from main: `/crypto/load`

![Screen Shot 2022-09-04 at 11 34 14 AM](https://user-images.githubusercontent.com/85772166/188328428-6ad7a85c-2525-4bb9-85b1-cc5ae2f90627.png)

**Comment by hjoaquim** [comment]
@deeleeramone i believe this is fixed now:
![image](https://user-images.githubusercontent.com/48914296/188753454-40b9221c-02c1-46df-b5af-bdb3b768c474.png)
