### ISSUE TITLE
[Bug] Funds/info - Inception Date field does not return a date for some funds, instead displays an unknown integer.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2469]
`load GTAPX`
`info`
<img width="703" alt="Screen Shot 2022-08-30 at 11 45 18 PM" src="https://user-images.githubusercontent.com/85772166/187611452-0e57e3ac-c699-4a83-a24d-0e9d2afec315.png">

`load VIIIX`
`info`
<img width="759" alt="Screen Shot 2022-08-30 at 11 47 10 PM" src="https://user-images.githubusercontent.com/85772166/187611771-056b410e-60a6-4590-a97f-c8522c74316f.png">

`load ARCIX`
`info`
<img width="1159" alt="Screen Shot 2022-08-30 at 11 49 27 PM" src="https://user-images.githubusercontent.com/85772166/187612171-ab96f1f5-b9db-4206-b7be-5c28dc7a8849.png">

**Comment by sandsmichael** [comment]
This is an issue around line 880-900 in get_fund_information() method of funds.py. Is forking required to commit a simple fix that can be merged into main? It says I do not have permission to commit directly to the main branch in order to resolve...Please advise.

**Comment by deeleeramone** [comment]
All commits to main must be done via a pull request from another branch. If you modify the file directly on main, through the GitHub website, you will be presented the option to create a pull request from a new branch of your newly created fork. Tag this issue in your pull request and a maintainer will verify, test, and merge which should close the issue.

**Comment by jmaslek** [comment]
> This is an issue around line 880-900 in get_fund_information() method of funds.py. Is forking required to commit a simple fix that can be merged into main? It says I do not have permission to commit directly to the main branch in order to resolve...Please advise.

So that is in the `investpy` source code.  Best method will be to either raise an issue or submit a PR to https://github.com/alvarobartt/investpy

**Comment by sandsmichael** [comment]
> > This is an issue around line 880-900 in get_fund_information() method of funds.py. Is forking required to commit a simple fix that can be merged into main? It says I do not have permission to commit directly to the main branch in order to resolve...Please advise.
> 
> So that is in the `investpy` source code. Best method will be to either raise an issue or submit a PR to https://github.com/alvarobartt/investpy

Interesting. That project doesn't appear to have too much recent activity. I created a PR to redact and replace decimal value Inception Dates with an NA when they appear.
