### ISSUE TITLE
[Bug] Crypto/Disc/CMCTOP - Error: display_cmc_top_coins() got an unexpected keyword argument 'descend'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2470]
<img width="1136" alt="Screen Shot 2022-08-30 at 11 55 11 PM" src="https://user-images.githubusercontent.com/85772166/187613202-036d08cd-becb-4750-91db-591816ac8256.png">

**Comment by jmaslek** [comment]
This was merged.  Yay
