### ISSUE TITLE
[Bug] Crypto/NFT - NFT Calendar functions are dead

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2471]
<img width="1143" alt="Screen Shot 2022-08-30 at 11 59 38 PM" src="https://user-images.githubusercontent.com/85772166/187613915-cef28e2a-2489-44a1-bbd0-03a86965f8b4.png">

**Comment by jwjohns** [comment]
If you dump the request return when trying the nftcalendar items if shows they are using cloudflare as bot protection. 

I have tried using cfscraper and cloudscraper to no avail. it gets caught up every time. Selenium or something like flaresolverr might work. flaresolverr is nodejs though and runs as a proxy so not sure if it's a fit.

**Comment by deeleeramone** [comment]
@jose-donato, @minhhoang1023, any thoughts here?

**Comment by jose-donato** [comment]
#2475 fixes commands from nftpricefloor, will take a look into the others

**Comment by jose-donato** [comment]
about the nftcalendar ones, they dont allow scraping anymore, should we remove the commands? @DidierRLopes

**Comment by jmaslek** [comment]
Looks like #2540 should close this
