### ISSUE TITLE
[Bug]Stock Load producers incorrect changes over time

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2474]
**Describe the bug**
Terminal gives incorrect changes over time when time is not daily.

**Screenshots**
![image](https://user-images.githubusercontent.com/72827203/187684496-bae54e95-70d1-49af-be05-a2d9fbe9a3e7.png)

**Additional context**
We just need to hide this when not daily.

**Comment by deeleeramone** [comment]
@colin99d - it is even showing old data. Last price does not = last price. 
<img width="745" alt="Screen Shot 2022-08-31 at 2 45 44 PM" src="https://user-images.githubusercontent.com/85772166/187791111-c0c8d952-6ff0-4d45-9e0e-aeef8f59a330.png">

**Comment by northern-64bit** [comment]
> @colin99d - it is even showing old data. Last price does not = last price.

Took a look at this and it uses the previous days adjusted close. Thus all of the data on daily frequency is at least one day delayed. The problem with other time frequencies is that it just uses a fixed amount of data, for weekly return the 5 latest data points (with no adjustments).
