### ISSUE TITLE
[Bug] Crypto/NFT - can't enter menu. "Error: 'slug'"

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2484]
recreate with: `/crypto/nft`

<img width="1166" alt="Screen Shot 2022-09-02 at 10 15 25 AM" src="https://user-images.githubusercontent.com/85772166/188205193-21d77659-9ed2-48ca-a57d-c0e38fcb4434.png">

related to #2471

**Comment by jwjohns1220** [comment]
looks like line 45 in `nft_controller.py` 
`     
nft_price_floor_collections = nftpricefloor_model.get_collection_slugs()
`
is causing the issue. I commented it out and set the var equal to something arbitrary and I can get into the nft menu again. 
```
        #nft_price_floor_collections = nftpricefloor_model.get_collection_slugs()
        nft_price_floor_collections = ['finiliar']
```

still digging further into nftpricefloor_model.get_collection_slugs() as it seems like the way it's called fires it off requiring the slug.

**Comment by jwjohns** [comment]
looks like line 45 in `nft_controller.py`
`nft_price_floor_collections = nftpricefloor_model.get_collection_slugs()`
is causing the issue. I commented it out and set the var equal to something arbitrary and I can get into the nft menu again.
```
        #nft_price_floor_collections = nftpricefloor_model.get_collection_slugs()
        nft_price_floor_collections = ['finiliar']
```
still digging further into `nftpricefloor_model.get_collection_slugs()` as it seems like the way it's called fires it off requiring the slug which throws the error. 

Ill keep at it and see if I can't resolve it.

**Comment by minhhoang1023** [comment]
@jwjohns Dope! Once you figure it out, feel free to create a PR for this. Let us know if you need any help :D

**Comment by colin99d** [comment]
@deeleeramone I am not able to recreate this issue, are you still experiencing it?

**Comment by deeleeramone** [comment]
Seems like this was addressed somewhere else and wasn't linked to the closed issue. Screenshot is from v1.8 of the installation package. 


![Screen Shot 2022-09-20 at 9 13 27 AM](https://user-images.githubusercontent.com/85772166/191310424-fd53a17f-ce90-489f-b778-39936d068e5e.png)
