### ISSUE TITLE
[Bug] Stocks/FA - Cash, Income, Balance - Limit flag doesn't work.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2511]
The limit flags do not work for these functions. 

<img width="935" alt="Screen Shot 2022-09-07 at 8 04 14 AM" src="https://user-images.githubusercontent.com/85772166/188912424-d6dc9202-32c1-4770-b351-dcc3b2239107.png">

When `--source Polygon` only one frame of data is returned. The numbers are also returned as $M/B instead of whole numbers like the others. Whole numbers are better for data processes than abbreviations, this should be converted to full values.

<img width="527" alt="Screen Shot 2022-09-07 at 8 05 58 AM" src="https://user-images.githubusercontent.com/85772166/188912817-7d100a85-add4-448b-8905-41c9e4076d2c.png">

<img width="854" alt="Screen Shot 2022-09-07 at 8 08 33 AM" src="https://user-images.githubusercontent.com/85772166/188913462-19aafbe1-08c9-42b4-b8e8-9412a9a8d8b6.png">

**Comment by jmaslek** [comment]
Ahahha we werent passing limit into the yahoo finance function rip
