### ISSUE TITLE
[Bug] portfolio/var - var command does not work

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#2519]
`var` command under `portfolio`menu is not working with any of available files.

`load Public_Equity_Orderbook.xlsx`
`var`
-> Error: "None of [Index(['adjclose'], dtype='object', name='Date')] are in the "

![image](https://user-images.githubusercontent.com/79287829/189085200-7ee0ecbe-7318-4001-8766-982b35c34fbb.png)

- OS: Windows 11
- Python 3.8.13

**Comment by yalcindavid** [comment]
Maybe the columns name of public_equity_orderbook.xlsx got space ?

**Comment by montezdesousa** [comment]
> Maybe the columns name of public_equity_orderbook.xlsx got space ?

It was due to changes in args on qa_view.var
