### ISSUE TITLE
[IMPROVE] behavioural analysis menu commands aren't separate from ticker dependent to not

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2534]
<img width="1066" alt="Screenshot 2022-09-13 at 11 56 49" src="https://user-images.githubusercontent.com/25267873/189883905-48981379-e2dd-4c83-a985-c62f6cbf38fa.png">

**Comment by jmaslek** [comment]
maybe its just late but that title is not coherent english
