### ISSUE TITLE
[Bug] stocks/gov/contracts empty for AMT still shows plot

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2537]
<img width="1442" alt="Screenshot 2022-09-13 at 12 35 34" src="https://user-images.githubusercontent.com/25267873/189891057-cecc3355-7a84-4eb1-9c24-948d6dc1c667.png">

**Comment by jmaslek** [comment]
hmmm.  technically its not empty...

<img width="1735" alt="Screen Shot 2022-09-16 at 10 10 01 PM" src="https://user-images.githubusercontent.com/18151143/190836452-960e8666-a4e3-4545-9b6a-d0f90f699d96.png">

**Comment by jmaslek** [comment]
Ill add a check to if the sum of abs contracts is zero.

**Comment by jmaslek** [comment]
It will now print:
```
2022 Sep 16, 22:17 (🦋) /stocks/gov/ $ contracts
Contracts found, but they are all equal to $0.00.
```
