### ISSUE TITLE
[Bug] Crypto/Load - CCXT not responding, doesn't load.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2546]
recreate by attempting to load Ethereum or Bitcoin using CCXT as the source.

<img width="1196" alt="Screen Shot 2022-09-14 at 9 18 14 PM" src="https://user-images.githubusercontent.com/85772166/190313315-4dd6330d-68f6-423c-bca4-031b60913007.png">

**Comment by jmaslek** [comment]
Ill add to this @jose-donato.  The sources should probably be case insensitive on matching.

If I load with CCXT (note the capitalization) -- it then says YahooFinance


<img width="505" alt="Screen Shot 2022-09-16 at 10 21 14 PM" src="https://user-images.githubusercontent.com/18151143/190836772-78973f7d-7952-4983-be1f-fac9eb8e2878.png">

**Comment by deeleeramone** [comment]
The same issue is present when entering the DD menu. The source loaded is different than what was displayed on the main menu. @minhhoang1023 - seems like the same underlying issue as we briefly discussed yesterday. 

![Screen Shot 2022-09-22 at 7 32 08 AM](https://user-images.githubusercontent.com/85772166/191775294-993562b8-ae34-4b6d-83e9-39d155743266.png)
