### ISSUE TITLE
[Bug] Stocks/gov/topbuys - when "--govtype" == "house", returns error.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2548]
This is likely because this category is redundant. For all intents and purposes, there are only two buckets for the US Federal office: congress and senate.

<img width="716" alt="Screen Shot 2022-09-14 at 9 45 06 PM" src="https://user-images.githubusercontent.com/85772166/190316656-d8aa8d3c-abee-46f3-bb6e-fb10e13c10b1.png">

**Comment by jmaslek** [comment]
This now has an Options column when we specifiy the -g flag.  The dropna in the code was getting rid of the entire table whoops

<img width="981" alt="Screen Shot 2022-09-16 at 9 59 13 PM" src="https://user-images.githubusercontent.com/18151143/190836144-07dfd54d-9bf4-4bfd-9df9-13affba040d9.png">
