### ISSUE TITLE
[FR] Arthur Hayes USD Liquidity Index - Public Data and Simple Subtraction of Columns

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2549]
From Reddit (https://www.reddit.com/r/openBB/comments/x8euyf/new_request_arthur_hayes_usd_liquidity_index/):

He spun up this index for his Bloomberg terminal so I figured why not request it for my favorite superiorly customizable stocks platform!USD Liquidity Conditions Index = [The Fed’s Balance Sheet] — [NY Fed Total Amount of Accepted Reverse Repo Bids] — [US Treasury General Account Balance Held at NY Fed]

![image](https://user-images.githubusercontent.com/85772166/190319646-3fc7ca97-d764-457a-88c5-dac824683d4f.png)

This index is measured on a weekly resolution because the Federal Reserve Balance Sheet is published on Wednesdays.

The Wednesday Level of the Fed's Balance Sheet is: WALCL

The amount of accepted reverse repo bids is here: https://www.newyorkfed.org/markets/desk-operations/reverse-repo

The Wednesday Level of the US Treasury General Account Balance is: WDTGAL

**Comment by jmaslek** [comment]
for my future reference, the second one is the fred series: RRPONTSYD

**Comment by jmaslek** [comment]
Okay so with #2559 merged, this is kind of possible.

If we do 
```
fred RRPONTSYD WALCL CBBTCUSD WTREGEN -s 2020-01-01
```

```
eval liquid = WALCL*1000000000**-1-WTREGEN-RRPONTSYD
```

This is my attempt at it.  Not sure why the division is needed tp replicate this, but if you know your formula, you can do it now!

**Comment by deeleeramone** [comment]
If I follow your snippets here (erasing CBBTCUSD, because what is that doing there?), this is my output:
![Screen Shot 2022-10-23 at 8 43 36 PM](https://user-images.githubusercontent.com/85772166/197444523-e3464152-31af-46c8-bb0a-5a300b4369ed.png)

![Screen Shot 2022-10-23 at 8 44 04 PM](https://user-images.githubusercontent.com/85772166/197444608-dd643c47-01b6-473e-a7df-a17c5d1940a7.png)


![Screen Shot 2022-10-23 at 8 41 17 PM](https://user-images.githubusercontent.com/85772166/197444375-26fa12bd-e0e7-4a78-8026-b632c3737de7.png)

**Comment by jmaslek** [comment]
![Screen Shot 2022-10-27 at 10 28 56 AM](https://user-images.githubusercontent.com/18151143/198314598-0caefceb-5284-44b6-8b41-8bab5cb0ffef.png)
