### ISSUE TITLE
[Bug] Every graph throws Wayland/Qt errors constantly when open

### ISSUE THREAD

**Issue by ebdavison** [OpenBB-finance/OpenBBTerminal#2553]
**Describe the bug**
Every graph throws Wayland/Qt errors constantly when open which is:
> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

**To Reproduce**
1. Start using openbb in terminal
2. `crypto` command
3. `load btc` command
4. `candle` command
5. when graph opens, the errors constantly scroll by

**Screenshots**
![image](https://user-images.githubusercontent.com/549431/190465064-bc80f02b-b88c-489c-87a7-b69cbe9fb721.png)

**Desktop (please complete the following information):**

- OS: Fedora Linux 36 (Workstation Edition)
- Python version: 3.10.6

**Additional context**
Add any other information that you think could be useful for us.

Wayland is the default window manager for Fedora Linux 36 and this looks like a compatiblity issue for wayland and Qt.  However, since it is being thrown in OpenBB, seems like a quick check on the DM to not make this call would fix this without too much friction.

**Comment by ebdavison** [comment]
A comment here indicates this is expected so maybe it could just be avoided in the code.

https://forum.qt.io/topic/90639/comparing-qt-widgets-app-under-gnome-wayland-using-platform-wayland-egl-to-xcb/8

**Comment by piiq** [comment]
@ebdavison can you use tkinter in fedora instead of qt as a matplotlib backend?
in the terminal set `settings/backend` to `tkAgg` manually

**Comment by ebdavison** [comment]
I did try tkAgg and the result was the same.

However, I re-created by virtual environment with copies rather than symlinks and used 3.9.14 instead of 3.10.6 and now there are not more error messages.

So, issue seems to be solved by using Python 3.9.x rather than 3.10.x.

**Comment by ebdavison** [comment]
Seems like this should be in the documentation or in an FAQ and I checked and do not see it.  The installation docs don't talk about Linux at all either and this is most definitely possible despite the missing installer.

Happy to troubleshoot this more if needed.  If not, this issue can be closed.

**Comment by colin99d** [comment]
I updated the docs to make it even more clear. Thanks for pointing this out!
