### ISSUE TITLE
windows 10 Docker Desktop on Windows no graphical output

### ISSUE THREAD

**Issue by wwn** [OpenBB-finance/OpenBBTerminal#2565]
Current state: Running openBB Terminal in Docker on Windows, load a ticker, enter candle command. No chart window appears. No error message appears. Had no graphical output on other places as well.
Expected: see a candle chart

**Comment by wwn** [comment]
My fault. Not expected to have charts etc. if it's running on Docker.

**Comment by DidierRLopes** [comment]
@wwn you should be able to do so.

Have you seen these instructions https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/DOCKER_ADVANCED.md ?

**Comment by wwn** [comment]
Thx for the hint but Windows is not mentioned there.
In between I switched to the real desktop app. So fine for me. Thx for patience.
