### ISSUE TITLE
[IMPROVE time of last update] options/UNU 

### ISSUE THREAD

**Issue by Lorenzo025** [OpenBB-finance/OpenBBTerminal#2572]
**What's the feature that should be improved?**

options/unu

**Describe how you would like the feature improved**
The UNU feature has a late updated time frame. For example
![Screen Shot 2022-09-20 at 9 39 56 AM](https://user-images.githubusercontent.com/82773076/191273339-f99d3969-f872-4cc5-b6ea-4044a2b204bc.png)
 today at market open if i run this, it gives me a table from options last updated the day before at 3pm. 

**Possibly describe the ideal way to improve this**
Live time updates?

**Comment by jmaslek** [comment]
We take this from https://app.fdscanner.com/unusualvolume

If you have another source you would recommend, feel free to let us know and we can look into it, but live options data will likely require a paid subscription somewhere.

**Comment by deeleeramone** [comment]
@jmaslek - https://www.optionvisualizer.com/api/option/search

https://www.optionvisualizer.com/option-screener/unusual-option-activity?o.open_interest=manual%7C100%7C&o.volume=manual%7C%7C&o.volume_to_open_interest=manual%7C10%7C&o.radio_option_type=manual%7Ctrue%7Ctrue&sort_by=o.volume_to_open_interest&sort_order=desc
