### ISSUE TITLE
[Bug] Economy/spectrum: Terminal hangs after image opens, need to press "enter" to restore functionality.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2574]
To recreate: `economy/spectrum` - then wait a few moments and the message will appear. The terminal will be hung until the `enter` key is pressed. 

![image](https://user-images.githubusercontent.com/85772166/191369954-ebc6ab7b-ccf7-4226-9648-4faf287993d4.png)

![image](https://user-images.githubusercontent.com/85772166/191370168-862783da-03e2-4737-9fd2-2b3153c41665.png)

**Comment by jmaslek** [comment]
boop

<img width="944" alt="Screen Shot 2022-09-20 at 8 35 52 PM" src="https://user-images.githubusercontent.com/18151143/191388733-1f475b46-6730-4fbe-a80b-e9be3b39d23c.png">

**Comment by colin99d** [comment]
@deeleeramone I am not able to reproduce this, is it still happening for you?

**Comment by deeleeramone** [comment]
This appears to have been fixed through some other PR.
