### ISSUE TITLE
Clenow Indicator Legend Missing

### ISSUE THREAD

**Issue by lawzeus** [OpenBB-finance/OpenBBTerminal#2575]
after we print a chart for clenow indicator (/stocks/ts/clenow) the output chart does not have any indication of asset in study .

this becomes confusing when looking at multiple charts.

thanks team you guys are awesome

**Comment by DidierRLopes** [comment]
Hey @lawzeus,

Sorry for late reply on this. Just fixed it.

Thank you for the kind words. If you have any question or request, let me know 😄
