### ISSUE TITLE
[Bug] User Styles are being ignored.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2577]
The easiest way I could show this is with: `"xticks_rotation": 90,` in the file `dark.mplrc.json`

![Screen Shot 2022-09-20 at 9 50 37 PM](https://user-images.githubusercontent.com/85772166/191417012-a366302a-c20d-4ef0-946f-ae19f3bd6b58.png)

This is likely a result of changing paths to where user data is located. Copying the style sheets, from the `user` folder into the `default` folder applies the changes that existed in the `user` folder.

![Screen Shot 2022-09-20 at 9 57 56 PM](https://user-images.githubusercontent.com/85772166/191417787-d9d1f01a-3bf7-4168-8bdd-4ea17f6792b3.png)

**Comment by colin99d** [comment]
Hey Darren. This is not a bug. Please add custom styles by adding the desired file to ~/OpenBBUserData/styles.
