### ISSUE TITLE
[Bug] Settings/FeatFlags are being written to a location they are not read from.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2578]
The path where the `.env` file is being written is one folder deeper, `/.openbb/`, than the file that is being read. This nullifies all changes made to this file. Keys, settings, feature flags, etc.

![Screen Shot 2022-09-20 at 10 38 59 PM](https://user-images.githubusercontent.com/85772166/191423027-b4140525-ee70-4eaa-9579-c4242543c87e.png)
![Screen Shot 2022-09-20 at 10 40 44 PM](https://user-images.githubusercontent.com/85772166/191423287-4951a947-fa72-4da0-b937-a821dea60b46.png)
![Screen Shot 2022-09-20 at 10 42 52 PM](https://user-images.githubusercontent.com/85772166/191423583-7ea5d22c-7ed2-4d1b-afcf-2dda00b2a3cc.png)

**Comment by colin99d** [comment]
<img width="673" alt="Screen Shot 2022-09-27 at 1 54 15 P@dakhouya src="https://user-images.githubusercontent.com/72827203/192518397-5fe77218-5a37-4492-b961-2e8ada672e1b.png">
@deeleeramone I think this has been fixed. I disabled everything and then reloaded and it worked.

**Comment by colin99d** [comment]
@soggyomelette cannot reproduce this earlier. I am on mac so its not an OS issue.

**Comment by deeleeramone** [comment]
This has likely been fixed with the round of bug fixes. Closing for now.
