### ISSUE TITLE
[Bug] Econometrics menu takes an incredible long time to load

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#2582]
**Describe the bug**
It takes a very long time to load the Econometrics menu and it sometimes even doesn't load at all. Depending on your internet connection it can be well over 5 minutes.

There is something being downloaded or loaded that shouldn't be. In essence all that needs to be done is import some packages, namely `statsmodels` and `linearmodels` and that's it. Apparently it is doing some sort of parsing that is messing up. **Note that this is only for the INSTALLER version, Python version has no issues.**

What I _think_ is going on that it looks for data in a specific folder that messes up in the Installer version where it looks much further than it should. E.g. in the screenshot below it messes up on a Google Drive file which shouldn't even be part of finding files to import.

**To Reproduce**
Simply open up the `econometrics` menu within the installer version.

**Screenshots**
See timestamps:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/191459791-0c201553-cdf8-472d-8f92-6b8c80acca97.png">

**Comment by montezdesousa** [comment]
@JerBouma I cannot reproduce this, mine loads almost instantly.

Do you have any idea why this path is being checked? Your help on this menu displays what path for 'custom imports'?

**Comment by JerBouma** [comment]
@montezdesousa Are you running on Mac too? Unfortunately currently on Windows which indeed doesn't have this issue. I know that within the `Econometrics` menu, there is a script running that checks all files matching .csv or .xlsx which most likely searched in folders it shouldn't have.

**Comment by montezdesousa** [comment]
> @montezdesousa Are you running on Mac too? Unfortunately currently on Windows which indeed doesn't have this issue. I know that within the `Econometrics` menu, there is a script running that checks all files matching .csv or .xlsx which most likely searched in folders it shouldn't have.

I tried on Mac and Windows. Installer is a bit slower than Python, but loads in some seconds

**Comment by JerBouma** [comment]
Then let's assume this is was just an issue on my end :)
