### ISSUE TITLE
[Bug] Yahoo finance output in stocks/fa/income is not multiplying by 1000

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2583]
<img width="683" alt="Screenshot 2022-09-21 at 12 52 52" src="https://user-images.githubusercontent.com/25267873/191497085-43dc283f-d0e8-4c2c-991e-c3719c7e0a71.png">

See Yahoo Finance

![image](https://user-images.githubusercontent.com/25267873/191497241-b681d81c-d6c6-4245-b779-6d58ab1a42b8.png)

**Comment by catalintoma** [comment]
I will take this one.
The only complication here is that not all the data is in thousands (check Basic / Diluted EPS).
I am thinking we either:

- specify explicitly which data is not in thousands
- use the dot in the value to realize it's a "per share" value

**Comment by DidierRLopes** [comment]
@catalintoma I like that "dot" idea, yes!

**Comment by catalintoma** [comment]
@DidierRLopes  The fix was merged into main

**Comment by DidierRLopes** [comment]
> @DidierRLopes  The fix was merged into main

Thank you. Let's close this 🫡
