### ISSUE TITLE
[Bug] Issue with setting expiry date

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2590]
After loading `AAPL` and going into options menu
<img width="322" alt="Screenshot 2022-09-22 at 12 02 38" src="https://user-images.githubusercontent.com/25267873/191730370-e061d450-2b22-49eb-a4e7-de7af4968075.png">

**Comment by erlandsen-tech** [comment]
I had the same error, and I thought it only was the tradier_token that was the error, however if this is not the case, I can look into this. I am a foreign resident and am unable to get a tradier token without lots of hassle so if I need to do that I will pass.

**Comment by DidierRLopes** [comment]
Merged! Thanks for solving this @erlandsen-tech !

**Comment by erlandsen-tech** [comment]
Just happy to help this amazing project! :)
