### ISSUE TITLE
[Bug] Econometrics Menu - Loaded Files and Data Columns is Unaware of any Changes Made, Like Adding

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2594]
To recreate, load a dataset and delete a column, `?`, then remove the dataset. 

<img width="1174" alt="Screen Shot 2022-09-22 at 2 58 41 PM" src="https://user-images.githubusercontent.com/85772166/191859140-182263fc-f383-4418-ae8b-a0b7111ad22f.png">

**Comment by colin99d** [comment]
I think the remove was just broken in general.
