### ISSUE TITLE
[Improve] Econometrics Menu - Data is lost when the menu is left. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2595]
Remember context is true. To recreate, load a dataset then exit and re-enter the Econometrics menu. 

<img width="1195" alt="Screen Shot 2022-09-22 at 3 08 29 PM" src="https://user-images.githubusercontent.com/85772166/191860085-fd9f0f96-3c80-4bb5-a400-47364b04a93d.png">

**Comment by simmonsj330** [comment]
Doesn't this occur for all menus?

**Comment by deeleeramone** [comment]
No, although there is a feature flag to disable the behaviour.

<img width="1258" alt="Screen Shot 2022-09-25 at 7 18 19 PM" src="https://user-images.githubusercontent.com/85772166/192181016-60f6da2a-ce4c-4778-92f5-fe3ea365be1f.png">

**Comment by deeleeramone** [comment]
It also occurs within the Portfolio menus.

**Comment by colin99d** [comment]
The forecast menu does not do this through some special engineering. That feature flag only applies for some menus.

**Comment by deeleeramone** [comment]
> 

I don't think this is a feature request because this functionality is expected, as a user, when selecting this feature flag to be true.

**Comment by colin99d** [comment]
So we need to improve how we explain the feature then.
