### ISSUE TITLE
[Bug] Portfolio - Risk Free Rate is displayed as 0.00% when portfolio was loaded with a value of 3.5%

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2596]
recreate by loading any portfolio and using the `-r` flag. 

`load -f portfolio -r 3.5`

Unclear if the setting specified is being referenced. 

<img width="1254" alt="Screen Shot 2022-09-22 at 7 30 43 PM" src="https://user-images.githubusercontent.com/85772166/191881981-26eb3f57-6a36-4946-93e5-fd57f3350928.png">

**Comment by montezdesousa** [comment]
Fixed, will PR
