### ISSUE TITLE
[Bug] Portfolio/show -h: Error: 'NoneType' object has no attribute 'limit'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2597]
<img width="720" alt="Screen Shot 2022-09-22 at 7 34 41 PM" src="https://user-images.githubusercontent.com/85772166/191882348-1789ea37-a61d-40f4-9bef-0a45315da522.png">
<img width="1114" alt="Screen Shot 2022-09-22 at 7 35 18 PM" src="https://user-images.githubusercontent.com/85772166/191882388-1cd0338f-9843-41f7-863a-956d0541173f.png">

**Comment by montezdesousa** [comment]
Fixed, will PR
