### ISSUE TITLE
[Bug] Portfolio/rbeta - Empty graph where x-axis is not a date. Error: index 0 is out of bounds for axis 0 with size 0. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2599]
Related to #2598

<img width="1207" alt="Screen Shot 2022-09-22 at 7 45 31 PM" src="https://user-images.githubusercontent.com/85772166/191883249-ac3e79e2-c74e-41d7-aab3-0dcce0e38060.png">

**Comment by montezdesousa** [comment]
Hi, can you provide more details on how to replicate this? Mine seems to work fine

![image](https://user-images.githubusercontent.com/79287829/191953280-6baec27c-a036-4464-82d0-dc6d6d08338b.png)

**Comment by deeleeramone** [comment]
Same process as https://github.com/OpenBB-finance/OpenBBTerminal/issues/2601#issuecomment-1256363326
<img width="1153" alt="Screen Shot 2022-09-23 at 8 39 02 AM" src="https://user-images.githubusercontent.com/85772166/191999301-b9688e27-5aff-4f68-aadf-159479c8ca77.png">
