### ISSUE TITLE
[Bug] Portfolio/rsort: Error: 'Series' object has no attribute 'returns' - Displays empty graph

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2600]
Related to #2598

<img width="1253" alt="Screen Shot 2022-09-22 at 7 49 44 PM" src="https://user-images.githubusercontent.com/85772166/191883667-edf632f7-2b85-4d2d-bcb5-053d39310914.png">

**Comment by montezdesousa** [comment]
Fixed, will PR
