### ISSUE TITLE
[Bug] Portfolio/rvol - No error message printed, but an empty graph with a legend is returned

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2601]
related to #2598

<img width="1224" alt="Screen Shot 2022-09-22 at 7 54 39 PM" src="https://user-images.githubusercontent.com/85772166/191884083-5199e022-38b4-43d7-b5e7-37c8dbab8729.png">

**Comment by montezdesousa** [comment]
Hi, can you provide more details on how to replicate this? Mine seems to work fine
![image](https://user-images.githubusercontent.com/79287829/191988517-4e9dfff5-861e-45a3-9adc-7192e5d73713.png)

**Comment by deeleeramone** [comment]
portfolio loaded is that same one from provided for debugging before: 

[canadian_gold.csv](https://github.com/OpenBB-finance/OpenBBTerminal/files/9635002/canadian_gold.csv)


to recreate, load portfolio and enter `rvol`
