### ISSUE TITLE
[Bug] Portfolio/PO/Params/save - Error: No such file or directory. Trying to save to a bad path.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2603]
Parameters attempted to be saved try to save it in the wrong path:
```
Error: [Errno 2] No such file or directory: '/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/portfolio/portfolio_optimization/parameters/portfolio/optimization/test.ini'
```

<img width="1216" alt="Screen Shot 2022-09-22 at 8 25 38 PM" src="https://user-images.githubusercontent.com/85772166/191886765-eef6a78a-429c-4f3b-a224-c6241af9dff7.png">

**Comment by minhhoang1023** [comment]
@JerBouma this is a bug since Danny's creation 5 months ago. I checked it quickly and it was due to the parser error. Wanna have a look into this? I tried fixing it, but it's related to the ini file creation, and has certain logic involved.

**Comment by JerBouma** [comment]
@DidierRLopes This is your baby ;)
