### ISSUE TITLE
[Bug] Stocks/dps/prom - Error: darkpool_otc() got an unexpected keyword argument 'promising'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2606]
Function is dead. 
<img width="1182" alt="Screen Shot 2022-09-22 at 10 53 01 PM" src="https://user-images.githubusercontent.com/85772166/191899395-9586e021-1c5e-4426-94e0-b785c1ba2fcd.png">

**Comment by montezdesousa** [comment]
Fixed, will PR
