### ISSUE TITLE
[Bug] Stocks/dps/ctb - Function is broken. Error: display_cost_to_borrow() got an unexpected keyword argument 'num_stocks'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2608]
<img width="542" alt="Screen Shot 2022-09-22 at 11 04 34 PM" src="https://user-images.githubusercontent.com/85772166/191900570-f2c7f099-9a77-4cbd-840a-640d629e5d77.png">

**Comment by montezdesousa** [comment]
Fixed, will PR
