### ISSUE TITLE
[Bug] /crypto/defi/ $ pool - an unexpected keyword argument 'escend'

### ISSUE THREAD

**Issue by minhhoang1023** [OpenBB-finance/OpenBBTerminal#2616]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/40023817/192141638-eda6ab80-14b3-4f63-b3ad-7d41caf5698b.png">

**Comment by erlandsen-tech** [comment]
This is a typo in display_uni_pools call in line 812 of defi_controller.py , the keyword should be "ascend" . Pushing change after I have tested it.

**Comment by DidierRLopes** [comment]
Fixed by @erlandsen-tech !
