### ISSUE TITLE
[IMPROVE] Add in the ability to search for indices within the Economy and Portfolio menu.

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#2626]
**What's the feature that should be improved?**
A request has been posted multiple times about certain indices not existing within the `index` function of the Economy menu. This makes sense because we provide merely a small list of options **although** any ticker can be inputted.

This is the same for the `bench` functionality of the Portfolio menu. This should also have a search functionality and it should be clear that the list we provide is not all that is possible.

**Possibly describe the ideal way to improve this**
The suggestion would be is to build in a search functionality, using for example the data from FinanceDatabase (querying https://raw.githubusercontent.com/JerBouma/FinanceDatabase/master/Database/Indices/_Indices%20List.json).

It is also important that it is clear that you can search and input any ticker you desire. Naming should also be more clear which can be obtained from the file.

**Additional information**
![image](https://user-images.githubusercontent.com/46355364/192215636-0f19b8e0-9ec5-425f-a122-6688e94ade36.png)

![image](https://user-images.githubusercontent.com/46355364/192216642-28405242-44e1-49b2-b551-b37aa2cd4bee.png)

**Comment by tsmith023** [comment]
@JerBouma, I'd be happy to have a go at this as a first contribution :grin:

**Comment by piiq** [comment]
@tsmith023 we have bi-weekly developer community calls happening on Fridays at 6:30pm CET / 12:30 ET / 9:30 PT on our Discord. Please join us there this Friday so that we discuss how to approach the improvement
