### ISSUE TITLE
[Bug] news command shows no results

### ISSUE THREAD

**Issue by hugo4711** [OpenBB-finance/OpenBBTerminal#2636]
1. setup api key for newsapi /keys
2.  news                   NEWSAPI                    defined, test passed        
3. /stocks
4. load tsla
5. news
6. no results are being displayed

I tried it with different stock symbols - there is no error message, but only an empty result:

`2022 Sep 26, 15:55 🔥 /stocks/ $ load tsla

Loading Daily TSLA stock with starting period 2019-09-23 for analysis.

Company:  Tesla, Inc.
Exchange: NASDAQ/NMS (GLOBAL MARKET)
Currency: USD

                                          TSLA Performance                                           
┏━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ 1 Day   ┃ 1 Week  ┃ 1 Month ┃ 1 Year ┃ YTD      ┃ Volatility (1Y) ┃ Volume (10D avg) ┃ Last Price ┃
┡━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ -8.47 % │ -9.24 % │ -7.33 % │ 9.6 %  │ -31.15 % │ 64.09 %         │ 63.38 M          │ 275.33     │
└─────────┴─────────┴─────────┴────────┴──────────┴─────────────────┴──────────────────┴────────────┘

2022 Sep 26, 15:55 🔥 /stocks/ $ news

2022 Sep 26, 15:55 🔥 /stocks/ $`

OpenBB Terminal v1.8.0

**Comment by deeleeramone** [comment]
There is some odd behaviour that is experienced where FeedParser stops working temporarily. Myself and @simmonsj330 have both experienced it drop out and then pick up again - without making any changes.

**Comment by hugo4711** [comment]
It started to work for me right after filing this bug... Murphys law I guess...

Can I provide any help to debug this issue?

**Comment by DidierRLopes** [comment]
> It started to work for me right after filing this bug... Murphys law I guess...
> 
> Can I provide any help to debug this issue?

We have been struggling with this issue for a bit. We cannot understand the intermittent behaviour

**Comment by jmaslek** [comment]
Closing this as we added a new news source (rss feeds) and the issue was something from newsapi.
