### ISSUE TITLE
[Bug] error: module 'i18n' has no attribute 'load_path' after new installation

### ISSUE THREAD

**Issue by shilkazx** [OpenBB-finance/OpenBBTerminal#2649]
**Describe the bug**

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
1. Install openbb according to [https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/openbb_terminal#anaconda--python] with conda and poetry.
2. After *poetry install* completed, run *python terminal.py*, then:
> Traceback (most recent call last):
>   File "/home/shilka/git/OpenBBTerminal/terminal.py", line 23, in <module>
>     from openbb_terminal.common import feedparser_view
>   File "/home/shilka/git/OpenBBTerminal/openbb_terminal/common/feedparser_view.py", line 7, in <module>
>     from openbb_terminal.decorators import log_start_end
>   File "/home/shilka/git/OpenBBTerminal/openbb_terminal/decorators.py", line 8, in <module>
>     from openbb_terminal import feature_flags as obbff
>   File "/home/shilka/git/OpenBBTerminal/openbb_terminal/feature_flags.py", line 21, in <module>
>     i18n.load_path.append(i18n_dict_location)
> AttributeError: module 'i18n' has no attribute 'load_path'

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
Archlinux x86_64

- Python version [e.g. 3.6.8]
3.9.13

**Additional context**
Add any other information that you think could be useful for us.

**Comment by colin99d** [comment]
Can I confirmed you performed the following steps:
1. git clone https://github.com/OpenBB-finance/OpenBBTerminal.git
2. cd OpenBBTerminal/
3. conda env create -n obb --file build/conda/conda-3-9-env.yaml
4. conda activate obb
5. poetry install

**Comment by shilkazx** [comment]
Except that I add **--depth=1** when cloning the repo.
 
> Can I confirmed you performed the following steps:
> 1. git clone https://github.com/OpenBB-finance/OpenBBTerminal.git
> 2. cd OpenBBTerminal/
> 3. conda env create -n obb --file build/conda/conda-3-9-env.yaml
> 4. conda activate obb
> 5. poetry install

**Comment by colin99d** [comment]
Do you have the environment activated? I only ever get this issue when I forget to activate my environment.

**Comment by shilkazx** [comment]
Of course, it's activated. Furthermore, the**i18n** subfolder only has one yml and one ipynb file, is it normal?

> Do you have the environment activated? I only ever get this issue when I forget to activate my environment.
