### ISSUE TITLE
[IMPROVE] Funds/Search - Get rid of required argument `--fund`. Make it easier with, `search VanGuard`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2660]
The required argument turns the command into an illogical statement that is not part of autocomplete.

<img width="351" alt="Screen Shot 2022-09-28 at 10 57 55 AM" src="https://user-images.githubusercontent.com/85772166/192854921-e61b9ebd-c4dc-42dc-aa04-cdd36d14c617.png">

```
/funds/ $ search --by issuer --fund VanGuard
```
`--fund` is a redundant argument. The command should just be `search --by issuer VanGuard`
<img width="1150" alt="Screen Shot 2022-09-28 at 10 56 20 AM" src="https://user-images.githubusercontent.com/85772166/192854613-d98846aa-4f9e-4354-834a-a6f1b5f7189f.png">

**Comment by DidierRLopes** [comment]
Working as expected!

<img width="1039" alt="Screenshot 2022-10-05 at 00 13 56" src="https://user-images.githubusercontent.com/25267873/193947413-581dcadb-d481-4231-8e20-ebcc9809e1e2.png">
