### ISSUE TITLE
[IMPROVE] Fix pylint missing-timeout

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2661]
**What's the feature that should be improved?**
Currently we ignore pylint missing-timeout. If we were to track it, we could fix potential errors from requests timing out. This has already caused integration tests to fail once. Further, we could have a terminal wide variable for how long they list. 

**Possibly describe the ideal way to improve this**
Add `timeout=cfg.TIMEOUT` to each instance of requests get/post.

At the end we should also remove `missing-timeout` from line 57 of .pylintrc

**Comment by Abelarm** [comment]
Hi @colin99d,

I could take this if is not already taken.

**Comment by colin99d** [comment]
Hello Abelarm! I love the enthusiasm, but I would stay away from this for right now. We still have to agree on whether or not to do this and how we want to implement it. When we do it, this will involve us changing thousands of function calls. There are high chances if you take this one a lot of work will go in with a low chance of PR merge.

**Comment by Abelarm** [comment]
Hi Colin thank you for the transparency! I’ll try to find a more simple issue to tackle.

**Comment by DidierRLopes** [comment]
Hey @Abelarm 

This one should be easy: https://github.com/OpenBB-finance/OpenBBTerminal/issues/2455 do you want to tackle it?

If you need any help you can ping me and I can help you. Let me know 😄
