### ISSUE TITLE
[Bug] quandl api key not working (nasdaq data link)

### ISSUE THREAD

**Issue by hugo4711** [OpenBB-finance/OpenBBTerminal#2673]
Even though under /keys the quandl api key shows up green and ready to use, I get:

```
2022 Sep 29, 17:52 🔥 /economy/ $ bigmac
{"quandl_error":{"code":"QEAx01","message":"We could not recognize your API key: REPLACE_ME. Please check your API key and try again. You can find your API key under your account settings."}}
Unable to get big mac data

2022 Sep 29, 17:52 🔥 /economy/ $
```

**Comment by colin99d** [comment]
Hello! Can you confirm that you are on the last version of the terminal (run `git pull` if you are not using the installer). I just tried this and it worked fine for me. 

<img width="867" alt="Screen Shot 2022-09-30 at 8 02 39 AM" src="https://user-images.githubusercontent.com/72827203/193201025-dcfed64b-5e69-42cd-9ddf-72ad62d42b38.png">

I even tried closing the programing and reopening to confirm the keys were not being stored in memory, and it still worked.

**Comment by colin99d** [comment]
This was probably an error because we changed how things were stored but did not update everything right. We have released several patches since so for now I am going to close, If you still have issues reopen this issue and at me.

**Comment by hugo4711** [comment]
Confirmed - it works in the latest version I just pulled.
