### ISSUE TITLE
[FR] integrate socialsentiment.io instead of sentimentinvestor.com

### ISSUE THREAD

**Issue by hugo4711** [OpenBB-finance/OpenBBTerminal#2674]
sentimentinvestor.com does not seem to be working anymore. There is no ability to contact their support.

Perhaps another option would be https://socialsentiment.io/

**Comment by JerBouma** [comment]
Just FYI, this is regarding these functionalities:
![image](https://user-images.githubusercontent.com/46355364/194063862-ccffb51e-75f9-4b2c-b357-26477c0c164f.png)
