### ISSUE TITLE
[Bug] reports/crypto

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2679]
**Describe the bug**
Using `reports/crypto` creates a bunch of shows a bunch of charts (on my screen not in the report).

**To Reproduce**
Run `python terminal.py reports/crypto btc`

**Screenshots**
<img width="1728" alt="Screen Shot 2022-09-30 at 7 44 19 AM" src="https://user-images.githubusercontent.com/72827203/193198665-b5246a5c-1b66-4b3b-9775-f5afd405f5e0.png">

**Desktop (please complete the following information):**
- OS: MacOs Monterey
- Python version 3.9

**Comment by minhhoang1023** [comment]
I also have the same problem
