### ISSUE TITLE
[IMPROVE] Alphabetize Documentation Navigation Sidebar

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2685]
The randomness does not follow logic, alphabetizing is the natural expectation in the absence of it. I don't know how to navigate using the sidebar; as a user, it's annoying and it takes far too long to find items visually.

![Screen Shot 2022-09-30 at 8 47 56 PM](https://user-images.githubusercontent.com/85772166/193386455-20e7f8de-80c8-4df2-ac9f-fa215ee22e32.png)

**Comment by koriop** [comment]
Can I take up this issue?

**Comment by bilal-aamer** [comment]
@deeleeramone Could you pls assign this issue to me ! Thanks

**Comment by DidierRLopes** [comment]
> Can I take up this issue?

Sorry @koriop and @bilal-aamer  just saw this now! So sorry 😢  Is any of you still happy to take it?

This has a #hacktoberfest flag now as well 😄

**Comment by bilal-aamer** [comment]
Sure! @DidierRLopes

**Comment by DidierRLopes** [comment]
Perfect, just did it! @bilal-aamer  😄

**Comment by deeleeramone** [comment]
loving the enthusiasm!

**Comment by JerBouma** [comment]
Sounds good to have this, indeed!

**Comment by wonhyeongseo** [comment]
Hello everyone, hope you are doing well.
I am working on this PR for Hacktoberfest. May you please guide me on ways to improve? Any help would be greatly appreciated.
Thank you for making this awesome repo. @DidierRLopes @JerBouma @deeleeramone
