### ISSUE TITLE
[Bug] Economy/Macro --parameters POP --countries China. Error: 'Tens of thousands'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2691]
This function produces an error when the `parameters` is POP and `--countries` is China. 
<img width="515" alt="Screen Shot 2022-10-03 at 8 38 23 AM" src="https://user-images.githubusercontent.com/85772166/193618725-0db64d0d-7b02-46e1-aa98-c7fe5b4fc6f1.png">

Other countries return a chart as expected.

**Comment by colin99d** [comment]
<img width="882" alt="Screen Shot 2022-10-04 at 9 28 13 AM" src="https://user-images.githubusercontent.com/72827203/193760014-4930bbc9-1032-4f19-bb4a-a8b0d025be69.png">
Its funny because I can't reproduce the error but I know how to fix it.
