### ISSUE TITLE
[IMPROVE] Stocks/FA - when plotting the Financial Statement Items, include the price on a separate Y-Axis

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2697]
Plotting components of the Financial Statement is great, but it would be ever better as an overlay on a price chart with a second y-axis.

![image](https://user-images.githubusercontent.com/85772166/193643015-09327f9b-e638-4e72-9d4b-74c0ceab98d6.png)

**Comment by catalintoma** [comment]
@JerBouma  
This is something that looks interesting and I would like to tackle it. 

@deeleeramone can you please add some more details to help me find the code?

- is that snapshot coming from the terminal or an external tool?
- can you specify the commands and arguments you wish to extend explicitly? I am new to this and don't really know how to navigate

**Comment by deeleeramone** [comment]
It would also be reasonable to build in some logic for if `-p` is True, show all statements available over time.

**Comment by catalintoma** [comment]
@deeleeramone thanks for the explanation, I am aware of those commands from FA.
By default, it uses Yahoo Finance which only shows 5 years worth of data. 
There is limit argument, but that is still constrained by the maximum value the source has available.

I think the biggest issue will be how will this price chart look over such scarce data? In the default source view there are only 5 (annual) points on the X-axis

**Comment by deeleeramone** [comment]
A five-year price chart is not an unreasonable window to look at, not so pretty as a bar chart I can understand that. The overall intention is to enable the ability to easily overlay data like this, or multiple points, with the underlying price action.

**Comment by JerBouma** [comment]
@catalintoma Go for it! Let me know if you need any help or explanation.
