### ISSUE TITLE
[IMPROVE] Stocks/SIA - If ticker is loaded, default to include in results. + other things related to `ticker`.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2720]
The scenario is as follows: 

You enter the `SIA` menu with a stock loaded, and you would like to know more about the global industry and how that stock compares. 

![Screen Shot 2022-10-05 at 5 22 20 PM](https://user-images.githubusercontent.com/85772166/194186838-61f0e6e1-bb62-493f-bc83-c597695698dc.png)

Currently, although fields self-populate, the ticker you have loaded is not always destined to show up on the chart. In this example, none of the returned tickers are the loaded ticker:

![Screen Shot 2022-10-05 at 5 20 04 PM](https://user-images.githubusercontent.com/85772166/194186634-2ae09ef3-06c3-4aff-91d9-f26f7bf261f9.png)

If it does, it might be from some foreign exchange that is not the listing you had loaded:

![Screen Shot 2022-10-05 at 5 23 26 PM](https://user-images.githubusercontent.com/85772166/194186956-6840d38c-45af-424d-9e1b-737e5b208e1f.png)

With `Exclude Exchanges: False`, it shows the same "companies", but with different tickers and a wildly different market cap. What is the currency being used to measure market cap and why is it changing on me out of nowhere? How can I determine what these numbers are supposed to mean? 

![Screen Shot 2022-10-05 at 5 25 00 PM](https://user-images.githubusercontent.com/85772166/194187537-4e4d8932-7362-4d52-8808-fc67885a80e0.png)

I thought these were both banks for Switzerland, why is it telling me about Mexican Pesos and comparing them as Apples-to-Apples? 

Essentially, this menu presents unreliable data to the user and there is nothing that they can do about it.

**Comment by jmaslek** [comment]
rip SIA
