### ISSUE TITLE
[Bug] /funds/load returns 403 error.

### ISSUE THREAD

**Issue by chrismolli** [OpenBB-finance/OpenBBTerminal#2724]
**Describe the bug**
Upon loading of a fund by name or symbol the terminal returns:
```
openbb_terminal.mutual_funds.investpy_model|get_fund_historical|0|Exception: ERR#0015: error 403, try again later. 
- Traceback (most recent call last): 
- File cut/file/path/decorators.py, line 66, in wrapper - value = func(*args, **kwargs) 
- File cut/file/path/investpy_model.py, line 189, in get_fund_historical 
- investpy.funds.get_fund_historical_data( 
- File cut/file/path/funds.py, line 638, in get_fund_historical_data
- ConnectionError: ERR#0015: error 403, try again later.
```

**To Reproduce**
Open the terminal, go to funds, load a fund symbol.

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: MacOSX 11.6
- Python version 3.9.9

**Additional context**
According to the underlying usage of `investpy` the function `get_fund_historical_data` is broken due to an undocumented API deprecation by Investing.com. The analogue issue for stocks is tracked [here](https://github.com/alvarobartt/investpy/issues/600).

**Comment by jmaslek** [comment]
As you mention, we are hoping that this gets patched up.   We can look into commenting out the function for the time being.

An interim fix could be  to load through the stocks menu.  For example, if I run `funds/overview`, I see FCNTX on there, which I can load using `stocks/load FCNTX`.  If you are looking outside the US, I am not sure if things will match up between yahoo's naming and investing.coms naming.

**Comment by deeleeramone** [comment]
this error message is different: 
<img width="1056" alt="Screen Shot 2022-10-06 at 9 51 01 PM" src="https://user-images.githubusercontent.com/85772166/194470171-5cdc142b-c720-4e5a-bc7b-d9a919bf933f.png">

**Comment by alvarobartt** [comment]
Hi, @jmaslek note that I released [`investiny`](https://github.com/alvarobartt/investiny) just a week ago and it supports more or less the same functionality as `investpy`, while I wait for Investing.com to answer my email to get to an agreement to continue developing `investpy`.

If you need help with the integration of `investiny` in your package let me know and I'll try to fill in a PR 🤗 All the best!

**Comment by chrismolli** [comment]
> this error message is different, and is a recent development:
> <img alt="Screen Shot 2022-10-06 at 9 51 01 PM" width="1056" src="https://user-images.githubusercontent.com/85772166/194470171-5cdc142b-c720-4e5a-bc7b-d9a919bf933f.png">

This is just what is printed in the frontend. When you look at your logs under `~/OpenBBUserData/logs/` you will see the underlying log messages.

**Comment by jmaslek** [comment]
> Hi, @jmaslek note that I released [`investiny`](https://github.com/alvarobartt/investiny) just a week ago and it supports more or less the same functionality as `investpy`, while I wait for Investing.com to answer my email to get to an agreement to continue developing `investpy`.
> 
> If you need help with the integration of `investiny` in your package let me know and I'll try to fill in a PR 🤗 All the best!

Hi @alvarobartt!  Nice to chat with you :)

I did dig around slightly with the new package and was going to look into using that once you have the time stamps integrated (ummmm looks like you have added that now!). Currently I have only integrated your package with mutual fund menus but will be looking at adding more in the upcoming months.

If there are more areas you would like to integrate, we can chat :)

**Comment by alvarobartt** [comment]
> > Hi, @jmaslek note that I released [`investiny`](https://github.com/alvarobartt/investiny) just a week ago and it supports more or less the same functionality as `investpy`, while I wait for Investing.com to answer my email to get to an agreement to continue developing `investpy`.
> 
> > 
> 
> > If you need help with the integration of `investiny` in your package let me know and I'll try to fill in a PR 🤗 All the best!
> 
> 
> 
> Hi @alvarobartt!  Nice to chat with you :)
> 
> 
> 
> I did dig around slightly with the new package and was going to look into using that once you have the time stamps integrated (ummmm looks like you have added that now!). Currently I have only integrated your package with mutual fund menus but will be looking at adding more in the upcoming months.
> 
> 
> 
> If there are more areas you would like to integrate, we can chat :)

I'm still working on some fixes, improvements and new features, but sure we can have a chat to collaborate on both ends. Keep up the great work! ✨
