### ISSUE TITLE
[IMPROVE] Allow news to be real-time

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2727]
We could just have a loop that checks for new news on the RSS feed at (let's say) every 1 second. Then if there's an update we flag it to the user so that they get it as soon as it's out.

We could allow users to leave this command with "Ctrl+C", basically working similarly to how Pyth price feeds are.

**Comment by deeleeramone** [comment]
I think this would be very helpful and is a functionality that can be used for other purposes as well, such as quote streams. You could run multiple terminal instances with one left to stream uninterrupted and the other having normal terminal operations.
