### ISSUE TITLE
[Bug] stocks/load aapl/sia/clear mktcap/vis re

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2728]

**Comment by deeleeramone** [comment]
This menu has a LONG list of problems and it should be seriously considered to remove it. The data is unreliable and, in a lot of cases, is wrong.
https://github.com/OpenBB-finance/OpenBBTerminal/issues/2720

**Comment by deeleeramone** [comment]
![image](https://user-images.githubusercontent.com/85772166/195953922-a8f18806-36dc-4177-b1d5-3e2fd74abe38.png)

Like here, a currency pair is apparently part of the Uranium industry.
