### ISSUE TITLE
Incompatible MacOs Version

### ISSUE THREAD

**Issue by gtaouil** [OpenBB-finance/OpenBBTerminal#2729]
I get  this message when I get into to economy menu:

Error: dlopen(/Applications/OpenBB Terminal/.OpenBB/lxml/etree.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/OpenBB Terminal/.OpenBB/lxml/etree.cpython-39-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/OpenBB Terminal/.OpenBB/lxml/etree.cpython-39-darwin.so

I think this problem is with my Os Version. My system is MacOS High Sierra 10.13.1.2. Is there way to compile the system to be compatible with my Os?

**Comment by colin99d** [comment]
Hello @gtaouil! Thank you for downloading our installer! MacOs High Sierra reach end of life November 30th 2020, so unfortunately it is out of scope for our support.
