### ISSUE TITLE
[IMPROVE] Compare with BB terminal 

### ISSUE THREAD

**Issue by NoelJacob** [OpenBB-finance/OpenBBTerminal#2730]
**What's the feature that should be improved?**
Show feature parity with Bloomberg Terminal on home page or repo. Someone with firsthand access to BB terminal could really help. No idea about feasibility of this.

**Comment by colin99d** [comment]
Love the idea! If someone has access and wants to talk about how to do this I would love to talk.

**Comment by skhan59bbk** [comment]
I have BBG terminal access. Let me know what you're after.

**Comment by qmarsun** [comment]
I would like to take this #2730
