### ISSUE TITLE
[Bug] pred/conv1d is broken

### ISSUE THREAD

**Issue by husmen** [OpenBB-finance/OpenBBTerminal#2732]
**Describe the bug**
Trying to run predictions using `conv1d` results in the following error:

```
Could not load library libcudnn_cnn_infer.so.8. Error: libcuda.so: cannot open shared object file: No such file or directory
```

All other models worked with no issue.

**To Reproduce**
- crypto
- load eth
- pred
- conv1d

**Screenshots**

**Desktop (please complete the following information):**

- OS: WSL2 (Ubuntu 22.04.1 LTS) on Windows 11
- Python version 3.9

**Additional context**
I tried tensorflow from both `conda` and `pip`. the former automatically installed  `cudatoolkit 11.7.0` and `cudnn 8.4.1.50`. And for the latter, I manually installed `cuda 11.7.0` and `cudnn 8.5.0` under `/usr/local/cuda/`. Both resulted in the same error.

**Comment by colin99d** [comment]
I am going to close this because we removed prediction with our new menu! @husmen please tell me how you like the new forecast menu, it blows pred out of the water.

**Comment by husmen** [comment]
The menu is nice but the issue persists. This time in `tcn`.
In the meantime, I submitted a PR #2829 to enable GPU support for some of the models.
