### ISSUE TITLE
[Improve] New menu is not accessible without rebuilding the Python Environment. Error: Please install forecast version.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2746]
<img width="1116" alt="Screen Shot 2022-10-08 at 1 49 24 PM" src="https://user-images.githubusercontent.com/85772166/194727364-8bd23ba4-4c6f-4601-822e-e2aea99c121d.png">

**Comment by deeleeramone** [comment]
`poetry install -E prediction` does not overcome this.

**Comment by colin99d** [comment]
Hey Darren! Did you follow the installation guide step by step? If you do not follow it exactly the terminal will not work.

**Comment by deeleeramone** [comment]
as a user who has used `update` to have many new functions and menus added, it is not at all obvious that the version of `conda` might be problematic. everything appears to install correctly except for when you actually enter the menu.

users will need to know several things:

- M1/ARM versions for the Mac M1 systems will absolutely need to have a `conda` installation that is x86/x64
- the cache should be cleaned prior to rebuilding the virtual environment.

**Comment by colin99d** [comment]
So you would like the forecast menu to have better instructions on how to get the menu working?

**Comment by deeleeramone** [comment]
The forecast menu installation should not be a "separate" item, it's part of the main process and should be the *default* installation.

**Comment by colin99d** [comment]
This is a good idea, but is also comes with some drawbacks. I think it should be up to our product team to decide @minhhoang1023 @JerBouma. But in the mean time if you would like a more detailed error message in the forecast menu I can help there.

**Comment by deeleeramone** [comment]
the only drawback is you have to reinstall the virtual environment and our previous installation instructions are voided.

**Comment by colin99d** [comment]
I think the drawbacks are:
- Larger download size
- Stricter installation requirements (miniconda only?)
- More potential errors during installation

**Comment by deeleeramone** [comment]
those are the requirements to run the software.

**Comment by JerBouma** [comment]
I think it is fine for now to keep the seperate versions mostly due to the larger size. We could use some better instructions when you receive this error as I recall I also struggled with this and didn't understand the issue.

Could you look into this @colin99d?
