### ISSUE TITLE
[Bug] Latest PRs break the API and can't initiate it.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2748]
the current main branch throws an error when initiating the API:
![image](https://user-images.githubusercontent.com/85772166/194742447-d77ddbe8-921b-476a-91c3-a08809e95556.png)

`git revert 7fd72d9ee1e8847717195859bf6d608268a94e2f`
![image](https://user-images.githubusercontent.com/85772166/194742466-8f33c46f-b0f9-48f7-94a8-3e2b38e3426d.png)

**Comment by colin99d** [comment]
Can you pull main and see if this is still happening?

**Comment by hjoaquim** [comment]
Seems fine now:
![image](https://user-images.githubusercontent.com/48914296/195080994-19458bad-2553-4345-b74f-0d0d5f02593d.png)
Can we close it? @deeleeramone @colin99d
