### ISSUE TITLE
/stocks/th local variable referenced before assignment

### ISSUE THREAD

**Issue by Gabighz** [OpenBB-finance/OpenBBTerminal#2762]
**Describe the bug**
Calling /stocks/th returns:

    Error: local variable 'result' referenced before assignment

    Error: 'builtin_function_or_method' object has no attribute 'values'

**To Reproduce**
- Open terminal
- Type stocks
- Type th

**Desktop (please complete the following information):**

- OS: Windows 11
- Python version: 3.10.0

**Additional context**
Will look into making a pull request later but no promises.

**Comment by Jrryy** [comment]
I have already identified the error and fixed it, and I'm currently writing some tests for it. However, if you'd still want to fix it yourself and upload a PR, I can explain what the error is and where to look for it.

**Comment by Gabighz** [comment]
Glad to hear that! Sounds cool. Thanks for the offer, but credit's all yours!

Feel free to ping me for a code review, would be happy to help.

**Comment by Jrryy** [comment]
Sure, will link the issue when I'm done
