### ISSUE TITLE
[Bug] You are not using the lastest version incorrectly rendered

### ISSUE THREAD

**Issue by tinix84** [OpenBB-finance/OpenBBTerminal#2776]
**Describe the bug**
after update the, openbb shows terminal not last version

**To Reproduce**
install openbb in wsl

**Screenshots**
![image](https://user-images.githubusercontent.com/16301528/195001910-11f30951-87d1-417e-b38e-ba2c63377498.png)

**Desktop (please complete the following information):**

- OS: win wsl
- Python version 3.9

**Additional context**
Add any other information that you think could be useful for us.

**Comment by colin99d** [comment]
I am not able to reproduce this, but I have made a fix that should result in this message being displayed less.
