### ISSUE TITLE
[IMPROVE] Similar to the Terminal documentation, the SDK documentation needs to be alphabetised 

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#2780]
As is done with #2685 (PR: #2760), this also should be done for the SDK (currently named "API") documentation. See the following: https://openbb-finance.github.io/OpenBBTerminal/api/

**Comment by shngt** [comment]
Hi, I'd like to take a stab at this for Hacktoberfest. I noticed that the linked PR says the yaml config for the SDK section is auto-generated - could you please point me to where that happens? I guess that part would need to be changed to fix this issue?

**Comment by JerBouma** [comment]
@colin99d Can you help out here?

**Comment by colin99d** [comment]
https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/docs/generate.py here is the link to the file that generates our documentation!

**Comment by shngt** [comment]
Thank you! :) How exactly is this file run? I have a fix in mind but am not sure how to test it
