### ISSUE TITLE
[Bug] Forecast Menu - Files in User Data Folder Are Not Found With `Load`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2788]
It is reading files only from the folder located in the application, `custom_imports/forecasting`. The `OpenBBUserData` folder is not being read at all.

![Screen Shot 2022-10-11 at 8 22 58 AM](https://user-images.githubusercontent.com/85772166/195133455-2324c51c-beb4-4fe6-b4da-c97f208d4c2a.png)

**Comment by martinb-bb** [comment]
@colin99d  we should remove looking into the `custom_imports` and only look into `OpenBBUserData/imports/forecasting`

**Comment by colin99d** [comment]
Will do

**Comment by martinb-bb** [comment]
Fixed.
