### ISSUE TITLE
[Bug] crypto/ov/hm is not working

### ISSUE THREAD

**Issue by jose-donato** [OpenBB-finance/OpenBBTerminal#2800]
**Describe the bug**
`crypto/ov/hm` is broken

**Screenshots**
<img width="799" alt="image" src="https://user-images.githubusercontent.com/43375532/195324438-bf8ebb26-2852-4bf3-a23b-fd54774d84b0.png">
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/43375532/195324503-b91a4242-c79c-45d7-9f51-27c0313dfdc2.png">

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by erlandsen-tech** [comment]
Ill see what I can do about this.

**Comment by jose-donato** [comment]
> Ill see what I can do about this.

Amazing! Let me know if you need any help

**Comment by erlandsen-tech** [comment]
I assume this is due to the NaN and 0 values in the table. Will probably have time to fix by Sunday. 🧐
