### ISSUE TITLE
e command doesn't allow the terminal to exit

### ISSUE THREAD

**Issue by eonvdk** [OpenBB-finance/OpenBBTerminal#2804]
**Describe the bug**
e command doesn't allow the terminal to exit
Instead exit works

**To Reproduce**

1. Open terminal
2. Type "e" to exit
3. "e" command doesn't work
4. Type "exit" instead and that works

**Screenshots**

"e" command not working
<img width="569" alt="Screenshot 2022-10-12 at 15 35 11" src="https://user-images.githubusercontent.com/3930974/195344405-cbe45290-4518-40d5-835b-b00a619df1fb.png">

"e" command in the instruction panel at the bottom of the window should be "exit" - "exit" works
<img width="682" alt="Screenshot 2022-10-12 at 15 19 18" src="https://user-images.githubusercontent.com/3930974/195343506-42e2cd2b-723c-4f1b-9f52-d5a8261f8153.png">

**Desktop (please complete the following information):**

- OS: macOS Monterey 12.6
- Python version - Python 3.9.6

**Additional context**
Add any other information that you think could be useful for us.

**Comment by erlandsen-tech** [comment]
I fix

**Comment by erlandsen-tech** [comment]
It should be fixed now in the pr
