### ISSUE TITLE
[Bug] Stocks/disc/upcoming - no output.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2812]
`stocks/disc/upcoming` - empty dataframe returned.

<img width="809" alt="Screen Shot 2022-10-12 at 2 17 43 PM" src="https://user-images.githubusercontent.com/85772166/195449764-90fc4166-cc09-4a5e-a1e7-73b5fc43e28f.png">

**Comment by jmaslek** [comment]
Ummmm
```
2022 Oct 12, 17:44 (🦋) /stocks/disc/ $ upcoming

      Upcoming Earnings Releases       
┏━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃     ┃ Earnings on 2022-10-12        ┃
┡━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ PEP │ PepsiCo, Inc.                 │
├─────┼───────────────────────────────┤
│ DCT │ Duck Creek Technologies, Inc. │
└─────┴───────────────────────────────┘
2022 Oct 12, 17:44 (🦋) /stocks/disc/ $

```

**Comment by deeleeramone** [comment]
I guess it's hit-and-miss then. I was trying for 15-20 minutes. 

<img width="436" alt="Screen Shot 2022-10-12 at 2 49 51 PM" src="https://user-images.githubusercontent.com/85772166/195454613-6688c06e-c78a-479e-b599-a3c506703fac.png">
