### ISSUE TITLE
[Bug] fund/load --fund voo Error: time data '13/10/2022' does not match format '%m/%d/%Y'

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2820]
**Describe the bug**

**To Reproduce**
`python terminal.py fund/load --fund voo`

**Screenshots**
<img width="688" alt="Screen Shot 2022-10-13 at 1 14 24 PM" src="https://user-images.githubusercontent.com/72827203/195593288-dfc92e93-9322-456d-8531-b60956c3c1f5.png">

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by 0xDareDevil** [comment]
This is strange issue. The error appeared initially when I started testing, after that it disappeared but now no data is returned.. will look into it
