### ISSUE TITLE
[Bug] Can't Import API - Latest Update to Main Breaks 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2824]
![Screen Shot 2022-10-13 at 10 40 15 AM](https://user-images.githubusercontent.com/85772166/195667472-c059d5fc-69b6-46c9-8e2d-e98d518b75bf.png)

**Comment by deeleeramone** [comment]
![Screen Shot 2022-10-13 at 10 48 09 AM](https://user-images.githubusercontent.com/85772166/195669055-dc38f3ce-0efb-4cb8-9280-b8731aae5109.png)

**Comment by deeleeramone** [comment]
manually updating 3 dependencies resolves the issue:
```
pip install --upgrade numpy==1.23.4
pip install kaleido
pip install --upgrade setuptools
```
![Screen Shot 2022-10-13 at 11 07 28 AM](https://user-images.githubusercontent.com/85772166/195673045-c7ad8ee4-2556-4914-afc4-bc1d43b945cb.png)

**Comment by colin99d** [comment]
I am unable to reproduce this, Darren had you been doing anything different with your dependencies?

**Comment by deeleeramone** [comment]
Nope. This was immediately after pulling from main yesterday morning.

**Comment by colin99d** [comment]
Had you run poetry install?

**Comment by deeleeramone** [comment]
Nope. Literally had changed nothing and it was working fine when I went to sleep. The only things that changed were deltas in the code.
