### ISSUE TITLE
[Bug] API - portfolio.po.maxdecorr - Error: get_max_decorrelation_portfolio() got an unexpected keyword argument 'table'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2825]
Docstring at every level says there is an argument for `table`

openbb.portfolio.po.maxdecorr(symbols = ['SPY', 'QQQ', 'BND', 'GOVT', 'TLT', 'JNK'], table = True)

```
Error: get_max_decorrelation_portfolio() got an unexpected keyword argument 'table'

2022-10-13 11:10:32 openbb_terminal.portfolio.portfolio_optimization.optimizer_model ERROR: Exception: get_max_decorrelation_portfolio() got an unexpected keyword argument 'table'
TypeError: get_max_decorrelation_portfolio() got an unexpected keyword argument 'table'
```

![Screen Shot 2022-10-13 at 11 11 24 AM](https://user-images.githubusercontent.com/85772166/195674438-b5f816e8-ecce-4506-856a-fd9ca68eb6d9.png)

`chart = True` returns a dictionary and not a chart. 

![Screen Shot 2022-10-13 at 11 16 57 AM](https://user-images.githubusercontent.com/85772166/195674838-6f156740-6fd1-4b37-80c2-fda228ca7d18.png)

**Comment by montezdesousa** [comment]
This was fixed here https://github.com/OpenBB-finance/OpenBBTerminal/pull/3443
