### ISSUE TITLE
[FR] Multi-language support

### ISSUE THREAD

**Issue by wonhyeongseo** [OpenBB-finance/OpenBBTerminal#2855]
**What's the problem of not having this feature?**
Multi-language support is necessary for wider adoption by the global community. As a translator I would like to contribute to this endeavor on OpenBBTerminal as well. It would help attract a plethora of well-done commits.

**Describe the solution you would like**
Use of localization software such as crowdin.com with its Open-source pricing model will definitely help.

**Describe alternatives you've considered**
- manual i18n with simple folders for each language, but this turns out to be poorly maintained in the long run.
- global vendors for profit like **s. I use them at work and I don't like them.

**Additional information**
https://crowdin.com/page/open-source-project-setup-request

![Screenshot_20221015_105331_Chrome.jpg](https://user-images.githubusercontent.com/29195190/195963798-51de5bd6-78c1-4aa0-9c12-f0222f311375.jpg)

**Comment by colin99d** [comment]
I love this idea! Our terminal is already set up to allow for internationalization easily, so contributions here would be very appreciated.
