### ISSUE TITLE
[Bug] Errors not handled in reports / equity

### ISSUE THREAD

**Issue by kairosdojo** [OpenBB-finance/OpenBBTerminal#2860]
**Describe the bug**
`reports` → `equity <stock_name>` → several errors displayed

They might be due to lack of valid APIs. 

**To Reproduce**
Because the `stdout` of the notebook `equity.ipynb` is captured by the context in [reports_controller.py](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/reports/reports_controller.py#L281) you first have to disabled it temporarily:

```
            # Run the report
            try:
                console.print(f"Report to run: {report_to_run}")
                notebook_execution_output = io.StringIO()
                #with contextlib.redirect_stdout(notebook_execution_output):
                importlib.import_module(
                        f"openbb_terminal.reports.{report_to_run}copy"
                    )

```
Then:
`python terminal.py` / `reports` / `equity <stock_name>` → several errors displayed

**Screenshots**
![Screenshot_2022-10-15_11-50-44](https://user-images.githubusercontent.com/22766463/195980370-b0ccc204-4eba-4c56-a02a-6bce067c7b7e.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux 22.0.0
- Python version 3.9.6

**Comment by colin99d** [comment]
Closing as duplicate.
