### ISSUE TITLE
[Bug] stocks command non-responsive

### ISSUE THREAD

**Issue by AntouanK** [OpenBB-finance/OpenBBTerminal#2863]
Trying the docker version of it on my PC ( manjaro/arch linux ).

Trying `news` or setting API keys works.
But `stocks` gets stuck and doesn't do anything. I have to ctrl+c to get out.

the command I use
```
docker run -v ~/.openbb_terminal:/home/python/.openbb_terminal -v ~/OpenBBUserData:/home/python/OpenBBUserData -it --rm ghcr.io/openbb-finance/openbbterminal-poetry
```

example : 
https://asciinema.org/a/jsWwzVgJC4WJaMHN9QQ6L9wQo

On a separate note, the API keys I set do not persist, once I close the container they are gone. The folders I mount are always empty.
```
❯ ls .openbb_terminal OpenBBUserData
.openbb_terminal:
total 16K
drwxr-xr-x    2 antouank 4.0K Oct 15 23:07 .
drwx--x---+ 129 antouank  12K Oct 15 23:32 ..

OpenBBUserData:
total 16K
drwxr-xr-x    2 antouank 4.0K Oct 15 23:07 .
drwx--x---+ 129 antouank  12K Oct 15 23:32 ..
```

**Comment by colin99d** [comment]
We need to hurry up and push the new docker image. I can take lead on this task.

**Comment by AntouanK** [comment]
:+1: 
Let me know if there's some way I can help debug/test it.

**Comment by colin99d** [comment]
We have now pushed version 1.9.1. Let me know if you have any issues.
