### ISSUE TITLE
[Bug] Setting a bad environment variable can brick the terminal

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2865]
**To Reproduce**
`python terminal.py pheight`, then restart the terminal

**Screenshots**
<img width="753" alt="Screen Shot 2022-10-16 at 8 44 19 AM" src="https://user-images.githubusercontent.com/72827203/196022119-764500a7-98ac-4388-abfa-254caae5c8e5.png">

**Comment by andrewkenreich** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/23067478/199635935-f2916e92-97f6-4970-99bd-c45bfe97832c.png">

Mine still runs after this

**Comment by colin99d** [comment]
I added handling for some of them, but we need to add handling for the rest.
