### ISSUE TITLE
[IMPROVE] Where the input of a command is a list, there is not a consistent syntax system-wide. Space? Comma? Space and Comma? Capital Sensitive?

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2866]
Everything works, but it's hard to know which functions have what requirements. Many are `space`, some are `comma`. Is there distinction between a phrase and a list?

![Screen Shot 2022-10-16 at 7 56 09 PM](https://user-images.githubusercontent.com/85772166/196079731-96303da3-4b22-4a7b-a689-848e0c13f790.png)

**Comment by jmaslek** [comment]
I duped this at #2887 with a helpful description
