### ISSUE TITLE
[FR] Keys menu: `remove` Command

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#2886]
**What's the problem of not having this feature?**
Currently, there is no way to remove keys from your environment other than manually changing your `.env` file. This is true for the installer, SDK, and conda terminal. Adding a feature that allows the user to remove previously inputted keys would be beneficial.

**Describe the solution you would like**
Add a `remove` command with the functionality `remove <key>`. 

Example
```
remove fred
Successfully removed fred key!
```

**Comment by piiq** [comment]
should this be a flag (argument) for an existing command in the keys menu?
example:
```
2022 Oct 18, 04:37 (🦋) /keys/ $ tokenterminal -h
usage: tokenterminal [-k KEY] [-h]

Set Token Terminal API key.

optional arguments:
  -k KEY, --key KEY  key (default: None)
  -r , --remove      remove existing key
  -h, --help         show this help message (default: False)
```

**Comment by AK6263** [comment]
Hi, is anybody working on this issue? I would like to give it a try.

**Comment by jmaslek** [comment]
> Hi, is anybody working on this issue? I would like to give it a try.

Have at!
