### ISSUE TITLE
[FR] use version numbering YYYY-MM instead of sequence numbers v2022-10 vs v1.9

### ISSUE THREAD

**Issue by qmarsun** [OpenBB-finance/OpenBBTerminal#2888]
**What's the problem of not having this feature?**
A clear description of what you are lacking, or why you need this additional feature.

**Describe the solution you would like**
its very clear when was that version was released and How old version I am used.
Avoid extra lookup what is 1.8 when was released.

**Describe alternatives you've considered**
None. 

**Additional information**
None

**Comment by jmaslek** [comment]
Hey thanks for the suggestion!  

We decided to go with the major.minor.patch versioning, which was the preference across the team.  Versioning with YYYY-MM would require further subversioning if we need to put out multiple patches or versions in the same calendar month.  We can potentially look into adding the release date along the bottom of the terminal.

Previous releases all live at: https://github.com/OpenBB-finance/OpenBBTerminal/releases

**Comment by qmarsun** [comment]
okay understand  the team decisions. I am also reading  the 1.9 as 
( 1st year release and 9  for (end of sep month release ) . 
.if we follow this consistent.  then next year end of March release 2.2 like that. 
 just sharing
c++ following the year in their release  https://isocpp.org/files/img/timeline-2022-07.png
