### ISSUE TITLE
[Bug] `reports/ forex usdgbp` Error : 'list' object has no attribute 'to_html'

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2900]
<img width="408" alt="Screen Shot 2022-10-18 at 1 20 29 PM" src="https://user-images.githubusercontent.com/72827203/196416303-7a0785ad-c7d7-40b1-aa71-5dd100545d23.png">

**Comment by hjoaquim** [comment]
@montezdesousa can we close this?

**Comment by montezdesousa** [comment]
> @montezdesousa can we close this?

yes, outdated vs current version
