### ISSUE TITLE
[Bug] `reports/equity tsla` Error : list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2901]
<img width="665" alt="Screen Shot 2022-10-18 at 1 29 56 PM" src="https://user-images.githubusercontent.com/72827203/196417722-0403264a-9b32-44b3-bbf1-440ce1604228.png">
ands to reproduce the behavior

**Comment by colin99d** [comment]
This also happens for me on the crypto menu

**Comment by colin99d** [comment]
The forecast menu is also not working for me

**Comment by Jrryy** [comment]
Is the forecast menu error the same as this? Because it was not working for me either but the reason was different. What's the error you found there? Because it's possible I've already fixed it locally.

**Comment by hjoaquim** [comment]
@montezdesousa can we close this?

**Comment by montezdesousa** [comment]
> @montezdesousa can we close this?

did you find this error in the current reports menu qa?

**Comment by hjoaquim** [comment]
Outdated vs current version, also.
