### ISSUE TITLE
[Bug] "You are not using the latest version" message

### ISSUE THREAD

**Issue by bohruz** [OpenBB-finance/OpenBBTerminal#2903]
**Describe the bug**
The terminal is showing the message of not using the latest version even when fetching the latest version on github.

![openbb_1](https://user-images.githubusercontent.com/32798723/196460269-e07ed625-48bb-4a93-ab93-f7ee117fe835.png)
---
![openbb_2](https://user-images.githubusercontent.com/32798723/196460274-be0adba9-72bc-4370-93df-54db6217d6b1.png)

**To Reproduce**
1 - `git fetch upstream`
2 - `git merge upstream/main`
3 - `python3 terminal.py`

**Desktop:**

- OS: Ubuntu
- Python 3.8.10

**Is it a bug, or am i missing something?**

**Comment by jmaslek** [comment]
After doing a `git pull upstream main` -- usually a `poetry install` is needed to change the version number.  Could be mistaken.

**Comment by bohruz** [comment]
> After doing a `git pull upstream main` -- usually a `poetry install` is needed to change the version number. Could be mistaken.

I followed the steps suggested by you, as in the image below:
![image](https://user-images.githubusercontent.com/32798723/196477189-b59d2e6c-ed44-46d4-bbcc-83cdd044e189.png)

But it remains the same:
![image](https://user-images.githubusercontent.com/32798723/196477383-2662ec11-2ab5-4f5a-be7f-4edcde87a299.png)


**Is there any other step I should take to update the version?**

**Comment by jmaslek** [comment]
@deeleeramone

**Comment by deeleeramone** [comment]
Updating from 1.8 to 1.9 requires removing the entire virtual environment and re-building it. There is no other way around it, unfortunately.

**Comment by bohruz** [comment]
> Updating from 1.8 to 1.9 requires removing the entire virtual environment and re-building it. There is no other way around it, unfortunately. Also need to build it with `build/conda/conda-3-9-env-full.yaml`, and then `poetry install -E prediction`

Ok, thank you for your explanation!
I will try it later, I im not using conda now, I just set up a virtual environment with `venv` for run OpenBB.
