### ISSUE TITLE
[IMPROVE] Docs in white background

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2912]
Since docs (https://openbb-finance.github.io/OpenBBTerminal/) can be quite heavy, it would be great if there was the possibility to change the background color to white.

**Comment by wonhyeongseo** [comment]
Hello @DidierRLopes, how are you? The used hugo theme (geekdocs) seems to have [dark mode](https://geekdocs.de/features/dark-mode/) capability, and I expected the version in this repo (later than [v0.13.0](https://github.com/thegeeklab/hugo-geekdoc/releases/tag/v0.13.0)) would have it built-in. Surprised it didn't and want to take a shot at rebasing the `website/themes` folder to its latest version to get the functionality for free.
What kind of problems may I encounter? Is this a bad idea?

I would love to hear your feedback @jose-donato. Thank you and have a great day.

**Comment by andrewkenreich** [comment]
closing this as we have updated quite a bit recently

**Comment by wonhyeongseo** [comment]
@andrewkenreich Great to hear! Thank you for the message.
