### ISSUE TITLE
[IMPROVE] Rename commands with underscore

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2913]
In order to follow our guidelines, we shouldn't have commands with underscores.

**Comment by piiq** [comment]
the commands I've found are
```
al_swe
info_swe
all_login
ema_cross
spac_c
reddit_sent
all_volexch
```

**Comment by simmonsj330** [comment]
call_login & call_volexch already depricated. Emacross, spacc, alswe, infoswe, and redditsent have all been addressed. I believe we can close this issue. @DidierRLopes

**Comment by DidierRLopes** [comment]
Let's do it 🤝
