### ISSUE TITLE
[IMPROVE] Commands with same output, should be condensed into same command.

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#2915]
cmctop and cgtop here:
<img width="822" alt="Screenshot 2022-10-19 at 01 54 25" src="https://user-images.githubusercontent.com/25267873/196572171-59dc2ffc-6ecf-445d-a062-109b35e87703.png">

or getpoly, getfinviz and getfinnhub:
<img width="588" alt="Screenshot 2022-10-19 at 01 54 51" src="https://user-images.githubusercontent.com/25267873/196572216-0651ba2c-7c99-4c93-a3d7-de4e7e3e9a0c.png">

**Comment by Chavithra** [comment]
@DidierRLopes are you only talking about the ones listed here or are there others?
Thanks

**Comment by DidierRLopes** [comment]
> @DidierRLopes are you only talking about the ones listed here or are there others?
> Thanks

There are others that I know on top of my head, e.g. `getpoly`, `getfinviz` and `getfinnhub` on the `stocks/ca` menu. 

Overall the name of the command should represent the data it outputs and not have mention of the name of the source.
