### ISSUE TITLE
[Bug] `crypto/defi/dpi` ValueError: 6 columns passed, passed data had 7 columns

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2920]
<img width="865" alt="Screen Shot 2022-10-19 at 2 20 39 PM" src="https://user-images.githubusercontent.com/72827203/196689159-f419823b-0bce-414e-aed2-dc3c3b1e3f50.png">

This was done in the newest pip build.

**Comment by jmaslek** [comment]
IS this a dupe of #2909
