### ISSUE TITLE
[Bug] `funds/overview` ConnectionError: ERR#0015: error 403, try again later.

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#2921]
<img width="862" alt="Screen Shot 2022-10-19 at 2 22 52 PM" src="https://user-images.githubusercontent.com/72827203/196689663-06808daf-d501-4260-806b-4f27715dda47.png">

This was done in the newest build of the pip package

**Comment by jmaslek** [comment]
Hmmmm.  This is probably related to the other 403 issue that came up with the investpy change.  If we look at this request it throws the 403:

```
country = "usa"
head = {
        "User-Agent": "shfeh",
        "X-Requested-With": "XMLHttpRequest",
        "Accept": "text/html",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "keep-alive",
    }

url = (
    "https://www.investing.com/funds/"
    + country.replace(" ", "-")
    + "-funds?&issuer_filter=0"
)

req = requests.get(url, headers=head)
```

I am not sure if investiny has this funds feature.

**Comment by colin99d** [comment]
I just finished a round of error handling for this stuff
