### ISSUE TITLE
[improve] `/economy/events` needs a new source

### ISSUE THREAD

**Issue by ethene** [OpenBB-finance/OpenBBTerminal#2925]
**Describe the bug**
Using M1 pre-compiled build

2022 Oct 19, 21:54 (🦋) /economy/ $ events
Error: 'GMT +10:00'

Error: not enough values to unpack (expected 2, got 0)

**To Reproduce**
select 'economy' and then 'events' from the main menu

**Screenshots**

![Screenshot 2022-10-20 at 12 01 41](https://user-images.githubusercontent.com/57169/196838668-69b27f9c-ac01-4028-81b3-8a8bcaacb793.png)

**Desktop:**

- OS: 12.6
- Python version standard

local timezone GMT +10

**Comment by jmaslek** [comment]
This is the same as in #2919

Unfortunately investing.com changed all their api endpoints to be protected by cloudflare.

The investpy author is working on mitigating the issues but tracking it doesn't seem to promising.

We will likely need to deprecate this in lieu of another source for the time being.

**Comment by deeleeramone** [comment]
here's one: https://tradingeconomics.com/api/calendar.aspx

**Comment by deeleeramone** [comment]
https://www.nasdaq.com/market-activity/economic-calendar - here we go, @jmaslek - say hello to the new source, same as the old source!

**Comment by colin99d** [comment]
This issue is one part bug (matching #2919) and one part improvement ( we now need a new source). I am going to change this to an improvement since the but part has already been handled.
