### ISSUE TITLE
[Bug] stocks/news flags unused?

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#2938]
In stocks/news, I cannot use the NewsApi option using the source flag.  And -s does nothing.  Using yahoo does not give me yahoo results :0

```
2022 Oct 20, 16:37 (🦋) /stocks/ $ news --source NewsApi
2022 Oct 20, 16:38 (🦋) /stocks/ $ news -s yahoo.com
Fetching data. Please be patient


> 2022-10-20 20:31:00+00:00 - Apple Inc. stock falls Thursday, still outperforms market - MarketWatch
https://news.google.com/__i/rss/rd/articles/CBMicmh0dHBzOi8vd3d3Lm1hcmtldHdhdGNoLmNvbS9zdG9yeS9hcHBsZS1pbmMtc3RvY2stZmFsbHMtdGh1cnNkYXktc3RpbGwtb3V0cGVyZm9ybXMtbWFya2V0LTAxNjY2Mjk3OTE3LTAyZmQ2MjAyMDhlZtIBAA?oc=5

> 2022-10-20 19:24:46+00:00 - Battle with Bots Prompts Mass Purge of Amazon, Apple Employee Accounts on LinkedIn - Security Boulevard
https://news.google.com/__i/rss/rd/articles/CBMieGh0dHBzOi8vc2VjdXJpdHlib3VsZXZhcmQuY29tLzIwMjIvMTAvYmF0dGxlLXdpdGgtYm90cy1wcm9tcHRzLW1hc3MtcHVyZ2Utb2YtYW1hem9uLWFwcGxlLWVtcGxveWVlLWFjY291bnRzLW9uLWxpbmtlZGluL9IBfGh0dHBzOi8vc2VjdXJpdHlib3VsZXZhcmQuY29tLzIwMjIvMTAvYmF0dGxlLXdpdGgtYm90cy1wcm9tcHRzLW1hc3MtcHVyZ2Utb2YtYW1hem9uLWFwcGxlLWVtcGxveWVlLWFjY291bnRzLW9uLWxpbmtlZGluL2FtcC8?oc=5

> 2022-10-20 16:06:39+00:00 - Microsoft Takes On Apple And Google, Plans Xbox Mobile Game Store On Heels Of Activision Blizzard Deal - - Benzinga
https://news.google.com/__i/rss/rd/articles/CBMikQFodHRwczovL3d3dy5iZW56aW5nYS5jb20vbmV3cy8yMi8xMC8yOTMzOTQzOS9taWNyb3NvZnQtdGFrZXMtb24tYXBwbGUtYW5kLWdvb2dsZS1wbGFucy14Ym94LW1vYmlsZS1nYW1lLXN0b3JlLW9uLWhlZWxzLW9mLWFjdGl2aXNpb24tYmxpenphcmQtZGVh0gEtaHR0cHM6Ly93d3cuYmVuemluZ2EuY29tL2FtcC9jb250ZW50LzI5MzM5NDM5?oc=5
```

**Comment by hjoaquim** [comment]
@jmaslek this is a little tricky, but here is the explanation:
The available sources for the **news** command are: Feedparser and NewsApi
Those can be changes in the `sources` menu by using `set stocks_news Feedparser` or `set stocks_news NewsApi`.
In the context of the **news** command, the sources are used as an input for the `allinurl` operator, that it's then used in the search.

**Comment by jmaslek** [comment]
So then why do I get nothing about yahoo.com if I add it after the -s flag?

**Comment by hjoaquim** [comment]
Did some play around with it, and we're searching with something like this:

`https://news.google.com/rss/search?q=Apple%2BInc.&hl=en-US&gl=US&ceid=US:en&when:24h+allinurl:bbc.com`

where **sources** would be `bbc.com`.
seems that `allinurl` is not doing anything.

Tried some different combinations but nothing seems to work :face_exhaling:

Any suggestion?

**Comment by hjoaquim** [comment]
I guess @DidierRLopes  was the author. Any hint on this?

**Comment by DidierRLopes** [comment]
I can have a look into this 👍🏽
