### ISSUE TITLE
[IMPROVE] Get rid of stocks/dps/prom

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#2945]
It takes way too long and I have no idea what value it adds to an investment research platform.

IF anyone objects, speak now or forever hold their peace.

**Comment by deeleeramone** [comment]
It's possible that better default settings may yield better results. It is slow, but it does offer a unique type of volume analysis that I do not believe is applied in any of the screeners.

`prom -t T1 -n 10`
![Screen Shot 2022-10-20 at 3 13 42 PM](https://user-images.githubusercontent.com/85772166/197069139-dc40aedf-c4d7-468e-843f-7b15e5e288b0.png)

`prom -t T2 -n 10`
![Screen Shot 2022-10-20 at 3 15 18 PM](https://user-images.githubusercontent.com/85772166/197069360-e5a5dbfd-25a2-422f-9e5e-4be5a0d2aaf0.png)
