### ISSUE TITLE
DEBUG MODE DOESNT WORK

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#2990]
is hard to fix bugs without

**Comment by deeleeramone** [comment]
Can confirm.

**Comment by deeleeramone** [comment]
However, it seems to be working now in unexpected ways:
![Screen Shot 2022-10-22 at 7 54 24 PM](https://user-images.githubusercontent.com/85772166/197371042-ddb13fce-91ab-4aaf-a374-7e85e88e7fad.png)

**Comment by jmaslek** [comment]
Thats not even debug related.  Meant to open a separate issue thanks 4 reminding
