### ISSUE TITLE
[IMPROVE] longer history on cost to borrow function 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2995]
![Screen Shot 2022-10-22 at 8 58 25 PM](https://user-images.githubusercontent.com/85772166/197373089-5aa0da7b-a554-459f-b4f2-12a3cb20631c.png)

I would recommend the default output for a chart here to be "max history". Historical context is important here.

**Comment by deeleeramone** [comment]
Naming convention for `--source` is also broken by way of all lower-case.

**Comment by jmaslek** [comment]
stocksera api does not (currently) support this.  also looking at the website, it shows < 1 month of data on the borrowed shares tab (https://stocksera.pythonanywhere.com/ticker/borrowed_shares/?quote=AMC) so not sure if we could even just load in a large number then parse ourself like we do with yahoo

**Comment by deeleeramone** [comment]
https://iborrowdesk.com/ ?
