### ISSUE TITLE
[IMPROVE] Description of the Insider Trading menu does not reflect its true functionality.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#2996]
![Screen Shot 2022-10-22 at 9 17 50 PM](https://user-images.githubusercontent.com/85772166/197373528-2e2c1142-1bb7-4ccc-98de-4f6d041c31f2.png)

![Screen Shot 2022-10-22 at 9 19 52 PM](https://user-images.githubusercontent.com/85772166/197373565-4f36af48-cb39-46e0-97e7-0e4ad8b147d6.png)

**Comment by JerBouma** [comment]
Also note the grammar mistake in the Insider Trading menu doc, `navaigate`.

**Comment by deeleeramone** [comment]
I'm surprised the linting didn't yell at me for that one. https://github.com/OpenBB-finance/OpenBBTerminal/pull/3061#top
