### ISSUE TITLE
[IMPROVE] Title is too long

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3003]
![image](https://user-images.githubusercontent.com/25267873/197416788-3f28b94e-c5c8-45d5-8829-e28edeae5264.png)

**Comment by harisaisundhar** [comment]
I can work on this. Can you assign it to me

**Comment by DidierRLopes** [comment]
Absolutely @harisaisundhar ! Done 👍🏽

**Comment by harisaisundhar** [comment]
Hey sorry about the delay. How do you want the graph title to be ? Shorten the length of the title or make it in 2 lines ?

**Comment by harisaisundhar** [comment]
Shorten as in re-frame the title to be crisp.

**Comment by harisaisundhar** [comment]
Hey, I'm midst of a personal work. @reshuraj57 Will take this issue for me and get it sorted. Thanks for understanding!

**Comment by DidierRLopes** [comment]
Hey @harisaisundhar . No problem at all, thanks for letting us know - and for bringing @reshuraj57, very much appreciated 😊

**Comment by andrewkenreich** [comment]
Closing as PyWry fixes this
