### ISSUE TITLE
[Bug] `crypto/price` broken command

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3018]
**Describe the bug**
The price command in the crypto menu is broken with the following error:
`The symbol selected does not exist.`

<img width="339" alt="Screen Shot 2022-10-24 at 11 11 39 AM" src="https://user-images.githubusercontent.com/53658028/197561256-c2bcf9c2-12c3-4f35-8603-10331db39bf9.png">

**To Reproduce**
`crypto/price btc`

**Additional context**
Please update `openbb_terminal/miscellaneous/scripts/cryptocurrency/test_crypto.openbb` after fixing by un-commented the commands.

**Comment by andrewkenreich** [comment]
@jose-donato this one works but it is throwing a different error - can you take it
