### ISSUE TITLE
[Bug] Binance API keys

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3023]
<img width="609" alt="Screenshot 2022-10-24 at 19 34 54" src="https://user-images.githubusercontent.com/25267873/197600053-80796eaf-189d-4a6e-98e2-9d080da7013e.png">

**Comment by jmaslek** [comment]
#3001 duplicate

**Comment by jmaslek** [comment]
#3002 closes this

**Comment by jose-donato** [comment]
Can i close it @jmaslek?
