### ISSUE TITLE
[Bug] Intro will never be called because ethplorer

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3024]

**Comment by colin99d** [comment]
Why dont we just have a boolean env variable called OPENBB_FIRST_TIME, and the first time the terminal we make it false, and then the into never gets called again.

**Comment by DidierRLopes** [comment]
@colin99d that should work yea!

You can even do easier, check if the var exists. if it doesn't it's because it's my first time using the terminal. And then you create it so next time it will no longer be the first time 😋
