### ISSUE TITLE
[Bug] `cggainers` sort and futurewarnings

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3026]
**Describe the bug**
For `cggainers`...

1. FutureWarning
<img width="900" alt="Screen Shot 2022-10-24 at 12 09 44 PM" src="https://user-images.githubusercontent.com/53658028/197573735-a82641a8-44df-4ef9-bcdf-a8f7d8e67826.png">

2. `-s Symbol` and `-s Name` do not work.
<img width="901" alt="Screen Shot 2022-10-24 at 2 42 31 PM" src="https://user-images.githubusercontent.com/53658028/197601356-4d50e4e7-f7c2-437d-ae40-d71cbdedd99a.png">

3. `-s Price [$]`, `-s market_cap`, `-s market_cap_rank`, `total_volume`, do not sort properly.

Example of sorting error using Price [$]
<img width="903" alt="Screen Shot 2022-10-24 at 2 46 52 PM" src="https://user-images.githubusercontent.com/53658028/197602139-8028a2ff-cde8-400c-bc51-52ecc48601f6.png">

**To Reproduce**
`cggainers -s <sort by>`

**Comment by aadityasinha-dotcom** [comment]
Hi can I work on this issue? I think this issue is same as #3027. Can you assign me this also??
