### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3028]
economy/events seems to be giving an issue

<img width="361" alt="Screenshot 2022-10-24 at 20 35 19" src="https://user-images.githubusercontent.com/25267873/197610599-fe0e4b0d-b301-4387-b64c-d906659245d7.png">

**Comment by jmaslek** [comment]
can u provide info? this command was updated last week so itll be broken on installer

**Comment by jmaslek** [comment]
#2936
