### ISSUE TITLE
[Bug] `crypto/disc` broken commands from DappRadar

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3033]
**Describe the bug**
The commands `drnft`, `drgames`, `drapps`, `drdex` are broken with the following response:

<img width="934" alt="Screen Shot 2022-10-25 at 12 36 25 AM" src="https://user-images.githubusercontent.com/53658028/197683663-22ba12f4-2878-4268-83e9-1823e6d4d0cd.png">

**To Reproduce**
`crypto/disc/drnft`
`crypto/disc/drgames`
`crypto/disc/drapps`
`crypto/disc/drdex`

**Additional context**
Please update `openbb_terminal/miscellaneous/scripts/cryptocurrency/test_crypto_disc.openbb` after fixing by removing commented out commands.

**Comment by jmaslek** [comment]
Also note all these functions should be included in #2914
