### ISSUE TITLE
[Bug] `crypto/ov/cgstables` various bugs

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3035]
**Describe the bug**
Bugs with the `cgstables` command...

1. FutureWarning

2. Sort flag names do not match with table and `Percentage [%] of top 15` is not listed.
<img width="933" alt="Screen Shot 2022-10-25 at 12 46 32 AM" src="https://user-images.githubusercontent.com/53658028/197684933-3839c0ad-ed1e-4182-9752-d96480a8a1fb.png">

3. Sorting by market cap rank shows that the values are shown with (k) to represent thousand.
<img width="934" alt="Screen Shot 2022-10-25 at 12 52 07 AM" src="https://user-images.githubusercontent.com/53658028/197685666-20bccc90-d7ba-4ddb-a0da-ae9bfd5dece8.png">

4. Sorting by `price_change_percentage_7d_in_currency` seems to sort `price_change_percentage_24h_in_currency` and vice versa
<img width="1074" alt="Screen Shot 2022-10-25 at 12 54 20 AM" src="https://user-images.githubusercontent.com/53658028/197685934-2e311a7d-18cc-4ad8-830d-cc6559382250.png">
5. The `--descend` command does not seem to have any effect and seems to be set to default when the help flag states that it is not.
6. When adding the `--limit <N>` flag, table rows are missing.
<img width="1071" alt="Screen Shot 2022-10-25 at 1 00 40 AM" src="https://user-images.githubusercontent.com/53658028/197686594-81d5de9d-6a41-406a-a4d0-3f287a3552ed.png">

**Additional context**
Please update `openbb_terminal/miscellaneous/scripts/cryptocurrency/test_crypto_ov.openbb` with the appropriate flag names after fixing this.

**Comment by Youngdonzzz** [comment]
Please can we talk
