### ISSUE TITLE
[Bug] Links that refer to the Prediction menu should redirect to Forecasting menu in the openbb.co/docs

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3038]
Within `/website/content` find all locations that still have one of these links:

- `https://openbb-finance.github.io/OpenBBTerminal/terminal/common/pred/`
- `https://openbb-finance.github.io/OpenBBTerminal/terminal/common/prediction_techniques/`

And replace with `https://openbb-finance.github.io/OpenBBTerminal/terminal/forecast/`. Also, rename all link titles that say `Prediction Techniques` to `Forecasting menu` and double-check if you can actually still access the Forecasting menu from the corresponding menu. If not, please remove the text altogether.

**Comment by Pragya2056** [comment]
Please assign this to me!!

**Comment by JerBouma** [comment]
@Pragya2056 Thank you sir!

**Comment by Pragya2056** [comment]
@JerBouma I have created a PR. 
#3067 
Please review it.
