### ISSUE TITLE
[Bug] Stocksera module missing on SDK

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3042]
<img width="1043" alt="Screenshot 2022-10-25 at 15 15 07" src="https://user-images.githubusercontent.com/25267873/197801479-95ef28ef-29f5-4428-b192-a6d700af9c9f.png">

**Comment by montezdesousa** [comment]
This is still happening @DidierRLopes ?

**Comment by DidierRLopes** [comment]
> This is still happening @DidierRLopes ?

I doubt it. After Portugal match I will be playing with the SDK, if it happens again I will re-open this ticket. Thanks!
