### ISSUE TITLE
[Bug] Improve ca menu

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3045]
Can we get rid of everything above and basically have this command called similar?

The tsne can be included here with the source being YahooFinance - where we just use a ML algorithm to get the similar ones.

The comands above are no longer necessary because then this command can be used as

similar AAPL
similar TSLA --source Polygon

**Comment by jmaslek** [comment]
im like 99% sure this is the case now.
