### ISSUE TITLE
[Bug] `crypto/ov/exchanges` bugs

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3048]
**Describe the bug**

1. CoinPaprika source does not work
<img width="827" alt="Screen Shot 2022-10-25 at 4 36 47 PM" src="https://user-images.githubusercontent.com/53658028/197876829-66b1b06e-75ee-4309-9c7d-c7cd3a93bf52.png">

2. Sort does not work on any column
<img width="833" alt="Screen Shot 2022-10-25 at 4 39 25 PM" src="https://user-images.githubusercontent.com/53658028/197877306-b66e4cd8-fe29-4a15-84fa-36978cfcb0e9.png">

3. Descend is false, using the `--descend` flag does not make sense when it is ascending
<img width="835" alt="Screen Shot 2022-10-25 at 4 40 26 PM" src="https://user-images.githubusercontent.com/53658028/197877519-37dc8e33-f5e5-4b29-b112-f8b6331550db.png">
3. `--vs` flag does nothing.
<img width="818" alt="Screen Shot 2022-10-25 at 4 44 49 PM" src="https://user-images.githubusercontent.com/53658028/197878259-7cb3adf2-175e-462c-b0ff-a386de0f21e7.png">

**To Reproduce**
`crypto/ov/exchanges`

**Comment by andrewkenreich** [comment]
-- vs is ok here as it only works when using the other exchange
