### ISSUE TITLE
[Bug] Dashboards/Forecast - There was an error when executing cell [1].

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3054]
It says it can't find the file `~/openbb_terminal/futures/futures.csv`, but this file does indeed exist at that path. 

![Screen Shot 2022-10-25 at 3 57 07 PM](https://user-images.githubusercontent.com/85772166/197897590-703df2c9-50be-47b4-9b5f-3abe4b8220c3.png)
![Screen Shot 2022-10-25 at 4 02 56 PM](https://user-images.githubusercontent.com/85772166/197898133-70447d96-a31a-4324-a361-dfe6d557a75a.png)

**Comment by colin99d** [comment]
@deeleeramone are you still getting this issue? I am not able to reproduce it.
