### ISSUE TITLE
[Bug] `crypto/ov/cr` flags and plot bugs

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3060]
**Describe the bug**
1. `-t` flag is not in the dropdown
<img width="459" alt="Screen Shot 2022-10-25 at 9 26 14 PM" src="https://user-images.githubusercontent.com/53658028/197912881-afe2429d-99d8-435c-b584-865f901a62b0.png">

2. `--limit` flag does not limit plot, but does limit the table
<img width="767" alt="Screen Shot 2022-10-25 at 9 28 29 PM" src="https://user-images.githubusercontent.com/53658028/197913116-b4eedda6-a82b-40fc-b622-a41e76694b6e.png">

**To Reproduce**
`crypto/ov/cr`

**Comment by andrewkenreich** [comment]
second part is not really a bug - its showing per the 4 there - so its not supposed to limit
