### ISSUE TITLE
[Bug]`crypto/disc/search` command broken

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3062]
**Describe the bug**
1. Command is broken as seen below.
<img width="445" alt="Screen Shot 2022-10-25 at 10 02 10 PM" src="https://user-images.githubusercontent.com/53658028/197917081-86e24417-93b6-4cbb-9947-005de25c6daf.png">

**To Reproduce**
`crypto/disc/search ethereum` 

**Additional context**
This is tested in an integration test, please make sure the integration test is passing successfully after fixing.

**Comment by andrewkenreich** [comment]
![image](https://user-images.githubusercontent.com/23067478/199138257-a7b5548d-d305-4800-b6fb-cb24cce30c6c.png)

This one seems to be working

**Comment by andrewkenreich** [comment]
Going to close this - maybe @jose-donato you can close it if you try and it works too

**Comment by jmaslek** [comment]
also not broken for me
