### ISSUE TITLE
[Bug] Sub-Menu is Broken: `crypto/ov`

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3063]
**Describe the bug**
The sub-menu is not usable.
<img width="418" alt="Screen Shot 2022-10-25 at 10 04 04 PM" src="https://user-images.githubusercontent.com/53658028/197917352-8daca80e-28f7-430c-8a13-9097549c3224.png">

**To Reproduce**
`crypto/ov`

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
That's a weird error. Currently can't replicate, but for some reason the command path is now printing where the description should be.

![Screen Shot 2022-10-25 at 8 56 27 PM](https://user-images.githubusercontent.com/85772166/197931089-bd48d69c-08e5-4b0e-bace-85b208483c5d.png)
