### ISSUE TITLE
[IMPROVE] In Documentation Directory Tree, where acronyms present, all caps should be used. Macd --> MACD

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3064]
Acronyms should be in all-caps. Ad --> AD, Adx --> ADX, etc. 

![Screen Shot 2022-10-25 at 8 50 56 PM](https://user-images.githubusercontent.com/85772166/197930597-4c004a34-b28c-495b-b680-b3e8d1a31d8d.png)

**Comment by wonhyeongseo** [comment]
The easy but slow path would be to rename the folders in `website/content/SDK`. 

Another over engineered method would be to use [abbreviation detector on huggingface](huggingface.co/surrey-nlp/roberta-base-finetuned-abbr), inserting random words to make a sentence like '~ is here.' Get all the AC entity groups, upper them automatically.

**Comment by deeleeramone** [comment]
Do you think that the acronyms specific the finance, technical analysis, crypto, etc. would be a challenge for huggingface?

**Comment by jmaslek** [comment]
looks like this got relifted and everything is now lower cased
