### ISSUE TITLE
[Bug] Some changes on portfolio menu

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#3072]
**What's the feature that should be improved?**
- Portfolio menu references to orderbook should be changed to transactions or any synonym. Orderbook usually refers to the bid/offer table with respective sizes for each order. There are some references on the menu help and progress bars. 
- remove line between `show` and `bench` commands and pull `Benchmark:` up together with other custom options like `Loaded orderbook:` and `Risk free rate:`
- Warning `Please first define the portfolio (via 'load') and the benchmark (via 'bench').` should only ask for `load` since it attributes a benchmark by default.
![Screenshot 2022-10-26 at 11 47 05](https://user-images.githubusercontent.com/79287829/198007136-c4cd6cfd-8295-4390-a341-9ba110f09f60.png)

- change `load` progress to something closer to `tqdm` for consistency with remaining terminal 
- `var` and `es` table values should be changed to % 2 decimals format
![Screenshot 2022-10-26 at 11 54 24](https://user-images.githubusercontent.com/79287829/198008459-0cf6eb35-f2b1-4e85-9443-114362bfb6a5.png)
- `var` and `es` argument `--percentile` too many 0s in prompt
- Pull `Metrics` commands to before `Graphs` because this is what gives you a snapshot of your portfolio
- `summary` values are missing % symbol
- `alloc assets -t` tables have no spacing between them
- Message: `Loading country/region data:` shows up out of nowhere with `alloc -a countries` command
- Message: `Loading sector data:` shows up out of nowhere with `alloc sectors`
- default `sum` to True in `holdv` and `holdp`. Remove total value from legend. See https://github.com/OpenBB-finance/OpenBBTerminal/issues/3121
- `mret --raw` outputs 2 tables, one for benchmark, other for portfolio. Should be identified which is which in the title.

**Comment by JerBouma** [comment]
Please note that we have items on Jira for a long time now that need to unify `po` and `portfolio` transactions Excel sheet. I agree with the rename to transactions (since orderbook can refer to outstanding orders too). See: https://openbb.atlassian.net/browse/GSTDEV-1502

<img width="565" alt="image" src="https://user-images.githubusercontent.com/46355364/198008548-ea87e0b5-1750-4265-a49a-63ebbdc29b2e.png">
