### ISSUE TITLE
[Bug] /forex/ta/ $ bbands -l 1 -s 0.25 -m ema

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#3075]
Does not allow float values despite auto-completion:
![image](https://user-images.githubusercontent.com/48914296/198001395-a2b5270d-6803-48bb-a46c-5f8989de4d3a.png)

**Comment by jmaslek** [comment]
I would drop the auto complete here (and anywhere that has any possible numeric input)
