### ISSUE TITLE
[Bug] /forex/qa/ $ line --draw

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#3076]
Terminal dies after using this command.

![image](https://user-images.githubusercontent.com/48914296/198004135-e1a34aeb-afe6-4757-8543-1a8b580fe120.png)

**Comment by andrewkenreich** [comment]
The --draw function is blocking on the main thread - it also works if you install like pyqt5 and change the backend rendering to that - so definately something there - I would suggest just removing this function all together as its blocking anyways.

**Comment by jmaslek** [comment]
Permission granted to ditch

**Comment by andrewkenreich** [comment]
![image](https://user-images.githubusercontent.com/23067478/199869267-84d4df09-e69e-4755-bc48-962b06ff45d4.png)

@jmaslek this lives in 3 other spots - i'll hold off til i hear otherwise
