### ISSUE TITLE
[Bug] `/economy/ $ fred` - wrong example on the website

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#3086]
Website page: `https://openbb-finance.github.io/OpenBBTerminal/terminal/economy/index`

![image](https://user-images.githubusercontent.com/48914296/198064545-35e8bed2-1c87-4707-a8eb-2eba93a329dc.png)

Should be instead:

`fred T5YIEM,T10YIEM,T20YIEM,T30YIEM`

**Comment by hjoaquim** [comment]
Hello @Ph0tonic, I see you've fixed this :smile: , thanks for that!
Wondering if you need any help opening the PR? Feel free to tag me/ add me as reviwer!

**Comment by hjoaquim** [comment]
If you're wondering how to test this, this should do the trick:
(go to your repo base folder and then:)
```
cd website
hugo server -D
```

**Comment by Ph0tonic** [comment]
I just forgot to open it, here it is. 👍
