### ISSUE TITLE
[Bug] `crypto/defi/dpi` command broken

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3096]
**Describe the bug**
1. Calling `dpi` shows this response:
<img width="380" alt="Screen Shot 2022-10-26 at 3 31 30 PM" src="https://user-images.githubusercontent.com/53658028/198119235-f6534a6c-dfcf-402c-b39a-9f97ed960540.png">

**To Reproduce**
`crypto/defi/dpi`

**Additional context**
Please update `openbb_terminal/miscellaneous/scripts/cryptocurrency/test_crypto_defi.openbb` after fixing and make sure to test all optional flags.

**Comment by andrewkenreich** [comment]
Going to remove this command - https://www.defipulse.com/ does not exist anymore in the way this one was added
