### ISSUE TITLE
[FR] Add ability to compare percentage gain of multiple stocks over N period of time

### ISSUE THREAD

**Issue by not-aristotle** [OpenBB-finance/OpenBBTerminal#3115]
**What's the problem of not having this feature?**
For example, it would be very useful for a user to see how their favorite stock compares to other similar stocks or benchmarks.

**Describe the solution you would like**
I would like to have this option available in Comparison Analysis Menu. Alternatively, it could be under any command as long as it is intuitive and properly documented.

**Additional information**
Similar feature is available in Yahoo Finance:

<img width="1394" alt="Screenshot 2022-10-26 at 10 28 08 PM" src="https://user-images.githubusercontent.com/104706525/198199470-06eb7075-2014-4529-94e3-2d36c9a7cb71.png">

I would say either graph or even tabular format would be fine. I actually tend to think that tabular format is more concise and preferable since it probably doesn't matter what fluctuations were there along the way...
I imagine tabular format to be something like:

`Results over 5Y` - ideally this would be a top row with merged cells - could not accomplish it with markdown 😔 
| Company A      | Company B |
| ----------- | ----------- |
| 123%      | 78%       |

**Comment by Aditya04-code** [comment]
I have a suggestion 
can we use plotly ! for that as it provides interactive graphs that help in better understanding of graphs

**Comment by deeleeramone** [comment]
Closing, this is part of the `openbb-charting` library.

```
SPDRS = [
    "SPY",
    "XLE",
    "XLB",
    "XLI",
    "XHB",
    "XLP",
    "XLY",
    "XRT",
    "XLF",
    "XLV",
    "XLK",
    "XLC",
    "XLU",
    "XLRE",
]
start_date = (datetime.now() - timedelta(weeks=52*5)).date()
spdrs = obb.equity.price.historical(SPDRS, start_date=start_date, provider="yfinance", chart=True)

spdrs.show()
```
![SPDRs Cumulative Returns - 5 years](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/8884f4ed-b09c-4161-9dc6-87ad66d9fc8b)

YTD:

```
new_data = spdrs.to_df().loc[datetime(2023,12,29).date():]
spdrs.charting.to_chart(data=new_data, title="YTD")
```

![SPDRs Cumulative Returns - YTD](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/22ed2588-1098-4712-aec1-54dd22c324ef)
