### ISSUE TITLE
[IMPROVE] Redesign `portfolio/holdv` and `portfolio/holdp`

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3121]
**What's the feature that should be improved?**
These two charts are absolute not insightful. Especially once you have a portfolio of more than a 100 tickers.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/198258328-9b55c8bf-f7b0-4e49-a6d2-d640a6aca17b.png">

**Describe how you would like the feature improved**
This needs to be redesigned to be based off `Sectors`, `Industries` and `assets` by using stacked charts. Assets would be the current method but done in a better way. See the attached Excel for a randomized example and the following charts (note that due to how the random numbers are defined in the spreadsheet, the capital doesn't really grow).

<img width="625" alt="image" src="https://user-images.githubusercontent.com/46355364/198261953-560962fe-598f-4889-a529-f1dc89d8da23.png">

<img width="666" alt="image" src="https://user-images.githubusercontent.com/46355364/198261967-820a0a77-71fc-448e-b94e-3e95ab713cab.png">

[Example HOLDP and HOLDV.xlsx](https://github.com/OpenBB-finance/OpenBBTerminal/files/9878458/Example.HOLDP.and.HOLDV.xlsx)

**Possibly describe the ideal way to improve this**
I am looking for stacked charts for both functionalities. Here, I want it to select by default the `sectors`. Whenever the amount of sectors, industries or assets are **greater than 10**. Pick the top 9 based on allocation value or percentage and put the remainder in "Others". Also include a flag that can disable this functionality. We do this to prevent overflooding the chart leading to meaningless results.

**Comment by montezdesousa** [comment]
@JerBouma did you try wit `--sum` ? Looks like this

![Screenshot 2022-10-27 at 18 44 52](https://user-images.githubusercontent.com/79287829/198361482-a4d9467d-5c57-41d5-9f7c-98a6d4bfc12c.png)

**Comment by JerBouma** [comment]
Should be default yes but needs support for sector, industry and assets. Legend most likely outside the graph.

**Comment by JerBouma** [comment]
Also note total value shouldn't be in `holdv` stacked chart.

**Comment by montezdesousa** [comment]
> Also note total value shouldn't be in `holdv` stacked chart.

got it
