### ISSUE TITLE
[Bug] equity report uses an SDK function that no longer exists

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#3122]
![image](https://user-images.githubusercontent.com/48914296/198268433-c2fe9f26-88a3-4af5-9d05-1f12142b803a.png)

Report: `openbb_terminal/reports/templates/equity.ipynb`

**Comment by zafar-hussain** [comment]
Hi @jmaslek,

Please check and advise on my PR,

cheers

**Comment by hjoaquim** [comment]
Hello @zafar-hussain , thanks for this contribution! 

I think you may have done the PR in the wrong order. 
Right now you have:

`zafar-hussain wants to merge 3 commits into zafar-hussain:main from OpenBB-finance:main`

But, it should be 

`zafar-hussain wants to merge 3 commits into OpenBB-finance:main from zafar-hussain:main`

Meaning that you're trying to merge OpenBB-finance:main into your fork instead of your fork into OpenBB-finance:main!

**Comment by zafar-hussain** [comment]
Hi @hjoaquim,

I am terribly sorry about this, let me sort it out,

cheers
