### ISSUE TITLE
[Bug] /alternative/covid

### ISSUE THREAD

**Issue by Chavithra** [OpenBB-finance/OpenBBTerminal#3136]
**Describe the bug**

### /alternative/covid/country

    1. Country command not documented
    2. Autocompletion doesn't work on the countries, ei :
        country F
        country -c F

### /alternative/covid/cases

    it's confusing because `--limit` only apply to the table
    and the table is only displayed when we use raw
    raw shouldn't display chart?

### /alternative/covid/deaths

    same than cases

### /alternative/covid/ov

    same than cases

### /alternative/covid/

    1. bug with : `slopes -d 1`

    ** On entry to DLASCLS parameter number  4 had an illegal value
    Error: SVD did not converge in Linear Least Squares

    Error: 'list' object has no attribute 'columns'

    2. autocompletion not working

    3. export not working

**Comment by colin99d** [comment]
it's confusing because `--limit` only apply to the table
and the table is only displayed when we use raw
raw shouldn't display chart?

How do you want this resolved?

**Comment by colin99d** [comment]
![Uploading Screenshot 2022-11-01 at 2.02.04 PM.png…]()
I am not getting the output of the commands to be the same.

**Comment by jmaslek** [comment]
ruh roh.  Another country conversion
```
2022 Nov 03, 12:27 (🦋) /alternative/covid/ $ country -c United Kingdom

The following args couldn't be interpreted: ['Kingdom']
United not a valid selection.
```

**Comment by jmaslek** [comment]
Also do we want the `country` command on hugo? (`about country` gives a 404).  I dont see the need for it, but am open to keeping it
