### ISSUE TITLE
[Bug] /alternative/oss

### ISSUE THREAD

**Issue by Chavithra** [OpenBB-finance/OpenBBTerminal#3137]
**Describe the bug**

### /alternative/oss/rossidx

    Update doc `-t {stars,forks}` => `-ct {stars,forks}`

### /alternative/oss/rs

    1. This command doesn't work : `rs --help`
    2. Type `rs foo` -> `rs` ; now autocompletion doesn't work
    3. incorrect export written in the web doc
        `{csv,json,xlsx,png,jpg,pdf,svg}` -> `{csv,json,xlsx}`
        https://openbb-finance.github.io/OpenBBTerminal/terminal/alternative/oss/rs/

### /alternative/oss/sh

    same than rs

### /alternative/oss/tr

    1. Need to remove the `US COVID cases` chart from the documentation
        https://openbb-finance.github.io/OpenBBTerminal/terminal/alternative/oss/tr/
    2. This command doesn't work : `tr --raw`

**Comment by colin99d** [comment]
```
Update doc `-t {stars,forks}` => `-ct {stars,forks}`
```
So you want the command argument changed from -t to -ct?

**Comment by colin99d** [comment]
```
1. This command doesn't work : `rs --help`
```
I thought only `-h` was supposed to work?
