### ISSUE TITLE
[Bug] SDK - `openbb.economy.spectrum()` Docstring says: Available groups can be accessed through `get_groups()`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3140]
`get_groups()` is not accessible through importing `from openbb_terminal.sdk import openbb`

![Screen Shot 2022-10-27 at 3 38 18 PM](https://user-images.githubusercontent.com/85772166/198411118-9863e159-8896-4ea9-a2b1-69f93dbfd9fb.png)

**Comment by jmaslek** [comment]
Im addressing this in #3420, but I think we shouldn't have these functions as it looks like the system viewer does not delete the files?
