### ISSUE TITLE
[Bug] economy/rtps chart is hijacked by other charts

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBBTerminal#3146]
**Describe the bug**
The `rtps` chart in the economy menu is hijacked by other charts meaning other charts appear in the rtps figure

**To Reproduce**
The following command sequence should reproduce the bug

```
economy
rtps
treasury
rtps
ycrv
rtps
```

**Screenshots**
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/11668535/198574454-8d35bf0d-f02d-487a-8c45-282c55eb9be9.png">

**Desktop (please complete the following information):**

- OS: macOS Ventura
- Python 3.9 arm64

**Comment by jmaslek** [comment]
whoever is fixing this one:

the rtps command does not make sure of the external axis arg and just does this
```
ax = df_rtp.plot(kind="barh", color=colors)
```
