### ISSUE TITLE
[Bug] Failing to commit to forked branch due to CLRF pre-commit hook errors under pylint

### ISSUE THREAD

**Issue by louiseamy4** [OpenBB-finance/OpenBBTerminal#3155]
**Describe the bug**
Pre-commit hook for pylint showing error for files when trying to commit: "C0328 Unexpected line ending format. There is CLRF while it should be LF". This is displaying on files already existing on the platform, and not files that were touched on local copy of repo. This error is preventing a commit to a forked branch for eventual pull request.

**To Reproduce**
After enabling pre-commit install command per https://github.com/OpenBB-finance/OpenBBTerminal#3-contributing step 3, attempting to commit changes fails per step 4 and is aborted by Git.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/74476622/198757286-14d105d8-d650-4e8a-8322-3f829306cc8a.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Python version 3.9.13

**Comment by jmaslek** [comment]
As a non-windows user, I am not sure exactly what is up with this.  But this stackoverflow post has some good info it seems

https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

Seems like the solution is to set your git config using `git config core.autocrlf false` (from the repository root)

**Comment by louiseamy4** [comment]
Correct, it is not an issue on Mac but on Windows has the issue with the core.autocrlf set to false not resolving. Manually changing the files to LF line endings works but not possible due to large number of files.

**Comment by colin99d** [comment]
@tehcoderer you mind helping out here?

**Comment by andrewkenreich** [comment]
@louiseamy4 so I just ran into this issue as well - 

![image](https://user-images.githubusercontent.com/23067478/199817031-e32999c2-5fae-4715-9c35-f1efb5e89934.png)

If you reinstall Git and make sure you pick the middle option here highlighted in green and then create a folder - pull again - and install everything you will be good to go.

**Comment by louiseamy4** [comment]
Excellent thank you all working
