### ISSUE TITLE
[FR] SDK - `openbb.common.ta.ema` - `chart = True` is a missing argument in the SDK function.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3165]
![Screenshot 2022-10-29 at 11 43 46 AM](https://user-images.githubusercontent.com/85772166/198847836-5b16cbe1-45ff-495f-8775-8701bf3a4f84.png)

**Comment by colin99d** [comment]
This endpoint currently does not have a view. I am switching this to a feature request.
