### ISSUE TITLE
[Improve] SDK - `openbb.common.ta.ema` - length is not a list like the Terminal function is. Accepts only one value.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3166]
`ema = openbb.common.ta.ema(data = data['Close'], length = ['20,50,150'])`

```
TypeError: '>' not supported between instances of 'list' and 'int'
```

In the Terminal: `/crypto/load eth/ta/ema 20,50,150`

![Screenshot 2022-10-29 at 11 49 54 AM](https://user-images.githubusercontent.com/85772166/198848030-b23570ff-7e4e-4d6c-8c6e-5411b5724ffb.png)

**Comment by JerBouma** [comment]
Won't `length = [20, 50, 100]` fix this?

**Comment by deeleeramone** [comment]
No, because length is not defined as a list.

**Comment by JerBouma** [comment]
> No, because length is not defined as a list. 
> ![Screenshot 2022-10-29 at 12 15 53 PM](https://user-images.githubusercontent.com/85772166/198848979-f0a18789-d4ee-4f1b-a91e-b8c9c1601c1e.png)
> 

Got it! Definitely a bug then.

**Comment by colin99d** [comment]
It looks like there are two different functions. This one only creates one EMA. I am going to move this to a feature request.

**Comment by tehcoderer** [comment]
You'd want to use 

```python
df = openbb.stocks.load("TSLA")
openbb.common.ta.ma(df["Close"], window=[50, 200], ma_type="SMA")
```

![image](https://user-images.githubusercontent.com/61340027/200031337-ab1ea9b0-69b8-4b61-889d-5624d1ec9f80.png)

**Comment by deeleeramone** [comment]
You're using a different function here though: `openbb.common.ta.ema` != `openbb.common.ta.ma`

![Screenshot 2022-11-04 at 10 07 07 AM](https://user-images.githubusercontent.com/85772166/200034607-8309c138-3772-418d-89c1-2922b203f031.png)
