### ISSUE TITLE
[Bug] SDK `openbb.stocks.screener.screener_data` - `loaded_preset` not a valid argument as shown in the docstrings

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3172]
`openbb.stocks.screener.screener_data(limit = -1, loaded_preset = 'unusual_volume')`
![Screenshot 2022-10-29 at 1 10 45 PM](https://user-images.githubusercontent.com/85772166/198850764-092b3449-fc55-465c-9e89-715a6a15d888.png)

`openbb.stocks.screener.screener_data(limit = -1, preset_loaded = 'unusual_volume')`
![Screenshot 2022-10-29 at 1 09 10 PM](https://user-images.githubusercontent.com/85772166/198850715-c45713df-5d67-43fe-9316-483f297edf5a.png)

**Comment by colin99d** [comment]
This will be fixed in Juan's pr.
