### ISSUE TITLE
[Bug] SDK - `openbb.stocks.fa.poly_financials` - Error: get_financials() got an unexpected keyword argument 'limit'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3173]
`openbb.stocks.fa.poly_financials(symbol = 'WMT', statement = 'balance', limit = 40, quarterly = True)`

![Screenshot 2022-10-29 at 1 19 31 PM](https://user-images.githubusercontent.com/85772166/198851014-4361e98f-5d6c-4ace-8d81-9a04bf168b4f.png)

Taking away the `limit` argument:

![Screenshot 2022-10-29 at 1 21 39 PM](https://user-images.githubusercontent.com/85772166/198851046-75ebae42-7423-4f5d-b59f-dace3f0829b2.png)

**Comment by colin99d** [comment]
@tehcoderer's upcoming PR should fix this.

**Comment by colin99d** [comment]
This one is also tricky because it makes since to have the `limit` argument in the view, but not the model.

**Comment by jmaslek** [comment]
this is no longer relevant as there is no poly_financials function
