### ISSUE TITLE
[Bug] `crypto/dd/balance` command broken

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3185]
**Describe the bug**
1. Broken command
<img width="556" alt="Screen Shot 2022-10-30 at 2 00 06 PM" src="https://user-images.githubusercontent.com/53658028/198893843-0502f004-6481-48c7-b1bf-6dae25d458f4.png">

**To Reproduce**
`crypto/dd/balance` 

**Additional context**
Please update `openbb_terminal/miscellaneous/scripts/cryptocurrency/test_crypto_dd.openbb` after fixing

**Comment by hjoaquim** [comment]
No issues found:

```bash
2023 Feb 01, 11:29 (🦋) /crypto/dd/ $ balance


You currently have 0.xxxx coins and the breakdown is:
         Account Holdings for Assets         
┏━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━┓
┃        ┃ Amount ┃ Amount [USDT] ┃ Percent ┃
┡━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━┩
│ Free   │ 0.xx   │ xxx.xx        │ 100.00  │
├────────┼────────┼───────────────┼─────────┤
│ Locked │ 0.00   │ 0.00          │ 0.00    │
└────────┴────────┴───────────────┴─────────┘

2023 Feb 01, 11:29 (🦋) /crypto/dd/ $
```
