### ISSUE TITLE
[Bug] `crypto/dd/funot` broken command

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3187]
**Describe the bug**
1. command is broken, `-h` command flag doesn't work.
<img width="863" alt="Screen Shot 2022-10-30 at 2 13 53 PM" src="https://user-images.githubusercontent.com/53658028/198894529-a45611c3-d0ae-407c-9c53-5cb24db0fe6f.png">

**To Reproduce**
`crypto/dd/funot` 

**Additional context**
Please update `openbb_terminal/miscellaneous/scripts/cryptocurrency/test_crypto_dd.openbb` after fixing.

**Comment by andrewkenreich** [comment]
https://github.com/OpenBB-finance/OpenBBTerminal/pull/3220 fixes #3220
