### ISSUE TITLE
[Bug] Improvement on sto,rsi,...

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3188]
To run `sto` (and others) then we assume the dataset has a fixed column name. It's fine to have a default name selected, BUT we should have a way to allow the user to select name of the columns to be used in that dataframe.
<img width="349" alt="Screenshot 2022-10-30 at 18 20 08" src="https://user-images.githubusercontent.com/25267873/198894807-68380222-9b0b-46e0-a625-b4ae9f6326d5.png">

Small warning also
<img width="1659" alt="Screenshot 2022-10-30 at 18 19 52" src="https://user-images.githubusercontent.com/25267873/198894801-44f760cb-213f-4990-ba4f-447d90c69e7d.png">

**Comment by martinb-bb** [comment]
@DidierRLopes I can fix the warning.

To the first point, RSI and STO are financial equations that require specific variables like open/close/high/low etc. How do you recommend we modify that?

**Comment by DidierRLopes** [comment]
> @DidierRLopes I can fix the warning.
> 
> To the first point, RSI and STO are financial equations that require specific variables like open/close/high/low etc. How do you recommend we modify that?

To keep it very easy & fast for now I recommend having additional arguments with `close_name`, `high_name`, `low_name` and do something like
```
func(
    ...,
    close_name="Close",
    high_name="High",
    low_name="Low",
```

Does that make sense?

**Comment by martinb-bb** [comment]
Got it!

**Comment by jmaslek** [comment]
#3224
