### ISSUE TITLE
[Bug] stocks/fa/dcf -> Error: Could generate a dataframe for the ticker symbol

### ISSUE THREAD

**Issue by kajdo** [OpenBB-finance/OpenBBTerminal#3198]
**Describe the bug**
Trying to generate the dcf from /stocks/fa gives me an error message instead of some data 

```
Error: Could generate a dataframe for the ticker symbol

Error: Could generate a dataframe for the ticker symbol

Error: Could generate a dataframe for the ticker symbol

Error: 'list' object has no attribute 'shape'

Error: not enough values to unpack (expected 3, got 0)

```

**To Reproduce**
```
stocks
load JNJ
fa
dcf
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8735942/198904890-34cb42bd-e545-4c64-bc56-cae0f96bb540.png)

**Desktop (please complete the following information):**

- OS: Linux
- Python version Python 3.9.13

**Additional context**
installed via conda / git clone ... works out of the box and I included financialmodelingprep & finhub key
I would have checked logs - but I can't find any
Unfortunately the error msg itself doesn't give me enough hints to debug or do any further analysis

btw. I think the errormsg should be "could *not* generate a dataframe for the ticker symbol"

**Comment by colin99d** [comment]
Thanks for reporting this!

**Comment by kajdo** [comment]
works perfectly @colin99d thx for the quick action!!
