### ISSUE TITLE
[Bug] `crypto/qa/acf` future warning

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3201]
**Describe the bug**
<img width="867" alt="Screen Shot 2022-10-30 at 9 37 13 PM" src="https://user-images.githubusercontent.com/53658028/198914100-36d541c1-cc8f-4abb-8df7-3688034a2209.png">

**To Reproduce**
`crypto/qa/acf`

**Comment by jose-donato** [comment]
Fixed on #3081
