### ISSUE TITLE
[Bug] `/stocks/ $ news` both sources display errors

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#3236]
- For ` /stocks/ $ news --source Feedparser`

```python
2022 Nov 01, 07:02 (🦋) /stocks/ $ news --source Feedparser

Fetching data. Please be patient

Error: 'NoneType' object has no attribute 'replace'
```

- For ` /stocks/ $ news --source NewsApi`

```python
2022 Nov 01, 07:03 (🦋) /stocks/ $ news --source NewsApi

440 news articles for  Tesla,+Inc. were found since 2022-10-25

                                   Factbox-Tesla’s Autopilot faces unprecedented scrutiny                                    
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Content                                                                                                                   ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 2022-11-01 10:22:44                                                                                                       │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ By Hyunjoo Jin (Reuters) -   Elon Musk has championed Tesla Inc&#039;s driver assistance Autopilot and "Full              │
│ Self-Driving" software as innovations that will both improve road safety and position the electric vehicle maker as a     │
│ technology leader.                                                                                                        │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ https://www.fxempire.com/news/article/factbox-teslas-autopilot-faces-unprecedented-scrutiny-1180983                       │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

...

Error: can only join an iterable
```

**Comment by victortangggg** [comment]
source should be either bloomberg or reuters looking at the help manual.

![image](https://user-images.githubusercontent.com/23350634/199249085-3785e9e8-54a9-4a8a-b04a-40fc91a4b9e8.png)


![image](https://user-images.githubusercontent.com/23350634/199249332-99a4e061-ccdf-48d5-99d1-1a2edd2e6483.png)

**Comment by hjoaquim** [comment]
Hey @victortangggg 

On this context, `source` and `sources` is different. i.e., `source` (singular) is API where we get the data from and `sources` (plural) a filter to apply on the data we'll retrieve from the API.

Meaning that we can have data from `NewsApi` and filter it by choosing we just want to see stuff from `bloomber` or `reuters`.

**Comment by victortangggg** [comment]
ah yes my bad. i see that the error occurs due to having an empty sources variable in the get_news function. Just curious is anyone working that? I am a developer i probably could help.

**Comment by hjoaquim** [comment]
I would probably say the 1st option, as the `sources` is not a required argument.

@victortangggg as no one is assigned to this yet, I'll assign you.
Feel free to tag me if you need any help or want to change some ideas!
Thanks :smile: !

**Comment by victortangggg** [comment]
@hjoaquim pardon my noobness with the messy PRs. The final one should be correct. Please let me know if i'm doing this correctly. thanks!
