### ISSUE TITLE
[Bug] Stocks/SIA - `vis --show-all`: Error: list index out of range

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3249]
```
2022 Nov 01, 10:39 (🦋) /stocks/sia/ $ select MS

2022 Nov 01, 10:39 (🦋) /stocks/sia/ $ vis --show-all

The following args couldn't be interpreted: ['--show-all']
If it takes too long, you can use 'Ctrl + C' to cancel.

Error: list index out of range

Error: not enough values to unpack (expected 2, got 0)
```

![Screenshot 2022-11-01 at 10 40 28 AM](https://user-images.githubusercontent.com/85772166/199301329-ab74f421-7997-4268-9d83-9ed53e40a587.png)

**Comment by jmaslek** [comment]
There should not be a --show-all option (and I dont see one on vis -h).  `vis` with no arguments shows all

But this should also be handled properly.

**Comment by gsegatti** [comment]
I've tracked down the error messages to `display_plots_financials()`. Could try to take a further look into it.

**Comment by deeleeramone** [comment]
> There should not be a --show-all option (and I dont see one on vis -h). `vis` with no arguments shows all
> 
> But this should also be handled properly.

Appears to be an autocomplete artifact.

![Screenshot 2022-11-02 at 4 26 38 PM](https://user-images.githubusercontent.com/85772166/199621127-e22d4c97-022c-4c8e-acc9-5fab20aca6ea.png)
