### ISSUE TITLE
[Bug] /portfolio/metric rsquare - when using example file it crashes terminal

### ISSUE THREAD

**Issue by andrewkenreich** [OpenBB-finance/OpenBBTerminal#3252]
**Describe the bug**
![image](https://user-images.githubusercontent.com/23067478/199330440-7b856ecc-ddcd-4bb3-be33-7e8802647dda.png)

**To Reproduce**
load example portfolio file and run metric rsquare

/portfolio/metric rsquare - when using example file it crashes terminal

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by colin99d** [comment]
<img width="419" alt="Screenshot 2022-11-02 at 12 32 19 PM" src="https://user-images.githubusercontent.com/72827203/199479341-d79964dc-88d0-46e7-8ec3-75cb2a417402.png">
I cannot recreate this. Is `example.csv` the file you used?

**Comment by andrewkenreich** [comment]
No I used the one from the about in the docs - had a longer name

**Comment by colin99d** [comment]
<img width="474" alt="Screenshot 2022-11-02 at 12 39 15 PM" src="https://user-images.githubusercontent.com/72827203/199480663-172475ab-6a68-488f-9201-ae9eaf7bdb83.png">
That works for me to.

**Comment by andrewkenreich** [comment]
hmm ok, i can't reproduce today either...weird.
