### ISSUE TITLE
[IMPROVE] Consistent ascend/descend throughout the terminal

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#3254]
Looking at a lot of these PRs/issues, we have so many of these --ascend vs --descend and then ascending = not ascend. 

We should pick a default sorting order and a standard flag that we use each time and update the contributing docs to reflect that

**Comment by colin99d** [comment]
Personally I am much more in favor of having A standard, than what that specific standard might be. I think `reverse` does make the most sense, because then if there ever are times that we do need to do from low to high, the user still can use reverse.

**Comment by jmaslek** [comment]
think this was done.  woooooooot
