### ISSUE TITLE
[Improvement] Autocompletion of futures expirations

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3264]
None of the choices are a valid expiration date. 

<img width="783" alt="Screenshot 2022-11-02 at 12 39 53 AM" src="https://user-images.githubusercontent.com/85772166/199428407-5596cbfc-35f2-4690-b341-11a5d57797a9.png">

`--expiry` does not trigger any autocomplete.

<img width="460" alt="Screenshot 2022-11-02 at 12 41 48 AM" src="https://user-images.githubusercontent.com/85772166/199428775-ccd0a832-b2a5-4aa0-98d7-8acf6ad78ef2.png">

There is also no way to make multiple contract expiry dates for the same asset appear on the same chart. With the Futures Dashboard, this was the default output.

<img width="330" alt="Screenshot 2022-11-02 at 12 53 23 AM" src="https://user-images.githubusercontent.com/85772166/199431116-d1fbca5c-172d-4d2f-b4d9-cad6d998445d.png">

<img width="579" alt="Screenshot 2022-11-02 at 12 54 55 AM" src="https://user-images.githubusercontent.com/85772166/199431442-ac018a9d-cc29-4896-80c2-21348d0ae047.png">

**Comment by andrewkenreich** [comment]
Fixed a few issues here - but we can't load the expiration with a larger refactor - we should reclassify most of this as a [feature] and then we can do more after the freeze

**Comment by jmaslek** [comment]
In order to refactor this to auto-complete the expirations, we would need to change the design similar to how we do the options menu, where we load a symbol then find the expirations.

#3264  enhances teh auto complete, but adding the expirations will change this to an enhancement not a bug.
