### ISSUE TITLE
[Bug] Stocks/SIA - `metric --show-all` - Error: None 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3277]
`/stocks/sia/select JPM/clear mktcap/period Quarterly/metric --show-all`

![Screenshot 2022-11-02 at 3 42 32 PM](https://user-images.githubusercontent.com/85772166/199616275-3730e9f9-9a00-43ba-91b7-d953d7cefbf4.png)

**Comment by deeleeramone** [comment]
related to #3249 
![image](https://user-images.githubusercontent.com/85772166/199621440-9808ea5b-2d87-4122-a52d-366729dd81b6.png)

**Comment by jmaslek** [comment]
Should be fixed with the PR #3275
