### ISSUE TITLE
[Imporve] Standardize Stocks/SIA Output (or alert users to EXACTLY what they are being shown)

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3278]
I can't use this menu, because I can't trust the numbers.

`/stocks/sia/select CS/clear country/period Quarterly/metric --metric ev`
![Screenshot 2022-11-02 at 3 55 51 PM](https://user-images.githubusercontent.com/85772166/199617794-42169546-834c-4765-8b44-2bbd2d395841.png)

![Screenshot 2022-11-02 at 4 03 19 PM](https://user-images.githubusercontent.com/85772166/199619016-08a1d752-9a49-4156-ba0d-a26190bb30fa.png)

`metric --metric pb`
![Screenshot 2022-11-02 at 4 13 42 PM](https://user-images.githubusercontent.com/85772166/199619889-e7221c51-8d6a-4890-9b0d-53ab08c5b55b.png)

**Comment by JerBouma** [comment]
There are indeed some wild results within Yahoo Finance that require a better look. Do note that the PB ratio is actually correct, it simply is based on quarterly book value. It doesn't say so, which makes it weird to look at, but given that definition they do all match up. Requires some action.

**Comment by JerBouma** [comment]
Actually, I need to come back on this. These numbers can totally be correct, we are looking at **enterprise value** here. What needs to happen here is that we draft up the proper definition of these numbers instead. E.g. see:

- https://www.zacks.com/stock/chart/RY/fundamental/enterprise-value
- https://ycharts.com/companies/RY/enterprise_value
- https://www.gurufocus.com/term/ev/RY/Enterprise-Value/RY
- https://www.tradingview.com/symbols/NEO-RY.PR.H/financials-statistics-and-ratios/enterprise-value/

All of them say something else.

**Comment by deeleeramone** [comment]
There is not a single entry that denotes the enterprise value as a negative number; so, clearly, it is the delta of the EV, which is not what the expected output would be. The returned values should be the actual numbers unless otherwise chosen. 

This also impacts the pie charts, because it will simply eliminate these negative values and the companies just won't exist according to the pie chart. You actually have to print the raw dataframe to even get an idea for what the problem is. 

I still call this a bug because, a) Output is not what is expected or described, b) The charts produced do not return results in a lot of instances simply because of this, and the titles do not accurately describe the statistics.

**Comment by JerBouma** [comment]
Yes there is, Zacks notes it as negative too. We need to find the definition, until then we can't consider this a bug.

**Comment by deeleeramone** [comment]
We can assume that the same formula is being applied, regardless of the type of company that it is. Cash and debt are not the same for banks as they are for other types of companies, and thus the formulas are not really applicable to financial services and insurance companies because their balance sheets are fundamentally different. Interest, for example, is a component of income *and* expenses. Debt is money and cash is a liability. 

Yahoo Finance is aware of this discrepancy, and report `N/A` for these metrics. 

<img width="929" alt="Screenshot 2022-11-04 at 6 46 11 PM" src="https://user-images.githubusercontent.com/85772166/200095687-84eba3c1-d002-44e5-8f5f-a4acd5bdb1de.png">

**Comment by JerBouma** [comment]
Formula definition can change dramatically. I will be discussing this with others how we deal with these changes in numbers on a fundamental level.

**Comment by JerBouma** [comment]
See comment on Slack.
