### ISSUE TITLE
[Bug] SDK - `openbb.stocks.options.unu` - Error: unusual_options() got an unexpected keyword argument 'export'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3280]
![Screenshot 2022-11-02 at 8 41 04 PM](https://user-images.githubusercontent.com/85772166/199643456-f4381645-59ad-4568-b686-f9561da25b3f.png)

Model is returned, but `limit` argument does not exist in the SDK function. 

![Screenshot 2022-11-02 at 8 41 43 PM](https://user-images.githubusercontent.com/85772166/199643513-df037f9e-ee5f-44db-91ab-79a03c0ebbec.png)

**Comment by colin99d** [comment]
This will be fixed in Juan's pr.
