### ISSUE TITLE
[Bug] SDK - `openbb.stocks.options.chains` - Missing `--source Nasdaq`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3283]
From the Terminal: 
`usage: chains [-c] [-p] [-m MIN_SP] [-M MAX_SP] [-d TO_DISPLAY] [-h] [--export EXPORT] [--source {YahooFinance,Tradier,Nasdaq}]`

SDK command:

![Screenshot 2022-11-02 at 9 34 51 PM](https://user-images.githubusercontent.com/85772166/199648286-9e4d3871-b6c5-4024-a05b-75b7c77594b7.png)

**Comment by colin99d** [comment]
This will be fixed in Juan's pr.
