### ISSUE TITLE
[Bug] SDK - `openbb.econometrics.norm` - Error: get_normality() got an unexpected keyword argument 'column'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3311]
![Screenshot 2022-11-04 at 10 44 56 AM](https://user-images.githubusercontent.com/85772166/200041593-6bdae647-8e70-447c-a3f7-fd270d47ffb1.png)

![Screenshot 2022-11-04 at 10 43 14 AM](https://user-images.githubusercontent.com/85772166/200041470-fbeba3c8-4181-49d8-9e18-2ed9407a12db.png)

**Comment by deeleeramone** [comment]
Additionally, the function `openbb.common.qa.normality`, is the same function - and even has the same description:

The distribution of returns and generate statistics on the relation to the normal curve. This function calculates skew and kurtosis (the third and fourth moments) and performs both a Jarque-Bera and Shapiro Wilk test to determine if the data is normally distributed.

However, the results are different from each.

![Screenshot 2022-11-05 at 1 24 14 PM](https://user-images.githubusercontent.com/85772166/200139466-de100672-6f91-46ce-94de-354b41f6eebf.png)

**Comment by jmaslek** [comment]
> However, the results are different from each.
> 
> 
> 
> ![Screenshot 2022-11-05 at 1 24 14 PM](https://user-images.githubusercontent.com/85772166/200139466-de100672-6f91-46ce-94de-354b41f6eebf.png)
> 
These are the exact same. One just has the default scipy formatting

**Comment by northern-64bit** [comment]
Regarding the unexpected keyword argument error, the error stems from the model only haveing one parameter and the view having several (including `column`). We default to using the signature from the view model. So it should work if you would have added the `chart=True` parameter. For this very reason the model doc, which includes the model parameters, is in the doc string.

**Comment by deeleeramone** [comment]
> So it should work if you would have added the chart=True parameter. 

There are arguments for `plot` & `chart`. Why?

All `chart=True` does is return a printed table, and the numbers are rounded down to a point where they are meaningless. The table cannot be passed to another function like this without being `--exported` to a file.

![Screenshot 2022-11-06 at 11 20 27 PM](https://user-images.githubusercontent.com/85772166/200248370-6d190274-1d37-4a1f-9409-bdd4bae88eb1.png)

It is rather confusing to have two arguments named: `data`, and, `dataset`. Why wouldn't `dataset` be `name`, or `title`? That is what the argument is actually for, is it not? 

![Screenshot 2022-11-06 at 11 06 15 PM](https://user-images.githubusercontent.com/85772166/200246242-dd732829-0fad-40be-9859-9751567e6762.png)

**Comment by northern-64bit** [comment]
I agree that the function needs to be refactored and fixed, just wanted to explain why the error occured. I'll work on a fix for it 👍
