### ISSUE TITLE
[Bug] stocks/fa/dcf -> Error: Could generate a dataframe for the ticker symbol

### ISSUE THREAD

**Issue by am063080** [OpenBB-finance/OpenBBTerminal#3342]
**Describe the bug**

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

stocks/fa/dcf -> Error: Could generate a dataframe for the ticker symbol
Error: Could generate a dataframe for the ticker symbol
Error: 'list' object has no attribute 'shape'
![dcf issue](https://user-images.githubusercontent.com/117734855/200558136-393f9328-f5b8-4ece-8302-6d423b9aeee6.jpg)

Error: not enough values to unpack (expected 3, got 0)

DCF NOT LOADING

**Comment by jmaslek** [comment]
#3198 duplicate

This has been fixed and will be pushed in the next release
