### ISSUE TITLE
[Bug] Pip install `statsforecast` dependency `numba` conflict

### ISSUE THREAD

**Issue by simmonsj330** [OpenBB-finance/OpenBBTerminal#3348]
**Describe the bug**
`numba` version is too low.
<img width="805" alt="Screen Shot 2022-11-08 at 2 13 15 PM" src="https://user-images.githubusercontent.com/53658028/200664325-7af0276c-cfb0-4d9f-b642-ed45855049e3.png">

Additionally, shouldn't `statsforecast` be an extra dependency under `openbbterminal[prediction]` and not apart of the base install?

**Comment by martinb-bb** [comment]
Statsforecast is installed via darts, so its basically a 2 for 1.
also, just increase numba version to min 0.55
