### ISSUE TITLE
[IMPROVE] SDK - `openbb.econometrics.ols` input can be much nicer

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3369]
How you enter an ols regression is not intuitive. Ideally what you would want to do is the same pattern as Statsmodels uses which is `EXECUTIONS ~ SOUTH + INCOME`. What we currently have to do is the following:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/46355364/201069855-1b1f2d8a-abb8-4ecd-b943-910d2d179976.png">

Instead of Statmodels version:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/46355364/201070043-3a664dd4-347c-4761-b565-8be8c975027d.png">

**Comment by jmaslek** [comment]
How do you like what I refactored it to -- where we use an X and Y variable, and these can be anything you want.
