### ISSUE TITLE
[Bug] SDK - `openbb.econometrics.panel` shows the same thing twice

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3374]
The output of the Panel regression is messy and the same result (the table with regression results) is outputted twice.

![image](https://user-images.githubusercontent.com/46355364/201073302-567f75b2-60f1-4122-88bd-b5870a4d3a67.png)

**Comment by jmaslek** [comment]
Looks like you were auto-running the OLS with whatever was selecting and both were printing.  I will supppress the OLS output in my PR.
