### ISSUE TITLE
[IMPROVE] Error handling for `DCF` function when the symbol is not supported. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3392]
Currently, when users attempt to run the command `/stocks/fa/dcf` with a symbol that is not US-listed, this error message is printed:

![Screenshot 2022-11-11 at 10 14 20 AM](https://user-images.githubusercontent.com/85772166/201403027-8bb963e1-c8e9-4b96-b807-d1733cd267b4.png)

It appears as a bug, when it is actually a limitation of the source. It would be an improvement to make these calculation in-house, using the fundamentals data available from a desirable `--source`.

**Comment by Gabighz** [comment]
I've found that loading e.g. INGA.AS enables replicating this issue. Will take a look but no promises

**To Reproduce**
- Type 'stocks'
- Type 'load INGA.AS'
- Type 'fa'
- Type 'dfc'

**Comment by Gabighz** [comment]
Issue is very likely from line 104 in stocks/fundamental_analysis/dcf_view.py

**Comment by colin99d** [comment]
This error should be handled in new version. Also you find me a source as good as Stock Analysis and I will work on --source command. It was the only one with ~10 years of data. And its the only one where consistently A = L + E and Revenue - expenses = net income. Will close this for now, but you find me a source and im on it.
