### ISSUE TITLE
[Bug] stocks/options/voi - Chart weirdness + `--raw` flag does not work.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3403]
`stocks/load qqq/options/exp 0/voi`

The chart displays `volume` and `oi`. However, `oi` is added on to the end of the `volume` graph, instead of being an overlapping value that begins at 0. The chart title also states that open interest is only displayed during market hours, it appears to be inaccurate. 

When the strike range is defined as `-m 250 -M 290`, the chart does not display the full-width of the values. One needs to zoom out before seeing the complete bar.

![Screenshot 2022-11-12 at 2 26 29 PM](https://user-images.githubusercontent.com/85772166/201506692-b49a5b2a-3416-49a8-a3a3-fb4362ffdeab.png)

`voi --raw` does not show the raw table.

**Comment by hjoaquim** [comment]
@deeleeramone I think when we use the `--source Nasdaq` we can accomplish what you're saying. Should the default (yf) has a similiar chart?
![image](https://user-images.githubusercontent.com/48914296/205985055-8d1b3fe7-f291-4f26-8a5f-bc553b02a6a5.png)
 
I started addressing this here (mainly the `--raw` issue): #3665
