### ISSUE TITLE
[IMPROVE] Installation on Apple M2 CPU

### ISSUE THREAD

**Issue by ajoaris** [OpenBB-finance/OpenBBTerminal#3409]
**What's the feature that should be improved?**
Installation doesn't recognize the Mac M2 CPU.

**Describe how you would like the feature improved**
Extend the hardware for OpenBBTermınal.

**Possibly describe the ideal way to improve this**
I guess recompile with the additional CPU checks and authorize M2.

**Additional information**
Add any other information or screenshots about the feature improvement.
<img width="1158" alt="Screen Shot 2022-11-14 at 11 03 01" src="https://user-images.githubusercontent.com/58373247/201606860-6eea9d64-58c5-4b9b-8f62-c16a80f47076.png">

**Comment by deeleeramone** [comment]
Hi there, 

Does your system Terminal open using "Rosetta"? If not, please select this option and try again.

![Screenshot 2022-11-14 at 11 46 59 AM](https://user-images.githubusercontent.com/85772166/201751819-99a743b3-3408-4f65-a69e-f395d4573a51.png)

**Comment by ajoaris** [comment]
Hi,

Much better indeed.  It works with Rosetta.

Thanks a lot.

**Comment by deeleeramone** [comment]
I'm going to leave this open for now because of this report from another M2 user, and Rosetta did not resolve:

![image](https://user-images.githubusercontent.com/85772166/202601422-592284af-3402-461c-a778-9bcdccb34d48.png)
