### ISSUE TITLE
[Bug] After loading `/stocks/load` Performace Stats are not current. Last Price != Last Price

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3430]
![Screenshot_20221115_101347](https://user-images.githubusercontent.com/85772166/201995436-dd133fdb-848e-49bf-a2df-ecddd8284e16.png)

**Comment by colin99d** [comment]
@jmaslek it looks like the top once is pulling from the historical data while the quote is pulling from ticker.info. I think we should just update the names to express exactly what each one means.
