### ISSUE TITLE
[Bug] economy single line with plot

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3442]
![image](https://user-images.githubusercontent.com/25267873/202424855-232d21d1-7bba-4ee9-9db8-1a5596cc5dd1.png)

Recreate: economy/index --indices sp500,cboe_vix  -s 2022-10-10/plot --y1 sp500 --y2 cboe_vix

**Comment by jmaslek** [comment]
The plot function does show the 2 different y values. 
![Screen Shot 2022-11-17 at 9 58 42 AM](https://user-images.githubusercontent.com/18151143/202480656-350bda31-1717-402c-8a82-d8719e5e0455.png)

One other suggestion is to use the `--returns` flag on index.
<img width="801" alt="Screen Shot 2022-11-17 at 10 00 31 AM" src="https://user-images.githubusercontent.com/18151143/202481015-33765a26-68aa-416f-8d7c-752130862ac3.png">
