### ISSUE TITLE
[Bug] SDK - openbb.economy.spectrum() returns nothing

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3448]
With or without arguments, it returns nothing.

`openbb.economy.spectrum(group = sector)`

**Comment by jmaslek** [comment]
Im in favor of ditching this function.

After you run it -- there is a Sector.jpg in your folder right?

**Comment by deeleeramone** [comment]
yes. it is kind of out of place.

**Comment by jmaslek** [comment]
Right now, you would run spectrum_chart to get it to open.  I will change this shortly to make it just spectrum.  Or delete it.  Havent decided yet.

**Comment by jmaslek** [comment]
#3450 will address this

**Comment by colin99d** [comment]
Fixed with #3450
