### ISSUE TITLE
[Bug] /stocks/options/greeks

### ISSUE THREAD

**Issue by andrewkenreich** [OpenBB-finance/OpenBBTerminal#3454]
Pretty sure this is a weekly issue - but I loaded Friday Exp and got this error

Ticker is AMD Today is Thursday the 17th and expiration is 18th. greeks does this

<img width="393" alt="image" src="https://user-images.githubusercontent.com/23067478/202607083-8c67ada0-2d1c-450e-bad0-23fd5c7d070c.png">

**Comment by jmaslek** [comment]
So if I remember correctly, this is because some of the options in yfinance return an iv=0.

We can get rid of it by filtering impliedVolatility>0.

The Greeks fail because of the 1/iv terms.

**Comment by deeleeramone** [comment]
@andrewkenreich , this is probably because of a stock split, and there are now two options chains. `AMD1221118` and `AMD221118`
![Screenshot 2022-11-17 at 8 42 34 PM](https://user-images.githubusercontent.com/85772166/202618552-7b476d35-434b-466b-90a2-de466251e67a.png)

**Comment by deeleeramone** [comment]
![Screenshot 2022-11-17 at 8 50 23 PM](https://user-images.githubusercontent.com/85772166/202619517-ed768553-55a4-4c5d-9020-3a5f5b0a1700.png)

**Comment by deeleeramone** [comment]
`chains` does not the same output for greeks as `greeks`... 

![Screenshot 2022-11-17 at 10 37 27 PM](https://user-images.githubusercontent.com/85772166/202637343-1a87ea39-b54f-4362-8ef8-4ee851055a01.png)

this is likely flawed as well, `rfr` is not 0:
```
usage: greeks [-d DIVIDEND] [-r RISK_FREE] [-p] [-m MIN] [-M MAX] [-a] [-h] [--export {png,jpg,pdf,svg}]

The greeks for a given option.

optional arguments:
  -d DIVIDEND, --div DIVIDEND
                        The dividend continuous rate (default: 0)
  -r RISK_FREE, --risk-free RISK_FREE
                        The risk free rate (default: None)
  -p, --put             Whether the option is a put. (default: False)
  -m MIN, --min MIN     Minimum strike price to show. (default: None)
  -M MAX, --max MAX     Maximum strike price to show. (default: None)
  -a, --all             Whether to show all greeks. (default: False)
  -h, --help            show this help message (default: False)
  --export {png,jpg,pdf,svg}
                        Export figure into png, jpg, pdf, svg (default: )

For more information and examples, use 'about greeks' to access the related guide.
```


![Screenshot 2022-11-17 at 10 34 40 PM](https://user-images.githubusercontent.com/85772166/202636847-67691e4f-0854-455d-8c3a-7bc381d1a045.png)

**Comment by colin99d** [comment]
@jmaslek, are you still planning on removing this functionality?
