### ISSUE TITLE
[FR] Prediction Models Accuracy or F-Score metrics?

### ISSUE THREAD

**Issue by austenmyers** [OpenBB-finance/OpenBBTerminal#346]
We cannot compare the prediction models for our different use cases unless we have some sort of scoring metric for each.

This will improve the prediction piece of the project tremendously imho.

- A

**Comment by DidierRLopes** [comment]
You mean like we have implemented for the Neural Network models?

E.g.
![](https://user-images.githubusercontent.com/25267873/111053158-420c7300-8459-11eb-993b-6d9c26f98af9.png)

**Comment by austenmyers** [comment]
Thanks @DidierRLopes I didn't notice this in the code, what method did you call for the above screenshot?
I was merely using the pred -> one of the models and passing a ticker to see preds, but didn't see the function for displaying the model scoring metrics for the historical.

**Comment by DidierRLopes** [comment]
This one is only used for Neural Networks!

Do you think the other prediction models should also have these?

**Comment by austenmyers** [comment]
Yeah I think it is interesting to see the model metrics for any kind of predictive model personally

**Comment by DidierRLopes** [comment]
Sounds good, I'll try to work on this soon!
