### ISSUE TITLE
[Bug] Dashboards/vsurf - get stuck at 2 of 4

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3463]
![Screenshot 2022-11-17 at 8 04 10 PM](https://user-images.githubusercontent.com/85772166/202614245-13d0f7b5-dfdc-4732-9d41-ec1c88f92a07.png)

**Comment by colin99d** [comment]
@deeleeramone I think this works it just takes a pretty long time (just took me 10 minutes).

**Comment by colin99d** [comment]
Nvmd. It takes forever now. Only works in Jupyter.
