### ISSUE TITLE
[Bug] /stocks/ba All Stocktwits source commands don't seem to do anything

### ISSUE THREAD

**Issue by andrewkenreich** [OpenBB-finance/OpenBBTerminal#3468]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/23067478/202617264-0a551c49-e32b-4edd-b97b-3cf867df4b19.png">

**Comment by deeleeramone** [comment]
Not able to reproduce here. 

![Screenshot 2022-11-17 at 10 16 59 PM](https://user-images.githubusercontent.com/85772166/202634180-603ef60a-1037-45b6-ab11-37fa83076150.png)

![Screenshot 2022-11-17 at 10 17 52 PM](https://user-images.githubusercontent.com/85772166/202634303-c88edb36-c066-46ad-b3b4-e326985242bb.png)


![Screenshot 2022-11-17 at 10 18 31 PM](https://user-images.githubusercontent.com/85772166/202634395-3425df0a-5fc8-4bea-994d-22d0529a7e37.png)

**Comment by jmaslek** [comment]
cannot replicate

**Comment by andrewkenreich** [comment]
Ok - I ran on my windows box and it worked - mac must suck - closing
