### ISSUE TITLE
[IMPROVE] /stocks/ca/get - Similar company returning the company you lookup - should show first

### ISSUE THREAD

**Issue by andrewkenreich** [OpenBB-finance/OpenBBTerminal#3470]
ok its late so ignore this - but improvement comment below :D

**Comment by andrewkenreich** [comment]
also if you leave menu and comeback - The same ticker is still on the Similar - but just that one.

**Comment by andrewkenreich** [comment]
ok im dumb but... - We should show this ticker first on all the tables - as we are comparing this against the others for quick reference

**Comment by jmaslek** [comment]
looks like this became the cast at some point
