### ISSUE TITLE
[Bug] stocks/fa/fraud and dupont - need to show API Key error

### ISSUE THREAD

**Issue by andrewkenreich** [OpenBB-finance/OpenBBTerminal#3471]
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/23067478/202624925-fd260c85-e236-44a1-a153-6b18bfa7df34.png">

**Comment by colin99d** [comment]
These fakes his my first PR behind a paywall???

**Comment by colin99d** [comment]
Aye!! My first pr.
