### ISSUE TITLE
[Improve] SDK `openbb.crypto.load` when `source = CCXT`, adding the `interval` is only a string

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3478]
```python
df_eth = openbb.crypto.load(
    symbol = 'ETH',
    source = 'CCXT',
    exchange = 'binance',
)
```

![Screenshot 2022-11-18 at 10 05 17 AM](https://user-images.githubusercontent.com/85772166/202772971-d97902e0-c6bb-48df-acbf-82292e460d52.png)

```python
df_eth = openbb.crypto.load(
    symbol = 'ETH',
    source = 'CCXT',
    exchange = 'binance',
    interval = 30,
)
Pair ETH/USDT not found on binance
```

It works in the Terminal, but not the SDK

![Screenshot 2022-11-18 at 10 05 51 AM](https://user-images.githubusercontent.com/85772166/202773051-4db8cb2a-87f3-4594-be4b-fd410526e308.png)

**Comment by jmaslek** [comment]
does it work if you pass the interval as a string?  "30"

**Comment by deeleeramone** [comment]
Yes it does, I guess I forgot to read the docstring where it says that. 

| date                |    Open |    High |     Low |   Close |   Volume |
|:--------------------|--------:|--------:|--------:|--------:|---------:|
| 2022-11-18 16:00:00 | 1211.14 | 1214.47 | 1209.17 | 1210.74 |  4582.63 |
| 2022-11-18 16:30:00 | 1210.74 | 1211.05 | 1203.5  | 1207.45 | 11714.9  |
| 2022-11-18 17:00:00 | 1207.44 | 1208.35 | 1200.36 | 1205.35 | 11359.4  |
| 2022-11-18 17:30:00 | 1205.36 | 1207.12 | 1202.5  | 1204.17 |  5878.59 |
| 2022-11-18 18:00:00 | 1204.17 | 1207.28 | 1203.26 | 1206.37 |  1540.67 |

**Comment by jmaslek** [comment]
Leave this open.  Not intuitive to pass a string, so i want to add in string or int
