### ISSUE TITLE
[Bug] Can't load SDK - ParserError: Error tokenizing data. C error: Expected 3 fields in line 334, saw 4

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3485]
Not sure what happened, I'm on Main branch, and suddenly can't load SDK. Something to do with `trail_map = TrailMap()`

![Screenshot 2022-11-18 at 8 30 54 PM](https://user-images.githubusercontent.com/85772166/202834115-d956e6ee-b853-4433-8635-9d3c8bbea8ae.png)
![Screenshot 2022-11-18 at 8 32 17 PM](https://user-images.githubusercontent.com/85772166/202834147-1347647b-7259-49a7-9e14-217be4387297.png)

**Comment by jmaslek** [comment]
Oooof. The parser saying 4 instead of 3 means there is probably an extra , in the trail map csv somewhere.

Any chance if you open the trailmap.csv (in the miscellaneous folder) is it possible to ctrl+F for a double , (,,).  If there is anything, getting rid of one should solve this

**Comment by deeleeramone** [comment]
Looks like the everything under Portfolio Optimization. 

![Screenshot 2022-11-18 at 8 53 21 PM](https://user-images.githubusercontent.com/85772166/202834804-40725e9b-eefd-4538-9282-f84e61e22476.png)

**Comment by jmaslek** [comment]
That'll do it.  Should all be single ,

**Comment by jmaslek** [comment]
#3487

**Comment by deeleeramone** [comment]
line 334 issue seems resolved, now line 345 is the new blocker  
![Screenshot 2022-11-19 at 10 12 49 AM](https://user-images.githubusercontent.com/85772166/202865552-d1002b9b-c8e0-44b9-8c4a-33c59e83b470.png)

**Comment by jmaslek** [comment]
aha i found it.  trailing ' after view functions as well.  1 second
![Screen Shot 2022-11-19 at 1 25 27 PM](https://user-images.githubusercontent.com/18151143/202865973-6594a69b-eaea-436b-a7a6-cb34249b12c3.png)
