### ISSUE TITLE
[Improve] Error Handling For Stocks Insider Menu When Ticker is not US Exchange-Listed

### ISSUE THREAD

**Issue by jczernia** [OpenBB-finance/OpenBBTerminal#3493]
**Describe the bug**
Insider trading data shows data for ENR ticker while ENR.DE was loaded 

**To Reproduce**
1. Go to stocks menu and load ENR.DE (Siemens Energy - Germany)
2. Move to ins menu
3. Note ticker ENR (instead of ENR.DE) is listed there
4. Run stats - note data for ENR are listed

**Screenshots**

**Desktop (please complete the following information):**

- OS: N/A
- Python version N/A
- OpenBB Terminal v1.9.0 (from Win installer)

**Additional context**
Feel free to contact me for more data if needed

**Comment by deeleeramone** [comment]
Hi, this data is only for SEC filings, and therefore does not work for this symbol.

**Comment by jczernia** [comment]
Hi I still think it is a bug. For companies which doesn't have SEC fillings the message is that data is unavailable or something like that. Here it shows simply wrong data. It took me a while when I processed this company to realize that the presented data is trash.
