### ISSUE TITLE
Missing dotenv module in conda env install

### ISSUE THREAD

**Issue by bjg90** [OpenBB-finance/OpenBBTerminal#3494]
**Describe the bug**
Missing modules -  "ModuleNotFoundError: No module named 'dotenv'"

After manually conda install dotenv then more modules are missing with trying to run.

**To Reproduce**
install openBB using ReadMe for conda env. then try 'python terminal.py'

**Comment by deeleeramone** [comment]
Hello, this error - in many cases - is resolved by activating the environment before running `python terminal.py`.

```
conda activate obb
python terminal.py
```

**Comment by garcialn** [comment]
Hello. I'm having the same problem but i'm sure it's not because of the venv. I'm in the correct folder with even active and running into the same message

**Comment by deeleeramone** [comment]
Hey, 

Can you confirm that when installing, after activating the environment upon creating, that you then ran `poetry install -E all`?

**Comment by deeleeramone** [comment]
> 

Same question as well, please confirm. When you installed, after creating and activating the `conda` environment, did you then next run, `poetry install`?

**Comment by garcialn** [comment]
Hi, there. Yes, i did.

But i think i was running into some issues for some problems with new versions of dependencies. I just needed to run `poetry update`to update everything, and after that, the `python terminal.py`worked just fine.

Thank u for the attention!

**Comment by deeleeramone** [comment]
Glad to know you got it figured!
