### ISSUE TITLE
[Bug] Forecast report not working with installer

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#3504]
**Describe the bug**
![image](https://user-images.githubusercontent.com/79287829/203142329-fafd6583-dedc-4f7d-ba6b-30fb9d6ef8ed.png)

OS: Windows 11 Home

**Comment by montezdesousa** [comment]
Apparently was fixed by https://github.com/OpenBB-finance/OpenBBTerminal/pull/3509

**Comment by jmaslek** [comment]
weird I didnt touch this one lol
