### ISSUE TITLE
[Bug] SDK `openbb.stocks.sia.maketcap` --> missing `r`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3510]
![Screenshot 2022-11-21 at 9 58 06 PM](https://user-images.githubusercontent.com/85772166/203236505-50a882f0-ec65-4787-8d0e-57b3708b47fb.png)

**Comment by deeleeramone** [comment]
Also seems to be missing a few arguments.

![Screenshot 2022-11-21 at 10 07 55 PM](https://user-images.githubusercontent.com/85772166/203237796-5e4f67ec-599d-4441-83c2-f6681d42b2f1.png)

**Comment by PedroMirao** [comment]
pls assign it to me! :)

**Comment by sbshah97** [comment]
Is this completed? Would love to contribute. Any good first issues?

**Comment by jmaslek** [comment]
Hey @sbshah97.  Yes this got taken care of!

A good first issue could be #3865!
