### ISSUE TITLE
[Bug] SDK - `openbb.stocks.ca.dle()`: TypeError: 'Breadcrumb' object is not callable

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3511]
![Screenshot 2022-11-21 at 10 12 17 PM](https://user-images.githubusercontent.com/85772166/203238451-ad28e0e6-8eff-4633-845c-7db9db963f3c.png)

**Comment by jmaslek** [comment]
There is no dle function.
![Screen Shot 2022-11-22 at 8 26 40 AM](https://user-images.githubusercontent.com/18151143/203326007-345c0fea-f873-44c8-abab-d63705764a1a.png)


Although @Chavithra, I bet this is parsing stocks.candle as stocks.ca.dle.  Does

**Comment by colin99d** [comment]
<img width="702" alt="Screenshot 2022-11-25 at 11 52 46 AM" src="https://user-images.githubusercontent.com/72827203/203967861-2f2f2cbe-feeb-4004-9eef-3de970c82ee8.png">
The bug here is that dle is shown as a valid option, even though it is not.
