### ISSUE TITLE
[Bug] SDK `stocks.ca.hcorr` - When candle_type = 'R', NaN values found. Backfilling Data

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3512]
```python
tickers = ['SPY', 'XLE', 'XLB', 'XLI', 'XLP', 'XLY', 'XLV', 'XLF', 'XLK', 'XLC', 'XLU', 'XLRE']
openbb.stocks.ca.hcorr(similar = tickers, candle_type = 'R', start_date = '2018-11-12')
```
```console
NaN values found in: SPY	XLE	XLB	XLI	XLP	XLY	XLV	XLF	XLK	XLC	XLU XLRE. Backfilling data
             No results.
```

![Screenshot 2022-11-21 at 10 26 37 PM](https://user-images.githubusercontent.com/85772166/203240610-88cc0e3f-987a-4403-bd7d-f44ab9e4611b.png)

```python
openbb.stocks.ca.hcorr(similar = tickers, candle_type = 'a', start_date = '2018-11-12')
```

![Screenshot 2022-11-21 at 10 25 16 PM](https://user-images.githubusercontent.com/85772166/203240423-2711f13b-75e4-49cd-805e-79c6130c59e0.png)

**Comment by colin99d** [comment]
<img width="907" alt="Screenshot 2022-11-25 at 11 25 45 AM" src="https://user-images.githubusercontent.com/72827203/203962769-bb162983-29b1-437f-8d1d-d35c977562a1.png">
@deeleeramone this is what I get now, is this the desired output?

**Comment by deeleeramone** [comment]
I'm wondering why `NaN` values message gets printed. When correlation is for `returns`, does it not ignore the first row, because returns will be 0?

**Comment by colin99d** [comment]
The message is telling the user that the data included NaN's so they were backfilled. And it looks like a list of dataframes is whats provided.
