### ISSUE TITLE
[Bug] SDK - `openbb.stocks.dd.news` - Error: time data 'Nov-21-22 02:50' does not match format '%b-%d-%y %I:%M%p'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3513]
```
openbb.stocks.dd.news(symbol = 'XLE')

Error: time data 'Nov-21-22 02:50' does not match format '%b-%d-%y %I:%M%p'

```
![Screenshot 2022-11-21 at 10 35 17 PM](https://user-images.githubusercontent.com/85772166/203242106-6ab8aea1-3604-4167-8338-3c1937501f97.png)

**Comment by montezdesousa** [comment]
Apparently this is as finviz issue. We either leave it as is or we disable the endpoint...

![Screenshot 2022-11-22 at 12 47 52](https://user-images.githubusercontent.com/79287829/203317764-a6829a9c-9279-4bfb-b012-8fafb3bba802.png)

**Comment by colin99d** [comment]
The new command is here: openbb.stocks.fa.news(symbol = 'XLE')

**Comment by colin99d** [comment]
Unfortunately, as Diogo said, we won't be able to actually fix this. But I have added a better message and left an issue on Finviz.

**Comment by colin99d** [comment]
https://github.com/mariostoev/finviz/issues/152
