### ISSUE TITLE
[Bug] SDK - `openbb.stocks.splits` has `_chart` but `dividends` does not. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3515]

**Comment by montezdesousa** [comment]
> <img alt="Screenshot 2022-11-22 at 8 11 55 AM" width="857" src="https://user-images.githubusercontent.com/85772166/203364506-8776667f-915a-4712-ac92-5f64d5414df4.png">

Got it, but `divs` has no chart in the terminal, just a rich table

**Comment by deeleeramone** [comment]
it does, `divs --plot`

<img width="1389" alt="Screenshot 2022-11-22 at 8 34 45 AM" src="https://user-images.githubusercontent.com/85772166/203369898-9583dba2-8b46-466c-8b38-93ecbb45a908.png">

**Comment by montezdesousa** [comment]
> it does, `divs --plot`
> 
> <img alt="Screenshot 2022-11-22 at 8 34 45 AM" width="1389" src="https://user-images.githubusercontent.com/85772166/203369898-9583dba2-8b46-466c-8b38-93ecbb45a908.png">

nvm I'm dumb, will take a look thanks!
