### ISSUE TITLE
[Bug] Stocks/FA - Quarterly statements are not available from Yahoo Finance. Returning Annual. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3516]
This error message is incorrect, and the function is broken. 

![image](https://user-images.githubusercontent.com/85772166/203248152-ed2f787f-bf50-46dc-9758-c4634ad0cc06.png)

![image](https://user-images.githubusercontent.com/85772166/203248180-c29137c1-4f2b-492c-8099-a97066f24e78.png)

**Comment by jmaslek** [comment]
This was a reasoning behind #1984.  On discord, it was discussed our UK friends couldn't access yf financials, so the request is now hard coded:
```
url = (
        "https://uk.finance.yahoo.com/quote/"
        + symbol
        + "/"
        + statement
        + "?p="
        + symbol
)
```

If we look at the request to yahoo when asking for quarterly, we see that we can pass a `&type=quarterly`, however when we actually pass that to the url, we can see there is still annual data being passed.

![Screen Shot 2022-11-22 at 9 03 28 AM](https://user-images.githubusercontent.com/18151143/203333698-54f2e875-fe2a-42aa-af07-cb6d18d2a426.png)
