### ISSUE TITLE
[Bug] SDK - `openbb.stocks.dps.vol_exch_chart` - Error: 'Date' 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3519]
![Screenshot 2022-11-21 at 11 44 29 PM](https://user-images.githubusercontent.com/85772166/203255020-d8dcf8b0-1059-493d-93ed-dccd1bcbe9bf.png)

**Comment by montezdesousa** [comment]
@jmaslek you commented this command `volexch` in the terminal, should we remove it from the SDK as well? Not sure if the original issue is solved

**Comment by jmaslek** [comment]
> @jmaslek you commented this command `volexch` in the terminal, should we remove it from the SDK as well? Not sure if the original issue is solved 

Yes it should not be in the sdk
