### ISSUE TITLE
[Bug] prediction score is caculated with wrong data?

### ISSUE THREAD

**Issue by cg31** [OpenBB-finance/OpenBBTerminal#3527]
The prediction score is caculated by using original series with forecast:

https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/forecast/helpers.py#L745
```
precision = mape(
        actual_series=ticker_series, pred_series=historical_fcast
    )  # mape = mean average precision error
```

it shoud use validation series with forecast:
```
train, val = ticker_series.split_before(train_split)

precision = mape(
        actual_series=val, pred_series=historical_fcast
    )  # mape = mean average precision error
```

**Comment by colin99d** [comment]
@martinb-bb you know anything about this?

**Comment by martinb-bb** [comment]
hi @cg31  thanks for the report! 

This was done only due to assuming the MAPE module calculated percentage only on matching timestamps with `historical_fcast`
When running both, I get the same MAPE, but it is best we follow regular protocol for data science principals. 

Thank you for your report! It will be updated shortly.

**Comment by cg31** [comment]
You are right, the results are the same. Because darts will use the common time interval of two series:
https://github.com/unit8co/darts/blob/master/darts/metrics/metrics.py#L554

so it is indeed a readability issue. I was surprised when reading the code.

**Comment by martinb-bb** [comment]
Precisely! 

Again, thanks for the report! Your feedback means a lot to the company. Please do not hesitate to create another report if you find a discrepancy in anything else. :+1: 

Will close now as the fix will be updated shortly.
