### ISSUE TITLE
[FR] - Put Call ratio 

### ISSUE THREAD

**Issue by FriendlyUser** [OpenBB-finance/OpenBBTerminal#3546]
**What's the problem of not having this feature?**
Put Call Ratio for SPY, using the put call ratio you can see if investors are bullish or bearish, I could figure out how to scrap it from some websites, but I think there are better solutions out there.

**Describe the solution you would like**

User searchs for put call ratio and then receives chart and data
(https://www.barchart.com/stocks/quotes/$CPC)

**Describe alternatives you've considered**
go to website https://www.barchart.com/stocks/quotes/$CPC

**Additional information**
![image](https://user-images.githubusercontent.com/13860264/203607321-4d55e241-6f14-4a2d-b782-1b80ce4d44df.png)

**Comment by deeleeramone** [comment]
This already exists, `/stocks/options/info` and `/stocks/options/pcr`

![Screenshot 2023-01-10 at 2 20 23 PM](https://user-images.githubusercontent.com/85772166/211674601-f595c219-0bc4-4a40-8cc5-5a8d7de42ba1.png)

![Screenshot 2023-01-10 at 2 21 08 PM](https://user-images.githubusercontent.com/85772166/211674743-a5f7f9af-0e92-467d-a80d-2b8562f0aedb.png)

**Comment by FriendlyUser** [comment]
Let me try this out
