### ISSUE TITLE
[Bug] SDK - `openbb.forecast.show()` console print returned and no dataframe

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3551]
![Screenshot 2022-11-23 at 4 31 22 PM](https://user-images.githubusercontent.com/85772166/203668601-fb536af4-6571-49eb-9ff9-056c7798b76c.png)

```
openbb.forecast.show_chart(data = 'SPY')

Error: 'str' object has no attribute 'shape'
```

**Comment by deeleeramone** [comment]
![Screenshot 2022-11-23 at 4 42 32 PM](https://user-images.githubusercontent.com/85772166/203669644-e37e1adc-1425-497a-8d8c-1187fee5a85e.png)

**Comment by martinb-bb** [comment]
This works now, with changes to PR:
https://github.com/OpenBB-finance/OpenBBTerminal/pull/3554

<img width="591" alt="image" src="https://user-images.githubusercontent.com/105685594/203686520-1011949f-6e94-41c4-a970-25237d14e504.png">

**Comment by martinb-bb** [comment]
@deeleeramone  Will remove show from SDK in the future release
