### ISSUE TITLE
[Bug] SDK - `openbb.forecast.plot_chart` is redundant

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3552]
`openbb.forecast.plot` works, although some parameters to label the axes and the title would be beneficial here

**Comment by martinb-bb** [comment]
Currently: 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/105685594/203689486-add91bee-e77a-4e38-a87e-1f28fd5e1a57.png">

I will look into how to get the `ax` to display title. seems like when its run in a note book, the legend does not appear (but works fine in the terminal.

**Comment by martinb-bb** [comment]
@deeleeramone  Placed in backlog :)
