### ISSUE TITLE
[Bug] SDK - All Forecast functions seemingly broken - Warning: no date found, assuming items evenly spaced.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3553]
date = date?

![image](https://user-images.githubusercontent.com/85772166/203676348-216916d1-d38c-4094-98fe-a8ed7b75525b.png)

![image](https://user-images.githubusercontent.com/85772166/203676504-ee7dbb8f-de24-482f-9ee9-9e4421921529.png)

**Comment by martinb-bb** [comment]
Fixed.
