### ISSUE TITLE
[Bug] Equity report with empty plots

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3565]
<img width="803" alt="Screenshot 2022-11-25 at 00 09 26" src="https://user-images.githubusercontent.com/25267873/203876756-1eb30ed3-73ed-48c9-bf95-4bf1f72447ba.png">

**Comment by DidierRLopes** [comment]
This is what I'm getting now on the latest branch

<img width="1272" alt="Screenshot 2022-12-08 at 10 30 28" src="https://user-images.githubusercontent.com/25267873/206424161-8140076c-8bff-4733-8001-7c3754b9875b.png">

**Comment by jmaslek** [comment]
#3732 will fix the handing notebook @DidierRLopes.

I do not see the empty plots.
