### ISSUE TITLE
[Bug] Reports/Portfolio - Report fails because cell five declares the path for holdings to be in the code folder.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3569]
The portfolio report fails, giving an error message: An error was encountered in cell [12], check the notebook.

Checking the notebook reveals that in cell [5]:

```
holdings = (
    str(REPOSITORY_DIRECTORY)
    + "/openbb_terminal/miscellaneous/portfolio_examples/holdings/"
)
```

The correct path is:

`"~/OpenBBUserData/portfolio/holdings/"`

It would make the user experience much better if the sample files, templates, and screener presets all had, at minimum, a clickable shortcut present in the OpenBBUserData folder that allows them to navigate to where these files exist within the code folders.

**Comment by montezdesousa** [comment]
I'm guessing the issue occurred when you tried to use a file that was not a OpenBB template. Can you try and see if it's fixed here https://github.com/OpenBB-finance/OpenBBTerminal/pull/3574?

I'm not sure if it is good idea to mix OpenBB template files with user's. We can and should provide the files as a template but if everything lies in the OpenBBUserData folder, the risk of user deleting or changing the folder/file and breaking the command is higher.

**Comment by deeleeramone** [comment]
Here's the thing with this, the path for the report is pointed at the source code folder, users do not keep their files there. Why would I want a report for a template?  The path needs to be OpenBBUserData, and not the code directory.

**Comment by montezdesousa** [comment]
Fixed by https://github.com/OpenBB-finance/OpenBBTerminal/pull/3574
