### ISSUE TITLE
[Bug] etf/load arkw/overview

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3581]
![Screenshot 2022-11-25 at 16 04 43](https://user-images.githubusercontent.com/25267873/204022028-78c6ae53-1861-4825-9bdf-929b95d80a40.png)

**Comment by DidierRLopes** [comment]
compare is also not working:

![Screenshot 2022-11-25 at 16 06 39](https://user-images.githubusercontent.com/25267873/204022238-147e6d03-e827-4ad4-858d-8fac3831cbb9.png)

**Comment by jmaslek** [comment]
Stockanalysis has changed up again.  We need to remove them as they are unmaintainable on our end

**Comment by simmonsj330** [comment]
I can't seem to replicate the errors :grimacing:

<img width="529" alt="Screen Shot 2022-11-27 at 12 54 44 AM" src="https://user-images.githubusercontent.com/53658028/204123177-43c2b2b0-579a-460d-a553-af1f70601e27.png">

<img width="420" alt="Screen Shot 2022-11-27 at 12 55 37 AM" src="https://user-images.githubusercontent.com/53658028/204123205-cd04fb2e-430a-41ba-a2d6-ab04d0374f1a.png">

**Comment by DidierRLopes** [comment]
@simmonsj330 @jmaslek has fixed them 🙏🏽 Closing this now
