### ISSUE TITLE
[IMPROVE] Store API Keys when running via Docker

### ISSUE THREAD

**Issue by Shivamp629** [OpenBB-finance/OpenBBTerminal#3585]
**What's the feature that should be improved?**
API Keys should be saved to storage when running the terminal via Docker. Currently, if you run the container and set keys, they're wiped when you restart the container and have to set them all over again.

**Describe how you would like the feature improved**
When running and stopping the docker container, API keys should be persisted on disc so that they do not need to be set again.

**Possibly describe the ideal way to improve this**
If you have thought about how you would do it, add it here.

**Additional information**
Add any other information or screenshots about the feature improvement.

**Comment by piiq** [comment]
Hey 👋

This was addressed in December 2022 with the updates to key management and the introduction of the `~/.openbb_terminal/.env` file.

The issue of keys not being available in the container was resolved by #3545 #3666 and subsequent PRs.

When using docker you can mount that file into the container to have your keys available

We have a docker-compose file that helps you launch the container with a simpler command (compared to a `docker run`)

```
curl -o docker-compose.yaml https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.yaml

docker compose run openbb
```

It mounts your key/settings file and your OpenBBUserData folder into the container
<img width="528" alt="image" src="https://user-images.githubusercontent.com/11668535/218054387-3e650aa0-b22f-413b-a595-6c67b3782d15.png">
