### ISSUE TITLE
[Bug] Portfolio/Holdp - chart is not right - Terminal & SDK

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3586]
`portfolio/holdp`

![Screenshot 2022-11-25 at 3 22 41 PM](https://user-images.githubusercontent.com/85772166/204062780-f572d005-3c87-4439-8fa2-b1e3306db112.png)

**Comment by deeleeramone** [comment]
Typically in a stacked chart the highest weighting or value is at the top, and lowest weighting is at the bottom. This appears randomly ordered, confusing to interpret, and the legend is also very hard to read.

**Comment by montezdesousa** [comment]
> Typically in a stacked chart the highest weighting or value is at the top, and lowest weighting is at the bottom. This appears randomly ordered, confusing to interpret, and the legend is also very hard to read. 
> 
> Thinking out loud here, wouldn't a pie chart be better suited for the presentation of the information
> 
> **edit**: probably should have kept that thought to myself. Pie charts aren't any good for a timeseries. haha.

Ahah :) Ok got your idea, we need to pop the legend out and sort the weights. Sounds good?

**Comment by deeleeramone** [comment]
Is there a difference between this chart and the multi-line chart it is replacing? The only difference between them that I can see is that this new one wants to have a 100% fill all the time, whereas the line chart plots the weights as is and a 40% weighting will automatically be on the top.

**Comment by deeleeramone** [comment]
@montezdesousa - I managed to make a portfolio that adds up to more than 100%.

![Screenshot 2022-12-23 at 9 33 55 AM](https://user-images.githubusercontent.com/85772166/209377603-124e6192-6135-4dd8-b905-1f2977ad7ecf.png)

**Comment by montezdesousa** [comment]
> @montezdesousa - I managed to make a portfolio that adds up to more than 100%.
> 
> ![Screenshot 2022-12-23 at 9 33 55 AM](https://user-images.githubusercontent.com/85772166/209377603-124e6192-6135-4dd8-b905-1f2977ad7ecf.png)
> 
> It would be better to move the legend so that it is outside of the graph.

Thanks, that's not ok. Could you share the file used to reproduce this pls?

**Comment by colin99d** [comment]
There are issues here, but I am closing this in favor of #3121.
