### ISSUE TITLE
[Bug] Portfolio/holdv - chart doesn't make any sense

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3587]
![Screenshot 2022-11-25 at 3 30 06 PM](https://user-images.githubusercontent.com/85772166/204063080-79caa4de-f7bc-4503-9932-367c1872f0f9.png)

**Comment by montezdesousa** [comment]
This was discussed here https://github.com/OpenBB-finance/OpenBBTerminal/issues/3121. What doesn't make sense?

**Comment by deeleeramone** [comment]
Same as #3586 - not stacked according to value.

**Comment by colin99d** [comment]
Issue discussed in #3121
