### ISSUE TITLE
[FR]Request for voi in sdk

### ISSUE THREAD

**Issue by JingyiHe99** [OpenBB-finance/OpenBBTerminal#3631]
**What's the problem of not having this feature?**
Can voi function be imported in SDK? I think we can use voi in python before, but now this function only exists in terminal.
![image](https://user-images.githubusercontent.com/119362053/204383971-7eaec130-bf41-4826-ac1b-f4c5378009e9.png)
The voi function chart would look like this:
![image](https://user-images.githubusercontent.com/119362053/204384148-efc8db01-8760-4ba4-a5d7-9c3a21a70e56.png)

**Comment by jmaslek** [comment]
Hey!  

Sorry for removing this on you.  Our options menu is in need of some refactoring in how we pass data around the terminal.  I intentionally dropped this function from the sdk to avoid some errors.

We will work on this post 2.0 release, but in the meantime, I can offer you an example script that generates this kind of plot:
(note that the chain contains all the data needed and can be used to create a stacked bar):

```
import seaborn as sns
import matplotlib.pyplot as plt
from openbb_terminal.sdk import openbb
chain = openbb.stocks.options.chains("AAPL",expiration="2022-12-02")
chain[["p_Openinterest","p_Volume"]] = chain[["p_Openinterest","p_Volume"]]*-1
fig,ax = plt.subplots()
sns.barplot(y="strike", x="c_Volume", data=chain, orient = "h", ax=ax, color="green")
sns.barplot(y="strike", x="p_Volume", data=chain, orient = "h", ax=ax, color = "red")
plt.show()
```

**Comment by JingyiHe99** [comment]
> 
Thank you for replying. I tried the code and the image is quite different than the example I put. When can the function be fixed?
![image](https://user-images.githubusercontent.com/119362053/204389486-d130ac21-c9f5-489b-b6c5-37d0c6dcdf1a.png)

**Comment by jmaslek** [comment]
So your example can be close to replicated with the following:

```
import seaborn as sns
import matplotlib.pyplot as plt
from openbb_terminal.sdk import openbb
chain = openbb.stocks.options.chains("AMZN",expiration="2022-12-02")
chain[["p_Openinterest","p_Volume"]] = chain[["p_Openinterest","p_Volume"]]*-1
chain["c_VOI"] = chain["c_Volume"]+chain["c_Openinterest"]
chain["p_VOI"] = chain["p_Volume"]+chain["p_Openinterest"]

chain = chain[(chain.strike<112) & (chain.strike > 82)]

fig,ax = plt.subplots()
sns.barplot(y="strike", x="c_VOI", data=chain, orient = "h", ax=ax, color="lightgreen")
sns.barplot(y="strike", x="p_VOI", data=chain, orient = "h", ax=ax, color = "pink")
sns.barplot(y="strike", x="c_Volume", data=chain, orient = "h", ax=ax, color="green")
sns.barplot(y="strike", x="p_Volume", data=chain, orient = "h", ax=ax, color = "red")
```

Just need to play with the axis labels (struggling to flip it while preparing the release)

Ideally we can have the wrapper to do so within a couple weeks.  Getting the options functions mapped is at the top of the backlog

**Comment by JingyiHe99** [comment]
> So your example can be close to replicated with the following:
> 
> ```
> import seaborn as sns
> import matplotlib.pyplot as plt
> from openbb_terminal.sdk import openbb
> chain = openbb.stocks.options.chains("AMZN",expiration="2022-12-02")
> chain[["p_Openinterest","p_Volume"]] = chain[["p_Openinterest","p_Volume"]]*-1
> chain["c_VOI"] = chain["c_Volume"]+chain["c_Openinterest"]
> chain["p_VOI"] = chain["p_Volume"]+chain["p_Openinterest"]
> 
> chain = chain[(chain.strike<112) & (chain.strike > 82)]
> 
> fig,ax = plt.subplots()
> sns.barplot(y="strike", x="c_VOI", data=chain, orient = "h", ax=ax, color="lightgreen")
> sns.barplot(y="strike", x="p_VOI", data=chain, orient = "h", ax=ax, color = "pink")
> sns.barplot(y="strike", x="c_Volume", data=chain, orient = "h", ax=ax, color="green")
> sns.barplot(y="strike", x="p_Volume", data=chain, orient = "h", ax=ax, color = "red")
> ```
> 
> Just need to play with the axis labels (struggling to flip it while preparing the release)
> 
> Ideally we can have the wrapper to do so within a couple weeks. Getting the options functions mapped is at the top of the backlog

Thank you! I still have a question about how to add the values of max pain and current stock price in this barplot.

**Comment by jmaslek** [comment]
You can add the current price by adding this to the above code:
```
from bisect import bisect_left
current_price = float(openbb.stocks.quote("AMZN").loc["Price"].values[0])
s = [float(strike.get_text()) for strike in ax.get_yticklabels()]
spot_index = bisect_left(s, current_price)  # find where the spot is on the graph
spot_line = ax.axhline(spot_index, ls="--", alpha=0.3)
```
The max pain calculation is not in a state where it is usable in the sdk, but if you had a function to calculate it, you would use that value in the code above.

Once again we will be working on adding this and is not in yet because it is not standardized across the different data sources.

**Comment by JingyiHe99** [comment]
chain = chain[(chain.strike<112) & (chain.strike > 82)]

Hi James,
Could you explain to me how to define the range (chain.strike<112) & (chain.strike > 82) when calculating max pain?

**Comment by jmaslek** [comment]
Hey!  Sorry to not follow up, but this command was added to the SDK in the last few updates :)
