### ISSUE TITLE
[Bug] Settings ENV file is in the installation folder, where it is read. It does not write to the same file

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3633]
I've reported this several times, most notably, **before and after each release**. 

The `/settings` are being written to a file they are not being read from.

Read: `~/Application/OpenBBTerminal/.OpenBB/.env`.

Write: `~/.openbb_terminal/.env`

It's a very annoying bug because users will never be able to properly adjust the `/settings` and `/featflags`. They will change it once, and then when they open the program next, it will be back to default.

![Screenshot 2022-11-28 at 3 05 06 PM](https://user-images.githubusercontent.com/85772166/204399659-5495e219-0759-4458-9152-0bdb930f49d2.png)

**Comment by montezdesousa** [comment]
@northern-64bit , @Chavithra do you see any problem with changing the priority for the .env files?

Rn, it is like this in the `terminal_controller.py` and `feature_flags.py`:
```
load_dotenv(USER_ENV_FILE)
load_dotenv(REPOSITORY_ENV_FILE, override=True)
load_dotenv(PACKAGE_ENV_FILE, override=True)
```

If we change it to:
```
load_dotenv(REPOSITORY_ENV_FILE, override=True)
load_dotenv(PACKAGE_ENV_FILE, override=True)
load_dotenv(USER_ENV_FILE, override=True)
```

The user .env changes `USER_ENV_FILE` will have priority over other the installer .env -> `PACKAGE_ENV_FILE`

This seems to be the issue right now, the `USER_ENV_FILE` is read but `PACKAGE_ENV_FILE` overrides it.

**Comment by northern-64bit** [comment]
> @northern-64bit , @Chavithra do you see any problem with changing the priority for the .env files?
> 
> Rn, it is like this in the `terminal_controller.py` and `feature_flags.py`:
> 
> ```
> load_dotenv(USER_ENV_FILE)
> load_dotenv(REPOSITORY_ENV_FILE, override=True)
> load_dotenv(PACKAGE_ENV_FILE, override=True)
> ```
> 
> If we change it to:
> 
> ```
> load_dotenv(REPOSITORY_ENV_FILE, override=True)
> load_dotenv(PACKAGE_ENV_FILE, override=True)
> load_dotenv(USER_ENV_FILE, override=True)
> ```
> 
> The user .env changes `USER_ENV_FILE` will have priority over other the installer .env -> `PACKAGE_ENV_FILE`
> 
> This seems to be the issue, the `USER_ENV_FILE` is read but `PACKAGE_ENV_FILE` overrides it with some defaults.

@montezdesousa, it looks like this should fix this. I don't see a problem with this, but I don't know much about the architecture of the installer.
