### ISSUE TITLE
[Bug] Installer Only - All reports fail to `import openbb_terminal.sdk` - An error was encoutered in cell [1] - 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3634]
Cell one is reporting: `AttributeError: module '__main__' has no attribute '__file__'`

The output of the report is attached for inspection.

[20221128_151415_economy.ipynb.zip](https://github.com/OpenBB-finance/OpenBBTerminal/files/10108284/20221128_151415_economy.ipynb.zip)

**Comment by deeleeramone** [comment]
![Screenshot 2022-11-28 at 3 22 17 PM](https://user-images.githubusercontent.com/85772166/204401495-95133412-d5ce-4027-9f2e-3ff3d832c41c.png)

**Comment by jmaslek** [comment]
The workaround was put out with 2.0.0.  Reports should be getting past the import cell
