### ISSUE TITLE
[Bug] `pip install` with native M1 fails to load iPython. Solution inside.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3635]
Conda with M1/ARM version installs all components successfully if:

- conda install -c conda-forge cvxpy
- conda install -c conda-forge lightgbm
- pip install openbb[all]

However, iPython fails to launch in a the Jupyter window of VS Code. 

![image](https://user-images.githubusercontent.com/85772166/204402469-06d15b9a-d23f-4bff-b4f3-06e38a0af492.png)

The solution was: 

![image](https://user-images.githubusercontent.com/85772166/204402496-7f93eea6-5612-49f0-a6e6-17306abcc73e.png)

**Comment by piiq** [comment]
@deeleeramone your screenshot shows that your ipython is using a different python environment. Can you please double check that you are using the correct jupyter kernel
![image](https://user-images.githubusercontent.com/11668535/204592748-8bf9d633-9fc1-47a1-a5ae-d4af8879da1b.png)

**Comment by piiq** [comment]
There is a drop down menu with environment selection where it says python 3.9.6. Click there to select the correct kernel

**Comment by deeleeramone** [comment]
It's the same kernel, I promise. Appears to be caching or something. For the first time, the kernel name in the environment changed to reflect the version of Python, but it still did not under the Python Environment Manager tab from which the Interactive shell was launched. 

![Screenshot 2022-11-30 at 7 42 06 PM](https://user-images.githubusercontent.com/85772166/204960724-7edde5c5-e020-4832-9f73-4a1bf0323c4a.png)
