### ISSUE TITLE
[Bug]`etf/ta/fib` - invalid value encountered in log10. majorstep_no_exponent = 10 ** (np.log10(majorstep) %1) - & chart weirdness

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3639]
Also, can't get seem to get a reasonable chart out of it. Below are non-adjusted outputs.

Autoscaling off DPI 300:

![Screenshot_20221128_083557](https://user-images.githubusercontent.com/85772166/204440020-2a24a8ef-ae52-40c1-bddd-a558c673bc01.png)

Autoscaling off DPI 72

![image](https://user-images.githubusercontent.com/85772166/204440523-50dfaf8b-6006-402f-a07a-f22672ba913b.png)

Autoscaling on:
pwidth 90
pheight 60

![Screenshot_20221128_083324](https://user-images.githubusercontent.com/85772166/204439640-3d692686-2212-4331-9e3d-a12930896073.png)

**Comment by colin99d** [comment]
I am not sure how to reproduce the log 10 issue, but Juan's new plotly fixes the charting issues. If there is still an error, feel free to reopen and let me know how to reproduce.
