### ISSUE TITLE
[Bug] `load` from `portfolio/po` is missing its examples files

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3640]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/46355364/204456324-7b4ffe44-b597-4eb6-9fa2-30661451e18f.png">

**Comment by montezdesousa** [comment]
Related to this https://github.com/OpenBB-finance/OpenBBTerminal/issues/3613
