### ISSUE TITLE
[Bug] `/dashboards/ $ forecasting` does not show anything

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#3644]
**Describe the bug**

`/dashboards/ $ forecasting` does not show anything and can't write anything else on the terminal - had to kill the terminal.

**To Reproduce**

```
dashboards
forecasting
```

**Screenshots**
![image](https://user-images.githubusercontent.com/48914296/204504206-a50bf6ba-1da9-46a2-914f-de23c34805a1.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Python/ git clone
- Python version [e.g. 3.9.6]

**Comment by deeleeramone** [comment]
I have also never been able to get this version of the dashboard to launch.

#3566 

#3464

**Comment by hjoaquim** [comment]
Thank you @deeleeramone !

**Comment by martinb-bb** [comment]
This is due to the terminal not being able to run the streamlit executable :( 

If you want to work on it `streamlit run forecast.py`

**Comment by jmaslek** [comment]
this still alive?

**Comment by martinb-bb** [comment]
@jmaslek This is fixed now. Closing!
