### ISSUE TITLE
[Bug] Reports don't work on `pip install openbb`

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#3645]
**Describe the bug**
Reports don't work on `pip install openbb`.

**To Reproduce**
```
reports
crypto --symbol BTC
equity --symbol AAPL
```

**Screenshots**

![image](https://user-images.githubusercontent.com/48914296/204510116-59cad459-1a78-450d-9b25-3f278c8671b2.png)

With `--debug` flag:

![image](https://user-images.githubusercontent.com/48914296/204510359-3ee73ffb-7da3-4a0e-acf7-e2e108a94521.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- `pip install openbb` and `pip install "openbb[all]"`
- Python version [e.g. 3.9.6]

**Comment by hjoaquim** [comment]
Reports do get generated and correct tho - it's just not opening it

**Comment by deeleeramone** [comment]
Does this still happen if you use a Miniconda3 environment instead of Anaconda3? There are dependency chain issues when Anaconda3 is solving the environment. I'll try to recreate this in a WSL2 Ubuntu environment.

**Comment by hjoaquim** [comment]
@deeleeramone this kept happening with Miniconda :cry:

**Comment by deeleeramone** [comment]
I got an error, in cell 16, after running, `equity --symbol AMZN`, with WSL2/Win11 installation that has otherwise been working great:

```
Attribute Error: `if target in df_analyst columns: 'list' object has no attribute 'columns'`


Error: "None of ['date'] are in the columns"

```
