### ISSUE TITLE
[IMPROVE] SDK - method to print/get SDK version 

### ISSUE THREAD

**Issue by jczernia** [OpenBB-finance/OpenBBTerminal#3646]
**What's the feature that should be improved?**
Taking into consideration more releases are on the roadmap sanity check which get the SDK version used would be helpful for SDK users. Something like openbb.get_version() which will return the string would be perfect

**Comment by jmaslek** [comment]
You can now do `openbb.__version__` to get the version.  If you run pip, you can also check from `pip list|grep openbb`
