### ISSUE TITLE
[Bug] Charts not showing on docker

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#3647]
**Describe the bug**

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**

![image](https://user-images.githubusercontent.com/48914296/204537366-28e43a2b-a4c3-4bb4-afd1-60acc9bb09e8.png)

On running the instructions on the **[X-Server on Linux Desktop](https://docs.openbb.co/terminal/quickstart/installation?tab=docker)** section:

![image](https://user-images.githubusercontent.com/48914296/204537657-9a76d87d-6224-43bc-81f1-a8c84c8e794b.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Docker image

**Comment by Chavithra** [comment]
> @Chavithra tested for Win and same thing happens.

We merge a fix that should work on windows.

@Lukazcreations testing on M1 Mac.

**Comment by Chavithra** [comment]
Charts are now working on macOS and Windows.
Ubuntu still need to to fix

**Comment by colin99d** [comment]
@henriqueio did Juan's new PR fix this?

**Comment by jiiiijiij** [comment]
did it fix now ? on linux ?

**Comment by andrewkenreich** [comment]
Closing this as we have fixed issue here on the new version - This is related to an older version of docker now.

@jiiiijiij if you have issues still let us know.

https://github.com/OpenBB-finance/OpenBBTerminal/issues/4872
