### ISSUE TITLE
[IMPROVE] create flatpak flathub release

### ISSUE THREAD

**Issue by ghtesting2020** [OpenBB-finance/OpenBBTerminal#3651]
**What's the feature that should be improved?**
No "official" release for Linux besides docker. Not everyone runs docker. Out of the 3 main packaging methods on Linux (flatpaks, snaps and appimages) flatpaks are the most widely used and acceptable. Snaps being mostly limited to Ubuntu and garbage. Appimages have their own major problems. Flatpaks have their own problems but it is the best of the 3.

**Describe how you would like the feature improved**
Provide a flatpak release on flathub.

**Possibly describe the ideal way to improve this**
Provide a flatpak release on flathub.

**Additional information**
https://flathub.org/home
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by hjoaquim** [comment]
Hello @ghtesting2020, thanks for the input! 
Why not using `pip install openbb`? I'm using that on my Ubuntu and works like a charm!

**Comment by wiki-me** [comment]
Was this actually created? I don't see anything here or on flathub.
