### ISSUE TITLE
[Bug]/keys/oanda throws Error: str expected, not NoneType

### ISSUE THREAD

**Issue by 4x** [OpenBB-finance/OpenBBTerminal#3659]
**Cannot add Oanda api key**

**To Reproduce**
`/keys/oanda my-api-key-0123456789`

**Returns**
```
The following args couldn't be interpreted: ['my-api-key-0123456789']
Error: str expected, not NoneType
```

**Desktop (please complete the following information):**
- OS: Windows 11
- OpenBB Terminal 2.0.0 installed today 2022-11-29

**Additional context**
I was able to add api keys for other sources such as polygon and alphavantage.
Also, I know for a fact that my Oanda api key works (elsewhere).

**Comment by jmaslek** [comment]
Since oanda takes multiple values, we have it so that they all need to be passed

```
/keys/oanda -a ACCOUNT_NUMBER -t ACCOUNT_TOKEN -at LIVE
```
