### ISSUE TITLE
[Bug] `economy/ycrv` is broken and has issues giving data from other countries

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3670]
No data is given for `ycrv`, see:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/204995807-7586a38e-85a2-4909-8b4b-9112cd3c465f.png">

Also, we list that it is possible to provide other countries which is false. This is due to the fact functionality from Investing.com no longer works and that is still baked into the command.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/204995922-8904280d-e485-4ff1-ab89-8e6214b530ba.png">

**Comment by deeleeramone** [comment]
Looking at the raw data shows that the Rate column is returning all NaN values, and the date is November 24 for some reason. This defaults normally to be today.

```console
(🦋) /economy/ $ ycrv --raw

United States Yield Curve for 2022-11-24
┏━━━━━━━━━━┳━━━━━━┓
┃ Maturity ┃ Rate ┃
┡━━━━━━━━━━╇━━━━━━┩
│ 0.083    │ nan  │
├──────────┼──────┤
│ 0.250    │ nan  │
├──────────┼──────┤
│ 0.500    │ nan  │
├──────────┼──────┤
│ 1.000    │ nan  │
├──────────┼──────┤
│ 2.000    │ nan  │
├──────────┼──────┤
│ 3.000    │ nan  │
├──────────┼──────┤
│ 5.000    │ nan  │
├──────────┼──────┤
│ 7.000    │ nan  │
├──────────┼──────┤
│ 10.000   │ nan  │
├──────────┼──────┤
│ 20.000   │ nan  │
├──────────┼──────┤
│ 30.000   │ nan  │
└──────────┴──────┘
``` 

Adding a date prints one warning message per maturity. 

```console
ycrv --date 2022-12-01

fred.py:142: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return pd.Series(data)
```

**Comment by jmaslek** [comment]
im on it.  although note that using --date = today wont work because fred lags 1 (2?) days
