### ISSUE TITLE
[IMPROVE] Volatility charts and analysis for different options and futures and consecutive expiry dates

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3672]
Request on Linkedin:

![Screenshot 2022-12-01 at 12 05 29](https://user-images.githubusercontent.com/25267873/205048547-9226eb87-f29b-46a4-b2fa-e765af614188.png)

**Comment by jmaslek** [comment]
can you be a little more specific?
