### ISSUE TITLE
[IMPROVE] fred search should allow multiple words

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3674]
In general, when searching for a term we should allow spaces

**Comment by deeleeramone** [comment]
I know this isn't what you refer to, but it is possible use multiple keywords with: `+` and `&`. Phrases, however, are not.

```
fred --query raw+materials+tobacco
fred --query raw+materials&steel
```

This also works for `news`.

**Comment by jmaslek** [comment]
please make issues for any others.  We took out all the nargs = "+" when we decided countries should be comma separated with "_" in between words.
