### ISSUE TITLE
[Bug] When the portfolio exists for less than a year, the yearly return is wrong

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3678]
I've designed an example portfolio that only has trades for **this year**. Then, when I compare the result between `yret` and `perf` it's off. This shouldn't be the case but it seems like our calculation of `yret` is off here.

![image](https://user-images.githubusercontent.com/46355364/205105386-c19e09e3-c205-423e-9d3d-a03e4d163540.png)

Use this example portfolio: [Issue_Demonstration.xlsx](https://github.com/OpenBB-finance/OpenBBTerminal/files/10134128/Issue_Demonstration.xlsx) (put it into `OpenBBUserData/portfolio/holdings`)

Manual calculation to verify:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/46355364/205142242-680a7439-c669-4507-ab58-90797c2f0a17.png">

There is a definition question here at play and we need to look into it.

**Comment by northern-64bit** [comment]
The issue is that `yret` just returns the total return of the holdings. Thus buying price and fees won't affect it. The `perf` command takes all of these things into account.
