### ISSUE TITLE
[IMPROVE] stocks/ba/interest should allow sentences

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3683]
I should be able to check interest on word "open source" against price of an open source company for instance.

FYI @jmaslek

**Comment by jmaslek** [comment]
Already addressed in my big fixes.

Although instead of open source I used tomato soup.  I don't even like tomato soup.

**Comment by DidierRLopes** [comment]
Will close then! Thanks!
