### ISSUE TITLE
[IMPROVE] '-' arguments with more than one letter

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#3687]
@deeleeramone noted this:
"If I am remembering correctly, there was a previous effort to clean up all arguments, terminal-wide, so that - are assigned to only single letters; and arguments which can't reasonably be abbreviated as one letter should convert to being only -- with the full argument name. I'm pretty sure there was a specific reason for this, argparse-related, but it was a little while back."

![image](https://user-images.githubusercontent.com/79287829/205283370-c451b7e8-ff58-496f-abc4-5736399332af.png)

**Comment by jmaslek** [comment]
Yes!  The reasoning is that if I have something that is `-ab` it actually treats it as `-a -b` which can be problematic.
