### ISSUE TITLE
[IMPROVE] why openBB shows Bloomberg news 

### ISSUE THREAD

**Issue by qmarsun** [OpenBB-finance/OpenBBTerminal#3693]
**What's the feature that should be improved?**
Typing news shows all the Bloomberg news. what is the point of showing Bloomberg news

**Describe how you would like the feature improved**
Do not show Any Bloomberg news. Find a way to get from other source. That's one way to prove
openBB is better alternative to Bloomberg. 
--------------

2022 Dec 03, 19:23 (🦋) / $ news

Fetching data. Please be patient

> 2022-12-03 23:57:15+00:00 - FTX Investors Sue Celebrities, Border Policy Suit - Bloomberg
https://news.google.com/__i/rss/rd/articles/CBMiaGh0dHBzOi8vd3d3LmJsb29tYmVyZy5jb20vbmV3cy9hdWRpby8yMDIyLTEyLTAzL2Z0eC1pbnZlc3RvcnMtc3VlLWNlbGVicml0aWVzLWJvcmRlci1wb2xpY3ktc3VpdC1wb2RjYXN00gEA?oc=5

> 2022-12-03 21:22:06+00:00 - Ackman Says Recent Comments on Bankman-Fried Were Misinterpreted - Bloomberg
https://news.google.com/__i/rss/rd/articles/CBMic2h0dHBzOi8vd3d3LmJsb29tYmVyZy5jb20vbmV3cy9hcnRpY2xlcy8yMDIyLTEyLTAzL2Fja21hbi1zYXlzLXJlY2VudC1jb21tZW50cy1vbi1iYW5rbWFuLWZyaWVkLXdlcmUtbWlzaW50ZXJwcmV0ZWTSAQA?oc=5

> 2022-12-03 21:01:37+00:00 - Russia-Ukraine Latest News: December 3, 2022 - Bloomberg
https://news.google.com/__i/rss/rd/articles/CBMib2h0dHBzOi8vd3d3LmJsb29tYmVyZy5jb20vbmV3cy9hcnRpY2xlcy8yMDIyLTEyLTAzL3VrcmFpbmUtbGF0ZXN0LXJ1c3NpYS1wcmVzc2luZy1zeW1ib2xpYy1hc3NhdWx0LW5lYXItYmFraG11dNIBAA?oc=5

> 2022-12-03 21:00:00+00:00 - Investment Grade New Deals Likely Busy Sector Next Week - Bloomberg
https://news.google.com/__i/rss/rd/articles/CBMiamh0dHBzOi8vd3d3LmJsb29tYmVyZy5jb20vbmV3cy9hcnRpY2xlcy8yMDIyLTEyLTAzL2ludmVzdG1lbnQtZ3JhZGUtbmV3LWRlYWxzLWxpa2VseS1idXN5LXNlY3Rvci1uZXh0LXdlZWvSAQA?oc=5

> 2022-12-03 21:00:00+00:00 - Bonds Rallying Back From Brutal Year Show Power of Higher Rates - Bloomberg
https://news.google.com/__i/rss/rd/articles/CBMif2h0dHBzOi8vd3d3LmJsb29tYmVyZy5jb20vbmV3cy9hcnRpY2xlcy8yMDIyLTEyLTAzL2JvbmRzLXJhbGx5aW5nLWJhY2stZnJvbS1icnV0YWwteWVhci1zaG93LXBvd2VyLW9mLWhpZ2hlci1yYXRlcz9zcm5kPXByZW1pdW3SAQA?oc=5

2022 Dec 03, 19:23 (🦋) / $

**Comment by JerBouma** [comment]
Bloomberg News is a massive media outlet, why do you suggest not showing this information? Do note that Bloomberg Terminal and Bloomberg News are not the same thing.

**Comment by qmarsun** [comment]
**Let me set my baseline.**
 I have great respect for Richard Stallman and Linus Torvalds for their contribution to world as open source.
 Same way its great that what openBB is trying to do for world.
 
**My argument:**
Tag line for openBB is that BB charging xx amount etc.. so you can get free from openBB correct?.
Please note  that free Bloomberg news only possible 
if they were able to sell the terminals.  So selling the terminals is contribute to free news.
in fact terminals was started first then news came latter with money made from terminals.

if openBB tag line is against BB terminal at xx amount then its not right to use their free news.

**Conclusion:**
Its great effort what openBB is trying do. I want/prefer openBB shows the strength by features/functionality of product by itself not have any reference to Bloomberg.

**Comment by JerBouma** [comment]
Hi @qmarsun,

The purpose of the OpenBB product and the nature of it, is the full range of customizability. Limiting the scope just because the Bloomberg Terminal itself resides in the same industry would go against the company's nature. Besides that, Bloomberg News is very much possible without the Bloomberg Terminals, it's a completely separate product. Find the subscription to their news channels [here](https://www.bloomberg.com/subscriptions).

If a user would prefer to use Bloomberg News as its news source, we want them to be able to do so as we want people to have the freedom to decide on what they like. Similarly, Apple would also not exclude Microsoft Office on their MacBooks even though it's owned by Microsoft which is their direct competitor.

**Comment by qmarsun** [comment]
This is issue is closed. My final comments
I really like definition of openBB. yes. This is the way to go. No complain about other products and their cost. OpenBB stand itself by their strength. Great.
--------
WHY OPENBB?
OpenBB is a leading open source investment research software platform for accessing and analyzing financial market data.
We represent millions of investors who want to leverage state-of-the-art data science and machine learning technologies to make sense of raw unrefined data. Our mission is to make investment research effective, powerful and accessible to everyone.
--------------------------
[JerBouma](https://github.com/JerBouma)
FYI : Apple and Microsoft deal .
https://www.cnbc.com/2017/08/29/steve-jobs-and-bill-gates-what-happened-when-microsoft-saved-apple.html
