### ISSUE TITLE
[Bug] Reports - `equity` report hangs after creating the file, must `ctrl-c` to break

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3696]
Running `reports/equity --symbol AAPL`, everything executes and the files are created; however, it hangs after launching the finished report as HTML.

![Screenshot 2022-12-03 at 8 44 47 PM](https://user-images.githubusercontent.com/85772166/205475282-e30eb334-0ffe-4b32-b215-d4ed85b1d202.png)

The last line of the traceback:

```
File "/Users/danglewood/GitHub/GST1/miniconda3/envs/obbx86/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by jmaslek** [comment]
imma guess you don't get this still?

**Comment by deeleeramone** [comment]
Correct,  on to new and exciting issues.

![Screenshot 2023-03-17 at 11 30 55 PM](https://user-images.githubusercontent.com/85772166/226089503-263db7bd-15fc-4bfc-b66a-ac4573a10c4b.png)

![Screenshot 2023-03-17 at 11 32 20 PM](https://user-images.githubusercontent.com/85772166/226089539-c985d651-fe33-47f8-9234-c6628f53b9d4.png)
