### ISSUE TITLE
[FR] SDK - ETF module is missing `pir` and `compare`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3697]
`compare` is a fast way to create a multi-ticker table like the screener, but using lists. `pir` is a natural companion to the ETF screener.

**Comment by JerBouma** [comment]
For `pir`, I'd suggest that this remains within the Jupyter Notebook and not export an Excel file (unless specified). This can be achieve with `collect_data` from `pir` that curates data from Yahoo Finance.
