### ISSUE TITLE
[Bug] Adjust notation of numbers in income statements in the automated reports

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3703]
Adjust the notation of the numbers in the income statements? Do not use scientific notation

**Comment by colin99d** [comment]
<img width="2519" alt="Screenshot 2023-05-24 at 4 01 47 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/72827203/fdf3ed32-cf63-4249-99bd-3a6907fc36c9">
It looks like scientific notation is no longer used, I am going to go ahead and close this.
