### ISSUE TITLE
[Bug] Stocks/TH/exchange: bursa_model.py:39: FutureWarning: The frame.append method is deprecated. Use pandas.concat instead.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3707]
Non critical but will eventually stop working. Use any exchange for: `/stocks/th/exchange`

```console
OpenBBTerminal/openbb_terminal/stocks/tradinghours/bursa_model.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
```

**Comment by deepgohil** [comment]
I would like to take this up. As this will be my first contribution to this repo. if you can guide me it will be very helpful

**Comment by deepgohil** [comment]
@deeleeramone I would like to take this up. As this will be my first contribution to this repo. if you can guide me it will be very helpful

**Comment by deeleeramone** [comment]
Happy to help where I can, which aspect are you looking for guidance on?
