### ISSUE TITLE
[Bug] When exporting without declaring a filename, the source code path is used in the filename and this contains an extra `.`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3715]
Exporting a file without declaring the filename was creating the files with the terminal menu and function, but it is now using the path of the installation folder instead. This adds an extra `.`, which is undesirable, and can also make for a really long file name.

`/OpenBBUserData/exports/20221205_091629_.OpenBB_openbb_terminal_load.csv`

**Comment by deeleeramone** [comment]
You can tell by the path, but this is the installer version.

**Comment by simmonsj330** [comment]
@deeleeramone what command did you run to produce this error?
