### ISSUE TITLE
[Bug] on equity.ipynb

### ISSUE THREAD

**Issue by tinix84** [OpenBB-finance/OpenBBTerminal#3728]
**Describe the bug**
df_analyst = openbb.stocks.dd.analyst(symbol=symbol) report None obj.
print(df_analyst.columns) report Error: "None of ['date'] are in the columns"

**To Reproduce**
launch openbb_terminal/reports/templates/equity.ipynb

**Screenshots**
![image](https://user-images.githubusercontent.com/16301528/206305783-93f568a7-474b-4727-b697-3e7d4e8f6642.png)

**Desktop (please complete the following information):**

- OS: WLS2
- Python version 3.9

**Additional context**
Add any other information that you think could be useful for us.

**Comment by jmaslek** [comment]
Hey this is the same as in #3713.

I submitted a PR into the finviz repo that would fix this.  Not sure what the timeline would be for that to be merged in.
