### ISSUE TITLE
[Bug] Stocks/FA --source Polygon: `cash` returns over 100 columns when limit is only `20` & other strange behaviour

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3738]
ticker = `KO`
source = `Polygon`

Financial statements are being returned properly from Polygon. From default settings, `cash` returns seventeen years with bad column names, and `balance` fetches only five years. 

(🦋) /stocks/fa/ $ cash --source Polygon

![Screenshot 2022-12-08 at 8 14 31 PM](https://user-images.githubusercontent.com/85772166/206622655-ec6c5eb0-0856-4e17-aacc-d1bcb2e8f9e7.png)

(🦋) /stocks/fa/ $ balance --source Polygon

![Screenshot 2022-12-08 at 8 17 39 PM](https://user-images.githubusercontent.com/85772166/206622996-87c0d5c8-8873-4ffb-9dca-eebe1a1916f1.png)

Increasing the `limit` to `20` for `balance` presents the rows in a different order, and only eleven years of records.

![Screenshot 2022-12-08 at 8 12 51 PM](https://user-images.githubusercontent.com/85772166/206622442-6121b2ef-2de0-4316-924d-c6c577e2e5ac.png)

Then things really go screwy when the same limit is applied to `cash`, over 100 columns are returned....

![Screenshot 2022-12-08 at 8 22 28 PM](https://user-images.githubusercontent.com/85772166/206623737-e5635b34-d496-4203-99cf-6295b6bba874.png)

**Comment by jmaslek** [comment]
#3809 takes care of the cash issues.  The balance row ordering is done on polygons end, not ours.  Note their fundamentals are still experimental and the 11 years are the max we get from the api request so can't do anything about getting more.
