### ISSUE TITLE
[Bug] Vomma is not correct. Copied from Vanna

### ISSUE THREAD

**Issue by CarloLepelaars** [OpenBB-finance/OpenBBTerminal#3749]
**Describe the bug**
The formula for Vomma is exactly the same as that for Vanna. 
The output for Vanna is correct, but wrong for Vomma.

This function for Vomma was probably copied over from Vanna and then not implemented. Are there any tests for Option Greeks available in `OpenBB`?

Reference: https://github.com/OpenBB-finance/OpenBBTerminal/blob/fb667ce867d07a39076b158a2aeef8504543920d/openbb_terminal/stocks/options/op_helpers.py#L376

**To Reproduce**
```python
from openbb_terminal.stock.options import Option
test_S = 55.0 
test_K = 50.0
test_T = 365 
test_r = 0.0025 
test_sigma = 0.15
opt = Option(s=test_S,
                 k=test_K,
                 rf=test_r,
                 div_cont=0.,
                 expiry=test_T,
                 vol=test_sigma, opt_type=1)
print(opt.Vanna(change=1.)) ## -1.1782993        
print(opt.Vomma(change=1.)) ## Should be 47.1186994, but getting -1.1782993
```

- Python version [e.g. 3.10]

**Comment by jmaslek** [comment]
Nice catch! Yes this appears to just have been copies directly over.  We do not have any tests yet for this part, but we are aiming to increase our coverage throughout, so this will eventually get some needed attention.
