### ISSUE TITLE
[IMPROVE] `portfolio` and `portfolio.po` functions should use the same portfolio object

### ISSUE THREAD

**Issue by dmitri-b** [OpenBB-finance/OpenBBTerminal#3751]
**What's the feature that should be improved?**
I expect the same excel template that I use for the portfolio functions, like the drawdown or returns to also work with the portfolio optimizer. The following columns that are in the ordinary portfolio table should also work to optimise this portfolio:
```
Date	Ticker	Type	Sector	Industry	Country	Price	Quantity	Fees	Premium	Investment	Side	Currency	Region
```

**Describe how you would like the feature improved**
There should be a single portfolio object type that can be used across all subpackages of openbb, with the same associated excel template

**Possibly describe the ideal way to improve this**
Some refactoring is needed to merge the two object together

**Additional information**
Unhelpfully, the optimisation functions return an empty dataframe when called on a portfolio loaded from the other template.

![image](https://user-images.githubusercontent.com/27496678/206861060-a9d2019e-8c77-4237-a1bc-6ea53dc2e2fc.png)

**Comment by montezdesousa** [comment]
Hi @dmitri-b, thanks for your feedback. 

100% agreed, we are aware of this issue and will work on fixing it, meanwhile you can take a look at some usage examples here: https://docs.openbb.co/sdk/reference/portfolio/po
