### ISSUE TITLE
Not able to run "docker compose run openbb" successfully

### ISSUE THREAD

**Issue by pynixis** [OpenBB-finance/OpenBBTerminal#3760]
**Describe the bug**
After pulling down the images by running "curl -o docker-compose.yaml https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.yaml" Then, I run "docker compose run openbb"

I get the following message error message:
Traceback (most recent call last):
  File "/home/python/terminal.py", line 2, in <module>
    from openbb_terminal import terminal_controller
  File "/home/python/openbb_terminal/terminal_controller.py", line 26, in <module>
    from openbb_terminal import feature_flags as obbff
  File "/home/python/openbb_terminal/feature_flags.py", line 20, in <module>
    paths_helper.init_userdata()
  File "/home/python/openbb_terminal/core/config/paths_helper.py", line 75, in init_userdata
    create_paths(dirs_list)
  File "/home/python/openbb_terminal/core/config/paths_helper.py", line 27, in create_paths
    dirs.mkdir(
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/python/OpenBBUserData/styles'

I am running the command as root.

- Ubuntu server with docker installed.
- python3/jammy-updates,now 3.10.6-1~22.04 amd64 [installed,automatic]

**Comment by pynixis** [comment]
I tried creating a bash script with the following two lines in it:

curl -o docker-compose.yaml https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.yaml
docker compose run openbb


based on the following documentation for Linux:
https://docs.openbb.co/terminal/quickstart/installation

**Comment by ebaschiera** [comment]
Why did you close this issue? How did you fix the problem? I am having the same issue on 2 different PCs with v2.1.0.
Thanks.

**Comment by aaronsgithub** [comment]
I'm also having this issue on WSL2 Ubuntu 22.04
