### ISSUE TITLE
[Bug] Permissions issue inside Docker container

### ISSUE THREAD

**Issue by djl0** [OpenBB-finance/OpenBBTerminal#3763]
Crash when attempting to run via docker container 2.0.0 with:

```Traceback (most recent call last):
  File "/home/python/terminal.py", line 2, in <module>
    from openbb_terminal import terminal_controller
  File "/home/python/openbb_terminal/terminal_controller.py", line 26, in <module>
    from openbb_terminal import feature_flags as obbff
  File "/home/python/openbb_terminal/feature_flags.py", line 20, in <module>
    paths_helper.init_userdata()
  File "/home/python/openbb_terminal/core/config/paths_helper.py", line 75, in init_userdata
    create_paths(dirs_list)
  File "/home/python/openbb_terminal/core/config/paths_helper.py", line 27, in create_paths
    dirs.mkdir(
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/python/OpenBBUserData/styles'```


- OS: Ubuntu

**Comment by djl0** [comment]
Sorry, I think it was local permissions issue... my bad.

**Comment by hjoaquim** [comment]
Thank you, @djl0 feel free to re-open if necessary!

**Comment by alvarocleite** [comment]
Hi @djl0,

I'm having exactly the same error, can you tell us how do you solved it?

**Comment by alvarocleite** [comment]
I guess I found the problem:

This docker image creates two directories in the home directory:
- .openbb_terminal
- OpenBBUserData

The problem can be related to the ownership, the user or the group

I solved my problem using the chown command

```console
$cd ~

$sudo chown -R $USER:wheel OpenBBUserData

$sudo chown -R $USER:wheel .openbb_terminal
```

**Comment by hjoaquim** [comment]
Thanks for sharing @alvarocleite

**Comment by jsr-p** [comment]
@alvarocleite did not work for me. 
However, 
```bash
cd ~
sudo chown -R $USER OpenBBUserData
sudo chown -R $USER .openbb_terminal
```
worked :smiley:

**Comment by jiiiijiij** [comment]
I think the problem was caused by docker installing in the wrong direction. After install I don't have 2 openbb folders in my user home but instead in my root folder. And now I don't even know where openbb was installed. 

I hope the team able to finish the appimage so we can get most pip and docker install problem closed

**Comment by roniesha1994** [comment]
I'm having a hard time coding.been a hassle especially with little
knowledge I'm sorry you guys I've been the delay.if anyone can help me
out/code it for me I would really appreciate it please

**Comment by inot12** [comment]
Experienced this with latest image (OpenBB Terminal v3.2.3).
[openbbterminal]$ sudo docker image inspect ghcr.io/openbb-finance/openbbterminal/openbb
[
{
"Id": "sha256:b0851365c6dc59ce81914b909204bff45f54953a40c3131ba693b47413e34e09",
"RepoTags": [
"ghcr.io/openbb-finance/openbbterminal/openbb:latest"
],
"RepoDigests": [
"ghcr.io/openbb-finance/openbbterminal/openbb@sha256:f688627f8b7ff3f9fe19bf9ff56ebc8a16b23eb83063197092ff289571e1d156"
],
"Parent": "",
"Comment": "buildkit.dockerfile.v0",
"Created": "2023-10-04T17:15:35.964038137Z",
...
]
Solved it by modifying the docker-compose.yaml.
[openbbterminal]$ diff docker-compose-original.yaml docker-compose.yaml
7,8c7,8
<       - ~/OpenBBUserData:/home/python/OpenBBUserData
<       - ~/.openbb_terminal:/home/python/.openbb_terminal
---
>       - ~/OpenBBUserData:/home/$USER/OpenBBUserData
>       - ~/.openbb_terminal:/home/$USER/.openbb_terminal
