### ISSUE TITLE
[Bug] `ETF` When the ETF is not US-listed, holdings and other info are lost, despite being available from YahooFinance.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3765]
When loading an ETF from outside of the US, data is not returning:

```
(🦋) /etf/ $ load EXSA.MI

No company holdings found!
```

Looking at YahooFinance shows there are holdings listed:

https://ca.finance.yahoo.com/quote/EXSA.MI/holdings?p=EXSA.MI

![Screenshot 2022-12-12 at 9 44 25 AM](https://user-images.githubusercontent.com/85772166/207116590-c4be50ae-d199-4370-a557-18be1181afc5.png)

`/etf/load exsa.mi/summary`

![Screenshot 2022-12-12 at 9 36 18 AM](https://user-images.githubusercontent.com/85772166/207114641-213cdee3-4c08-42d0-b7c1-bd07e974e205.png)

From `/stocks/load exsa.mi/fa/info`

![Screenshot 2022-12-12 at 9 35 11 AM](https://user-images.githubusercontent.com/85772166/207114421-31dfd034-ccbc-4a13-901e-63df1b861b59.png)

**Comment by jmaslek** [comment]
Holdings are obtained from stockanalysis since that provides up to 200.

If we add in yf then we get complaints that only 10 are showing.  Its a zero sum game with this.

**Comment by deeleeramone** [comment]
Note that Stock Analysis does not provide results for non-US ETFs or Stocks.

**Comment by colin99d** [comment]
I am going to move this to a feature request.

**Comment by deeleeramone** [comment]
If we're gonna go that route, then let's enhance the functionality by adding better data:

https://site.financialmodelingprep.com/developer/docs/#Historical-ETF-Holdings-available-dates
