### ISSUE TITLE
[Bug] `stocks/ba/popular` - Function breaks the terminal

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3784]
/stocks/ba/popular

The terminal has to be forced out with a keyboard interrupt. 

```
(🦋) /stocks/ba/ $ popular

/Users/danglewood/GitHub/GST1/miniconda3/envs/obbx86/lib/python3.10/site-packages/psaw/PushshiftAPI.py:192: UserWarning: Got non 200 code 404
  warnings.warn("Got non 200 code %s" % response.status_code)
/Users/danglewood/GitHub/GST1/miniconda3/envs/obbx86/lib/python3.10/site-packages/psaw/PushshiftAPI.py:180: UserWarning: Unable to connect to pushshift.io. Retrying after backoff.
  warnings.warn("Unable to connect to pushshift.io. Retrying after backoff.")
  ```

**Comment by jmaslek** [comment]
Looks like pushshift is broken

<img width="1180" alt="Screenshot 2022-12-15 at 11 36 13 AM" src="https://user-images.githubusercontent.com/18151143/207916935-44ec9462-aea2-4eac-bc9e-eee5cfefc0af.png">

**Comment by jmaslek** [comment]
Looks like a month later pushshift is still down.  Will likely need to deprecate this function until someone adds a different reddit api.

**Comment by montezdesousa** [comment]
I was putting a timeout here https://github.com/OpenBB-finance/OpenBBTerminal/pull/3999, do you prefer to deprecate?

**Comment by jmaslek** [comment]
Have you gotten this specific function to work or does it just timeout?

**Comment by montezdesousa** [comment]
> Have you gotten this specific function to work or does it just timeout?

Just timeout, but looking at this https://github.com/dmarx/psaw/issues/107 it might really need to use a different reddit api

**Comment by montezdesousa** [comment]
Fix here https://github.com/OpenBB-finance/OpenBBTerminal/pull/3999
