### ISSUE TITLE
[Bug] Portfolio/Load - CASH is not a supported type

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3790]
Recreate by trying to add cash to any portfolio template file.

**Comment by jmaslek** [comment]
duplicate #3584

**Comment by deeleeramone** [comment]
my bad! I suppose as a relevant update, it's not crashing it; fails to load properly. 

![Screenshot 2022-12-15 at 12 35 38 PM](https://user-images.githubusercontent.com/85772166/207961684-51132dc7-8d9c-490c-bec8-2d209cecda75.png)

```
(🦋) /portfolio/ $ holdv

Error: 'End Value'

(🦋) /portfolio/ $ summary -p 3m

Error: at least one array or dtype is required

```

**Comment by deeleeramone** [comment]
This has not been resolved. Cash is not a support Type.
