### ISSUE TITLE
[Bug] `stocks/load` Concatenation error while loading a ticker

### ISSUE THREAD

**Issue by kjura** [OpenBB-finance/OpenBBTerminal#3796]
**Describe the bug**
Python message shows up stating the following error "Error: can only concatenate str (not "NoneType") to str"

**To Reproduce**
1. Type in the terminal: "openbb"
2. Type "stocks"
3. Type "load AAPL" or "load AMZN" or "load TSLA" (or any other ticker I suppose)
4. Python error message should show up

**Screenshots**
![bugConcatError](https://user-images.githubusercontent.com/30084359/208255816-fd764f8b-5f1d-41e3-94b2-da6cee7bd228.png)
![debugFlag](https://user-images.githubusercontent.com/30084359/208255892-166b0dd0-adb4-4a18-8d69-6cd5bafca41e.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 21.10
- Python version: 3.9.15
- Conda: 4.12.0

**Additional context**
This error started to appear today, i.e Saturday December 17, 2022, CET,  couple of days before there was no such behaviour, I stumbled upon this while I was investigating the cause of #3752 
Commit: fb667ce86

**Comment by jmaslek** [comment]
Looks like this is an issue with yahoo changing up their api.

There is currently a yfinance issue tracking the issue.

**Comment by deeleeramone** [comment]
Looks like this impacts all tickers.

```console
(🦋) /stocks/ $ load rnlsy

Loading Daily data for RNLSY with starting period 2019-12-13.
Error: can only concatenate str (not "NoneType") to str


(🦋) /stocks/ $ load spx


1 Failed download:
- SPX: No data found for this date range, symbol may be delisted

(🦋) /stocks/ $ load spy

Loading Daily data for SPY with starting period 2019-12-13.
Error: can only concatenate str (not "NoneType") to str


(🦋) /stocks/ $ load spy

Loading Daily data for SPY with starting period 2019-12-13.
Error: can only concatenate str (not "NoneType") to str


(🦋) /stocks/ $ load spy --source Polygon

Loading Daily data for SPY with starting period 2019-12-13.
Error: can only concatenate str (not "NoneType") to str
```

**Comment by kjura** [comment]
> Looks like this is an issue with yahoo changing up their api.
> 
> There is currently a yfinance issue tracking the issue.

This one? https://github.com/ranaroussi/yfinance/issues/1246

From the discussion it seems that they have deliberately decided to encode the data

**Comment by jmaslek** [comment]
Yup.  The current workaround will be to select another source

**Comment by deeleeramone** [comment]
that is not working either, as illustrated above. SDK `stocks.load` works as expected. 

![Screenshot 2022-12-17 at 11 29 18 AM](https://user-images.githubusercontent.com/85772166/208263212-ef2f77bd-ffa0-4b79-bd31-4b4a9b0b74ef.png)

**Comment by jmaslek** [comment]
Looking at it -- I think the additional stats are what are breaking.  Seems like the download still works.

Do options and futures still work?

**Comment by deeleeramone** [comment]
Futures, yes. Options, nope:

```console
(🦋) /stocks/options/ $ chains --source YahooFinance

Error: float() argument must be a string or a real number, not 'NoneType'

Error: 'list' object has no attribute 'fillna'
```

**Comment by jmaslek** [comment]
Will need to dig but my guess is options not working because it requires getting the last price from ticker.info which is what seems to be breaking.

**Comment by ValueRaider** [comment]
We've fixed the encoding problem, users testing fix now.

> getting the last price from ticker.info

This is a great way to get blocked by Yahoo's spam detector. Use `Ticker.history(period="1d")` instead. I have no association with this project so will leave to you to fix.

**Comment by deeleeramone** [comment]
So it appears that this issue is resolved with a yFinance version bump:

`pip install yfinance==0.1.93`

**Comment by jmaslek** [comment]
#3801 should fix this.  Updates coming in the next day or so

**Comment by PrayingMantis99** [comment]
> So it appears that this issue is resolved with a yFinance version bump:
> 
> `pip install yfinance==0.1.93`

Nice!! Thx you!! Works!!
