### ISSUE TITLE
[Bug] `openbb.economy.gdpc_chart` displays real GDP and not nominal GDP

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3805]
It is not clear that you are looking at **real** Gross Domestic Product instead of **nominal**. Generally, when we refer to GDP we refer to nominal and not real.

Looking at this Tweet we put out: https://twitter.com/openbb_finance/status/1604952213293436928

<img width="613" alt="image" src="https://user-images.githubusercontent.com/46355364/208642545-110564b1-9e98-4534-bd97-8ffa3a0ba9fc.png">

And `EconDB`'s GDP and RGDP versions:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/208642785-d025179f-ad4d-487a-9615-8eda8bb5a16a.png">

It is clear we provide the Real Gross Domestic Product. However, the function naming suggests that we provide the nominal GDP per Capita. Ideally, you would just use the EconDB data and not AlphaVantage here too since EconDB is more extensive in this manner (data goes back to 1950).

**Comment by Alex-Leontaridis** [comment]
On it!
