### ISSUE TITLE
[Bug] `/stocks/ins` Stocks - Insider Trading wrong command in menu

### ISSUE THREAD

**Issue by Drinkler** [OpenBB-finance/OpenBBTerminal#3807]
**Describe the bug**
In the Stocks - Insider Trading menu which is accessible with `/stocks/ins` the command `bclp` [big latest CEO/CFO purchases ($25k+)] doesn't execute correctly.
OpenBB Terminal will replace this command with `blop` [big latest officer purchases ($25k+)]

**To Reproduce**

- Open OpenBB Terminal v2.0.0
- Navigate to `stocks/ins`
- Activate command `bclp` as seen in menu (first screenshot)
- Result of command `bclp` is the second screenshot

**Screenshots**
<img width="1423" alt="Stocks - Insider Trading menu" src="https://user-images.githubusercontent.com/17321535/208750433-e5daff72-3ceb-48e0-ad91-769330060ba2.png">
<img width="587" alt="Result of command bclp" src="https://user-images.githubusercontent.com/17321535/208750486-830be019-ba7d-4e0a-a920-af3c2dd02100.png">

**Desktop (please complete the following information):**

- OS: Mac Ventura 13.1
- OpenBB Terminal v2.0.0

**Additional context**
The command `blcp` runs the intended code. The command can be found in the file [`openbb_terminal/stocks/insider/insider_controller.py`](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/stocks/insider/insider_controller.py) in the `CHOICES_COMMANDS` constant.

**Comment by montezdesousa** [comment]
Fixes by https://github.com/OpenBB-finance/OpenBBTerminal/pull/3808
