### ISSUE TITLE
[Bug] Download link broken

### ISSUE THREAD

**Issue by aleksejst** [OpenBB-finance/OpenBBTerminal#3816]
Hi

The link on the download page for [Win installation](https://docs.openbb.co/terminal/quickstart/installation?tab=windows#installing-wsl-only-for-windows-users)

Points to:
`https://github.com/OpenBB-finance/OpenBBTerminal/releases/download/v2.1.0/Windows.10.OpenBB.Terminal.v2.1.0.exe`
This does not work, since has an extra dot in it.

The correct link should be:
`https://github.com/OpenBB-finance/OpenBBTerminal/releases/download/v2.1.0/Windows10.OpenBB.Terminal.v2.1.0.exe`

**Comment by jose-donato** [comment]
Hey, thank you for reporting this! 
Fixed here: #3817
