### ISSUE TITLE
[Bug] openbb.stocks.fa.analysis for ticker that doesn't exist

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3822]
<img width="429" alt="Screenshot 2022-12-22 at 19 36 16" src="https://user-images.githubusercontent.com/25267873/209212928-54527cd5-3db1-447b-81bc-d2c461224884.png">

**Comment by northern-64bit** [comment]
Has been fixed by #3858.
