### ISSUE TITLE
[Bug] openbb.stocks.fa.cal 

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3823]
<img width="513" alt="Screenshot 2022-12-22 at 20 30 02" src="https://user-images.githubusercontent.com/25267873/209220762-e507914f-78b2-4288-ab17-6f22363c07f9.png">

**Comment by jmaslek** [comment]
<img width="766" alt="Screenshot 2022-12-22 at 5 02 18 PM" src="https://user-images.githubusercontent.com/18151143/209233567-02f27e0c-fe36-41d4-8080-992cb8984a69.png">
