### ISSUE TITLE
[Bug] openbb.stocks.fa.growth with COIN

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3825]
<img width="520" alt="Screenshot 2022-12-22 at 21 37 55" src="https://user-images.githubusercontent.com/25267873/209230580-d25989cc-550c-4165-9029-4bc1aa345ad2.png">

**Comment by jmaslek** [comment]
<img width="543" alt="Screenshot 2022-12-22 at 5 00 03 PM" src="https://user-images.githubusercontent.com/18151143/209233272-45e6d503-07f4-4372-9e53-57ffaccba7fb.png">
