### ISSUE TITLE
[Bug] openbb.stocks.fa.metrics with COIN

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3826]
<img width="617" alt="Screenshot 2022-12-22 at 21 41 32" src="https://user-images.githubusercontent.com/25267873/209231059-91abca69-3cbf-48a4-84bc-a59d604745eb.png">

**Comment by jmaslek** [comment]
<img width="444" alt="Screenshot 2022-12-22 at 4 59 40 PM" src="https://user-images.githubusercontent.com/18151143/209233210-707cfd2c-3ecc-4a2b-9596-c61a920fd320.png">
