### ISSUE TITLE
[Bug] openbb.stocks.fa.mktcap

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3827]
<img width="461" alt="Screenshot 2022-12-22 at 21 46 36" src="https://user-images.githubusercontent.com/25267873/209231604-f429c706-efa9-4c88-8db4-e2840f501003.png">

**Comment by jmaslek** [comment]
you updated?  this was resolved with the yf bump?
<img width="394" alt="Screenshot 2022-12-22 at 4 57 51 PM" src="https://user-images.githubusercontent.com/18151143/209233046-2f51cb4e-587f-4d84-9172-46b6a9fb91e1.png">
