### ISSUE TITLE
[Bug] openbb.stocks.fa.ratios

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3828]
<img width="616" alt="Screenshot 2022-12-22 at 21 51 38" src="https://user-images.githubusercontent.com/25267873/209232260-2a14fdae-8903-4a4b-987c-93484dcdab7a.png">

**Comment by jmaslek** [comment]
update 
<img width="424" alt="Screenshot 2022-12-22 at 4 58 49 PM" src="https://user-images.githubusercontent.com/18151143/209233101-50ea3417-e9cd-4047-970a-b19952f27031.png">
