### ISSUE TITLE
[IMPROVE] We can add the possible finance_key

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#3834]
Also, what is the purpose of stocks_data, it retrieve the same as the function returns

![Screenshot 2022-12-22 at 23 28 37](https://user-images.githubusercontent.com/25267873/209241939-0646986c-e8c0-4f33-94e6-deb918be40f5.png)

**Comment by jmaslek** [comment]
rip sia
