### ISSUE TITLE
[FR] Download price history from the SDK for multiple symbols at once

### ISSUE THREAD

**Issue by jasonstrimpel** [OpenBB-finance/OpenBBTerminal#3835]
**What's the problem of not having this feature?**
I'd like to download price history through the SDK for multiple symbols at one time, similar to yfinance.

**Describe the solution you would like**

symbols = ["MSFT", "GME"]
prices = openbb.stocks.load(symbols, start_date=start, end_date=end)['Adj Close']

**Describe alternatives you've considered**
Loop through the list and append columns to DataFrames.

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by deeleeramone** [comment]
This functionality exists already:

```
openbb.economy.index(['MSFT','AAPL'])

```

![Screenshot 2022-12-27 at 9 56 00 AM](https://user-images.githubusercontent.com/85772166/209704483-976cdba4-da84-4711-ac51-ef056c5d378b.png)


That said, it would be nice to get groups from other sources too.

**Comment by jmaslek** [comment]
The sdk function I would recommend would be to use `openbb.stocks.ca.hist(ticker_list)`

**Comment by jasonstrimpel** [comment]
`openbb.stocks.ca.hist(ticker_list)` doesn't allow an end date so does not fit my requirements.

`openbb.economy.index(['MSFT','AAPL'])` better fits.

That said, both solutions may be better in a different namespace.

Per the documentation, `openbb.economy.index(['MSFT','AAPL'])` is for comparables and `openbb.economy.index(['MSFT','AAPL'])` is for indexes.

**Comment by jmaslek** [comment]
This was actually very easy to add: so I did #3867.

I think stocks.load( tickers ) may be more intuitive down the line, but I did not want to break that load that is used EVERYWHERE, and for loading in multiple symbols, comparison (ca) made sense to me.

That pr will let you do
```
start = "2012-08-22"
end = "2015-02-02
stocks.ca.hist( list_of_tickers , start, end)
```
(Also applied into the terminal functions!)

**Comment by jmaslek** [comment]
Hey @jasonstrimpel, any chance you took a look and would consider your requirements met?

**Comment by jasonstrimpel** [comment]
This is cool thanks @jmaslek closing
