### ISSUE TITLE
[Bug] Function openbb.stocks.options.grhist() does not return Option Greeks

### ISSUE THREAD

**Issue by nirmalpol** [OpenBB-finance/OpenBBTerminal#3836]
**Describe the bug**
I ran the following line using the SDK to get the call option greeks for ASTS  on 2023-01-20 for a strike of 4.0:

`openbb.stocks.options.grhist(symbol="ASTS", expiry='2023-01-20', strike=4.0, put=False)
`

![image](https://user-images.githubusercontent.com/33207203/209417148-2f545aff-bf40-446e-8565-fa0c68cfadae.png)

However, it states that the strike for 4.0 is not found even though there is a call option available for ASTS at a strike of 4.0 on 2023-01-20 as shown below:

![image](https://user-images.githubusercontent.com/33207203/209417072-4e75525c-8539-47d3-9b21-4be0b41e6b2e.png)

**To Reproduce**
Run the following command 

```
from openbb_terminal.sdk import openbb
openbb.stocks.options.grhist(symbol="ASTS", expiry='2023-01-20', strike=4.0, put=False)
```

**Desktop (please complete the following information):**

- OS: [Windows/WSL2]
- Python version [e.g. 3.9.6]

**Comment by jmaslek** [comment]
This is weird because the terminal functions work for this option.

Anyways, since this is buggy, another potential workaround is to pass the `chain_id` parameter.  For  that ASTS 4.0 Call, the id is `ASTS230113C00004000`.  We can do the following (sorry for the non-intuitive params, but chain_id takes precendence over any parameter)

```
openbb.stocks.options.grhist(symbol="", expiry="", strike= 4, chain_id="ASTS230113C00004000")
```

**Comment by deeleeramone** [comment]
It looks like the strike just needs to be input as a string and not a float/integer. However, another bug appears to be the timestamp conversion. 

![Screenshot 2022-12-27 at 1 58 49 PM](https://user-images.githubusercontent.com/85772166/209726039-972db200-21d1-4ab9-8c10-d2794f37abcc.png)

**Comment by deeleeramone** [comment]
The terminal doesn't like the Chain ID as an input:

```
(🦋) /stocks/options/ $ grhist ASTS230113C00004000

usage: grhist -s STRIKE [-p] [-g {iv,gamma,theta,vega,delta,rho,premium}] [-c CHAIN_ID] [-r] [-l LIMIT] [-h] [--export EXPORT]
grhist: error: argument -s/--strike: invalid float value: 'ASTS230113C00004000'

(🦋) /stocks/options/ $ grhist -c ASTS230113C00004000

usage: grhist -s STRIKE [-p] [-g {iv,gamma,theta,vega,delta,rho,premium}] [-c CHAIN_ID] [-r] [-l LIMIT] [-h] [--export EXPORT]
grhist: error: the following arguments are required: -s/--strike

(🦋) /stocks/options/ $ grhist -c ASTS230113C00004000 -s

usage: grhist -s STRIKE [-p] [-g {iv,gamma,theta,vega,delta,rho,premium}] [-c CHAIN_ID] [-r] [-l LIMIT] [-h] [--export EXPORT]
grhist: error: argument -s/--strike: expected one argument
```

**Comment by deeleeramone** [comment]
Symbol is SPY, expiration is 2022-12-30

![Screenshot 2022-12-27 at 2 04 53 PM](https://user-images.githubusercontent.com/85772166/209726410-34b5539e-7994-4eda-8187-e9974357426e.png)


![Screenshot 2022-12-27 at 2 04 19 PM](https://user-images.githubusercontent.com/85772166/209726380-48e8f2f0-98d9-4dc7-bce0-9cf90bc66f5a.png)

**Comment by jmaslek** [comment]
#4060 should have addressed this.
