### ISSUE TITLE
[Bug] Crypto/Disc/NFT - `--sort` argument fails when column name has a space in it.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3837]
```
/crypto/disc/nft
```
![Screenshot 2022-12-27 at 10 00 24 AM](https://user-images.githubusercontent.com/85772166/209704968-4a901bce-ef54-4a05-ad5b-0339e73fb79a.png)

```
(🦋) /crypto/disc/ $ nft --sort Volume [$]

usage: nft [-l LIMIT] [-s SORTBY [SORTBY ...]] [-h] [--export EXPORT]
nft: error: argument -s/--sort: invalid choice: 'Volume' (choose from 'Name', 'Protocols', 'Floor Price [$]', 'Avg Price [$]', 'Market Cap [$]', 'Volume [$]')

(🦋) /crypto/disc/ $
```

**Comment by brendef** [comment]
Hey @deeleeramone,

 I fixed this bug and created a pull request. 
 
 Would love your feed back.

**Comment by jose-donato** [comment]
> Hey @deeleeramone, @jose-donato @hjoaquim
> 
> I fixed this bug and created a pull request.
> 
> Would love your feed back.

Hey there. Thank you! I can review it later today
