### ISSUE TITLE
[Bug] Openbb installs but terminal won't start

### ISSUE THREAD

**Issue by ogrebeer** [OpenBB-finance/OpenBBTerminal#3839]
**Describe the bug**
openbb installs (via python instructions on Ubuntu Linux), but doesn't open.  Gives error:
`PermissionError: [Errno 13] Permission denied: '~/OpenBBUserData/styles'`
Note that the foler OpenBBUserData is empty, including a lack of hidden files

**To Reproduce**
Follow installation steps under python, on Ubuntu Linux 20.04LTS, and at the terminal type $openbb

Full error printout:
`Traceback (most recent call last):
  File "terminal.py", line 2, in <module>
    from openbb_terminal import terminal_controller
  File "~/openbb/openbb_terminal/terminal_controller.py", line 26, in <module>
    from openbb_terminal import feature_flags as obbff
  File "~/openbb/openbb_terminal/feature_flags.py", line 20, in <module>
    paths_helper.init_userdata()
  File "~/openbb/openbb_terminal/core/config/paths_helper.py", line 75, in init_userdata
    create_paths(dirs_list)
  File "~/openbb/openbb_terminal/core/config/paths_helper.py", line 27, in create_paths
    dirs.mkdir(
  File "~/miniconda3/envs/obb/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '~/OpenBBUserData/styles'`

**Desktop (please complete the following information):**

- OS: Ubuntu Linux 20.04 LTS
- Python 3.8.15

**Comment by ogrebeer** [comment]
Solved.  For some reason openbb makes some directories that I don't have ownership of.  The commands:
`sudo chown -R ogrebeer: ~/OpenBBUserData`
and
`sudo chown -R ogrebeer: ~/.openbb_terminal/`
(the later from an effectively identical error)
gave me ownership of of these folders, and openbb now runs

**Comment by davidhaley** [comment]
@hjoaquim, should this be closed?
