### ISSUE TITLE
API_KEY_QUANDL not defined

### ISSUE THREAD

**Issue by msh855** [OpenBB-finance/OpenBBTerminal#3852]
Hello, 

I am using the openBB_SDK in python. 

when I run this function: 
`openbb.economy.bigmac('GBR') `

I get this error:
`API_KEY_QUANDL not defined. Set API Keys in ~/.openbb_terminal/.env or under keys menu.`

It looks that I need to define my personal API for quandl, but I couldn't find somewhere an information about this. 

I recommend either adding an argument to functions that need api_keys to be supplied by the users as an argument in the function. Might make things easier and more flexible for the openBB_SDK. 

In the meantime, can you please help fix this?

Thanks

**Comment by jmaslek** [comment]
Hey.  Using the SDK, you can set this key using:

```
from openbb_terminal.sdk import openbb
openbb.keys.quandl(key="example_key")
```

More infromation found on our documentation: https://docs.openbb.co/sdk/guides/advanced/api-keys

**Comment by msh855** [comment]
Thanks
