### ISSUE TITLE
[Bug] Loading a stock fails with: Error: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by kajdo** [OpenBB-finance/OpenBBTerminal#3853]
**Describe the bug**
loading a ticker fails with `Error: index -1 is out of bounds for axis 0 with size 0`

**To Reproduce**
stocks/load msft

**Screenshots**
![image](https://user-images.githubusercontent.com/8735942/210183222-c625937c-74cf-4664-a72b-1dc206c54971.png)

**Desktop (please complete the following information):**

- OS: Linux mint 5.15.0-56-generic
- Python version: Python 3.9.13

**Additional context**
assumed the issue is related to OpenBBTerminal/issues/3796 and tried the described solutions (`pip install yfinance==0.1.93` and changing the source to Polygon) .... both didn't work

**Comment by jmaslek** [comment]
So I quickly looked at this:

the reason is when we try to calculate the `ytd` performance, there is no ytd data since it is now a new year.

In theory this should be resolved on its own either tomorrow or tuesday, but we should probably evaluate this edge case.

**Comment by kajdo** [comment]
haha ... alright - thx for the quick check ... and happy new year

**Comment by nishdwi** [comment]
![Screenshot 2023-01-02 at 21 33 56](https://user-images.githubusercontent.com/50500686/210279415-29a8d31c-ca14-4e05-856d-cf9c3ca5072a.png)
providing the end date to avoid the new year issue fails as well

**Comment by deeleeramone** [comment]
hey, so a workaround is to load intraday data, like `load tsla -i 60`, which will give you 2 years of 1 hour candles. Alternatively, you can use `--monthly` & `--weekly` flags. This particular error will likely resolve itself after there are two days of closing prices on the books. Definitely still a bug though, this error occurs after the data has been loaded but is trying to make YTD stats while dividing by zero.

**Comment by jmaslek** [comment]
> I wonder if it would be worth a thought to "soften" the requirement to "load" the data before going into fa, dd or... if I want to check some fundamentals without looking at the candles the load of the daily data isn't really necessary and causes an unnecessary request to yf/other source ... but that's a different topic to the issue itself
> 
> i might raise a feature request to discuss

Feel free to.  This has been something I have thought about and there is no reason to require the ticker!

**Comment by jmaslek** [comment]
#3860 closes this.
