### ISSUE TITLE
Stocks/disc/ Gainers and Losers

### ISSUE THREAD

**Issue by jmmartinnu2** [OpenBB-finance/OpenBBTerminal#3854]
Now that we're starting the new year is when we look up a lot of past stats. For example, if we want to do a search for the shares of the NYSE, Nasdaq... etc. looking for those that have lost the most value ordered by annual date... that is currently not available. So let's see if this functionality is implemented and complete this section

**Comment by jmaslek** [comment]
I dont understand the request?  

The gainers/losers commands is just looking at the extreme percent changes from yahoo finance at the time.  It doesn't allow one to filter by a given day.  If you wanted to look at a filter of extreme gainers/losers from ytd, we would need to store all the data, which we can not legally do.

You can use the stocks/scr menu to look at ytd performance

**Comment by deeleeramone** [comment]
Pretty easy to accomplish with existing tools, like the stocks screener.

![Screenshot_20230102_071832](https://user-images.githubusercontent.com/85772166/210296102-57c4ae7f-3db8-47e5-94da-ade1e95ecefe.png)

**Comment by jmmartinnu2** [comment]
Hi, I understand if you can't then nothing. I thought that by doing some kind of scraping and storing and displaying it in a source table like barchart where this metric is, you can get it for free! and I find this super interesting!

image Barchart column **YTD%Ch**
![ano](https://user-images.githubusercontent.com/93231115/210386019-9c3d1fff-f3b4-42da-b2de-332142b3cbe6.png)

**Comment by jmmartinnu2** [comment]
I think I was getting confused... of course we are already in the year 2023 and I was seeing this ordering and I was not realizing that it is already collecting the information for this year 2023... that's it!! So if I want to collect the information for 2022 and see the biggest losses of that past year, if I need to add one more parameter to be able to filter by year, right?

**Comment by jmaslek** [comment]
> I think I was getting confused... of course we are already in the year 2023 and I was seeing this ordering and I was not realizing that it is already collecting the information for this year 2023... that's it!! So if I want to collect the information for 2022 and see the biggest losses of that past year, if I need to add one more parameter to be able to filter by year, right?

I dont think the finviz screener has an option to select for a given year. And it looks like the Perf Year = YTD, so even using this won't give the rolling last 1 Yr performance.  Based on this, I can't think of a way to find

- Biggest loser in a given year
- Biggest winner in a given year

@deeleeramone?  Anything in the terminal I'm not thinking of?

**Comment by deeleeramone** [comment]
Perf Year != Perf YTD

![Screenshot 2023-01-03 at 4 31 08 PM](https://user-images.githubusercontent.com/85772166/210463481-2da9418c-984e-4a91-950a-6480c93e859a.png)

However, when you take those results to the `CA` menu, the patch you deployed with `start` & `end`, would work perfectly for this, *BUT*, there also needs to be a `--raw` flag to output as a table instead of plotting 1000 tickers.

**Comment by deeleeramone** [comment]
@jmaslek, Another method would be to use Polygon, get_group_aggs, for the first and last day of the period, and then sort by change between the two dataframe.
