### ISSUE TITLE
[Bug] The `etf/pir` functionality is broken, please update the `thepassiveinvestor` package to v1.0.11

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3856]
Due to changes to `yfinance` and the fact `thepassiveinvestor` relied on a version of the package that is no longer working, it needed an update. This update has been made (it's my own package). To verify, if you try to use `pir` it returns no data while a ticker like `VOO` should.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/210258121-ca3f8a88-ef81-4844-9c19-fc5f9230607f.png">

See newest version with same ticker:

<img width="1512" alt="Screenshot 2023-01-02 at 17 35 02" src="https://user-images.githubusercontent.com/46355364/210258279-db4ba7e7-0351-4a45-99e8-941a14899f66.png">

**Comment by martinb-bb** [comment]
to be updated with: https://github.com/OpenBB-finance/OpenBBTerminal/pull/3866

**Comment by martin-musashi** [comment]
@JerBouma  can be closed now.

**Comment by martinb-bb** [comment]
@JerBouma Can be closed now.
