### ISSUE TITLE
[Bug] Timezone does not change when selected from the settings menu. Reset does not include changes to environment variables.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3863]
Changing the timezone in the Terminal does not change the timezone. Using the `reset` does not implement the changes, only after `exit` and relaunch do changes to the environment variables appear. For an installer-version, the changes will never appear because of: #3633
 
https://user-images.githubusercontent.com/85772166/210400870-e4d5e27c-e1ee-4811-ae32-9cbdaf077b18.mov

**Comment by montezdesousa** [comment]
Fixed by #3871
