### ISSUE TITLE
[Bug] Stocks/Load - Last Price != Last Price

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3865]
It seems that 'last price' is being procured from 'previous close' instead of 'last price'.

![image](https://user-images.githubusercontent.com/85772166/210430897-54da6b44-9748-49e6-bcef-471e011f997a.png)

![Screenshot 2023-01-03 at 11 52 08 AM](https://user-images.githubusercontent.com/85772166/210431019-04390700-cf50-427a-8fd5-d3bc774182b3.png)

**Comment by jmaslek** [comment]
Yeah this needs to be update to say "Previous Close".  Although if you specify an end date, it will give the price at that point, as it gives the last price in the df, so its technically "last price you asked for"

I think this is a good first issue and will add the tag!

**Comment by deeleeramone** [comment]
Wouldn't it be a lot better to just get the actual last price? That would make the 1-day return accurate as well.

**Comment by jmaslek** [comment]
Not if you specify an end date. And Getting the yf last price takes another 1.7 seconds for me me which is just slightly too irritating for my liking

This is probably at the point where there are slightly too many edge cases and it's better to nix this is favor of a function that calculates some of this info directly

**Comment by deeleeramone** [comment]
it really should, because loading from other sources breaks when this part fails. think, `brk-a` vs. `brk.a`

**Comment by deeleeramone** [comment]
![Screenshot 2023-01-03 at 5 03 58 PM](https://user-images.githubusercontent.com/85772166/210465864-11231bd5-d752-48ec-83d3-1bfcb73c0283.png)

**Comment by qmarsun** [comment]
Something is not correct in my local dev
I changed that line but not seeing the changes to myself . Where can I find steps to test locally the code change
