### ISSUE TITLE
[IMPROVE] Ensure all exports to Excel are always numbers and not strings

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3872]
Whenever you export something to Excel, e.g. `stocks/load MSFT/income --source Polygon --export xlsx` you will receive output that includes Bs, Ms and similar which will always require data adjustments if you wish to do anything with the data. This is very undesirable because it requires additional work from the user side in which it can question why not just get this from somewhere else if it's such a burden to edit?

There needs to be a helper functionality that automatically recognizes these type of numbers and converts it accordingly.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/46355364/210754809-79e5f061-35cb-4dcc-b895-c2c86a5232aa.png">

**Comment by deeleeramone** [comment]
Not the same, but similar to: #3840
