### ISSUE TITLE
Error /stocks load ES=F and others[Bug]

### ISSUE THREAD

**Issue by jmmartinnu2** [OpenBB-finance/OpenBBTerminal#3880]
![version](https://user-images.githubusercontent.com/93231115/211037876-e78fc5a5-6743-4abf-bb5e-fd52c2c592d5.png)
I have version 2.1 and I don't know what happens when I want to load ticker sp500 or other indices or really any asset...

**Comment by jmaslek** [comment]
For ES=F, you should run

```
/futures/historical ES
```

For indices, you can go to `/economy/index -h`

**Comment by deeleeramone** [comment]
Windows installer and Git Clone versions working over here, perhaps you need to update your local clone @jmmartinnu2. 

```
git fetch
git pull
poetry install -E all
```

**Comment by colin99d** [comment]
@jmmartinnu2 are you still experiencing this issue?
