### ISSUE TITLE
[Bug] Stocks/load - Can't load intraday/monthly/weekly from AlphaVantage - Error: local variable 's_interval' referenced before assignment

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3882]
```
/stocks/load SPY --source AlphaVantage --interval 5
```
Error: local variable 's_interval' referenced before assignment

Weekly/monthly flags returns only daily.

![Screenshot 2023-01-06 at 9 37 31 AM](https://user-images.githubusercontent.com/85772166/211067211-67cfa1ae-f910-4f87-8750-0bf633baa4b8.png)

**Comment by MertNuhuz** [comment]
As a result of the research I have done, no code for importing data from the "alpha_vantage" source has been written for weekly and monthly intervals in the file at the [1]. I think I can make the necessary additions. I would be happy if assigned to me.

[1]:[https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/stocks/stocks_helper.py](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/openbb_terminal/stocks/stocks_helper.py) file link

**Comment by jmaslek** [comment]
that is correct.  feel free to add it!

**Comment by deeleeramone** [comment]
There are direct endpoints for this, so it probably doesn't even need much.

TIME_SERIES_WEEKLY
TIME_SERIES_WEEKLY_ADJUSTED
TIME_SERIES_MONTHLY
TIME_SERIES_MONTHLY_ADJUSTED
