### ISSUE TITLE
[Bug] SDK - Docstrings are not returning info where they should. Every function is only labeled as "instance"

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#3887]
None of the OpenBB SDK docstrings are being read properly. They should respond like this:

![Screenshot 2023-01-06 at 5 51 14 PM](https://user-images.githubusercontent.com/85772166/211126022-b70d8a46-90c5-4163-b858-624106dcd9ba.png)

Instead, everything is an "instance" with no function parameters displayed like the above.

https://user-images.githubusercontent.com/85772166/211125925-385addbe-e2e0-47ce-9ede-155c5a3092b5.mov

**Comment by jmaslek** [comment]
At no point there do you attempt to show a docstring.  What you are expecting is the language server to pick up a signature which is not possible with the way the sdk was defined.

this has been asked for in #3832

**Comment by deeleeramone** [comment]
Ah. Sorry, my bad, my personal language server was missing that definition. 🥲
