### ISSUE TITLE
Clould no print any figure.

### ISSUE THREAD

**Issue by alvarocleite** [OpenBB-finance/OpenBBTerminal#3894]
I cannot display any figure generated by OpenBB

Here it gives an error
![Screenshot_20230108_163305](https://user-images.githubusercontent.com/20518135/211208116-c140d842-ffac-4520-9038-e2fbaed6086c.png)

Here it doesn't give an error but nothing opens
![Screenshot_20230108_163522](https://user-images.githubusercontent.com/20518135/211208207-ee2f1455-aabc-4804-a3c3-ded01d2799de.png)

The same happens for everything that is not printed directly on the terminal.

I'm using the docker image.
I have Matplotlib installed, and the python qt5 too.

Here is my OpenBB configs:
![Screenshot_20230108_164128](https://user-images.githubusercontent.com/20518135/211208434-d34fb472-2d5c-43d4-83f9-c7ff3cbf4d0a.png)

I already tried to change the backend and the monitor, the errors continues.

- OS: Manjaro with KDE
- Python version 3.10.8

**Comment by deeleeramone** [comment]
Docker requires additional steps to display images, see these steps here if you have not already:
https://docs.openbb.co/terminal/quickstart/installation#13-install-vcxsrv

**Comment by alvarocleite** [comment]
Thank you for your response.

I think I made it work by running those three commands in sequence:

``` commands
$ export DISPLAY=localhost:0.0
$ xhost +local:
$ docker compose run -it --rm --name openbb -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix openbb
```

I would like to know if there is an easier way to make it work. I know I can create a small sh script for that, but it seems to me that it is not the best solution.

**Comment by colin99d** [comment]
We have not found one, but if you find one please let us know!
