### ISSUE TITLE
[FR] Integate OECD Database within the `economy` menu

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3907]
Basing this of a variety of market reports, I wanted to understand the ease how we can reproduce the results in the OpenBB Terminal. This lead to the suggestion to integrate the OECD Database.

## Context

Getting governmental bond data (most easily, the 10 years curve) the `fred` functionality can be used. However, it is very tricky to get the data and it doesn't look too nice in the graph. For example, what I need to do to get data on United Kingdom, Germany, Greece and Italy is to query fred with `freq -q` and find the relevant timeseries. This was okay to do, e.g. I now know that the following will provide that data IRLTLT01GBM156N, IRLTLT01DEM156N, IRLTLT01GRM156N and IRLTLT01ITM156N.

![Figure_1](https://user-images.githubusercontent.com/46355364/211341253-13271a33-034d-4a2c-a562-fd59cf64f282.png)

However, what the data actually represents is a mystery. I need to do manual research first to come to this page https://data.oecd.org/interest/long-term-interest-rates.htm. Here is where I discovered that OECD has most of the important data that we can use.

## Getting the data

You can query OECD relatively easy. All information comes from https://stats.oecd.org/ and as you can see it is incredibly extensive. See for example a Medium article about it here: https://medium.com/@koki_noda/how-to-use-oecd-data-in-python-69a0234c6b27

For example, here is a massive dump of long-term interest rates: https://stats.oecd.org/restsdmx/sdmx.ashx/GetData/KEI/IR+IRLTLT01.AUS+AUT+BEL+CAN+CHL+COL+CRI+CZE+DNK+EST+FIN+FRA+DEU+GRC+HUN+ISL+IRL+ISR+ITA+JPN+KOR+LTU+LVA+LUX+MEX+NLD+NZL+NOR+POL+PRT+SVK+SVN+ESP+SWE+CHE+TUR+GBR+USA+NMEC+ARG+BRA+CHN+IND+IDN+RUS+SAU+ZAF.ST.A+Q+M/all?startTime=2019&endTime=2022

Which corresponds to the (made compact on purpose) table:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/211351450-b8f1a6fb-ef68-4965-a322-37603e9d00e1.png">

This link I got from https://stats.oecd.org/Index.aspx?QueryId=21762 --> Export --> SDMX. You should be able to query this data through https://data.oecd.org/api/sdmx-ml-documentation/ to get all long term rates in an instant. A process that is much more clean and complete than you would ever be able to achieve via FRED.

Another example of how to query the data is done here: https://github.com/bdecon/econ_data/blob/master/APIs/OECD.ipynb

**Impressive bonus:** you can also get a complete overview and future expectations from the OECD for **any country** with the following query: https://stats.oecd.org/Index.aspx?QueryId=51397

## Use case

When it comes to market reports written by Finance Societies, Investment Clubs and Investment Banks, they will often require a hefty amount of macro-economic data. Take the following examples:

- [Goldman Sachs Market Report](https://github.com/OpenBB-finance/OpenBBTerminal/files/10381417/report.pdf)
- [Market Outlook 2023 by Forbes](https://www.forbes.com/advisor/investing/stock-market-outlook-and-forecast/)
- [Market Report November for Athens University](https://github.com/OpenBB-finance/OpenBBTerminal/files/10381420/NOVEMBER-2022-MARKET-REPORT.2.pdf)
- [Market Report May for Athens University](https://github.com/OpenBB-finance/OpenBBTerminal/files/10381460/May-2022-Market-Report.pdf)

Having the OECD source integrated, makes it much easier to collect the relevant data as found in these reports. **Therefore, the purpose is to promote adoption within these parties by showing them how easy it is to get a complete market overview through the OpenBB Terminal.**

**Comment by joshuabuildsthings** [comment]
@JerBouma - OECD has a [free JSON API](https://data.oecd.org/api/sdmx-json-documentation/)

There are some Python Libraries already available to parse it's SDMX format which is also used by a lot of other [really interesting sources.](https://pandasdmx.readthedocs.io/en/latest/sources.html)

This one seems to not be actively developed:
[https://pandasdmx.readthedocs.io/en/latest/](https://pandasdmx.readthedocs.io/en/latest/)

But this fork does appear to be actively developed:
[https://sdmx1.readthedocs.io/en/latest/](https://sdmx1.readthedocs.io/en/latest/)

[https://github.com/khaeru/sdmx](https://github.com/khaeru/sdmx)

**Comment by jmaslek** [comment]
@JerBouma does your new PR close this :D

**Comment by JerBouma** [comment]
@jmaslek Let's close it and I revisit later. There is much more useful stuff we can grab from there but that can be part of 4.0.
