### ISSUE TITLE
`/economy/events` outputs API error, but `/economy/bigmac` doesn't; even though they seem to use the same source

### ISSUE THREAD

**Issue by mainuser369** [OpenBB-finance/OpenBBTerminal#3925]
**Describe the bug**
/economy/events doesn't return any data whatsoever and outputs the following error (Screenshot 1: Error Message.png)

```
There was an error connecting to the API. Please try again later.

Error: 'list' object has no attribute 'empty'
```

**To Reproduce**
1. Launch conda environment for openbb using `conda activate <ENVIRONMENT-NAME>`
2. Launch OpenBB using `openbb`
3. Enter `economy`
4. Execute either `events` or `events -c united_states --categories inflation`
5. After 2-3 minutes, the above error message is displayed.
6. Execute `bigmac`, which outputs the correct data (while using the same API/Source as `events`)

**Desktop (please complete the following information):**

- OS: Debian 11.6 with GNOME
- Python version 3.9.6

**Screenshots and Attachments**
**1. Screenshot 1: Error Message**
![Screenshot 1 - Error Message](https://user-images.githubusercontent.com/65833418/211694474-8c0ec7eb-e394-4708-be15-59b502b2659f.png)
**2. Screenshot 2: API Keys installed in OpenBB**
![Screenshot 2 - API Keys installed in OpenBB](https://user-images.githubusercontent.com/65833418/211694478-5efda325-f80a-4654-a2e0-3a977e465c2a.png)
**3. Screenshot 3: bigmac Command Output.**
![Screenshot 3 - bigmac Command Output](https://user-images.githubusercontent.com/65833418/211694479-02b2d5d5-e119-465e-a51d-dde2ff04d3dc.png)
**4. debug-log.txt (Output of `/economy/events` after executing `python terminal.py --debug`)**
[debug-log.txt](https://github.com/OpenBB-finance/OpenBBTerminal/files/10387960/debug-log.txt)

**Additional context**
None. I'm more than happy to provide further information as requested.

**Comment by jmaslek** [comment]
Hmmm.  I have run into timeout issues with this source (it grabs directly from nasdaq website, bigmac grabs from nasdaq datalink/formerly quandl).

2 follow ups: 1) are you using the installer/packaged app (if you are running with --debug I assume you are not) And 2) are you in the US?

The workaround would be to try a different user agent in the request or adjust some headers.

**Comment by mainuser369** [comment]
@jmaslek : Thank you very much for getting back quickly. I appreciate your help.

Answers to your follow-up questions:

1. Are you using the installer/packaged app -- I have been installing OpennBB Terminal (and in its earlier incarnation as the GameStonk Terminal) using Anaconda3/Python3 (https://docs.openbb.co/terminal/quickstart/installation). Let me know if you need further elaboration on this topic.
2. I'm not located in the US. I'm located in Europe, but do have access to VPNs based in the USA.

I hope the above answers your questions. Let me know what other information you need; and I'm more than happy to answer your questions!

As always, thank you very much for all the work you people are doing!

**Comment by deeleeramone** [comment]
> 
> Could you please elaborate on the workarounds? I can try to troubleshoot the problem myself and provide feedback, if you could help me out with the necessary steps.
> 

I'm pretty sure you are using an old version. There is no `--categories` argument for the `events` function.

**Comment by colin99d** [comment]
I can confirm there is no --categories in the newest version.
```
😀 /economy/ $ events --help

usage: events [-c COUNTRIES] [-n] [-s START_DATE] [-e END_DATE] [-d SPEC_DATE] [-h] [--export EXPORT] [--sheet-name SHEET_NAME [SHEET_NAME ...]] [--raw] [-l LIMIT]

Economic calendar. If no start or end dates, default is the current day high importance events.

options:
  -c COUNTRIES, --countries COUNTRIES
                        Display calendar for specific country. (default: )
  -n, --names           Flag to show all available country names (default: False)
  -s START_DATE, --start START_DATE
                        The start date of the data (format: YEAR-MONTH-DAY, i.e. 2010-12-31) (default: 2023-03-23)
  -e END_DATE, --end END_DATE
                        The start date of the data (format: YEAR-MONTH-DAY, i.e. 2010-12-31) (default: 2023-03-23)
  -d SPEC_DATE, --date SPEC_DATE
                        Get a specific date for events. Overrides start and end dates. (default: None)
  -h, --help            show this help message (default: False)
  --export EXPORT       Export raw data into csv, json, xlsx (default: )
  --sheet-name SHEET_NAME [SHEET_NAME ...]
                        Name of excel sheet to save data to. Only valid for .xlsx files. (default: None)
  --raw                 Flag to display raw data (default: False)
  -l LIMIT, --limit LIMIT
                        Number of entries to show in data. (default: 100)

For more information and examples, use 'about events' to access the related guide.


😀 /economy/ $
```
@mainuser369 are you still having issues with this in our newest version?
