### ISSUE TITLE
[Bug] Axes are off when plotting data within `futures/historical`

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3939]
As none of the data even comes close to the bottom part, it is odd that we would still show these axes.

Code: ` historical --ticker GC -s 2022-01-01`

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/46355364/212066322-9c809252-0075-4ffb-91be-493d43fedae2.png">

When changing the expiry to 1-mo, you would see much better picture.

Code: `historical --ticker GC -s 2022-01-01 -e 2023-02`

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/212066462-a76ee5b4-6726-4063-b005-039cfea6ca73.png">

**Comment by jmaslek** [comment]
Interesting.  This happens because there is actually a value of 255 in the series.

```
print(np.min(historicals["Adj Close"].dropna().values))

255.1
```

Got it.  We actually plot before applying the start date to the dataframe, so because GC=F was 250 back in the 2000s, that is what the y axis is doing.  Need to slice the df before plotting.
