### ISSUE TITLE
[Bug] `forex/load` lacks a way to select an end date and `forex/candle` chart makes little sense

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3940]
It is not possible to select an end date with `forex/load`:

```
2023 Jan 12, 07:37 (🦋) /forex/ $ load -h

usage: load [-t TICKER] [-r {i,d,w,m}] [-i {1min,5min,15min,30min,60min,90min,1hour,1day,5day,1week,1month,3month}] [-s START_DATE] [-h] [--export EXPORT] [--source {YahooFinance,AlphaVantage,Polygon,Oanda}]

Load historical exchange rate data.Available data sources are Alpha Advantage and YahooFinanceBy default main source used for analysis is YahooFinance (yf). To change it use --source av

optional arguments:
  -t TICKER, --ticker TICKER
                        Currency pair to load. (default: None)
  -r {i,d,w,m}, --resolution {i,d,w,m}
                        [Alphavantage only] Resolution of data. Can be intraday, daily, weekly or monthly (default: d)
  -i {1min,5min,15min,30min,60min,90min,1hour,1day,5day,1week,1month,3month}, --interval {1min,5min,15min,30min,60min,90min,1hour,1day,5day,1week,1month,3month}
                        Interval of intraday data. Options: [YahooFinance] 1min, 2min, 5min, 15min, 30min, 60min, 90min, 1hour, 1day, 5day, 1week, 1month, 3month. [AlphaVantage] 1min, 5min, 15min, 30min, 60min
                        (default: 1day)
  -s START_DATE, --start START_DATE
                        Start date of data. (default: 2022-01-12 13:37:54.851857)
  -h, --help            show this help message (default: False)
  --export EXPORT       Export raw data into csv, json, xlsx (default: )
  --source {YahooFinance,AlphaVantage,Polygon,Oanda}
                        Data source to select from (default: YahooFinance)

For more information and examples, use 'about load' to access the related guide.
```

The candle chart also does not properly represent the actual scenario.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/212068818-023f52cf-6382-4628-82b3-96b00373800e.png">

Compare this to Yahoo Finance:

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/46355364/212068998-d8703df7-caa3-4cf6-a5c4-0371f395c621.png">

**Comment by hjoaquim** [comment]
Hello @JerBouma, would you help me with some more context about this comment, please:

> The candle chart also does not properly represent the actual scenario.


When loading for the same period, looks like this:

![image](https://user-images.githubusercontent.com/48914296/215467097-fef658f4-ee9d-4568-9b05-703b56c3311e.png)

**Comment by JerBouma** [comment]
@hjoaquim It's about the only red candle sticks, if a stock moves up that should be green. It's clear that isn't happening in that chart for a portion of it.

**Comment by hjoaquim** [comment]
@JerBouma got it, thanks!

**Comment by jmaslek** [comment]
That candle seems to be a yf thing.  Even if you look at their website, the Open==Close for those days, so it always makes the candles "down" 


<img width="665" alt="Screenshot 2023-01-30 at 3 32 05 PM" src="https://user-images.githubusercontent.com/18151143/215588656-87bae651-a819-487d-be14-2ef32c21ee9d.png">

**Comment by hjoaquim** [comment]
That seems to be the case.
Looking at the other data sources, looks like the function that processes the data to plot the candle is alright, and it is a yf thing.

**Comment by JerBouma** [comment]
It's odd since the Yahoo Finance chart itself is fine. Anyways, then it's a data issue, issue closed.

![image](https://user-images.githubusercontent.com/46355364/215747300-69dc355b-293c-4a12-a97c-a92f4eadd9e9.png)
