### ISSUE TITLE
Mutual Funds in openBB SDK

### ISSUE THREAD

**Issue by msh855** [OpenBB-finance/OpenBBTerminal#3972]
Hi, 

I don't see in the SDK the equivalent of `mutual fund` reference/module that exist in the terminal. 

Is missing from the documentation of the SDK or this feature is just missing ?

**Comment by skhan59bbk** [comment]
I don't think you're using the latest version of the terminal... I believe the mutual fund menu was deprecated.

**Comment by deeleeramone** [comment]
That is correct. The Mutual Fund functions were deprecated when the Investpy library broke.

**Comment by msh855** [comment]
Thank you both. 

I am not using any version. I just looked at your documentation. The reference to `mutual funds` was still there and I got confused because I was looking where I can see this reference in the SDK. 

So, I take the documentation for the SDK is more updated than the documentation of the terminal. 

Yes, investpy not robust. I tried it myself and I gave up.

**Comment by deeleeramone** [comment]
Good catch. That part of the documentation is generated automatically, and because the code is still present - the functions have just been commented out in hopes of it being repaired - it thinks it still exists.
