### ISSUE TITLE
[IMPROVE]Increase number of news pieces output at OpenBBSDK

### ISSUE THREAD

**Issue by leeauk21** [OpenBB-finance/OpenBBTerminal#3976]
**What's the feature that should be improved?**
A description of what's the feature you want improved, and a bit of context (why is that).

**Describe how you would like the feature improved**
A description of what the current feature is vs what it would be after your suggestion.

**Possibly describe the ideal way to improve this**
If you have thought about how you would do it, add it here.

**Additional information**
Add any other information or screenshots about the feature improvement.

**Comment by deeleeramone** [comment]
You can use the `--limit` argument to increase the number of results returned.

**Comment by leeauk21** [comment]
But then in the openb. Sdk there are only 3 argument and none of them is limit. I think you are referring to the terminal

**Comment by deeleeramone** [comment]
You are correct, I mistakenly conflated the two and 100 the ceiling there. My bad!
