### ISSUE TITLE
[IMPROVE] Make the `stocks/load` function more robust

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3990]
When Yahoo Finance package `yfinance` breaks, it’s a major issue because the entire `stocks/load` functionality becomes broken because whatever source you use, it will rely on data coming from `yfinance`. This instantly makes most of the OpenBB Terminal's Stocks menu unusable.

As we have multiple sources this shouldn't be the case as I would simply need to select a different source to continue to use the OpenBB Terminal. However, these sources also have some affiliation with the `yfinance` package. As seen below:

```
2023 Jan 17, 06:24 (🦋) /stocks/ $ load MSFT

Loading Daily data for MSFT with starting period 2020-01-13.
Error: can only concatenate str (not "NoneType") to str


2023 Jan 17, 06:24 (🦋) /stocks/ $ load --ticker MSFT --source IEXCloud

('Response 402 - ', 'Access is restricted to paid subscribers. Please upgrade to gain access')

2023 Jan 17, 06:25 (🦋) /stocks/ $ load --ticker MSFT --source AlphaVantage

Loading Daily data for MSFT with starting period 2020-01-13.
Error: can only concatenate str (not "NoneType") to str


2023 Jan 17, 06:25 (🦋) /stocks/ $ load --ticker MSFT --source Polygon

Loading Daily data for MSFT with starting period 2021-01-19.
Error: can only concatenate str (not "NoneType") to str


2023 Jan 17, 06:25 (🦋) /stocks/ $ load --ticker MSFT --source EODHD

Loading Daily data for MSFT with starting period 2022-01-18.
Error: can only concatenate str (not "NoneType") to str


2023 Jan 17, 06:25 (🦋) /stocks/ $ fa

Use 'load <ticker>' prior to this command!

2023 Jan 17, 06:28 (🦋) /stocks/ $ load TSLA

Loading Daily data for TSLA with starting period 2020-01-13.
Error: can only concatenate str (not "NoneType") to str
```

What I would propose is the following:

- When data fails to load that is **not** crucial for usage in other functionality, it should simply warn the user and then let the user continue. E.g. if I use AlphaVantage as source, it should just tell me it was not able to acquire company name, exchange and currency if that data comes from `yfinance`.
- When some or all options fail, I should still be able to set a ticker. When I am using `stocks/fa` I do not need market data. It is a big blocker that I can not use this menu just because market data can't be loaded. I should be able to just say `set MSFT` and it will save this ticker and use it within the other functionalities. There needs to be a flag within `stocks/load` that allows me to continue with a disclaimer that says that I can't use x menus **and** the ticker still needs to load when market data fails and it would just tell me that x menus are unusable.
- Given that `yfinance` is using an unofficial API from Yahoo Finance, it is important that we lower the reliance on this source. The chance of it breaking compared to e.g. FinancialModellingPrep is much higher and it makes installation builds no longer usable. Given that it could be that our software is installed on virtual machines and not updated regularly, this makes it very cumbersome to adopt within these environments.

The first two proposals should make the menu more robust and continue to be usable when a package breaks. It is really not great that people constantly are required to update.

**Comment by jmaslek** [comment]
This should have already been addressed in a recent PR.  Also had a PR that made sure ETFs load without breaking.

**Comment by JerBouma** [comment]
Perfect.
