### ISSUE TITLE
Command /crypto/load BTC/dd/mcapdom BTC percentage share returns incorrect Data

### ISSUE THREAD

**Issue by bernardobalroa** [OpenBB-finance/OpenBBTerminal#3992]
Data Source: Messari 
Command: /crypto/load BTC/dd/mcapdom

The command has some bugs. When I run the command, he returns data that goes to 0 when it shouldn't.

**Comment by jeugregg** [comment]
Yes, same for me with SDK :
using `openbb.crypto.dd.mcapdom` on BTC,  ETH 2023-02-14 & 2023-02-15

```
from openbb_terminal.sdk import openbb
openbb.crypto.dd.mcapdom(symbol="BTC")


  | marketcap_dominance
-- | --

7.058662e+01
7.169934e+01
7.124913e+01
6.844049e+01
6.848675e+01
...
4.066569e+01
1.150324e-29
1.172279e-29
4.152526e+01
4.361406e+01


```
