### ISSUE TITLE
[Bug] Export of `stocks/load` leaves you with unrecognizable Excel file names

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#3994]
See the following, this is an export of multiple different tickers but it is not possible to recognize which is which:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/46355364/212914115-d9b3241c-6298-41b2-9581-617df0b5859f.png">

The command `stocks/candle` does this better but downloading data via `load` is more efficient.

**Comment by jmaslek** [comment]
you can specify --export aapl.csv

**Comment by JerBouma** [comment]
Hmm that solves the issue to some extend but adding the ticker to the string wouldn't be too hard either right? Candle does that too. It's mostly that the naming is off, e.g. candle produces `20230117_150713_stocks_AAPL.xlsx` then I'd expect the same naming to be produced by `load`.

**Comment by deeleeramone** [comment]
if using routines, you can set the filename to include the ticker by using the variable inputs, `$ARGV[0]`

`load $ARGV[0] --export $ARGV[0]_ohlc.xlsx`
