### ISSUE TITLE
[Bug] Economy Menu - Plotting function not plotting two things

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4020]
One works:

`/economy/index sp500`

![Screenshot 2023-01-19 at 9 41 27 AM](https://user-images.githubusercontent.com/85772166/213519980-3cec1b4d-d00c-40fb-9b18-0b0a26396304.png)

`/economy/index hk_hsi`

![Screenshot 2023-01-19 at 9 42 24 AM](https://user-images.githubusercontent.com/85772166/213520142-964dc71a-e622-4fee-af98-4e85362b895f.png)

Two together, no dice:

`/economy/index sp500,hk_hsi`

![Screenshot 2023-01-19 at 9 43 27 AM](https://user-images.githubusercontent.com/85772166/213520302-067361d0-fe91-4410-b248-c00ad36236b4.png)

Plotting using the `plot` function also produces the wrong scale for the second y-axis:

`plot --y1 sp500 --y2 hk_hsi`

![Screenshot 2023-01-19 at 9 45 17 AM](https://user-images.githubusercontent.com/85772166/213520614-8ed6313b-9ecf-4434-abc8-832412ce8e2c.png)

**Comment by JerBouma** [comment]
Happend to be just an artifact from the recent Yahoo Finance changes. Fixed with adding `ignore_tz=True`
