### ISSUE TITLE
[Bug] Error when charting multiple country indices

### ISSUE THREAD

**Issue by jerryduluk** [OpenBB-finance/OpenBBTerminal#4022]
# Bug #
Trying command: `/economy/ $ index --indices sp500,ftse100,jp_n225,hk_hsi -s 2022-01-01`
Only the sp500 is coming up. However, when individually requested, each index is able to load

Add “-r” and I get “Error: local variable “plot_data’ referenced before assignment

![Screenshot 2023-01-19 at 10 57 56 AM](https://user-images.githubusercontent.com/123030228/213535286-03a02a2a-be17-4be9-ae72-d608fe0349d1.png)

**Comment by JerBouma** [comment]
Also related to #4020
