### ISSUE TITLE
[Bug] Terminal update V.2.2.0

### ISSUE THREAD

**Issue by mDull618** [OpenBB-finance/OpenBBTerminal#4039]
**Describe the bug**
After unistall and reinstall Windows10.OpenBB.Terminal.v2.2.0.exe, I recive this message:

OpenBB Terminal v2.1.0 (https://openbb.co) 
You are not using the latest stable version
Check for updates at https://openbb.co/products/terminal#get-started

2023 Jan 23, 23:12 (🦋) / $

**Comment by jmaslek** [comment]
This seems to happen 50/50 for some reason.  We just tested on our end and see the 2.2.0.

The real test is if you run the command `stocks/load appl`

2.1 has a broken version of yfinance.  So if you can load a ticker, you are on 2.2

**Comment by jmaslek** [comment]
We have updated to 2.3.1. Feel free to open any issues related to that!
