### ISSUE TITLE
[Bug] OpenBB SDK compains about not having API_FRED_KEY even though it exists

### ISSUE THREAD

**Issue by jasonstrimpel** [OpenBB-finance/OpenBBTerminal#4042]
**Describe the bug**
I'm attempting to run the `openbb.economy.fred` method in a Jupyter Notebook using the OpenBB SDK.

When I do, I receive a warning: `API_FRED_KEY not defined. Set API Keys in ~/.openbb_terminal/.env or under keys menu.`

I set my FRED API keys in `~/.openbb_terminal/.env` like this:

```
API_FRED_KEY='my_fred_api_key'
```

When I re-run the `openbb.economy.fred` method in a Jupyter Notebook using the OpenBB SDK, I get the same warning.

**To Reproduce**
See above

**Screenshots**
![Screen Shot 2023-01-24 at 05 39 02](https://user-images.githubusercontent.com/908118/214293842-75b9956c-e7a3-431f-ab4c-d7414914ecf0.png)

![Screen Shot 2023-01-24 at 05 39 24](https://user-images.githubusercontent.com/908118/214293868-0ff62ba0-2fc0-4d9c-aca6-5dafb66c99b0.png)

**Desktop (please complete the following information):**

- OS: Mac
- Python version: 3.19.13

**Additional context**
1. After adding the API key to the `.env` file, I shut down the terminal window and Jupyter Notebook instance before trying again. 
2. I tried adding the API both with and without quotes.
3. I tried running the same code from a Python interactive session.

**Comment by jmaslek** [comment]
Will investigate.  An alternative with the sdk would be:

```
openbb.keys.fred(
    key = 'replace_me',
    persist = True,
)
```

Which will replace in the correct env file

**Comment by jasonstrimpel** [comment]
This worked.

**Comment by jmaslek** [comment]
Hey @jasonstrimpel 

Anychance that the original issue has been resolved with the update?

**Comment by hjoaquim** [comment]
Looks like it's fixed now:

![image](https://user-images.githubusercontent.com/48914296/217226265-a93e73a7-03b0-48c0-ac39-f78427e398b4.png)

Disclaimer: this might not behave exactly this way after #4015 is merged.
