### ISSUE TITLE
[IMPROVE] CTRL-C in windows terminal should clear the current line instead of exiting the entire terminal

### ISSUE THREAD

**Issue by jdilley** [OpenBB-finance/OpenBBTerminal#4043]
**What's the feature that should be improved?**
CTRL-C behavior in windows (maybe other platforms too)

**Describe how you would like the feature improved**
CTRL-C in windows should clear the current terminal line instead of exiting

**Possibly describe the ideal way to improve this**
CTRL-C in windows should clear the current terminal line instead of exiting

**Additional information**
every other terminal clears the current line, including windows power shell. this creates accidentally exits which can be very frustrating

**Comment by jmaslek** [comment]
CTRL-C in python raises a KeyBoardInturrupt error.  We went with Linux/Unix convention that the SIGINT generated is meant to stop whatever process you are running.  This is handy if an import or a request hangs and you want to stop the process without having to close

**Comment by jdilley** [comment]
fwiw ipython is a great example of a python based terminal application that handles this properly. you can still keyboard interrupt scripts that are being run without the entire terminal going with it.

you can have what you're saying without having to kill the entire terminal. should i make a new feature request?
