### ISSUE TITLE
[Bug] Open BB installed in my environment in Ananconda

### ISSUE THREAD

**Issue by MKK-64** [OpenBB-finance/OpenBBTerminal#4050]
Facing error in running the below code in Jupyter lab:

ModuleNotFoundError: No module named 'sseclient'

The code is as under:

from openbb_terminal.sdk import openbb
import quantstats as qs

This worked fine then ran the below code:

data = openbb.stocks.load("AAPL", start_date="2012-06-01", end_date="2022-06-30")

**Comment by MKK-64** [comment]
Facing error in running the below code in Jupyter lab:

ModuleNotFoundError: No module named 'sseclient'

The code is as under:

from openbb_terminal.sdk import openbb
import quantstats as qs

This worked fine then ran the below code:

data = openbb.stocks.load("AAPL", start_date="2012-06-01", end_date="2022-06-30")

**Comment by deeleeramone** [comment]
Strange that it didn't get installed with the OpenBB environment. 

Try:
```
pip install sseclient==0.0.27
```

Then restart the kernel.

**Comment by colin99d** [comment]
Closing for now! If you have any questions feel free to let me know.
