### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by bushanka** [OpenBB-finance/OpenBBTerminal#4074]
**Describe the bug**
Throws an errors when displaying the price of crypto in real time.

**To Reproduce**
Go to crypto section, then use command: price -s ETH-USD

**Screenshots**
![image](https://user-images.githubusercontent.com/61285033/215388775-7478dfae-af7c-4479-8a3c-325fd9106d02.png)

**Desktop (please complete the following information):**

- OS: Windows 10

**Comment by hjoaquim** [comment]
Looks like this is a windows specific thing.
Running on ubuntu:

```
2023 Feb 01, 11:51 (🦋) /crypto/ $  price -s ETH-USD

If it takes too long, you can use 'Ctrl + C' to cancel.

ETH-USD = 1581.80292377 ± 0.5529237771827
```

Closing as this is a duplicate with #3411
