### ISSUE TITLE
[IMPROVE] `funds` menu

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#4113]
After the refactor on the fund's menu on #4068 by @Mael-J there are a couple of things that can be improved to match other sections of the terminal.

### Make the `funds` menu usable on:

- **SDK** : currently there is no mapping for the SDK. This might require some work, as the function that loads the asset is returning a custom object `mstarpy.Funds`. Although the other functions then return `pd.Dataframe` this behavior kinda breaks the standard behavior of not having custom objects but dataframes instead.
- **Forecasting menu** : for the same reason as described above - it will require us to pass a usable dataframe to the forecasting menu to work with.

### Deprecate:
- `investpy` dependency - not sure if we're still using it anywhere, if not, the dependency should be removed.
- `investiny` dependency - not sure if we're still using it anywhere, if not, the dependency should be removed.
- `investingcom*.py` (views + models) that are not used anymore.
- remove unit/integration tests related with the above points

### Tests:
- add integration tests for the `funds` menu 
- improve unit test coverage for `funds_controller`, `mstarpy_model` and `mstarpy_view`

**Comment by jmaslek** [comment]
think we have hit everything here except linking to forecast menu.
