### ISSUE TITLE
[Bug] [SDK] `openbb.stocks.ins.lins` - InsecureRequestWarning: Unverified HTTPS request is being made to host 'finviz.com'. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4140]
A warning that is silenced in the Terminal, but the SDK returns with it.

`openbb.stocks.ins.lins('VZ')`

```
InsecureRequestWarning: Unverified HTTPS request is being made to host 'finviz.com'. 
Adding certificate verification is strongly advised. 
See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings warnings
  ```

**Comment by montezdesousa** [comment]
Might have been removed, I can't reproduce it. If this pops up again feel free to reopen this issue

<img width="905" alt="Screenshot 2023-02-25 at 19 15 26" src="https://user-images.githubusercontent.com/79287829/221375503-8184578b-6beb-4022-bdbb-af6137630d36.png">
