### ISSUE TITLE
[Bug] After installing the new DMG version, the Terminal fails to launch - ValueError: 'macos' is not a valid value for backend;

### ISSUE THREAD

**Issue by BychkovRY** [OpenBB-finance/OpenBBTerminal#4141]
**Describe the bug**
After install new version, I started OpenBB Terminal and got the message

 Traceback (most recent call last):
  File "terminal.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "openbb_terminal/helper_funcs.py", line 50, in <module>
  File "matplotlib/init.py", line 1129, in use
  File "matplotlib/rcsetup.py", line 255, in validate_backend
  File "matplotlib/rcsetup.py", line 82, in call
ValueError: 'macos' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'GTK4Agg', 'GTK4Cairo', 'MacOSX', 'nbAgg', 'QtAgg', 'QtCairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
[1715] Failed to execute script 'terminal' due to unhandled exception!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed. 

**To Reproduce**
Clean install and try to run

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ventura 13.1
- Python version 3.10

**Additional context**
In your discord I found solution
hi there! we can fix this. Go to the application folder and show hidden files with shift+command+period. Then inside the folder: ~/Applications/OpenBB Terminal/.OpenBB/ is a file called .env. Open that in a text editor and place this at the bottom: OPENBB_BACKEND='MacOSX'

Could you fix .env that you include in .dmg?

**Comment by deeleeramone** [comment]
This is odd that it would revert to this setting. Can you look in the `.env` file which is in this location:
```
~/.openbb_terminal/.env
```
Add to the bottom:
```
OPENBB_BACKEND='MacOSX'
```
Does this resolve the issue?

**Comment by BychkovRY** [comment]
After install /.env does't have this parameter. If I add it manually - everything will be ok and terminal will run correctly

**Comment by deeleeramone** [comment]
Thanks for the information.

**Comment by piiq** [comment]
unable to reproduce this error. matplotlib has it's own mechanism for choosing the backend and it is supposed to select the macos one automatically. i can assume that there is a matplotlibrc file not created by openbb that specifies the macos backend with a wrong string ('macos' vs 'MacOSX'). we don't set that on the terminal level as of now

**Comment by BychkovRY** [comment]
I have 2 matplotlibrc only in venv folders for other projects. In both files 'macos'not defined as parameter

**Comment by piiq** [comment]
Can you tell a bit more about your machine, please?
Is it an apple silicon or an intel mac? What's the OS version?
Do you do other python development? Maybe jupyter lab installed in an environment or as a desktop app?

**Comment by BychkovRY** [comment]
MacBook Pro 16'' 2019, Intel, MacOS - Ventura 13.1 (22C65).
I have Pycharm as Development environment, I have installed Jupyter notebook as environment (I run it when I need it. It turn off by default)

**Comment by colin99d** [comment]
Hello,
We have changed how we show charts, so you should no longer be experiencing this issue.
