### ISSUE TITLE
[Bug] Stocks/FA/enterprise - Error: 'Namespace' object has no attribute 'source'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4154]
Just trying out the latest merge to the develop branch, the ticker loaded is AAPL.

```
2023 Feb 06, 18:27 (🦋) /stocks/fa/ $ enterprise

Error: 'Namespace' object has no attribute 'source'
```

**Comment by JerBouma** [comment]
?

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/46355364/217271311-f0a15080-397c-4878-bb09-e0a1235deef7.png">

**Comment by deeleeramone** [comment]
It works on the main branch:
![Screenshot 2023-02-07 at 6 32 07 AM](https://user-images.githubusercontent.com/85772166/217273680-33aaf62c-09b2-4f84-8f05-0af4f2cfa5c4.png)


On Develop branch, I get the changes to the menu, but `enterprise`  does not work. 
```
(obb-m1) Danglewoods-MacBook-Pro:OpenBBTerminal danglewood$ git branch
* (HEAD detached at origin/develop)
```

![Screenshot 2023-02-07 at 6 35 39 AM](https://user-images.githubusercontent.com/85772166/217274411-d00dbcd2-58e4-4b7f-bc09-973351736af2.png)

**Comment by JerBouma** [comment]
What commit are you on, I am on the develop branch.

**Comment by JerBouma** [comment]
Seems your `data_sources_default.json` is not updated. Please pull the latest develop commit.

**Comment by deeleeramone** [comment]
`HEAD is now at ef12295f33 Remove code of legacy jupyter lab extensions from the repo (#4146)`

**Comment by JerBouma** [comment]
See this file: https://github.com/OpenBB-finance/OpenBBTerminal/blob/develop/openbb_terminal/miscellaneous/data_sources_default.json. Yours is old.

**Comment by deeleeramone** [comment]
I think you're the one with old code, your branch is missing a function that was added in 2.3.1:
 
![Screenshot 2023-02-07 at 6 46 18 AM](https://user-images.githubusercontent.com/85772166/217277385-435e8ed5-76e3-44de-88c7-8635ccbc835b.png)

This is yours:
![Screenshot 2023-02-07 at 6 44 29 AM](https://user-images.githubusercontent.com/85772166/217276780-dfb7b530-1627-44c6-8e62-07cc0ef5aa0b.png)

**Comment by JerBouma** [comment]
Just to make sure we aren't missing anything, nuked my entire repo and pulled everything back and still same effect. This is on @deeleeramone side. Closing issue.

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/46355364/217278577-a84e7c1f-d709-4fac-8fe0-1bb68d55cb7b.png">

**Comment by JerBouma** [comment]
Please delete your entire repo and pull everything back in and check back with us if it still doesn't work.

**Comment by deeleeramone** [comment]
I'm looking directly on GitHub at data_sources_default.json file. Deleting my entire repo will do nothing for this. It is missing the filings function.

**Comment by JerBouma** [comment]
It's merged into `sec` but you won't see that since.. older version.

**Comment by deeleeramone** [comment]
what? I think you're talking about something else entirely.

**Comment by deeleeramone** [comment]
This function is not part of the FA menu, and is not supposed to be. 

![Screenshot 2023-02-07 at 6 57 38 AM](https://user-images.githubusercontent.com/85772166/217280272-f9b10587-e7b2-47b4-86e0-31b8d6903d75.png)

**Comment by deeleeramone** [comment]
Please stop telling me I have an "old version". How is that possible?

> It's merged into `sec` but you won't see that since.. older version.

![Screenshot 2023-02-07 at 7 00 43 AM](https://user-images.githubusercontent.com/85772166/217281074-e32dfd30-5e91-443e-bf80-168e839f738e.png)

**Comment by deeleeramone** [comment]
Please restore the filings function to it's original location and with the functionality that was included with it.

**Comment by JerBouma** [comment]
I've nuked my entire repository, deleted everything and pulled it back in. No issue whatsoever regarding `enterprise`. Given I see all the sources missing in your screenshot I see that there is something going wrong in your repository. Also given @jmaslek has no issues either, it must be something in your repository which is why I ask you to make a new one to validate.

No one can reproduce this issue so far.

**Comment by deeleeramone** [comment]
I found the culprit. Deleting my folder would not have done anything for it, as it is an `.env` thing. The `/settings` menu does not take kindly to changes to the `/settings/source`. Had to manually change the .env file.
