### ISSUE TITLE
Exception installing OpenBB SDK because missing Rust package manager

### ISSUE THREAD

**Issue by jasonstrimpel** [OpenBB-finance/OpenBBTerminal#4159]
**Describe the bug**

The pip installation of the OpenBB SDK in a fresh conda virtual environment running Python 3.9.6 fails. The failure is caused because the dependency `y-py<0.6.0,>=0.5.3` requires Cargo (the Rust package manager) to be on `PATH`.

I understand what the bug is telling me (I need Cargo on `PATH`) but this is a new bug (successfully installed the OpenBB SDK last week) and Rust is not a documented dependency.

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

```
$ conda create -n newsletter python=3.9.6 -y
$ conda activate newsletter
$ pip install openbb
```

**Screenshots**

![Screen Shot 2023-02-07 at 06 25 16](https://user-images.githubusercontent.com/908118/217257082-22060427-bd29-4334-89b7-33bf26d7d97a.png)
**Desktop (please complete the following information):**

- OS: macOS Monterey v12.5 (M2)
- Python: Conda virtual environment v 3.9.6

**Comment by piiq** [comment]
Can replicate the issue but I can't yet trace who's pulling y-py. It relates to a technology that's used by jupyter project to enable real-time collaboration on the notebooks. We haven't noticed problems with this part of the dependencies before

**Comment by jmaslek** [comment]
It looks like you can do this:

```
pip install y-py==0.5.4
pip install openbb
```

We are working on a hotfix.  Looks like something in our deps didnt pin y-py and the most recent didnt provide some binaries we want
