### ISSUE TITLE
[Bug] Report rendering can't handle save path for users that have a period (.) in username

### ISSUE THREAD

**Issue by tys203831** [OpenBB-finance/OpenBBTerminal#4174]
**Describe the bug**

When I try to run `\reports\economy` or `\reports\run -f test.ipynb", it will show the error as below:

`Error: output folder C:\Users\**test_user**\OpenBBUserData\reports doesn't exist.`

The problem is that my windows username is actually **test.user** instead of **test_user**. It wrongly recognize the full stop (.) to an underscore (_).

**To Reproduce**
1. Use windows and create an user called <any words>.<any words> as long as the full stop (.) exists inside the username.
2. Run `\reports\economy` or `\reports\run -f test.ipynb"

**Screenshots**
<img width="853" alt="report-bug" src="https://user-images.githubusercontent.com/64836390/217565257-da5c3902-f949-4424-b992-4b48d32d06af.png">

**Desktop (please complete the following information):**

- OS: Version 22H2 (OS Build 22621.1194)
- Python version: .10.8

Thanks for creating such amazing platform.

**Comment by tys203831** [comment]
Kindly advise me where the code can be amended to make it works. Thanks.

**Comment by piiq** [comment]
Thanks for the reporting @tys203831 

To fix change this 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/11668535/217661803-2007a18d-a498-4d52-afc2-e31f15a5e6bf.png">

to this
<img width="706" alt="image" src="https://user-images.githubusercontent.com/11668535/217661914-4ebf3117-ba76-4c3a-a416-52cd47b8bd29.png">

that's in `openbb_terminal/reports/reports_model.py`

feel free to submit a PR with this change

**Comment by tys203831** [comment]
Hi, thanks for helping. However, it seems does not work to me.

As I found that openbb install its python in library at "C:\Users\test.user\OpenBB\openbb_terminal\", I go to the directory: "C:\Users\test.user\OpenBB\openbb_terminal\reports\reports_model.py" that you suggested.

I amend the code that you suggest as below. Yet, the error still persists.
 
![image](https://user-images.githubusercontent.com/64836390/217864286-c9786065-316e-4907-a8f6-35391307382c.png)

**Comment by piiq** [comment]
What installation method are you using for the terminal? How did you install the application?

**Comment by tys203831** [comment]
> What installation method are you using for the terminal? How did you install the application?

through Windows Installer: https://docs.openbb.co/terminal/quickstart/installation

**Comment by tys203831** [comment]
I use python to install the app: https://docs.openbb.co/terminal/quickstart/installation

and then I amend the code there. It works now. Thanks @piiq.

**Comment by piiq** [comment]
> I use python to install the app: https://docs.openbb.co/terminal/quickstart/installation
> 
> 
> 
> and then I amend the code there. It works now. Thanks @piiq.

Great to hear that!
Do you want to make a PR with this contribution or you prefer us to do that?
