### ISSUE TITLE
[IMPROVE] Remove functions that don't belong.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4180]
This menu presents itself as confusing. Functions related to the screener presets should be separated from the other functions. A screener is for screening the entire market, and not for analyzing an individual ticker.

![Screenshot 2023-02-08 at 3 52 38 PM](https://user-images.githubusercontent.com/85772166/217678469-7a279f18-c062-44c4-86e7-15870ed511b2.png)

The `historical` function doesn't even make sense, and should be removed. How is it a screener?
```
2023 Feb 08, 18:51 (🦋) /stocks/scr/ $ historical


The limit of stocks to compare with are 10. Hence, 10 random similar stocks will be displayed. 
The selected list will be: BANR, BGRY, EAR, HOTH, PSNL, SQL, STRRP, UA, XIN, YQ
```

![Screenshot 2023-02-08 at 3 56 29 PM](https://user-images.githubusercontent.com/85772166/217678775-c4faab8e-6c32-48f1-9f6a-a993c5ad15fa.png)

**Comment by JerBouma** [comment]
Please specify which and where they should go in your opinion.
