### ISSUE TITLE
[Bug] Stocks/FA/Overview - There was an error connecting to the API. Please try again later.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4202]
This is an intermittent issue with Finviz. Also happens occasionally with any Finviz function.

1) Error message is not helpful. 
2) Not so much a bug, but I loaded a ticker using `--source`, which means I specifically want data from `--source`. Every API has this data, `load` should == `load` and follow `--source`, and the workflow that follows should respect that choice. 

![Screenshot 2023-02-09 at 10 24 46 PM](https://user-images.githubusercontent.com/85772166/218018479-60b48d74-c13d-4492-b257-7e421f51e552.png)

**Comment by JerBouma** [comment]
Does it work with something like MSFT? Error message is indeed unhelpful.

**Comment by deeleeramone** [comment]
It is intermittent. It happens from time-to-time for any Finviz-source function, and while it usually corrects itself by repeating the data request, having this as a default source [choice 1] will inevitably break user scripts unnecessarily.

**Comment by JerBouma** [comment]
Alright, can you make a quick PR changing the source around? Should be relatively simple to do by adjusting https://github.com/OpenBB-finance/OpenBBTerminal/blob/develop/openbb_terminal/miscellaneous/data_sources_default.json from Finviz to for example FinancialModelingPrep.

**Comment by colin99d** [comment]
I spammed this pretty heavily and every request was successful, is this still and issue for you @deeleeramone?

**Comment by deeleeramone** [comment]
I do get the error occasionally, and it can randomly appear from any FinViz function, but does not persist if you run it again.
