### ISSUE TITLE
[Bug] Stocks/FA/Cash - Value for CIK number and Calendar Year is X.XXX M/K

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4203]
![Screenshot 2023-02-09 at 10 52 29 PM](https://user-images.githubusercontent.com/85772166/218023152-08925373-3d3a-4689-b7d9-962a0c9cc915.png)

Calendar year is converted where is shouldn't be.

![Screenshot 2023-02-09 at 10 54 32 PM](https://user-images.githubusercontent.com/85772166/218023222-82a9eefa-87e4-4fda-88fe-7d390b032748.png)

**Comment by deeleeramone** [comment]
Also applies to `balance` and `income`. Seems to be an error with parsing FinancialModellingPrep data specifically.

**Comment by hjoaquim** [comment]
@JerBouma @deeleeramone could you help me with some more context, please? What's the expected output?

**Comment by JerBouma** [comment]
You can use https://financialmodelingprep.com/api/v3/income-statement/AAPL?limit=120&apikey=YOUR_API_KEY to see an example (change the API key).

![Screenshot_20230210-100913.png](https://user-images.githubusercontent.com/46355364/218050665-f438e15a-e9d1-47cd-8a57-7b37a7c18d63.png)

Make sure it represents the numbers you see here while the financial items of the report do get converted.

**Comment by deeleeramone** [comment]
> @JerBouma @deeleeramone could you help me with some more context, please? What's the expected output?

CIK - Central Index Key 

A Central Index Key or CIK number is a unique number assigned to an individual, company, filing agent or foreign government by the [United States Securities and Exchange Commission](https://en.wikipedia.org/wiki/United_States_Securities_and_Exchange_Commission). The number is used to identify its filings in several online databases, including [EDGAR](https://en.wikipedia.org/wiki/EDGAR).

The numbers are up to ten digits in length and are permanent identifiers that may not be changed.

**Comment by jmaslek** [comment]
> @JerBouma @deeleeramone could you help me with some more context, please? What's the expected output?

If the year is 2023 it should say 2023, not 2.023 k

**Comment by hjoaquim** [comment]
^ thank you for the clarification @jmaslek @JerBouma @deeleeramone
