### ISSUE TITLE
Reports `equity` command failed to create ipynb notebook

### ISSUE THREAD

**Issue by tys203831** [OpenBB-finance/OpenBBTerminal#4223]
**Describe the bug**
I expect when I type `reports\equity`,  both ipynb and html equity report will be generated. It works for other reports such as crypto, economy, but only not working for equity report.

For your reference, here is the bug shown inside the ipynb file generated from the command `\reports\equity`:
<img width="551" alt="Code_8IXBSbVXis" src="https://user-images.githubusercontent.com/64836390/218296509-6bb24cbd-5cce-48c3-8050-6f9a9a9e565d.png">

Referring to this image, I suspect that the "Long business summary" in the ipynb file is not longer extractable from yfinance anymore and so thus, it will generate a KeyError for that when we tried to run it on ipynb file:

For your info, I have also attached the ipynb file generated as the text file at the most bottom part of this bug report. Or you could refer here: 

Text file (as .ipynb file format is not supported here): https://paste.ee/p/lKP3V
<Instructions: Copy the content of above file and then save this file as .ipynb file>

**To Reproduce**
Step 1: type `reports`
Step 2: type `equity`

**Screenshots**
<img width="849" alt="WindowsTerminal_syhUbTxDyJ" src="https://user-images.githubusercontent.com/64836390/218296409-640002ec-3738-4517-9958-4836845df4c3.png">

**Desktop (please complete the following information):**
- OS: Windows 11 Pro
- Python version: 3.9.12

**Installation method:**
- using conda and poetry as instructed here: https://docs.openbb.co/terminal/quickstart/installation

**ipynb file created with error inside**
Text file (as .ipynb file format is not supported here): https://paste.ee/p/lKP3V
<Instructions: Copy the content of above file and then save this file as **.ipynb** file>

**Comment by deeleeramone** [comment]
Hi there, this is because of all of the yFinance issues. #4212 for example.
