### ISSUE TITLE
[IMPROVE] Cache on long-running command

### ISSUE THREAD

**Issue by arisliang** [OpenBB-finance/OpenBBTerminal#423]
**What's the feature that should be improved?**
Some command takes longer time to run, e.g. dd->dp, which might take 1.5 minute or so.

It would be nice if it can be cached to some period of time, especially after market close, to improve those long-running command's performance.

**Describe how you would like the feature improved**
The first command run would still take that long, but subsequent run within the cache validity would return much faster.

**Possibly describe the ideal way to improve this**
Add cache for command, especially after market close.

**Additional information**
Most command probably doesn't need this, just the long-running ones, like things running longer than 10s or so.

**Comment by andrewkenreich** [comment]
https://github.com/OpenBB-finance/OpenBBTerminal/pull/4268

An attempt was made here - going to close this.

Improvements need to be made to this to check market times and allow users to set or not set it, among other things.
