### ISSUE TITLE
Hedge Fund Mangers Portfolio Data[FR]

### ISSUE THREAD

**Issue by shivansh2310** [OpenBB-finance/OpenBBTerminal#4258]
**What's the problem of not having this feature?**
Every large hedge fund manager had his or her approach to the market, which was very visible in their portfolio. So, by including hedge fund managers' portfolio data in the platform, users can access the insights of the market's professional players and analyse macro to sectorial cyclic trends through which types of stocks are being bought and sold by the top hedge fund managers.

**Describe the solution you would like**
Because we already have a subsection of government data in the stocks section, we can create a similar type of Hedge Fund Section in the Main menu where users can go and see top buys, top sells, Trades, portfolios, and so on. We can begin by selecting some of the top ten hedge funds and then simply adding to this data.

**Describe alternatives you've considered**
https://strike.market/funds

This dedicated platform mainly deals in hedge fund portfolio data where we can see what type of stock the world's best investors ka buying and selling.

**Comment by deeleeramone** [comment]
There is a good, free, resource for monitoring the hedge fund world here: https://nilssonhedge.com/

The only difference between requesting SEC forms for a fund, instead of a company, is the requirement to lookup by CIK. A dictionary of (Funds, CIKs) would be a good thing to compile as a helper function.

```
2023 Feb 15, 12:44 (🦋) /stocks/disc/ $ filings

Timestamp: 2023-02-15 12:39:30  US/Eastern
Ticker: None
CIK: 1423296
Form Type: 13F-HR
13F-HR - Zuckerman Investment Group, LLC (0001423296) (Filer)
https://www.sec.gov/Archives/edgar/data/1423296/000142329623000002/0001423296-23-000002-index.htm
```

**Comment by shivansh2310** [comment]
Thanks for the heads up
