### ISSUE TITLE
[Bug] `Stocks/FA/SEC --source FinancialModelingPrep` does not work, no results for 'Ticker'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4259]
![Screenshot 2023-02-15 at 9 21 16 AM](https://user-images.githubusercontent.com/85772166/219105096-ac69b990-3ab3-4094-adcf-f5938fbc959f.png)

```
2023 Feb 15, 11:20 (🦋) /stocks/fa/ $ load aapl

Loading Daily data for AAPL with starting period 2020-02-11.

2023 Feb 15, 11:22 (🦋) /stocks/fa/ $ sec --source FinancialModelingPrep

No filings found for ticker AAPL, consider increasing the value for --pages. Showing recent filings instead.
```

If no results are found for the ticker, how would increasing the number of pages help? Is this function hitting the right end point?

`https://financialmodelingprep.com/api/v3/sec_filings/AAPL?type=10-K&page=0&apikey=YOUR_API_KEY`

![Screenshot 2023-02-15 at 9 30 08 AM](https://user-images.githubusercontent.com/85772166/219107291-93f3861e-3cb1-4701-86e3-c88ad17b4ebd.png)

The output of this function is better suited as a `console.print` output because all URLs are truncated, and broken, when bound by a table. Wrapping the text in the column also does not allow for copy/paste because selecting text in the CL doesn't respect column boundaries. 

![Screenshot 2023-02-15 at 9 22 13 AM](https://user-images.githubusercontent.com/85772166/219105299-e90260bd-d1d5-4b7f-9fd7-1f2712e36ebe.png)

Adding a filter for the `Form Type` would increase the utility of this function.

**Comment by colin99d** [comment]
It looks like with our newest update, sec and rating are not working at all, I will get on fixing them.

**Comment by colin99d** [comment]
If you increase the number of pages, you are more likely to find relevant information (in FMP only). Other concerns will be fixed by Jose's new charts.
