### ISSUE TITLE
[Bug] `Stocks/FA/income --plot`: Error: could not convert string to float: 'USD'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4277]
The same errors happens using `balance` and `cash`.

Recreate with:
```
/stocks/load AAPL/fa/income --plot revenue
```

```
2023 Feb 17, 22:21 (🦋) /stocks/fa/ $ income --plot revenue

Error: could not convert string to float: 'USD'
```

The help dialogue has conflicting statements for the `--plot` argument. Are we plotting a column, or a row? Not clear.

![Screenshot 2023-02-17 at 7 25 02 PM](https://user-images.githubusercontent.com/85772166/219829176-8454072a-c199-4191-8723-f08efe4f7c3c.png)

Presented choices are begging for the function to fail:

![Screenshot 2023-02-17 at 7 28 45 PM](https://user-images.githubusercontent.com/85772166/219829311-c85a4091-112a-4fb9-a1ff-937dd746d5e4.png)

```
2023 Feb 17, 22:21 (🦋) /stocks/fa/ $ income --plot cik

Error: could not convert string to float: 'USD'


2023 Feb 17, 22:21 (🦋) /stocks/fa/ $ income --plot revenue

Error: could not convert string to float: 'USD'


2023 Feb 17, 22:22 (🦋) /stocks/fa/ $ income --plot link

Error: could not convert string to float: 'USD'


2023 Feb 17, 22:27 (🦋) /stocks/fa/ $ income --plot eps

Error: could not convert string to float: 'USD'
```

Unclear why only row[0] is of interest when the key value is changing. Certainly no need to plot the filing date against the Fiscal Year. 

The docstrings "description" are strange. Why only AlphaVantage

**Comment by jmaslek** [comment]
#4142
