### ISSUE TITLE
[Bug] openbb-stocks-sia fails with yfinance error

### ISSUE THREAD

**Issue by kajdo** [OpenBB-finance/OpenBBTerminal#4283]
**Describe the bug**
when i access stocks/sia without a stock loaded, the menu works to enter the menu - but when a stock is loaded (tried with JNJ) it fails with Error: yfinance failed to decrypt Yahoo data response

**To Reproduce**
stocks/load jnj/sia

**Screenshots**
![image](https://user-images.githubusercontent.com/8735942/219899892-14cde6af-1cfd-415d-aed2-e854499ed7ef.png)

**Desktop (please complete the following information):**

- OS: Linux mint 5.15.0-56-generic 
- Python version: Python 3.10.6

**Comment by deeleeramone** [comment]
```
2023 Feb 19, 01:01 (🦋) /stocks/ $ sia

Error: yfinance failed to decrypt Yahoo data response
```

Yup. Guess it's time to completely rethink this menu, eh @jmaslek?

**Comment by jmaslek** [comment]
yeah.  I found a patch for now.
