### ISSUE TITLE
[Bug] stocks-enterprise throws an error Namespace object has no attribute 'source'

### ISSUE THREAD

**Issue by kajdo** [OpenBB-finance/OpenBBTerminal#4284]
**Describe the bug**
tried to check the enterprise report with loaded jnj

**To Reproduce**
stocks/load jnj/enterprise

**Screenshots**
![image](https://user-images.githubusercontent.com/8735942/219900586-f98c27bb-edf1-4d87-b3e1-ca64d18e5515.png)

**Desktop (please complete the following information):**

- OS: Linux mint 5.15.0-56-generic
- Python version 3.10.6

**Comment by deeleeramone** [comment]
Same as #4285

**Comment by kajdo** [comment]
I should be on the current version -- did a fresh install
![image](https://user-images.githubusercontent.com/8735942/219969649-6598ec96-ce8f-45b2-855b-ef644dd47a98.png)

but you're right -- removed my datasources from the user directory and it works again ... think it was some legacy config from new years yf issue where I tried to change datasources to get openbb up and running
