### ISSUE TITLE
[FR] Provide/document a way to use this package on Kaggle

### ISSUE THREAD

**Issue by lcrmorin** [OpenBB-finance/OpenBBTerminal#4310]
I often participate in Kaggle comp. and I Sometimes illustrate some work / exploration with real data. Generally I pull market data from yfinance and other API. I was trying to 'upgrade' to openBB. However I am not able to install the package with standard approaches. 

I was wondering if there is a simple way to install openBB in a Kaggle environement. It could be a good source of visibility for the package. If there is, could it be documented ?

(I will make a similar post on kaggle forum, so as to involve Kaggle team / other Kagglers; post is here: https://www.kaggle.com/discussions/product-feedback/389086)

**Comment by jmaslek** [comment]
I've tried before. One of the issues I ran into was that kaggle was using a runtime of 3.7 whereas openbb requires 3.8.

I'm not sure if they have updated (google colab recently did).  In colab I am able to run !pip install openBB and use it out of the box.

Can't say I have tried recently, but not sure if it will be possible at the moment.
