### ISSUE TITLE
[Bug] `/sources` Can't enter menu - Error: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4311]
![Screenshot 2023-02-20 at 1 52 27 PM](https://user-images.githubusercontent.com/85772166/220203739-ec1a9b91-468e-4ceb-8c3a-6457f481a217.png)

**Comment by elyanah-aco** [comment]
Also got the same error. Upon checking, this seems to be caused by `data_sources_default.json` being empty. Maybe we should investigate when and why it saves as an empty file?

**Comment by jmaslek** [comment]
Looks like it is pointing to the wrong spot.  It is looking in 

```
OpenBBUserData / data_sources_default.json
```

When it should be looking into MISCELLANEOUS_DIRECTORY.  Ill try a fix real quick
