### ISSUE TITLE
[Bug] sdk doesn't respect local keys

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBBTerminal#4316]
**Describe the bug**
My branch is synced with develop. When trying to use the sdk the keys and settings in ~/.openbb_terminal/.env  are not recognized.

 
![image](https://user-images.githubusercontent.com/11668535/220400127-d1252604-da03-49b8-8f0f-aba90f0ad70f.png)

**Comment by Chavithra** [comment]
Fixed by PR #4357
