### ISSUE TITLE
[IMPROVE] The charts plotted within `funds` are massive in terms of size

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4326]
When using any of the plotting capabilities plots seem to map the entire screen.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/221177145-81f22d56-31c2-4805-9c72-1bf27eae8279.png">

As a reference, this does not happen in other menus.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/221177263-379fe3bd-698f-4a50-89bc-cc2d0d597b4b.png">

**Comment by deeleeramone** [comment]
related to #4276

**Comment by jmaslek** [comment]
was addressed with library change
