### ISSUE TITLE
[Bug] Docker image is not working

### ISSUE THREAD

**Issue by GiftofHermes** [OpenBB-finance/OpenBBTerminal#4331]
**Docker image is not working**
On a fresh install of a ubuntu and docker, docker image is not building properly.

**To Reproduce**
curl -o docker-compose.yaml https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.yaml

xhost +local:
docker compose run openbb

Traceback (most recent call last):
  File "/home/python/terminal.py", line 5, in <module>
    from openbb_terminal.terminal_helper import is_auth_enabled
  File "/home/python/openbb_terminal/terminal_helper.py", line 18, in <module>
    from openbb_terminal import (
  File "/home/python/openbb_terminal/feature_flags.py", line 17, in <module>
    paths_helper.init_userdata()
  File "/home/python/openbb_terminal/core/config/paths_helper.py", line 75, in init_userdata
    create_paths(dirs_list)
  File "/home/python/openbb_terminal/core/config/paths_helper.py", line 27, in create_paths
    dirs.mkdir(
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/python/OpenBBUserData/styles'

- OS: Ubuntu

**Comment by deeleeramone** [comment]
hey! you need to explicitly give Docker permission to access folders.

https://phoenixnap.com/kb/docker-permission-denied

**Comment by GiftofHermes** [comment]
Hello, I tried running docker compose with sudo but I get the same exact error. sudo should have fixed it if it was a permission issue right? 

```
sudo docker compose run openbb
Traceback (most recent call last):
  File "/home/python/terminal.py", line 5, in <module>
    from openbb_terminal.terminal_helper import is_auth_enabled
  File "/home/python/openbb_terminal/terminal_helper.py", line 18, in <module>
    from openbb_terminal import (
  File "/home/python/openbb_terminal/feature_flags.py", line 17, in <module>
    paths_helper.init_userdata()
  File "/home/python/openbb_terminal/core/config/paths_helper.py", line 75, in init_userdata
    create_paths(dirs_list)
  File "/home/python/openbb_terminal/core/config/paths_helper.py", line 27, in `create_paths`
    dirs.mkdir(
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/python/OpenBBUserData/styles
```

**Comment by deeleeramone** [comment]
No, you have to explicitly give Docker permission for each `PATH`. I believe `chown` is what you are looking for.

**Comment by colin99d** [comment]
Did this resolve the issue @GiftofHermes?

**Comment by GiftofHermes** [comment]
As far as I understand the docker image is not configured correctly and the issue is not related to file permissions of my computer. I haven't tried changing the dockerfile myself

**Comment by bitcoiner-dev** [comment]
I am running into the same issue.

**Comment by franalbani** [comment]
Same problem here. I tried many workarounds with no luck. I will keep trying.

**Comment by ferdinandhubbard981** [comment]
Same issue. I don't think this is an issue with the docker setup, but with the Dockerfile or the command

**Comment by ferdinandhubbard981** [comment]
https://github.com/OpenBB-finance/OpenBBTerminal/issues/3763
They seem to have a solution to this in this issue.
I think this should be added to the docker setup instructions on the website.

**Comment by andrewkenreich** [comment]
Fix for this issue is 

sudo chown USERNAME: .openbb_terminal
sudo chown USERNAME: OpenBBUserData

wish username being the name of your user

You can run this from your user home folder
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/23067478/3b82267e-87a5-416d-94d4-06f9bff01e35)


We are looking into fixing this in the next release

**Comment by Panos277** [comment]
Change the path in the docker-compose yaml from /home/python to /home/user/python etc. and it will work just fine

**Comment by GiftofHermes** [comment]
Has this issue have been fixed?

**Comment by tidux** [comment]
This is an SELinux problem.  Add `:Z` to the mount names and add `--rm` as a parameter to `docker compose run`.
