### ISSUE TITLE
[FR] Real Time Data Updates Feature

### ISSUE THREAD

**Issue by ranjan2829** [OpenBB-finance/OpenBBTerminal#4346]
Dear [Product/Service Team],

[Provide real time Data updates and chart updates with in-detailed macroeconomics ]

I believe that this feature would be particularly useful for traders. Additionally, it would help differentiate your product/service from others in the market.

Thank you for your time and attention to this matter. If you need any additional information or would like to discuss this further, please do not hesitate to contact me.

**Comment by deeleeramone** [comment]
Hi, @ranjan2829,

Can you please provide specific examples of what you mean by, "chart updates with in-detailed macroeconomics"?

The terminal requests data and those end points are not streaming web sockets. What data source, specifically, are you hoping to have real-time data for? Please be specific.

**Comment by masq6r** [comment]
Can we reopen this issue? I can give you a scenario for this request: doing a backtest and make OpenBB Workspace a GUI which shows the current state of the backtest which includes the real-time equity curve update.
