### ISSUE TITLE
[Bug] Stocks/FA/DCF - error when ticker not supported: Error: __init__() should return None, not 'list'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4348]
There should be a pleasant message to indicate the ticker is not supported, US-listings only. 

![Screenshot 2023-02-27 at 11 53 42 AM](https://user-images.githubusercontent.com/85772166/221668973-75bca7f5-54c9-421c-a634-52fb14ddada4.png)

**Comment by BeastOfBodmin** [comment]
I see this for US tickers too:

```
2023 Apr 02, 04:53 (🦋) /stocks/fa/ $ dcf -t BRK.B

Error: 'BRK.B'

Error: __init__() should return None, not 'list'


2023 Apr 02, 04:53 (🦋) /stocks/fa/ $ dcf -t ELV

Error: 'ELV'

Error: __init__() should return None, not 'list'
```

**Comment by deeleeramone** [comment]
@colin99d 

![Screenshot 2023-04-03 at 11 01 57 AM](https://user-images.githubusercontent.com/85772166/229590260-71223991-51b6-4edd-ae90-062261fcf3bb.png)

![Screenshot 2023-04-03 at 11 03 30 AM](https://user-images.githubusercontent.com/85772166/229590564-31a730a7-f9c0-4e60-bb81-7e932f1fa3c9.png)

**Comment by andrewkenreich** [comment]
@colin99d not sure this is how we want to handle this - dont think we should add a try except around it all if its something more underlying here. why would these 2 fail ?

**Comment by colin99d** [comment]
The problem is that the website has to have the data, and a lot of times it just doesn't. The reason I added a try except around the whole thing, is that originally I added raises where bad things happen, but I dont catch them in the terminal. This leads to the bad looking outputs you can already see. 
If you want me to find another solution, I would be more than happy to look into it, but at the end of the day, if the ticker isn't on the website we can't get data for it.

**Comment by deeleeramone** [comment]
What is the data is actually required to populate the spreadsheet? What exactly is the data which is unique to this site only? 

The source for the fundamentals data on Stock Analysis is: 

```
Source: Financials are provided by [Nasdaq Data Link](https://data.nasdaq.com/) and sourced from the audited annual ([10-K](https://www.sec.gov/cgi-bin/browse-edgar?CIK=0001675149&type=10-K)) and quarterly ([10-Q](https://www.sec.gov/cgi-bin/browse-edgar?CIK=0001675149&type=10-Q)) reports submitted to the Securities and Exchange Commission (SEC).
```

Financial statements are pretty easy to come by, why are we stuck with this one website/source?

**Comment by colin99d** [comment]
This was the only website that provides enough detail, years of dating, and where A = L + E. I don't love it either. But it is the best I have found. If you are able to create a scraper of Nasdaq and have A = L + E consistently, I would love to switch to that.

**Comment by colin99d** [comment]
@deeleeramone its a lot of data required to populate. Every column in the DCF. With as many years in the past as possible.

**Comment by OussamaLouhaibi** [comment]
<img width="528" alt="Screenshot 2023-07-26 at 00 52 58" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/101013300/15431bfc-4de4-4057-805e-a7e64c834e2e">

any ideas about this error here?

**Comment by deeleeramone** [comment]
Are you using the latest version? 

![Screenshot 2023-07-25 at 7 16 52 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/bdf4061b-e901-497b-bf1f-9b93bb928276)
