### ISSUE TITLE
[Bug] [SDK] Crypto/Load - Default source (CoinGecko) is returning bad data. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4367]
![Screenshot 2023-03-01 at 10 13 38 AM](https://user-images.githubusercontent.com/85772166/222226218-de6c94c3-f170-484f-833d-7c2a142a39e4.png)

**Comment by deeleeramone** [comment]
![Screenshot 2023-03-01 at 11 40 24 AM](https://user-images.githubusercontent.com/85772166/222247071-449d2333-c73e-40be-8ae9-a7519f45c5b1.png)

**Comment by hjoaquim** [comment]
Hello @deeleeramone !
Could you pls help me with some more context? What's exactly the issue?

**Comment by deeleeramone** [comment]
> I don't think this is a bug, that's the way `coingecko` provides the data. Here's an example:
> 
> ![image](https://user-images.githubusercontent.com/48914296/231203031-3e1abcf9-0379-4322-9851-7381d420627b.png)
> 
> We can check that's also the case here:
> 
>     * docs: https://www.coingecko.com/en/api/documentation
> 
>     * the above request: https://api.coingecko.com/api/v3/coins/bitcoin/ohlc?vs_currency=usd&days=90

Here's the bug:

- It's the default response, and the data returned is from every four days.

Please remove this source completely if this is the data being returned.
