### ISSUE TITLE
[IMPROVE] Requirements are confusing given that it doesn't separate by OS or use easy to understand language

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4372]
When looking at the following:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/222379259-41b2f2bb-df60-4cf8-955a-21e446009aa9.png">

It doesn't specify anywhere that you don't need to have both Windows 10 and MacOS installed, it's one of the two. Furthermore, it mentions something about Ubuntu and my first instinct was "Wait, why do I need Ubuntu?". It's vague that this isn't mentioned.

Furthermore, it says `A modern CPU compatible with the Intel Math Kernel Library, supporting SSE3 & SSE4.2 instructions`. This means literally nothing to me. I can assume my M1 should be fine (just given the raw power of the device) but how should anyone know if they meet these requirements this way? The requirements page is simply lacking easy-to-understand language.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/222380211-e4f58cde-d61a-413c-b0bf-2a416ab9cea2.png">

What if I have 5G? Does that not work? I get that it does but this needs to be abundantly clear.

**Comment by deeleeramone** [comment]
I would be in favour of eliminating these pages altogether.

**Comment by JerBouma** [comment]
Could you list to me the absolute minimal requirements? E.g. I can assume right that on basically any device it should _just work_? Are there any barriers other than the OS, storage and RAM?

**Comment by deeleeramone** [comment]
No, I cannot, and I have not received any real answers either.

**Comment by JerBouma** [comment]
@piiq Am I right to pinging you and could you provide me the answer to this question?

> Could you list to me the absolute minimal requirements? E.g. I can assume right that on basically any device it should just work? Are there any barriers other than the OS, storage and RAM?

**Comment by piiq** [comment]
@JerBouma how about this:

Minimal requirements

For Windows:

- Windows 10 or newer
- Modern CPU (Intel or AMD processor made in the last 5 years)


For Mac:

- MacOS Monterey or newer
- Modern CPU (Intel processor made in the last 5 years or Apple Silicon chip)
- Rosetta installed

For Ubuntu Linux:

- Modern CPU (Intel or AMD processor made in the last 5 years)

Other minimal requirements:

- At least 4GB of RAM
- At least 5GB of free storage
- Internet connection (cable or 4G mobile)

**Comment by deeleeramone** [comment]
Might need to up the minimum storage and RAM when for using the `whisper` models, that could get big pretty fast.
