### ISSUE TITLE
[Bug] Windows - Cannot `git clone` repo because of filename too long error.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4373]
![Screenshot 2023-03-02 011125](https://user-images.githubusercontent.com/85772166/222383956-860eb138-d860-4c46-bec5-d74515e530aa.png)

**Comment by JerBouma** [comment]
This is so odd it suddenly pops up, nothing has been changed to those files 🤷. I'll delete the whole thing.
