### ISSUE TITLE
[Bug] `economy/cpi` is broken due to Plotly merge

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4375]
Seems to be that the code wasn't correctly changed for Plotly.

```
(🦋) /economy/ $ cpi --countries australia,belgium

No monthly data available for all countries. Using common frequency.
Error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


(🦋) /economy/ $
```

E.g. the installer build works fine (which is without plotly merge).

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/222466313-f114c860-6729-4b68-bf7e-85a7b96c5624.png">

**Comment by tehcoderer** [comment]
Fixed have a PR going! 🥰

**Comment by tehcoderer** [comment]
fixed
