### ISSUE TITLE
[Bug] Stocks/Quote - Premium key error message not displayed, only "Data not found"

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4394]
This ticker is from the TSX, and while it is dual-listed, this is not the desired behaviour. 
![Screenshot 2023-03-04 at 9 37 07 AM](https://user-images.githubusercontent.com/85772166/222920588-b956469b-addf-461d-add1-123fc06f7a03.png)

It should return an error message indicating it is a premium end point, for US-listed stocks only, as the SDK does:

```python
from openbb_terminal.sdk import openbb
import fundamentalanalysis
fundamentalanalysis.quote(ticker = 'RY.TO', api_key = 'REPLACE_WITH_KEY')
```
Returns:

```
HTTPError: HTTP Error 403: Forbidden
ValueError: This endpoint is only for premium members. Please visit the subscription page to upgrade the plan (Starter or higher) at https://financialmodelingprep.com/developer/docs/pricing
```

When requesting quotes from non dual-listed stocks, an unhelpful message is returned:
```
2023 Mar 04, 12:34 (🦋) /stocks/ $ quote GLXY.TO

Data not found
```

For reference: https://site.financialmodelingprep.com/developer/docs/#International-Filings

**Comment by colin99d** [comment]
When I run this endpoint with a key I get `Data not found`, but when I run it without a key I get:
`API_KEY_FINANCIALMODELINGPREP not defined. Set API Keys in ~/.openbb_terminal/.env or under keys menu.` I believe this is the expected behavior.

**Comment by deeleeramone** [comment]
> I believe this is the expected behaviour.

I don't believe so, because the data actually exists, and the error message should be: This endpoint is only for premium members.

![Screenshot 2023-03-15 at 2 45 02 PM](https://user-images.githubusercontent.com/85772166/225451061-f378ce2a-897b-4bb8-8853-a775b075d302.png)


![Screenshot 2023-03-15 at 2 42 03 PM](https://user-images.githubusercontent.com/85772166/225450571-c4ecf12a-d896-487d-a708-457976246b61.png)

**Comment by colin99d** [comment]
Ok, I see what you mean, unfortunately this is an issue with the FMP SDK and not the OpenBBTerminal.

```
def quote(ticker, api_key):
    """
    Description
    ----
    Gives information about the quote of a company which includes i.a.
    high/low close prices, price-to-earning ratio and shares outstanding.

    Input
    ----
    ticker (string)
        The company ticker (for example: "AMD")
    api_key (string)
        The API Key obtained from https://financialmodelingprep.com/developer/docs/

    Output
    ----
    data (dataframe)
        Data with variables in rows and the period in columns.
    """
    try:
        response = urlopen(
            f"https://financialmodelingprep.com/api/v3/quote/{ticker}?apikey={api_key}"
        )
        data = json.loads(response.read().decode("utf-8"))
    except HTTPError:
        print("PREMIUM ENDPOINT")
        raise ValueError(
            "This endpoint is only for premium members. Please visit the subscription page to upgrade the "
            "plan (Starter or higher) at https://financialmodelingprep.com/developer/docs/pricing"
        )

    if "Error Message" in data:
        raise ValueError(data["Error Message"])

    data_formatted = pd.DataFrame(data).T
    print(data_formatted)

    return data_formatted
```
I added a print statement to the FMP `quote` function to confirm the error handling for a premium endpoint is not being triggered. This gives us no way from differentiating from nonexistent data, and premium data. I think we will need to file an issue with FMP.
