### ISSUE TITLE
[Bug] resizing bug

### ISSUE THREAD

**Issue by Mikisavage** [OpenBB-finance/OpenBBTerminal#4395]
**Describe the bug**

When I enter full screen, the text gets all jumbled up.

**To Reproduce**
Enter full screen or Resizing the window

**Screenshots**

![image](https://user-images.githubusercontent.com/64377250/222956050-4a14814f-752b-4c8e-bcae-66d78dd4af1e.png)

**Desktop (please complete the following information):**

-Windows 11 Home

**Comment by deeleeramone** [comment]
This is an artifact specific to Windows terminals, and is not related to the OpenBB code.
