### ISSUE TITLE
[IMPROVE] Introduce a feature flag that removes the version number (off by default)

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4401]
his is helpful when adding images to presentations and documentation so that it is not perceived outdated as soon as a new version is released. Given that we do not make changes to every single menu all the time, this can remove confusion. I am happy if it just says "`OpenBB Terminal (http://www.openbb.co/)`"

**Comment by jmaslek** [comment]
think you did this
