### ISSUE TITLE
[Bug] `fixedincome/fed --export` returns no values

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4402]
Data seems to be incorrectly exported. 

<img width="622" alt="image" src="https://user-images.githubusercontent.com/46355364/223071840-34ba2dbf-f01d-494d-afe0-4e86cc73167d.png">

**Comment by jmaslek** [comment]
what exact command did you run.  fed --export xlsx works fine for me

**Comment by JerBouma** [comment]
Confused, it just works :)
