### ISSUE TITLE
[Bug] Stocks/Load --source AlphaVantage not working properly. `--interval` broken and wrong prices returned.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4441]
Recreate with:
```
/stocks/load SPY -i 5 --source AlphaVantage
```

It says that it is loading 5 minute intraday data from AlphaVantage, but that is not what is returned.

![Screenshot 2023-03-08 at 4 04 54 PM](https://user-images.githubusercontent.com/85772166/223881388-25368fa3-f74e-42f5-8275-8439ff56595d.png)

Probably related to #4426

**Comment by jmaslek** [comment]
Yeah juan goofed up the candle command and it is fixed in the table pr
