### ISSUE TITLE
[Bug] Plot with message `No html content to show, please provide a html_path or a html_str key`

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#4443]
**Describe the bug**
Without apparent reason plots start showing the message `No html content to show, please provide a html_path or a html_str key`
Couldn't spot any pattern, but if affects all plots regardless of the menu. 

Restarting the terminal fixes the issue, so it might be related with the plots backend.

<img width="1286" alt="Screenshot 2023-03-09 at 09 57 32" src="https://user-images.githubusercontent.com/79287829/223989643-bb6d1683-029c-4873-8ff0-7bdb90dbe191.png">

- OS: masOS Monterey
- Python version 3.10.9

**Additional context**
Add any other information that you think could be useful for us.

**Comment by montezdesousa** [comment]
@IgorWounds spotted that this occurs after running integration tests with flag `--subproc 0`.

Seems a specific issue only occurring when running integration tests and another terminal at the same time.

**Comment by tehcoderer** [comment]
@montezdesousa We create a temp html file with current terminal Path that we delete at program exit, so when the tests finished in the other terminal the html was deleted lol.

I'm getting a PR ready with a edge case fix! 👍👍Thanks!
