### ISSUE TITLE
[Bug] stocks/fa/dupont and fraud - doesn't print anything

### ISSUE THREAD

**Issue by andrewkenreich** [OpenBB-finance/OpenBBTerminal#4446]
**Describe the bug**
I just get a blank output when I run dupont or --raw 

Doesn't tell me anything

**Screenshots**
![image](https://user-images.githubusercontent.com/23067478/224161026-34618794-d007-481b-93a5-155c40390cbe.png)

**Comment by andrewkenreich** [comment]
![image](https://user-images.githubusercontent.com/23067478/224161375-3268b377-c2b0-4590-a387-2802d7f96db4.png)
fraud does same thing

**Comment by deeleeramone** [comment]
This is probably because it is a premium end point, but there is no error message returned, only None.

![Screenshot 2023-03-10 at 11 07 14 AM](https://user-images.githubusercontent.com/85772166/224404514-3e496b29-c39c-457d-b610-ef9a55a04e25.png)

**Comment by deeleeramone** [comment]
`fraud` on the other hand is behaving the same as you are experiencing.

**Comment by deeleeramone** [comment]
Here's the point of failure for `fraud`. The actual key is not being called.

![Screenshot 2023-03-10 at 11 21 18 AM](https://user-images.githubusercontent.com/85772166/224407055-8ba82775-96d2-4184-81d7-874476805237.png)

Should be:
```
fd = FundamentalData(key=get_current_user().credentials.API_KEY_ALPHAVANTAGE, output_format="pandas")
```
