### ISSUE TITLE
[Bug] openBB SDK fail to be installled in google colab environment

### ISSUE THREAD

**Issue by Wintoplay** [OpenBB-finance/OpenBBTerminal#4455]
I am new to this OpenBB and just try to use it in google colab. It say "AttributeError: module 'numpy' has no attribute 'asscalar'" as soon as I try to import the module via from openbb_terminal.sdk import openbb.

**To Reproduce**
run this colab to reproduce the error
https://colab.research.google.com/drive/1g44TB7E-CJB3mSkUDAZn-SX4in_cJpCX?usp=sharing

**Screenshots**
![image](https://user-images.githubusercontent.com/66968226/224366028-016b1ef7-2e95-49a7-892e-bbb71a7f9fab.png)

Python 3.9.16

**Comment by deeleeramone** [comment]
This is probably more to do with Google CoLab forcing a dependency tree that is not the same as the OpenBB requirements file. Python 3.8 is also becoming increasingly unsupported by many libraries.

**Comment by colin99d** [comment]
Hello @Wintoplay. Thank you for this issue! We currently do not officially support Google Colab, however the following resources may be helpful in getting it to work (if you get it to work we would LOVE to hear how):
- Changing the version of each individual package: https://stackoverflow.com/questions/70674293/use-specific-version-of-package-in-google-colab
- Loading our requirements.txt: https://stackoverflow.com/questions/50379804/install-dependencies-from-requirements-txt-in-google-colaboratory

I have no clue whether this will work. But I would love to hear how it goes!
