### ISSUE TITLE
[Bug] candle argument `add_trend` throws error

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#4480]
**Describe the bug**

`openbb.stocks.candle(symbol="AAPL", add_trend=True)`
![Screenshot 2023-03-14 at 16 15 00](https://user-images.githubusercontent.com/79287829/225069159-50c1dca0-8f6b-4e11-9af8-425a617327c9.png)

`openbb.forex.candle(data=data, add_trend=True)`
![Screenshot 2023-03-14 at 16 19 25](https://user-images.githubusercontent.com/79287829/225070283-b858e9dc-4143-4cfc-b9f0-eacdb5651a0a.png)

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
Trend line is not drawn in the Terminal, error message does not print.

![Screenshot 2023-03-14 at 6 51 16 PM](https://user-images.githubusercontent.com/85772166/225184014-f69f5511-edda-43f7-bc1e-405539a5a87a.png)

**Comment by jmaslek** [comment]
I think the find_trendline is somewhat buggy and should be deprecated.

I have noticed there is a check that it is only on daily data (`(data.index[1] - data.index[0]).total_seconds() >= 86400` -- not sure why).  And it doesn't seem to find any channels for half the tickers I seem to try.

- `load aapl/candle --trend` -> gives trend
- `load tsla/candle --trend` -> Error adding trend line
- `load spy/candle --trend` -> questionable trendline

If someone is really attached, we could add this to TA instead.

**Comment by tehcoderer** [comment]
#4467 Fixes this
