### ISSUE TITLE
[Bug] `/stocks/ta/vwap`: Error: can't compare datetime.datetime to datetime.date

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#4481]
**Describe the bug**

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by colin99d** [comment]
I cannot reproduce this

**Comment by colin99d** [comment]
I am going to close this.

**Comment by hjoaquim** [comment]
it's still here:

![image](https://user-images.githubusercontent.com/48914296/234294493-f006abde-9cb3-4e97-936e-1bb2139f591a.png)
