### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'pywry'

### ISSUE THREAD

**Issue by Shudh** [OpenBB-finance/OpenBBTerminal#4507]
After installation from source I am getting the below error

/home/shudh/miniconda3/envs/obb/bin/python /home/shudh/PycharmProjects/pythonProject/OpenBB/terminal.py
Traceback (most recent call last):
  File "/home/shudh/PycharmProjects/pythonProject/OpenBB/terminal.py", line 5, in <module>
    import openbb_terminal.config_terminal as cfg  # noqa: F401
  File "/home/shudh/PycharmProjects/pythonProject/OpenBB/openbb_terminal/__init__.py", line 13, in <module>
    from .core.plots.plotly_helper import OpenBBFigure, plots_backend, theme, TerminalStyle
  File "/home/shudh/PycharmProjects/pythonProject/OpenBB/openbb_terminal/core/plots/__init__.py", line 2, in <module>
    from .plotly_helper import OpenBBFigure
  File "/home/shudh/PycharmProjects/pythonProject/OpenBB/openbb_terminal/core/plots/plotly_helper.py", line 27, in <module>
    from openbb_terminal.core.plots.backend import PLOTLYJS_PATH, plots_backend
  File "/home/shudh/PycharmProjects/pythonProject/OpenBB/openbb_terminal/core/plots/backend.py", line 16, in <module>
    import pywry
ModuleNotFoundError: No module named 'pywry'

Process finished with exit code 1

**To Reproduce**
Follow the steps mentioned here under install from source section for Ubuntu 
Source Code Insall
The following instructions are for installing the OpenBB Terminal source code.

**Desktop (please complete the following information):**

- OS: [Ubuntu Jammie]

**Comment by colin99d** [comment]
Hello Shudh,

How did you install the dependencies. Pywry appears in our pyproject.lock, requirements.txt, and requirements-full.txt?

**Comment by colin99d** [comment]
Please run the following:
`curl https://sh.rustup.rs/ -sSf | sh -s -- -y --default-toolchain nightly`
`pip install pywry`

This will be made easier in the future, but we are still working through some stuff to simplify the process.

**Comment by tehcoderer** [comment]
Before doing `pip install pywry` make sure this libs are installed as well

# Pywry v0.3.5
```
sudo apt update
sudo apt install -y \
    libgtk-3-dev \
    libsoup-3.0-dev \
    libwebkit2gtk-4.1-dev
```

# Pywry v0.3.6
```
sudo apt update
sudo apt install -y \
    libgtk-3-dev \
    libsoup2.4-dev \ 
    librsvg2-dev \
    javascriptcoregtk-4.0 \
    libwebkit2gtk-4.0-dev
```

Let us know if that works!

**Comment by Shudh** [comment]
Thanks Colin.. I will do it today and take screenshots and report back here..I hope to succeed for I plan to contribute to this wonderful initiative..

**Comment by Shudh** [comment]
![image](https://user-images.githubusercontent.com/14231420/226083623-80a5b0dd-089d-45d5-9dfc-9af6fac0ede6.png)
Thanks Colin.. finally it worked..Earlier the error was Cargo and rust was missing in my computer during building from source..Probably the developer installation might mention this dependency..Based on your comments above I installed Rust and then installed all of that below .. sudo apt install -y \
    libgtk-3-dev \
    libsoup2.4-dev

    
    
    sudo apt-get install -y librsvg2-dev
    sudo apt-get install -y javascriptcoregtk-4.0
    sudo apt-get install -y libwebkit2gtk-4.0-dev
Then bumped up the version of pywry to v0.3.6 in poetry and ran the build successfully using  poetry install -E all .. Many thanks for replying to the bus reports so fast.. and I hope no user is facing this issue as it probably is for development install..Now I will check the MVC development model pattern in use ..

**Comment by grantwwoodford** [comment]
Installing Rust fixes this issue for me on Ubuntu.

**Comment by colin99d** [comment]
Glad to see this worked!
