### ISSUE TITLE
[Bug] Stocks/Candle - Candles overlap each other and are various widths.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4520]
Candles are drunk. Recreate with `/stocks/load UBS --weekly/candle`

![Screenshot 2023-03-17 at 2 23 15 PM](https://user-images.githubusercontent.com/85772166/226056395-98d486d2-a8f9-4904-a315-204be02226e5.png)

![Screenshot 2023-03-17 at 2 24 26 PM](https://user-images.githubusercontent.com/85772166/226056397-f50eafe5-168d-4ca8-ace6-b7203efe9509.png)

**Comment by tehcoderer** [comment]
fixed in #4467
