### ISSUE TITLE
[Bug] TA/DeMark - default parameters returns bad data when `--weekly` data.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4521]
Recreate with `stocks/load UBS --weekly/demark`

Default setting only displays, two, 6s. 

`demark`
![Screenshot 2023-03-17 at 2 48 05 PM](https://user-images.githubusercontent.com/85772166/226059231-97ce1da5-f018-4e77-a339-fb688140d48c.png)

There are, three, 6s when the `--min` parameter is set at 3.

`demark --min 3`

![Screenshot 2023-03-17 at 2 49 09 PM](https://user-images.githubusercontent.com/85772166/226059340-a9dcef2d-b23d-43df-8926-42889074cf58.png)

**Comment by colin99d** [comment]
I told @tehcoderer about this.

**Comment by colin99d** [comment]
It looks like Juan's PR has fixed this.
