### ISSUE TITLE
[Feature] Stocks/Options/exp - autocomplete does not give choices for expiration dates.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4543]
This behaviour is new to me, it used to present choices. 

![Screenshot 2023-03-20 at 7 43 33 PM](https://user-images.githubusercontent.com/85772166/226506585-e10b5895-68da-45c8-b860-233fe721dcdd.png)

![Screenshot 2023-03-20 at 7 41 20 PM](https://user-images.githubusercontent.com/85772166/226506512-3d0593ec-b835-4cac-b9e4-a93c370b3b7d.png)

**Comment by akshatakulkarni25** [comment]
hey @deeleeramone i would like to contribute to this issue. Could you please help me in understanding this issue better

**Comment by colin99d** [comment]
@akshatakulkarni25 thanks for the interest! Currently, we get the choices from the argparse options. To add auto-selection here, you will need to make the available expirations options. Here is the argparse item that needs modified:
https://github.com/OpenBB-finance/OpenBBTerminal/blob/develop/openbb_terminal/stocks/options/options_controller.py#L692
