### ISSUE TITLE
[Bug] [SDK] `openbb.crypto.dd.candle` has no `_chart` and returns a DataFrame - basically `load` by another name. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4545]
`openbb.crypto.dd.candle` is a function that should simply be `--source = 'coinbase'`, under `openbb.crypto.load()`. `candle` everywhere else produces a chart, while this only returns a DataFrame.

It's also not clear why this would be in the `DD` menu when it is simply OHLC+V data.
 
![Screenshot 2023-03-20 at 9 32 41 PM](https://user-images.githubusercontent.com/85772166/226517718-7f14bd18-9f06-448f-a96a-7908136abeb3.png)

**Comment by deeleeramone** [comment]
Also worth noting that the `date` is returned as a timestamp instead of date-time.

**Comment by the-praxs** [comment]
> Also worth noting that the `date` is returned as a timestamp instead of date-time.

Data returned from the APIs is by default in UNIX timestamp so that's fixable by a single line of code.


> `openbb.crypto.dd.candle` is a function that should simply be `--source = 'coinbase'`, under `openbb.crypto.load()`. `candle` everywhere else produces a chart, while this only returns a DataFrame.
> 
> It's also not clear why this would be in the `DD` menu when it is simply OHLC+V data.
> 
> ![Screenshot 2023-03-20 at 9 32 41 PM](https://user-images.githubusercontent.com/85772166/226517718-7f14bd18-9f06-448f-a96a-7908136abeb3.png)

Maybe just a mislabeling?

**Comment by deeleeramone** [comment]
It's simply price data, and it is out of context for the Due Diligence menu. It should be an additional `--source` to the `openbb.crypto.load()` function.  There is no need for an entirely separate function to get OHLC+V data.
