### ISSUE TITLE
[Bug] `stocks/load` and `stocks/candle` docstrings for `--prepost` argument are not accurate.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4551]
Pre-market/After-market flag does not work, source agnostic.

![Screenshot 2023-03-21 at 2 43 50 PM](https://user-images.githubusercontent.com/85772166/226748260-3adca704-0314-42f8-8ede-8f7a513ebaee.png)

![Screenshot 2023-03-21 at 2 46 58 PM](https://user-images.githubusercontent.com/85772166/226748724-97d66b51-3955-42c1-9fcf-3a6ba9c73386.png)

In addition, a Python error message is returned when `--source Intrinio` with `--prepost`

```
We currently do not support intraday data with Intrinio.

Error: local variable 's_start' referenced before assignment
```

**Comment by jmaslek** [comment]
FYI:  in the help for load:
```
-p, --prepost         Pre/After market hours. Only works for 'yf' source, and intraday data (default: False)
```

**Comment by deeleeramone** [comment]
> FYI: in the help for load:
> 
> ```
> -p, --prepost         Pre/After market hours. Only works for 'yf' source, and intraday data (default: False)
> ```

The help dialogue is wrong.

![Screenshot 2023-03-21 at 7 18 51 PM](https://user-images.githubusercontent.com/85772166/226784925-0a91bd8d-ce51-419d-b494-eeb66e3bace8.png)

**Comment by deeleeramone** [comment]
resolved in another issue.
