### ISSUE TITLE
[Bug] Failed to install torch . Is there any way to do in conda?

### ISSUE THREAD

**Issue by voidmain443** [OpenBB-finance/OpenBBTerminal#4556]
**Describe the bug**
I follow the rules that is in the doc . there is the pipit torch version 1.11.0 have to be installed . but in conda packages they're a  pythorch packages and I had an error with the conda environment. It is allowed to do with the PyTorch version? or I have install manually from the pypi?

'poetry install -E all' 

**Screenshots**
![CleanShot 2023-03-22 at 12 30 18](https://user-images.githubusercontent.com/83549147/226795027-d5a282ce-d7e9-486f-9cb8-4c0259b98673.png)

**Desktop (please complete the following information):**

- OS: conda virtual
- Python version [latest]

**Additional context**

**Comment by deeleeramone** [comment]
- What version of Linux are you running?

You may need some items that are Linux-specific:

```
sudo apt-get update
sudo apt-get install -y \
    build-essential \
    libgtk-3-dev \
    libsoup-3.0-dev \
    libsoup2.4-dev \
    libssl-dev \
    curl \
    wget \
    squashfs-tools \
    gcc \
    g++ \
    make \
    file \
    librsvg2-dev \
    libwebkit2gtk-4.1-dev \
    javascriptcoregtk-4.0 \
    libwebkit2gtk-4.0-dev \
    libayatana-appindicator3-dev
    ```

**Comment by noubre** [comment]
I am having the same issue and installing the Linux-Specific stuff didn't work. I am on Ubuntu 22.04.2.

**Comment by noubre** [comment]
> I am having the same issue and installing the Linux-Specific stuff didn't work. I am on Ubuntu 22.04.2.

Fixed it

**Comment by colin99d** [comment]
Awesome!
