### ISSUE TITLE
[Bug] `economy/gdp` seems to be broken

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#4559]
I was able to get the csv directly from the browser and using postman, but couldn't find a way to get it using python directly.

![image](https://user-images.githubusercontent.com/48914296/226903700-1e03082e-d7cc-45f4-8b1f-3f7a41740c86.png)

**Comment by jmaslek** [comment]
does the workflow here fix it?

https://github.com/OpenBB-finance/OpenBBTerminal/issues/4444

**Comment by hjoaquim** [comment]
#4508 fix this issue

**Comment by colin99d** [comment]
Closing per Henrique's comment.
