### ISSUE TITLE
[IMPROVE] Word wrap tables with columns containing words and sentences, like `/etf/news` or `/stocks/fa/analysis`.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4585]
Reasoning: It is very hard to read summaries like this. 

![Screenshot 2023-03-24 at 10 07 35 AM](https://user-images.githubusercontent.com/85772166/227593495-7a091868-94a8-4be3-a888-6b4808f0553f.png)

**Comment by andrewkenreich** [comment]
Closing as these are word wrapped now
