### ISSUE TITLE
[Bug] Stocks/Candle - Volume bars are the opposite color as the OHLC candles.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4589]
`/stocks/load msft/candle`

Volume bars are the opposite color as the OHLC candles, which is visually confusing.

![Screenshot 2023-03-25 at 7 54 07 AM](https://user-images.githubusercontent.com/85772166/227724897-b03d52ff-500a-4244-aae4-dda9f6226db1.png)

Having them be the same colour is also problematic where the volume and OHLC data overlap. Is there any real benefit to having up/down volume bar colours?  Does this tell us anything different than mirroring the up/down status of OHLC?  A single, more neutral and unobtrusive colour, may serve the chart better.

**Comment by tehcoderer** [comment]
fixed in #4613
