### ISSUE TITLE
[Bug] not opening forecast Error unable to load libomp.dylib

### ISSUE THREAD

**Issue by syedsajjadaskari** [OpenBB-finance/OpenBBTerminal#4593]
**Describe the bug**

 >> forecast 
Error: dlopen(/Users/syedaskari/miniconda3/envs/obb/lib/python3.10/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'
  Referenced from: '/Users/syedaskari/miniconda3/envs/obb/lib/python3.10/site-packages/lightgbm/lib_lightgbm.so'
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)

**To Reproduce**
forecast

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue
![Screenshot 2023-03-27 at 2 41 00 PM](https://user-images.githubusercontent.com/84753561/227896781-aea2ef38-36d7-4fa7-84c2-a42522b81bdf.png)
. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: [Mac Sierra]
- Python version [ 3.10]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by piiq** [comment]
We're still looking for a way how to ensure that when installing from source you get libomp.

For now the solution will be to install it from homebrew with `brew install libopm`

**Comment by piiq** [comment]
this issue is addressed in #4508 
the new installation instructions specify that libomp should be installed from homebrew
