### ISSUE TITLE
[IMPROVE] Improvements to tables v2

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4595]
Readability is not great, it should wrap the text in the box, now I need to scroll in an individual row of the column, that's very difficult to read.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/227901285-47b8fa73-6bad-4f7d-9dc4-8df6ce6ac1ad.png">

If I select "all" it's odd there still is an options to switch pages, this implies that "all" is not really all while it actually is and switching pages just gives you sub-selections again. **EDIT: Selecting all actually still cuts off a part of the table.**

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/227899009-16393873-dee0-4982-9c54-6e28f27cca1b.png">

`stocks/fa/income`, `balance` and `cash` are still cut off given that the minimum is now defaulted to 30. E.g. balance is 50 which is why I suggested to switch to 50.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/227899833-22ea5a87-04b5-4c21-b54f-e2dbf7591464.png">

Location of file saved is now correct but it has an empty string `File saved ""` below. Should honestly just be removed.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/227899995-876b649b-8503-46c0-8f11-01463f9c8a50.png">

Links still not clickable but I guess this is already being tackled?

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/227900415-4d79536c-9c90-4868-a6ee-545abdefbee5.png">

@andrewkenreich @jose-donato Just a few minor tidbits.

**Comment by jmaslek** [comment]
Adding on, we should check if the index is supposed to be a date.  See the econometrics/load wage_panel/show

It tries to make the index a. date, when that is not the case.

**Comment by tehcoderer** [comment]
- The File Saved prints from PyWry on download success, I've removed the filepath and just kept the `File Saved` on mac due to Webkit on Mac API limitation 
- `_blank` Links not opening another API limitation.. lolol

## Fixes incoming 
![image](https://user-images.githubusercontent.com/61340027/228251135-e25503ad-77f5-460b-9926-41cca7552689.png)

**Comment by deeleeramone** [comment]
related to: #4585
