### ISSUE TITLE
[Bug] Docs Page - Clicking on "see all results" ends on a page with "no results found"

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4617]
Go to the docs page, search for a term, scroll down and click "see all results"

![Screenshot 2023-03-28 at 10 10 19 PM](https://user-images.githubusercontent.com/85772166/228432636-9d1a7693-7105-45a9-89ff-9e5f78875b08.png)

https://user-images.githubusercontent.com/85772166/228432980-6189113d-0537-4e86-b267-55602b380ab6.mov

**Comment by MarkBenjamin** [comment]
what is the URL for the page?

**Comment by deeleeramone** [comment]
https://docs.openbb.co

**Comment by MarkBenjamin** [comment]
MWE it seems is the more specific URL https://docs.openbb.co/search

**Comment by deeleeramone** [comment]
Sure, I'm talking about the search bar from the top of the page.  Enter a search, then click on "see all results".

**Comment by andrewkenreich** [comment]
@deeleeramone will get this fixed - I see we have an issue in our config for the new v2 version they have

**Comment by andrewkenreich** [comment]
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/23067478/8133b93a-019a-44c4-84d4-22aa24b7a85c)

**Comment by andrewkenreich** [comment]
closinggggg
