### ISSUE TITLE
[Bug] `stocks/ba/redditsent` - chart has no labels, and some other issues with this function.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4618]
`/stocks/load btc-usd/ba/redditsent`

There are no labels, and it is not clear why this chart even exists.   

![Screenshot 2023-03-28 at 11 45 31 PM](https://user-images.githubusercontent.com/85772166/228448867-2f5a1bef-9a32-43db-a424-c10073b4aed4.png)

![Screenshot 2023-03-28 at 11 48 33 PM](https://user-images.githubusercontent.com/85772166/228452758-a319eaff-0de4-41df-bb0e-f65b95b81e6d.png)

Furthermore, what does "Sentiment" even mean, like, how is "Sentiment Analysis" determined?

![Screenshot 2023-03-28 at 11 51 37 PM](https://user-images.githubusercontent.com/85772166/228450109-8e438dc2-67e7-4c5a-9c98-918412f48ec0.png)

The arguments for `--display` and `--graphic` are strange. They must both be "True" because a table and a graphic are displayed no matter what. Again, not sure why a graphic is relevant or necessary.

The explanation for the argument `--full` does not actually explain what a comprehensive search does differently than deploying the other arguments.

**Comment by tehcoderer** [comment]
fixed
