### ISSUE TITLE
[Bug] Stocks/Quote - Timestamp is returned as a shortened value in Billions.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4619]
Recreate with: `/stocks/load aapl/quote`

![Screenshot 2023-03-29 at 12 08 17 AM](https://user-images.githubusercontent.com/85772166/228454078-074fbfdc-3b48-41a8-a3e8-bc27262866d8.png)

Timestamp should be converted as a date-time format.

**Comment by tehcoderer** [comment]
fixed in #4619

![image](https://user-images.githubusercontent.com/61340027/229575978-f33ef457-9c32-4625-b889-09a04f3669c6.png)
