### ISSUE TITLE
[Bug] `stocks/options/eodchain --help` - error: the following arguments are required: -d/--date. + other items.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4620]
recreate with:

`/stocks/load aapl/options/exp 1/eodchain --help`

![Screenshot 2023-03-29 at 12 16 31 AM](https://user-images.githubusercontent.com/85772166/228455734-96e103e3-7006-42e6-9661-024cd317193b.png)

It is also not clear what happens after this command is used. There's no option to export from the function, and there is no way to see "what was loaded", or verify that it is the date selected.  What are the expected results of this function? It lives separately from the `load` command, the expectation of the user is that the entire option chain for the ticker will be loaded and presented as a single table.

![Screenshot 2023-03-29 at 12 17 39 AM](https://user-images.githubusercontent.com/85772166/228455996-93d0a1b8-32d2-45a9-98da-083dd179bc00.png)

**Comment by Raghavendrapara** [comment]
Hi @deeleeramone 

![image](https://user-images.githubusercontent.com/41910672/228894543-e77ed3ea-017c-4b4c-9e6c-de8300c2e804.png)
 
The --help error that can be fixed by removing this line on required args at https://github.com/OpenBB-finance/OpenBBTerminal/blob/4861b4f261c56ead9a67c0382bbf5545d7dce78c/openbb_terminal/stocks/options/options_controller.py#L1451

Does fixing this only involved in the scope of issue?

**Comment by deeleeramone** [comment]
@Raghavendrapara - looks like the scope of the issue is broader than initially reported, also happening with `/stocks/options/load --help`. 

![Screenshot 2023-03-30 at 9 39 54 AM](https://user-images.githubusercontent.com/85772166/228905802-a2fd7b23-8550-4cb6-aed0-8cbca77d1c60.png)

**Comment by Raghavendrapara** [comment]
Aah, thanks for checking!
It would need thorough review of all commands

**Comment by the-praxs** [comment]
Fixed and adding PR.

**Comment by hjoaquim** [comment]
Regarding the following:

> 
> It is also not clear what happens after this command is used. There's no option to export from the function, and there is no way to see "what was loaded", or verify that it is the date selected. What are the expected results of this function? It lives separately from the `load` command, the expectation of the user is that the entire option chain for the ticker will be loaded and presented as a single table.
> 

I agree with this, although we can actually see the option chain by running `chains`.

Since the primary bug is being addressed by @the-praxs on #4709, should we open a new issue with the #improve tag instead @deeleeramone?
