### ISSUE TITLE
[Feature] [SDK] `openbb.stocks.options.greeks` - Calculate Greeks based on actual expiration

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4622]
This function cannot be used as shown because the calculations will be wrong. All duration is ignored, and the closest expiration date is used to calculate everything. Not clear how this impacts terminal operations. 

![Screenshot 2023-03-29 at 12 41 40 AM](https://user-images.githubusercontent.com/85772166/228461838-0d61b315-951b-4166-9c15-0bc665d4338b.png)

![Screenshot 2023-03-29 at 12 37 43 AM](https://user-images.githubusercontent.com/85772166/228460859-e531bb24-9318-46a6-a757-bc1d9ff26394.png)

```
Examples
--------
>>> from openbb_terminal.sdk import openbb
>>> aapl_chain = openbb.stocks.options.chains("AAPL", source="Tradier")
>>> aapl_last_price = openbb.stocks.options.last_price("AAPL")
>>> greeks = openbb.stocks.options.greeks(aapl_last_price, aapl_chain, aapl_chain.iloc[0, 2])
```

**Comment by colin99d** [comment]
I think you need to filter so that all expirations are the same. Do you want me to add a warning if the dates are different?

**Comment by deeleeramone** [comment]
> I think you need to filter so that all expirations are the same. Do you want me to add a warning if the dates are different?

It would be way better to not calculate incorrectly at all, by using the expiration date that is defined within each row.

**Comment by deeleeramone** [comment]
In the meantime, let's fix the example docstring so that an expiration date is selected at the load.
