### ISSUE TITLE
[Bug]`stocks/ta/recom`: integers formatted as dates

### ISSUE THREAD

**Issue by colin99d** [OpenBB-finance/OpenBBTerminal#4629]
`python terminal.py stocks/load aapl/ta/recom`

Generates the following:
<img width="879" alt="Screenshot 2023-03-29 at 2 50 44 PM" src="https://user-images.githubusercontent.com/72827203/228638759-34ffcb27-d0e9-432f-add7-8c8d05d3d279.png">

**Comment by colin99d** [comment]
Andrew suggest fixing this by checking if the integer is less than 5 digits long in the javascript code.

**Comment by andrewkenreich** [comment]
we did something different
