### ISSUE TITLE
[Bug] `stocks/fa/income` tables are broken

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4631]
Use: `stocks/load MSFT/fa/income`

Applies to basically any table, e.g. also ratios, balance, cash.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/228763114-1232b3f9-0417-4f31-8323-06ce5fef7522.png">

**Comment by tehcoderer** [comment]
fixed in #4636
