### ISSUE TITLE
[Bug] `fixedincome/usrates --export xlsx` - Exported file has no data under the `tbill` column.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4638]
Recreate with: `/fixedincome/usrates --export xlsx`

![image](https://user-images.githubusercontent.com/85772166/228874563-1d009d82-3384-4ef6-b85f-d814291cbab2.png)

[20230330_074329_fixedincome_TB3MS.xlsx](https://github.com/OpenBB-finance/OpenBBTerminal/files/11112846/20230330_074329_fixedincome_TB3MS.xlsx)

**Comment by Raghavendrapara** [comment]
@deeleeramone I am unable to reproduce this
![image](https://user-images.githubusercontent.com/41910672/228888635-96cc041f-60d6-423c-bff0-5862a5d659a2.png)

Getting Accurate data here
![image](https://user-images.githubusercontent.com/41910672/228888786-9ab5f310-ee17-449e-ac30-6b0ad59d9bf4.png)

**Comment by deeleeramone** [comment]
@Raghavendrapara, sorry! I was checking on two functions for someone and `fed` was the one that worked, it was `usrates` which was returning the empty data.  I got the working/not-working backwards.

**Comment by Raghavendrapara** [comment]
No worries mate!

**Comment by Raghavendrapara** [comment]
Have raised a PR for this issue
