### ISSUE TITLE
[Bug] `economy/events` - output is an empty table.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4646]
To reproduce: `/economy/events`

![Screenshot 2023-03-31 at 8 23 31 AM](https://user-images.githubusercontent.com/85772166/229162987-7622d0ba-54d1-47e8-bdc9-39bcded31a06.png)

**Comment by jmaslek** [comment]
ruh roh 
![Screenshot 2023-03-31 at 11 33 40 AM](https://user-images.githubusercontent.com/18151143/229165216-14459dfe-7476-400f-944f-bcc6bf3e4e11.png)

**Comment by deeleeramone** [comment]
hmmm.. I seem to be getting all tables returning as blanks.

**Comment by jmaslek** [comment]
#4631 had this

**Comment by deeleeramone** [comment]
updated pywry to 0.4.3, still blanks.

![Screenshot 2023-03-31 at 9 15 36 AM](https://user-images.githubusercontent.com/85772166/229174687-c4b66bb3-a5d8-4951-be54-c190ffe83250.png)

![Screenshot 2023-03-31 at 9 16 03 AM](https://user-images.githubusercontent.com/85772166/229174749-766f9e5c-6929-4cb4-8153-233c303d6ab4.png)
