### ISSUE TITLE
[Bug] `stocks/options/chains` --display argument does not do anything.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4649]
Recreate with any chains, from any source.

Using `--source Intrinio`

![Screenshot 2023-03-31 at 10 10 08 AM](https://user-images.githubusercontent.com/85772166/229185777-586e45a5-e7d7-4afd-b8c1-bd649c3db9b0.png)

Using `--source YahooFinance`

![Screenshot 2023-03-31 at 10 15 14 AM](https://user-images.githubusercontent.com/85772166/229186761-9215a5fb-eb9a-4dc6-8782-c0d9f7f46295.png)

**Comment by andrewkenreich** [comment]
Juan did a little something to fix this
