### ISSUE TITLE
[FR] Option for script-oriented output

### ISSUE THREAD

**Issue by ggian00** [OpenBB-finance/OpenBBTerminal#4655]
Option for script-friendly output and input consumption. As of now, it seems impossible to integrate with the rest of the system (with shell scripting).

Example usage of what I would like to do (in Linux):
`echo news | openbb --script | commands...`

Where option '--script' (or '-s') instructs openbb to reduce it's verbosity only to the result of 'news' command. It seems that openbb is aware of when the input is not from the keyboard, in that case passing the '--script' option is redundant.

Another example:
`echo stocks/candle -t GME | openbb --script`

I would expect openbb to show the results of the command "stocks/candle -t GME'' and exit immediately.

Being able to do shell scripting with openbb terminal will make automation and integration with the rest of the system easier. As of now, the alternative is to use openbb SDK which requires knowledge of the SDK and python.

**Comment by deeleeramone** [comment]
Hey!

Have you tried working with the Routine scripts? 

https://docs.openbb.co/terminal/usage/guides/scripts-and-routines

**Comment by ggian00** [comment]
Oh, I wasn't aware about routines. I will look into it. 

At a first glance, it seems I won't be able to use it with "pipes" `cmd1 | cmd2 | ...`, but I think I can achieve what I want with routines and exporting data to csv. 

I guess this issue can be closed. I will explore the capabilities of routines and if I find a case where routines are not enough I will update.
