### ISSUE TITLE
[Bug] `stocks/load TSLA` does not load daily data for TSLA.

### ISSUE THREAD

**Issue by MelikBelkhiria** [OpenBB-finance/OpenBBTerminal#4659]
**Bug Description**
Running the command `stocks/load TSLA` does not load daily data for TSLA.

**To Reproduce**
1. Open the OpenBBTerminal.
2. Run the following command: `stocks/load TSLA`
**Note:** In my case I used the TSLA ticker but it could be any other ticker and the daily data will still be not displayed as expected.

**Screenshots**
- **Input:**
```
stocks/load TSLA
```

- **Expected Output**:  ![Screenshot (4)](https://user-images.githubusercontent.com/119343734/229385855-ff35b4bb-1dff-4351-b662-0a4c22a12a3f.png)

- **Current Output:** 
![Screenshot (5)](https://user-images.githubusercontent.com/119343734/229386030-f8c9c407-4de1-4a12-a8d9-8cf47fd22a90.png)

**Comment by jmaslek** [comment]
Hey! The additional information was recently removed because of some issues with yfinance.  What you see is the desired output.

You can get the table using load TSLA --performance

**Comment by MelikBelkhiria** [comment]
I appreciate your fast response. Thanks for letting me know!
