### ISSUE TITLE
[Bug] `stocks/load msft/fa/balance --source EODHD` - Error: 'EODHD' - Valid subscription

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4660]
User report that the All-in-One subscription package fails to retrieve company fundamentals data. They already use their API with Python for this purpose.

```
/stocks/fa/ $ balance -t MSFT --source EODHD

Error: 'EODHD'
```

![image](https://user-images.githubusercontent.com/85772166/229414444-2662cac7-e894-49ba-9829-5475585a0c54.png)

**Comment by jmaslek** [comment]
Can you try to get a full debug printout ? Usually it just showing like that indicates a key error, but I do not see where that would be the case.

**Comment by deeleeramone** [comment]
The user has reported that 3.0.0rc1 resolves the issue and it can be closed.
