### ISSUE TITLE
[IMPROVE] Table Improvements v3

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4677]
Allow for resizing of tables when you increase the font or auto-resize automatically. Manual column adjustments is not preferred.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/229815121-701a35f7-9212-443d-8d39-02de9794d8ff.png">

Freeze the top column so that it is possible to see what year you are looking at. Especially with more bulky tables this can be difficult.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/229815356-ab8e7e0d-c5f4-4378-9d71-4d4e0c1f7d8a.png">

Freeze the "index" column so that if you scroll to the right you still have an idea what you are looking at.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/46355364/229815640-82194001-ffb9-4a36-b8d6-b2734d4d183e.png">

**Comment by deeleeramone** [comment]
Hijacking this to add-on, there is no need for everything to be so big. What I mean by this, the output from: `/alternative/oss/rossidx`

![Screenshot 2023-04-04 222627](https://user-images.githubusercontent.com/85772166/229989192-678d0506-a060-46e2-800c-ef4aa1ac88bd.png)

and then zooming out 3 times - `ctr -` - presents the entire table without any scrolling.

![Screenshot 2023-04-04 222706](https://user-images.githubusercontent.com/85772166/229989209-bc4207ed-6344-4c3d-8383-4b0657b60b70.png)

but then increasing the font size seems to show that the text in the columns are an overlay on the the columns, and not within the same element, unlike how the contents of a cell would be expected to behave.

![Screenshot 2023-04-04 223449](https://user-images.githubusercontent.com/85772166/229989974-9043a637-feca-4f77-9e05-df67b4c657be.png)

**Comment by deeleeramone** [comment]
Word wrap works with inconsistent results.  For `/alternative/hn`, Time is also being converted to trillions instead of a Datetime.

![Screenshot 2023-04-04 224459](https://user-images.githubusercontent.com/85772166/229991677-b3f933ee-77ec-42c0-a25b-888dcbd74f46.png)

**Comment by andrewkenreich** [comment]
@jose-donato is going to change the wordwrap css on url's to be dif here - its not breaking correctly

**Comment by andrewkenreich** [comment]
Move data formatting to happen before passing to react table - so our spacing works

0.0000000

![image](https://user-images.githubusercontent.com/23067478/231472256-e79c834e-8de8-419d-8e53-866e6f238071.png)



`  const getColumnWidth = (rows, accessor, headerText) => {
    const maxWidth = 200;
    const magicSpacing = 6;
    const cellLength = Math.max(
      ...rows.map((row) => getCellWidth(row, accessor) * 2),
      headerText.length * 2
    );
    console.log(accessor, cellLength * magicSpacing, cellLength * magicSpacing)
    return (cellLength * magicSpacing);
  };`

**Comment by andrewkenreich** [comment]
Add a max column header length of text and do "..." with hover to show the text

**Comment by jose-donato** [comment]
Fixing some of the issues on this PR #4765

**Comment by skhan59bbk** [comment]
Can I add in here to show unrounded prices please? Example below from economy/overview but happens elsewhere too. FWIW, prices are unrounded when "interactive" featflag is disabled. 

![image](https://user-images.githubusercontent.com/57355784/235242789-ef64888b-33c9-4b5a-b4cc-b65e2f4c3c66.png)
