### ISSUE TITLE
[FR] Integrate brokers TD and IKR

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#4684]
From a LinkedIn message:

> Do you all have any plans to integrate openBB with brokers like TD and IBKR? TD has a nice api to get data (free for TD account holders). I think this would be a nice addition to your product

> something like this but native in openBB https://github.com/alexgolec/tda-api

> TD and IBKR are the most popular brokers for retail traders. IBKR even for hedge funds. TD provides free data (stock timeseries and fundamental) while IBKR data is paid.

> TD and Charles have merged ao if you have access to TD you can have a big market.

> link to TD developer page

> https://developer.tdameritrade.com/

> This along with the github link I sent has everything your team would need to integrate TD in OpenBB. I would definately put TD on the roadmap

![image](https://user-images.githubusercontent.com/25267873/229870624-b49e7fee-f929-41a2-86a0-52a7901876a1.png)

**Comment by jmaslek** [comment]
#343 
#2149
