### ISSUE TITLE
[Bug] FixedIncome - "The combination of parameters does not result in any data." - displays an empty chart.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4687]
The sequence of parameters used was:

```
/fixedincome/icespread --area eu --grade aaa --category all
```

![Screenshot 2023-04-04 at 9 23 59 PM](https://user-images.githubusercontent.com/85772166/229980969-d4c3b4de-e00f-4203-96fb-f69b6dd4f757.png)

The bug is that a chart is still drawn without any data.

Ideally, the error message would inform the user what choices are valid; or, which choice was the one to invalidate the others. To remove any guess work.

**Comment by tehcoderer** [comment]
Fixed in #4701
