### ISSUE TITLE
[Bug] `portfolio/po/mktcap` - Error: unsupported operand type(s) for +=: 'int' and 'list'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4688]
To recreate this error:

```
/portfolio/load --example/po/mktcap

```

![Screenshot 2023-04-04 at 9 41 47 PM](https://user-images.githubusercontent.com/85772166/229982818-0daf35f7-2eaa-40c8-9047-6d7d26ea45a1.png)

**Comment by deeleeramone** [comment]
`blacklitterman` also has the same error.

![Screenshot 2023-04-04 at 9 44 10 PM](https://user-images.githubusercontent.com/85772166/229983115-d9584dc2-1d2b-41ce-a35e-6c2285a4892e.png)

**Comment by tehcoderer** [comment]
Fixed in #4701
