### ISSUE TITLE
[Bug] `stocks/fa/splits` index is falsely represented as numbers instead of dates

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4690]
See: `/stocks/load KO/fa/splits`

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/46355364/230044036-df35a7d8-a763-465e-9b1f-1d04af30e109.png">

**Comment by tehcoderer** [comment]
PR coming 👍 
![image](https://user-images.githubusercontent.com/61340027/230127270-3e7722ec-5e57-458a-8892-f2ec6f144ded.png)

**Comment by tehcoderer** [comment]
Fixed in #4701
