### ISSUE TITLE
[Bug] support command opens 3 blank windows + recaptcha

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#4692]
**Describe the bug**
`support` command opens several windows

**To Reproduce**
`openbb support`

**Screenshots**
![Screenshot 2023-04-05 at 14 16 00](https://user-images.githubusercontent.com/79287829/230091848-322715d8-5b42-48c2-85c6-9a1c5d8c5233.png)

**Desktop (please complete the following information):**

- OS: Ventura 13.3
- Python version 3.9.13

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
I am able to recreate this, only I get 4 windows of blanks.

![Screenshot 2023-04-05 at 10 21 23 AM](https://user-images.githubusercontent.com/85772166/230156291-fe20f91c-fd5e-4b62-9424-6b7082d9dcd7.png)

**Comment by andrewkenreich** [comment]
This will open in the default browser after 3.0 launch and not use the pywry window
