### ISSUE TITLE
[Bug] `crypto/find --help` - find: error: the following arguments are required: -c/--coin

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4707]
The help dialogue is printed when `-h` is employed, but not when `--help` is used.

Related to #4620 because it is the same issue.

![Screenshot 2023-04-06 at 7 24 03 PM](https://user-images.githubusercontent.com/85772166/230528020-a8f414db-8eba-4454-81c9-4a6c31c3c712.png)

**Comment by the-praxs** [comment]
I can confirm this happens for the `load` and `price` commands too. 

So the issue #4620 is extended to a broader range.

![image](https://user-images.githubusercontent.com/88149434/230574920-00f3aa7d-b03c-4013-8c60-2c26c01068f5.png)

**Comment by the-praxs** [comment]
Fixed and adding PR.
