### ISSUE TITLE
[Bug] `econometrics\load macrodata` Cannot format dates properly to set the index.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4713]
If you load one of the sample data sets in the Econometrics menu, for this example it is `macrodata`, the column for `year` is formatted as an abbreviated integer in thousands. 

![Screenshot 2023-04-07 at 12 35 09 PM](https://user-images.githubusercontent.com/85772166/230667732-b0ea7e80-a865-442c-8029-4db919731311.png)

`type macrodata.year --format date` then converts them all to `0.000`.
![Screenshot 2023-04-07 at 12 36 22 PM](https://user-images.githubusercontent.com/85772166/230667989-c67eff3d-527c-4d16-81a9-69991dad94fd.png)

It would be a reasonable argument to make that `type --format date` is not sufficient for converting these values. This should convert to a `DatetimeIndex` and allow for the desired formatting of the date and time.

With the inability to correct this, you can't set the index and it essentially becomes impossible to do any meaningful analysis or calculations.  Furthermore, upon loading any data set, it should automatically find the column titled, `date` or `year`/`month` and format the DataFrame appropriately.

**Comment by the-praxs** [comment]
@tehcoderer changing `year` to `str` will show `1960.0` instead of our desired output `1960`.

**Comment by the-praxs** [comment]
Issue extends to the datetime type index

![image](https://user-images.githubusercontent.com/88149434/231344421-4d01ae36-5d24-44b7-8e85-60ed8a4d858c.png)

**Comment by the-praxs** [comment]
> > @tehcoderer changing `year` to `str` will show `1960.0` instead of our desired output `1960`.
> 
> Convert the date to a string. An integer does not have a decimal, so you must have converted to a float first.

The dataset was loaded with `float64` dtype. I tried this approach but found a more direct and suitable way to fix it. Please feel free to review the commit (#4742). It works as intended on my end.

If you find any more issues, please ping me and I will fix them as soon as I can.

**Comment by tehcoderer** [comment]
Fixed in #4848 👍

**Comment by tehcoderer** [comment]
> @tehcoderer changing `year` to `str` will show `1960.0` instead of our desired output `1960`.

yeah had to convert to int then str for it to work when I tested today lol.

**Comment by deeleeramone** [comment]
Fixed in #4848
