### ISSUE TITLE
[Bug] [SDK] - Every initialization creates an error. Error: Failed to create session. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4714]
Every time the SDK is initialized this error message is printed:

```
(obb) Danglewoods-MacBook-Pro:OpenBBTerminal danglewood$ ipython
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:13) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.11.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from openbb_terminal.sdk import openbb
Error: Failed to create session.
```

For Reports, it prints the Traceback:

```
Error: Failed to create session.

Exception: Failed to create session.
Traceback (most recent call last):
  File "[/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py](https://file+.vscode-resource.vscode-cdn.net/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/decorators.py)", line 71, in wrapper
    value = func(*args, **kwargs)
  File "[/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/core/session/sdk_session.py](https://file+.vscode-resource.vscode-cdn.net/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/core/session/sdk_session.py)", line 67, in login
    session = get_session(email, password, token, keep_session)
  File "[/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/core/session/sdk_session.py](https://file+.vscode-resource.vscode-cdn.net/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/core/session/sdk_session.py)", line 30, in get_session
    raise Exception("Failed to create session.")
Exception: Failed to create session.
```

**Comment by the-praxs** [comment]
@deeleeramone it will work if you create an account at https://my.openbb.dev/ and then login with those creds into the terminal.

I think it needs to have better exception handling or disallow creating reports altogether if not logged in.

**Comment by the-praxs** [comment]
@deeleeramone what kind of output are you expecting out of this in case there was no session found (primarily due to guest login)?

**Comment by colin99d** [comment]
@deeleeramone I can reproduce the first error, but not the second. How could I reproduce the second issue?

**Comment by deeleeramone** [comment]
> @deeleeramone I can reproduce the first error, but not the second. How could I reproduce the second issue?

That is the output from a report.

**Comment by hjoaquim** [comment]
I tried to invalidate the session token and create a report, but can't get that error:

![image](https://user-images.githubusercontent.com/48914296/231296538-fed3aa2b-2981-40c8-a4b2-319b819eaea1.png)

When initializing the SDK, I do get the message saying that the login failed, but that's expected.

**Comment by deeleeramone** [comment]
You need to open the IPYNB report file and look at the cell which initializes the SDK.

**Comment by deeleeramone** [comment]
This still happens every time the SDK is initialized. 

![Screenshot 2023-04-17 at 7 57 28 AM](https://user-images.githubusercontent.com/85772166/232524839-77c3a446-6c14-44e3-9bf5-e26e13ec62a0.png)


![image](https://user-images.githubusercontent.com/85772166/232524589-092d0617-3618-4e0d-8662-d7233327a8ab.png)

**Comment by deeleeramone** [comment]
How would a user know this?

**Comment by the-praxs** [comment]
> How would a user know this?

That's a good question. Honestly one can either continue the session as a guest and as @jmaslek suggested show a warning or be given an option to login.

**Comment by hjoaquim** [comment]
If the login is successful, we can display the message saying so if not, I think the line `from openbb_terminal.sdk import openbb` should not raise an exception nor a warning.

Then, we can have either a warning or exception on `openbb.login(...)`. wdyt?
