### ISSUE TITLE
[Bug] `reports/etf` Default ticker fails because the quotes are added to the query.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4715]
To recreate, `/reports/etf`

Then you can open the notebook and run each cell individually, it will not fail.  You can also specify the ticker as `VTI` and it will not fail. The bug is in the way that the default symbol is handled.

![Screenshot 2023-04-07 at 1 46 43 PM](https://user-images.githubusercontent.com/85772166/230676948-734995e8-fc44-4051-a706-204d265845c9.png)

![Screenshot 2023-04-07 at 1 51 14 PM](https://user-images.githubusercontent.com/85772166/230677200-33ab895d-4a13-4699-9dfd-c1835875653d.png)

**Comment by the-praxs** [comment]
Error identified for all the commands in the `/reports/` menu.

![image](https://user-images.githubusercontent.com/88149434/230711199-9167f78a-bd95-4510-a7b4-463fa4411bb0.png)

**Comment by the-praxs** [comment]
@deeleeramone I think we can close this issue. The PRs have been merged.

**Comment by deeleeramone** [comment]
closed by #4718
