### ISSUE TITLE
[Bug] Default ticker fails in `reports` menu commands

### ISSUE THREAD

**Issue by the-praxs** [OpenBB-finance/OpenBBTerminal#4717]
**Describe the bug**
`reports` menu commands throw error without argument(s) (using default symbol).

**Screenshots**
![image](https://user-images.githubusercontent.com/88149434/230712884-a5657b3e-32e2-465e-9812-7a8b26dc709e.png)**Desktop (please complete the following information):**

**Additional context**
Extension of the bug #4715

**Comment by the-praxs** [comment]
So far able to fix all the commands other than `economy`. It's having a different issue where the `openbb.news` module throws an error stating `Ticker not supported. Unable to retrieve data`.

**Comment by hjoaquim** [comment]
Fixed by #4729
