### ISSUE TITLE
[Bug] `reports\equity` empty Behavioural Analysis tab in output

### ISSUE THREAD

**Issue by the-praxs** [OpenBB-finance/OpenBBTerminal#4746]
**Describe the bug**
Output from `reports\equity` does not contain behavioural analysis data. This is because of a bug in the pytrends API where the Google bot recognition system recently started flagging scraping requests. Hence an error 429 is returned by the bot and this exception occurs in the notebook file - `Too many requests: You have reached your quota limit. Please try again later.`

**To Reproduce**
Run the `reports\equity` command and view the `Behavioural Analysis` tab.

**Screenshots**
The empty details in the Behavioural Analysis` tab -

![image](https://user-images.githubusercontent.com/88149434/231434993-7f61f19e-c96e-452c-ae13-f0805b3e30c3.png)

The generated notebook file throws the following exception when requesting the data -

![image](https://user-images.githubusercontent.com/88149434/231437483-ef9bd155-8d78-4db5-88c5-288d7c1efb22.png)

**Desktop:**

- OS: Manjaro Linux
- Python 3.10.9

**Additional context**
pytrends is yet to merge the fix for the issue in its next release i.e. 4.9.2. Until then I have devised a workaround for it. Once pytrends is updated, the dependency requirement will be - `pytrends>=4.9.2`

**Comment by deeleeramone** [comment]
This bug is already an open issue: https://github.com/OpenBB-finance/OpenBBTerminal/issues/4535

**Comment by the-praxs** [comment]
@deeleeramone this was fixed. Please close this issue. Thanks.

**Comment by the-praxs** [comment]
This was fixed. Closing the issue.
