### ISSUE TITLE
[Bug] SEC filings command deleted for no reason...

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4763]
The function that was removed had nothing to do with the Fundamental Analysis menu.  It is not the same function *at all*.  I cannot understate this enough.  They are not the same function nor do they serve the same purpose. 

On main branch:
![Screenshot 2023-04-12 at 3 31 38 PM](https://user-images.githubusercontent.com/85772166/231600431-508b24b7-8417-4aa9-9b69-9fe109c81dd0.png)

```
(🦋) /stocks/disc/ $ filings --help

usage: filings [-p pages] [-t] [-h] [--export EXPORT] [--sheet-name SHEET_NAME [SHEET_NAME ...]] [-l LIMIT]

The most-recent filings submitted to the SEC

options:
  -p pages, --pages pages
                        The number of pages to get data from (1000 entries/page; maximum 30 pages) (default: 1)
  -t, --today           Show all filings from today (default: False)
  -h, --help            show this help message (default: False)
  --export EXPORT       Export raw data into csv, json, xlsx (default: )
  --sheet-name SHEET_NAME [SHEET_NAME ...]
                        Name of excel sheet to save data to. Only valid for .xlsx files. (default: None)
  -l LIMIT, --limit LIMIT
                        Number of entries to show in data. (default: 5)

For more information and examples, use 'about filings' to access the related guide.
```

On Develop:
![Screenshot 2023-04-12 at 3 37 19 PM](https://user-images.githubusercontent.com/85772166/231601302-b52e08bc-3a78-4d83-8ced-cc5c9c3912ee.png)

**Comment by the-praxs** [comment]
This also causes the  `reports\equity` feature to break.

![image](https://user-images.githubusercontent.com/88149434/231675768-cbed6855-0e16-46cb-99ef-5834d1047886.png)

![image](https://user-images.githubusercontent.com/88149434/231675904-7d06892f-1cbd-4c63-8bbe-3dcaaa8efe5b.png)
