### ISSUE TITLE
[Bug] Docstrings Error: `openbb.economy.balance_chart` - Returns: Dataframe with interest rate data.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4776]
The function does not return interest rate data.  It does return a chart, with the budget deficit/surplus as a percentage of GDP.

![Screenshot 2023-04-13 at 2 08 19 PM](https://user-images.githubusercontent.com/85772166/231883485-ad660e12-b566-4fea-ab1b-84bbae7a8924.png)

Other notable item is that there are no examples included in the docstrings.

**Comment by the-praxs** [comment]
@deeleeramone `oecd.py` contains functions for plotting charts for the `openbb.economy` data. This error extends to the whole file.

![image](https://user-images.githubusercontent.com/88149434/231983270-a90b830b-8446-4b7d-b1d6-9f86f2a13854.png)
![image](https://user-images.githubusercontent.com/88149434/231983340-ecc371be-5da4-4a6d-bf92-b10600d282a3.png)
