### ISSUE TITLE
`stocks/search --exchange`  Filter does not work.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4778]
Searching by `--exchange` does not return the expected results. It has the expected input of a country, but the field itself contains exchange codes. 

 ![Screenshot 2023-04-13 at 4 05 55 PM](https://user-images.githubusercontent.com/85772166/231901669-2bcd8fce-6429-4dbc-b58c-0accc74df726.png)

`search --exchange united_states --industry food_products`

![Screenshot 2023-04-13 at 4 02 35 PM](https://user-images.githubusercontent.com/85772166/231901285-11ae799c-ac02-4168-81fd-8cd1e7b66700.png)

**Comment by the-praxs** [comment]
@deeleeramone If one has to search for stocks listed in a country one can use the `country` argument. So what's the use for the `exchange` argument given its description?

Also shouldn't this option to search for the stock for a given exchange?
