### ISSUE TITLE
[IMPROVE] Remove function: `/economy/spectrum`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4779]
This specific function, `/economy/spectrum`, does not jive with anything else.  It does not belong, and it dumps a PNG file to an unspecified location in the system when running it. As per, @jmaslek, charts not originating from within the OpenBB library should go bye-bye.

![image](https://user-images.githubusercontent.com/85772166/231940760-2730ce29-ea59-4aff-af98-675e83f80bfb.png)

**Comment by the-praxs** [comment]
Looks like the file is stored in the `tmp`/`temp` directory.

**Comment by the-praxs** [comment]
The url is scraped to get the image from the finviz website. I guess then this function needs to be removed.
