### ISSUE TITLE
[Bug] `openbb.stocks.options.eodchain` value for DTE is less than 1 when expiration is 2023-12-15

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4790]
The DTE column is also perplexing.  Using the SDK function for DTE returns the expiration being 244 days away, the value of 0.671233 doesn't make any sense.

```
In [46]: openbb.stocks.options.dte('2023-12-15')
Out[46]: 244
```

```
chains_bb = openbb.stocks.options.eodchain('SPY', '2023-04-14')
chains_bb.query("`code` == 'SPY231215P00520000'")
```
![image](https://user-images.githubusercontent.com/85772166/232171531-d5de57bf-5255-416e-b3a3-9dbb87277544.png)

**Comment by jmaslek** [comment]
notice that the date 2023-04-14 is not equal to the date a year earlier of 2022-04-14

**Comment by deeleeramone** [comment]
> notice that the date 2023-04-14 is not equal to the date a year earlier of 2022-04-14 

hahaha. hang on. I may have messed up the copy/pasta or I may just have totally jump the shark.

**Comment by deeleeramone** [comment]
Thanks, that's rather annoying that I didn't catch that sillyness!  I suppose the question is now the value for DTE.

![Screenshot 2023-04-14 at 4 43 31 PM](https://user-images.githubusercontent.com/85772166/232171251-1e64704d-0957-4516-a1ea-b25d57e43364.png)

**Comment by jmaslek** [comment]
> Thanks, that's rather annoying that I didn't catch that sillyness!  I suppose the question is now the value for DTE.
> 
> 
> 
> ![Screenshot 2023-04-14 at 4 43 31 PM](https://user-images.githubusercontent.com/85772166/232171251-1e64704d-0957-4516-a1ea-b25d57e43364.png)
> 
> 

Dte is reported in years because Iv is annualized and any BS calculation requires the correct units.  In the example you had where exp was dec 2024 and the date was apr 2022 you got 1.67 ish because it was 1 year and 8 months ~ 1.67 years

**Comment by deeleeramone** [comment]
> Dte is reported in years because Iv is annualized and any BS calculation requires the correct units.

For actually referencing, filtering, and communicating DTE, it is always expressed as the number of days.  You never hear anyone talking about 0.25 DTE options, which would be *years* to expiration, not Days.
