### ISSUE TITLE
[Bug] `/fixedincome/ecb --export xlsx` does not export values, only dates.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4791]
Reproduce with: `/fixedincome/ecb --export xlsx`

![Screenshot 2023-04-14 184015](https://user-images.githubusercontent.com/85772166/232177242-bb521567-189d-49ca-ad4d-2aa9690609f4.png)

**Comment by the-praxs** [comment]
@deeleeramone please review the fix (#4792).
