### ISSUE TITLE
[Bug] `account\list` displays `No routines found.` but opens a windows with 3 default routines

### ISSUE THREAD

**Issue by the-praxs** [OpenBB-finance/OpenBBTerminal#4794]
**Describe the bug**
I have not set any routine in my account. So executing `accounts\list` command displays the proper output -

![image](https://user-images.githubusercontent.com/88149434/232234927-a750ab89-e3c8-449c-a4d3-006be4cb2ce6.png)

However, it opens a window that displays 3 routines configured - 

![openbb_Default_routines_20230415_154016](https://user-images.githubusercontent.com/88149434/232234973-84c47841-992f-4d43-b374-57ca843fe6e9.png)

**Comment by the-praxs** [comment]
On my.openbb.dev profile, I see these as default routines - 

![image](https://user-images.githubusercontent.com/88149434/232263058-1f248112-bea7-4447-9b1f-965d6980216f.png)

Then the output should not be `No routines found.`. May I know what's the expected output for this command so that I can develop a fix for it?

**Comment by deeleeramone** [comment]
Thanks for this issue, @the-praxs!  This is because the routines are not refreshed in memory and you need to restart in order for them to be recognized.  The choices for the `exe` command need to refresh after.

**Comment by the-praxs** [comment]
> Thanks for this issue, @the-praxs! This is because the routines are not refreshed in memory and you need to restart in order for them to be recognized. The choices for the `exe` command need to refresh after.

Gotcha. I noticed in the code that even if one has personal routines, it would still display the default routines.

![image](https://user-images.githubusercontent.com/88149434/232402304-10078717-f1c2-4634-9aa5-ff0f1b33e561.png)

The last 3 lines are out of the conditional block so when the `if` clause runs, it will also display the default routines afterward.
