### ISSUE TITLE
[Bug] `account/list` says no routines while there are default routines

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4803]
This should basically be because default ones are not counted.

```
(🦋) /account/ $ list

No routines found.


(🦋) /account/ $
```

![image](https://user-images.githubusercontent.com/46355364/232478787-dc065ea1-74ba-4cc5-be14-098810302b75.png)

**Comment by deeleeramone** [comment]
#4794
