### ISSUE TITLE
[Bug] Routines not removed when I remove them from the Hub

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#4804]
Routines from the Hub are not removed whenever I do delete them on [my.openbb.dev](http://my.openbb.dev/). I now have multiple routines in here that don’t exist if I visit the Hub but they simple still reside in my routines/hub folder. That’s not how it is supposed to be in my opinion.

![image](https://user-images.githubusercontent.com/46355364/232479569-cb586dc7-bff8-405e-aa71-e823dc82ba24.png)

**Comment by montezdesousa** [comment]
Fixed here https://github.com/OpenBB-finance/OpenBBTerminal/pull/4802
