### ISSUE TITLE
[Bug] Personal routines overwrite default if name collision

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#4826]
**Describe the bug**
* If user names its personal routine a name already used by default routines, the latter will overwrite the default inside `OpenBBUserData/routines/hub` folder

<img width="764" alt="Screenshot 2023-04-19 at 11 11 57" src="https://user-images.githubusercontent.com/79287829/233043713-fe00edfa-9dff-4757-a17a-8ac20cfd0a3f.png">

<img width="655" alt="Screenshot 2023-04-19 at 11 10 06" src="https://user-images.githubusercontent.com/79287829/233043187-427e380e-6484-4775-95e4-dffcd5d09c4f.png">

<img width="688" alt="Screenshot 2023-04-19 at 11 12 47" src="https://user-images.githubusercontent.com/79287829/233043813-7efb20b3-5065-4ee0-979c-cec5ec6c5c1c.png">

**Comment by LOne2three** [comment]
Can i work on this

**Comment by montezdesousa** [comment]
> Can i work on this

Sure, do you have any idea how to fix it?

**Comment by LOne2three** [comment]
Yeah I am looking at the code right now and I think I might know how to fix it

**Comment by LOne2three** [comment]
Hi may I know how you got that dialog box to show? The docs only demonstrate  how to manually add a routine to the hubs folder. I have tried uploading a file with the same name and downloading it again but I get the prompt which tells me that a duplicate exists in the hubs folder and if I want to overwrite it.

**Comment by LOne2three** [comment]
> > Hi may I know how you got that dialog box to show? The docs only demonstrate how to manually add a routine to the hubs folder. I have tried uploading a file with the same name and downloading it again but I get the prompt which tells me that a duplicate exists in the hubs folder and if I want to overwrite it.
> 
> The dialog box is shown here https://my.openbb.dev/app/terminal/routines when clicking "Create new". To replicate the issue you can either:
> 
> * create a routine in that link with the name "The Influence of the Central Bank"
> * `upload --file The Influence of the Central Bank.openbb` in the terminal
> 
> The quick fix I see for this is to ask user confirmation, so he is aware that routine name being uploaded is already given to a default and it will overwrite it. Same way we do for the personal routines basically.

Default routines are technically constants that can't be changed or removed at least from the terminal or from openbb.dev. When a user saves a routine with the same name it automatically becomes a personal routine in the hubs folder, while the default routine in the cloud remains the same. When you call list on routines, you can see that the default routine remains unchanged while a new routine with the same name is added to the user's personal routine's list and this logic is also reflected on the website. I wonder if this is done by design so users can edit personal routines with the same name in the hubs folder as two files cannot have the same name in the same folder.

**Comment by montezdesousa** [comment]
> > > Hi may I know how you got that dialog box to show? The docs only demonstrate how to manually add a routine to the hubs folder. I have tried uploading a file with the same name and downloading it again but I get the prompt which tells me that a duplicate exists in the hubs folder and if I want to overwrite it.
> 
> > The dialog box is shown here https://my.openbb.dev/app/terminal/routines when clicking "Create new". To replicate the issue you can either:
> > 
> > * create a routine in that link with the name "The Influence of the Central Bank"
> > * `upload --file The Influence of the Central Bank.openbb` in the terminal
> > 
> > The quick fix I see for this is to ask user confirmation, so he is aware that routine name being uploaded is already given to a default and it will overwrite it. Same way we do for the personal routines basically.
> 
> Default routines are technically constants that can't be changed or removed at least from the terminal or from openbb.dev. When a user saves a routine with the same name it automatically becomes a personal routine in the hubs folder, while the default routine in the cloud remains the same. When you call list on routines, you can see that the default routine remains unchanged while a new routine with the same name is added to the user's personal routine's list and this logic is also reflected on the website. I wonder if this is done by design so users can edit personal routines with the same name in the hubs folder as two files cannot have the same name in the same folder.

Yes, it is done for that reason plus having the ability to run the routine with `exe --file` command. That command will look for routines inside `OpenBBUserData/routines` folder. 

Other idea, we can mimic the website structure and have two subfolders:
`OpenBBUserData/routines/hub/personal` and `OpenBBUserData/routines/hub/defaults`, then on login we each routine is saved where it is due, no problem with name collision. 

On the `exe --file` command we need to prepend the subfolder name to the routine:
* `personal/The Influence of the Central Bank.openbb`
* `defaults/The Influence of the Central Bank.openbb`
instead of otherwise we would only see one of the files
<img width="427" alt="Screenshot 2023-04-20 at 11 26 42" src="https://user-images.githubusercontent.com/79287829/233339173-622f6df5-7a1b-4dd6-9ccb-e6e74947b352.png">

**Comment by LOne2three** [comment]
> > > > Hi may I know how you got that dialog box to show? The docs only demonstrate how to manually add a routine to the hubs folder. I have tried uploading a file with the same name and downloading it again but I get the prompt which tells me that a duplicate exists in the hubs folder and if I want to overwrite it.
> > 
> > 
> > > The dialog box is shown here https://my.openbb.dev/app/terminal/routines when clicking "Create new". To replicate the issue you can either:
> > > 
> > > * create a routine in that link with the name "The Influence of the Central Bank"
> > > * `upload --file The Influence of the Central Bank.openbb` in the terminal
> > > 
> > > The quick fix I see for this is to ask user confirmation, so he is aware that routine name being uploaded is already given to a default and it will overwrite it. Same way we do for the personal routines basically.
> > 
> > 
> > Default routines are technically constants that can't be changed or removed at least from the terminal or from openbb.dev. When a user saves a routine with the same name it automatically becomes a personal routine in the hubs folder, while the default routine in the cloud remains the same. When you call list on routines, you can see that the default routine remains unchanged while a new routine with the same name is added to the user's personal routine's list and this logic is also reflected on the website. I wonder if this is done by design so users can edit personal routines with the same name in the hubs folder as two files cannot have the same name in the same folder.
> 
> Yes, it is done for that reason plus having the ability to run the routine with `exe --file` command. That command will look for routines inside `OpenBBUserData/routines` folder.
> 
> Other idea, we can mimic the website structure and have two subfolders: `OpenBBUserData/routines/hub/personal` and `OpenBBUserData/routines/hub/defaults`, then on login each routine is saved where it is due, no problem with name collision.
> 
> On the `exe --file` command we need to prepend the subfolder name to the routine:
> 
> * `hub/personal/The Influence of the Central Bank.openbb`
> * `hub/defaults/The Influence of the Central Bank.openbb`
>   instead of
> 
> <img alt="Screenshot 2023-04-20 at 11 26 42" width="427" src="https://user-images.githubusercontent.com/79287829/233339173-622f6df5-7a1b-4dd6-9ccb-e6e74947b352.png">
> 
> otherwise we would only see one of the files.

Yeah I agree as I can't find the source code for openbb.dev  in the repo where the hotfix suggestion could be implemented.

**Comment by LOne2three** [comment]
> > > > > Hi may I know how you got that dialog box to show? The docs only demonstrate how to manually add a routine to the hubs folder. I have tried uploading a file with the same name and downloading it again but I get the prompt which tells me that a duplicate exists in the hubs folder and if I want to overwrite it.
> > > 
> > > 
> > > > The dialog box is shown here https://my.openbb.dev/app/terminal/routines when clicking "Create new". To replicate the issue you can either:
> > > > 
> > > > * create a routine in that link with the name "The Influence of the Central Bank"
> > > > * `upload --file The Influence of the Central Bank.openbb` in the terminal
> > > > 
> > > > The quick fix I see for this is to ask user confirmation, so he is aware that routine name being uploaded is already given to a default and it will overwrite it. Same way we do for the personal routines basically.
> > > 
> > > 
> > > Default routines are technically constants that can't be changed or removed at least from the terminal or from openbb.dev. When a user saves a routine with the same name it automatically becomes a personal routine in the hubs folder, while the default routine in the cloud remains the same. When you call list on routines, you can see that the default routine remains unchanged while a new routine with the same name is added to the user's personal routine's list and this logic is also reflected on the website. I wonder if this is done by design so users can edit personal routines with the same name in the hubs folder as two files cannot have the same name in the same folder.
> > 
> > 
> > Yes, it is done for that reason plus having the ability to run the routine with `exe --file` command. That command will look for routines inside `OpenBBUserData/routines` folder.
> > Other idea, we can mimic the website structure and have two subfolders: `OpenBBUserData/routines/hub/personal` and `OpenBBUserData/routines/hub/defaults`, then on login each routine is saved where it is due, no problem with name collision.
> > On the `exe --file` command we need to prepend the subfolder name to the routine:
> > 
> > * `hub/personal/The Influence of the Central Bank.openbb`
> > * `hub/defaults/The Influence of the Central Bank.openbb`
> >   instead of
> > 
> > <img alt="Screenshot 2023-04-20 at 11 26 42" width="427" src="https://user-images.githubusercontent.com/79287829/233339173-622f6df5-7a1b-4dd6-9ccb-e6e74947b352.png">
> > otherwise we would only see one of the files.
> 
> Yeah I agree as I can't find the source code for openbb.dev in the repo where the hotfix suggestion could be implemented.

I think I have fixed this issue. I have also created separate folders for personal and default routines. I will send a pull request after I finish unit testing

**Comment by LOne2three** [comment]
> > > > Hi may I know how you got that dialog box to show? The docs only demonstrate how to manually add a routine to the hubs folder. I have tried uploading a file with the same name and downloading it again but I get the prompt which tells me that a duplicate exists in the hubs folder and if I want to overwrite it.
> > 
> > 
> > > The dialog box is shown here https://my.openbb.dev/app/terminal/routines when clicking "Create new". To replicate the issue you can either:
> > > 
> > > * create a routine in that link with the name "The Influence of the Central Bank"
> > > * `upload --file The Influence of the Central Bank.openbb` in the terminal
> > > 
> > > The quick fix I see for this is to ask user confirmation, so he is aware that routine name being uploaded is already given to a default and it will overwrite it. Same way we do for the personal routines basically.
> > 
> > 
> > Default routines are technically constants that can't be changed or removed at least from the terminal or from openbb.dev. When a user saves a routine with the same name it automatically becomes a personal routine in the hubs folder, while the default routine in the cloud remains the same. When you call list on routines, you can see that the default routine remains unchanged while a new routine with the same name is added to the user's personal routine's list and this logic is also reflected on the website. I wonder if this is done by design so users can edit personal routines with the same name in the hubs folder as two files cannot have the same name in the same folder.
> 
> Yes, it is done for that reason plus having the ability to run the routine with `exe --file` command. That command will look for routines inside `OpenBBUserData/routines` folder.
> 
> Other idea, we can mimic the website structure and have two subfolders: `OpenBBUserData/routines/hub/personal` and `OpenBBUserData/routines/hub/defaults`, then on login each routine is saved where it is due, no problem with name collision.
> 
> On the `exe --file` command we need to prepend the subfolder name to the routine:
> 
> * `hub/personal/The Influence of the Central Bank.openbb`
> * `hub/defaults/The Influence of the Central Bank.openbb`
>   instead of
> 
> <img alt="Screenshot 2023-04-20 at 11 26 42" width="427" src="https://user-images.githubusercontent.com/79287829/233339173-622f6df5-7a1b-4dd6-9ccb-e6e74947b352.png">
> 
> otherwise we would only see one of the files.

I think I have fixed this issue. I have also created separate folders for personal and default routines. I will send a pull request after I have finished unit testing
