### ISSUE TITLE
[Bug] Pywry exception is raised on logout

### ISSUE THREAD

**Issue by montezdesousa** [OpenBB-finance/OpenBBTerminal#4832]
Exception is raised when:
* `openbb --login`
* `account/logout`
* `exit`
<img width="940" alt="Screenshot 2023-04-20 at 00 25 28" src="https://user-images.githubusercontent.com/79287829/233220625-ce587730-30d9-407f-968d-702ee9de81ef.png">

**Comment by the-praxs** [comment]
I did not encounter this on Windows, maybe its a mac/Linux issue?

![image](https://user-images.githubusercontent.com/88149434/233438825-fe4bf20a-a8d9-44ce-a6c1-e0e43b32ce9e.png)

**Comment by andrewkenreich** [comment]
I couldnt reproduce this either - @montezdesousa are you still seeing the same behavior?

**Comment by montezdesousa** [comment]
> I couldnt reproduce this either - @montezdesousa are you still seeing the same behavior?

Stopped happening, we can close it perhaps got fixed meanwhile
