### ISSUE TITLE
[Improve] `stocks/ca` - `ticker` and `set` should do the same thing, having both is confusing.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4834]
this is `/stocks/ca/ticker tsla/add F,GM,VW,RIVN`

<img width="992" alt="Screenshot 2023-04-19 at 6 39 50 PM" src="https://user-images.githubusercontent.com/85772166/233235781-698a4d4c-c1ca-4ec4-a340-b6a802d0c100.png">

There should be a "base" ticker, and then everything else.  If you want to add a list of tickers, use `add`.

**Comment by jmaslek** [comment]
So there is a subtle enough difference.

`set` resets the list of similar tickers whereas `ticker` sets the base as you mention we should do and it resets the similar companies set.

Made this change in #5146
