### ISSUE TITLE
[Bug] Anonymize flair for logged-in users on the logs

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#4838]
^

The flair for logged-in users is set after the user's email, so we need to anonymize on the logs in order to ensure that the emails are protected.

> reported by @deeleeramone

**Comment by clairericks** [comment]
Hey, I wanted to contribute and add a fix for this, but when I try to push my PR with a personal access token, I keep getting a 403. I didn't know if I needed permission first.
