### ISSUE TITLE
[FR] Option to turn off the logo box in plots view

### ISSUE THREAD

**Issue by jiiiijiij** [OpenBB-finance/OpenBBTerminal#4840]
Maybe it just me, but i think if the plot don't have big blue box above it. Openbb would be more aesthetic and matching with the terminal (I like the plots that CEO showcase in recent youtube video).

**Comment by DidierRLopes** [comment]
Hey @jiiiijiij,

Having our OpenBB banner on top is our way to have the community recognize us and be able to reach out to us in case they want to replicate the chart or have questions.

I think that for the value added for free it's a good compromise.

In any case, if you are interested on white labelling or fully getting rid of the top banner, our license is MIT so you can fork the project and do that. I can help you do that if you want 🙏🏽

**Comment by jiiiijiij** [comment]
I understand that, I don't want to delete the logo, it is completely reasonable to have a logo. I just think the blue box blackground just too big.

Well sacrifices a bit of the nostalgia for a greater good is a fair trade. Hoping one day openbb will reach to the point that just a small BB logo can make ppl know where the origin, like tradingview today.
