### ISSUE TITLE
[Bug] `stocks/ta/bbands` --std argument does not work.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4863]
Instead of 2 standard deviations, some users may want to use a 1.5 STD, which fails a `check_positive_value` test.

```console
/stocks/ta/ $ bbands --std 1.5

usage: bbands [-l N_LENGTH] [-s N_STD] [-m {ema,sma,wma,hma,zlma}] [-h] [--export EXPORT] [--sheet-name SHEET_NAME [SHEET_NAME ...]]
bbands: error: argument -s/--std: invalid check_positive value: '1.5'
```

Setting `--std` at 1 does not change the value from the default setting of 2.

<img width="1149" alt="Screenshot 2023-04-21 at 7 26 02 PM" src="https://user-images.githubusercontent.com/85772166/233757118-9fb1ec31-2b96-41d0-afc7-0bb1d43c6707.png">

The same applies when the value is set at 4.

<img width="1446" alt="Screenshot 2023-04-21 at 7 30 19 PM" src="https://user-images.githubusercontent.com/85772166/233757361-be6785d5-57fd-4e55-b1a0-98638eb30fe0.png">

**Comment by northern-64bit** [comment]
The results change when changing the value for `--std`.
<img width="562" alt="image" src="https://user-images.githubusercontent.com/75195383/233771981-6133ccac-8cad-4734-96a3-1bf2ed25f047.png">
