### ISSUE TITLE
About command redirects to 404

### ISSUE THREAD

**Issue by 0xiDen** [OpenBB-finance/OpenBBTerminal#4868]
**Describe the bug**
about command direct to a web page which doesn't exist resulting in 404 error.

**To Reproduce**
go to open bb terminal. -> type `economy` -> type `about` 

**Screenshots**
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/118856658/233803785-d225c2d0-61b7-4db6-8550-93de9d51fc3e.png">

**Desktop (please complete the following information):**

- OS: macOS Ventura 13.3.1
- Python version 3.11

**Additional context**
it also happens on keys & other commands

**Comment by deeleeramone** [comment]
Hi there, 

Thanks for reporting. This has been fixed here: https://github.com/OpenBB-finance/OpenBBTerminal/pull/4825 and it will be included in version 3.0.
