### ISSUE TITLE
[Bug] Ubuntu docker shows white blank window instead of charts

### ISSUE THREAD

**Issue by loongx2** [OpenBB-finance/OpenBBTerminal#4872]
**Describe the bug**
While trying to display charts all I got was a white window

**To Reproduce**
Run the command below:
1. xhost +local:
2. docker compose -f docker-compose.yaml -f docker-compose-X11.yaml run --rm openbb (with changes from #4447)
3. stocks/candle -t LIN

**Screenshots**
![image](https://user-images.githubusercontent.com/8901041/233819568-89ccfb0c-d337-4f08-8d56-a8691cef7dde.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Python version [3.10]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by carsanbu** [comment]
I need to check, something changed in latest versions and ruined my solution. My latest tested image was 2.5.1.

**Comment by loongx2** [comment]
Apart from changing docker compose configurations should we be looking at some other components ?

**Comment by piiq** [comment]
hey @loongx2 
your launch command specifies `docker-compose-X11.yaml` when @carsanbu's PR adds `docker-compose.x11.yaml`
can you check that you actually have the second compose file please?

**Comment by loongx2** [comment]
Similar outcome even without xhost +local:

**Comment by hjoaquim** [comment]
@loongx2 are you launching the terminal from within VSCode or on a separate terminal?

**Comment by loongx2** [comment]
I am launching from a normal shell 
Ubuntu 22.04
Docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 23.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-70-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.75GiB
 Name: loong-desktop
 ID: 2U22:TDLK:VTOU:NCQ6:5WZB:AB3Y:6O5V:AXY5:SMTZ:EH4U:4YYS:WCOI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Using default Ubuntu Shell
 Python 3.10.6

It is a native Ubuntu not emulated or VM

**Comment by loongx2** [comment]
tested with docker-desktop but now no windows appear at all maybe the X11 config of mine need changing ?

**Comment by piiq** [comment]
I've asked chatgpt about this and here are some suggestions

When forwarding X11 sessions from a Docker container to the host Ubuntu, you need to ensure that the X11 server is properly configured to accept connections from the container. Here are the steps you can follow:

1. Check if the X11 server is running on the host machine. You can do this by running the following command in the host terminal:

   ```bash
   ps -ef | grep Xorg
   ```
   
   If the X11 server is running, you should see a process with a command similar to `/usr/lib/xorg/Xorg :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch`.

2. Check if the xhost utility is installed on the host machine. You can do this by running the following command:

   ```bash
   which xhost
   ```

3. If the xhost utility is not installed, you can install it by running the following command:

   ```bash
   sudo apt-get install x11-xserver-utils
   ```

4. Allow connections from the Docker container to the X11 server by running the following command on the host machine:

   ```bash
   xhost +local:docker
   ```

5. You can now try running a simple X11 application in the Docker container, such as xeyes, to verify that X11 is working correctly:

   ```bash
   docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ubuntu xeyes
   ```

If you see the eyes window, X11 is working properly, and you can try running your application again. If you still cannot see any windows, there might be an issue with the application itself or its configuration.

**Comment by loongx2** [comment]
There should be bothing wrong on my ubuntu host as I run it natively and use it for everything. The docker desktop however could not launch xeyes

**Comment by loongx2** [comment]
seems to be due to my docker environment unless there are new findings like logs or error prompts I would close this thread

**Comment by deeleeramone** [comment]
Reopening because people are still reporting the same issue.

**Comment by dynamicstrategies** [comment]
Getting the same issue

Everything installs like a charm on Linux Mint 20.3 Una

But then, when trying to plot charts or get any drill down, I always get a white screen. 

The solution proposed by @piiq to test on a clean ubuntu docker image works fine
with a minor caveat that the ubuntu image doesn't come with xeyes preinstalled, but after running `docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ubuntu` then `apt-get update` then `apt-get install x11-apps` then `xeyes` displays the eyes as described. So the X11 is working fine.

I also tried:
`sudo docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /openBB/data:/home/python/OpenBBUserData -v /openBB/terminal:/home/python/.openbb_terminal ghcr.io/openbb-finance/openbbterminal/openbb:latest`

And sadly get the same result - white screen on charts

**downgrading to version 2.5.1 seems to fix the issue as an interim solution** 
So running this works:

`sudo docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /openBB/data:/home/python/OpenBBUserData -v /openBB/terminal:/home/python/.openbb_terminal ghcr.io/openbb-finance/openbbterminal/openbb:2.5.1`

where

`echo $DISPLAY` is `:0`

All the best

**Comment by piiq** [comment]
thanks @dynamicstrategies this helps narrow it a lot

@andrewkenreich @tehcoderer I now think this might be related to how pywry talks to the plots backend and we may need to adjust some network settings of the container for the charts and tables to work

**Comment by loongx2** [comment]
Should there be a announcement that we should revert to OpenBB 2.5.1 for now for native Ubuntu users ? Otherwise can we backport the recent changes to 2.5.1 and deduce which change caused this?

**Comment by piiq** [comment]
At the moment none of the team members who use Ubuntu can replicate this. We will be looking into it further. I would advice ubuntu users to first try out the latest docker image with the latest docs and revert to 2.5.1 only if it's not working

**Comment by deeleeramone** [comment]
The exact same thing happens with WSL as well.  X-Eyes works, but the window does not appear.

**Comment by ronstone2000** [comment]
I am also seeing this on MacOS Ventura 13.3 running OpenBB Terminal 3.0 natively from the installer.

**Comment by piiq** [comment]
> I am also seeing this on MacOS Ventura 13.3 running OpenBB Terminal 3.0 natively from the installer.

what command are you using? i'm on 13.3.1

**Comment by ronstone2000** [comment]
stocks/options/chains

... but I just tried again and got results using a couple of tickers (pg,jnj). Unfortunately I don't recall what ticker I had loaded when it didn't work. If I reproduce, I'll add details here.

**Comment by piiq** [comment]
> stocks/options/chains

so this is most likely unrelated to the issue discussed in this thread. we'll check how chains behave when no data is available

**Comment by carsanbu** [comment]
I'm reproducing this on Debian 12. Unfortunately, I don't know how works the new Pywry backend so I can't debug this.

**Comment by sanoopuio** [comment]
I use OpenBB Terminal v3.0.0 on Ubuntu,  i have kind for same issue . for popup window is not opening at all.

`$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 8
  Running: 1
  Paused: 0
  Stopped: 7
 Images: 71
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-148-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.08GiB
 Name: sanoop-TUXEDO
 ID: HAAW:SIEA:DXWD:7WRX:JUUB:NHT3:ROBF:OFHZ:KUFX:X3TS:536E:TSMC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
`

**Comment by sanoopuio** [comment]
Also when i do docker compose up , I get error "2023 May WARNING: your terminal doesn't support cursor position requests (CPR).
openbb-openbb-1  | 2023 May 08, 03:45 (🐛) / $
"
So I use command "docker run -it IMAGEID"

**Comment by andrewkenreich** [comment]
Another thing that would help -

go to ~/.openbb_terminal and open the .env file - then add -> OPENBB_DEBUG_MODE='True'

This will get us some good prints of what is going on - then once the window opens - you should see a dev console - open this and check if anything is printed in the console and take a screenshot of the elements

**Comment by andrewkenreich** [comment]
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/23067478/9c90b7a7-cb4d-49fd-be70-cfe062b15351)
I tried to recreate on 22.04 and it works for me with docker

**Comment by sanoopuio** [comment]
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/904870/43b27c8f-1f78-434e-a776-303413436ba7)
I added debug and restarted but no debugging information(dev console) shown in my system .

Could you guys let me know if you have a "GTK_PATH" set when you run "env" in the docker?  I am not sure how to check this , i have attached the screen shot of .env file in  ~/.openbb_terminal

**Comment by andrewkenreich** [comment]
> ![image](https://user-images.githubusercontent.com/904870/237307472-43b27c8f-1f78-434e-a776-303413436ba7.png) I added debug and restarted but no debugging information(dev console) shown in my system .
> 
> Could you guys let me know if you have a "GTK_PATH" set when you run "env" in the docker? I am not sure how to check this , i have attached the screen shot of .env file in ~/.openbb_terminal

Are you running from vs code? If so just run "env" from the terminal and hit enter. Then look for the GTK_PATH. If you are running from vs code tho - please also try running it just from the shell outside of vscode and see if that helps - you can find the command to run here https://docs.openbb.co/terminal/installation/docker under Linux at the bottom

**Comment by sanoopuio** [comment]
I ran docker compose -f docker-compose.yaml -f docker-compose.x11.yaml run openbb

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/904870/1e416409-7cb8-4c44-ad54-a7d056eb736f)

I also got a blank window now.
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/904870/53a07dc9-8764-4c01-b217-e6d21ebd3a1e)

**Comment by sanoopuio** [comment]
I dont find anything called 'GTK_PATH=/snap/code/124/usr/lib/x86_64-linux-gnu/gtk-3.0'

but i found 2 entires for GTK as below when typing env

GTK_MODULES=gail:atk-bridge
DBUS_STARTER_BUS_TYPE=session
PWD=/home/sanoop/Projects/openbb
XDG_SESSION_DESKTOP=budgie-desktop
LOGNAME=sanoop
QT_QPA_PLATFORMTHEME=gtk2
XDG_SESSION_TYPE=x11

**Comment by andrewkenreich** [comment]
can you try running with this 

`docker compose -f docker-compose.yaml -f docker-compose.x11.yaml -e WEBKIT_DISABLE_COMPOSITING_MODE=1 run openbb`

**Comment by sanoopuio** [comment]
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/904870/b772fac0-2a00-4172-8c7a-0efcd64335f6)

**Comment by andrewkenreich** [comment]
oops sorry - doesnt work on compose 

here run this one

`docker run -it -e WEBKIT_DISABLE_COMPOSITING_MODE=1 openbb`

**Comment by sanoopuio** [comment]
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/904870/0a238974-2e06-447c-85c1-b50f1822788e)

**Comment by andrewkenreich** [comment]
lol ok last try :)

`docker compose -f docker-compose.yaml -f docker-compose.x11.yaml run -e WEBKIT_DISABLE_COMPOSITING_MODE=1 openbb`

**Comment by andrewkenreich** [comment]
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/23067478/1495e10b-0833-4146-a6cf-f3d726a47028)
this is on 20.04.02 and working from a fresh install

**Comment by loongx2** [comment]
Nice I will try this ...

**Comment by andrewkenreich** [comment]
awesome! good to hear - we will add this to our docs as a workaround as well

**Comment by sanoopuio** [comment]
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/904870/b7dead64-31b0-4027-b878-ae5da14a73ce)

yes it works for me too

**Comment by loongx2** [comment]
I will close this with the workaround command:

docker compose -f docker-compose.yaml -f docker-compose.x11.yaml run -e WEBKIT_DISABLE_COMPOSITING_MODE=1 openbb
