### ISSUE TITLE
[IMPROVE] Support for NSE/BSE i.e Indian Equity Market tickers

### ISSUE THREAD

**Issue by devfinwiz** [OpenBB-finance/OpenBBTerminal#4873]
**What's the feature that should be improved?**
India is an emerging economy and equity exposure of Indians is rising with each day passing. Inclusion of NSE/BSE tickets into OpenBB will drive more users towards it. In my opinion, missing out on these is no less than a tragedy. 

**Describe how you would like the feature improved**
We can use yfinance, Nsepy, etc to include the tickers from NSE/BSE and in turn also expand the database.

**Comment by skhan59bbk** [comment]
Hey - perhaps you just need to set the relevant API keys. I can view NSE/BSE traded tickers just fine.

**Comment by devfinwiz** [comment]
Oh, my bad. I guessed I missed out somewhere...
