### ISSUE TITLE
[Bug] stocks/search -c russia returns a white page

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBBTerminal#4879]
**Describe the bug**

`stocks/search -c russia` returns a white page.

this does not happens with `stocks/search -c argentina` for example

**To Reproduce**
`stocks/search -c russia`

**Screenshots**
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/11668535/234070166-63121013-b91f-4eac-90e8-d94c61505136.png">

**Desktop (please complete the following information):**

openbb conda python on latest develop

**Additional context**
The data is there
<img width="981" alt="image" src="https://user-images.githubusercontent.com/11668535/234071389-7043adbd-9fb5-4210-8d6b-319bb4f961b9.png">

**Comment by tehcoderer** [comment]
fixed in #4860
