### ISSUE TITLE
[Bug] News table prints datetimes as integers

### ISSUE THREAD

**Issue by piiq** [OpenBB-finance/OpenBBTerminal#4880]
**Describe the bug**

The table with news articles (Feedparser source) shows artcle publishing date as integer

**To Reproduce**
`news openai`

**Screenshots**
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/11668535/234072939-e3889e40-9e79-4505-adf9-15f21f349230.png">

**Desktop (please complete the following information):**

openbb python env with latest develop

**Comment by jmaslek** [comment]
im on this one
