### ISSUE TITLE
[Bug] [Installer] An error occurred during installation. Contact the software manufacturer for assistance.

### ISSUE THREAD

**Issue by Tumb1ew33d** [OpenBB-finance/OpenBBTerminal#4912]
**Describe the bug**

I tried the installer on my Mac OS, Apple M1, OS is Ventura 13.3.1

It stops at the very end:

I also gave the correct settings in the Privacy Section. 

It did update on my other Mac that is not M1, its an Intel Core I5

<img width="623" alt="Screenshot 2023-04-26 at 7 56 59 PM" src="https://user-images.githubusercontent.com/118567546/234663063-a40f14ec-40d9-48f8-b2cf-9ecaf7430b73.png">

**Comment by deeleeramone** [comment]
Was there a previous version installed? Did you uninstall it first?

**Comment by Tumb1ew33d** [comment]
Hi, Yes and I uninstalled the previous version.

**Comment by colin99d** [comment]
Hello @Tumb1ew33d thank you so much for sharing this! I have never seen this issue before, but would love to debug it together.
Do you mind running through the installation steps again, and then once you get to this error screen again pressing `command` + `l`. This will bring up the logs. Then please copy and paste them into here.

**Comment by Tumb1ew33d** [comment]
Hi - I'm using the Touch ID. I'll try typing in my password

**Comment by Tumb1ew33d** [comment]
Here's the logs:

Apr 28 18:49:57 Sarahs-MacBook-Pro Installer[1305]: Could not load resource readme: (null)
Apr 28 18:50:11 Sarahs-MacBook-Pro installd[1265]: PackageKit: ----- Begin install -----
Apr 28 18:50:11 Sarahs-MacBook-Pro installd[1265]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=110 "An error occurred while extracting files from the package “OpenBBv3.pkg”." UserInfo={NSLocalizedDescription=An error occurred while extracting files from the package “OpenBBv3.pkg”., NSURL=file://localhost/Users/prosperity/Library/CloudStorage/Dropbox/Mac%20(2)/Downloads/OpenBBv3.pkg#OpenBBTerminal.pkg, PKInstallPackageIdentifier=OpenBB Terminal, NSUnderlyingError=0x14e30afa0 {Error Domain=PKXARArchiveErrorDomain Code=101 "archive open failed" UserInfo={NSURL=file:///Users/prosperity/Library/CloudStorage/Dropbox/Mac%20(2)/Downloads/OpenBBv3.pkg, NSFileOwnerAccountID=501, NSFileHFSTypeCode=0, NSFileSystemFileNumber=76668867, NSFileExtensionHidden=false, NSFileSystemNumber=16777234, NSFileSize=653002700, NSFileGroupOwnerAccountID=20, NSFileHFSCreatorCode=0, NSFileOwnerAccountName=prosperity, NSFilePosixPermissions=420, NSFileCreationDate=2023-04-28 16:36:56 +0000, NSFileType=NSFileTypeRegular, NSFileProtectionKey=NSFileProtectionCompleteUntilFirstUserAuthentication, NSFileGroupOwnerAccountName=staff, NSFileReferenceCount=1, NSFileModificationDate=2023-04-28 16:41:50 +0000, NSLocalizedDescription=archive open failed}}} {
	    NSLocalizedDescription = "An error occurred while extracting files from the package \U201cOpenBBv3.pkg\U201d.";
	    NSURL = "file://localhost/Users/prosperity/Library/CloudStorage/Dropbox/Mac%20(2)/Downloads/OpenBBv3.pkg#OpenBBTerminal.pkg";
	    NSUnderlyingError = "Error Domain=PKXARArchiveErrorDomain Code=101 \"archive open failed\" UserInfo={NSURL=file:///Users/prosperity/Library/CloudStorage/Dropbox/Mac%20(2)/Downloads/OpenBBv3.pkg, NSFileOwnerAccountID=501, NSFileHFSTypeCode=0, NSFileSystemFileNumber=76668867, NSFileExtensionHidden=false, NSFileSystemNumber=16777234, NSFileSize=653002700, NSFileGroupOwnerAccountID=20, NSFileHFSCreatorCode=0, NSFileOwnerAccountName=prosperity, NSFilePosixPermissions=420, NSFileCreationDate=2023-04-28 16:36:56 +0000, NSFi
Apr 28 18:50:12 Sarahs-MacBook-Pro Installer[1305]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
Apr 28 18:50:12 Sarahs-MacBook-Pro Installer[1305]: Displaying 'Install Failed' UI.
Apr 28 18:50:12 Sarahs-MacBook-Pro Installer[1305]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.

**Comment by Tumb1ew33d** [comment]
Well I uploaded this to ChatGPT and it identified the issue. The package installer was downloaded to a Dropbox folder. It recommended I move it to a local folder and then re-run it. It worked! Thanks for your comments and help here!
