### ISSUE TITLE
[Bug] [Installer 3.0.0] `/reports/equity`: async handler deleted by the wrong thread

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4914]
![image](https://user-images.githubusercontent.com/85772166/234722650-e919176c-8f1d-4c00-85e2-a6187c78259d.png)

**Comment by the-praxs** [comment]
@deeleeramone confirming this for all options in the `reports` menu, maybe change the title to - **[Bug] [Installer 3.0.0] `/reports/`: async handler deleted by the wrong thread**?

![image](https://user-images.githubusercontent.com/88149434/235074538-a50cd37f-8601-48d4-80eb-328e2d66a097.png)

![image](https://user-images.githubusercontent.com/88149434/235074725-fd895b55-f179-4f73-879d-74d0785bb1a2.png)

![image](https://user-images.githubusercontent.com/88149434/235074805-0bef30f4-1054-48ed-9c89-eecf85812bf0.png)
