### ISSUE TITLE
[Bug] 'about news' broken link

### ISSUE THREAD

**Issue by skhan59bbk** [OpenBB-finance/OpenBBTerminal#4929]
Looks like a broken link follows the `about news` command...

![image](https://user-images.githubusercontent.com/57355784/235253447-658066fe-f7f0-4af1-8291-bb493c667510.png)

![image](https://user-images.githubusercontent.com/57355784/235253509-6cf8b3c3-f3c7-47a0-9ce7-34bea03a70c4.png)

**Comment by LOne2three** [comment]
I found the issue in the code. The paths need to be reassigned. I'll send a pull request when I'm done

**Comment by deeleeramone** [comment]
@andrewkenreich 

![Screenshot 2023-04-29 at 11 14 48 AM](https://user-images.githubusercontent.com/85772166/235317967-53b9515b-24bd-4f87-a61d-cd55dd3e3f92.png)

**Comment by skhan59bbk** [comment]
Same thing here fwiw... 
Cheers


![image](https://user-images.githubusercontent.com/57355784/235495735-4418fe78-8617-462c-aa79-cb84979ac493.png)

**Comment by deeleeramone** [comment]
The URL created by `/stocks/scr/about set`

```
https://my.openbb.co/app/terminal/commands?path=/stocks/scr/set
```

The URL where it needs to go:

```
https://docs.openbb.co/terminal/reference/stocks/screener/set
```
