### ISSUE TITLE
[Bug] Avoid reporting false dependency-conflicts

### ISSUE THREAD

**Issue by woutervh** [OpenBB-finance/OpenBBTerminal#4930]
**Describe the bug**

in pyproject.toml, you are using range-pinning all dependencies.

Although the poetry-creators promote this as a default, this should be considered harmful,
as it quickly creates an avoidable unnecessary dependency-hell with a multitude of false incompatibility-reports.
see https://iscinumpy.dev/post/bound-version-constraints/ for a detailed write-up.

Range-pinning conflates the concept of abstract dependencies versus concrete dependencies .

In pyproject.toml and setup.py before we should define the *abstract* dependencies, 
a minimum-version can be specified under which there is no compatibility 
but please do not specifiy an upper-bound, unless you are certain your application  will *never* work on that newer version.

Right now, many dependant packages work perfectly fine on their latest releases, yet pyproject.toml forbids them.

Concrete example: my application has a dependency on python-dotenv v1.0 : 

but this pyproject.toml defines:
```
python-dotenv = "^0.19.2"
```

The latest release of python-dotenv is v1.0 and works perfectly fine, yet installation is forbidden.
So this is falsely reporting incompatibilities and creating install-issues where non should exist.

Imagine all your dependencies behaving like this.

To create a reproducible setup *requirements.txt* or *poetry.lock* defines the list of concrete dependencies.

Solution:  replace with only lower-bounds, and wait for bug reports if something *actually* breaks.
```
python-dotenv = ">=0.19.2"
```

**Comment by colin99d** [comment]
Hello @woutervh and thanks for this!

For right now, I do not think this is a good direction for our dependency management. The terminal depends on about 100 pip packages, and needs to work in a number of different platforms:
- Installer (mac, and windows)
- Conda (mac, windows, and linux)
- Docker
- PYPI

I think this route is likely to decrease our confidence in the code. We have had issues with packages in the past causing issues, so I think that being safe is better than potentially allowing breaking changes into the codebase.

However, if someone would like to manually bump dependencies, and then test that all of these distributions still work, we would be very appreciative of that work.

**Comment by woutervh** [comment]
Imagine all of your 100 dependencies starting to report false incompatibilities like this.  
In no time it would become impossible to create a larger-scale project.  
Most of my larger project contains 100 deps. 
Having lots of dependencies is exactly the reason why this needs fixing.

>> Range-pinning conflates the concept of abstract dependencies versus concrete dependencies .

You need concrete dependencies to create a working application / environment.  
That exact set is what you guarantee to work.  requirements.txt or poetry.lock.

>However, if someone would like to manually bump dependencies, 
> and then test that all of these distributions still work, we would be very appreciative of that work.

This is exactly *not*  what this issue is about. 
This is about fixing the *abstract* dependencies, to stop reporting nonsense,
