### ISSUE TITLE
[FR] Loops in routines

### ISSUE THREAD

**Issue by ronstone2000** [OpenBB-finance/OpenBBTerminal#4934]
**What's the problem of not having this feature?**
Automations in routines are limited.

**Describe the solution you would like**
1. Ability to loop over arguments, for example:

```
for ticker in ARGV[*]; do

  balance --ticker $ticker --export balance_comps.xlsx --sheet-name $ticker

done
```

2. Ability to loop over input from a command. e.g:

```
for SYMBOL in stocks/disc/ugs; do

  stocks/ca/ticker $SYMBOL
  get
  performance --export $SYMBOL_comps.xlsx

done
```

**Comment by DidierRLopes** [comment]
Hey @ronstone2000,

This was a great idea. Sorry that I didn't see it before.

I've just started working on this and am looking for feedback, see https://github.com/OpenBB-finance/OpenBBTerminal/pull/5005.

Part 1 is what I added + creating variables on the script + slicing arguments

Part 2 would require a major rewrite  / refactoring. Something we'll probably discuss internally first.

Thank you 🙏🏽
