### ISSUE TITLE
[Bug] `fa/est -t AAPL -e quarterearnings` - data is not returning properly.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4938]
Recreate with: `fa/est -t AAPL -e quarterearnings`

Unknown rows in position 2 & 5.  Unknown column at the index position.

![Screenshot 2023-04-30 at 3 17 08 PM](https://user-images.githubusercontent.com/85772166/235378576-90ef75b5-8b24-48fd-808c-e17180c357a8.png)

**Comment by the-praxs** [comment]
Investigating the issue, I found that these values are not aligned properly. I am working to fix the dataframe.

![image](https://user-images.githubusercontent.com/88149434/235405973-36cf0ce0-7a2f-4032-9f91-cd72771622f3.png)
