### ISSUE TITLE
[Bug] `/stocks/fa/` - Exporting from the tables only works when the `type` is `XLSX`. 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4939]
Recreate with: `/stocks/load aapl/fa/income`

Select either `CSV` or `PNG` as the `type` and then try to export.  Switching to `XLSX` does generate the file in the OpenBBUserData folder, but this is not ideal because there is no message to indicate it was successful and where the file can be found.  Exporting from the tables should open a window to select the destination, like when choosing a CSV file to overlay on a chart.

**Comment by securixhk** [comment]
As far as I've tested : whatever are the selected menus or commands, exports are failing for CSV and PNG format (whatever are the selected settings from the displayed tables).

Thanks in advance @tehcoderer for diving into this `bug` 🙏 !

**Comment by securixhk** [comment]
Hey @tehcoderer @jmaslek :

First of all , thanks for your deep-dive on it.

I've updated OpenBB and tried different exports : issue still remains present (on my end, at least).
Any idea ?
@deeleeramone : what's the behavior on your end ?
Thanks in advance :).

**Comment by deeleeramone** [comment]
> what's the behavior on your end ?

@securixhk - I'm still experiencing the same behaviour.  Reopening the issue.

**Comment by securixhk** [comment]
Thanks for your insight, @deeleeramone !

**Comment by tehcoderer** [comment]
> Hey @tehcoderer @jmaslek :
> 
> First of all , thanks for your deep-dive on it.
> 
> I've updated OpenBB and tried different exports : issue still remains present (on my end, at least). Any idea ? @deeleeramone : what's the behavior on your end ? Thanks in advance :).

Whelp, haha can you test #5019
Hopefully it's resolved 🤞

**Comment by securixhk** [comment]
Thanks @tehcoderer .
Still doesn't work, at least on my end :/ .
