### ISSUE TITLE
[IMPROVE] `stocks/scr/` Unwanted delimiter when exporting Finviz data to csv 

### ISSUE THREAD

**Issue by skhan59bbk** [OpenBB-finance/OpenBBTerminal#4946]
Finviz has a comma in many company names (e.g. where Inc. is part of the name).
Exporting to .csv obviously then adds an extra column where one is not wanted, shifting the data by a column.

Haven't labelled this as a bug, as openbb isn't really doing anything "incorrect". Rather it's something that can be improved to cater for instances like this from a third party data provider. But feel free to relabel if you wish.

![image](https://user-images.githubusercontent.com/57355784/235641718-7d8acbd7-d097-444d-8c97-9131961a074c.png)

![image](https://user-images.githubusercontent.com/57355784/235642049-3ce4f08e-77fb-4868-a0fb-eb2d89c58e44.png)

This is from `stocks/screener`
The export is via the interactive table.

**Comment by deeleeramone** [comment]
Nice find.
