### ISSUE TITLE
[Bug] `Portfolio/po/file` There are no templates or example files included in the Terminal for the parameters.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4961]
There are no templates or presets for the risk parameters included, so the user has no way of using the `params` sub-menu and the `file` command to view default settings for parameters.  It should be automatically loaded with a "default" state.

![Screenshot 2023-05-03 at 9 35 12 AM](https://user-images.githubusercontent.com/85772166/235981535-586051bb-1006-4fab-a3b3-6b35315d11da.png)

![Screenshot 2023-05-03 at 9 32 55 AM](https://user-images.githubusercontent.com/85772166/235981010-ed8ebc0b-3a78-4c96-bde1-a50d2bcab870.png)

The help dialogue suggests that there is a template inside the documentation, but typing `about` leads to a 404 error.  As a user, it is terribly confusing that a basic template which can be used to explore is not immediately available to use.  Without this, there is no way to manually adjust settings and create their own parameters file with `save`.

```
(🦋) /portfolio/po/params/ $ load -h

usage: file [-f FILE [FILE ...]] [-h]

Select parameter file to use (ini or xlsx). The OpenBB Parameters Template can be found inside the Portfolio Optimization documentation. Please type `about`
to access the documentation.

options:
  -f FILE [FILE ...], --file FILE [FILE ...]
                        Parameter file to be used (default: None)
  -h, --help            show this help message (default: False)

For more information and examples, use 'about file' to access the related guide.
```

![Screenshot 2023-05-03 at 9 35 40 AM](https://user-images.githubusercontent.com/85772166/235981657-ad11535e-1639-427b-8d19-ddb2349f91e4.png)

**Comment by the-praxs** [comment]
Not exactly able to understand, is the `file` command broken or the `params` sub-menu?
