### ISSUE TITLE
[Bug] openbb.stocks.candle external_axes=True parameter does not work

### ISSUE THREAD

**Issue by Papalloon** [OpenBB-finance/OpenBBTerminal#4962]
**Describe the bug**
openbb.stocks.candle external_axes=True parameter does not work, seems to return a figure without any axes

**To Reproduce**
from openbb_terminal.sdk import openbb
import matplotlib.pyplot as plt

Ticker = 'AAPL'

VAR = openbb.stocks.load(
    symbol=Ticker,
    start_date='2023-01-01',
    interval='1440')

graph = openbb.stocks.candle(
    data=VAR,
    asset_type=Ticker,
    symbol='',
    external_axes=True)

# save graph to check it
candle_name = f'{Ticker}.png'
plt.savefig(candle_name)

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: W10
- Python version 3.9.6

**Additional context**

This works on 2.5.1:

from openbb_terminal.sdk import openbb
import matplotlib.pyplot as plt

Ticker = 'AAPL'

VAR = openbb.stocks.load(
    symbol=Ticker,
    start_date='2023-01-01',
    interval='1440')

graph = openbb.stocks.candle(
    data=VAR,
    asset_type=Ticker,
    symbol='')

# save graph to check it
candle_name = f'{Ticker}.png'
plt.savefig(candle_name)

**Comment by deeleeramone** [comment]
Matplotlib is not being used, and it looks like you are applying the wrong syntax.

```
df = openbb.stocks.load('AAPL')
fig = openbb.stocks.candle(data = df, symbol = 'AAPL', external_axes = True)
```

![Screenshot 2023-05-03 at 3 37 19 PM](https://user-images.githubusercontent.com/85772166/236065861-a1e19e8e-1e69-4c4b-8e8c-4c3aa3ddd914.png)
