### ISSUE TITLE
[Bug] `/economy/performance` & `valuation` Error:  'Name' - Error: 'list' object has no attribute 'empty'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4966]
Recreate with, `/economy/performance`. 

<img width="519" alt="Screenshot 2023-05-03 at 7 04 32 PM" src="https://user-images.githubusercontent.com/85772166/236095366-9b3c1894-325a-4b54-a726-25537c082252.png">

**Comment by the-praxs** [comment]
Issue with the `finvizfinance` library, header name contains `\n\nName` in place of 'Name'. Hence the errors. Issuing a fix.
