### ISSUE TITLE
[IMPROVE] economy/macro to research topics within OECD database

### ISSUE THREAD

**Issue by DidierRLopes** [OpenBB-finance/OpenBBTerminal#4977]
From user
> In economy/macro, 
It will be nice to add -q for OECD database , because there is a lot of Data base on different topics and some research.

**Comment by the-praxs** [comment]
@DidierRLopes what are the exact requirements for this feature? I have found a Python package that can access OECD data, I am wondering how to integrate it with the `economy/macro` command.

**Comment by the-praxs** [comment]
@bbalouki thank you for the information. I can work on this, but I believe this warrants a new `oecd` command in the menu. Later, we can merge it later with the `macro` command as another source, apart from EconDB.

**Comment by bbalouki** [comment]
@the-praxs if there is anything I can do to help let me know, i am really interested by openbb project..
