### ISSUE TITLE
[Bug] `/portfolio/load --example` The calculations applied when loading the file are way off.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#4982]
When using the `--example` portfolio, the calculated transactions are doing bad math.  It's hard to even guess at what it's doing because the numbers have seemingly no relationship to the ones in the spreadsheet.  The supplied example holdings file is not usable at all, and raises questions on the validity of any calculations done within the menu.

`/portfolio/load --example`

Below is pasted from Excel directly.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/danglewood/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/danglewood/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Date | Ticker | Type | Sector | Industry | Country | Region | Price | Quantity | Fees | Premium | Investment | Side | Currency
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2010-05-03 | GOOGL | Stock | Communication Services | Internet Content & Information | United States | North America | 13.27 | 2 | 5 | 6 | 21.54 | Buy | USD
2010-07-06 | AMZN | Stock | Technology | Internet Retail | United States | North America | 5.5 | 5 | 3 | 3 | 24.5 | Buy | USD
2011-08-06 | AAPL | Stock | Technology | Consumer Electronics | United States | North America | 12.61 | 3 | 1 | 0 | 36.83 | Buy | USD
2011-12-12 | APTV | Stock | Consumer Cyclical | Auto Parts | United States | North America | 18.02 | 5 | 0 | 2 | 90.1 | Buy | USD

</body>

</html>

Displaying the loaded holdings.

```
show
```

![Screenshot 2023-05-05 at 3 11 23 PM](https://user-images.githubusercontent.com/85772166/236576970-f2a59007-06ea-45ec-83c0-8753e2de67ca.png)

The problem is illustrated clearly using the `yret` command.

<img width="1481" alt="Screenshot 2023-05-05 at 3 16 33 PM" src="https://user-images.githubusercontent.com/85772166/236577543-24f45b55-da25-4599-8d7e-af243e2cb9a0.png">

There are two transactions from 2016 in the spreadsheet, 4 shares in total worth about $173 (according to the Investment column)

![Screenshot 2023-05-05 at 3 17 29 PM](https://user-images.githubusercontent.com/85772166/236577636-95baed1e-b6fb-403e-a525-7694e8557c5d.png)

**Comment by deeleeramone** [comment]
Adding fuel to the fire, I get very different price results using similar methods:

```
P = openbb.portfolio.load("/Users/danglewood/GitHub/OpenBBTerminal/openbb_terminal/miscellaneous/portfolio/holdings_example.xlsx")
P.portfolio_historical_prices
```

vs

```
openbb.stocks.ca.hist(similar = ["AAPL", "AMZN", "APTV", "ASML", "BABA", "DGX", "GOOGL", "NKE", "TSM", "YUM"], candle_type = 'c', start_date = "2010-05-03", end_date = "2023-05-19")
```

![Screenshot 2023-05-20 at 8 52 33 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/77fad9b5-8a14-4059-b18d-94e9d0317486)

**Comment by jmaslek** [comment]
this is definitely because the split calculation that was introduced.  if we look at the google line , P=13.97, Q = 2, from 2010-05-03.

They have undergone 3 (weird) splits, basically, 2,1,20, so a total of 40(ish):1

This means that split adjusted, your P should be 14/40 and Q = 2*40 -> which lines up up with .3 and 79 you have in the show.

If you look at the comments in the PR introducing that, it is unclear whether input data should be split adjusted or not

I am also thinking that there is a lack of dividend processing.  If we look at your comp between portfolio_historical ca, AMZN and GOOGL (not div stocks)  match up.  The others (ignoring the ones that are backfilled), dont match and do pay dividends.  Not sure why this happens (if you actually look at adj_close and close from yahoo finance, they tend to be the same).

Not solutions, but at least have identified the differences

**Comment by deeleeramone** [comment]
I think the most reasonable approach to splits and dividends would be to make the user supply their split-adjusted entry price and share count.  Meaning, if they bought 5 AMZN shares at $2000, they need to adjust their ledger to be 100 shares at a cost-basis of $100 to account for the recent 1:20 split.  Dividends could be added in the future as an automated method with a choice of cash deposit to the portfolio, or, a DRIP-style fractional allotment of shares per dividend, recorded on the payment date.

**Comment by deeleeramone** [comment]
Some more stuff to add here:

![Screenshot 2023-10-11 at 11 29 09 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/f79be0de-1e21-44ec-ba8d-bd15f6e005a6)
