### ISSUE TITLE
[IMPROVE] openbb_terminal/reports

### ISSUE THREAD

**Issue by vvronskyFX** [OpenBB-finance/OpenBBTerminal#4985]
**What's the feature that should be improved?**
The ability for analysts to create their own reports. The link to recreate a report leads to a 404 - Page Not found.

**Describe how you would like the feature improved**
Create a seamless way for analysts to create their own reports.

**Possibly describe the ideal way to improve this**
Have a template .ipynb file with comments.

**Additional information**
See screenshots
![image](https://user-images.githubusercontent.com/64465297/236644233-c61ecbcf-6cc2-4ddd-9705-15ded55e8fca.png)

**Comment by deeleeramone** [comment]
There is no "dark_pool.ipynb" template. 

![Uploading Screenshot 2023-05-06 at 3.21.33 PM.png…]()

Seems like the hyperlink shouldn't exist there. 

![Screenshot 2023-05-06 at 3 23 10 PM](https://user-images.githubusercontent.com/85772166/236648736-6c04bc35-2759-4235-bd38-2274f14da9d5.png)

Try a different one:

https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_terminal/reports/templates
