### ISSUE TITLE
[Bug] Routines - the `/stocks/scr/set` command does not appear to work in a routine.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5000]
The routines appear to skip right over the command.

Here's the routine:

```
stocks
scr
set --preset oversold
performance --limit 200 --export oversold-perf.csv
set --preset reversal
performance --limit 200 --export reversal-perf.csv
set --preset undervalue
performance --limit 200 --export undervalue-perf.csv
set --preset golden-cross
performance --limit 200 --export golden-perf.csv
set --preset head_shoulders_inverse
performance --limit 200 --export hs-inverse-perf.csv
home
```

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/0824f001-de2c-4bb5-87ee-fb6d6909aec3)
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/bcfdb139-bd8c-4731-a03c-f23387fcded3)

Entering the command as a one-liner works:

```
/stocks/scr/set --preset oversold/
```

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/0d0c2f2c-4edd-4ce6-82e2-5470226ce7b7)

**Comment by MelikBelkhiria** [comment]
Unfortunately, I couldn't reproduce the bug. My output was unexpected. Following the routine you described, running the line `performance --limit 200 --export undervalue-perf.csv` gives me the following output: 
[
![Screenshot 2023-05-12 203213](https://github.com/OpenBB-finance/OpenBBTerminal/assets/119343734/19f9692e-56ff-41ac-8ddf-c8b0faca5f56)
](url)

**Comment by deeleeramone** [comment]
The error that you are experiencing has been fixed recently. :(

https://github.com/OpenBB-finance/OpenBBTerminal/pull/4954
