### ISSUE TITLE
[Bug] Error Running 'pip install .'

### ISSUE THREAD

**Issue by DyNour** [OpenBB-finance/OpenBBTerminal#5007]
**Describe the bug**
Running into errors during `pip install .` on Windows.

**To Reproduce**
Run `pip install .`

**Screenshots**
![CI1](https://github.com/OpenBB-finance/OpenBBTerminal/assets/116679073/a8d2dc0d-3591-4035-a0e0-4bffd0088cc2)

**Desktop (please complete the following information):**

- OS: Windows 10
- Python version 3.11

**Additional context**
Add any other information that you think could be useful for us.

**Comment by jmaslek** [comment]
As you can see from your error message, you are running python 2.7 and not 3.11

**Comment by deeleeramone** [comment]
Not a good idea to install this at the system level. Follow the instructions here:
https://my.openbb.co/app/sdk/installation

**Comment by DyNour** [comment]
> As you can see from your error message, you are running python 2.7 and not 3.11
The thing is I don't really understand why it's telling me 2.7:
![C2](https://github.com/OpenBB-finance/OpenBBTerminal/assets/116679073/4c341284-39f8-4c72-a704-ce13f54a4974)

**Comment by deeleeramone** [comment]
That doesn't look like you are following the installation instructions and creating a virtual environment.

**Comment by DyNour** [comment]
> That doesn't look like you are following the installation instructions and creating a virtual environment. Python 3.11 is also not compatible with this library.

You are right, the issue seems to be with python 3.11, I installed a previous version and it was fixed
