### ISSUE TITLE
[Bug] `/stocks/options/eodchains` Does not return the entire options chain, only returns current exipiration dates.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5014]
When you call `eodchains`, it only returns data that has an expiration date that is in the future.  This means that requesting the EOD chain from May 2020 returns no results instead of the entire options chain at the end of that day.

![Screenshot 2023-05-12 at 8 55 28 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/7cdc410e-d479-4995-b789-37e5b0a58b30)

![Screenshot 2023-05-12 at 8 57 01 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/4db670a0-0f23-45d0-bc65-b5ffc13b2ec9)

**Comment by the-praxs** [comment]
Maybe the underlying function use `get_options_chain()` rather than `get_options_chain_eod()`?

**Comment by deeleeramone** [comment]
Related to this:

![Screenshot 2023-05-13 at 10 27 04 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/95404574-505a-4967-99b4-5f73486c8550)

**Comment by jmaslek** [comment]
Im checking with them, but this is a limitation of the data and we do not have access to that far back.  If I iterate historically, I can get spy for 2021-12-30, so the function is working as expected.

**Comment by jmaslek** [comment]
There are two things going on here.  1 is that I did incorrectly crop the expiration_date.  Fixing that in my bug pr.

The second is that we cant access data from a certain point on our plan.  I have asked them how far back it goes, but from this screenshot, I can get expected from 2021-12-30, but not from 2021-05-02

<img width="1024" alt="Screenshot 2023-05-19 at 4 49 36 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/f4fad5c6-af0e-4fe3-9194-6a471172c940">

**Comment by jmaslek** [comment]
Can confirm we only get historical eod chains until oct 2021 ish
