### ISSUE TITLE
[Bug] Terminal does not remember login after next session

### ISSUE THREAD

**Issue by the-praxs** [OpenBB-finance/OpenBBTerminal#5015]
When I open the terminal, log in, and set it to remember, it does not work. The next time I open the terminal I am logged in as a guest and have to login again, but my credentials are not required.

To reproduce this error:
* `/account/login` - Provide your credentials and select `y` to remember.
* `exit`
* Open the terminal again, you should be logged in as a guest
* `/account/login` - No credentials will be required this time

**Comment by MelikBelkhiria** [comment]
It works perfectly fine for me. This is what gets displayed in my terminal: 
[
![Screenshot (27)](https://github.com/OpenBB-finance/OpenBBTerminal/assets/119343734/24d16fad-3408-4add-bf34-32ac30d07088)
](url)

**Comment by MelikBelkhiria** [comment]
What version of the terminal are you currently running?

**Comment by the-praxs** [comment]
I am running v3.0.0 on the latest `develop` branch.

**Comment by AdamBenAlaya** [comment]
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/100477405/73f54020-833b-4af0-80cd-a4e15173c60b)
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/100477405/9e14e768-9d8f-4d52-906f-47030ad2fede)
I had the same bug here when I logged back again I logged in as a guest, but when I used the command /account/login 
I logged in again with my account without entering my credentials

**Comment by MelikBelkhiria** [comment]
@the-praxs I think this is not an error. The behaviour you mentionned describes perfectly that the "remember me" works perfectly. 
Once you login and set it to remember, when you run the terminal and login again you don't have to provide the credentials which is expected unless you logout.

**Comment by the-praxs** [comment]
I guess that's one way to look at it.

**Comment by the-praxs** [comment]
I believe that it should log in automatically if set to remember. Will have a look at this later.

**Comment by montezdesousa** [comment]
There are different flows wether you are using the source version or the installer. 

* Source version: you login as guest by default
* Installer version: you get asked for email/password or login automatically if "remember me" was set to "y" in a previous session

I understand you expect the installer behaviour while using the source version. There was an assumption that source users would prefer not to login by default. We kept the option in `openbb --login`

So if you wish to login without having to go to `/account/login` in the source version you can use `openbb --login` and it will ask you for email/password or login automatically if "remember me" was set to "y" in a previous session.

**Comment by the-praxs** [comment]
@montezdesousa thank you for providing this information. I am closing this.
