### ISSUE TITLE
[Bug] `reset` command throws error and quits the terminal

### ISSUE THREAD

**Issue by the-praxs** [OpenBB-finance/OpenBBTerminal#5016]
If I try to reset my terminal, I get the error `Unfortunately, resetting wasn't possible!`. Having this error since today.

**Comment by AdamBenAlaya** [comment]
this bug  acquired to me when I was running multiple instances of open bb terminal did you try closing all of them they may prevent resetting.

**Comment by tehcoderer** [comment]
Fixed on #5017 !
