### ISSUE TITLE
[Bug] Zero values are represented as blank fields in tables

### ISSUE THREAD

**Issue by JerBouma** [OpenBB-finance/OpenBBTerminal#5020]
For certain datasets, 0 and 1 have a clear meaning. Representing 0 as nothing is simply invalid. Furthermore, I would always show the actual data and not erase it.

Clear example is Econometrics in which 0 = False and 1 = True while the following screenshot shows blank fields instead.

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/46355364/1740cc31-2427-4dcf-88e9-2b9d17f33692)

**Comment by tehcoderer** [comment]
Fixed in #5019
