### ISSUE TITLE
[Bug] `/stocks/options/chains` - the default state, `-1`, for `min/max` argument does not appear to work.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5027]
Recreate this with:

```
stocks/options/load OXY/exp 2024-01-19/chains
```

Then do:

```
chains --min 1
```

The default state for `min/max` on the command is `-1`.

![Screenshot 2023-05-15 at 10 35 30 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/2ce75134-2848-43c4-8542-a396144b2673)

```
chains --max 1000
```

![Screenshot 2023-05-15 at 10 39 01 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/7b8dec25-7dad-4d1e-a456-6187d706ca10)

vs the default sorted value for highest strike price:

```
chains
```

![Screenshot 2023-05-15 at 10 40 45 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/8def9a1e-101f-4e31-8505-c643ddb57df0)

```
Display option chains

options:
  -c, --calls           Flag to show calls only (default: False)
  -p, --puts            Flag to show puts only (default: False)
  -m MIN_SP, --min MIN_SP
                        minimum strike price to consider. (default: -1)
  -M MAX_SP, --max MAX_SP
                        maximum strike price to consider. (default: -1)
```

**Comment by andrewkenreich** [comment]
is this after my fix? it didnt get merged for the release

**Comment by andrewkenreich** [comment]
Just tested and this isnt an issue on dev
