### ISSUE TITLE
[Bug] `/fixedincome/spot --description`  Function prints an extremely verbose output and also displays a chart.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5032]
To see this behaviour, `/fixedincome/spot --description`

This output should probably open in a PyWry window instead of a console print, and the chart should not be displayed when the `--description` argument is active.

**Comment by LOne2three** [comment]
It seems to me like the descriptions are either the same or a variation of the same message for every description. Maybe its best to  print a template description if maturity is not set or the template description with maturity subbed in when maturity is set
