### ISSUE TITLE
[Bug] `/stocks/ins/lins` - No insider information found for WMT

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5040]
The error is probably similar to the other recent issues from the Finviz library that have been patched already.

`/stocks/load wmt/ins/lins`

![Screenshot 2023-05-17 at 1 15 20 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/f1fbd13f-a17d-498b-bae7-0f205ddd44e4)

https://github.com/OpenBB-finance/OpenBBTerminal/pull/5010
https://github.com/OpenBB-finance/OpenBBTerminal/pull/4954
https://github.com/OpenBB-finance/OpenBBTerminal/pull/3732

**Comment by jmaslek** [comment]
error is directly in the finviz library we use:

<img width="396" alt="Screenshot 2023-05-19 at 3 00 02 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/4525d765-0eac-435b-9d25-e019eb12f3e1">

**Comment by jmaslek** [comment]
Found the cause.  Will need to update when this is fixed:

https://github.com/mariostoev/finviz/pull/170

**Comment by the-praxs** [comment]
I thought we were using finvizfinance api. This one is different.

**Comment by deeleeramone** [comment]
Looks like there's two different Finviz libraries in the dependencies..

**Comment by deeleeramone** [comment]
https://github.com/mariostoev/finviz/pull/171 

This will be a needed fix as well.
