### ISSUE TITLE
[Bug] `/stocks/options/hist --source Intrinio` Chart title is not in an editable position.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5053]
When `--source Intrinio`, the title for this chart cannot be edited.  Additionally, this function can be used without anything being loaded, but when doing so, the title is "None" and "Call", instead of the ChainID.

`stocks/options/hist --chain SPY230523C00400000 --source Intrinio`

![Screenshot 2023-05-20 at 2 55 47 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/3b09c8dd-9cbe-49ee-898f-822c622c8b7d)

`stocks/options/hist --chain SPY230523C00400000 --source Tradier`

![Screenshot 2023-05-20 at 2 58 22 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/bcf0894e-c769-4109-ab32-f436bec01f61)

**Comment by tehcoderer** [comment]
fixed in #5064
