### ISSUE TITLE
[Bug] `stocks/options/screen` - Errno 61 Connection refused.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5083]
When you attempt to use the Options screener, an error message is printed: 

```
There was an error connecting to the API. Please try again later.
```

Attempting to use the function at the model level, `get_screener_output()`, shows the error as "Connection refused".

```
Exception: HTTPSConnectionPool(host='api.syncretism.io', port=443): Max retries exceeded with url: [/ops](https://file+.vscode-resource.vscode-cdn.net/ops) (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1072b5600>: Failed to establish a new connection: [Errno 61] Connection refused'))
```

**Comment by jmaslek** [comment]
yeah looks like the site is down as well (ops.syncretism.io).  Can ping and ask if its going to be kept up.

**Comment by jmaslek** [comment]
The repo has been archived:

https://github.com/Tyruiop/syncretism

**Comment by deeleeramone** [comment]
rip
