### ISSUE TITLE
[Bug] `stocks/ca/tsne` Prompt Toolkit DeprecationWarning: There is no current event loop.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5093]
See the warning with:

```
/stocks/load AAPL/ca/tsne
```

```
/Users/danglewood/GitHub/Conda_M1/miniconda3/envs/obb/lib/python3.10/site-packages/prompt_toolkit/application/application.py:955: DeprecationWarning:

There is no current event loop
```

The command does work.

**Comment by deeleeramone** [comment]
Likely, 3.10 sports "enhanced error messages".

**Comment by jmaslek** [comment]
you still getting this?

**Comment by deeleeramone** [comment]
> you still getting this?

Yup.
![Screenshot 2023-08-07 at 2 41 14 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/4ef69cc3-9f4f-46a4-9557-9d78d980eb6e)

**Comment by colin99d** [comment]
@deeleeramone I am not getting this, are you still getting it?
