### ISSUE TITLE
[IMPROVE] Error messages when API keys are not found

### ISSUE THREAD

**Issue by AlexanderLavelle** [OpenBB-finance/OpenBBTerminal#5103]
**What's the feature that should be improved?**
When you attempt to load data from a source for which you do not have access (let's say `AlphaVantage`), the error returned is about a variable assignment. The same code works fine with public data (`yf` or the default source). 

**Describe how you would like the feature improved**
This should be twofold:
1.) Directly say that the user does not have the API key
2.) Offer clearer information about potential sources that the function takes (potentially suggest other source strings)

**Possibly describe the ideal way to improve this**
More error handling, like assert or try/except. I assume something ends up being empty or None but the function continues working.

**Additional information**
```python
openbb_terminal.api.stocks.load(
    'AAPL',
    start=datetime.datetime(2023,5,25), 
    end=datetime.datetime(2023,6,1), 
    interval=5,
    source='AlphaVantage'
)
```

error message:
```python
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[42], line 1
----> 1 openbb_terminal.api.stocks.load(
      2     'AAPL',
      3     start=datetime.datetime(2023,5,25), 
      4     end=datetime.datetime(2023,6,1), 
      5     interval=5,
      6     source='AlphaVantage'
      7 )

File ~/Python Projects/Finance/transformers/OpenBBTerminal/openbb_terminal/stocks/stocks_helper.py:539, in load(ticker, start, interval, end, prepost, source, iexrange, weekly, monthly)
    536         s_interval = f"{interval}min"
    537     int_string = "Intraday"
--> 539 s_intraday = (f"Intraday {s_interval}", int_string)[interval == 1440]
    541 console.print(
    542     f"\nLoading {s_intraday} {ticker.upper()} stock "
    543     f"with starting period {s_start.strftime('%Y-%m-%d')} for analysis.",
    544 )
    546 return df_stock_candidate

UnboundLocalError: local variable 's_interval' referenced before assignment
```

**Comment by deeleeramone** [comment]
This syntax looks old. What version are you using? We have been using the convention of: `from openbb_terminal.sdk import openbb` for a long while now. What does `openbb.__version__` show?

**Comment by AlexanderLavelle** [comment]
@deeleeramone I started a new environment with py 3.10 (up from 3.8), but then I was still having issues. Perhaps it's more related to pip installing? Must one install from source only?

**Comment by deeleeramone** [comment]
I'm talking about your actual local code folder, @AlexanderLavelle.  According to your path, you are using a GitHub cloned repo.  How long ago was this cloned, and when was the last time you updated it?

What your output of `openbb.__version__`?

The syntax `openbb_terminal.api` does not exist anymore, and every function that calls an API source has a decorator that checks for a valid API key.

**Comment by colin99d** [comment]
I am closing because it looks like the issue has to do with an old version of our product being used. @AlexanderLavelle if you still have issues after updating, or need any other help, please let me know.
