### ISSUE TITLE
[Bug] Bug Report: 'utf-8' codec decoding error on Windows 11

### ISSUE THREAD

**Issue by NunoBatistaReis** [OpenBB-finance/OpenBBTerminal#5109]
**Describe the bug**
After installing Open BB terminal version 3.0.1 on Windows 11, the application crashes with an error message stating "'utf-8' codec can't decode byte 0xe1 in position 570: invalid continuation byte." This error prevents the terminal from executing properly and results in an unhandled exception.

**To Reproduce**
Ensure that the operating system is Windows 11.
Download and install Open BB terminal version 3.0.1.
Launch the Open BB terminal application.
Observe the crash with the error message: "'utf-8' codec can't decode byte 0xe1 in position 570: invalid continuation byte [15756] Failed to execute script 'terminal' due to unhandled exception!"

**Screenshots**

![OpenBB_Issue](https://github.com/OpenBB-finance/OpenBBTerminal/assets/61207873/9f5e232c-be86-4063-a18e-1549bb01649d)

**Desktop (please complete the following information):**

- OS: Windows 11
- Windows.OpenBB.Terminal.v3.0.1

**Comment by deeleeramone** [comment]
Hello,

Can you confirm that you have enabled UTF-8 in the Windows language settings?

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/5191b03b-2848-45e1-bd79-e3649131c4cc)

**Comment by NunoBatistaReis** [comment]
Hello!
I did not have UTF-8 enabled before.
Now I have enabled it, but I'm still getting the same result.

**Comment by deeleeramone** [comment]
What is the language set under: "Current system locale"?  Do you have any language packs installed? (In Control Panel, "Time & Language --> Language".  @piiq, do you know of any local language settings that would affect the character decoding on a Windows machine & CMD?

**Comment by piiq** [comment]
> Now I have enabled it, but I'm still getting the same result.

You did reboot after changing the setting, right?

**Comment by NunoBatistaReis** [comment]
Yes, I did reboot after changing. 
This is my current configurations: 
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/61207873/8d2bf4bd-1a42-4db4-bc27-21766bbf5fda)
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/61207873/58c78ba5-a2ce-486f-9c34-3dd39ebe74f2)

**Comment by NunoBatistaReis** [comment]
This could be important information:
I had previously installed an older version of openBB, which was working fine.
However, I haven't used it for a while. Therefore, before attempting to open the older version, I decided to install the latest version.
Now, I'm uncertain if this issue is related to any residual files from the previous version. Could that be the cause?

**Comment by piiq** [comment]
Seems unlikely but everything is possible. 
Just to confirm, if you uninstall all openbb terminals, reboot and install the latest one you get this unicode error, right?

**Comment by piiq** [comment]
The error comes up when there is an attempt to load the .env with some of the settings. 
What was the old version that you had?
I would try to look for the files that contain environment variables and look if there's something odd in them (or just delete them)
@andrewkenreich @deeleeramone  can you point to locations where some of the .env files can be found on windows builds?

**Comment by deeleeramone** [comment]
What about the flair emoji? That could be getting lost in translation.

`.env` files are located in the root of the user account, under `\.openbb_terminal`, and in the installation folder.

**Comment by NunoBatistaReis** [comment]
Yes, I unistalled all openbb terminals, rebooted and install the latest version. Once I open it, I got the unicode error.

**Comment by NunoBatistaReis** [comment]
Unfortunately, I don't know which was the old version.

**Comment by NunoBatistaReis** [comment]
Thanks, got it!
There was a special character at OPENBB_USE_FLAIR='[Olá]'. 
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/61207873/4da85a3b-3dda-4d9b-8672-ef49b98d6b06)

**Comment by deeleeramone** [comment]
> There was a special character at OPENBB_USE_FLAIR='[Olá]'.

Nice. Excellent work!!

**Comment by NunoBatistaReis** [comment]
Solved!
