### ISSUE TITLE
[Bug] Current Reddit API appears to be deprecated.  All commands return with: `Wrong Reddit API keys`

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5110]
Pretty sure it's related to this: https://www.theverge.com/2023/5/31/23743993/reddit-apollo-client-api-cost

**Comment by jmaslek** [comment]
Looks like some of the commands are back?

**Comment by deeleeramone** [comment]
It does appear that the error message has changed.  

```
(🦋) /stocks/ba/ $ load AAPL

Loading Daily data for AAPL with starting period 2020-06-01.

(🦋) /stocks/ba/ $ popular --sub wsb

Searching for tickers in latest 10 'wsb' posts
  0 potential tickers found.
Error: Length mismatch: Expected axis has 0 elements, new values have 1 elements

Error: 'list' object has no attribute 'empty'


(🦋) /stocks/ba/ $ popular --sub wsb --num 100

Searching for tickers in latest 100 'wsb' posts
  0 potential tickers found.
Error: Length mismatch: Expected axis has 0 elements, new values have 1 elements

Error: 'list' object has no attribute 'empty'

(🦋) /stocks/ba/ $ getdd

No DD posts found


(🦋) /stocks/ba/ $ getdd --all

No DD posts found


(🦋) /stocks/ba/ $
```

**Comment by shruzki** [comment]
Will teddit.net help with this?
https://codeberg.org/teddit/teddit/wiki#teddit-api

**Comment by deeleeramone** [comment]
It will be safe to assume that all methods providing programmatic access to Reddit will be impacted by the changes being implemented.

https://www.forbes.com/sites/antoniopequenoiv/2023/06/13/reddit-stands-by-controversial-api-changes-as-subreddit-protest-continues/?sh=1a3ddba2d5d2

**Comment by joshuabuildsthings** [comment]
@deeleeramone @shruzki - Looks like Teddit works part of the time, but that Reddit is making an effort to block it.

[Instances being blocked by Reddit #411](https://codeberg.org/teddit/teddit/issues/411)

**Comment by deeleeramone** [comment]
Between "part of the time", and knowing with certainty that Reddit is not changing their stance on programmatic access to their data, it doesn't bode well. :(
