### ISSUE TITLE
[Bug] Error to import name 'rp' from 'riskfolio'

### ISSUE THREAD

**Issue by htmehdi** [OpenBB-finance/OpenBBTerminal#5116]
**Describe the bug**
When I try to run from openbb_terminal.sdk import openbb I got the following error:

ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 from openbb_terminal.sdk import openbb

File ~/opt/anaconda3/envs/Trading/lib/python3.10/site-packages/openbb_terminal/sdk.py:29
     25 from openbb_terminal.reports import widget_helpers as widgets  # noqa: F401
     27 from openbb_terminal.reports.reports_controller import ReportController
---> 29 import openbb_terminal.core.sdk.sdk_init as lib
     31 from openbb_terminal.core.sdk import (
     32     controllers as ctrl,
     33     models as model,
     34 )
     36 from openbb_terminal.core.session.current_system import get_current_system

File ~/opt/anaconda3/envs/Trading/lib/python3.10/site-packages/openbb_terminal/core/sdk/sdk_init.py:587
    582 from openbb_terminal.portfolio import portfolio_model, portfolio_view
    584 try:
    585     # pylint: disable=W0611 # noqa: F401 # pyright: reportMissingImports=false
--> 587     from openbb_terminal.portfolio.portfolio_optimization import (
    588         excel_model as portfolio_optimization_excel_model,
    589         optimizer_model as portfolio_optimization_optimizer_model,
    590         optimizer_view as portfolio_optimization_optimizer_view,
    591         po_model as portfolio_optimization_po_model,
    592         po_view as portfolio_optimization_po_view,
    593     )
    595     OPTIMIZATION_TOOLKIT_ENABLED = True
    597 except ModuleNotFoundError:

File ~/opt/anaconda3/envs/Trading/lib/python3.10/site-packages/openbb_terminal/portfolio/portfolio_optimization/po_model.py:14
     12 from numpy import floating
     13 from numpy.typing import NDArray
---> 14 from riskfolio import rp
     16 from openbb_terminal.decorators import log_start_end
     17 from openbb_terminal.portfolio.portfolio_optimization import (
     18     optimizer_helper,
     19     optimizer_model,
     20 )

ImportError: cannot import name 'rp' from 'riskfolio' (/Users/opt/anaconda3/envs/Trading/lib/python3.10/site-packages/riskfolio/__init__.py)

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac M1
- Python version 3.10.9

**Additional context**

**Comment by deeleeramone** [comment]
Hi there, you can resolve this issue by downgrading the version of riskfolio.

`pip install riskfolio==3.3.0`

**Comment by htmehdi** [comment]
Thank you for getting back to me so quickly.

I've done it, but it gave me this error: 
cvxpy 1.3.1 requires setuptools>65.5.1, but you have setuptools 65.4.1 which is incompatible.

Will this cause any other issues in the future?

**Comment by deeleeramone** [comment]
You can probably just ignore this as it's just a warning.

**Comment by htmehdi** [comment]
Thank you very much. Suggestion: it would benefit other users if you add a section in "https://docs.openbb.co/terminal/installation/pypi" regarding "riskfolio-lib" version adjustment.

Best,
