### ISSUE TITLE
[Bug] Connecting to Degiro fails

### ISSUE THREAD

**Issue by filiprejmus** [OpenBB-finance/OpenBBTerminal#5123]
**Describe the bug**
I tried setting up the Keys for Degiro with
`/keys/degiro -u USERNAME -p PASSWORD`
It fails and when I try `/portfolio/bro/degiro/ $ login` I get error `Error: 'NoneType' object is not callable`

**To Reproduce**
The same as in the description

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: MacOS14
- Python version 3.11.3

**Comment by colin99d** [comment]
I believe you can run debug mode by doing this before opening the terminal `export DEBUG_MODE=true`. Let me know if this works,
