### ISSUE TITLE
[Bug] `/crypto/dd/info` - Terminal hangs, must keyboard interrupt. Error: __init__() should return None, not 'list'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5129]
Recreate with: `/crypto/load eth/dd/info`, or any coin. 

![Screenshot 2023-06-12 at 11 52 33 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/cd37c392-ae05-4095-81c1-2df2605377d5)

**Comment by jmaslek** [comment]
if i launch in debug mode - I cant even use the crypto/load function (trace says stuck in loading coingecko list)

Both seem to point towards CoinGecko.

**Comment by IgorWounds** [comment]
Is this because CoinGecko is being overloaded with requests? If so, this isn't on us but we should have a timer to close it down after X seconds of inactivity.

**Comment by jmaslek** [comment]
It could potentially be.  They dont have a set limit of API requests per minute.  But lemme try something

**Comment by jmaslek** [comment]
hmmm.  tried overwriting the coingeckoAPI request_timeout to see if that changed it, but it did not

**Comment by jmaslek** [comment]
So my hypothesis is that we are getting rate limited on the free tier.  The coingecko api gets called on any crypto/load (via get_coingecko_id), so when we call another cg function, we have already called the api at least a couple times.

When it hangs, it eventually returns data (takes a minute or two), so I think this is more of a limitation than an actual bug.

**Comment by jmaslek** [comment]
closing since it technically doesnt hang, but rather the api takes minutes to reply.  only option on our end would be to remove the function
