### ISSUE TITLE
[Bug] sdk openbb.stocks.fa.overview("ticker", source = "YahooFinance") not working

### ISSUE THREAD

**Issue by stephaniec2020** [OpenBB-finance/OpenBBTerminal#5130]
**Describe the bug**
openbb.stocks.fa.overview("ticker", source = "YahooFinance") has an error

**To Reproduce**
https://docs.openbb.co/sdk/reference/stocks/fa/overview doc listed that I could add argument of which data provider that I would prefer, seems like only one argument is accepted - ticker, and only AlphaVantage as a source is working.

**Screenshots**
Error: get_overview() got an unexpected keyword argument 'source'

**Desktop (please complete the following information):**
- OS: Mac Monterey M1
- Python version 3.9.6

**Comment by tehcoderer** [comment]
You might be running an outdated version of the sdk.  

**Try updating by running `pip install openbb -U --force`**

```python
from openbb_terminal.sdk import openbb
print(f"openbb version: {openbb.__version__}")
openbb.stocks.fa.overview("TSLA", source = "YahooFinance")
```

Should return 
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/61340027/a0e61880-dd55-47a3-849b-55b17079f348)

**Comment by stephaniec2020** [comment]
It's working now, thanks!
