### ISSUE TITLE
[Bug]Unable to load XAUUAD(GOLD) data in forex

### ISSUE THREAD

**Issue by syedsajjadaskari** [OpenBB-finance/OpenBBTerminal#5143]
**Describe the bug**
Unable to load the data of xauusd and xagusd data in openbbterminal.

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.
![Screenshot 2023-06-15 at 7 57 20 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/84753561/c782aa0d-669d-4b8a-9c0f-480fb8a65703)

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by bimbolimbo** [comment]
Hello! 😄 

I have not come across any evident issues with openbbterminal or yfinance source code that is directly related to the problem mentioned. Nonetheless, I have noticed that currently, there is a lack of historical data available for xauusd=x and xagusd=x on Yahoo Finance. Maybe that's the problem.

**Comment by jmaslek** [comment]
Looks like it is not supported on yf.  However it is in the list of polygon tickers, so if you have the free api key, you may be able to access there.

**Comment by jmaslek** [comment]
Confirming on my end that polygon does support this symbol

![Screenshot 2023-06-15 at 10 32 40 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/a68a09c9-f6d0-43f4-9ff3-b7b6406b08c9)
