### ISSUE TITLE
[Bug] `stocks/fa/cash --source Polygon --quarter`: Quarterly information not available for statement of cash flows.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5149]
This error is wrong, a lot of financial statement data from Polygon is ignored for some reason.

![Screenshot 2023-06-16 at 9 29 24 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/58d061bb-59a0-478d-be3b-eb79a090bd66)
![Screenshot 2023-06-16 at 9 30 54 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/c802b9b3-c7b9-48c0-8817-992bf1e8e59d)

**Comment by jmaslek** [comment]
So if I look at the request, not every json entry has a cash flow statement:

<img width="835" alt="Screenshot 2023-07-13 at 2 44 31 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/bb79b27a-5ffd-4d31-b819-f8d397872cd5">

I will add in, but stay cautious about issues down the line

**Comment by deeleeramone** [comment]
Another related issue: #5114

**Comment by jmaslek** [comment]
> Another related issue: #5114

oh i got it
