### ISSUE TITLE
[FR] Save API keys to be reused in future docker sessions

### ISSUE THREAD

**Issue by SomwareHR** [OpenBB-finance/OpenBBTerminal#5166]
**What's the problem of not having this feature?**
Docker OpenBB is not saving API keys.

**Describe the solution you would like**
It would be nice to have an option to save API keys for future sessions.

**Describe alternatives you've considered**
Alternative is to define API keys on every docker session.

**Additional information**
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/45540611/f59217ee-ce82-47c8-8e05-f52a1da873f6)

Thanks!
BR

**Comment by deeleeramone** [comment]
Have you tried using the `/account/login` that syncs with [my.openbb.co](https://my.openbb.co)?

**Comment by SomwareHR** [comment]
Yes.
No progress.
Key written to cloud and saved to cloud stays in cloud.
I also choose "**Remember me**" in terminal during `/account/login`.
When I exit, it doesn't remember.

**Comment by deeleeramone** [comment]
@piiq, do you have any insight here?

**Comment by piiq** [comment]
what's the command you use to launch?

it looks like the keys are being saved inside the container that's being deleted after use. probably because the ~/.openbb_terminal folder hasn't been mounted into the container?

**Comment by SomwareHR** [comment]
I tried a few options from here
   https://docs.openbb.co/terminal/installation/docker
I am not Docker savvy, so don't really understand underlying mechanism.

This is Ubuntu 22.04, Docker 24.0.2, latest OpenBB

**Comment by piiq** [comment]
@montezdesousa do you know if docker logs you out and cleans up the local keys automatically?

**Comment by piiq** [comment]
@SomwareHR can you paste the exact command you're using?

**Comment by SomwareHR** [comment]
I've tried with:

1. `docker compose run openbb`

2. `docker compose -f docker-compose.yaml -f docker-compose.x11.yaml run openbb`

3. whole script:

`curl -o docker-compose.yaml https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.yaml
curl -o docker-compose.x11.yaml https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.x11.yaml

docker compose -f docker-compose.yaml -f docker-compose.x11.yaml run openbb`

4. Also with the one stating it's for issues with graphs only:

`docker compose -f docker-compose.yaml -f docker-compose.x11.yaml run -e WEBKIT_DISABLE_COMPOSITING_MODE=1 openbb`


What command are you using?

But I'm giving up slowly, so no need to be worried... I will use Windows installer. Thanks!
