### ISSUE TITLE
[Bug] `stocks/ta/rsp` is not up-to-date anymore

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#5167]
Data was being collected from https://github.com/soggyomelette/rs-log (a repo from our friend @soggyomelette)

But it seems it's not being updated since January.

**Comment by deeleeramone** [comment]
Repo from which it was forked is no longer maintained.

https://github.com/skyte/relative-strength#note-this-is-no-longer-maintained-if-you-need-it-fork-it-or-something

<img width="1074" alt="Screenshot 2023-06-22 at 11 40 17 AM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/08d6363e-b8bf-4766-90a6-3b8af639f9fd">
