### ISSUE TITLE
[Bug] `/stocks/load aapl/ca/tsne` - Error: Input contains NaN. Error: 'list' object has no attribute 'iloc'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5175]
Installer version 3.1.0:

```
/stocks/load aapl/ca/tsne
```

![Screenshot 2023-06-23 at 9 25 17 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/343568ab-522d-452b-bed2-7ef0a6482f86)

**Comment by deeleeramone** [comment]
The error persists still, reopening.

**Comment by jmaslek** [comment]
This should be closer to fixed.  For some reason yf was pulling some nans.  If you look where this is getting data:

https://github.com/jmaslek/daily_sp_500

I added a fillna in case that happens.... better case would be to use a better api

**Comment by Elikutter75** [comment]
Hi, I got the same issue today (but yesterday it was working perfectly)
<img width="958" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/150141621/cce0bad6-7156-4e4f-a5cb-d4ab20f582d3">

**Comment by RylandCapital** [comment]
still happening. nothing works, tried 10 tickers
