### ISSUE TITLE
[Bug] `/reports/economy` - Report .html couldn't be created. `/economy/rtps` - Invalid API call.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5176]
Installer version 3.1.0:

`/reports/economy`

![Screenshot 2023-06-23 at 9 40 37 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/7b51ee68-42db-49e6-a935-ba16594ad8a5)

`Cell [9]` fails because of an "invalid API call" to AlphaVantage.

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/0d7abcf9-1415-4cfd-9b50-11f2cc37ba37)

Also in the Terminal:

```
(🦋) /economy/ $ rtps

Error: Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for SECTOR.

Error: 'list' object has no attribute 'empty'
```

**Comment by jmaslek** [comment]
I dont see that endpoint anymore so may be time to deprecate

**Comment by lorenzeszz** [comment]
Same error with:

/reports/economy 
Report .html couldn't be created.
