### ISSUE TITLE
[Bug] Mac M1 installer link is broken

### ISSUE THREAD

**Issue by minkooseo** [OpenBB-finance/OpenBBTerminal#5184]
**Describe the bug**
In the Mac installation page, https://docs.openbb.co/terminal/installation/macos, clicking Mac M1 installer takes me to https://github.com/OpenBB-finance/OpenBBTerminal/releases/download/v3.1.0/ARM64.MacOS.OpenBB.Terminal.v3.1.0.pkg but it's 404 not found.

**To Reproduce**
See above.

**Screenshots**

**Desktop (please complete the following information):**
NA

**Additional context**
Use chrome (if it's relevant).

**Comment by deeleeramone** [comment]
This has been fixed, thanks!  There were a couple of extra characters in the filename for some reason, but the 404'd link is now working.
