### ISSUE TITLE
[Bug] `stocks/load`  Sources do not agree on what the values for OHLC vs. Adjusted are.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5186]
- The samples below are monthly prices from different sources, none agree with each other on what the price is.
- AlphaVantage is a different date, the end of the month, compared to everyone else.
- Monthly flag for `Intrinio` does not work.
- Random errors in Polygon prices where it gets multiplied by 10. (2005-01-01)

Polygon:
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/61b5feb9-2747-43d7-aa65-3610021b0035)

YahooFinance:
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/7bf76d20-9f2e-4406-8257-75626700bf87)

AlphaVantage:
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/9fd2e896-3da6-435c-a84c-121728a719be)

Intrinio:
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/6f254324-61cc-4c22-8ca2-e0f5a5dd9dca)

**Comment by EternalNooblet** [comment]
I am using EODHD. Their `/eod/` endpoint has raw OHLC, plus an adjusted_close. They have separate `/splits/` and `/div/` endpoints. The candle charts must be using adjusted_close as the close and the raw everything else. One could pull in the splits/divs along with the raw eod when loading from EODHD and pre-calculate adjusted prices.

`/stocks/load aapl -e=2021-06-01 -s=2020-01-01 --source=EODHD/candle`
![5xXAsU8](https://github.com/OpenBB-finance/OpenBBTerminal/assets/67196335/48e49097-df5c-4812-9043-a3ea3d33ccc5)
