### ISSUE TITLE
[Bug]  cannot import name 'FunctionMessage' from 'langchain.schema'

### ISSUE THREAD

**Issue by dshen1** [OpenBB-finance/OpenBBTerminal#5191]
**Describe the bug**

Just installed openbb sdk on a window 11 machine with the instruction listed on website.   
the python version is 3.9.13.   a brand new conda environment obb is created with the yaml on the web. 

when i typed from open_bb_terminal_sdk import openbb 
there is an import error:  cannot import name 'FunctionMessage' from 'langchain.schema'

the whole screenshots is attached. 

would you please review how to fix that?  thank you very much.  

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
![screeb](https://github.com/OpenBB-finance/OpenBBTerminal/assets/5157823/d0677249-b265-41e3-86c0-a014a86fab33)

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]  Window 11 Home
- Python version [e.g. 3.6.8]  3.9.13 

**Additional context**
Add any other information that you think could be useful for us.

**Comment by Earu** [comment]
Having the same issue.

**Comment by deeleeramone** [comment]
Hello,

Until this is patched, you can resolve the issue by downgrading llama-index.

`pip install -U llama-index==0.6.20`

**Comment by dshen1** [comment]
thank you very much. it works.
