### ISSUE TITLE
[Bug] Ploty.js throws error when I try to run server. 

### ISSUE THREAD

**Issue by Jephpico** [OpenBB-finance/OpenBBTerminal#5193]
**Describe the bug**
when I run server one of the scripts (backend.py) seem to be buggy.
if I comment out that plot.js block of the code in the backend .py it works.
the problem now is on heroku or docker the error appears again as I can't comment it out there.

**To Reproduce**
uvicorn main:app after install the OpenBB SDK

**Screenshots**
![Screenshot 2023-07-03 at 13 57 47](https://github.com/OpenBB-finance/OpenBBTerminal/assets/72971211/b73ae143-330f-4f0e-8931-5441eae7aade)

**Desktop (please complete the following information):**

- OS: [MacOs Intel]
- Python version [3.9.13]

**Additional context**

**Comment by tehcoderer** [comment]
as a quick fix run `python -m openbb_terminal.core.plots.backend` this will give an error but download the ploty.js.

This way the file exists so the code block will not run again when running `uvicorn`

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/61340027/34011363-72ad-4a47-b266-1e37fec4760a)
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/61340027/2237b1cd-a63b-4e72-b652-8e44ba0db382)

**Comment by tehcoderer** [comment]
Also another quick fix that could work in docker as well would be to add 

```python
from openbb_terminal.core.plots import backend  # pylint: disable=W0611 # noqa
``

to the top of main.py

**Comment by Jephpico** [comment]
I dunno for some weird reason the python -m openbb_terminal.core.plots.backend  and the from openbb_terminal.core.plots import backend at the top of the main.py doesn't resolve. I get a module not found error .
: Error while finding module specification for 'openbb_terminal.core.plots.backend' (ModuleNotFoundError: No module named 'openbb_terminal').
eventhough I have the openbb_terminal module installed

**Comment by tehcoderer** [comment]
@Jephpico whelp lol that's weird. 

instead of doing `pip install openbb` try with `pip install openbb-nightly` it should have the changes merged yesterday 🤞

**Comment by Jephpico** [comment]
![Screenshot 2023-07-06 at 18 12 17](https://github.com/OpenBB-finance/OpenBBTerminal/assets/72971211/c6d6973d-c7a0-4882-bb8e-e9c2dbe7db45)

I got this error still. from the error trail, it says download_plotly_js() method wasn't awaited. would the fix not be to  await the download_plotly_js()?


I also switched from my Mac to a windows system. got a whole different error.
the error suggests openbb-nightly is not available for installation
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/72971211/d0653680-c00d-4e9a-aa6b-0f6b75895646)

**Comment by tehcoderer** [comment]
@Jephpico  😭 #5203 100% this fixes

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/61340027/ff36c502-13d9-482c-8bbe-fd39e2c6a702)
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/61340027/81489a18-d040-4910-818e-24cf12625142)
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/61340027/72cbd773-f476-459e-80a0-13dd94405585)
