### ISSUE TITLE
[Bug]Oanda module no longer has the fwd ()

### ISSUE THREAD

**Issue by Jephpico** [OpenBB-finance/OpenBBTerminal#5194]
**Describe the bug**
I used a method from the documentation. check the code below.

@router.get("/detailedfxdata")
def detailed_fx_data(
    #to_symbol: str,
    #from_symbol:str,
):

    fwd_usdeur = openbb.forex.fwd('EUR', 'USD')
  
    fwd_jpyeur = openbb.forex.oanda.fwd('JPY', 'EUR')
    fwd_pairs = fwd_jpyeur.join(fwd_usdeur, on = ['Expiration'], lsuffix = ' JPY/EUR', rsuffix=' USD/EUR')

**To Reproduce**
hit the endpoint that uses openbb.forex.oanda.fwd()

**Screenshots**
![Screenshot 2023-07-03 at 15 24 15](https://github.com/OpenBB-finance/OpenBBTerminal/assets/72971211/05942231-0f1b-4002-a045-9e8c9679c882)

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
The `fwd` function doesn't actually come from Oanda, it comes for FX Empire.

![Screenshot 2023-07-03 at 9 37 17 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/db6c8d0e-e1bc-49fe-9810-6e7d058bc6d9)
