### ISSUE TITLE
[Bug] `/crypto/dd/` - `Coinglass` functions no longer work and prints, "deprecated".

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5200]
![Screenshot 2023-07-05 at 1 11 55 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/a9be9693-cb1b-4430-ae46-ca0cf77f11d7)

**Comment by deeleeramone** [comment]
Some of these commands might be salvageable.

```python
r = requests.get("https://open-api.coinglass.com/public/v2/liquidation_history?time_type=all&symbol=all", headers = headers)
```

![Screenshot 2023-07-17 at 1 46 29 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/67e1a2c6-f833-4033-9a99-e89397f9f937)

```python
In [45]: r = requests.get("https://open-api.coinglass.com/public/v2/liquidation_info?time_type=h1&symbol=ETH", headers = headers)

In [46]: r.json()["data"]
Out[46]: 
{'symbol': 'ETH',
 'h1TotalVolUsd': 464612.37267,
 'h1Amount': 245.8527,
 'h4TotalVolUsd': 8344152.10789453,
 'h4Amount': 4415.3626,
 'h12TotalVolUsd': 15948170.88563281,
 'h12Amount': 8439.0787,
 'h24TotalVolUsd': 18370222.46172855,
 'h24Amount': 9720.7231}

In [47]: r = requests.get("https://open-api.coinglass.com/public/v2/liquidation_top?time_type=h4", headers = headers)

In [48]: len(r.json()["data"])
Out[48]: 30

In [49]: r.json()["data"][0].keys()
Out[49]: dict_keys(['number', 'symbol', 'amount', 'longVolUsd', 'shortVolUsd', 'symbolLogo', 'totalVolUsd'])

```

**Comment by Ashhar-24** [comment]
Hey, would love to work on this issue. 
can you please guide me what exactly needs to be done here.
Thanks

**Comment by deeleeramone** [comment]
> Hey, would love to work on this issue. can you please guide me what exactly needs to be done here. Thanks

Basically, `coinglass_model.py` needs to be updated to point to the new endpoints, and maybe adjust for differences in column headers within this file and the associated view, `coinglass_view.py`.   It may turn out that the deprecated function no longer exists as is, in which case the Terminal `controller.py` file for the sub-menu will need to adapted to fit new parameters or names.
