### ISSUE TITLE
[Bug] Extremely long SDK import time

### ISSUE THREAD

**Issue by 99snowleopards** [OpenBB-finance/OpenBBTerminal#5210]
**Describe the bug**
`from openbb_terminal.sdk import openbb` takes minutes to execute when I run it in a Python interpreter in a terminal or run a python script

**To Reproduce**
the above import statement runs in a few seconds in a Jupyter notebook and I'm also able to start the openbb terminal immediately

**Screenshots**
details in these issues:

https://github.com/OpenBB-finance/OpenBBTerminal/issues/4921

https://github.com/OpenBB-finance/OpenBBTerminal/issues/4851

**Desktop (please complete the following information):**

- OS: Windows + WSL2
- Python version 3.9

**Additional context**

the above issues on long SDK import times have been open for a while - I'm unable to use this library right now and would really like to! 

it looks like the long import time is due to enabling interactive visualization - I don't need any visualization - I'm just trying to access some data - is there any way to speed the initial import and bypass some features that take a long time 

greatly appreciate any help on this - thank you!

**Comment by 99snowleopards** [comment]
I see - thanks for that suggestion - I'll use the repo for running any code

I wonder why it takes minutes on my laptop and if anyone else has this problem - could it be related to having installed VcXsrv and Xming ?

thanks again!

**Comment by deeleeramone** [comment]
> could it be related to having installed VcXsrv and Xming on Windows?

That's a great question. If you install to Windows, not using WSL2, does it improve or stay the same?

What is the hardware configuration of the laptop? CPU/memory, etc.

**Comment by 99snowleopards** [comment]
I don't have conda/python installed on Windows - I have 64GB, Intel 13th gen 32 core processor - I don't have this problem of long import time with any other library - also, when I import the library in a jupyter notebook in the same conda env, it executes instantly - it only takes long when I run a script or directly in the python interpreter

**Comment by 99snowleopards** [comment]
I installed the terminal and SDK on WSL without VcXsrv or the alternatives - installing those breaks something in the SDK import - I would add a note of caution to users that the WSL install process has not been tested thoroughly

**Comment by cober-data** [comment]
Had a similar issues took 4 minutes to import

<img width="799" alt="Screenshot 2023-08-31 161221" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/97363152/cf7e5c3a-3e5d-47c0-8485-3c18386b196d">
