### ISSUE TITLE
[Bug] `stocks/ta/ema --export` EMA values are not exported, only "Adj Close" and "date".

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5213]
To recreate,

```
/stocks/ta/ $ ema --length 10,20,30 --export csv
```

![Screenshot 2023-07-11 at 12 57 23 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/4d6a6ea3-9039-4001-99b8-f770a911d02e)

**Comment by deeleeramone** [comment]
Same issue, /forex/ta/ema. Also the filename gets "stocks" inserted into it despite being from the forex path.

![Screenshot 2023-07-14 at 10 55 30 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/6f3fbe70-0b6d-441d-ad31-872d3ba2b50d)

**Comment by deeleeramone** [comment]
Ditto that on everywhere else, stocks/crypto.  The headers are created, but the data is missing.

**Comment by LOne2three** [comment]
Hi is anyone working on this? can I work on it?

**Comment by deeleeramone** [comment]
@tehcoderer is this patched somewhere in another PR?

**Comment by deeleeramone** [comment]
Following up on this, @tehcoderer, if you do: `/stocks/load aapl/ta/ema 50,150 --export csv`

You get an exported file where the 50 day EMA is truncated to begin at row 151 instead of the full column of data beginning at row 51.

<img width="790" alt="Screenshot 2023-08-22 at 12 37 46 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/9bc2e651-0b56-4316-884c-17e3f1c33ea7">
