### ISSUE TITLE
[FR] Update the lib to use pandas 2.0.

### ISSUE THREAD

**Issue by homerokzam** [OpenBB-finance/OpenBBTerminal#5226]
**What's the problem of not having this feature?**
A clear description of what you are lacking, or why you need this additional feature.

**Describe the solution you would like**
A description of what you think would be the best solution for this. From user inputs, to an output.

**Describe alternatives you've considered**
If there are other alternatives (worth considering) to your solution, list them here. 

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by jmaslek** [comment]
this will be the case when we switch to #5225
