### ISSUE TITLE
download_plotly_js() bug

### ISSUE THREAD

**Issue by Jephpico** [OpenBB-finance/OpenBBTerminal#5227]
**Describe the bug**
a download_plotly error get thrown
**To Reproduce**
install pip openbb right now and attempt to call a method like forex.load()

**Screenshots**
![Screenshot 2023-07-18 at 08 26 54](https://github.com/OpenBB-finance/OpenBBTerminal/assets/72971211/7e50ba2d-8539-4544-a8f3-d1c46a7c2a26)

**Desktop (please complete the following information):**

- OS: [e.g. Macos]
- Python version [e.g. 3..9.13]

**Additional context**
this error was earlier fixed. it seems there is a merge that has Brought it back

**Comment by colin99d** [comment]
This is fixed per @tehcoderer
