### ISSUE TITLE
[Bug] Most API-tests are inconclusive or fail

### ISSUE THREAD

**Issue by LinusKaiser** [OpenBB-finance/OpenBBTerminal#5230]
I haven't logged on to OpenBB terminal for some weeks. Just downloaded the new version (3.1.0) and updated from 3.0.0.
Seems that most api-key tests are inconclusive. I don't know whether it is related to the 3.1.0 version as I didn't start 3.0.0 before updating. I have checked that the API-keys are correct and reentered the ones that say "inconclusive", but that didn't help. I'm using a M1 Mac.

Any ideas what could cause this?

![Screenshot 2023-07-18 at 22 14 51](https://github.com/OpenBB-finance/OpenBBTerminal/assets/25369346/0e5f74d1-7e05-4053-99a0-7a9d73f65dd0)

**Comment by deeleeramone** [comment]
hmm..I cannot seem to reproduce at this time.  Are you connected to the internet through a VPN or workplace environment? If you ignore what the tests are saying, do the functions work?

**Comment by LinusKaiser** [comment]
I think I figured it out. I changed some things in my DNS settings some weeks ago. By using a VPN and by that going around my DNS setting modifications all API-connections can be tested successfully.
