### ISSUE TITLE
Can't Deploy Streamlit Apps because files are being created and modified: PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by FedericoBohl** [OpenBB-finance/OpenBBTerminal#5242]
Hi, I am developing a streamlit app that is using openbb. I created an environment ready for openbb like it is [on the openbb installation web page](https://my.openbb.co/app/sdk/installation) and after running **pip install "openbb[all]" --no-cache-dir** seems to be well installed. Anyway, when I recall "openbb" in the terminal or I execute "from openbb_terminal.sdk import openbb" I recieve the following error:

ImportError: cannot import name 'FunctionMessage' from 'langchain.schema' (C:\Users\...\anaconda3\envs\nicefinance\lib\site-packages\langchain\schema.py)

I study economics and I am not very into this programing world. Do someone knows what is the error about and how to fix it?

**Comment by jmaslek** [comment]
We were having some issues with the dependenceis in the previous dependency tree.

We just pushed out 3.2, so can you run that pip command with -U and let us know if that issue is fixed?

**Comment by FedericoBohl** [comment]
I worked well, Anyway these version is not compatible with the requierements of tensorflow (protobuf versions not compatible). Do you have an indication of when older versions of openbb will be ready? So I can use them with tensorflow. Thanks

**Comment by jmaslek** [comment]
So in a couple months we should be at a place where dependencies should be minimal in the core library.

I was able to get tensorflow installed into the environment, with tensorflow==2.9.1.
<img width="637" alt="Screenshot 2023-07-24 at 4 27 26 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/dd9283b1-21de-4599-9e58-c088d4dd620a">

Not sure if that is enough of a building black, but happy to try debugging with you

**Comment by FedericoBohl** [comment]
Hi, so I tried with that tensorflow but still failing. When I run locally the streamlit app (I am using anaconda and PyCharm if it helps in something) but when I deploy the app I have the following output:
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/79208848/2d41b585-fac7-486e-be12-e2d885375d55)
Also, my library requirements for the app are mostly openbb, keras, tensorflow

**Comment by jmaslek** [comment]
Can you provide a minimal working example of your app so that we can dig in further?

Also are you on Mac/windows/Linux?

**Comment by FedericoBohl** [comment]
I am in Windows. 
The app works as following: I give the values to be set in the openbb.stocks.load(...) and then with that data I create financial indicators with openbb.ta... ,then with those indicators I run a LSTM model whose parameters are set in the app.

Also, recently I tried to create a new conda environment with python 3.10 where I only installed **pip install -U "openbb[all]" --no-cache-dir** I get the output of the image. Honestly, I don't know if the error is from the libraries, or it is something wrong in my computer.

**Comment by deeleeramone** [comment]
That's odd, are you using WSL?  libwebkit is a Linux component and Windows does not rely on it, so it looks like you are using some kind of VM or emulation that is not Windows.

**Comment by FedericoBohl** [comment]
@deeleeramone I don't quite understand what you mean with all that. In my conda enviorment the app works well but one I deploy it to streamlit app it fails.

**Comment by jmaslek** [comment]
@tehcoderer has provided me some guidance.

Try setting the environment variable: `OPENBB_PLOT_ENABLE_PYWRY = false`

**Comment by FedericoBohl** [comment]
Where should I put that? In the requirements?

**Comment by jmaslek** [comment]
quckest way : you can just put it in your script
```
import os
os.environ["OPENBB_PLOT_ENABLE_PYWRY"] = "false"
```

**Comment by FedericoBohl** [comment]
It did not work. The way I add that you mention is in the main file after importing the other libraries

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/79208848/dbea44fe-1839-4ece-8ec2-4807fcf9b16a)

**Comment by jmaslek** [comment]
Hmmm.

If you add that before when you import openbb, then does that change it?  It reads the env var on import so changing afterwards.

The other thing to do would be to just add it as a secret for you streamlit app.  Their instructions are here: https://docs.streamlit.io/streamlit-community-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management

**Comment by deeleeramone** [comment]
I see what's happening.. when the SDK initializes, there is a warning that requires a user intervention - press enter or keyboard interrupt - before the process finishes. In Google CoLabs you would simply be able to hit `enter` but because there is no access to the Streamlit command line, it is not possible to do and you get stuck in the await state.  Solution would be to remove the user intervention on initialize and automatically update the environment variables for the correct state.

**Comment by FedericoBohl** [comment]
That makes lots of sense, but, How can I do that?

**Comment by deeleeramone** [comment]
@tehcoderer, what's the best way to go about this?

**Comment by FedericoBohl** [comment]
I see you did some changes. Do I have to do something in particular or use a specific version of openbb, or I just have to deploy it as normal?

**Comment by deeleeramone** [comment]
> I see you did some changes. Do I have to do something in particular or use a specific version of openbb, or I just have to deploy it as normal?

It was an attempt, and it removed the keyboard intervention required, but it ended up exposing a new error message (Permission Error) that we need to now figure out a way around. 

```
Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/openbbterminal/openbb_terminal/dashboards/stream/pages/Indicators.py", line 16, in <module>

    from openbb_terminal.dashboards.stream import (

  File "/home/adminuser/venv/lib/python3.9/site-packages/openbb_terminal/dashboards/stream/common_vars.py", line 8, in <module>

    from openbb_terminal.sdk import openbb  # noqa: E402

  File "/home/adminuser/venv/lib/python3.9/site-packages/openbb_terminal/sdk.py", line 61, in <module>

    cfg.setup_config_terminal(is_sdk=True)

  File "/home/adminuser/venv/lib/python3.9/site-packages/openbb_terminal/config_terminal.py", line 142, in setup_config_terminal

    init_userdata()

  File "/home/adminuser/venv/lib/python3.9/site-packages/openbb_terminal/core/config/paths_helper.py", line 78, in init_userdata

    create_files(dirs_files)

  File "/home/adminuser/venv/lib/python3.9/site-packages/openbb_terminal/core/config/paths_helper.py", line 33, in create_files

    with open(str(filename), "w"):

PermissionError: [Errno 13] Permission denied: '/home/adminuser/venv/lib/python3.9/site-packages/.env'
```

and also:

```
Error downloading plotly.js: [Errno 13] Permission denied: '/home/adminuser/venv/lib/python3.9/site-packages/openbb_terminal/core/plots/assets/plotly-2.24.2.min.js'
```

At this point, I think the Issue title can change to reflect the current status.
