### ISSUE TITLE
[Bug] `/economy/gdp`: Wrong scale units. US GDP is displayed in millions when should be Trillions.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5248]
![Screenshot 2023-07-24 095757](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/60c746d1-345d-45fd-b1f8-cf09aff8ca03)

**Comment by jmaslek** [comment]
technically 20M Millions of us dollars is 20T :P

**Comment by deeleeramone** [comment]
`/economy/macro GDP` is more better. Not even sure why we need two commands for the same data points. EconDB even gives you quarterly values.

![Screenshot 2023-07-25 at 1 14 43 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/d9f9adfb-7d66-48d6-b310-11b0999cabc3)
