### ISSUE TITLE
[Bug] 3.2 Windows Installer: Chart legends do not display correctly.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5249]
Appears to be a Windows-only issue.

![Screenshot 2023-07-24 090728](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/483cd6aa-f563-4776-bab7-0d465f321809)

![Screenshot 2023-07-24 100629](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/7b4a6489-a8b7-4689-a91e-893bbbac4479)

Mac version appears normally:

![Screenshot 2023-07-24 at 10 07 35 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/396b347a-e2b1-4ba2-a3e3-7bffa6996bcf)

**Comment by andrewkenreich** [comment]
this behavior changed from windows 8 to windows 10 - not much we can do about it right now without some hacky stuff.

https://www.tenforums.com/customization/11795-title-bar-not-centered.html

**Comment by andrewkenreich** [comment]
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/23067478/3c3aa51b-13b7-4563-8c31-fe67e86a523c)

I can't recreate this - do you have any different charting settings?

**Comment by deeleeramone** [comment]
No settings changes, this screenshot is from the develop branch.

![Screenshot 2023-08-07 102020](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/f1800044-3cc6-47b7-ab96-6fafac80a191)
