### ISSUE TITLE
[Bug] `openbb.stocks.gov.topbuys()` & `openbb.stocks.gov.topsells()` give same output

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5258]
![Screenshot 2023-07-27 at 8 41 20 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/892043e5-a4c1-4f50-b634-6a17fdd03e02)

![Screenshot 2023-07-27 at 8 44 33 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/8e5c09e0-f049-4eb4-885f-7c10b0201538)

**Comment by deeleeramone** [comment]
Digging in to this a bit, and it appears there is something up with the `quiverquant_model` functions because they all return empty:

```
In [29]: from openbb_terminal.stocks.government import quiverquant_model as qm

In [30]: qm.get_government_trading("congress")
Out[30]: 
Empty DataFrame
Columns: []
Index: []

In [31]: qm.get_government_trading("senate")
Out[31]: 
Empty DataFrame
Columns: []
Index: []

In [32]: qm.get_government_trading("house")
Out[32]: 
Empty DataFrame
Columns: []
Index: []

**Comment by jmaslek** [comment]
getting 500 status code :(

**Comment by deeleeramone** [comment]
> getting 500 status code :(

was just going to update my comment to include that.

```
In [48]: r = requests.get("https://api.quiverquant.com/beta/historical/congresstrading/AAPL", headers=headers)

In [49]: r.status_code
Out[49]: 500

In [50]: r.content
Out[50]: b'"unsupported operand type(s) for -: \'NoneType\' and \'int\'"'
```

**Comment by deeleeramone** [comment]
BUT, you can still read the tables:

![Screenshot 2023-07-28 at 11 58 23 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/462d391b-042c-4ee3-af18-697002606bf7)

**Comment by deeleeramone** [comment]
> getting 500 status code :(

Related to the API call getting routed to `/beta/`?

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/740125b5-86a3-4868-a8d6-247fa6149f5a)

**Comment by jmaslek** [comment]
not related to beta
<img width="1113" alt="Screenshot 2023-08-07 at 11 25 33 AM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/480dd9f7-d75f-447a-b065-d7af659e1bdb">

**Comment by jmaslek** [comment]
will be fixed in release
