### ISSUE TITLE
[Bug] [SDK]`openbb.stocks.fa.score` - returned data does not resemble FMP end point.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5260]
Docstring says: "Gets value score from FMP".

What's returned vs. what FMP returns directly. As a user, I'm expecting to get what FMP delivers.

![Screenshot 2023-07-28 at 11 06 46 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/45b54531-56df-4371-b427-b1c40cc80315)

There are no explanations for what is returned by `openbb.stocks.fa.score`, and scratching the surface a little bit, "beta score" returns a literal, 1 or 0, with no explanation offered.  AAPL definitely does not have a beta of 0.

![Screenshot 2023-07-28 at 10 52 17 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/6982b378-e737-4b52-9422-68ed65c2dff7)

The Terminal description says:

"Value investing tool based on Warren Buffett, Joseph Piotroski and Benjamin Graham thoughts [Source: FMP]"

which does not contain any helpful information.

**Comment by jmaslek** [comment]
Note this is not fmp/score endpoint, but rather a 3rd party calculation: https://github.com/astro30/valinvest
