### ISSUE TITLE
[Bug] `/forecast` - any forecast with `--days` > 5: Error: mixed datetimes and integers in passed array

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5264]
When the number of days to get a forecast for is greater than 5, the time series chart fails.  The table of price predictions displays, so the forecast has been done, it is the chart that fails.  It happens with all models.

To recreate:

Fails:

```
/stocks/load XLE/forecast/rwd -d XLE -n 6
```

Works:

```
/stocks/load XLE/forecast/rwd -d XLE -n 4
```

![Screenshot 2023-07-29 at 11 38 36 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/68329e97-135f-4421-8825-7e80a80fbe37)

**Comment by jmaslek** [comment]
@tehcoderer 

This is not forecast related, but plotly related:

```  
File "/Users/james/OpenBBTerminal/OpenBBTerminal/openbb_terminal/core/plots/plotly_helper.py", line 1376, in add_rangebreaks
    pd.to_datetime(np.concatenate(values))
```
