### ISSUE TITLE
[Bug] `stocks/ca/hcorr`: Error: '<=' not supported between instances of 'Timestamp' and 'str'

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5272]
Function does not appear to work. 

```
(🦋) /stocks/ca/ $ add msft,appl

[Custom] Similar Companies: MSFT, APPL 


(🦋) /stocks/ca/ $ hcorr

NaN values found in: APPL.  Backfilling data
Error: '<=' not supported between instances of 'Timestamp' and 'str'

Error: 'list' object has no attribute 'corr'

Error: not enough values to unpack (expected 2, got 0)
```

**Comment by jmaslek** [comment]
think i figured this out in 3.2.1:  unclear of why aapl in your case and amzn in my case have NaN values, but likely something about yf....

![Screenshot 2023-08-07 at 10 48 19 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/d970f036-f4fa-47e6-8260-c68a74e1b64c)
