### ISSUE TITLE
[Bug] Prompt request prevents installing openbb SDK for CI

### ISSUE THREAD

**Issue by AzulGarza** [OpenBB-finance/OpenBBTerminal#5288]
**Describe the bug**

I'm trying to use `openbb` SDK as a dependency in our library and use it inside our continuous integration. But during CI, importing `openbb` requests a prompt that prevents the CI to conclude:

<img width="1017" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/10517170/302126a9-c86c-4e1b-84f1-d0d873e3f659">

The workaround right now is capturing the stdin of `openbb` using the following:

```python
import sys
import io

backup = sys.stdin
sys.stdin = io.StringIO('Default input') 

from openbb_terminal.sdk import openbb

sys.stdin = backup
```

**To Reproduce**
[Here's the link to the CI error.](https://github.com/Nixtla/nixtla/actions/runs/5781396926/job/15666431618?pr=64)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Python version 3.9,3.10

**Comment by jmaslek** [comment]
Any chance that if you run with the env var: OPENBB_PLOT_ENABLE_PYWRY set to false that it runs?
