### ISSUE TITLE
[Bug] YahooFinance price intraday column shows date/timestamp

### ISSUE THREAD

**Issue by jinkeatlim** [OpenBB-finance/OpenBBTerminal#5298]
**Describe the bug**
 shows date in Price Intraday column for certain stocks. This also occurs on other functions i.e. gainers 

**To Reproduce**
/stocks/disc/active
/stocks/disc/gainers

**Screenshots**
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/7218537/fe28ac66-e27b-4bbe-8fdc-1f28c0df31b5)

**Comment by jmaslek** [comment]
Can you confirm what version you are on?

**Comment by jinkeatlim** [comment]
v3.2.0 OpenBB Terminal

**Comment by jmaslek** [comment]
not able to recreate on 3.2

<img width="1511" alt="Screenshot 2023-08-09 at 12 41 45 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/bea93274-8399-43fb-9fb4-745bd431e606">

@deeleeramone can you?

**Comment by jinkeatlim** [comment]
FYI I am seeing below, reran as of today 8/9 to match above ss: 
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/7218537/8e02c473-d3c0-4ec7-a90a-91cdcabd5385)

**Comment by deeleeramone** [comment]
> @deeleeramone can you?
![Screenshot 2023-08-09 at 1 59 15 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/edcc621c-fe18-4f2c-8b41-6702652ee7a4)

I cannot, on either Windows and Mac.

**Comment by jinkeatlim** [comment]
Additional info: I just tried exporting results with 1970 date to csv, and opening the export in Excel shows the correct values. However, the new OpenBB window that opens when running /stocks/active/gainers still shows the 1970 dates. The screenshots I posted above are based on the OpenBB window.

**Comment by deeleeramone** [comment]
OK...I'm now recreating this. Seems to be the installer, specifically, @jmaslek, just did a fresh 3.2 Windows install from the EXE:

![Screenshot 2023-08-09 154209](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/21fb7145-6b81-419a-a71e-89ccf47a1bfb)

**Comment by jmaslek** [comment]
So maybe this somehow got fixed between then and #5289

**Comment by jmaslek** [comment]
Can we confirm if this is no longer an issue?

**Comment by deeleeramone** [comment]
> Can we confirm if this is no longer an issue?

Seems OK over here.

3.2.1 Mac ARM:

<img width="1569" alt="Screenshot 2023-08-16 at 11 34 45 AM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/ed832ca2-b36e-49e2-867e-eac3ec8e2c59">

3.2.1 Windows:

![Screenshot 2023-08-16 113710](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/dedbc867-c3d9-445f-ab80-82501f4a6da9)

**Comment by colin99d** [comment]
It looks like this issue is resolved, I will close it.
