### ISSUE TITLE
[Bug] CPI Series ID curation is not mapped correctly, Y/Y and M/M are backwards for some countries.

### ISSUE THREAD

**Issue by fredcmilhome** [OpenBB-finance/OpenBBTerminal#5315]
**Describe the bug**
Command CPI pulls the data from FRED in the wrong units for some countries.

**To Reproduce**
Running this command to pull CPI in Year-over-Year units (growth_same) 
cpi -c united_states,united_kingdom,brazil,china,germany --start 2018-01-01 --frequency monthly **--units growth_same**

Outputs:

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/65572709/4a0b66b0-daba-4cc7-b740-7d08681c8cfa)

But the graph shows the data for Germany and China in Month-over-Month units (which should come out if the units parameter were growth_previous), as it matches the following data from FRED:

CPALTT01CNM657N:
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/65572709/fd4f95f8-978c-4aee-b281-7c29bd32fac0)

CPALTT01DEM657N
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/65572709/c7f9cc1a-3987-4506-b776-8ea53610e9cf)

I'm running OpenBB version 3.0.1, and no error messages are shown. The units are wrong for units growth_previous as well, and I haven't checked other countries.

**Comment by jmaslek** [comment]
this is a very nice catch.  dug into it more and found this is the case for china, denmark, estonia, germany, japan and czech republic

![Screenshot 2023-08-17 at 2 54 48 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/1bb17013-4802-4dcc-97ad-b818d6196de7)
