### ISSUE TITLE
[FR] Add ISIN Numbers

### ISSUE THREAD

**Issue by Jleventhal1** [OpenBB-finance/OpenBBTerminal#5328]
**What's the problem of not having this feature?**
in using the openbb sdk to build out an application, I have ran into an issue where my program cannot distinguish between different securities listed on different exchanges that happen to have the same ticker. for example, TXG is the ticker for 10x Genomics in the US, but in Canada TXG is the ticker for Torex Gold Resources.

**Describe the solution you would like**
The solution would be to add the ISIN number to each ticker, as this is a 12 -digit number that uniquely identifies a specific security, even if they have the same ticker. my program can then use this to uniquely identify the desired securities.

**Describe alternatives you've considered**
an alternative may be to add the generally used country codes to general security data as a way to differentiate between multiple different securities with the same ticker. however this is not as ideal as ISIN numbers, which are more widely known and are more standardized.

**Additional information**
n/a

**Comment by deeleeramone** [comment]
Most data vendors have symbol suffixes that denote exchanges outside of the major US ones.  TXG.TO is an easy way to differentiate.  You can currently load a ticker by ISIN from YahooFinance or Intrinio.
