### ISSUE TITLE
[Bug] Different outputs depending on the OS

### ISSUE THREAD

**Issue by AzulGarza** [OpenBB-finance/OpenBBTerminal#5337]
**Describe the bug**

The function `openbb.stocks.fa.income` returns different outputs depending on the OS:

Ubuntu:

<img width="1071" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/10517170/bbbf4e96-6696-44ef-8fe5-2ce911bdc835">

Mac:

<img width="1103" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/10517170/48b51dc1-4ec4-455c-9792-8a472e176ecd">

**To Reproduce**

```python
revenue_pltr = openbb.stocks.fa.income('PLTR', quarterly=True, source='AlphaVantage').loc['totalRevenue'].reset_index()
```

**Desktop (please complete the following information):**

- OS: Mac Monterrey, Ubuntu Ubuntu 22.04.2 LTS.
- Python version 3.10

**Comment by colin99d** [comment]
What is the version for each of these?

**Comment by deeleeramone** [comment]
Pretty sure this is because the long number formatting is happening at the model stage instead of on display like elsewhere.

![Screenshot 2023-08-18 at 9 06 35 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/35f243c2-4e26-412b-837e-6a130de50360)
