### ISSUE TITLE
[Bug] Oanda API

### ISSUE THREAD

**Issue by juanex321** [OpenBB-finance/OpenBBTerminal#5342]
**Describe the bug**
I got the keys defined, test failed message. I have tried the keys (account, secret, and account type) in a different platform (Zorro) and have gotten successful connection so it seems like it might be an OpenBB problem, I would probably guess that it could be something to do with the account type as the other platform its not able to connect with a demo (practice) account 

**Screenshots**
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/72845500/dee4ef87-de11-4f6f-94f7-fd028aac084f)

- OS: Windows 
- Python version 3.8.17
- Open BB Terminal v3.2.1

**Comment by juanex321** [comment]
I believe it is a US account, is that one not supposed to work?

**Comment by piiq** [comment]
practice or live? i'm using a practice account

**Comment by juanex321** [comment]
I've tried either account (with their respective numbers)
