### ISSUE TITLE
[IMPROVE] Remove `update` command from main menu.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5343]
This command doesn't really work and is just a big tease.  All it does is make people think that is how you update the version of Terminal.

**Comment by colin99d** [comment]
@jmaslek do we know what percent of our users build themselves versus what percent use the installer. If the amount building themselves is high, we should probably dynamically show this, if not, we should just hide it.

Note: we also could technically make it work on installer... right?
