### ISSUE TITLE
[Bug] Screener preset names are being truncated by the Terminal/SDK. `not_oversold` is read as `ot_oversold` 

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5361]
Not all filenames are truncated, and appears to be specific characters at the start/end of the name.  They do work with the wrong key values, but very strange that it would alter this arbitrarily.

It reads `not_oversold` as `ot_oversold`, and, `above50_rsi` as `above50_rs`.  Does not happen to every preset.

<img width="1220" alt="Screenshot 2023-08-21 at 4 08 56 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/d5798dc8-9101-4627-afdf-12df99254596">

<img width="1159" alt="Screenshot 2023-08-21 at 4 10 36 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/cfc24659-131c-4f5a-80c1-6049ab9fe830">

<img width="1401" alt="Screenshot 2023-08-21 at 4 14 20 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/ba8f998d-396d-46e9-b9cc-44b8436535b9">

**Comment by kshitiz305** [comment]
Hi I would like to contribute to the and solve this bug

**Comment by jmaslek** [comment]
Are those custom ones?  Doesnt say they exist on my end....

Anyways the issue is we are using .strip(".ini") so any i or n will be stripped.  Fix coming up
