### ISSUE TITLE
pip installation fails

### ISSUE THREAD

**Issue by QMeqGR** [OpenBB-finance/OpenBBTerminal#5377]
On linux Fedora 38. Following the instructions on the openBB website for pip installation fails.

However, I was surprised to see what openBB needs for installation - it appeared to attempt installation of multiple versions of many packages. I won't be trying to install it again after this, but just mention it so you know it doesn't install cleanly with pip on Fedora 38.

**Comment by deeleeramone** [comment]
Without any information provided, like the specific error, or surrounding context like machine configuration and the steps done to prepare the machine for installation, this can only be assumed to be user error.
