### ISSUE TITLE
typo in the 3.2.2 release artifact

### ISSUE THREAD

**Issue by chenrui333** [OpenBB-finance/OpenBBTerminal#5405]
👋 looks like the x86 arch got specified wrong for 3.2.2 release, instead of being x86.64, it is x86.84. Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-cask/pull/154316

**Comment by jmaslek** [comment]
Thank you!  Just patched the file name

**Comment by nimeshneema** [comment]
It appears that the issue still persists.

The download URL is incorrectly generated with `x86.84`.
