### ISSUE TITLE
[Bug] Candle chart fails to zoom if chart has more than 2000 points

### ISSUE THREAD

**Issue by adrianmck1** [OpenBB-finance/OpenBBTerminal#5413]
**Describe the bug**
I have downloaded more than 2000 data points and request a candle chart. The chart displays with a warning about there being more than 2000 data points. I then try to zoom in on the left-hand side of the chart and something goes wrong, as no data is displayed, the chart scale is wrong, the chart background changes from black to white and it's not possible to zoom back out.
The issue does not seem to occur if there are less than 2000 data points.

Related to this, if I zoom in on a different part of the chart, and then try to zoom back out using the "auto-scale" or "home" buttons, it doesn't zoom out. It seems like the original data has been dropped and it can only render what remains. However if I zoom out using the mouse wheel, it does seem to display more of the original data.

**To Reproduce**
1. Type: stocks
2. Type: load -t ADI -s 2010-01-01
3. Type: candle
4. Click the "zoom" magnifying glass button and select data at the left of the chart. Alternatively click the "+" button and the same issue occurs.
5. The chart background should change to white, the scale should be incorrect and no data should be displayed

**Screenshots**

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/122870179/ea13d9fb-f800-4f00-b6ed-14b1b6a5f20b)

**Desktop (please complete the following information):**

- OS: Windows 10
- Python version: I am using OpenBBTerminal.exe, so I'm not sure if the version of Python on the system matters?

**Additional context**
N/A

**Comment by deeleeramone** [comment]
What is the version of OpenBBTerminal installed?  If it is not 3.2.2, please install the latest version.


With Windows 11, all items appear to work as expected:

![Screenshot 2023-09-15 153904](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/3968fcb8-1967-4727-a0ec-3fcd791a7507)

**Comment by adrianmck1** [comment]
Hi,Yes, I am using v3.2.2 on Windows 10. Thanks. On 15 Sep 2023, at 23:41, Danglewood ***@***.***> wrote:﻿
What is the version of OpenBBTerminal installed?  If it is not 3.2.2, please install the latest version.
With Windows 11, all items appear to work as expected:

**Comment by adrianmck1** [comment]
I have installed the SDK (v3.2.2) and have confirmed the issue also occurs through it when I go over the 2000 points threshold.
