### ISSUE TITLE
Inclusion of timeframes in seconds will be benificial for micro scalping

### ISSUE THREAD

**Issue by Akshat111111** [OpenBB-finance/OpenBBTerminal#5418]
**What's the problem of not having this feature?**
A clear description of what you are lacking, or why you need this additional feature.

**Describe the solution you would like**
A description of what you think would be the best solution for this. From user inputs, to an output.

**Describe alternatives you've considered**
If there are other alternatives (worth considering) to your solution, list them here. 

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by deeleeramone** [comment]
Which data source are you proposing to have this level of granularity?

**Comment by Akshat111111** [comment]
> Which data source are you proposing to have this level of granularity?

Refer stock exchange website

**Comment by deeleeramone** [comment]
> > Which data source are you proposing to have this level of granularity?
> 
> Refer stock exchange website

Which data source are you referring to? "stock exchange website" is not a `--source`.

**Comment by Akshat111111** [comment]
datatrade.ai I was using

**Comment by deeleeramone** [comment]
> datatrade.ai I was using

This is an online marketplace for data, and not a specific source.
