### ISSUE TITLE
Same feature set across all instrument types [FR]

### ISSUE THREAD

**Issue by szivkovicx** [OpenBB-finance/OpenBBTerminal#5422]
**What's the problem of not having this feature?**
Currently only stocks have some feature sets like backtesting strategy, summary from TradingView in TA feature set, behavioural analysis etc... This terminal is already great and has helped me tremendously but it would be that much greater with same feature set across all instrument types and not just stocks.

**Describe the solution you would like**
I would like for all instrument types ( FOREX, CRYPTO and ETFs ) to have same feature set as stocks have. I would like to see the following feature sets in all instrument types:
 - `th`
 - `ta` ( all options from stock ta feature set )
 -  `screener`
 -  `ca`
 -  `qa` ( all options from stock qa feature set )
 -  `ba`
 -  `ins`
 -  `backtesting`
 -  `news`

So essentially I understand that high quality data is a problem to find but I think that all these features can be implemented and configured to work for other instrument types. Again, having these features implemented and configured for other instrument types would be that much more helpful to getting general information.

**Describe alternatives you've considered**
I tend to rely mostly on this terminal for data and generating my predictions for the market since this terminal in a sense is an aggregator of data sources, machine learning algorithms etc... So since this acts as an aggregator ( and it already does a pretty good job! ) it kind of breaks it's structure by me going to TradingView to look for other information when it's totally implementable into the terminal itself.

**Additional information**
I'm an software engineer that's proficient in various programming concepts and languages including Python which is pretty relevant in this repo. I will be glad to contribute to implement this feature and all others!

**Comment by deeleeramone** [comment]
Hello!

I would tend to agree that the TA/QA menus should not have such wide differences where reasonable, but other items are just not possible because that's not how they work.  The stocks screener and insider trading menus are explicitly for stocks.

You can actually load almost anything you want from the `/stocks/load` function, which probably gets you 90% of the way there:

https://github.com/OpenBB-finance/OpenBBTerminal/blob/develop/examples/loadHistoricalPriceData.ipynb
