### ISSUE TITLE
[Bug] Can´t see the stock info (in_drain_helper)

### ISSUE THREAD

**Issue by Leganybit** [OpenBB-finance/OpenBBTerminal#5426]
Can´t see the info from stocks or even candle it. This is my error:
Actually, i can´t even login in to my account with the terminal

example:
2023 Sep 10, 17:05 (🐛) /stocks/ $ quote -t MSFT

The error:
2023 Sep 10, 17:06 (🐛) /stocks/ $ Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/site-packages/pywry/core.py", line 353, in run_backend
    await self.runner.stdin.drain()
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lostus menu    [e] exit terminal    [cmd -h] see usage and available options    [about (cmd/menu)] Stocks (cmd/menu) Documentation                                                                                           

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/site-packages/pywry/core.py", line 388, in run
    asyncio.run(self.run_backend())
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/site-packages/pywry/core.py", line 362, in run_backend
    await self.run_backend()
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/site-packages/pywry/core.py", line 343, in run_backend
    await self.runner.stdin.drain()
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/home/legany/anaconda3/envs/obb/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

im using an arch (Manjaro)
Python 3.11.3

**Comment by deeleeramone** [comment]
Python 3.11 is not compatible.

**Comment by Leganybit** [comment]
> Python 3.11 is not compatible.
> 
> The traceback error indicates the environment was built for 3.9. With your environment active, what is the output of `conda info`?

     active environment : None
            shell level : 0
       user config file : /home/legany/.condarc
 populated config files : /home/legany/.condarc
          conda version : 22.11.1
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.38=0
                          __linux=6.1.44=0
                          __unix=0=0
       base environment : /home/legany/anaconda3  (writable)
      conda av data dir : /home/legany/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/legany/anaconda3/pkgs
                          /home/legany/.conda/pkgs
       envs directories : /home/legany/anaconda3/envs
                          /home/legany/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.31.0 CPython/3.9.13 Linux/6.1.44-1-MANJARO manjaro/23.0.0 glibc/2.38
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by deeleeramone** [comment]
> With your environment active, what is the output of conda info?

> active environment : None
> conda version : 22.11.1

*with* your environment active. 

However, it looks like your version of Conda is behind, and this can create issues with PIP and recipes because they are looking in the past.

`conda update -n base -c conda-forge conda`

Upate your base environment, clear your cache, and try building a *new* environment from the updated base.

**Comment by Leganybit** [comment]
> > With your environment active, what is the output of conda info?
> 
> > active environment : None
> > conda version : 22.11.1
> 
> _with_ your environment active.
> 
> However, it looks like your version of Conda is behind, and this can create issues with PIP and recipes because they are looking in the past.
> 
> `conda update -n base -c conda-forge conda`
> 
> Upate your base environment, clear your cache, and try building a _new_ environment from the updated base.

     active environment : obb
    active env location : /home/legany/anaconda3/envs/obb
            shell level : 2
       user config file : /home/legany/.condarc
 populated config files : /home/legany/.condarc
          conda version : 22.11.1
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.38=0
                          __linux=6.1.44=0
                          __unix=0=0
       base environment : /home/legany/anaconda3  (writable)
      conda av data dir : /home/legany/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/legany/anaconda3/pkgs
                          /home/legany/.conda/pkgs
       envs directories : /home/legany/anaconda3/envs
                          /home/legany/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.31.0 CPython/3.9.13 Linux/6.1.44-1-MANJARO manjaro/23.0.0 glibc/2.38
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

"Upate your base environment, clear your cache, and try building a new environment from the updated base."
actually, i do that before, and still doesn`t work. maybe the problem is with python 3.11, i need to use python 3.9. i will try this
