### ISSUE TITLE
get_straddle() and other functions are not working

### ISSUE THREAD

**Issue by daniellopez-2** [OpenBB-finance/OpenBBTerminal#5431]
**Describe the bug**
ValueError: Expression (((strike) == (__pd_eval_local_call_strike_estimate)) & ((dte) == (__pd_eval_local_dte_estimate))) & (Series_1_0x200x390xe40x710x10x00x00x0) has forbidden control characters.

**To Reproduce**
openbb.stocks.options.load_options_chains('SPY').get_straddle()

- OS: Mac Sierra
- Python version 3.10

**Additional context**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[17], line 1
----> 1 chains.get_straddle()

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/openbb_terminal/stocks/options/options_sdk_helper.py:480, in OptionsChains.get_straddle(self, days, strike)
    457 def get_straddle(self, days=0, strike=0):
    458     """Calculates the cost of a straddle and its payoff profile. Use a negative strike price for short options.
    459 
    460     Parameters
   (...)
    477     >>> data.get_straddle()
    478     """
--> 480     return options_chains_model.calculate_straddle(self, days, strike)

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/openbb_terminal/stocks/options/options_chains_model.py:612, in calculate_straddle(options, days, strike)
    605 call_strike_estimate = get_nearest_call_strike(
    606     options, dte_estimate, strike_price
    607 )  # noqa:F841
    608 put_strike_estimate = get_nearest_put_strike(
    609     options, dte_estimate, strike_price
    610 )  # noqa:F841
--> 612 call_premium = options.chains.query(
    613     "`strike` == @call_strike_estimate and `dte` == @dte_estimate and `optionType` == 'call'"
    614 )[bidAsk].values
    616 put_premium = options.chains.query(
    617     "`strike` == @put_strike_estimate and `dte` == @dte_estimate and `optionType` == 'put'"
    618 )[bidAsk].values
    620 straddle_cost = call_premium + put_premium

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/pandas/util/_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/pandas/core/frame.py:4474, in DataFrame.query(self, expr, inplace, **kwargs)
   4472 kwargs["level"] = kwargs.pop("level", 0) + 2
   4473 kwargs["target"] = None
-> 4474 res = self.eval(expr, **kwargs)
   4476 try:
   4477     result = self.loc[res]

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/pandas/util/_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/pandas/core/frame.py:4612, in DataFrame.eval(self, expr, inplace, **kwargs)
   4609     kwargs["target"] = self
   4610 kwargs["resolvers"] = tuple(kwargs.get("resolvers", ())) + resolvers
-> 4612 return _eval(expr, inplace=inplace, **kwargs)

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/pandas/core/computation/eval.py:358, in eval(expr, parser, engine, truediv, local_dict, global_dict, resolvers, level, target, inplace)
    356 eng = ENGINES[engine]
    357 eng_inst = eng(parsed_expr)
--> 358 ret = eng_inst.evaluate()
    360 if parsed_expr.assigner is None:
    361     if multi_line:

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/pandas/core/computation/engines.py:81, in AbstractEngine.evaluate(self)
     78     self.result_type, self.aligned_axes = align_terms(self.expr.terms)
     80 # make sure no names in resolvers and locals/globals clash
---> 81 res = self._evaluate()
     82 return reconstruct_object(
     83     self.result_type, res, self.aligned_axes, self.expr.terms.return_type
     84 )

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/pandas/core/computation/engines.py:122, in NumExprEngine._evaluate(self)
    120 scope = env.full_scope
    121 _check_ne_builtin_clash(self.expr)
--> 122 return ne.evaluate(s, local_dict=scope)

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/numexpr/necompiler.py:943, in evaluate(ex, local_dict, global_dict, out, order, casting, _frame_depth, **kwargs)
    941     return re_evaluate(local_dict=local_dict, _frame_depth=_frame_depth)
    942 else:
--> 943     raise e

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/numexpr/necompiler.py:851, in validate(ex, local_dict, global_dict, out, order, casting, _frame_depth, **kwargs)
    849 expr_key = (ex, tuple(sorted(context.items())))
    850 if expr_key not in _names_cache:
--> 851     _names_cache[expr_key] = getExprNames(ex, context)
    852 names, ex_uses_vml = _names_cache[expr_key]
    853 arguments = getArguments(names, local_dict, global_dict, _frame_depth=_frame_depth)

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/numexpr/necompiler.py:714, in getExprNames(text, context)
    713 def getExprNames(text, context):
--> 714     ex = stringToExpression(text, {}, context)
    715     ast = expressionToAST(ex)
    716     input_order = getInputOrder(ast, None)

File ~/opt/anaconda3/envs/obb/lib/python3.10/site-packages/numexpr/necompiler.py:274, in stringToExpression(s, types, context)
    272 no_whitespace = re.sub(r'\s+', '', s)
    273 if _forbidden_re.search(no_whitespace) is not None:
--> 274     raise ValueError(f'Expression {s} has forbidden control characters.')
    276 old_ctx = expressions._context.get_current_context()
    277 try:

ValueError: Expression (((strike) == (__pd_eval_local_call_strike_estimate)) & ((dte) == (__pd_eval_local_dte_estimate))) & (Series_1_0x200x390xe40x710x10x00x00x0) has forbidden control characters.

**Comment by jmaslek** [comment]
Are you still experiencing this?  If so, can you provide some more details?  Is it from pip?  Is it running in a jupyter notebook etc...

I am not reproducing
![Screenshot 2023-09-15 at 11 37 40 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/50a297fd-3a28-4f69-85c3-9ca69ab8e240)

**Comment by deeleeramone** [comment]
@daniellopez-2 - This is an error related to a bad version of `numexpr`, you almost certainly have `2.8.5` -  https://github.com/pydata/numexpr/issues/444 - and can be resolved by installing `2.8.6`
