### ISSUE TITLE
Futures Data that can utilize Volume Profile/ Market Profile, and harmonic rotations to build stats around. 

### ISSUE THREAD

**Issue by daymians** [OpenBB-finance/OpenBBTerminal#5466]
**What's the problem of not having this feature?**
I would become a member for life if a handful of tools were added to expand the futures side of things. I trade auction market theory and I know many individuals do as well. It'd be great to generate some stats and avg a handful of things like average IB range, average range of value, NQ's harmonic rotations, a few places generate this data so I'm sure there is use for it. 

**Describe the solution you would like**
There doesn't seem to be anyway to plot futures info as easily as it is to plot stock info. I know NDX is an things being looked for are more so related to the volume transacted within the market profile standpoint. Looking to build stats/edge around these things 

**Describe alternatives you've considered**
I have tried to generate something similar within phyton but can't seem to get the code down. the Math I am using seems to be incorrect. NDX could techincally work but am not sure if the data / volume would translate the same as futures contracts consider the trading of ETH and RTH for futures. 

**Additional information**
I have provided screenshots of some cool and unique ways I've seen this data be displayed. Would be great to somehow gather this information as it is fundamental to my prep along side many others.

 
![period_range](https://github.com/OpenBB-finance/OpenBBTerminal/assets/95890778/2b5f848f-d5a5-41cd-8f6c-36755d5713f2)
![rth_stats](https://github.com/OpenBB-finance/OpenBBTerminal/assets/95890778/8019756f-2760-429c-829e-d122f9ba447a)
<img width="247" alt="Screen Shot 2023-09-21 at 7 28 13 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/95890778/5ef61337-bef9-4759-9688-0cf56854a777">
![rth20_stats](https://github.com/OpenBB-finance/OpenBBTerminal/assets/95890778/632c5032-f402-49f4-8501-e022644ab23c)

[Convergent Trading Market Stats Report - ES SAMPLE REPORT.pdf](https://github.com/OpenBB-finance/OpenBBTerminal/files/12696091/Convergent.Trading.Market.Stats.Report.-.ES.SAMPLE.REPORT.pdf)

![period_range](https://github.com/OpenBB-finance/OpenBBTerminal/assets/95890778/e7728c36-376f-4fed-bcc5-e01192a6027c)
![rth_stats](https://github.com/OpenBB-finance/OpenBBTerminal/assets/95890778/134385e0-cd5c-423e-b43c-d62088cb8341)
![rth20_stats](https://github.com/OpenBB-finance/OpenBBTerminal/assets/95890778/32e0eb60-00c1-4c4c-ad71-a7b24af2a564)
<img width="247" alt="Screen Shot 2023-09-21 at 7 28 13 PM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/95890778/f68bfa7c-5fae-4a2f-924e-8d54a79b0d61">

**Comment by piiq** [comment]
Thanks for the feature request. I think this would make a good v4 extension. 

Do you have a data source in mind?

**Comment by daymians** [comment]
It’s tricky for data source — I was originally looking into trading view as
they have the most customizable options. I use NT8 and could grab data from
there but am not sure how to automate it so that it can do it every single
time. finplot here seems to have some value area charting abilities so that
was also my thought.

https://github.com/highfestiva/finplot

**Comment by rischkong** [comment]
This FR is great @daymians . Especially the OF Overviews. I would love to go with CQG (or IBKR/dxfeed) tickdata, but didn't looked into the openBB sources deep enough to hook into the dataConnectivity interfaces. Any hints @piiq ?

**Comment by deeleeramone** [comment]
> finplot here seems to have some value area charting abilities so that was also my thought. https://github.com/highfestiva/finplot

We have looked at Finplot before and it didn't meet our requirements, from a technical standpoint.  Although, this was before PyWry...maybe it is more feasible now with that in place.

**Comment by jcros81234** [comment]
I believe the data source on this information is through Sierra Charts Denali feed https://www.sierrachart.com/index.php?page=doc/DenaliExchangeDataFeed.php. I've talked to one of the OrderFlowLab owners about these pivots before and I believe he uses SierraChart desktop application to export the tick data and creates these locally. He's active on twitter if you want to ask questions @ES_F_Leo
