### ISSUE TITLE
[IMPROVE] Append existing `--sheet-name` with additional rows when exporting to XLSX

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5472]
What would be an awesome outcome is if:

`load aapl --start 2022-01-01 --end 2022-12-31 --weekly --export aapl.xlsx --sheet-name weekly`

could be appended to add more rows later:

`load aapl --start 2023-01-01 --weekly --export aapl.xlsx --sheet-name weekly`

The current behaviour is to create a new sheet-name, `weekly1`.

**Comment by Exterminator11** [comment]
Hey @deeleeramone, could I work on this issue?

**Comment by deeleeramone** [comment]
> Hey @deeleeramone, could I work on this issue?

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/05d5b2a4-f8a1-4fc0-ae59-6debb960a17f)

**Comment by Exterminator11** [comment]
Thank you for assigning this issue to me 😀. Could I please have a starting point to build up from.

**Comment by deeleeramone** [comment]
> Thank you for assigning this issue to me 😀. Could I please have a starting point to build up from so that I can get started by the earliest.

I think the place to start poking around is, `export_data()`, in, `/openbb_terminal/helper_funcs.py`.
