### ISSUE TITLE
[IMPROVE] Return `/stocks/search` with the unique identifier codes in Terminal.

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5505]
These columns do exist, so should be a relatively quick win.

```python
import financedatabase as fd
fd.Equities().data.columns
```

```
Index(['name', 'summary', 'currency', 'sector', 'industry_group', 'industry',
       'exchange', 'market', 'country', 'state', 'city', 'zipcode', 'website',
       'market_cap', 'isin', 'cusip', 'figi', 'composite_figi',
       'shareclass_figi'],
      dtype='object')
```

**Comment by rabroldan** [comment]
Hey there is this issue still up? I wanted to see if I can take it. if so can you please provide a bit more detail on /stocks/search. are you looking to return just the ticker symbol of a stock?

**Comment by deeleeramone** [comment]
> Hey there is this issue still up? I wanted to see if I can take it. if so can you please provide a bit more detail on /stocks/search. are you looking to return just the ticker symbol of a stock?

I don't see any PRs open for it, so I'm assuming it's still open!  All that really needs to happen is the existing function needs to return additional columns which already exist, instead of discarding them.

**Comment by AdwaitSalankar** [comment]
Hi! @deeleeramone 
Can you tell me which of these columns should be returned?
```
Index(['name', 'summary', 'currency', 'sector', 'industry_group', 'industry',
       'exchange', 'market', 'country', 'state', 'city', 'zipcode', 'website',
       'market_cap', 'isin', 'cusip', 'figi', 'composite_figi',
       'shareclass_figi'],
      dtype='object')
```

**Comment by deeleeramone** [comment]
current_columns + ['isin', 'cusip', 'figi', 'composite_figi','shareclass_figi']
