### ISSUE TITLE
[FR] V4 - Add FINRA Provider for ATS/OTC data

### ISSUE THREAD

**Issue by jmaslek** [OpenBB-finance/OpenBBTerminal#5514]

**Comment by ssahaxd** [comment]
Hi @jmaslek 
I'm uncertain about how this provider operates. Could you provide resources to help me get started?

Regarding FINRA ATS/OTC data, are you specifically referring to the following sources?

[ATS Data](https://otctransparency.finra.org/AtsData)
[OTC (Non-ATS) Data](https://otctransparency.finra.org/OtcData)
