### ISSUE TITLE
[Bug] Revenue History and Estimations table has incorrectly formatted dates

### ISSUE THREAD

**Issue by adrianmck1** [OpenBB-finance/OpenBBTerminal#5539]
Hi,

I am looking at revenue history and estimations data for various tickers in /stocks/fa/revfc and when the table is displayed, the FISCALYEAR column only shows the date "1970-01-01 00:00:02". The rest of the data in the table is fine. 

When I export the CSV file, it shows the correct year, so I'm guessing it's just some sort of formatting bug on fiscal year. 

I have attached an image showing the issue and a second image showing the data from the CSV file.

**To Reproduce**
stocks/fa
load <TICKER>
revfc

**Screenshots**
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/122870179/6b47914d-0db5-4ab8-ab79-a0321f775e77)

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/122870179/694bccb9-c5b7-4cc1-a5c6-c16b2dec49a5)

**Desktop (please complete the following information):**

- OS: Windows 10
- Python version: N/A
- OpenBB executable v3.2.2

**Additional context**
As well as the executable, I also have the SDK installed and it's fine, but it's not using the table viewer.

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/122870179/1888cb0d-bc97-4dff-a59e-5f1fac82615f)

Thanks.

**Comment by deeleeramone** [comment]
Nice find!

**Comment by sohinidas1092** [comment]
Hi @deeleeramone , can you please assign this to me?
