### ISSUE TITLE
[FR] Compare current YTD time series against X years historical average  

### ISSUE THREAD

**Issue by alphamindtech** [OpenBB-finance/OpenBBTerminal#5573]
**What's the problem of not having this feature?**
This is a way to compare most recent year performance to historical.

**Describe the solution you would like**
User should be able to select the historical years over the last decade or two to aggregate and have them plot against the current YTD time series.

**Additional information**
![Screenshot 2023-10-17 at 22 58 46](https://github.com/OpenBB-finance/OpenBBTerminal/assets/36191510/2ec19eea-9d6d-4e24-9ff9-ed083eb73b4e)

**Comment by deeleeramone** [comment]
To clarify what the historical average means in the context of your request, is this correct?

```
historical_average=sum([ytd for year in years])/years
```
