### ISSUE TITLE
[FR] Inter/Intra commodities spread charts

### ISSUE THREAD

**Issue by alphamindtech** [OpenBB-finance/OpenBBTerminal#5574]
**What's the problem of not having this feature?**
Much of the CTA world focus a lot on Calendar Spreads and Inter Commodity Spreads and it would be a shame to not have this feature.

**Describe the solution you would like**
Be able to select Futures Reference data (contract expiry going as far as 18 months from now) - the kind data that is available through Quandl (Now NasdaqData) and custom build synthetic series with user selected contract and corresponding multiplier. 

One should also be able to select multiple of these series to check their correlation within a matrix.

**Comment by deeleeramone** [comment]
> Be able to select Futures Reference data (contract expiry going as far as 18 months from now) - the kind data that is available through Quandl (Now NasdaqData) and custom build synthetic series with user selected contract and corresponding multiplier.

What Quandl series IDs are these?
