### ISSUE TITLE
[FR] OpenBB R package?

### ISSUE THREAD

**Issue by alphamindtech** [OpenBB-finance/OpenBBTerminal#5575]
**What's the problem of not having this feature?**
Any chance of getting a R package for OpenBB like we have fmpc R package for Financial Modelling Prep?

**Comment by deeleeramone** [comment]
https://prefix.dev/blog/introducing_rip - wanna try it out with this version? 

https://pypi.org/project/openbb/4.0.0a3/

**Comment by jmaslek** [comment]
@IgorWounds did some messing around with an R package.

**Comment by deeleeramone** [comment]
I'm curious to know if the conversion packages work:
[https://cran.r-hub.io/web/packages/reticulate/vignettes/python_packages.html](https://cran.r-hub.io/web/packages/reticulate/vignettes/python_packages.html)

`Any Python package you install from PyPI or Conda can be used from R with reticulate.`
