### ISSUE TITLE
[Bug] Rapidfuzz breaks OpenBB install - using old version 

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [OpenBB-finance/OpenBBTerminal#5577]
I have tried Python clean virtual environment & pipx to install OpenBB. Both install attempts break at Rapidfuzz install.

* If I do `pip install rapidfuzz`
it installs normally: Successfully installed rapidfuzz-3.4.0

* OpenBB seems to pull in an older version however, and the resulting compile error is most likely due to an old version being used:
```
Collecting rapidfuzz<2.0.0,>=1.1.1 (from openbb)
Using cached rapidfuzz-1.9.1.tar.gz (537 kB)
```

* Install then tries to do wheel build for some reason:
```
Building wheels for collected packages: rapidfuzz
  Building wheel for rapidfuzz (pyproject.toml): started
  Building wheel for rapidfuzz (pyproject.toml): finished with status 'error'
Failed to build rapidfuzz
```

* The compile problem:
`creating build/temp.linux-x86_64-cpython-311/src
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Iextern/rapidfuzz-cpp/ -Icapi/ -I/home/rsb/.local/pipx/venvs/openbb/include -I/usr/include/python3.11 -c src/cpp_process.cpp -o build/temp.linux-x86_64-cpython-311/src/cpp_process.o -O3 -std=c++14 -Wextra -Wall -Wconversion -g0 -DNDEBUG -pthread -DVERSION_INFO=\"1.9.1\"`

      src/cpp_process.cpp:253:12: fatal error: longintrepr.h: No such file or directory
        253 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1`

**Desktop (please complete the following information):**
- OS:  Ubuntu Luna
- Python version:  3.11

**Comment by deeleeramone** [comment]
Python 3.11 is not compatible, that's the problem.

**Comment by deeleeramone** [comment]
Closing because environment is using an unsupported version of Python.
