### ISSUE TITLE
[Bug] SDK v4 `pip` installation has different behavior than the `pip` docs

### ISSUE THREAD

**Issue by jjfantini** [OpenBB-finance/OpenBBTerminal#5599]
**Describe the bug**
After installing openbb SDK v4 with `pip install openbb[all]==4.0.0a3`, I could not access the available modules with `obb.stocks.etc...`. I needed to either use `obb.obb.stocks...` or `obb.sdk.stocks...`.

It is documented in the pip docs that it should be `obb.stocks...`

This is a discrepancy

- 🚨 I also needed  to `pip install openbb==4.0.0a3` to install the  openbb module as well as extensions

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior:
1. 
```powershell
conda create -n bootstrap python=3.10.12

pip install openbb[all]==4.0.0a3
pip install openbb==4.0.0a3
```
2. 
```python
import openbb as obb

obb.stocks.load()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 5
      2 working2 = obb.sdk.stocks.load("AAPL", provider="yfinance")
      4 # Suggested method Using pip docs
----> 5 suggested = obb.stocks.load("AAPL", provider="yfinance")

AttributeError: module 'openbb' has no attribute 'stocks'
```

**Screenshots**
![openbb-v4-installation-error](https://github.com/OpenBB-finance/OpenBBTerminal/assets/63276164/394ff862-455d-4bf2-b6ef-1d446f3f700e)

**Desktop (please complete the following information):**

- OS: Windows 11
- Python version: 3.10.12
- IDE: Cursor
- OpenBB Version: 4.0.0a3

**Additional context**
Add any other information that you think could be useful for us.

**Comment by jmaslek** [comment]
The import is 

from openbb import obb

Then you can access obb.stocks.
