### ISSUE TITLE
[IMPROVE] ADD NEW SVG LOGO FOR TWITTER/ X IN THE FOOTER

### ISSUE THREAD

**Issue by professssor** [OpenBB-finance/OpenBBTerminal#5600]
The footer in the  [](https://docs.openbb.co/ ) still uses the old twitter logo i.e. the bird , we can add the current X Logo

**Comment by Adidem23** [comment]
Please assign this issue to me I will fix it

**Comment by Adidem23** [comment]
Can you Give me location / path where I have to change logo
