### ISSUE TITLE
openBB macro events API failures 

### ISSUE THREAD

**Issue by msh855** [OpenBB-finance/OpenBBTerminal#5625]
Hi, 

I am running this command 

`events = openbb.economy.events(countries='United States', start_date='2022-10-01')`

and I get this error:

`There was an error connecting to the API. Please try again later.`

if I try a later date such as `'2023-10-01'` it works, but if I want to go more back in history it fails and it shows the error above. 

Can you please help 

Thanks

**Comment by deeleeramone** [comment]
Hello,

Try including an `end_date`, and keep the window of time narrow.

![Screenshot 2023-11-03 at 2 02 35 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/1c0cf56b-0090-400c-b81b-7b30b68bb973)

**Comment by msh855** [comment]
I don't think this is the issue. For instance, using both `start_date` and `end_date` but going way back in history I again get this error: 

```
events = openbb.economy.events(countries='United States', start_date='2000-10-01', end_date = '2023-11-02')
There was an error connecting to the API. Please try again later.
```

**Comment by deeleeramone** [comment]
> I don't think this is the issue. For instance, using both `start_date` and `end_date` but going way back in history I again get this error:
> 
> ```
> events = openbb.economy.events(countries='United States', start_date='2000-10-01', end_date = '2023-11-02')
> There was an error connecting to the API. Please try again later.
> ```

Try with much smaller windows of time.

**Comment by msh855** [comment]
of course it works with much smaller time window. I have already said this. 

But the point is not to find a window that would make the function to work. But have this function to download the data for the window that users choose.  In what I do, I want to go back as much back in history as possible.

**Comment by deeleeramone** [comment]
> of course it works with much smaller time window. I have already said this.
> 
> But the point is not to find a window that would make the function to work. But have this function to download the data for the window that users choose. In what I do, I want to go back as much back in history as possible.

I think this will be resolved here:

https://github.com/OpenBB-finance/OpenBBTerminal/pull/5225

The function will be more robust and allow greater throughput.
