### ISSUE TITLE
[Bug] Site Documentation 404

### ISSUE THREAD

**Issue by deadghost** [OpenBB-finance/OpenBBTerminal#5643]
**Describe the bug**
Your website has some 404s on https://my.openbb.co/app/terminal/installation and https://my.openbb.co/app/terminal/usage.

**To Reproduce**
Login and go to the above links.

**Screenshots**
![Screenshot_2023-11-01_04-01-01](https://github.com/OpenBB-finance/OpenBBTerminal/assets/1156996/84fdc85c-2d44-415f-abe1-6f710083c136)
![Screenshot_2023-11-01_04-00-34](https://github.com/OpenBB-finance/OpenBBTerminal/assets/1156996/02e2bd6d-7210-42fd-8ecb-a9bc959493fa)

**Desktop (please complete the following information):**

- OS: Linux
- Python version N/A

**Additional context**
Doubt it matters but this is through firefox.

**Comment by fadilparves** [comment]
Hi, yep it seems like the `/intro` is taking to the old docs path. I will update and fix this. Thank you
