### ISSUE TITLE
[Bug] `/fixedincome/estr --source ECB` - Returns blank with an x-axis label: "</html>"

### ISSUE THREAD

**Issue by deeleeramone** [OpenBB-finance/OpenBBTerminal#5662]
Recreate with:

```console
/fixedincome/estr --source ECB
```

![Screenshot 2023-11-03 at 10 29 20 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/c05fa4ce-6188-45f5-a4d5-74e1df46b5fb)

**Comment by jimwallace335** [comment]
Hi! I'm working on a fix for this issue. Could you please assign it to me.
