### ISSUE TITLE
Screener crash when sorting

### ISSUE THREAD

**Issue by jkennedyvz** [OpenBB-finance/OpenBBTerminal#5671]
**Describe the bug**
Screener crashes when sorting by a value with a slash 
/stocks/scr/ $ valuation --sort fwdp/e 

**To Reproduce**
/stocks/scr/ $ valuation --sort fwdp/e

**Screenshots**
<img width="949" alt="Screenshot 2023-11-05 at 1 41 02 AM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/65985482/f1b7e4b9-78e1-428f-9c68-38e55b563810">
<img width="1342" alt="Screenshot 2023-11-05 at 1 40 49 AM" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/65985482/89fa1ee3-881f-4a7b-a975-d84f487cd59e">

**Comment by deeleeramone** [comment]
Nice. Good find.
