### ISSUE TITLE
unbound variable

### ISSUE THREAD

**Issue by likecodingloveproblems** [OpenBB-finance/OpenBBTerminal#5674]
**Describe the bug**
If exception raised in [`client.get_order_book`](https://github.com/OpenBB-finance/OpenBBTerminal/blob/04f0a63abfbb35103c42737b08e875c0ff8ccefb/openbb_terminal/cryptocurrency/due_diligence/binance_model.py#L187) it crash as `market_book` is not defined!

**To Reproduce**
Every thing to make BinanceApi raise exception,

**Additional context**
I was reading your code, and find it as a developer, not the user :)
So maybe my report is not complete, sorry for that.

**Comment by deeleeramone** [comment]
The function seems to work as expected.

![Screenshot 2023-11-06 at 4 38 39 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/82f27b72-18fe-4d77-874e-229ceb9792be)

Bugs should be reported in the context of use and include the complete steps to reproduce, along with the complete error message(s).  Closing this issue.
