### ISSUE TITLE
[Bug] CSV export from `news` GUI doesn't work correctly.

### ISSUE THREAD

**Issue by mnicstruwig** [OpenBB-finance/OpenBBTerminal#5683]
**Describe the bug**
Exporting to CSV from the "news" GUI exports an incorrectly formatted CSV file.
Exporting directly from the terminal using the `--export csv` flag **does** however export the CSV file correctly.

**To Reproduce**
To reproduce bug:
- Launch terminal
- `stocks`
- `load TSLA`
- `news`
- Click "export" button with CSV selected.

However, what does work is: 
`news --export csv`

**Screenshots**
Broken export from the GUI:
[openbb_News_-_articles_20231108_113626.csv](https://github.com/OpenBB-finance/OpenBBTerminal/files/13296244/openbb_News_-_articles_20231108_113626.csv)

Working export from the terminal:
[20231108_133939_common_news_T_S_L_A_.csv](https://github.com/OpenBB-finance/OpenBBTerminal/files/13296245/20231108_133939_common_news_T_S_L_A_.csv)

**Desktop (please complete the following information):**

- OS: MacOS Sonoma
- Python 3.10

**Comment by HarisRasul12** [comment]
Hi I think I have a fix please assign it to me. thanks

**Comment by cottrell** [comment]
I think this was just quote protection right? It seems to be everywhere? @HarisRasul12
