### ISSUE TITLE
Enable a dashboard interface for model performance evaluation

### ISSUE THREAD

**Issue by jstammers** [OpenBB-finance/OpenBBTerminal#57]
The CLI for this app is incredibly useful and allows the user to carry out a lot of analysis.

Is there any planned work to develop a dashboard to visualise multiple analyses at once, or retrieve model performance metrics from previously trained models? For instance, I can see that `tensorboard` is listed as a dependency, but I can't see that being used anywhere within the project.

For quick and dirty dashboards, [streamlit](https://www.streamlit.io/) is often a good place to start.

If this is something you're looking for help with, I'd be happy to contribute.

**Comment by DidierRLopes** [comment]
Hey @jstammers,

I think this is a good idea, admittedly I haven't used streamlit before. I can read a bit about the topic during this week. What is your idea?

I'm always keen to have people contributing to the project! So feel free to work on it! If you want to discuss this in more details also, feel free to drop me a message on Linkedin or e-mail!

**Comment by DidierRLopes** [comment]
It has been 1 year, but we have now the terminal in a much better state.

I believe this could be done on our `jupyter/dashboards` menu. @jstammers not sure where you are at in your life, but if this is still of interest, this could potentially be really helpful for a lot of users :)

**Comment by jmaslek** [comment]
We now have tensorboard integrated and you can look at the evaluation.

Feel free to reopen if this does not meet your needs!
