### ISSUE TITLE
[FR] Publishing `openbb-ultima` package to PyPI

### ISSUE THREAD

**Issue by hjoaquim** [OpenBB-finance/OpenBBTerminal#5729]
There were some breaking changes going on the OpenBB Platform core, which make older versions (that are published on PyPI) of extensions break.
The necessary changes were made in all the extensions and new versions were published, all but [`openbb-ultima`](https://pypi.org/project/openbb-ultima/).

The version was already updated, so the only needed action is to publish to PyPI.

Tagging @Ultima-Insights @AdiSai asking for the extension to be published.

**Comment by AdiSai** [comment]
Just published 1.0.0b0 to PyPI @hjoaquim

**Comment by hjoaquim** [comment]
Quick test:

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/48914296/f27eed61-0871-4d32-b486-d765a80fecea)

Seems its working properly. Thank you @AdiSai
