### ISSUE TITLE
I had an error message while installing openbb 

### ISSUE THREAD

**Issue by Jacques2101** [OpenBB-finance/OpenBBTerminal#5759]
**Describe the bug**
I try to install openbb with `pip install "openbb[forecast]" --no-cache-dir`

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: Mac OS Sonema 
- Python version 3.10
-
**Additional context**
Here a part of screenshot 
<img width="1496" alt="Capture d’écran 2023-11-19 à 21 39 16" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/49912455/4930be50-2cbf-4c53-90ed-db888ea6251a">
<img width="1496" alt="Capture d’écran 2023-11-19 à 21 39 26" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/49912455/75d596d1-b55d-4efc-80fc-ffac8adf95d4">
<img width="1496" alt="Capture d’écran 2023-11-19 à 21 39 33" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/49912455/91d3daee-1298-4d43-bfec-13c0f22bbcbc">
<img width="1496" alt="Capture d’écran 2023-11-19 à 21 39 43" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/49912455/e27384fd-0fbf-428e-ac7e-669fc9484ada">
<img width="1496" alt="Capture d’écran 2023-11-19 à 21 39 56" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/49912455/9eb9ef76-b15e-4393-b6a1-3cc791612993">
<img width="1496" alt="Capture d’écran 2023-11-19 à 21 40 06" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/49912455/b19664a6-bb83-41c4-98e0-623811b3d74f">
<img width="1496" alt="Capture d’écran 2023-11-19 à 21 40 38" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/49912455/34782e44-6d31-4a83-a740-5159dc33e39e">

```
Failed to build prophet
ERROR: Could not build wheels for prophet, which is required to install pyproject.toml-based projects
```

**Comment by deeleeramone** [comment]
What is the output of:

- `conda info`
- `xcode-select -v`
- `conda list cmdstan`

**Comment by Jacques2101** [comment]
Here it is
Conda info

(obb) ***@***.*** ~ % conda info



     active environment : obb

    active env location : /Users/jacques/miniconda3/envs/obb

            shell level : 2

       user config file : /Users/jacques/.condarc

 populated config files :

          conda version : 23.10.0

    conda-build version : not installed

         python version : 3.11.5.final.0

       virtual packages : __archspec=1=m1

                          __osx=14.1.1=0

                          __unix=0=0

       base environment : /Users/jacques/miniconda3  (writable)

      conda av data dir : /Users/jacques/miniconda3/etc/conda

  conda av metadata url : None

           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64

                          https://repo.anaconda.com/pkgs/main/noarch

                          https://repo.anaconda.com/pkgs/r/osx-arm64

                          https://repo.anaconda.com/pkgs/r/noarch

          package cache : /Users/jacques/miniconda3/pkgs

                          /Users/jacques/.conda/pkgs

       envs directories : /Users/jacques/miniconda3/envs

                          /Users/jacques/.conda/envs

               platform : osx-arm64

             user-agent : conda/23.10.0 requests/2.31.0 CPython/3.11.5 Darwin/23.1.0 OSX/14.1.1 solver/libmamba conda-libmamba-solver/23.11.0 libmambapy/1.5.3

                UID:GID : 501:20

             netrc file : None

           offline mode : False


xcode-select -v

xcode-select version 2403.
conda list cmdstan

# packages in environment at /Users/jacques/miniconda3/envs/obb:

#

# Name                    Version                   Build  Channel





Cordialement
________________________
Jacques Tebeka
Mobile : +33 6 28 69 19 01


De : Danglewood ***@***.***>
Date : mardi, 21 novembre 2023 à 07:44
À : OpenBB-finance/OpenBBTerminal ***@***.***>
Cc : Jacques ***@***.***>, Author ***@***.***>
Objet : Re: [OpenBB-finance/OpenBBTerminal] I had an error message while installing openbb (Issue #5759)

What is the output of:

  *   conda info
  *   xcode-select -v
  *   conda list cmdstan

**Comment by Jacques2101** [comment]
Did you receive my answer ? Any idea of my problem ?
Thx


Cordialement
________________________
Jacques Tebeka
Mobile : +33 6 28 69 19 01


De : jacques tebeka ***@***.***>
Date : mardi, 21 novembre 2023 à 10:32
À : OpenBB-finance/OpenBBTerminal ***@***.***>
Objet : Re: [OpenBB-finance/OpenBBTerminal] I had an error message while installing openbb (Issue #5759)
Here it is
Conda info

(obb) ***@***.*** ~ % conda info



     active environment : obb

    active env location : /Users/jacques/miniconda3/envs/obb

            shell level : 2

       user config file : /Users/jacques/.condarc

 populated config files :

          conda version : 23.10.0

    conda-build version : not installed

         python version : 3.11.5.final.0

       virtual packages : __archspec=1=m1

                          __osx=14.1.1=0

                          __unix=0=0

       base environment : /Users/jacques/miniconda3  (writable)

      conda av data dir : /Users/jacques/miniconda3/etc/conda

  conda av metadata url : None

           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64

                          https://repo.anaconda.com/pkgs/main/noarch

                          https://repo.anaconda.com/pkgs/r/osx-arm64

                          https://repo.anaconda.com/pkgs/r/noarch

          package cache : /Users/jacques/miniconda3/pkgs

                          /Users/jacques/.conda/pkgs

       envs directories : /Users/jacques/miniconda3/envs

                          /Users/jacques/.conda/envs

               platform : osx-arm64

             user-agent : conda/23.10.0 requests/2.31.0 CPython/3.11.5 Darwin/23.1.0 OSX/14.1.1 solver/libmamba conda-libmamba-solver/23.11.0 libmambapy/1.5.3

                UID:GID : 501:20

             netrc file : None

           offline mode : False


xcode-select -v

xcode-select version 2403.
conda list cmdstan

# packages in environment at /Users/jacques/miniconda3/envs/obb:

#

# Name                    Version                   Build  Channel





Cordialement
________________________
Jacques Tebeka
Mobile : +33 6 28 69 19 01


De : Danglewood ***@***.***>
Date : mardi, 21 novembre 2023 à 07:44
À : OpenBB-finance/OpenBBTerminal ***@***.***>
Cc : Jacques ***@***.***>, Author ***@***.***>
Objet : Re: [OpenBB-finance/OpenBBTerminal] I had an error message while installing openbb (Issue #5759)

What is the output of:

  *   conda info
  *   xcode-select -v
  *   conda list cmdstan

**Comment by deeleeramone** [comment]
> Did you receive my answer ? Any idea of my problem ? Thx Cordialement

I see that you don't have `cmdstan` installed, this may be the issue.   You can try installing that with:

```
pip install cmdstanpy==1.1.0
```

If that does not resolve, you can attempt to update the environment from the YAML file:

```
conda env update -n obb --file https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/develop/build/conda/conda-3-10-env.yaml
```

And then try again to pip install OpenBB.

**Comment by Jacques2101** [comment]
I tried but get an error message. This is the end of the error message (it’s long!)


 note: This error originates from a subprocess, and is likely not a problem with pip.

  ERROR: Failed building wheel for prophet

  Building wheel for pyod (setup.py) ... done

  Created wheel for pyod: filename=pyod-1.1.2-py3-none-any.whl size=190289 sha256=0311eec0485f0a73c10d5a9c262e3567a30b721f1be7bc1f6d6edd55d897fadb

  Stored in directory: /private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-ephem-wheel-cache-n33vzkx7/wheels/81/1b/61/aa85b78c3c0c8871f4231e3f4a03bb23cecb7db829498380ee

  Building wheel for fugue-sql-antlr (setup.py) ... done

  Created wheel for fugue-sql-antlr: filename=fugue_sql_antlr-0.1.8-py3-none-any.whl size=158200 sha256=2a46a97b267403a7ef913a030b58ab0f7984f21219fd276cefad160edd92c59c

  Stored in directory: /private/var/folders/rh/z_zf2fdx3vl233pb2z6pxfkw0000gn/T/pip-ephem-wheel-cache-n33vzkx7/wheels/a4/2b/3e/8ac985ad100a8f27de940864344fe14f47bc3d2fed7f29bf70

Successfully built openai-whisper pyod fugue-sql-antlr

Failed to build prophet

ERROR: Could not build wheels for prophet, which is required to install pyproject.toml-based projects



Cordialement
________________________
Jacques Tebeka
Mobile : +33 6 28 69 19 01


De : Danglewood ***@***.***>
Date : mercredi, 22 novembre 2023 à 18:53
À : OpenBB-finance/OpenBBTerminal ***@***.***>
Cc : Jacques ***@***.***>, Author ***@***.***>
Objet : Re: [OpenBB-finance/OpenBBTerminal] I had an error message while installing openbb (Issue #5759)

Did you receive my answer ? Any idea of my problem ? Thx Cordialement

I see that you don't have cmdstan installed, this may be the issue. You can try installing that with:

pip install cmdstanpy==1.1.0

If that does not resolve, you can attempt to update the environment from the YAML file:

conda env update -n obb --file https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/develop/build/conda/conda-3-10-env.yaml

And then try again to pip install OpenBB.

**Comment by deeleeramone** [comment]
Which of the two did you try?  Did you also complete all of the "machine prep" instructions? 

![Screenshot 2023-11-22 at 2 29 49 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/d97a3a4a-5256-4634-a4da-0ee35b4d4e78)

At any rate, it will be a good idea to completely delete the environment you have created, clear you cache, and create a new environment using the YAML file.

**Comment by deeleeramone** [comment]
Since you posted this, we have released version 4.  If you don't specifically need the forecast library, it will be a much simpler installation. [https://docs.openbb.co/platform/installation](https://docs.openbb.co/platform/installation)

Otherwise, cache can be cleared with:

```
conda clean -a
pip cache purge
poetry cache clear PyPI
```

Installation instructions [here](https://docs.openbb.co/terminal/installation/pypi) describe the environment creation process.
