### ISSUE TITLE
Improving the rendering of the quarterly figures of the US government spending figures of department. 

### ISSUE THREAD

**Issue by dhruvmalik007** [OpenBB-finance/OpenBBTerminal#5764]
**What's the feature that should be improved?**
For the command /stocks/gov/qtrcontracts , the description of amount should've commas for the amount beyond the decimal denomination 

<img width="1434" alt="image" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/29146213/846a4f0e-af88-4784-84f7-1e9580266122">

here its confusing to describe the values . also they are not partitioned correctly as per the nomenclature  (in pairs of 3 ).

**Comment by deeleeramone** [comment]
Thanks for reporting, this was fixed recently: #5722 it has been merged to the `/develop` branch.
