### ISSUE TITLE
[Bug] OpenBB fails to install 

### ISSUE THREAD

**Issue by msh855** [OpenBB-finance/OpenBBTerminal#5826]
I am trying to install the openbb as per instructions but it fails. PyCharm cannot find the module

**Comment by jmaslek** [comment]
What command did you run that causes the error?

**Comment by msh855** [comment]
I am literary using the examples you have (e.g. to load bitcoin prices or equities ('SPY') 

`ModuleNotFoundError: No module named 'openbb'`

I have installed the library as per site's instructions (`pip install openbb`) in my new environment

**Comment by jmaslek** [comment]
Can you confirm the environment you installed to is activated?

Do you see that openbb is installed if you run 'pip list|grep openbb'

**Comment by jmaslek** [comment]
Ah.  So I think this is something with PyCharms python console and where it sources python from.  In your first screenshot - You have a QuantitativePortfolioManagement env, but if you look at the second screenshot, it is running from an env called fwiz_env. 

I believe you need to change this (more info here: https://www.jetbrains.com/help/pycharm/interactive-console.html)


To test my hypothesis, in your first screenshot do the following:

```
python
from openbb import obb
```

If this works, then you need to change the python console interpreter:

![Screenshot 2023-12-01 at 8 56 20 AM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/18151143/af859788-ab9f-4ae3-ba7b-fd3615f62fe3)

**Comment by msh855** [comment]
You hypothesis was correct. 

Everything were well aligned. For some reason the console was always reading from a different environment even if I have restarted or closed and opened again pyCharm. 

Solution:

Once in the right env and interpreter, I opened a new console and this fixed the issue.
