### ISSUE TITLE
[Bug] Input should be 'fmp', 'intrinio', 'polygon' or 'tiingo' [type=literal_error, input_value='yfinance', input_type=str]

### ISSUE THREAD

**Issue by fayssalelmofatiche** [OpenBB-finance/OpenBBTerminal#5903]
**Describe the bug**
yfinance is not supported when trying to load equity historical price data.

**To Reproduce**
df_daily = obb.equity.price.historical(symbol = "spy", provider="yfinance")
df_daily.to_df().head(1)

**Screenshots**
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/149014037/a70e94ee-a95a-4989-830b-b9bedc3003ca)

**Desktop (please complete the following information):**

- OS: MacOS M2
- Python version 3.11

**Comment by piiq** [comment]
Hi 👋 @fayssalelmofatiche 
yfinance is not shipped by default (at least not yet).
When you install openbb you can do `pip install openbb[yfinance]` to get openbb with yfinance

**Comment by fayssalelmofatiche** [comment]
Many thanks for the quick response, @piiq ! Indeed, installing openbb with all extensions and restarting the notebook did the trick  👍 .
