### ISSUE TITLE
[Bug] No module named 'openbb'

### ISSUE THREAD

**Issue by felix-git-hub** [OpenBB-finance/OpenBBTerminal#5905]
**Describe the bug**

I try to follow the example,  using "from openbb import obb" , however the jupyter report No module named 'openbb'

https://github.com/OpenBB-finance/OpenBBTerminal/blob/develop/examples/loadHistoricalPriceData.ipynb
ModuleNotFoundError: No module named 'openbb'

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
1、install openbb sdk https://docs.openbb.co/terminal/installation/pypi
conda env create -n obb --file https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/conda/conda-3-9-env.yaml
conda activate obb
pip install openbb==3.2.4 --no-cache-dir

2、try to get the version, get 3.2.4
from openbb_terminal.sdk import openbb
openbb.__version__

3、try to follow the exmaple code , get no module named openbb
from openbb import obb

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/70873830/75dd7352-7611-46f1-85f6-52899e393120)

**Comment by deeleeramone** [comment]
Hi,

The installation instructions associated with this notebook are: https://docs.openbb.co/platform/installation 

The version you are installing is associated with these: https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/examples/v3


We can improve the clarity, but the two versions are not interchangeable.

**Comment by felix-git-hub** [comment]
> Hi,
> 
> The installation instructions associated with this notebook are: https://docs.openbb.co/platform/installation
> 
> The version you are installing is associated with these: https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/examples/v3
> 
> We can improve the clarity, but the two versions are not interchangeable.
thanks a lot,
which version do you reccomand

**Comment by felix-git-hub** [comment]
it seems openbb platform is the 4th version of the openbb sdk ?

**Comment by deeleeramone** [comment]
> it seems openbb platform is the 4th version of the openbb sdk ?

Correct.  It has a new identity and new architecture.

**Comment by felix-git-hub** [comment]
many thanks
