### ISSUE TITLE
[Bug] cannot import name 'start_blocking_portal' from 'anyio'

### ISSUE THREAD

**Issue by PamirAlbayrak** [OpenBB-finance/OpenBBTerminal#5915]
I'm running my project with latest JupyterLab, on Python 3.11 with macOS with Apple Silicon.

It seems that [EDIT] since anyio version 3, the "start_blocking_portal" function was moved from the main anyio module to the anyio.from_thread (see https://anyio.readthedocs.io/en/stable/migration.html#blocking-portal-changes).

Using current openbb version lead to the following error (tried downgrading to 3.7.1 but problem persists):

> File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openbb_core/provider/utils/helpers.py:9
>       6 from typing import Awaitable, Callable, List, Literal, Optional, TypeVar, Union, cast
>       8 import requests
> ----> 9 from anyio import start_blocking_portal
>      10 from typing_extensions import ParamSpec
>      12 from openbb_core.provider.utils.client import (
>      13     ClientResponse,
>      14     ClientSession,
>      15     get_user_agent,

>ImportError: cannot import name 'start_blocking_portal' from 'anyio' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/anyio/__init__.py)

I'm not sure if this is a JupyterLab / Apple Silicon related problem. Ideally, changing "from anyio import start_blocking_portal" to "from anyio.from_thread import start_blocking_portal" in helpers.py could solve the problem in case latest anyio will be supported.

**Comment by deeleeramone** [comment]
> I'm running my project with latest JupyterLab, on Python 3.11 with macOS with Apple Silicon.
> 
> > File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openbb_core/provider/utils/helpers.py:9

This path suggests that you have installed directly to the system Python instead of in a virtual Python environment, which can easily create issues.

**Comment by PamirAlbayrak** [comment]
> > I'm running my project with latest JupyterLab, on Python 3.11 with macOS with Apple Silicon.
> > > File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openbb_core/provider/utils/helpers.py:9
> 
> This path suggests that you have installed directly to the system Python instead of in a virtual Python environment, which can easily create issues.

Tried both ways (virtual and direct) to no avail. Still seems to be a version related issue

**Comment by deeleeramone** [comment]
> Tried both ways (virtual and direct) to no avail. Still seems to be a version related issue

As a macOS user with Apple Silicon and Python 3.11 who also uses Jupyter, I have not experienced this issue.

**Comment by deeleeramone** [comment]
It actually appears that `anyio.from_thread.start_blocking_portal()` is deprecated.

```console
In [3]: import anyio

In [4]: anyio.from_thread.create_blocking_portal?
Signature: anyio.from_thread.create_blocking_portal() -> 'BlockingPortal'
Docstring:
Create a portal for running functions in the event loop thread from external threads.

Use this function in asynchronous code when you need to allow external threads access to the
event loop where your asynchronous code is currently running.

.. deprecated:: 3.0
    Use :class:`.BlockingPortal` directly.
```

vs.

```
In [1]: import anyio

In [2]: anyio.start_blocking_portal?
Signature:
anyio.start_blocking_portal(
    backend: 'str' = 'asyncio',
    backend_options: 'dict[str, Any] | None' = None,
) -> 'Generator[BlockingPortal, Any, None]'
Docstring:
Start a new event loop in a new thread and run a blocking portal in its main task.

The parameters are the same as for :func:`~anyio.run`.

:param backend: name of the backend
:param backend_options: backend options
:return: a context manager that yields a blocking portal

.. versionchanged:: 3.0
    Usage as a context manager is now required.
File:      ~/GitHub/Conda_M1/miniconda3/envs/obb-sdk4/lib/python3.11/site-packages/anyio/from_thread.py
Type:      function
```

**Comment by PamirAlbayrak** [comment]
> > Tried both ways (virtual and direct) to no avail. Still seems to be a version related issue
> 
> As a macOS user with Apple Silicon and Python 3.11 who also uses Jupyter, I have not experienced this issue. @piiq, have you come across this yet?

Found the issue! This was actually a PyCharm related issue - by default, it uses "notebook --no-browser" as command line argument for Jupyter:

<img width="712" alt="Screenshot 2024-01-06 at 0 58 58" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/133224686/09d607a3-18e9-4252-bb2c-c2957e5cfa9d">

The correct one is "lab --no-browser":

<img width="722" alt="Screenshot 2024-01-06 at 1 02 32" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/133224686/37538fb1-a13b-472c-8cc1-cb6e0be8b2cd">

By changing the argument PyCharm now correctly uses virtual environment with Jupyterlab.

It seems to be a known issue, but not yet fixed:

https://youtrack.jetbrains.com/issue/PY-61643/PyCharm-uses-the-wrong-interpreter-in-Jupyter-notebook

**Comment by deeleeramone** [comment]
> The correct one is "lab --no-browser"

That is very useful information, thank you!

**Comment by piiq** [comment]
I've encountered the same problem yesterday when I installed openbb into an existing (old) environment. 
When I recreated the environment the problem didn't appear again. 
Can you try that?

I will be able to post the exact versions of packages that I have
