### ISSUE TITLE
Want to access a running openBBTerminal container running on my local server through a web browser

### ISSUE THREAD

**Issue by phbrgnomo** [OpenBB-finance/OpenBBTerminal#6020]
Hello folks,

I just started setting up a home server, and have a persistent openbb terminal container running on it.

After creating these [scripts](https://github.com/OpenBB-finance/OpenBBTerminal/pull/6016) to streamline openbb terminal installation, now i am looking for a way to access the container through a web browse.

Currently my plan is:
- Build an alpine container with ttyd installed
- Execute this container to access the existing openbb container and serve it through the local network.

My current network isn't open to the web yet, but i am planning to do that at some point, so i can access it from outside my home.

Still working on implementing and testing this, but i would like to ask if the community have any suggestions on how i should do this (or even alternatives to using the ttyd container), and how to eventually secure the connection so i can access it from outside my home network. (I will probably setup a VPN, but might consider other options)

**Comment by piiq** [comment]
1. we need to sync on the terminal container itself. the v3 container you're using is entering retirement and it would be great if you don't "waste" time on features for v3. are you on discord?
2. check out tailscale for network. they have a free account that should be good for homelab style setups (up to 3 users, up to 100 client devices)

**Comment by phbrgnomo** [comment]
Thanks @piiq for the swift response.

I actually noticed i haven't joined the openbb discord yet. Thanks for the reminder.

About the v3 container being retired, can you point me to where the updates about this is being shared?

**Comment by piiq** [comment]
The v4 terminal is still in the works. There already is a v4 container that serves the api and has the environment bundled, but no cli app yet. Here https://github.com/OpenBB-finance/OpenBBTerminal/blob/develop/build/docker/api.dockerfile
