### ISSUE TITLE
[Bug] 3D Volatility Surface -- axes are off

### ISSUE THREAD

**Issue by ShivaSmith** [OpenBB-finance/OpenBBTerminal#6027]
**Describe the bug**
The axes tick positions of the 3D Volatility Surface graph do not match the data points.

**To Reproduce**
1) Load current AAPL options data (Sun., Feb. 4th, 2024).
2) Run the 'vsurf' command to generate the graph.

**Screenshots**
<img width="1110" alt="pywry_ETGGstq9Iv" src="https://github.com/OpenBB-finance/OpenBBTerminal/assets/13121054/f389ca9b-1f58-4775-ae31-11991a69ba9b">
See in attached screenshot, the marked peak has DTE value of 275, but the "shadow" of the selected peak falls *well* below 200.  The volatility value looks correct.  The Strike also appears to be off.  It reads 39 on the selected peak, but the "shadow" of the selected point falls in between 250 and 300.  The graph has not been rotated or translated in any way... just using the default appearance.

**Desktop (please complete the following information):**

- OS: Windows: 11
- Python version:  3.9.18

**Comment by deeleeramone** [comment]
Yes, the strike and DTE are labelled incorrectly there, thanks.

You might want to try `/dashboards/options` instead.

![Screenshot 2024-02-07 at 3 25 05 PM](https://github.com/OpenBB-finance/OpenBBTerminal/assets/85772166/e1ca7ef5-47fa-46ef-a20e-6ad144197683)
