### ISSUE TITLE
[IMPROVE] News feature needs to improve make sure the news is about the stocks and not random news.

### ISSUE THREAD

**Issue by WynandVStaden** [OpenBB-finance/OpenBBTerminal#6066]
News feature does keyword search instead of making sure that the news does relate to the stock.

So, I load a stock like BABA. And when I select news, it gives news of article titles with the keyword containing BABA instead of news about the stock. Currently the news I get for i.e. BABA is like about some Indian prince named BABA or something instead of about the stock.

Here is what I am talking about in the image, it gives random news instead of about the stock.
![baba_news](https://github.com/OpenBB-finance/OpenBBTerminal/assets/148979790/1895e007-fbff-471b-9cf0-6182d620cc0d)

**Comment by Chaitanyjanmale2** [comment]
i have made the changes to improve [#6066](https://github.com/OpenBB-finance/OpenBBTerminal/issues/6066) 
Please review and let me know if i have made some mistake as its my First ever contribution

**Comment by WynandVStaden** [comment]
Waiting for owner with write access to review request of [Chaitanyjanmale2](https://github.com/Chaitanyjanmale2) to be integrated. Then owner probably will close issue. Thanks.
