### ISSUE TITLE
[Bug] Blank charts

### ISSUE THREAD

**Issue by Murtrag** [OpenBB-finance/OpenBBTerminal#6080]
I just installed OpenBB, tried if it works, the CLI menu works, but the popup windows are blank

**To Reproduce**
$ sudo dnf install python3.9
$ virtualenv -p python3.9 env
$ git clone https://github.com/OpenBB-finance/OpenBBTerminal.git
$ source env/bin/activate
$  cd OpenBBTerminal/
$ python3 terminal.py

**Screenshots**
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/19934843/e9d379f4-40f7-48b5-bc6d-4e28bd013e85)

**Desktop (please complete the following information):**

- OS:  Fedora Linux 38 (Thirty Eight)

- Python version 3.9.18

**Comment by deeleeramone** [comment]
The steps you outlined doesn't include actually installing the packages.  What did you do to install? 

A Linux pre-requisite is: `sudo dnf install gtk3-devel webkit2gtk3-devel`

Did you install that?

**Comment by Murtrag** [comment]
I did: 
$ python3 install -r requirements.txt

I just followed the instructions for installation with conda, with same result at the end
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/19934843/0286452b-5973-479d-ae6a-e3de2fab2a9f)


sudo dnf install gtk3-devel webkit2gtk3-devel
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/19934843/58a538bd-d007-4f7b-8f95-713d32e3b9ee)

**Comment by deeleeramone** [comment]
hmm. It looks like you are in debug mode, in which case you should be able to get at the console inspector in the open window. I'm thinking that's the top-left icon from your screenshot.  Are there any errors showing in there? Does any other content display in the window or is it always blank from every function?

**Comment by Murtrag** [comment]
I started debug mode purposely to get some clues but I don't see nothing useful.
No, inspect element does not open anything, I tried also webbrowser shortcuts for console with errors and nothing.
Every window I open from the OpenBB terminal is like this.

What package is responsible for this windows? I could try different version of this package
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/19934843/4af3b71a-8a48-4279-b760-fa6255171698)

**Comment by deeleeramone** [comment]
The package is PyWry: https://github.com/OpenBB-finance/pywry/tree/main?tab=readme-ov-file#pywry-web-viewer

The only Linux setup I have is a Raspberry Pi and PyWry operates as expected, so I'm not sure how to recreate your issue. @hjoaquim, as a Linux user, are you able to shed any insight here?

**Comment by Murtrag** [comment]
Finally I gave up and set it up with a vagrant with VM, and it works just fine
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/19934843/c48a1c95-d569-4195-b273-31fe4dadcf6d)

Vagrantfile
```Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.ssh.forward_x11 = true
  config.vm.provider "virtualbox" do |v|
    v.memory = 5120 
    v.cpus = 2
    # v.gui = true
  end
  config.vm.provision "shell", inline: <<-SHELL
    # Dependencies
    sudo apt-get update
    sudo apt-get install -y --no-install-recommends xubuntu-desktop
    sudo apt-get install -y python3-pip python3-dev
    sudo apt-get install -y libgirepository1.0-dev libcairo2-dev
    sudo apt-get install -y pkg-config libfreetype6-dev libglib2.0-dev
    sudo apt-get install -y git

    # Create my aliases
    echo "alias install-env='/vagrant/install.sh'" >> /home/vagrant/.bashrc
    echo "alias openbb='python3 /vagrant/OpenBBTerminal/terminal.py'" >> /home/vagrant/.bashrc

    # Auto login
    echo "[Seat:*]" | sudo tee /etc/lightdm/lightdm.conf.d/20-autologin.conf
    echo "autologin-user=vagrant" | sudo tee -a /etc/lightdm/lightdm.conf.d/20-autologin.conf
    echo "autologin-user-timeout=0" | sudo tee -a /etc/lightdm/lightdm.conf.d/20-autologin.conf
    sudo reboot
  SHELL
end
```

install.sh
```
#!/usr/bin/env bash

sudo apt install -y libgdk-pixbuf2.0-dev libcairo2-dev libgirepository1.0-dev
sudo apt install -y libgtk-3-dev
sudo apt install -y libsoup2.4-dev
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
sudo apt-get install -y libjavascriptcoregtk-4.0-dev
sudo apt-get install -y libwebkit2gtk-4.0-dev
source "$HOME/.cargo/env"
cd /vagrant/OpenBBTerminal
pip3 install -r requirements.txt

```

![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/19934843/73d16de7-dcf2-422a-b608-207c35bf8724)

**Comment by bwagley** [comment]
Ran into a similar issue of blank charts on Fedora, with an nvidia GPU, when running the docker image. 

The workaround I found is to disable hardware acceleration for WebkitGTK: 
` WEBKIT_DISABLE_COMPOSITING_MODE=1` 

I suspect this is due to poor HW acceleration support from nvidia.

**Comment by hjoaquim** [comment]
I usually run into issues related with charting when using the VSCode integrated console - all should work using a native terminal.
