### ISSUE TITLE
[Bug] No historical price data with yfinance 

### ISSUE THREAD

**Issue by bm2609** [OpenBB-finance/OpenBBTerminal#6093]
Hi,

I am using obb version 4.0.1 and suddenly, fetching price data with ``yfinance`` does not work. Here is a screenshot:

![screenshot](https://github.com/OpenBB-finance/OpenBBTerminal/assets/49444885/c4f048b3-f686-4717-a73d-a7ddd358d654)

- OS: Windows 10
- Python version 3.10

Best

**Comment by jmaslek** [comment]
Update the openbb package (`pip install -U openbb`):

```
>>> obb.equity.price.historical(symbol="spy", provider="yfinance").to_df()
              open    high     low   close     volume  dividends  stock_splits  capital_gains
date                                                                                         
2023-02-21  403.06  404.16  398.82  399.09   82655900        0.0           0.0            0.0
2023-02-22  399.52  401.13  397.02  398.54   83742300        0.0           0.0            0.0
2023-02-23  401.56  402.20  396.25  400.66   96242400        0.0           0.0            0.0
2023-02-24  395.42  397.25  393.64  396.38  108194400        0.0           0.0            0.0
```

**Comment by GreenbackBoogie2** [comment]
I had the same issue as bm2609.  I ran the update package and now I'm receiving a 'ModuleNotFoundError: No module named 'openbb_core.provider.standard_models.european_index_constituents'.  I'm new to Python and OpenBB.  While OpenBB Core appears to have been installed I don't see that this specific module was installed.  Any guidance on how to check this would be appreciated.  Thanks.

**Comment by jmaslek** [comment]
> I had the same issue as bm2609. I ran the update package and now I'm receiving a 'ModuleNotFoundError: No module named 'openbb_core.provider.standard_models.european_index_constituents'. I'm new to Python and OpenBB. While OpenBB Core appears to have been installed I don't see that this specific module was installed. Any guidance on how to check this would be appreciated. Thanks.

If you run `pip list|grep openbb` what do you get?  Do you get that error on `from openbb import obb` ?

**Comment by GreenbackBoogie2** [comment]
When I run pip list|grep openbb it shows the following is installed:
openbb                    4.1.4
openbb-alpha-vantage      1.1.2
openbb-benzinga           1.1.2
openbb-biztoc             1.1.2
openbb-cboe               1.1.2
openbb-charting           2.0.0
openbb-commodity          1.0.0
openbb-core               1.1.2
openbb-crypto             1.1.2
openbb-currency           1.1.2
openbb-derivatives        1.1.2
openbb-ecb                1.1.2
openbb-econometrics       1.1.2
openbb-economy            1.1.2
openbb-equity             1.1.2
openbb-etf                1.1.2
openbb-federal-reserve    1.1.2
openbb-finra              1.1.2
openbb-finviz             1.0.1
openbb-fixedincome        1.1.2
openbb-fmp                1.1.2
openbb-fred               1.1.2
openbb-government-us      1.1.2
openbb-index              1.1.2
openbb-intrinio           1.1.2
openbb-nasdaq             1.1.3
openbb-news               1.1.2
openbb-oecd               1.1.2
openbb-polygon            1.1.2
openbb-quantitative       1.1.2
openbb-regulators         1.1.2
openbb-sec                1.1.2
openbb-seeking-alpha      1.1.2
openbb-stockgrid          1.1.2
openbb-technical          1.1.3
openbb-tiingo             1.1.2
openbb-tradingeconomics   1.1.2
openbb-wsj                1.1.2
openbb-yfinance           1.1.2

I also went back and ran pip install "openbb[all]".  After going through all that I now receive the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 10
      3 price_data = {}
      4 for symbol in symbols:
      5     price_data[symbol] = obb.equity.price.historical(
      6         symbol, 
      7         start_date=start_date, 
      8         end_date=today,
      9         provider="yfinance"
---> 10     ).close

File ~/anaconda3/envs/my_quant_lab/lib/python3.10/site-packages/pydantic/main.py:767, in BaseModel.__getattr__(self, item)
    764     return super().__getattribute__(item)  # Raises AttributeError if appropriate
    765 else:
    766     # this is the current error
--> 767     raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')

AttributeError: 'OBBject' object has no attribute 'close'

I appreciate the help!

**Comment by jmaslek** [comment]
That's because what is returned from the functions are our custom OBBject (openBB object heh).

If you want to access it like pandas, you can do .to_df().close

You can also set a preference on how to always return as a dataframe

**Comment by bm2609** [comment]
Sorry, but after updating to version 4.1.4, I still get the error (see screenshots). Is something wrong with my setting?

![screenshot1](https://github.com/OpenBB-finance/OpenBBTerminal/assets/49444885/2ea3a243-1b98-478c-b5e5-1cfac29bf742)
![screenshot2](https://github.com/OpenBB-finance/OpenBBTerminal/assets/49444885/30ad3744-ebd0-4767-aab2-46a2bfc58efe)

**Comment by jmaslek** [comment]
Did you restart the kernel after updating?  Otherwise, there may be some issue with a cached package.  Can you try the following from a restarted kernel:

```
import openbb
openbb.build()
```

Then restart the kernel again and try the price

**Comment by GreenbackBoogie2** [comment]
Hi James - using .to_df().close fixed the issue for me.  Thank you.
