### ISSUE TITLE
[Bug] unable to register for account

### ISSUE THREAD

**Issue by Fritzie5** [OpenBB-finance/OpenBBTerminal#6352]
**Describe the bug**
When I try to register  for an account I get message "oauth login failed". I tried registering through email, discord, and GitHub. All produce same error. 

**To Reproduce**
Creating account submit than error occurs. 

**Screenshots**
If you are running the terminal using the conda version please
rerun the terminal with `python terminal.py --debug`, and then
recreate your issue. Then include a screenshot of the entire 
error printout.

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by deeleeramone** [comment]
Hello,

Can you please try again? We believe the issue was resolved. Thanks!

**Comment by Fritzie5** [comment]
Yes I tried again this morning and it seemed to work. Thanks!
