### ISSUE TITLE
seeking alpha usage query

### ISSUE THREAD

**Issue by 99snowleopards** [OpenBB-finance/OpenBBTerminal#6455]
**What's the problem of not having this feature?**
this pypi project shows that there us an openbb extension for seeking alpha, but I cannot find sufficient documentation and examples, and the source code for the project:

https://pypi.org/project/openbb-seeking-alpha/

**Describe the solution you would like**
I'd like to use the extension to import data from seeking alpha into a pandas dataframe

I'd appreciate any examples. Thank you

**Comment by deeleeramone** [comment]
Hi there,

The source code is located within the repository - https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_platform/providers/seeking_alpha/openbb_seeking_alpha - and as you can see, there's not a lot going on.

This PR - https://github.com/OpenBB-finance/OpenBBTerminal/pull/6461 - proposes adding the forward EPS and revenue estimates, but it sounds like you are looking for a Python client for consuming their entire API. If so, this is not that. All provider extensions are mapped to common router endpoints and their implementations are detailed in the Reference section of the documentation pages: https://docs.openbb.co/platform/reference/equity/calendar/earnings

**Comment by 99snowleopards** [comment]
thank you for the details - it'd be awesome if there was more comprehensive integration with seeking alpha from a Python client - seeking alpha has lots of useful information in their portfolios and comparisons and it'd be great to import that directly into a dataframe.

thank you again
