### ISSUE TITLE
[FR] renaming openBB - the bold idea 

### ISSUE THREAD

**Issue by qmarsun** [OpenBB-finance/OpenBBTerminal#6467]
**What's the problem of not having this feature?**
As we are gaining more populate sometime I prefer to rename something different 
anything founder can name but the goal is not want to have any reference to Bloomberg.
Linux is not named OpenWindows/OpenMac/OpenSolaris etc
Same Linux is stand by Linux strength.  similar I perfer "this open source financial" software 
stand by strength.

**Describe the solution you would like**
Unique name is very important 

**Describe alternatives you've considered**
N/A

**Additional information**
N/A

**Comment by DidierRLopes** [comment]
https://www.openbb.design/9242dc28c/p/989cf5-company-name

**Comment by qmarsun** [comment]
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/105653354/e6327052-7311-47ff-ad5f-cfeacb85a83f)

**Comment by qmarsun** [comment]
its oneword two meaning .  but initially we had reference 
again I leaving to founder of this product to make  final decision. 
but definitely unambiguous unique name is the  one I vote for :)

**Comment by qmarsun** [comment]
As of 
commit aefd92102726e27e8ba5191d4ee6ee6e60ea2c60
Date:   Fri May 24 12:22:52 2024 -0700
Here is the list of places Bloomberg word appear. 
I look for day that 
our code base with zero reference to the word Bloomberg.this is also showing to the 
world this source code doesn't have reference 
[list_of_reference_to_bloomberg_openBB_code.txt](https://github.com/OpenBB-finance/OpenBBTerminal/files/15464388/list_of_reference_to_bloomberg_openBB_code.txt)
