### ISSUE TITLE
[Bug] Missing docker-compose.yaml and docker-compose.x11.yaml files

### ISSUE THREAD

**Issue by gobpuH** [OpenBB-finance/OpenBBTerminal#6522]
**Describe the bug**
Docker compose files "docker-compose.yaml" and "docker-compose.yaml" are missing in source tree.

**To Reproduce**
`curl https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.yaml`
`curl https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.x11.yaml`
The commands above terminate with "404: Not Found".

**Desktop (please complete the following information):**

- OS: Linux 6.6.32-1-MANJARO
- Python version 3.12.3

**Additional context**
I'm trying to install "openBB terminal" via Docker following "Linux" section of this page:
[OpenBB Docker installation](https://docs.openbb.co/terminal/installation/docker)

**Comment by gobpuH** [comment]
Alternative way to reproduce the problem:
[docker-compose.yaml](https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.yaml)
[docker-compose.x11.yaml](https://raw.githubusercontent.com/OpenBB-finance/OpenBBTerminal/main/build/docker/docker-compose.x11.yaml)

**Comment by deeleeramone** [comment]
Hello, 

These files were removed intentionally. Installation the legacy Terminal application is no longer supported via this method, and it is not really an appropriate vehicle for use of the application.

You can install the Platform as Fast API in a Docker container: https://docs.openbb.co/platform/installation#docker

CLI operations are not supported for Docker.

**Comment by gobpuH** [comment]
Many thanks for you fast reply.
