### ISSUE TITLE
Stock Price download error

### ISSUE THREAD

**Issue by tairan0509** [OpenBB-finance/OpenBBTerminal#6554]
**Describe the bug**
HI there, I am using v3.2 as a beginner. When downloading stock price for my filtered tickers, there's "unexpected keyword argument 'show_errors' " below that prevent data to be shown. My codes are attached below. 
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/55723935/7e5a0100-7865-4e1a-a262-b146f548d5d6)

**To Reproduce**
below is my step:
from openbb_terminal.sdk import openbb as obb
new_highs = obb.stocks.screener.screener_data("new_high")
data = obb.economy.index(new_highs['Ticker'].tolist(), start_date = '2016-01-01', end_date= '2019-12-31')

**Screenshots**
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/55723935/bf446aa7-c476-4815-bef0-09c9b14e7bfb)

**Desktop (please complete the following information):**

- OS: Mac M1
- Python version: 3.9

**Additional context**
I have also tried openbb v4.3, but there's another error saying "equity" attribute not found, though following the GitHub example
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/55723935/551e7794-3889-4491-ad1d-af15396316f4)
  
And didn't find much relevant discussion in issue tracker. Can you help? thank you

**Comment by deeleeramone** [comment]
Hi there, this isn't a bug, you are using an obsolete version and applying syntax that is only valid from 4+, the new version. Please uninstall and use the latest version - [https://docs.openbb.co/platform/installation](https://docs.openbb.co/platform/installation)
